In [1]:
import enum
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from timm.layers import Conv2dSame
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.persistence_manager import PersistenceManager
from internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNETV2_S

In [4]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=True,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_efficientnet_b0_model()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        clf_module, clf_name = get_classifier_module(model)
        for param in clf_module.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effb0_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effb0_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")

# tf_efficientnetv2_s.in21k

In [5]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/10


    t_loss=4.3239 | F1(macro)=0.2659 | Acc=0.2672


Confusion matrix:
 [[12 10 14  5]
 [ 9  7  9  7]
 [ 1 13 10  6]
 [ 4  2  4  4]]
Train  loss=4.3239 acc=0.2672 f1=0.2659 | Val loss=5.8243 acc=0.2821 f1=0.2744
  🔥 New best F1: 0.2744 – model saved.

Epoch 2/10


    t_loss=3.7253 | F1(macro)=0.2673 | Acc=0.2672


Confusion matrix:
 [[ 8 13  7 13]
 [ 8  7  8  9]
 [ 5 14  6  5]
 [ 3  4  4  3]]
Train  loss=3.7253 acc=0.2672 f1=0.2673 | Val loss=6.1168 acc=0.2051 f1=0.2002

Epoch 3/10


    t_loss=3.7395 | F1(macro)=0.2666 | Acc=0.2672


Confusion matrix:
 [[17  8  5 11]
 [ 8  6  9  9]
 [ 3  9  7 11]
 [ 3  4  1  6]]
Train  loss=3.7395 acc=0.2672 f1=0.2666 | Val loss=4.8764 acc=0.3077 f1=0.2950
  🔥 New best F1: 0.2950 – model saved.

Epoch 4/10


    t_loss=3.7847 | F1(macro)=0.2928 | Acc=0.2953


Confusion matrix:
 [[10 11 14  6]
 [ 8  7 10  7]
 [ 9  7  8  6]
 [ 2  4  3  5]]
Train  loss=3.7847 acc=0.2953 f1=0.2928 | Val loss=4.9200 acc=0.2564 f1=0.2561

Epoch 5/10


    t_loss=3.1625 | F1(macro)=0.2992 | Acc=0.2996


Confusion matrix:
 [[10 13 11  7]
 [ 4 11  8  9]
 [ 8  9 12  1]
 [ 3  2  3  6]]
Train  loss=3.1625 acc=0.2996 f1=0.2992 | Val loss=4.9739 acc=0.3333 f1=0.3327
  🔥 New best F1: 0.3327 – model saved.

Epoch 6/10


    t_loss=3.3434 | F1(macro)=0.2680 | Acc=0.2694


Confusion matrix:
 [[10 11 10 10]
 [ 7  7  9  9]
 [ 1  9  9 11]
 [ 1  3  2  8]]
Train  loss=3.3434 acc=0.2694 f1=0.2680 | Val loss=5.0245 acc=0.2906 f1=0.2917

Epoch 7/10


    t_loss=3.3122 | F1(macro)=0.2939 | Acc=0.2974


Confusion matrix:
 [[ 8  7 19  7]
 [ 9 10  8  5]
 [ 7  8  9  6]
 [ 2  5  3  4]]
Train  loss=3.3122 acc=0.2974 f1=0.2939 | Val loss=4.6341 acc=0.2650 f1=0.2611

Epoch 8/10


    t_loss=2.9608 | F1(macro)=0.3089 | Acc=0.3103


Confusion matrix:
 [[11 10 11  9]
 [ 8  8 11  5]
 [10  5 10  5]
 [ 1  4  4  5]]
Train  loss=2.9608 acc=0.3103 f1=0.3089 | Val loss=4.5477 acc=0.2906 f1=0.2868

Epoch 9/10


    t_loss=3.1266 | F1(macro)=0.2836 | Acc=0.2845


Confusion matrix:
 [[ 9 12 11  9]
 [ 6  7  9 10]
 [11 10  6  3]
 [ 2  2  3  7]]
Train  loss=3.1266 acc=0.2845 f1=0.2836 | Val loss=4.9606 acc=0.2479 f1=0.2530

Epoch 10/10


    t_loss=3.2048 | F1(macro)=0.2622 | Acc=0.2629


Confusion matrix:
 [[ 7 12 11 11]
 [ 6  5 13  8]
 [ 6  7  9  8]
 [ 2  3  5  4]]
Train  loss=3.2048 acc=0.2629 f1=0.2622 | Val loss=5.1370 acc=0.2137 f1=0.2094
Restored best Stage 1 weights for fold 0 (F1=0.3327)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=3.2355 | F1(macro)=0.2892 | Acc=0.2888


Confusion matrix:
 [[ 9  7 10 15]
 [ 2  5 13 12]
 [ 7  1 11 11]
 [ 1  0  5  8]]
Train  loss=3.2355 acc=0.2888 f1=0.2892 | Val loss=4.2023 acc=0.2821 f1=0.2769
  🔥 New best F1: 0.2769 – model saved.

Epoch 2/15


    t_loss=2.2427 | F1(macro)=0.3718 | Acc=0.3879


Confusion matrix:
 [[ 8  3 17 13]
 [ 7  3 10 12]
 [ 6  1 15  8]
 [ 2  1  5  6]]
Train  loss=2.2427 acc=0.3879 f1=0.3718 | Val loss=4.1191 acc=0.2735 f1=0.2540

Epoch 3/15


    t_loss=1.9212 | F1(macro)=0.3988 | Acc=0.4095


Confusion matrix:
 [[14  8 13  6]
 [11  9  3  9]
 [ 9  5  7  9]
 [ 3  3  3  5]]
Train  loss=1.9212 acc=0.4095 f1=0.3988 | Val loss=3.0978 acc=0.2991 f1=0.2893
  🔥 New best F1: 0.2893 – model saved.

Epoch 4/15


    t_loss=1.7587 | F1(macro)=0.4329 | Acc=0.4526


Confusion matrix:
 [[ 8 11 16  6]
 [ 5  9  9  9]
 [ 2 10  6 12]
 [ 3  6  4  1]]
Train  loss=1.7587 acc=0.4526 f1=0.4329 | Val loss=3.2543 acc=0.2051 f1=0.1920

Epoch 5/15


    t_loss=1.6170 | F1(macro)=0.4496 | Acc=0.4612


Confusion matrix:
 [[ 9 14  9  9]
 [ 8  9  5 10]
 [ 6  7  8  9]
 [ 6  2  1  5]]
Train  loss=1.6170 acc=0.4612 f1=0.4496 | Val loss=2.7366 acc=0.2650 f1=0.2633

Epoch 6/15


    t_loss=1.3598 | F1(macro)=0.4563 | Acc=0.4784


Confusion matrix:
 [[ 9 14 11  7]
 [ 9  7  6 10]
 [ 4  4 11 11]
 [ 7  2  2  3]]
Train  loss=1.3598 acc=0.4784 f1=0.4563 | Val loss=2.7078 acc=0.2564 f1=0.2486

Epoch 7/15


    t_loss=1.2697 | F1(macro)=0.5201 | Acc=0.5259


Confusion matrix:
 [[ 9 11 17  4]
 [ 7  9  9  7]
 [ 5  6 15  4]
 [ 4  4  5  1]]
Train  loss=1.2697 acc=0.5259 f1=0.5201 | Val loss=3.1807 acc=0.2906 f1=0.2561

Epoch 8/15


    t_loss=1.0915 | F1(macro)=0.5586 | Acc=0.5797


Confusion matrix:
 [[16 10  8  7]
 [11  5  7  9]
 [14  3  7  6]
 [ 5  4  4  1]]
Train  loss=1.0915 acc=0.5797 f1=0.5586 | Val loss=2.7977 acc=0.2479 f1=0.2143

Epoch 9/15


    t_loss=1.1967 | F1(macro)=0.5606 | Acc=0.5625


Confusion matrix:
 [[15  7 13  6]
 [ 3  4 13 12]
 [ 1  3 15 11]
 [ 3  2  3  6]]
Train  loss=1.1967 acc=0.5625 f1=0.5606 | Val loss=2.5441 acc=0.3419 f1=0.3233
  🔥 New best F1: 0.3233 – model saved.

Epoch 10/15


    t_loss=1.0557 | F1(macro)=0.5773 | Acc=0.5884


Confusion matrix:
 [[12  5 14 10]
 [ 8  7  8  9]
 [ 9  2 13  6]
 [ 6  1  3  4]]
Train  loss=1.0557 acc=0.5884 f1=0.5773 | Val loss=2.5973 acc=0.3077 f1=0.2955

Epoch 11/15


    t_loss=1.0307 | F1(macro)=0.6133 | Acc=0.6185


Confusion matrix:
 [[ 7 14  8 12]
 [ 7  6  8 11]
 [ 6  2 13  9]
 [ 4  1  3  6]]
Train  loss=1.0307 acc=0.6185 f1=0.6133 | Val loss=2.6432 acc=0.2735 f1=0.2709

Epoch 12/15


    t_loss=0.9603 | F1(macro)=0.6334 | Acc=0.6444


Confusion matrix:
 [[12 12 13  4]
 [ 6  7  7 12]
 [ 8  3 16  3]
 [ 4  2  6  2]]
Train  loss=0.9603 acc=0.6444 f1=0.6334 | Val loss=2.6426 acc=0.3162 f1=0.2867

Epoch 13/15


    t_loss=1.0275 | F1(macro)=0.6069 | Acc=0.6207


Confusion matrix:
 [[11  9 15  6]
 [10  7 11  4]
 [ 7  5 12  6]
 [ 4  4  4  2]]
Train  loss=1.0275 acc=0.6207 f1=0.6069 | Val loss=2.7159 acc=0.2735 f1=0.2513

Epoch 14/15


    t_loss=0.9671 | F1(macro)=0.6525 | Acc=0.6595


Confusion matrix:
 [[ 9 10 16  6]
 [12  4  7  9]
 [ 8  3 14  5]
 [ 4  2  5  3]]
Train  loss=0.9671 acc=0.6595 f1=0.6525 | Val loss=2.4301 acc=0.2564 f1=0.2378

Epoch 15/15


    t_loss=0.9216 | F1(macro)=0.6291 | Acc=0.6422


Confusion matrix:
 [[ 6 16 15  4]
 [ 6  8  7 11]
 [11  3  9  7]
 [ 1  4  5  4]]
Train  loss=0.9216 acc=0.6422 f1=0.6291 | Val loss=2.4861 acc=0.2308 f1=0.2278

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/10


    t_loss=4.3896 | F1(macro)=0.2761 | Acc=0.2774


Confusion matrix:
 [[11  8  9 12]
 [ 9  6  8  9]
 [ 8  5 10  7]
 [ 6  0  3  5]]
Train  loss=4.3896 acc=0.2774 f1=0.2761 | Val loss=5.0923 acc=0.2759 f1=0.2697
  🔥 New best F1: 0.2697 – model saved.

Epoch 2/10


    t_loss=3.8108 | F1(macro)=0.2883 | Acc=0.2925


Confusion matrix:
 [[ 9  6 12 13]
 [ 9  6  7 10]
 [ 7  3 11  9]
 [ 4  3  5  2]]
Train  loss=3.8108 acc=0.2925 f1=0.2883 | Val loss=5.4950 acc=0.2414 f1=0.2307

Epoch 3/10


    t_loss=3.5122 | F1(macro)=0.2772 | Acc=0.2774


Confusion matrix:
 [[ 7  5 21  7]
 [ 8  6 14  4]
 [ 4  6 15  5]
 [ 3  2  4  5]]
Train  loss=3.5122 acc=0.2774 f1=0.2772 | Val loss=5.1580 acc=0.2845 f1=0.2760
  🔥 New best F1: 0.2760 – model saved.

Epoch 4/10


    t_loss=3.5076 | F1(macro)=0.2957 | Acc=0.2989


Confusion matrix:
 [[11  6  9 14]
 [ 7  6  7 12]
 [11  4  8  7]
 [ 4  0  2  8]]
Train  loss=3.5076 acc=0.2989 f1=0.2957 | Val loss=4.8937 acc=0.2845 f1=0.2820
  🔥 New best F1: 0.2820 – model saved.

Epoch 5/10


    t_loss=3.3981 | F1(macro)=0.2620 | Acc=0.2688


Confusion matrix:
 [[17  8  9  6]
 [12  6  6  8]
 [13  4  6  7]
 [ 7  0  2  5]]
Train  loss=3.3981 acc=0.2688 f1=0.2620 | Val loss=5.0325 acc=0.2931 f1=0.2746

Epoch 6/10


    t_loss=3.1024 | F1(macro)=0.2756 | Acc=0.2796


Confusion matrix:
 [[ 9  8 11 12]
 [ 7  5 11  9]
 [11  3  8  8]
 [ 3  5  4  2]]
Train  loss=3.1024 acc=0.2796 f1=0.2756 | Val loss=5.4397 acc=0.2069 f1=0.1962

Epoch 7/10


    t_loss=2.9247 | F1(macro)=0.3099 | Acc=0.3183


Confusion matrix:
 [[16  3 12  9]
 [10  8  6  8]
 [ 8  5  8  9]
 [ 1  5  4  4]]
Train  loss=2.9247 acc=0.3183 f1=0.3099 | Val loss=4.5576 acc=0.3103 f1=0.2943
  🔥 New best F1: 0.2943 – model saved.

Epoch 8/10


    t_loss=2.9772 | F1(macro)=0.2961 | Acc=0.3011


Confusion matrix:
 [[ 6  4 16 14]
 [ 8  8  7  9]
 [ 6  5  7 12]
 [ 0  1  4  9]]
Train  loss=2.9772 acc=0.3011 f1=0.2961 | Val loss=4.4916 acc=0.2586 f1=0.2623

Epoch 9/10


    t_loss=3.0047 | F1(macro)=0.3055 | Acc=0.3054


Confusion matrix:
 [[ 7 11  9 13]
 [ 6  8  5 13]
 [ 8  7  4 11]
 [ 1  2  3  8]]
Train  loss=3.0047 acc=0.3054 f1=0.3055 | Val loss=4.7152 acc=0.2328 f1=0.2301

Epoch 10/10


    t_loss=2.8754 | F1(macro)=0.3203 | Acc=0.3226


Confusion matrix:
 [[ 7  5 12 16]
 [ 6 10  4 12]
 [ 9  6  6  9]
 [ 2  3  1  8]]
Train  loss=2.8754 acc=0.3226 f1=0.3203 | Val loss=4.7963 acc=0.2672 f1=0.2684
Restored best Stage 1 weights for fold 1 (F1=0.2943)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.8483 | F1(macro)=0.3337 | Acc=0.3462


Confusion matrix:
 [[ 6  6 12 16]
 [ 4 10  3 15]
 [ 7  4  9 10]
 [ 2  4  3  5]]
Train  loss=2.8483 acc=0.3462 f1=0.3337 | Val loss=3.9773 acc=0.2586 f1=0.2607
  🔥 New best F1: 0.2607 – model saved.

Epoch 2/15


    t_loss=2.2520 | F1(macro)=0.3145 | Acc=0.3161


Confusion matrix:
 [[ 4  2 10 24]
 [ 1  9  1 21]
 [ 3  6  3 18]
 [ 0  1  1 12]]
Train  loss=2.2520 acc=0.3161 f1=0.3145 | Val loss=4.2332 acc=0.2414 f1=0.2324

Epoch 3/15


    t_loss=1.8345 | F1(macro)=0.3950 | Acc=0.4065


Confusion matrix:
 [[13 10  7 10]
 [12  6  5  9]
 [ 8  5  8  9]
 [ 3  3  4  4]]
Train  loss=1.8345 acc=0.4065 f1=0.3950 | Val loss=3.0502 acc=0.2672 f1=0.2567

Epoch 4/15


    t_loss=1.5852 | F1(macro)=0.4117 | Acc=0.4301


Confusion matrix:
 [[ 4 14 10 12]
 [ 5 11  5 11]
 [ 4  7  9 10]
 [ 1  5  1  7]]
Train  loss=1.5852 acc=0.4301 f1=0.4117 | Val loss=2.9592 acc=0.2672 f1=0.2634
  🔥 New best F1: 0.2634 – model saved.

Epoch 5/15


    t_loss=1.5271 | F1(macro)=0.4445 | Acc=0.4559


Confusion matrix:
 [[12 12  4 12]
 [ 8 13  2  9]
 [ 9 10  1 10]
 [ 7  4  0  3]]
Train  loss=1.5271 acc=0.4559 f1=0.4445 | Val loss=2.7068 acc=0.2500 f1=0.2153

Epoch 6/15


    t_loss=1.3002 | F1(macro)=0.4979 | Acc=0.5097


Confusion matrix:
 [[ 8 16  9  7]
 [ 6 18  2  6]
 [ 3 11  8  8]
 [ 1  3  4  6]]
Train  loss=1.3002 acc=0.5097 f1=0.4979 | Val loss=2.3927 acc=0.3448 f1=0.3301
  🔥 New best F1: 0.3301 – model saved.

Epoch 7/15


    t_loss=1.1120 | F1(macro)=0.5481 | Acc=0.5742


Confusion matrix:
 [[ 8  6  6 20]
 [10 11  3  8]
 [ 9  8  3 10]
 [ 2  2  2  8]]
Train  loss=1.1120 acc=0.5742 f1=0.5481 | Val loss=2.6049 acc=0.2586 f1=0.2519

Epoch 8/15


    t_loss=1.0709 | F1(macro)=0.5625 | Acc=0.5828


Confusion matrix:
 [[ 6 12  7 15]
 [ 7 11  3 11]
 [ 7  8  2 13]
 [ 5  2  2  5]]
Train  loss=1.0709 acc=0.5828 f1=0.5625 | Val loss=2.5252 acc=0.2069 f1=0.1966

Epoch 9/15


    t_loss=1.1032 | F1(macro)=0.5813 | Acc=0.5935


Confusion matrix:
 [[10  9 15  6]
 [13 12  5  2]
 [ 7  6 10  7]
 [ 4  3  3  4]]
Train  loss=1.1032 acc=0.5935 f1=0.5813 | Val loss=2.2762 acc=0.3103 f1=0.3043

Epoch 10/15


    t_loss=1.0263 | F1(macro)=0.6195 | Acc=0.6258


Confusion matrix:
 [[ 8  8  4 20]
 [14  9  2  7]
 [10  7  5  8]
 [ 4  3  0  7]]
Train  loss=1.0263 acc=0.6258 f1=0.6195 | Val loss=2.2801 acc=0.2500 f1=0.2524

Epoch 11/15


    t_loss=0.9432 | F1(macro)=0.6273 | Acc=0.6387


Confusion matrix:
 [[ 7  7 12 14]
 [11  8  8  5]
 [10  4  8  8]
 [ 1  3  6  4]]
Train  loss=0.9432 acc=0.6387 f1=0.6273 | Val loss=2.6005 acc=0.2328 f1=0.2317

Epoch 12/15


    t_loss=0.9300 | F1(macro)=0.6403 | Acc=0.6473


Confusion matrix:
 [[11  6  6 17]
 [ 7 10  5 10]
 [ 6  7  5 12]
 [ 6  2  2  4]]
Train  loss=0.9300 acc=0.6473 f1=0.6403 | Val loss=2.5690 acc=0.2586 f1=0.2535

Epoch 13/15


    t_loss=0.8746 | F1(macro)=0.6578 | Acc=0.6602


Confusion matrix:
 [[12  9  4 15]
 [ 7 12  3 10]
 [10  6  3 11]
 [ 4  3  2  5]]
Train  loss=0.8746 acc=0.6602 f1=0.6578 | Val loss=2.2302 acc=0.2759 f1=0.2601

Epoch 14/15


    t_loss=0.8695 | F1(macro)=0.6698 | Acc=0.6817


Confusion matrix:
 [[10  9  9 12]
 [10 12  3  7]
 [ 9 11  4  6]
 [ 5  3  3  3]]
Train  loss=0.8695 acc=0.6817 f1=0.6698 | Val loss=2.3739 acc=0.2500 f1=0.2337

Epoch 15/15


    t_loss=0.7965 | F1(macro)=0.6570 | Acc=0.6860


Confusion matrix:
 [[10 14  4 12]
 [12  7  4  9]
 [ 7  6  8  9]
 [ 3  3  4  4]]
Train  loss=0.7965 acc=0.6860 f1=0.6570 | Val loss=2.4459 acc=0.2500 f1=0.2476

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/10


    t_loss=5.2633 | F1(macro)=0.2539 | Acc=0.2559


Confusion matrix:
 [[15  5  9 12]
 [11  3  7 10]
 [ 9  7  7  7]
 [ 7  2  3  2]]
Train  loss=5.2633 acc=0.2559 f1=0.2539 | Val loss=6.2546 acc=0.2328 f1=0.2063
  🔥 New best F1: 0.2063 – model saved.

Epoch 2/10


    t_loss=3.8705 | F1(macro)=0.2986 | Acc=0.3054


Confusion matrix:
 [[10  5  9 17]
 [10  6  4 11]
 [ 9  5  4 12]
 [ 5  5  3  1]]
Train  loss=3.8705 acc=0.3054 f1=0.2986 | Val loss=6.2045 acc=0.1810 f1=0.1734

Epoch 3/10


    t_loss=3.7001 | F1(macro)=0.2863 | Acc=0.2903


Confusion matrix:
 [[11  9  7 14]
 [ 6  5  7 13]
 [ 7  7  7  9]
 [ 3  5  5  1]]
Train  loss=3.7001 acc=0.2903 f1=0.2863 | Val loss=5.4957 acc=0.2069 f1=0.1970

Epoch 4/10


    t_loss=3.5220 | F1(macro)=0.3069 | Acc=0.3054


Confusion matrix:
 [[14  2 14 11]
 [11  3  9  8]
 [ 9  4 13  4]
 [ 6  2  3  3]]
Train  loss=3.5220 acc=0.3054 f1=0.3069 | Val loss=4.9037 acc=0.2845 f1=0.2538
  🔥 New best F1: 0.2538 – model saved.

Epoch 5/10


    t_loss=3.5448 | F1(macro)=0.2782 | Acc=0.2796


Confusion matrix:
 [[18  7 11  5]
 [13  4 10  4]
 [ 7  5 10  8]
 [ 4  0  7  3]]
Train  loss=3.5448 acc=0.2796 f1=0.2782 | Val loss=4.5745 acc=0.3017 f1=0.2686
  🔥 New best F1: 0.2686 – model saved.

Epoch 6/10


    t_loss=3.3132 | F1(macro)=0.2966 | Acc=0.2989


Confusion matrix:
 [[ 8 10 10 13]
 [ 6 12  8  5]
 [ 7  6  9  8]
 [ 7  2  4  1]]
Train  loss=3.3132 acc=0.2989 f1=0.2966 | Val loss=5.6480 acc=0.2586 f1=0.2423

Epoch 7/10


    t_loss=3.2831 | F1(macro)=0.3371 | Acc=0.3376


Confusion matrix:
 [[13 10 11  7]
 [13  7  6  5]
 [12  7  4  7]
 [ 6  2  4  2]]
Train  loss=3.2831 acc=0.3376 f1=0.3371 | Val loss=4.9962 acc=0.2241 f1=0.2028

Epoch 8/10


    t_loss=3.3281 | F1(macro)=0.2500 | Acc=0.2538


Confusion matrix:
 [[12 12  9  8]
 [11  6  6  8]
 [12  5  8  5]
 [ 4  4  3  3]]
Train  loss=3.3281 acc=0.2538 f1=0.2500 | Val loss=4.5161 acc=0.2500 f1=0.2376

Epoch 9/10


    t_loss=3.0641 | F1(macro)=0.3244 | Acc=0.3247


Confusion matrix:
 [[14  4 10 13]
 [12  5  5  9]
 [10  1 10  9]
 [ 2  6  4  2]]
Train  loss=3.0641 acc=0.3247 f1=0.3244 | Val loss=4.7275 acc=0.2672 f1=0.2478

Epoch 10/10


    t_loss=3.2147 | F1(macro)=0.2881 | Acc=0.2882


Confusion matrix:
 [[11 16  6  8]
 [10  9  9  3]
 [ 7 13  4  6]
 [ 3  5  4  2]]
Train  loss=3.2147 acc=0.2882 f1=0.2881 | Val loss=4.2834 acc=0.2241 f1=0.2052
Restored best Stage 1 weights for fold 2 (F1=0.2686)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.8255 | F1(macro)=0.3291 | Acc=0.3355


Confusion matrix:
 [[12 12 10  7]
 [ 8  8  9  6]
 [ 5  9  7  9]
 [ 0  4  4  6]]
Train  loss=2.8255 acc=0.3355 f1=0.3291 | Val loss=3.9148 acc=0.2845 f1=0.2832
  🔥 New best F1: 0.2832 – model saved.

Epoch 2/15


    t_loss=2.3868 | F1(macro)=0.3467 | Acc=0.3505


Confusion matrix:
 [[16  5 12  8]
 [14  2  6  9]
 [10  1  9 10]
 [ 1  4  3  6]]
Train  loss=2.3868 acc=0.3505 f1=0.3467 | Val loss=3.3988 acc=0.2845 f1=0.2596

Epoch 3/15


    t_loss=1.7399 | F1(macro)=0.4093 | Acc=0.4323


Confusion matrix:
 [[19 14  1  7]
 [ 8 10  9  4]
 [13  9  2  6]
 [ 3  5  3  3]]
Train  loss=1.7399 acc=0.4323 f1=0.4093 | Val loss=3.0846 acc=0.2931 f1=0.2519

Epoch 4/15


    t_loss=1.6610 | F1(macro)=0.4460 | Acc=0.4559


Confusion matrix:
 [[ 9 13 12  7]
 [ 8  9  6  8]
 [ 4  7 11  8]
 [ 4  3  2  5]]
Train  loss=1.6610 acc=0.4559 f1=0.4460 | Val loss=2.7834 acc=0.2931 f1=0.2893
  🔥 New best F1: 0.2893 – model saved.

Epoch 5/15


    t_loss=1.4329 | F1(macro)=0.4311 | Acc=0.4430


Confusion matrix:
 [[ 7  2 17 15]
 [ 6  4  6 15]
 [ 8  3 16  3]
 [ 4  0  5  5]]
Train  loss=1.4329 acc=0.4430 f1=0.4311 | Val loss=2.4950 acc=0.2759 f1=0.2592

Epoch 6/15


    t_loss=1.3321 | F1(macro)=0.5099 | Acc=0.5183


Confusion matrix:
 [[ 8  4 13 16]
 [ 7  7  8  9]
 [ 5  8 12  5]
 [ 4  1  4  5]]
Train  loss=1.3321 acc=0.5183 f1=0.5099 | Val loss=2.4340 acc=0.2759 f1=0.2707

Epoch 7/15


    t_loss=1.2174 | F1(macro)=0.5225 | Acc=0.5312


Confusion matrix:
 [[17  4 14  6]
 [10  2 10  9]
 [14  4  7  5]
 [ 4  1  3  6]]
Train  loss=1.2174 acc=0.5312 f1=0.5225 | Val loss=2.0900 acc=0.2759 f1=0.2523

Epoch 8/15


    t_loss=1.0448 | F1(macro)=0.5557 | Acc=0.5806


Confusion matrix:
 [[10  6  6 19]
 [ 9  3  3 16]
 [ 5  6 10  9]
 [ 4  2  2  6]]
Train  loss=1.0448 acc=0.5806 f1=0.5557 | Val loss=2.3605 acc=0.2500 f1=0.2486

Epoch 9/15


    t_loss=1.0512 | F1(macro)=0.5717 | Acc=0.5785


Confusion matrix:
 [[ 9 10 13  9]
 [ 7 12  7  5]
 [ 8 11  6  5]
 [ 4  1  6  3]]
Train  loss=1.0512 acc=0.5785 f1=0.5717 | Val loss=2.4885 acc=0.2586 f1=0.2476

Epoch 10/15


    t_loss=0.9397 | F1(macro)=0.6246 | Acc=0.6301


Confusion matrix:
 [[12  5 13 11]
 [10  3  5 13]
 [11  2  9  8]
 [ 3  0  3  8]]
Train  loss=0.9397 acc=0.6301 f1=0.6246 | Val loss=2.0274 acc=0.2759 f1=0.2636

Epoch 11/15


    t_loss=0.9604 | F1(macro)=0.6440 | Acc=0.6495


Confusion matrix:
 [[17  5 15  4]
 [15  5  8  3]
 [11  2 11  6]
 [ 5  3  3  3]]
Train  loss=0.9604 acc=0.6495 f1=0.6440 | Val loss=2.1458 acc=0.3103 f1=0.2819

Epoch 12/15


    t_loss=0.9164 | F1(macro)=0.6484 | Acc=0.6516


Confusion matrix:
 [[ 6  4 10 21]
 [ 8  4  8 11]
 [ 7  2  9 12]
 [ 3  0  5  6]]
Train  loss=0.9164 acc=0.6516 f1=0.6484 | Val loss=2.2119 acc=0.2155 f1=0.2144

Epoch 13/15


    t_loss=0.9079 | F1(macro)=0.6480 | Acc=0.6581


Confusion matrix:
 [[11 14 10  6]
 [ 4  9  9  9]
 [ 4 11  8  7]
 [ 1  3  4  6]]
Train  loss=0.9079 acc=0.6581 f1=0.6480 | Val loss=2.1709 acc=0.2931 f1=0.2933
  🔥 New best F1: 0.2933 – model saved.

Epoch 14/15


    t_loss=0.8699 | F1(macro)=0.6919 | Acc=0.7032


Confusion matrix:
 [[16  8  9  8]
 [11  9  5  6]
 [ 9  8  7  6]
 [ 2  1  5  6]]
Train  loss=0.8699 acc=0.7032 f1=0.6919 | Val loss=2.1138 acc=0.3276 f1=0.3177
  🔥 New best F1: 0.3177 – model saved.

Epoch 15/15


    t_loss=0.9910 | F1(macro)=0.6166 | Acc=0.6194


Confusion matrix:
 [[ 9 12 11  9]
 [10  7  5  9]
 [10  4  8  8]
 [ 3  5  1  5]]
Train  loss=0.9910 acc=0.6194 f1=0.6166 | Val loss=2.3444 acc=0.2500 f1=0.2492

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/10


    t_loss=4.3652 | F1(macro)=0.2423 | Acc=0.2430


Confusion matrix:
 [[ 3 11 16 11]
 [ 4  8 12  7]
 [ 7  3 15  5]
 [ 4  1  6  3]]
Train  loss=4.3652 acc=0.2430 f1=0.2423 | Val loss=5.7098 acc=0.2500 f1=0.2319
  🔥 New best F1: 0.2319 – model saved.

Epoch 2/10


    t_loss=3.6338 | F1(macro)=0.2650 | Acc=0.2667


Confusion matrix:
 [[12 11  7 11]
 [ 4 13  8  6]
 [ 7  6 11  6]
 [ 4  4  3  3]]
Train  loss=3.6338 acc=0.2667 f1=0.2650 | Val loss=3.9710 acc=0.3362 f1=0.3190
  🔥 New best F1: 0.3190 – model saved.

Epoch 3/10


    t_loss=3.4482 | F1(macro)=0.2723 | Acc=0.2753


Confusion matrix:
 [[10 14 12  5]
 [10  9  8  4]
 [ 9 11  8  2]
 [ 3  5  3  3]]
Train  loss=3.4482 acc=0.2753 f1=0.2723 | Val loss=4.3130 acc=0.2586 f1=0.2519

Epoch 4/10


    t_loss=3.0515 | F1(macro)=0.3040 | Acc=0.3032


Confusion matrix:
 [[ 8 10 13 10]
 [ 4  7 12  8]
 [ 8  5 15  2]
 [ 1  4  3  6]]
Train  loss=3.0515 acc=0.3032 f1=0.3040 | Val loss=5.2300 acc=0.3103 f1=0.3037

Epoch 5/10


    t_loss=3.1763 | F1(macro)=0.2893 | Acc=0.2925


Confusion matrix:
 [[ 7  8 12 14]
 [ 9  5 10  7]
 [ 5  8 12  5]
 [ 2  2  3  7]]
Train  loss=3.1763 acc=0.2925 f1=0.2893 | Val loss=4.8814 acc=0.2672 f1=0.2650

Epoch 6/10


    t_loss=3.0283 | F1(macro)=0.3010 | Acc=0.3032


Confusion matrix:
 [[ 6 12 11 12]
 [ 5 11 11  4]
 [ 3  8 17  2]
 [ 4  3  3  4]]
Train  loss=3.0283 acc=0.3032 f1=0.3010 | Val loss=4.0409 acc=0.3276 f1=0.3091

Epoch 7/10


    t_loss=2.9412 | F1(macro)=0.2862 | Acc=0.2903


Confusion matrix:
 [[ 8  9 16  8]
 [ 8  8 11  4]
 [ 7  8 12  3]
 [ 4  3  3  4]]
Train  loss=2.9412 acc=0.2903 f1=0.2862 | Val loss=4.3879 acc=0.2759 f1=0.2706

Epoch 8/10


    t_loss=2.7613 | F1(macro)=0.3197 | Acc=0.3204


Confusion matrix:
 [[ 9 14 11  7]
 [ 6 13  8  4]
 [ 9 11  4  6]
 [ 2  6  2  4]]
Train  loss=2.7613 acc=0.3204 f1=0.3197 | Val loss=3.6446 acc=0.2586 f1=0.2473

Epoch 9/10


    t_loss=2.7836 | F1(macro)=0.3233 | Acc=0.3247


Confusion matrix:
 [[17 14  4  6]
 [ 5 11  8  7]
 [ 4 12  6  8]
 [ 6  0  1  7]]
Train  loss=2.7836 acc=0.3247 f1=0.3233 | Val loss=3.8313 acc=0.3534 f1=0.3419
  🔥 New best F1: 0.3419 – model saved.

Epoch 10/10


    t_loss=2.8292 | F1(macro)=0.3065 | Acc=0.3075


Confusion matrix:
 [[10 10 10 11]
 [ 4 10 13  4]
 [ 6  7  9  8]
 [ 2  3  4  5]]
Train  loss=2.8292 acc=0.3075 f1=0.3065 | Val loss=4.1317 acc=0.2931 f1=0.2890
Restored best Stage 1 weights for fold 3 (F1=0.3419)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.9964 | F1(macro)=0.3191 | Acc=0.3247


Confusion matrix:
 [[12 14  7  8]
 [14  7  7  3]
 [ 6 10  9  5]
 [ 4  4  2  4]]
Train  loss=2.9964 acc=0.3247 f1=0.3191 | Val loss=4.2785 acc=0.2759 f1=0.2716
  🔥 New best F1: 0.2716 – model saved.

Epoch 2/15


    t_loss=2.2940 | F1(macro)=0.3844 | Acc=0.3871


Confusion matrix:
 [[14 10  6 11]
 [12  6  5  8]
 [ 9  5  8  8]
 [ 2  2  2  8]]
Train  loss=2.2940 acc=0.3871 f1=0.3844 | Val loss=3.5620 acc=0.3103 f1=0.3054
  🔥 New best F1: 0.3054 – model saved.

Epoch 3/15


    t_loss=1.8845 | F1(macro)=0.4304 | Acc=0.4344


Confusion matrix:
 [[ 9  4 10 18]
 [ 6  4  8 13]
 [ 6  4 11  9]
 [ 1  1  5  7]]
Train  loss=1.8845 acc=0.4344 f1=0.4304 | Val loss=3.6179 acc=0.2672 f1=0.2602

Epoch 4/15


    t_loss=1.6959 | F1(macro)=0.4875 | Acc=0.4925


Confusion matrix:
 [[ 9 13 10  9]
 [ 7 12  4  8]
 [ 5 10 12  3]
 [ 3  1  3  7]]
Train  loss=1.6959 acc=0.4925 f1=0.4875 | Val loss=3.0637 acc=0.3448 f1=0.3458
  🔥 New best F1: 0.3458 – model saved.

Epoch 5/15


    t_loss=1.6682 | F1(macro)=0.4597 | Acc=0.4731


Confusion matrix:
 [[ 9 13 11  8]
 [11  7  9  4]
 [ 6  7 13  4]
 [ 2  4  5  3]]
Train  loss=1.6682 acc=0.4731 f1=0.4597 | Val loss=3.6772 acc=0.2759 f1=0.2627

Epoch 6/15


    t_loss=1.5127 | F1(macro)=0.4901 | Acc=0.5097


Confusion matrix:
 [[ 9 16 11  5]
 [10  8  9  4]
 [ 9  6 10  5]
 [ 1  4  3  6]]
Train  loss=1.5127 acc=0.5097 f1=0.4901 | Val loss=3.0998 acc=0.2845 f1=0.2934

Epoch 7/15


    t_loss=1.3418 | F1(macro)=0.4924 | Acc=0.5140


Confusion matrix:
 [[10 13 10  8]
 [ 5 15  7  4]
 [10  4 10  6]
 [ 2  1  5  6]]
Train  loss=1.3418 acc=0.5140 f1=0.4924 | Val loss=2.8414 acc=0.3534 f1=0.3503
  🔥 New best F1: 0.3503 – model saved.

Epoch 8/15


    t_loss=1.2831 | F1(macro)=0.5618 | Acc=0.5720


Confusion matrix:
 [[12 11  7 11]
 [ 7 11  9  4]
 [10  6  8  6]
 [ 3  4  4  3]]
Train  loss=1.2831 acc=0.5720 f1=0.5618 | Val loss=2.9636 acc=0.2931 f1=0.2779

Epoch 9/15


    t_loss=1.2115 | F1(macro)=0.5658 | Acc=0.5720


Confusion matrix:
 [[17 10  8  6]
 [12  8  9  2]
 [10  5  8  7]
 [ 6  3  1  4]]
Train  loss=1.2115 acc=0.5720 f1=0.5658 | Val loss=2.7478 acc=0.3190 f1=0.3010

Epoch 10/15


    t_loss=1.0968 | F1(macro)=0.5821 | Acc=0.5978


Confusion matrix:
 [[ 9 16 11  5]
 [11 10  6  4]
 [12  6  9  3]
 [ 2  5  3  4]]
Train  loss=1.0968 acc=0.5978 f1=0.5821 | Val loss=2.7573 acc=0.2759 f1=0.2765

Epoch 11/15


    t_loss=0.9525 | F1(macro)=0.6117 | Acc=0.6301


Confusion matrix:
 [[13 16  7  5]
 [ 7 11  6  7]
 [12  4 10  4]
 [ 4  4  3  3]]
Train  loss=0.9525 acc=0.6301 f1=0.6117 | Val loss=2.4938 acc=0.3190 f1=0.3025

Epoch 12/15


    t_loss=1.0906 | F1(macro)=0.5937 | Acc=0.6086


Confusion matrix:
 [[13 13  5 10]
 [14  9  4  4]
 [12  3  9  6]
 [ 5  2  1  6]]
Train  loss=1.0906 acc=0.6086 f1=0.5937 | Val loss=2.6060 acc=0.3190 f1=0.3209

Epoch 13/15


    t_loss=1.0958 | F1(macro)=0.6123 | Acc=0.6151


Confusion matrix:
 [[11 15  8  7]
 [ 8  9  9  5]
 [10  6  9  5]
 [ 0  8  4  2]]
Train  loss=1.0958 acc=0.6151 f1=0.6123 | Val loss=2.4998 acc=0.2672 f1=0.2491

Epoch 14/15


    t_loss=1.0386 | F1(macro)=0.6022 | Acc=0.6065


Confusion matrix:
 [[12 10  6 13]
 [ 7  9  5 10]
 [11  4  8  7]
 [ 4  2  3  5]]
Train  loss=1.0386 acc=0.6065 f1=0.6022 | Val loss=2.4573 acc=0.2931 f1=0.2883

Epoch 15/15


    t_loss=0.9619 | F1(macro)=0.6630 | Acc=0.6645


Confusion matrix:
 [[ 9 17  8  7]
 [ 9 13  4  5]
 [12  5  8  5]
 [ 3  2  5  4]]
Train  loss=0.9619 acc=0.6645 f1=0.6630 | Val loss=2.3764 acc=0.2931 f1=0.2863

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/10


    t_loss=5.0290 | F1(macro)=0.2137 | Acc=0.2129


Confusion matrix:
 [[ 6  7  7 21]
 [ 3  9  6 14]
 [ 6  7  7 10]
 [ 2  3  2  6]]
Train  loss=5.0290 acc=0.2129 f1=0.2137 | Val loss=6.3785 acc=0.2414 f1=0.2435
  🔥 New best F1: 0.2435 – model saved.

Epoch 2/10


    t_loss=3.8599 | F1(macro)=0.2735 | Acc=0.2753


Confusion matrix:
 [[ 4 11 15 11]
 [ 2 10  7 13]
 [ 4  7 15  4]
 [ 0  2  7  4]]
Train  loss=3.8599 acc=0.2753 f1=0.2735 | Val loss=5.4822 acc=0.2845 f1=0.2657
  🔥 New best F1: 0.2657 – model saved.

Epoch 3/10


    t_loss=3.4577 | F1(macro)=0.2948 | Acc=0.2968


Confusion matrix:
 [[ 7 19  6  9]
 [ 7 10  5 10]
 [ 3  9  7 11]
 [ 2  8  1  2]]
Train  loss=3.4577 acc=0.2968 f1=0.2948 | Val loss=5.5508 acc=0.2241 f1=0.2161

Epoch 4/10


    t_loss=3.5633 | F1(macro)=0.2680 | Acc=0.2667


Confusion matrix:
 [[12 12  7 10]
 [ 5 12  7  8]
 [ 4 12  9  5]
 [ 2  4  3  4]]
Train  loss=3.5633 acc=0.2667 f1=0.2680 | Val loss=4.5718 acc=0.3190 f1=0.3074
  🔥 New best F1: 0.3074 – model saved.

Epoch 5/10


    t_loss=3.3463 | F1(macro)=0.2920 | Acc=0.2925


Confusion matrix:
 [[ 6 15 10 10]
 [ 4 11 11  6]
 [ 4 11  4 11]
 [ 2  2  6  3]]
Train  loss=3.3463 acc=0.2925 f1=0.2920 | Val loss=4.9519 acc=0.2069 f1=0.1978

Epoch 6/10


    t_loss=3.3421 | F1(macro)=0.2750 | Acc=0.2731


Confusion matrix:
 [[ 5 20  8  8]
 [ 7 15  4  6]
 [ 6 11  5  8]
 [ 2  5  3  3]]
Train  loss=3.3421 acc=0.2731 f1=0.2750 | Val loss=4.8364 acc=0.2414 f1=0.2208

Epoch 7/10


    t_loss=2.9305 | F1(macro)=0.3488 | Acc=0.3505


Confusion matrix:
 [[ 7 11  4 19]
 [11 10  2  9]
 [ 3  5 10 12]
 [ 2  0  9  2]]
Train  loss=2.9305 acc=0.3505 f1=0.3488 | Val loss=4.5390 acc=0.2500 f1=0.2500

Epoch 8/10


    t_loss=3.0693 | F1(macro)=0.2764 | Acc=0.2817


Confusion matrix:
 [[ 4 10 14 13]
 [ 4 14  7  7]
 [ 5  7 10  8]
 [ 2  4  5  2]]
Train  loss=3.0693 acc=0.2817 f1=0.2764 | Val loss=4.8389 acc=0.2586 f1=0.2392

Epoch 9/10


    t_loss=2.8061 | F1(macro)=0.3352 | Acc=0.3355


Confusion matrix:
 [[ 7 15 11  8]
 [ 2 14  7  9]
 [ 2  8 12  8]
 [ 1  5  3  4]]
Train  loss=2.8061 acc=0.3355 f1=0.3352 | Val loss=4.3671 acc=0.3190 f1=0.3035

Epoch 10/10


    t_loss=2.9462 | F1(macro)=0.3329 | Acc=0.3333


Confusion matrix:
 [[ 8 10  7 16]
 [ 3 14  7  8]
 [ 1  9 14  6]
 [ 1  6  3  3]]
Train  loss=2.9462 acc=0.3333 f1=0.3329 | Val loss=4.4893 acc=0.3362 f1=0.3200
  🔥 New best F1: 0.3200 – model saved.
Restored best Stage 1 weights for fold 4 (F1=0.3200)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.8276 | F1(macro)=0.3356 | Acc=0.3398


Confusion matrix:
 [[ 7 12  9 13]
 [ 3 12  8  9]
 [ 7  6  8  9]
 [ 2  1  3  7]]
Train  loss=2.8276 acc=0.3398 f1=0.3356 | Val loss=3.8840 acc=0.2931 f1=0.2912
  🔥 New best F1: 0.2912 – model saved.

Epoch 2/15


    t_loss=2.1810 | F1(macro)=0.3612 | Acc=0.3785


Confusion matrix:
 [[ 2 24  9  6]
 [ 3 20  4  5]
 [ 2 13  6  9]
 [ 0  5  3  5]]
Train  loss=2.1810 acc=0.3785 f1=0.3612 | Val loss=4.1689 acc=0.2845 f1=0.2507

Epoch 3/15


    t_loss=2.0444 | F1(macro)=0.3913 | Acc=0.4022


Confusion matrix:
 [[ 4  8 14 15]
 [ 1 13  7 11]
 [ 1  8  8 13]
 [ 0  0  6  7]]
Train  loss=2.0444 acc=0.4022 f1=0.3913 | Val loss=3.7133 acc=0.2759 f1=0.2700

Epoch 4/15


    t_loss=1.7667 | F1(macro)=0.3936 | Acc=0.4043


Confusion matrix:
 [[ 5  2 22 12]
 [ 3  4 16  9]
 [ 2  3 13 12]
 [ 0  1  4  8]]
Train  loss=1.7667 acc=0.4043 f1=0.3936 | Val loss=3.2516 acc=0.2586 f1=0.2472

Epoch 5/15


    t_loss=1.4862 | F1(macro)=0.4362 | Acc=0.4495


Confusion matrix:
 [[ 3 20  8 10]
 [ 2 17  4  9]
 [ 0  7  9 14]
 [ 0  3  4  6]]
Train  loss=1.4862 acc=0.4495 f1=0.4362 | Val loss=2.9370 acc=0.3017 f1=0.2797

Epoch 6/15


    t_loss=1.3493 | F1(macro)=0.4966 | Acc=0.4989


Confusion matrix:
 [[ 5 14 11 11]
 [ 8  9  5 10]
 [ 4  6 11  9]
 [ 1  2  6  4]]
Train  loss=1.3493 acc=0.4989 f1=0.4966 | Val loss=2.9033 acc=0.2500 f1=0.2437

Epoch 7/15


    t_loss=1.2734 | F1(macro)=0.5080 | Acc=0.5204


Confusion matrix:
 [[ 3 11 15 12]
 [ 6  8 10  8]
 [ 3  5 14  8]
 [ 1  2  5  5]]
Train  loss=1.2734 acc=0.5204 f1=0.5080 | Val loss=2.6307 acc=0.2586 f1=0.2457

Epoch 8/15


    t_loss=1.2374 | F1(macro)=0.4992 | Acc=0.5097


Confusion matrix:
 [[ 7 13 11 10]
 [ 6 12  6  8]
 [ 6  9  9  6]
 [ 0  6  4  3]]
Train  loss=1.2374 acc=0.5097 f1=0.4992 | Val loss=2.6678 acc=0.2672 f1=0.2542

Epoch 9/15


    t_loss=1.1112 | F1(macro)=0.5701 | Acc=0.5763


Confusion matrix:
 [[12 14  8  7]
 [ 6 16  6  4]
 [ 7  7 13  3]
 [ 1  4  1  7]]
Train  loss=1.1112 acc=0.5763 f1=0.5701 | Val loss=2.1348 acc=0.4138 f1=0.4142
  🔥 New best F1: 0.4142 – model saved.

Epoch 10/15


    t_loss=1.0233 | F1(macro)=0.5972 | Acc=0.6043


Confusion matrix:
 [[ 4 14 17  6]
 [ 2 14 10  6]
 [ 2 11  8  9]
 [ 1  4  4  4]]
Train  loss=1.0233 acc=0.6043 f1=0.5972 | Val loss=2.2475 acc=0.2586 f1=0.2439

Epoch 11/15


    t_loss=0.9276 | F1(macro)=0.6118 | Acc=0.6258


Confusion matrix:
 [[ 7  9  8 17]
 [ 4 15  4  9]
 [ 4  6  5 15]
 [ 0  1  5  7]]
Train  loss=0.9276 acc=0.6258 f1=0.6118 | Val loss=2.2326 acc=0.2931 f1=0.2870

Epoch 12/15


    t_loss=0.9877 | F1(macro)=0.6420 | Acc=0.6473


Confusion matrix:
 [[ 6 12 13 10]
 [ 4 15  3 10]
 [ 6  6  7 11]
 [ 2  3  2  6]]
Train  loss=0.9877 acc=0.6473 f1=0.6420 | Val loss=2.2267 acc=0.2931 f1=0.2848

Epoch 13/15


    t_loss=0.9983 | F1(macro)=0.6259 | Acc=0.6344


Confusion matrix:
 [[ 9 13  8 11]
 [ 7 15  3  7]
 [ 3  6  8 13]
 [ 0  5  2  6]]
Train  loss=0.9983 acc=0.6344 f1=0.6259 | Val loss=2.1901 acc=0.3276 f1=0.3191

Epoch 14/15


    t_loss=0.9435 | F1(macro)=0.6458 | Acc=0.6581


Confusion matrix:
 [[ 8 12 10 11]
 [ 5 14  6  7]
 [ 5  6  7 12]
 [ 1  2  4  6]]
Train  loss=0.9435 acc=0.6581 f1=0.6458 | Val loss=2.3295 acc=0.3017 f1=0.2954

Epoch 15/15


    t_loss=0.9000 | F1(macro)=0.6495 | Acc=0.6602


Confusion matrix:
 [[ 7 16 10  8]
 [ 3 20  3  6]
 [ 1  8 11 10]
 [ 1  2  6  4]]
Train  loss=0.9000 acc=0.6602 f1=0.6495 | Val loss=2.1716 acc=0.3621 f1=0.3347


# convnext_tiny

In [6]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

In [7]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0"

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png        Luminal A
1  img_0001.png        Luminal B
2  img_0002.png        Luminal B
3  img_0003.png  Triple negative
4  img_0004.png        Luminal A


In [8]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
                         shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            img_tensor = img_tensor.squeeze(0)  # [3,H,W]
            img_tensor = img_tensor.to(device)

            # -------- TTA: apply multiple augmented views --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1,4]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N, 4]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
pred_indices = mean_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print("Saved submission_5fold_tta.csv")

Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_tta.csv


In [9]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.2787563627601578
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.16595022624434388
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.30344742063492064
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.26380703163219155
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.27852744645707517
Mean OOF F1: 0.25809769754573786
