In [1]:
import enum
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.persistence_manager import PersistenceManager
from notebooks.internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNETV2_S

# tf_efficientnetv2_s.in21k

In [3]:
if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(train_df_split, transforms=train_transforms, is_train=True, image_size=IMAGE_SIZE)
        val_dataset   = HistologyDataset(val_df_split,   transforms=val_test_transforms, is_train=True, image_size=IMAGE_SIZE)

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE,
                                  shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

        # --- create fresh model for this fold ---
        model = timm.create_model(
            PRETRAINED_MODEL,
            pretrained=True,
            num_classes=N_CLASSES
        ).to(device)

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.6633 | F1(macro)=0.2306 | Acc=0.2349


Confusion matrix:
 [[ 2  4 34  1]
 [ 1  3 26  2]
 [ 1  4 25  0]
 [ 2  1 11  0]]
Train  loss=4.6633 acc=0.2349 f1=0.2306 | Val loss=7.8236 acc=0.2564 f1=0.1546
  🔥 New best F1: 0.1546 – model saved.

Epoch 2/8


    t_loss=3.3138 | F1(macro)=0.2980 | Acc=0.2996


Confusion matrix:
 [[ 3  4 31  3]
 [ 3  1 28  0]
 [ 2  3 23  2]
 [ 2  1 10  1]]
Train  loss=3.3138 acc=0.2996 f1=0.2980 | Val loss=7.6312 acc=0.2393 f1=0.1609
  🔥 New best F1: 0.1609 – model saved.

Epoch 3/8


    t_loss=3.2791 | F1(macro)=0.2700 | Acc=0.2716


Confusion matrix:
 [[ 2  7 30  2]
 [ 3  3 23  3]
 [ 2  3 23  2]
 [ 4  0 10  0]]
Train  loss=3.2791 acc=0.2716 f1=0.2700 | Val loss=6.7141 acc=0.2393 f1=0.1517

Epoch 4/8


    t_loss=3.3171 | F1(macro)=0.2566 | Acc=0.2565


Confusion matrix:
 [[ 4  6 29  2]
 [ 2  4 24  2]
 [ 2  5 20  3]
 [ 2  2  9  1]]
Train  loss=3.3171 acc=0.2565 f1=0.2566 | Val loss=6.8329 acc=0.2479 f1=0.1920
  🔥 New best F1: 0.1920 – model saved.

Epoch 5/8


    t_loss=3.0439 | F1(macro)=0.3018 | Acc=0.3060


Confusion matrix:
 [[ 1  5 33  2]
 [ 2  3 23  4]
 [ 1  7 21  1]
 [ 3  2  9  0]]
Train  loss=3.0439 acc=0.3060 f1=0.3018 | Val loss=6.3248 acc=0.2137 f1=0.1315

Epoch 6/8


    t_loss=3.1607 | F1(macro)=0.2878 | Acc=0.2909


Confusion matrix:
 [[ 4  3 31  3]
 [ 3  1 25  3]
 [ 4  3 20  3]
 [ 3  0 11  0]]
Train  loss=3.1607 acc=0.2909 f1=0.2878 | Val loss=6.9109 acc=0.2137 f1=0.1347

Epoch 7/8


    t_loss=2.8825 | F1(macro)=0.3003 | Acc=0.3082


Confusion matrix:
 [[ 4  7 26  4]
 [ 3  3 25  1]
 [ 1  2 24  3]
 [ 2  1 10  1]]
Train  loss=2.8825 acc=0.3082 f1=0.3003 | Val loss=6.0505 acc=0.2735 f1=0.1986
  🔥 New best F1: 0.1986 – model saved.

Epoch 8/8


    t_loss=2.9382 | F1(macro)=0.3182 | Acc=0.3211


Confusion matrix:
 [[ 4  3 29  5]
 [ 1  4 25  2]
 [ 1  5 22  2]
 [ 1  3 10  0]]
Train  loss=2.9382 acc=0.3211 f1=0.3182 | Val loss=5.9256 acc=0.2564 f1=0.1790
Restored best Stage 1 weights for fold 0 (F1=0.1986)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=3.0066 | F1(macro)=0.3303 | Acc=0.3341


Confusion matrix:
 [[ 5  1 24 11]
 [ 5  5 17  5]
 [ 5  1 18  6]
 [ 2  1  8  3]]
Train  loss=3.0066 acc=0.3341 f1=0.3303 | Val loss=5.9504 acc=0.2650 f1=0.2368
  🔥 New best F1: 0.2368 – model saved.

Epoch 2/12


    t_loss=2.4782 | F1(macro)=0.3531 | Acc=0.3642


Confusion matrix:
 [[ 3  4 25  9]
 [ 3  8 18  3]
 [ 2  1 21  6]
 [ 0  3  9  2]]
Train  loss=2.4782 acc=0.3642 f1=0.3531 | Val loss=5.5503 acc=0.2906 f1=0.2453
  🔥 New best F1: 0.2453 – model saved.

Epoch 3/12


    t_loss=2.2254 | F1(macro)=0.3737 | Acc=0.3879


Confusion matrix:
 [[ 4  3 25  9]
 [ 2  4 23  3]
 [ 0  0 23  7]
 [ 0  2 11  1]]
Train  loss=2.2254 acc=0.3879 f1=0.3737 | Val loss=5.7054 acc=0.2735 f1=0.2087

Epoch 4/12


    t_loss=2.0475 | F1(macro)=0.3833 | Acc=0.3944


Confusion matrix:
 [[13  3 16  9]
 [ 6  4 19  3]
 [ 9  1 15  5]
 [ 4  4  5  1]]
Train  loss=2.0475 acc=0.3944 f1=0.3833 | Val loss=4.2027 acc=0.2821 f1=0.2384

Epoch 5/12


    t_loss=1.8604 | F1(macro)=0.3870 | Acc=0.3987


Confusion matrix:
 [[10  8 15  8]
 [ 2  6 19  5]
 [ 5  1 18  6]
 [ 0  6  5  3]]
Train  loss=1.8604 acc=0.3987 f1=0.3870 | Val loss=3.6856 acc=0.3162 f1=0.2879
  🔥 New best F1: 0.2879 – model saved.

Epoch 6/12


    t_loss=1.7568 | F1(macro)=0.4301 | Acc=0.4397


Confusion matrix:
 [[ 5  3 23 10]
 [ 2  3 17 10]
 [ 1  1 21  7]
 [ 0  2 10  2]]
Train  loss=1.7568 acc=0.4397 f1=0.4301 | Val loss=4.4042 acc=0.2650 f1=0.2148

Epoch 7/12


    t_loss=1.6449 | F1(macro)=0.4035 | Acc=0.4267


Confusion matrix:
 [[ 9 11 13  8]
 [ 3  7 12 10]
 [ 2  1 18  9]
 [ 0  4  6  4]]
Train  loss=1.6449 acc=0.4267 f1=0.4035 | Val loss=4.1054 acc=0.3248 f1=0.3038
  🔥 New best F1: 0.3038 – model saved.

Epoch 8/12


    t_loss=1.6137 | F1(macro)=0.4289 | Acc=0.4353


Confusion matrix:
 [[ 7 11 19  4]
 [ 2 12 14  4]
 [ 4  4 19  3]
 [ 2  3  8  1]]
Train  loss=1.6137 acc=0.4353 f1=0.4289 | Val loss=4.2452 acc=0.3333 f1=0.2841

Epoch 9/12


    t_loss=1.5209 | F1(macro)=0.4789 | Acc=0.4871


Confusion matrix:
 [[ 4 10 20  7]
 [ 5  9 13  5]
 [ 5  6 13  6]
 [ 2  4  7  1]]
Train  loss=1.5209 acc=0.4871 f1=0.4789 | Val loss=4.1211 acc=0.2308 f1=0.2023

Epoch 10/12


    t_loss=1.5117 | F1(macro)=0.4555 | Acc=0.4612


Confusion matrix:
 [[ 9 11 15  6]
 [ 5  6 18  3]
 [ 4  5 18  3]
 [ 3  3  8  0]]
Train  loss=1.5117 acc=0.4612 f1=0.4555 | Val loss=4.1705 acc=0.2821 f1=0.2263

Epoch 11/12


    t_loss=1.3725 | F1(macro)=0.4811 | Acc=0.4935


Confusion matrix:
 [[ 9  8 18  6]
 [ 7  4 18  3]
 [ 2  2 22  4]
 [ 3  2  9  0]]
Train  loss=1.3725 acc=0.4935 f1=0.4811 | Val loss=4.2564 acc=0.2991 f1=0.2276

Epoch 12/12


    t_loss=1.3542 | F1(macro)=0.5005 | Acc=0.5172


Confusion matrix:
 [[ 7 12 15  7]
 [ 3  7 18  4]
 [ 7  4 11  8]
 [ 4  4  5  1]]
Train  loss=1.3542 acc=0.5172 f1=0.5005 | Val loss=3.9661 acc=0.2222 f1=0.2001

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=5.2246 | F1(macro)=0.1990 | Acc=0.2022


Confusion matrix:
 [[ 9 10 13  8]
 [ 7  7  9  9]
 [ 0 11  8 11]
 [ 3  4  6  1]]
Train  loss=5.2246 acc=0.2022 f1=0.1990 | Val loss=6.6844 acc=0.2155 f1=0.2032
  🔥 New best F1: 0.2032 – model saved.

Epoch 2/8


    t_loss=4.1661 | F1(macro)=0.2603 | Acc=0.2645


Confusion matrix:
 [[ 5 18 11  6]
 [ 3 11  9  9]
 [ 4  9 15  2]
 [ 2  4  8  0]]
Train  loss=4.1661 acc=0.2645 f1=0.2603 | Val loss=6.0843 acc=0.2672 f1=0.2234
  🔥 New best F1: 0.2234 – model saved.

Epoch 3/8


    t_loss=3.3272 | F1(macro)=0.2853 | Acc=0.2860


Confusion matrix:
 [[10 14 11  5]
 [ 4 14  7  7]
 [ 5 10  8  7]
 [ 3  5  3  3]]
Train  loss=3.3272 acc=0.2860 f1=0.2853 | Val loss=5.3450 acc=0.3017 f1=0.2834
  🔥 New best F1: 0.2834 – model saved.

Epoch 4/8


    t_loss=3.4234 | F1(macro)=0.2925 | Acc=0.2989


Confusion matrix:
 [[ 6 14 17  3]
 [ 4  9 13  6]
 [ 1 13  8  8]
 [ 0  3 10  1]]
Train  loss=3.4234 acc=0.2989 f1=0.2925 | Val loss=6.5978 acc=0.2069 f1=0.1891

Epoch 5/8


    t_loss=3.5692 | F1(macro)=0.2683 | Acc=0.2688


Confusion matrix:
 [[ 7 11 13  9]
 [ 5 14  4  9]
 [ 2 11  7 10]
 [ 2  3  7  2]]
Train  loss=3.5692 acc=0.2688 f1=0.2683 | Val loss=6.3306 acc=0.2586 f1=0.2412

Epoch 6/8


    t_loss=3.4275 | F1(macro)=0.2701 | Acc=0.2710


Confusion matrix:
 [[ 9 15  8  8]
 [ 5 14  2 11]
 [ 2 10  7 11]
 [ 4  5  3  2]]
Train  loss=3.4275 acc=0.2710 f1=0.2701 | Val loss=5.2100 acc=0.2759 f1=0.2588

Epoch 7/8


    t_loss=3.2332 | F1(macro)=0.2758 | Acc=0.2774


Confusion matrix:
 [[12 11  9  8]
 [ 5  9 10  8]
 [ 3  7 12  8]
 [ 4  1  8  1]]
Train  loss=3.2332 acc=0.2774 f1=0.2758 | Val loss=4.6472 acc=0.2931 f1=0.2685

Epoch 8/8


    t_loss=3.1305 | F1(macro)=0.2713 | Acc=0.2710


Confusion matrix:
 [[ 9 12 14  5]
 [ 6  8 13  5]
 [ 4  8 13  5]
 [ 5  1  8  0]]
Train  loss=3.1305 acc=0.2710 f1=0.2713 | Val loss=5.7339 acc=0.2586 f1=0.2192
Restored best Stage 1 weights for fold 1 (F1=0.2834)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=3.1637 | F1(macro)=0.2916 | Acc=0.3032


Confusion matrix:
 [[14  6  9 11]
 [ 5  5  4 18]
 [ 6  2 12 10]
 [ 4  1  2  7]]
Train  loss=3.1637 acc=0.3032 f1=0.2916 | Val loss=4.2335 acc=0.3276 f1=0.3194
  🔥 New best F1: 0.3194 – model saved.

Epoch 2/12


    t_loss=2.5397 | F1(macro)=0.3287 | Acc=0.3376


Confusion matrix:
 [[ 8  6 13 13]
 [ 7 10  4 11]
 [ 5  6  8 11]
 [ 4  1  3  6]]
Train  loss=2.5397 acc=0.3376 f1=0.3287 | Val loss=3.9974 acc=0.2759 f1=0.2769

Epoch 3/12


    t_loss=2.2143 | F1(macro)=0.3627 | Acc=0.3656


Confusion matrix:
 [[12 11  6 11]
 [ 3 12  4 13]
 [ 0  6  7 17]
 [ 4  4  1  5]]
Train  loss=2.2143 acc=0.3656 f1=0.3627 | Val loss=3.4587 acc=0.3103 f1=0.3086

Epoch 4/12


    t_loss=2.1004 | F1(macro)=0.3815 | Acc=0.3871


Confusion matrix:
 [[ 3 17 10 10]
 [ 5 13  8  6]
 [ 4 11 10  5]
 [ 4  4  3  3]]
Train  loss=2.1004 acc=0.3871 f1=0.3815 | Val loss=3.1762 acc=0.2500 f1=0.2326

Epoch 5/12


    t_loss=1.8879 | F1(macro)=0.3670 | Acc=0.3763


Confusion matrix:
 [[ 7  7  7 19]
 [ 4  8  9 11]
 [ 0 10 10 10]
 [ 5  1  4  4]]
Train  loss=1.8879 acc=0.3763 f1=0.3670 | Val loss=3.2969 acc=0.2500 f1=0.2493

Epoch 6/12


    t_loss=1.7697 | F1(macro)=0.3713 | Acc=0.3828


Confusion matrix:
 [[12 11  8  9]
 [ 8 14  2  8]
 [ 4 14  9  3]
 [ 3  3  2  6]]
Train  loss=1.7697 acc=0.3828 f1=0.3713 | Val loss=2.8695 acc=0.3534 f1=0.3474
  🔥 New best F1: 0.3474 – model saved.

Epoch 7/12


    t_loss=1.6095 | F1(macro)=0.3926 | Acc=0.4172


Confusion matrix:
 [[ 4  9  5 22]
 [ 3  8  0 21]
 [ 2  6  6 16]
 [ 3  1  2  8]]
Train  loss=1.6095 acc=0.4172 f1=0.3926 | Val loss=3.1088 acc=0.2241 f1=0.2290

Epoch 8/12


    t_loss=1.5388 | F1(macro)=0.4273 | Acc=0.4430


Confusion matrix:
 [[13  4  2 21]
 [11  2  2 17]
 [ 8  7  2 13]
 [ 4  1  2  7]]
Train  loss=1.5388 acc=0.4430 f1=0.4273 | Val loss=2.9707 acc=0.2069 f1=0.1822

Epoch 9/12


    t_loss=1.4891 | F1(macro)=0.4123 | Acc=0.4280


Confusion matrix:
 [[ 8  6  3 23]
 [ 4  8  3 17]
 [ 1  6  7 16]
 [ 2  2  2  8]]
Train  loss=1.4891 acc=0.4280 f1=0.4123 | Val loss=2.8794 acc=0.2672 f1=0.2759

Epoch 10/12


    t_loss=1.3306 | F1(macro)=0.4510 | Acc=0.4688


Confusion matrix:
 [[ 5  6  7 22]
 [ 2  7  5 18]
 [ 2  8  6 14]
 [ 2  1  4  7]]
Train  loss=1.3306 acc=0.4688 f1=0.4510 | Val loss=2.8324 acc=0.2155 f1=0.2182

Epoch 11/12


    t_loss=1.3373 | F1(macro)=0.4422 | Acc=0.4538


Confusion matrix:
 [[11  8  3 18]
 [ 6  8  1 17]
 [ 1 14  4 11]
 [ 1  2  4  7]]
Train  loss=1.3373 acc=0.4538 f1=0.4422 | Val loss=2.5144 acc=0.2586 f1=0.2556

Epoch 12/12


    t_loss=1.3794 | F1(macro)=0.4209 | Acc=0.4258


Confusion matrix:
 [[ 7 17  4 12]
 [ 4 11  2 15]
 [ 1  9  5 15]
 [ 3  2  4  5]]
Train  loss=1.3794 acc=0.4258 f1=0.4209 | Val loss=2.9574 acc=0.2414 f1=0.2376

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.3423 | F1(macro)=0.2436 | Acc=0.2516


Confusion matrix:
 [[23  6  1 11]
 [12  7  1 11]
 [17  3  2  8]
 [ 5  4  1  4]]
Train  loss=4.3423 acc=0.2516 f1=0.2436 | Val loss=5.5621 acc=0.3103 f1=0.2562
  🔥 New best F1: 0.2562 – model saved.

Epoch 2/8


    t_loss=3.3571 | F1(macro)=0.3238 | Acc=0.3247


Confusion matrix:
 [[19  4  7 11]
 [15  5  4  7]
 [15  3  7  5]
 [ 3  2  4  5]]
Train  loss=3.3571 acc=0.3247 f1=0.3238 | Val loss=4.2626 acc=0.3103 f1=0.2845
  🔥 New best F1: 0.2845 – model saved.

Epoch 3/8


    t_loss=3.6157 | F1(macro)=0.2541 | Acc=0.2538


Confusion matrix:
 [[26  6  4  5]
 [20  6  2  3]
 [19  3  1  7]
 [ 7  2  1  4]]
Train  loss=3.6157 acc=0.2538 f1=0.2541 | Val loss=4.9006 acc=0.3190 f1=0.2513

Epoch 4/8


    t_loss=3.4281 | F1(macro)=0.2577 | Acc=0.2624


Confusion matrix:
 [[17  6  5 13]
 [14  8  3  6]
 [15  4  3  8]
 [ 2  2  4  6]]
Train  loss=3.4281 acc=0.2624 f1=0.2577 | Val loss=4.5801 acc=0.2931 f1=0.2711

Epoch 5/8


    t_loss=3.2100 | F1(macro)=0.2810 | Acc=0.2839


Confusion matrix:
 [[19  4 10  8]
 [17  5  5  4]
 [18  2  4  6]
 [ 4  1  3  6]]
Train  loss=3.2100 acc=0.2839 f1=0.2810 | Val loss=4.7826 acc=0.2931 f1=0.2715

Epoch 6/8


    t_loss=3.1454 | F1(macro)=0.3051 | Acc=0.3097


Confusion matrix:
 [[15  5 10 11]
 [12  6  6  7]
 [11  5  6  8]
 [ 3  1  3  7]]
Train  loss=3.1454 acc=0.3097 f1=0.3051 | Val loss=3.9536 acc=0.2931 f1=0.2830

Epoch 7/8


    t_loss=2.8622 | F1(macro)=0.3413 | Acc=0.3441


Confusion matrix:
 [[20  4  7 10]
 [19  7  1  4]
 [18  1  3  8]
 [ 6  1  2  5]]
Train  loss=2.8622 acc=0.3441 f1=0.3413 | Val loss=4.8746 acc=0.3017 f1=0.2716

Epoch 8/8


    t_loss=2.8400 | F1(macro)=0.2991 | Acc=0.3011


Confusion matrix:
 [[17  8  6 10]
 [15  7  2  7]
 [15  4  6  5]
 [ 5  2  2  5]]
Train  loss=2.8400 acc=0.3011 f1=0.2991 | Val loss=4.6344 acc=0.3017 f1=0.2849
  🔥 New best F1: 0.2849 – model saved.
Restored best Stage 1 weights for fold 2 (F1=0.2849)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=2.8389 | F1(macro)=0.3179 | Acc=0.3290


Confusion matrix:
 [[20  3  8 10]
 [11  4  6 10]
 [17  2  5  6]
 [ 4  0  3  7]]
Train  loss=2.8389 acc=0.3290 f1=0.3179 | Val loss=4.7697 acc=0.3103 f1=0.2801
  🔥 New best F1: 0.2801 – model saved.

Epoch 2/12


    t_loss=2.5769 | F1(macro)=0.3274 | Acc=0.3376


Confusion matrix:
 [[18  9  6  8]
 [17  7  3  4]
 [15  3  4  8]
 [ 5  2  3  4]]
Train  loss=2.5769 acc=0.3376 f1=0.3274 | Val loss=4.1822 acc=0.2845 f1=0.2572

Epoch 3/12


    t_loss=2.1970 | F1(macro)=0.3795 | Acc=0.4000


Confusion matrix:
 [[11 15  7  8]
 [ 6 12  5  8]
 [11 10  4  5]
 [ 3  6  1  4]]
Train  loss=2.1970 acc=0.4000 f1=0.3795 | Val loss=3.3227 acc=0.2672 f1=0.2513

Epoch 4/12


    t_loss=2.0127 | F1(macro)=0.3613 | Acc=0.3785


Confusion matrix:
 [[21  2 11  7]
 [14  8  6  3]
 [16  1 11  2]
 [ 5  1  3  5]]
Train  loss=2.0127 acc=0.3785 f1=0.3613 | Val loss=3.5443 acc=0.3879 f1=0.3721
  🔥 New best F1: 0.3721 – model saved.

Epoch 5/12


    t_loss=1.8964 | F1(macro)=0.3585 | Acc=0.3742


Confusion matrix:
 [[11 12 16  2]
 [ 8  8 13  2]
 [10  4 15  1]
 [ 3  1  9  1]]
Train  loss=1.8964 acc=0.3742 f1=0.3585 | Val loss=4.0275 acc=0.3017 f1=0.2621

Epoch 6/12


    t_loss=1.8004 | F1(macro)=0.3842 | Acc=0.3957


Confusion matrix:
 [[20  9  9  3]
 [13  5 13  0]
 [18  4  5  3]
 [ 7  2  2  3]]
Train  loss=1.8004 acc=0.3957 f1=0.3842 | Val loss=3.9049 acc=0.2845 f1=0.2576

Epoch 7/12


    t_loss=1.7222 | F1(macro)=0.3924 | Acc=0.4065


Confusion matrix:
 [[17  6 13  5]
 [10  8 11  2]
 [ 8  6 10  6]
 [ 5  2  4  3]]
Train  loss=1.7222 acc=0.4065 f1=0.3924 | Val loss=3.2587 acc=0.3276 f1=0.3039

Epoch 8/12


    t_loss=1.5463 | F1(macro)=0.4397 | Acc=0.4495


Confusion matrix:
 [[11  7 15  8]
 [ 7 11 10  3]
 [ 8  6 12  4]
 [ 2  2  5  5]]
Train  loss=1.5463 acc=0.4495 f1=0.4397 | Val loss=2.8807 acc=0.3362 f1=0.3331

Epoch 9/12


    t_loss=1.4595 | F1(macro)=0.4480 | Acc=0.4559


Confusion matrix:
 [[19 10 10  2]
 [ 8 12  9  2]
 [13  7  6  4]
 [ 3  3  4  4]]
Train  loss=1.4595 acc=0.4559 f1=0.4480 | Val loss=2.7011 acc=0.3534 f1=0.3361

Epoch 10/12


    t_loss=1.3905 | F1(macro)=0.4824 | Acc=0.4925


Confusion matrix:
 [[ 9 15 12  5]
 [10  9 11  1]
 [ 7  7 12  4]
 [ 5  3  3  3]]
Train  loss=1.3905 acc=0.4925 f1=0.4824 | Val loss=2.7652 acc=0.2845 f1=0.2755

Epoch 11/12


    t_loss=1.3455 | F1(macro)=0.4404 | Acc=0.4624


Confusion matrix:
 [[ 9 12 14  6]
 [ 7 13 10  1]
 [ 8  6 13  3]
 [ 4  3  4  3]]
Train  loss=1.3455 acc=0.4624 f1=0.4404 | Val loss=3.0014 acc=0.3276 f1=0.3123

Epoch 12/12


    t_loss=1.4003 | F1(macro)=0.4661 | Acc=0.4753


Confusion matrix:
 [[14 14  7  6]
 [10 11  8  2]
 [19  3  4  4]
 [ 4  5  2  3]]
Train  loss=1.4003 acc=0.4753 f1=0.4661 | Val loss=2.8480 acc=0.2759 f1=0.2564

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=5.1921 | F1(macro)=0.2467 | Acc=0.2516


Confusion matrix:
 [[ 1  9  0 31]
 [ 1  1  1 28]
 [ 1  2  2 25]
 [ 2  1  1 10]]
Train  loss=5.1921 acc=0.2516 f1=0.2467 | Val loss=8.7863 acc=0.1207 f1=0.0979
  🔥 New best F1: 0.0979 – model saved.

Epoch 2/8


    t_loss=4.3219 | F1(macro)=0.2702 | Acc=0.2731


Confusion matrix:
 [[ 2 17  0 22]
 [ 2  9  1 19]
 [ 2  2  5 21]
 [ 0  3  0 11]]
Train  loss=4.3219 acc=0.2731 f1=0.2702 | Val loss=7.7578 acc=0.2328 f1=0.2265
  🔥 New best F1: 0.2265 – model saved.

Epoch 3/8


    t_loss=3.9066 | F1(macro)=0.2447 | Acc=0.2473


Confusion matrix:
 [[ 2 12  4 23]
 [ 4  7  3 17]
 [ 1  1  7 21]
 [ 0  1  2 11]]
Train  loss=3.9066 acc=0.2473 f1=0.2447 | Val loss=6.7342 acc=0.2328 f1=0.2282
  🔥 New best F1: 0.2282 – model saved.

Epoch 4/8


    t_loss=3.4261 | F1(macro)=0.2591 | Acc=0.2602


Confusion matrix:
 [[ 5 11  1 24]
 [ 2 10  0 19]
 [ 1  3  5 21]
 [ 0  3  2  9]]
Train  loss=3.4261 acc=0.2602 f1=0.2591 | Val loss=6.5517 acc=0.2500 f1=0.2547
  🔥 New best F1: 0.2547 – model saved.

Epoch 5/8


    t_loss=3.2852 | F1(macro)=0.2955 | Acc=0.2989


Confusion matrix:
 [[ 1  9  8 23]
 [ 1  7  2 21]
 [ 2  3  5 20]
 [ 0  2  2 10]]
Train  loss=3.2852 acc=0.2989 f1=0.2955 | Val loss=7.4259 acc=0.1983 f1=0.1884

Epoch 6/8


    t_loss=3.5332 | F1(macro)=0.2672 | Acc=0.2688


Confusion matrix:
 [[ 3  8  3 27]
 [ 2  6  1 22]
 [ 2  2  6 20]
 [ 0  1  1 12]]
Train  loss=3.5332 acc=0.2688 f1=0.2672 | Val loss=6.8370 acc=0.2328 f1=0.2301

Epoch 7/8


    t_loss=3.3718 | F1(macro)=0.2563 | Acc=0.2602


Confusion matrix:
 [[ 3  8  4 26]
 [ 0  8  0 23]
 [ 0  3  4 23]
 [ 0  1  1 12]]
Train  loss=3.3718 acc=0.2602 f1=0.2563 | Val loss=6.8173 acc=0.2328 f1=0.2250

Epoch 8/8


    t_loss=3.3203 | F1(macro)=0.2631 | Acc=0.2645


Confusion matrix:
 [[ 2 14  2 23]
 [ 1  7  2 21]
 [ 0  1  6 23]
 [ 0  2  0 12]]
Train  loss=3.3203 acc=0.2645 f1=0.2631 | Val loss=7.2895 acc=0.2328 f1=0.2259
Restored best Stage 1 weights for fold 3 (F1=0.2547)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=3.2422 | F1(macro)=0.2478 | Acc=0.2581


Confusion matrix:
 [[ 3 13  9 16]
 [ 1 11  6 13]
 [ 1  5  7 17]
 [ 2  1  4  7]]
Train  loss=3.2422 acc=0.2581 f1=0.2478 | Val loss=5.3022 acc=0.2414 f1=0.2362
  🔥 New best F1: 0.2362 – model saved.

Epoch 2/12


    t_loss=2.5616 | F1(macro)=0.3253 | Acc=0.3398


Confusion matrix:
 [[ 4  4 15 18]
 [ 7  3  7 14]
 [ 4  3 10 13]
 [ 0  0  5  9]]
Train  loss=2.5616 acc=0.3398 f1=0.3253 | Val loss=4.7850 acc=0.2241 f1=0.2131

Epoch 3/12


    t_loss=2.1575 | F1(macro)=0.3649 | Acc=0.3763


Confusion matrix:
 [[ 4  9  8 20]
 [ 6  8  4 13]
 [ 5  6  8 11]
 [ 0  2  4  8]]
Train  loss=2.1575 acc=0.3763 f1=0.3649 | Val loss=4.2484 acc=0.2414 f1=0.2418
  🔥 New best F1: 0.2418 – model saved.

Epoch 4/12


    t_loss=2.1237 | F1(macro)=0.3448 | Acc=0.3527


Confusion matrix:
 [[ 3  5  3 30]
 [ 1  3  0 27]
 [ 3  1  2 24]
 [ 0  0  1 13]]
Train  loss=2.1237 acc=0.3527 f1=0.3448 | Val loss=5.2080 acc=0.1810 f1=0.1567

Epoch 5/12


    t_loss=1.9332 | F1(macro)=0.3587 | Acc=0.3720


Confusion matrix:
 [[12  9  1 19]
 [ 5  6  0 20]
 [ 6  2  1 21]
 [ 1  0  1 12]]
Train  loss=1.9332 acc=0.3720 f1=0.3587 | Val loss=4.0049 acc=0.2672 f1=0.2397

Epoch 6/12


    t_loss=1.6619 | F1(macro)=0.3939 | Acc=0.4108


Confusion matrix:
 [[18  4  1 18]
 [14  4  3 10]
 [ 9  4  3 14]
 [ 2  0  2 10]]
Train  loss=1.6619 acc=0.4108 f1=0.3939 | Val loss=2.9829 acc=0.3017 f1=0.2679
  🔥 New best F1: 0.2679 – model saved.

Epoch 7/12


    t_loss=1.4946 | F1(macro)=0.4078 | Acc=0.4237


Confusion matrix:
 [[12  7  5 17]
 [ 8  7  7  9]
 [ 7  4  4 15]
 [ 1  1  2 10]]
Train  loss=1.4946 acc=0.4237 f1=0.4078 | Val loss=2.8468 acc=0.2845 f1=0.2755
  🔥 New best F1: 0.2755 – model saved.

Epoch 8/12


    t_loss=1.4837 | F1(macro)=0.4316 | Acc=0.4366


Confusion matrix:
 [[10 16  5 10]
 [ 6 11  6  8]
 [ 8  4  4 14]
 [ 2  1  3  8]]
Train  loss=1.4837 acc=0.4366 f1=0.4316 | Val loss=2.7231 acc=0.2845 f1=0.2777
  🔥 New best F1: 0.2777 – model saved.

Epoch 9/12


    t_loss=1.3803 | F1(macro)=0.4252 | Acc=0.4409


Confusion matrix:
 [[ 3 16 14  8]
 [ 0 17  5  9]
 [ 2  5  7 16]
 [ 0  2  4  8]]
Train  loss=1.3803 acc=0.4409 f1=0.4252 | Val loss=2.8030 acc=0.3017 f1=0.2834
  🔥 New best F1: 0.2834 – model saved.

Epoch 10/12


    t_loss=1.3516 | F1(macro)=0.4272 | Acc=0.4430


Confusion matrix:
 [[10 15  5 11]
 [14 11  0  6]
 [ 8  7  4 11]
 [ 1  3  2  8]]
Train  loss=1.3516 acc=0.4430 f1=0.4272 | Val loss=2.6501 acc=0.2845 f1=0.2784

Epoch 11/12


    t_loss=1.2600 | F1(macro)=0.4969 | Acc=0.5032


Confusion matrix:
 [[ 7 17  4 13]
 [ 8 11  2 10]
 [ 6  8  5 11]
 [ 1  2  2  9]]
Train  loss=1.2600 acc=0.5032 f1=0.4969 | Val loss=2.9971 acc=0.2759 f1=0.2724

Epoch 12/12


    t_loss=1.3843 | F1(macro)=0.4492 | Acc=0.4624


Confusion matrix:
 [[ 6 16  5 14]
 [ 7 14  0 10]
 [ 4 12  2 12]
 [ 2  5  1  6]]
Train  loss=1.3843 acc=0.4624 f1=0.4492 | Val loss=3.1634 acc=0.2414 f1=0.2196

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=5.1601 | F1(macro)=0.2355 | Acc=0.2387


Confusion matrix:
 [[20  8 12  1]
 [16  5  7  4]
 [19  3  6  2]
 [ 8  2  2  1]]
Train  loss=5.1601 acc=0.2387 f1=0.2355 | Val loss=5.6858 acc=0.2759 f1=0.2226
  🔥 New best F1: 0.2226 – model saved.

Epoch 2/8


    t_loss=4.2450 | F1(macro)=0.2336 | Acc=0.2323


Confusion matrix:
 [[28  3  8  2]
 [25  4  1  2]
 [23  0  4  3]
 [ 9  2  1  1]]
Train  loss=4.2450 acc=0.2323 f1=0.2336 | Val loss=6.8618 acc=0.3190 f1=0.2292
  🔥 New best F1: 0.2292 – model saved.

Epoch 3/8


    t_loss=3.6269 | F1(macro)=0.2593 | Acc=0.2602


Confusion matrix:
 [[24  4  9  4]
 [17  5  7  3]
 [18  2  7  3]
 [ 9  1  1  2]]
Train  loss=3.6269 acc=0.2602 f1=0.2593 | Val loss=5.4187 acc=0.3276 f1=0.2717
  🔥 New best F1: 0.2717 – model saved.

Epoch 4/8


    t_loss=3.3035 | F1(macro)=0.2732 | Acc=0.2753


Confusion matrix:
 [[27  3  7  4]
 [22  1  6  3]
 [15  3  9  3]
 [ 8  1  1  3]]
Train  loss=3.3035 acc=0.2753 f1=0.2732 | Val loss=5.5303 acc=0.3448 f1=0.2746
  🔥 New best F1: 0.2746 – model saved.

Epoch 5/8


    t_loss=3.2051 | F1(macro)=0.3052 | Acc=0.3097


Confusion matrix:
 [[23  3 12  3]
 [21  2  6  3]
 [16  1  6  7]
 [ 8  0  1  4]]
Train  loss=3.2051 acc=0.3097 f1=0.3052 | Val loss=5.8359 acc=0.3017 f1=0.2530

Epoch 6/8


    t_loss=3.1839 | F1(macro)=0.2724 | Acc=0.2774


Confusion matrix:
 [[23  4 12  2]
 [25  2  3  2]
 [20  1  5  4]
 [ 9  1  1  2]]
Train  loss=3.1839 acc=0.2774 f1=0.2724 | Val loss=6.2730 acc=0.2759 f1=0.2150

Epoch 7/8


    t_loss=2.8221 | F1(macro)=0.3223 | Acc=0.3247


Confusion matrix:
 [[25  3 10  3]
 [22  1  6  3]
 [21  1  4  4]
 [ 8  1  2  2]]
Train  loss=2.8221 acc=0.3247 f1=0.3223 | Val loss=5.8106 acc=0.2759 f1=0.1985

Epoch 8/8


    t_loss=3.1984 | F1(macro)=0.2583 | Acc=0.2602


Confusion matrix:
 [[29  3  6  3]
 [22  3  6  1]
 [17  2  6  5]
 [ 8  1  1  3]]
Train  loss=3.1984 acc=0.2602 f1=0.2583 | Val loss=5.8658 acc=0.3534 f1=0.2817
  🔥 New best F1: 0.2817 – model saved.
Restored best Stage 1 weights for fold 4 (F1=0.2817)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=2.9686 | F1(macro)=0.3007 | Acc=0.3118


Confusion matrix:
 [[22  3 14  2]
 [16  4  9  3]
 [16  3  7  4]
 [ 7  1  3  2]]
Train  loss=2.9686 acc=0.3118 f1=0.3007 | Val loss=5.0235 acc=0.3017 f1=0.2516
  🔥 New best F1: 0.2516 – model saved.

Epoch 2/12


    t_loss=2.2600 | F1(macro)=0.3485 | Acc=0.3763


Confusion matrix:
 [[23 12  4  2]
 [14 10  4  4]
 [19  7  3  1]
 [ 7  4  1  1]]
Train  loss=2.2600 acc=0.3763 f1=0.3485 | Val loss=4.2166 acc=0.3190 f1=0.2470

Epoch 3/12


    t_loss=2.0901 | F1(macro)=0.3632 | Acc=0.3785


Confusion matrix:
 [[23  6 11  1]
 [17  8  6  1]
 [16  5  7  2]
 [ 6  4  1  2]]
Train  loss=2.0901 acc=0.3785 f1=0.3632 | Val loss=3.6250 acc=0.3448 f1=0.3006
  🔥 New best F1: 0.3006 – model saved.

Epoch 4/12


    t_loss=1.8766 | F1(macro)=0.3551 | Acc=0.3634


Confusion matrix:
 [[20  8 11  2]
 [14  7 10  1]
 [15  2  9  4]
 [ 6  2  4  1]]
Train  loss=1.8766 acc=0.3634 f1=0.3551 | Val loss=3.3722 acc=0.3190 f1=0.2669

Epoch 5/12


    t_loss=1.5433 | F1(macro)=0.3973 | Acc=0.4065


Confusion matrix:
 [[13 10 11  7]
 [12 11  7  2]
 [ 7  4 12  7]
 [ 3  1  4  5]]
Train  loss=1.5433 acc=0.4065 f1=0.3973 | Val loss=2.6997 acc=0.3534 f1=0.3476
  🔥 New best F1: 0.3476 – model saved.

Epoch 6/12


    t_loss=1.5025 | F1(macro)=0.4103 | Acc=0.4258


Confusion matrix:
 [[12 18  9  2]
 [14 10  7  1]
 [10  9  7  4]
 [ 3  4  4  2]]
Train  loss=1.5025 acc=0.4258 f1=0.4103 | Val loss=2.8102 acc=0.2672 f1=0.2504

Epoch 7/12


    t_loss=1.4356 | F1(macro)=0.4238 | Acc=0.4430


Confusion matrix:
 [[25  3  9  4]
 [20  2  7  3]
 [22  1  3  4]
 [ 8  1  3  1]]
Train  loss=1.4356 acc=0.4430 f1=0.4238 | Val loss=2.8757 acc=0.2672 f1=0.1822

Epoch 8/12


    t_loss=1.3098 | F1(macro)=0.4315 | Acc=0.4538


Confusion matrix:
 [[22  6 10  3]
 [12  6 12  2]
 [ 7  2 16  5]
 [ 8  1  3  1]]
Train  loss=1.3098 acc=0.4538 f1=0.4315 | Val loss=2.5226 acc=0.3879 f1=0.3196

Epoch 9/12


    t_loss=1.1705 | F1(macro)=0.4839 | Acc=0.5032


Confusion matrix:
 [[14 14 11  2]
 [ 9  9 11  3]
 [ 9  4 15  2]
 [ 6  1  3  3]]
Train  loss=1.1705 acc=0.5032 f1=0.4839 | Val loss=2.3999 acc=0.3534 f1=0.3360

Epoch 10/12


    t_loss=1.2506 | F1(macro)=0.4437 | Acc=0.4602


Confusion matrix:
 [[ 9  8 22  2]
 [ 9  7 13  3]
 [ 5  2 18  5]
 [ 3  0  5  5]]
Train  loss=1.2506 acc=0.4602 f1=0.4437 | Val loss=2.7392 acc=0.3362 f1=0.3302

Epoch 11/12


    t_loss=1.1428 | F1(macro)=0.5103 | Acc=0.5355


Confusion matrix:
 [[12 13 15  1]
 [12  9 10  1]
 [ 7  5 14  4]
 [ 4  2  6  1]]
Train  loss=1.1428 acc=0.5355 f1=0.5103 | Val loss=2.8681 acc=0.3103 f1=0.2711

Epoch 12/12


    t_loss=1.2658 | F1(macro)=0.4722 | Acc=0.4903


Confusion matrix:
 [[12 14  9  6]
 [12  9  9  2]
 [13  4  9  4]
 [ 3  3  3  4]]
Train  loss=1.2658 acc=0.4903 f1=0.4722 | Val loss=2.6683 acc=0.2931 f1=0.2906


# convnext_tiny

In [4]:
if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            train_df_split,
            transforms=train_transforms,
            is_train=True,
            image_size=IMAGE_SIZE
        )
        val_dataset = HistologyDataset(
            val_df_split,
            transforms=val_test_transforms,
            is_train=True,
            image_size=IMAGE_SIZE
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = timm.create_model(
            PRETRAINED_MODEL,
            pretrained=True,
            num_classes=N_CLASSES
        ).to(device)

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

In [5]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny"

test_dataset = HistologyDataset(
    test_df,
    transforms=val_test_transforms,
    is_train=False,   # returns (img, sample_index)
    image_size=IMAGE_SIZE
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=False,
        num_classes=N_CLASSES
    ).to(device)
    state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv("submission_5fold_no_tta.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png        Luminal A
1  img_0001.png        Luminal B
2  img_0002.png  Triple negative
3  img_0003.png        Luminal B
4  img_0004.png        Luminal B


In [8]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(test_df, transforms=val_test_transforms, is_train=False, image_size=IMAGE_SIZE)
test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
                         shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")
    model = timm.create_model(PRETRAINED_MODEL, pretrained=False, num_classes=N_CLASSES).to(device)
    model.load_state_dict(torch.load(f"effv2_s_fold{fold}.pth", map_location=device))
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            img_tensor = img_tensor.squeeze(0)  # [3,H,W]
            img_tensor = img_tensor.to(device)

            # -------- TTA: apply multiple augmented views --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1,4]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N, 4]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
pred_indices = mean_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv("submission_5fold_tta.csv", index=False)

print("Saved submission_5fold_tta.csv")

Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_tta.csv


In [7]:
from internal.nn.test_time_augmentation import apply_tta
from sklearn.metrics import f1_score
from torch.nn.functional import softmax

def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(val_df_split, transforms=val_test_transforms, is_train=True, image_size=IMAGE_SIZE)
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    model = timm.create_model(PRETRAINED_MODEL, pretrained=False, num_classes=N_CLASSES).to(device)
    model.load_state_dict(torch.load(f"effv2_s_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.23500724208308646
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.21726200673987575
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.31500159676389183
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.24750116118744675
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.32576610381488436
Mean OOF F1: 0.268107622117837
