In [1]:
import enum
import os
from copy import deepcopy

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B0

In [4]:
best_f1_per_fold: dict[int, int] = {}

In [5]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_blocks_and_head(model: nn.Module):
    freeze_all(model)

    # unfreeze last 2 conv blocks
    if hasattr(model, "blocks"):
        for blk in model.blocks[-2:]:
            for p in blk.parameters():
                p.requires_grad = True

    # unfreeze classifier head
    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True


if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 5
    LR_STAGE1 = 1e-3
    LR_STAGE2 = 3e-5
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_efficientnet_b0_model()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        freeze_all(model)

        # --- 1.1. unfreeze only the classifier head ---
        clf_module, _ = get_classifier_module(model)
        for p in clf_module.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR_STAGE1,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_{PREFIX}_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        unfreeze_last_blocks_and_head(model)

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR_STAGE2,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_{PREFIX}_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights
            print(f"Restored best Stage 2 weights for fold {fold} (F1={best_f1:.4f})")

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"{PREFIX}_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.5868 | F1(macro)=0.2909 | Acc=0.2974


Confusion matrix:
 [[14 13 11  3]
 [ 9  7  8  8]
 [ 9 15  4  2]
 [ 2  7  5  0]]
Train  loss=2.5868 acc=0.2974 f1=0.2909 | Val loss=2.7594 acc=0.2137 f1=0.1751
  🔥 New best F1: 0.1751 – model saved.

Epoch 2/8


    t_loss=2.6139 | F1(macro)=0.2594 | Acc=0.2672


Confusion matrix:
 [[14 16  9  2]
 [ 4 19  4  5]
 [ 8 18  3  1]
 [ 3  8  3  0]]
Train  loss=2.6139 acc=0.2672 f1=0.2594 | Val loss=2.6265 acc=0.3077 f1=0.2328
  🔥 New best F1: 0.2328 – model saved.

Epoch 3/8


    t_loss=2.3664 | F1(macro)=0.2937 | Acc=0.2931


Confusion matrix:
 [[ 8 17 11  5]
 [ 4 16  6  6]
 [ 4 19  4  3]
 [ 1  9  3  1]]
Train  loss=2.3664 acc=0.2931 f1=0.2937 | Val loss=2.6797 acc=0.2479 f1=0.2093

Epoch 4/8


    t_loss=2.5177 | F1(macro)=0.2626 | Acc=0.2672


Confusion matrix:
 [[ 3 25  9  4]
 [ 2 18  5  7]
 [ 2 19  6  3]
 [ 0 10  4  0]]
Train  loss=2.5177 acc=0.2672 f1=0.2626 | Val loss=2.7952 acc=0.2308 f1=0.1733

Epoch 5/8


    t_loss=2.3812 | F1(macro)=0.2820 | Acc=0.2866


Confusion matrix:
 [[ 9 14 16  2]
 [ 4 15  7  6]
 [ 4 16  7  3]
 [ 2  8  4  0]]
Train  loss=2.3812 acc=0.2866 f1=0.2820 | Val loss=2.5695 acc=0.2650 f1=0.2179

Epoch 6/8


    t_loss=2.5172 | F1(macro)=0.2655 | Acc=0.2672


Confusion matrix:
 [[ 9 14 15  3]
 [ 2 17  8  5]
 [ 2 19  8  1]
 [ 2  8  4  0]]
Train  loss=2.5172 acc=0.2672 f1=0.2655 | Val loss=2.5743 acc=0.2906 f1=0.2363
  🔥 New best F1: 0.2363 – model saved.

Epoch 7/8


    t_loss=2.5751 | F1(macro)=0.2501 | Acc=0.2500


Confusion matrix:
 [[ 6 15 15  5]
 [ 4 13  8  7]
 [ 2 13 12  3]
 [ 2  7  5  0]]
Train  loss=2.5751 acc=0.2500 f1=0.2501 | Val loss=2.4483 acc=0.2650 f1=0.2215

Epoch 8/8


    t_loss=2.3858 | F1(macro)=0.2759 | Acc=0.2780


Confusion matrix:
 [[10 15 12  4]
 [ 6 12  7  7]
 [ 3 14 10  3]
 [ 2  7  5  0]]
Train  loss=2.3858 acc=0.2780 f1=0.2759 | Val loss=2.5445 acc=0.2735 f1=0.2338
Restored best Stage 1 weights for fold 0 (F1=0.2363)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=2.3482 | F1(macro)=0.2713 | Acc=0.2737


Confusion matrix:
 [[ 7 13 15  6]
 [ 3 12  7 10]
 [ 1 14 11  4]
 [ 2  7  4  1]]
Train  loss=2.3482 acc=0.2737 f1=0.2713 | Val loss=2.5826 acc=0.2650 f1=0.2381
  🔥 New best F1: 0.2381 – model saved.

Epoch 2/5


    t_loss=2.1642 | F1(macro)=0.2582 | Acc=0.2716


Confusion matrix:
 [[ 5 18  7 11]
 [ 5 11  4 12]
 [ 1 14  7  8]
 [ 2  8  3  1]]
Train  loss=2.1642 acc=0.2716 f1=0.2582 | Val loss=2.6942 acc=0.2051 f1=0.1921

Epoch 3/5


    t_loss=2.0206 | F1(macro)=0.3151 | Acc=0.3276


Confusion matrix:
 [[ 7 11 19  4]
 [ 4 10  9  9]
 [ 2  9 12  7]
 [ 1  6  7  0]]
Train  loss=2.0206 acc=0.3276 f1=0.3151 | Val loss=2.6070 acc=0.2479 f1=0.2151

Epoch 4/5


    t_loss=2.0671 | F1(macro)=0.2809 | Acc=0.2931


Confusion matrix:
 [[ 4 14 17  6]
 [ 5 13  6  8]
 [ 0 13 11  6]
 [ 1  7  6  0]]
Train  loss=2.0671 acc=0.2931 f1=0.2809 | Val loss=2.5628 acc=0.2393 f1=0.2001

Epoch 5/5


    t_loss=2.0011 | F1(macro)=0.3004 | Acc=0.3147


Confusion matrix:
 [[ 3 13 18  7]
 [ 2 11 10  9]
 [ 0 12 12  6]
 [ 0  7  6  1]]
Train  loss=2.0011 acc=0.3147 f1=0.3004 | Val loss=2.6561 acc=0.2308 f1=0.1984
Restored best Stage 2 weights for fold 0 (F1=0.2381)

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.8648 | F1(macro)=0.2387 | Acc=0.2409


Confusion matrix:
 [[13  1 14 12]
 [ 6  5 14  7]
 [ 8  2  7 13]
 [ 5  0  2  7]]
Train  loss=2.8648 acc=0.2409 f1=0.2387 | Val loss=2.8983 acc=0.2759 f1=0.2711
  🔥 New best F1: 0.2711 – model saved.

Epoch 2/8


    t_loss=2.7223 | F1(macro)=0.2365 | Acc=0.2387


Confusion matrix:
 [[13  0  8 19]
 [ 9  4 10  9]
 [ 8  4  7 11]
 [ 3  0  2  9]]
Train  loss=2.7223 acc=0.2387 f1=0.2365 | Val loss=2.7032 acc=0.2845 f1=0.2730
  🔥 New best F1: 0.2730 – model saved.

Epoch 3/8


    t_loss=2.5574 | F1(macro)=0.2787 | Acc=0.2839


Confusion matrix:
 [[12  0 11 17]
 [ 9  4 12  7]
 [ 7  3 11  9]
 [ 4  0  5  5]]
Train  loss=2.5574 acc=0.2839 f1=0.2787 | Val loss=2.5802 acc=0.2759 f1=0.2624

Epoch 4/8


    t_loss=2.4454 | F1(macro)=0.3133 | Acc=0.3183


Confusion matrix:
 [[13  0 13 14]
 [ 8  3 12  9]
 [ 8  3  7 12]
 [ 3  0  4  7]]
Train  loss=2.4454 acc=0.3183 f1=0.3133 | Val loss=2.4772 acc=0.2586 f1=0.2453

Epoch 5/8


    t_loss=2.2184 | F1(macro)=0.2635 | Acc=0.2645


Confusion matrix:
 [[11  0 16 13]
 [ 6  5 12  9]
 [ 7  3 10 10]
 [ 5  0  3  6]]
Train  loss=2.2184 acc=0.2645 f1=0.2635 | Val loss=2.5021 acc=0.2759 f1=0.2703

Epoch 6/8


    t_loss=2.3838 | F1(macro)=0.2870 | Acc=0.2968


Confusion matrix:
 [[17  1 12 10]
 [11  5  7  9]
 [10  3  5 12]
 [ 5  0  3  6]]
Train  loss=2.3838 acc=0.2968 f1=0.2870 | Val loss=2.4504 acc=0.2845 f1=0.2661

Epoch 7/8


    t_loss=2.5479 | F1(macro)=0.2666 | Acc=0.2688


Confusion matrix:
 [[12  3 11 14]
 [ 5  7 12  8]
 [ 5  5  6 14]
 [ 5  0  3  6]]
Train  loss=2.5479 acc=0.2688 f1=0.2666 | Val loss=2.5111 acc=0.2672 f1=0.2660

Epoch 8/8


    t_loss=2.2985 | F1(macro)=0.2881 | Acc=0.2860


Confusion matrix:
 [[13  0 13 14]
 [ 7  4 10 11]
 [ 5  2  9 14]
 [ 3  0  4  7]]
Train  loss=2.2985 acc=0.2860 f1=0.2881 | Val loss=2.5922 acc=0.2845 f1=0.2747
  🔥 New best F1: 0.2747 – model saved.
Restored best Stage 1 weights for fold 1 (F1=0.2747)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=2.2646 | F1(macro)=0.3142 | Acc=0.3161


Confusion matrix:
 [[ 9  0 12 19]
 [ 6  3  9 14]
 [ 5  3  7 15]
 [ 3  0  4  7]]
Train  loss=2.2646 acc=0.3161 f1=0.3142 | Val loss=2.7814 acc=0.2241 f1=0.2181
  🔥 New best F1: 0.2181 – model saved.

Epoch 2/5


    t_loss=2.1983 | F1(macro)=0.2669 | Acc=0.2796


Confusion matrix:
 [[ 9  0  6 25]
 [ 5  4  5 18]
 [ 5  3  5 17]
 [ 2  0  4  8]]
Train  loss=2.1983 acc=0.2796 f1=0.2669 | Val loss=2.7190 acc=0.2241 f1=0.2238
  🔥 New best F1: 0.2238 – model saved.

Epoch 3/5


    t_loss=2.0677 | F1(macro)=0.2959 | Acc=0.3097


Confusion matrix:
 [[ 8  8  5 19]
 [ 5  6  6 15]
 [ 6 10  4 10]
 [ 5  1  3  5]]
Train  loss=2.0677 acc=0.3097 f1=0.2959 | Val loss=2.4166 acc=0.1983 f1=0.1965

Epoch 4/5


    t_loss=1.9256 | F1(macro)=0.2946 | Acc=0.3140


Confusion matrix:
 [[ 8  2  6 24]
 [ 4  6  5 17]
 [ 6  8  4 12]
 [ 1  0  3 10]]
Train  loss=1.9256 acc=0.3140 f1=0.2946 | Val loss=2.4576 acc=0.2414 f1=0.2369
  🔥 New best F1: 0.2369 – model saved.

Epoch 5/5


    t_loss=1.9343 | F1(macro)=0.3116 | Acc=0.3269


Confusion matrix:
 [[11  1  6 22]
 [ 5  4  7 16]
 [ 8  6  2 14]
 [ 3  0  4  7]]
Train  loss=1.9343 acc=0.3269 f1=0.3116 | Val loss=2.3163 acc=0.2069 f1=0.1970
Restored best Stage 2 weights for fold 1 (F1=0.2369)

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.9278 | F1(macro)=0.2129 | Acc=0.2151


Confusion matrix:
 [[17  9 13  2]
 [12  7  8  4]
 [13  3 11  3]
 [ 5  3  5  1]]
Train  loss=2.9278 acc=0.2151 f1=0.2129 | Val loss=2.3307 acc=0.3103 f1=0.2656
  🔥 New best F1: 0.2656 – model saved.

Epoch 2/8


    t_loss=2.3897 | F1(macro)=0.2713 | Acc=0.2710


Confusion matrix:
 [[20  7 12  2]
 [12 10  3  6]
 [14  4  7  5]
 [ 4  4  4  2]]
Train  loss=2.3897 acc=0.2710 f1=0.2713 | Val loss=2.2100 acc=0.3362 f1=0.2962
  🔥 New best F1: 0.2962 – model saved.

Epoch 3/8


    t_loss=2.4838 | F1(macro)=0.2709 | Acc=0.2710


Confusion matrix:
 [[21  2 14  4]
 [12  3  7  9]
 [11  2 12  5]
 [ 4  2  4  4]]
Train  loss=2.4838 acc=0.2710 f1=0.2709 | Val loss=2.3026 acc=0.3448 f1=0.3006
  🔥 New best F1: 0.3006 – model saved.

Epoch 4/8


    t_loss=2.5043 | F1(macro)=0.2927 | Acc=0.2946


Confusion matrix:
 [[23  5 10  3]
 [13  6  4  8]
 [11  3 11  5]
 [ 5  3  4  2]]
Train  loss=2.5043 acc=0.2946 f1=0.2927 | Val loss=2.1808 acc=0.3621 f1=0.3106
  🔥 New best F1: 0.3106 – model saved.

Epoch 5/8


    t_loss=2.4276 | F1(macro)=0.2820 | Acc=0.2817


Confusion matrix:
 [[13  8 17  3]
 [10  6  7  8]
 [ 9  2 14  5]
 [ 2  3  6  3]]
Train  loss=2.4276 acc=0.2817 f1=0.2820 | Val loss=2.1444 acc=0.3103 f1=0.2867

Epoch 6/8


    t_loss=2.2545 | F1(macro)=0.2525 | Acc=0.2538


Confusion matrix:
 [[15  6 19  1]
 [10  9  7  5]
 [11  4 12  3]
 [ 4  2  6  2]]
Train  loss=2.2545 acc=0.2538 f1=0.2525 | Val loss=2.1368 acc=0.3276 f1=0.3002

Epoch 7/8


    t_loss=2.3624 | F1(macro)=0.2857 | Acc=0.2882


Confusion matrix:
 [[16  6 15  4]
 [10  8  5  8]
 [10  5  9  6]
 [ 3  2  5  4]]
Train  loss=2.3624 acc=0.2882 f1=0.2857 | Val loss=2.1531 acc=0.3190 f1=0.3028

Epoch 8/8


    t_loss=2.4841 | F1(macro)=0.2629 | Acc=0.2645


Confusion matrix:
 [[15 10 13  3]
 [ 9  9  4  9]
 [ 9  3 12  6]
 [ 4  3  6  1]]
Train  loss=2.4841 acc=0.2645 f1=0.2629 | Val loss=2.1392 acc=0.3190 f1=0.2840
Restored best Stage 1 weights for fold 2 (F1=0.3106)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=2.3905 | F1(macro)=0.2616 | Acc=0.2624


Confusion matrix:
 [[13  6 18  4]
 [ 6  3 12 10]
 [ 8  3 13  6]
 [ 4  2  5  3]]
Train  loss=2.3905 acc=0.2624 f1=0.2616 | Val loss=2.4015 acc=0.2759 f1=0.2475
  🔥 New best F1: 0.2475 – model saved.

Epoch 2/5


    t_loss=2.2647 | F1(macro)=0.2633 | Acc=0.2710


Confusion matrix:
 [[16  4 15  6]
 [11  3  8  9]
 [11  1  9  9]
 [ 3  1  5  5]]
Train  loss=2.2647 acc=0.2710 f1=0.2633 | Val loss=2.4296 acc=0.2845 f1=0.2604
  🔥 New best F1: 0.2604 – model saved.

Epoch 3/5


    t_loss=2.0218 | F1(macro)=0.3054 | Acc=0.3269


Confusion matrix:
 [[12  5 17  7]
 [ 8  5  8 10]
 [ 7  4 11  8]
 [ 2  2  5  5]]
Train  loss=2.0218 acc=0.3269 f1=0.3054 | Val loss=2.3543 acc=0.2845 f1=0.2732
  🔥 New best F1: 0.2732 – model saved.

Epoch 4/5


    t_loss=2.0376 | F1(macro)=0.2554 | Acc=0.2817


Confusion matrix:
 [[ 7  2 22 10]
 [ 7  3 11 10]
 [ 6  2 14  8]
 [ 2  1  5  6]]
Train  loss=2.0376 acc=0.2817 f1=0.2554 | Val loss=2.5888 acc=0.2586 f1=0.2419

Epoch 5/5


    t_loss=2.0278 | F1(macro)=0.2759 | Acc=0.2839


Confusion matrix:
 [[12  1 21  7]
 [ 6  3 12 10]
 [ 5  2 16  7]
 [ 2  1  6  5]]
Train  loss=2.0278 acc=0.2839 f1=0.2759 | Val loss=2.4298 acc=0.3103 f1=0.2826
  🔥 New best F1: 0.2826 – model saved.
Restored best Stage 2 weights for fold 2 (F1=0.2826)

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=3.1116 | F1(macro)=0.2212 | Acc=0.2258


Confusion matrix:
 [[10  5 21  5]
 [10  6 10  5]
 [ 5  4 17  4]
 [ 2  4  5  3]]
Train  loss=3.1116 acc=0.2258 f1=0.2212 | Val loss=2.1846 acc=0.3103 f1=0.2843
  🔥 New best F1: 0.2843 – model saved.

Epoch 2/8


    t_loss=2.4892 | F1(macro)=0.2651 | Acc=0.2645


Confusion matrix:
 [[12  3 20  6]
 [ 5  8 13  5]
 [ 4  4 15  7]
 [ 4  3  5  2]]
Train  loss=2.4892 acc=0.2645 f1=0.2651 | Val loss=2.1455 acc=0.3190 f1=0.2923
  🔥 New best F1: 0.2923 – model saved.

Epoch 3/8


    t_loss=2.3512 | F1(macro)=0.2968 | Acc=0.3011


Confusion matrix:
 [[ 8  4 19 10]
 [ 3 10 13  5]
 [ 5  2 15  8]
 [ 2  3  7  2]]
Train  loss=2.3512 acc=0.3011 f1=0.2968 | Val loss=2.1584 acc=0.3017 f1=0.2827

Epoch 4/8


    t_loss=2.4253 | F1(macro)=0.2596 | Acc=0.2624


Confusion matrix:
 [[14  4 14  9]
 [ 8 10  6  7]
 [ 6  3 13  8]
 [ 3  3  5  3]]
Train  loss=2.4253 acc=0.2624 f1=0.2596 | Val loss=1.9807 acc=0.3448 f1=0.3274
  🔥 New best F1: 0.3274 – model saved.

Epoch 5/8


    t_loss=2.5333 | F1(macro)=0.2207 | Acc=0.2215


Confusion matrix:
 [[16  3 12 10]
 [ 8  8  7  8]
 [11  5  7  7]
 [ 3  3  6  2]]
Train  loss=2.5333 acc=0.2215 f1=0.2207 | Val loss=2.1028 acc=0.2845 f1=0.2621

Epoch 6/8


    t_loss=2.3408 | F1(macro)=0.2669 | Acc=0.2667


Confusion matrix:
 [[11  4 20  6]
 [ 8  5 15  3]
 [ 7  2 18  3]
 [ 2  4  6  2]]
Train  loss=2.3408 acc=0.2667 f1=0.2669 | Val loss=2.0303 acc=0.3103 f1=0.2709

Epoch 7/8


    t_loss=2.5243 | F1(macro)=0.2440 | Acc=0.2452


Confusion matrix:
 [[12  4 17  8]
 [12  6  9  4]
 [ 7  3 14  6]
 [ 4  0  5  5]]
Train  loss=2.5243 acc=0.2452 f1=0.2440 | Val loss=2.1049 acc=0.3190 f1=0.3080

Epoch 8/8


    t_loss=2.4507 | F1(macro)=0.2548 | Acc=0.2581


Confusion matrix:
 [[17  5 17  2]
 [11  9  7  4]
 [ 7  5 15  3]
 [ 6  4  4  0]]
Train  loss=2.4507 acc=0.2581 f1=0.2548 | Val loss=1.8464 acc=0.3534 f1=0.2897
Restored best Stage 1 weights for fold 3 (F1=0.3274)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=2.2863 | F1(macro)=0.2740 | Acc=0.2774


Confusion matrix:
 [[17  4 10 10]
 [14  3  9  5]
 [13  4  7  6]
 [ 7  2  2  3]]
Train  loss=2.2863 acc=0.2774 f1=0.2740 | Val loss=2.1854 acc=0.2586 f1=0.2263
  🔥 New best F1: 0.2263 – model saved.

Epoch 2/5


    t_loss=2.1005 | F1(macro)=0.2930 | Acc=0.3054


Confusion matrix:
 [[11  4 15 11]
 [ 7  8  9  7]
 [ 7  3 14  6]
 [ 3  2  4  5]]
Train  loss=2.1005 acc=0.3054 f1=0.2930 | Val loss=2.0685 acc=0.3276 f1=0.3184
  🔥 New best F1: 0.3184 – model saved.

Epoch 3/5


    t_loss=2.0611 | F1(macro)=0.3278 | Acc=0.3333


Confusion matrix:
 [[ 9  7 15 10]
 [ 6 11  9  5]
 [ 8  4 13  5]
 [ 4  3  4  3]]
Train  loss=2.0611 acc=0.3333 f1=0.3278 | Val loss=2.0640 acc=0.3103 f1=0.2965

Epoch 4/5


    t_loss=1.9990 | F1(macro)=0.2859 | Acc=0.3054


Confusion matrix:
 [[13  7 12  9]
 [ 8 13  1  9]
 [ 6  6  9  9]
 [ 5  1  1  7]]
Train  loss=1.9990 acc=0.3054 f1=0.2859 | Val loss=1.7914 acc=0.3621 f1=0.3589
  🔥 New best F1: 0.3589 – model saved.

Epoch 5/5


    t_loss=1.9192 | F1(macro)=0.3115 | Acc=0.3226


Confusion matrix:
 [[ 9  5 16 11]
 [ 6  7 14  4]
 [ 4  2 17  7]
 [ 3  2  4  5]]
Train  loss=1.9192 acc=0.3226 f1=0.3115 | Val loss=2.0167 acc=0.3276 f1=0.3118
Restored best Stage 2 weights for fold 3 (F1=0.3589)

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.4869 | F1(macro)=0.2943 | Acc=0.2946


Confusion matrix:
 [[ 9  9 20  3]
 [ 4 15 11  2]
 [ 2 10 18  0]
 [ 4  4  5  0]]
Train  loss=2.4869 acc=0.2946 f1=0.2943 | Val loss=2.2435 acc=0.3621 f1=0.2893
  🔥 New best F1: 0.2893 – model saved.

Epoch 2/8


    t_loss=2.5010 | F1(macro)=0.2836 | Acc=0.2860


Confusion matrix:
 [[11  8 20  2]
 [ 5 14 12  1]
 [10  6 14  0]
 [ 5  6  2  0]]
Train  loss=2.5010 acc=0.2860 f1=0.2836 | Val loss=2.0866 acc=0.3362 f1=0.2722

Epoch 3/8


    t_loss=2.3595 | F1(macro)=0.3063 | Acc=0.3140


Confusion matrix:
 [[14  6 19  2]
 [12 11  8  1]
 [ 9  6 15  0]
 [ 6  4  3  0]]
Train  loss=2.3595 acc=0.3140 f1=0.3063 | Val loss=2.0422 acc=0.3448 f1=0.2786

Epoch 4/8


    t_loss=2.3622 | F1(macro)=0.2888 | Acc=0.2903


Confusion matrix:
 [[13  8 16  4]
 [ 9 13 10  0]
 [ 7 10 13  0]
 [ 6  4  2  1]]
Train  loss=2.3622 acc=0.2903 f1=0.2888 | Val loss=1.9350 acc=0.3448 f1=0.3019
  🔥 New best F1: 0.3019 – model saved.

Epoch 5/8


    t_loss=2.3249 | F1(macro)=0.2743 | Acc=0.2753


Confusion matrix:
 [[ 9  6 23  3]
 [ 7 11 13  1]
 [ 5  8 17  0]
 [ 3  4  6  0]]
Train  loss=2.3249 acc=0.2753 f1=0.2743 | Val loss=2.0100 acc=0.3190 f1=0.2549

Epoch 6/8


    t_loss=2.3228 | F1(macro)=0.2674 | Acc=0.2688


Confusion matrix:
 [[16  9 13  3]
 [10 13  8  1]
 [ 8  9 13  0]
 [ 5  4  4  0]]
Train  loss=2.3228 acc=0.2688 f1=0.2674 | Val loss=1.9324 acc=0.3621 f1=0.2926

Epoch 7/8


    t_loss=2.4296 | F1(macro)=0.2831 | Acc=0.2839


Confusion matrix:
 [[11  5 22  3]
 [ 9  9 12  2]
 [ 7  6 16  1]
 [ 5  3  5  0]]
Train  loss=2.4296 acc=0.2839 f1=0.2831 | Val loss=2.0340 acc=0.3103 f1=0.2513

Epoch 8/8


    t_loss=2.3414 | F1(macro)=0.3012 | Acc=0.3054


Confusion matrix:
 [[14 10 14  3]
 [ 9 14  8  1]
 [ 6 10 14  0]
 [ 6  3  3  1]]
Train  loss=2.3414 acc=0.3054 f1=0.3012 | Val loss=1.8041 acc=0.3707 f1=0.3228
  🔥 New best F1: 0.3228 – model saved.
Restored best Stage 1 weights for fold 4 (F1=0.3228)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=2.4062 | F1(macro)=0.2511 | Acc=0.2559


Confusion matrix:
 [[15  6 15  5]
 [11 10  8  3]
 [ 7 10 12  1]
 [ 6  3  3  1]]
Train  loss=2.4062 acc=0.2559 f1=0.2511 | Val loss=2.0855 acc=0.3276 f1=0.2857
  🔥 New best F1: 0.2857 – model saved.

Epoch 2/5


    t_loss=2.1262 | F1(macro)=0.3167 | Acc=0.3269


Confusion matrix:
 [[20  5 11  5]
 [16  7  6  3]
 [10  6 13  1]
 [ 6  2  3  2]]
Train  loss=2.1262 acc=0.3269 f1=0.3167 | Val loss=2.2626 acc=0.3621 f1=0.3197
  🔥 New best F1: 0.3197 – model saved.

Epoch 3/5


    t_loss=2.0353 | F1(macro)=0.3148 | Acc=0.3204


Confusion matrix:
 [[12  5 18  6]
 [ 8  8  8  8]
 [ 5  6 17  2]
 [ 5  3  4  1]]
Train  loss=2.0353 acc=0.3204 f1=0.3148 | Val loss=2.1119 acc=0.3276 f1=0.2856

Epoch 4/5


    t_loss=2.1386 | F1(macro)=0.2767 | Acc=0.2839


Confusion matrix:
 [[14  4 13 10]
 [10  7 10  5]
 [ 7  5 16  2]
 [ 6  2  5  0]]
Train  loss=2.1386 acc=0.2839 f1=0.2767 | Val loss=2.1317 acc=0.3190 f1=0.2679

Epoch 5/5


    t_loss=1.9473 | F1(macro)=0.2769 | Acc=0.2946


Confusion matrix:
 [[17  5 14  5]
 [ 9 10 11  2]
 [ 6  7 15  2]
 [ 6  3  2  2]]
Train  loss=1.9473 acc=0.2946 f1=0.2769 | Val loss=2.0145 acc=0.3793 f1=0.3411
  🔥 New best F1: 0.3411 – model saved.
Restored best Stage 2 weights for fold 4 (F1=0.3411)


# tf_efficientnetv2_s.in21k

In [6]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [7]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [8]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

# test_dataset = HistologyDataset(
#     df=test_df,
#     image_size=IMAGE_SIZE,
#     is_train=False,   # returns (img, sample_index)
#     use_mask_crop=True
# )
#
# test_loader = DataLoader(
#     test_dataset,
#     batch_size=BATCH_SIZE,
#     shuffle=False,
#     num_workers=N_WORKERS,
#     pin_memory=cuda_is_available
# )
#
# all_fold_probs = []   # list of arrays [N, num_classes]
# all_sample_indices = None
#
# for fold in range(N_FOLDS):
#     print(f"Inference with fold {fold} model")
#
#     # recreate model and load weights
#     if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
#         model = create_model_tf_efficientnetv2_s(pretrained=False)
#     elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
#         model = create_model_convnext(pretrained=False)
#     else:
#         model = create_efficientnet_b0_model(pretrained=False)
#     state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
#     model.load_state_dict(state)
#     model.eval()
#
#     fold_probs = []
#     sample_indices_list = []
#
#     with torch.no_grad():
#         for imgs, sample_indices in test_loader:
#             imgs = imgs.to(device, non_blocking=True)
#
#             logits = model(imgs)               # [B, num_classes]
#             probs = softmax(logits, dim=1)     # [B, num_classes]
#             fold_probs.append(probs.cpu().numpy())
#
#             # collect sample indices only once
#             if all_sample_indices is None:
#                 sample_indices_list.extend(sample_indices)
#
#     fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
#     all_fold_probs.append(fold_probs)
#
#     if all_sample_indices is None:
#         all_sample_indices = sample_indices_list
#
# # average probabilities across folds
# mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
# pred_indices = mean_probs.argmax(axis=1)
#
# pred_labels = [idx2label[int(i)] for i in pred_indices]
# sample_index_with_ext = [
#     f"{si}.png" if not si.endswith(".png") else si
#     for si in all_sample_indices
# ]
#
# submission_df = pd.DataFrame({
#     "sample_index": sample_index_with_ext,
#     "label": pred_labels
# })
#
# submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
# print("Saved submission_5fold_no_tta.csv")
# print(submission_df.head())


In [9]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # deterministic, returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=1,               # per-image TTA
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

val_f1_per_fold = np.array(
    [best_f1_per_fold[fold] for fold in range(N_FOLDS)],
    dtype=np.float32
)

# Normalize to get weights that sum to 1
fold_weights = val_f1_per_fold / val_f1_per_fold.sum()
print("Fold weights:", fold_weights)

# -----------------------------
# 2) Accumulate weighted probs
# -----------------------------
all_probs = None
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model (weight={fold_weights[fold]:.3f})")

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)

    state_dict = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            # img_tensor: [1, 4, H, W]  (RGB+mask)
            img_tensor = img_tensor.squeeze(0).to(device)  # [4, H, W]

            # -------- TTA: apply multiple augmented views [4xHxW] --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1, 4, H, W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1, N_CLASSES]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)  # [N_CLASSES]
            fold_probs.append(avg_probs)

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N_test, N_CLASSES]

    # initialize global probs
    if all_probs is None:
        all_probs = np.zeros_like(fold_probs, dtype=np.float32)

     # weighted accumulation
    all_probs += fold_weights[fold] * fold_probs

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# -----------------------------
# 3) Final predictions
# -----------------------------
pred_indices = all_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print(f"Saved submission_5fold_tta_{prefix_filename}.csv")

Fold weights: [0.16334502 0.16251166 0.19389029 0.2462267  0.23402636]
Inference with fold 0 model (weight=0.163)
Inference with fold 1 model (weight=0.163)
Inference with fold 2 model (weight=0.194)
Inference with fold 3 model (weight=0.246)
Inference with fold 4 model (weight=0.234)
Saved submission_5fold_tta_effb0.csv


In [10]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.23521387651874498
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.20647431764453042
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.32431322116243344
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.3172188967065326
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.3196428571428572
Mean OOF F1: 0.28057263383501974
