In [1]:
import enum
import json
import os
from copy import deepcopy

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from timm.data import Mixup
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.mixup_cutmix_wrapper import MixupCutmixWrapper
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B0

In [4]:
best_f1_per_fold: dict[int, int] = {}

In [5]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,          # Dropout
        drop_path_rate=0.1      # Stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    For EfficientNet from timm: unfreeze last 2 blocks + classifier head.
    """
    freeze_all(model)

    # Last 2 conv blocks
    if hasattr(model, "blocks"):
        for blk in model.blocks[-2:]:
            for p in blk.parameters():
                p.requires_grad = True

    # Classifier head
    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True


if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    GRAD_ACCUM_STEPS = 2
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 25
    LR = 3e-4
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b0_model(pretrained=True)
        unfreeze_last_two_blocks_and_head(model)

        # ---- loss, optimizer, scheduler ----
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.1
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None
        mixup_fn = MixupCutmixWrapper(
            alpha=0.4,       # mixup/cutmix Beta distribution
            mixup_prob=0.4,  # 40% of batches => mixup
            cutmix_prob=0.2  # 20% of batches => cutmix
        )

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device, grad_accum_steps=GRAD_ACCUM_STEPS, mixup_fn=mixup_fn
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(
                    best_state,
                    f"best_effb0_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best weights for this fold
        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1


========== Fold 0 ==========

Epoch 1/25


    t_loss=2.3012 | F1(macro)=0.2952 | Acc=0.3060


Confusion matrix:
 [[13  2  2 24]
 [13  3  6 10]
 [ 7  2  2 19]
 [ 1  2  1 10]]
Train  loss=2.3012 acc=0.3060 f1=0.2952 | Val loss=2.5048 acc=0.2393 f1=0.2126
  🔥 New best F1: 0.2126 – model saved.

Epoch 2/25


    t_loss=1.7499 | F1(macro)=0.3282 | Acc=0.3427


Confusion matrix:
 [[ 1 11  9 20]
 [ 5  5 12 10]
 [ 2  3  9 16]
 [ 0  3  1 10]]
Train  loss=1.7499 acc=0.3427 f1=0.3282 | Val loss=1.9825 acc=0.2137 f1=0.2017

Epoch 3/25


    t_loss=1.5782 | F1(macro)=0.3327 | Acc=0.3491


Confusion matrix:
 [[12 11  8 10]
 [16  3  6  7]
 [14  4  6  6]
 [ 2  1  3  8]]
Train  loss=1.5782 acc=0.3491 f1=0.3327 | Val loss=1.7496 acc=0.2479 f1=0.2455
  🔥 New best F1: 0.2455 – model saved.

Epoch 4/25


    t_loss=1.5407 | F1(macro)=0.3470 | Acc=0.3685


Confusion matrix:
 [[26  5  1  9]
 [18  5  2  7]
 [16  2  0 12]
 [ 3  2  1  8]]
Train  loss=1.5407 acc=0.3685 f1=0.3470 | Val loss=2.1121 acc=0.3333 f1=0.2593
  🔥 New best F1: 0.2593 – model saved.

Epoch 5/25


    t_loss=1.4060 | F1(macro)=0.3895 | Acc=0.3987


Confusion matrix:
 [[21  8  5  7]
 [18  8  3  3]
 [14  3  6  7]
 [ 6  2  1  5]]
Train  loss=1.4060 acc=0.3987 f1=0.3895 | Val loss=1.7820 acc=0.3419 f1=0.3166
  🔥 New best F1: 0.3166 – model saved.

Epoch 6/25


    t_loss=1.4003 | F1(macro)=0.4062 | Acc=0.4138


Confusion matrix:
 [[12  4 11 14]
 [ 8 10  7  7]
 [ 7  5  6 12]
 [ 1  2  1 10]]
Train  loss=1.4003 acc=0.4138 f1=0.4062 | Val loss=1.7559 acc=0.3248 f1=0.3236
  🔥 New best F1: 0.3236 – model saved.

Epoch 7/25


    t_loss=1.2884 | F1(macro)=0.4352 | Acc=0.4483


Confusion matrix:
 [[13  4 11 13]
 [10  5  9  8]
 [11  3  8  8]
 [ 1  2  3  8]]
Train  loss=1.2884 acc=0.4483 f1=0.4352 | Val loss=1.9774 acc=0.2906 f1=0.2839

Epoch 8/25


    t_loss=1.1980 | F1(macro)=0.4593 | Acc=0.4763


Confusion matrix:
 [[16  3  6 16]
 [16  1  6  9]
 [10  1  4 15]
 [ 2  0  3  9]]
Train  loss=1.1980 acc=0.4763 f1=0.4593 | Val loss=2.1033 acc=0.2564 f1=0.2199

Epoch 9/25


    t_loss=1.3206 | F1(macro)=0.4396 | Acc=0.4483


Confusion matrix:
 [[15  2  9 15]
 [11  5  5 11]
 [11  1  8 10]
 [ 1  2  2  9]]
Train  loss=1.3206 acc=0.4483 f1=0.4396 | Val loss=1.9069 acc=0.3162 f1=0.3048

Epoch 10/25


    t_loss=1.1650 | F1(macro)=0.4841 | Acc=0.5000


Confusion matrix:
 [[25  2  1 13]
 [21  3  1  7]
 [14  2  4 10]
 [ 5  1  1  7]]
Train  loss=1.1650 acc=0.5000 f1=0.4841 | Val loss=2.0339 acc=0.3333 f1=0.2781

Epoch 11/25


    t_loss=1.1420 | F1(macro)=0.4783 | Acc=0.4935


Confusion matrix:
 [[14  7  2 18]
 [ 8  6  4 14]
 [11  5  1 13]
 [ 2  2  1  9]]
Train  loss=1.1420 acc=0.4935 f1=0.4783 | Val loss=2.0126 acc=0.2564 f1=0.2291

Epoch 12/25


    t_loss=1.1892 | F1(macro)=0.5429 | Acc=0.5453


Confusion matrix:
 [[18 10  3 10]
 [11  9  3  9]
 [10  8  4  8]
 [ 2  3  1  8]]
Train  loss=1.1892 acc=0.5453 f1=0.5429 | Val loss=1.9944 acc=0.3333 f1=0.3127

Epoch 13/25


    t_loss=1.1163 | F1(macro)=0.5283 | Acc=0.5453


Confusion matrix:
 [[17 10  5  9]
 [17  8  1  6]
 [10  6  5  9]
 [ 1  4  0  9]]
Train  loss=1.1163 acc=0.5453 f1=0.5283 | Val loss=1.9295 acc=0.3333 f1=0.3222

Epoch 14/25


    t_loss=1.1066 | F1(macro)=0.5211 | Acc=0.5345


Confusion matrix:
 [[19 11  6  5]
 [13 13  2  4]
 [16  6  4  4]
 [ 5  5  1  3]]
Train  loss=1.1066 acc=0.5345 f1=0.5211 | Val loss=1.9397 acc=0.3333 f1=0.2946

Epoch 15/25


    t_loss=1.0810 | F1(macro)=0.5241 | Acc=0.5366


Confusion matrix:
 [[18  8  3 12]
 [15  9  2  6]
 [15  2  3 10]
 [ 4  2  2  6]]
Train  loss=1.0810 acc=0.5366 f1=0.5241 | Val loss=1.9838 acc=0.3077 f1=0.2817

Epoch 16/25


    t_loss=1.0331 | F1(macro)=0.5757 | Acc=0.5819


Confusion matrix:
 [[18  6  6 11]
 [15  6  3  8]
 [10  4  8  8]
 [ 4  1  2  7]]
Train  loss=1.0331 acc=0.5819 f1=0.5757 | Val loss=1.8959 acc=0.3333 f1=0.3180

Epoch 17/25


    t_loss=0.9885 | F1(macro)=0.5814 | Acc=0.5991


Confusion matrix:
 [[20  7  8  6]
 [16  6  5  5]
 [14  4  8  4]
 [ 4  1  3  6]]
Train  loss=0.9885 acc=0.5991 f1=0.5814 | Val loss=1.9358 acc=0.3419 f1=0.3251
  🔥 New best F1: 0.3251 – model saved.

Epoch 18/25


    t_loss=0.9934 | F1(macro)=0.5369 | Acc=0.5647


Confusion matrix:
 [[15 11 11  4]
 [13  7 10  2]
 [10  6 11  3]
 [ 2  3  5  4]]
Train  loss=0.9934 acc=0.5647 f1=0.5369 | Val loss=1.9528 acc=0.3162 f1=0.3081

Epoch 19/25


    t_loss=0.9915 | F1(macro)=0.5649 | Acc=0.5841


Confusion matrix:
 [[14 11 14  2]
 [12 10  3  7]
 [ 9  7  7  7]
 [ 2  4  4  4]]
Train  loss=0.9915 acc=0.5841 f1=0.5649 | Val loss=1.8622 acc=0.2991 f1=0.2870

Epoch 20/25


    t_loss=0.9686 | F1(macro)=0.6305 | Acc=0.6336


Confusion matrix:
 [[17  9 10  5]
 [15  9  2  6]
 [12  6  7  5]
 [ 5  1  2  6]]
Train  loss=0.9686 acc=0.6336 f1=0.6305 | Val loss=1.8836 acc=0.3333 f1=0.3254
  🔥 New best F1: 0.3254 – model saved.

Epoch 21/25


    t_loss=0.9838 | F1(macro)=0.5982 | Acc=0.6056


Confusion matrix:
 [[19  7  9  6]
 [14 10  3  5]
 [11  7  6  6]
 [ 4  3  2  5]]
Train  loss=0.9838 acc=0.6056 f1=0.5982 | Val loss=1.9462 acc=0.3419 f1=0.3209

Epoch 22/25


    t_loss=0.9393 | F1(macro)=0.6593 | Acc=0.6681


Confusion matrix:
 [[15  5 15  6]
 [12  9  5  6]
 [10  4 10  6]
 [ 3  3  2  6]]
Train  loss=0.9393 acc=0.6681 f1=0.6593 | Val loss=1.8429 acc=0.3419 f1=0.3371
  🔥 New best F1: 0.3371 – model saved.

Epoch 23/25


    t_loss=0.9286 | F1(macro)=0.6491 | Acc=0.6573


Confusion matrix:
 [[12  3 21  5]
 [13  4 10  5]
 [ 9  4 12  5]
 [ 3  2  4  5]]
Train  loss=0.9286 acc=0.6573 f1=0.6491 | Val loss=1.9526 acc=0.2821 f1=0.2728

Epoch 24/25


    t_loss=0.9587 | F1(macro)=0.6228 | Acc=0.6272


Confusion matrix:
 [[15  8 12  6]
 [13  9  7  3]
 [10  7  8  5]
 [ 4  3  2  5]]
Train  loss=0.9587 acc=0.6272 f1=0.6228 | Val loss=1.9742 acc=0.3162 f1=0.3102

Epoch 25/25


    t_loss=0.9845 | F1(macro)=0.6116 | Acc=0.6164


Confusion matrix:
 [[16  7 12  6]
 [11 11  4  6]
 [11  4 10  5]
 [ 5  3  2  4]]
Train  loss=0.9845 acc=0.6164 f1=0.6116 | Val loss=1.8611 acc=0.3504 f1=0.3351
Restored best weights for fold 0 (F1=0.3371)

========== Fold 1 ==========

Epoch 1/25


    t_loss=2.3004 | F1(macro)=0.2949 | Acc=0.3140


Confusion matrix:
 [[ 7  6 20  7]
 [ 6  5 15  6]
 [ 5  4 19  2]
 [ 1  2  9  2]]
Train  loss=2.3004 acc=0.3140 f1=0.2949 | Val loss=2.4810 acc=0.2845 f1=0.2448
  🔥 New best F1: 0.2448 – model saved.

Epoch 2/25


    t_loss=1.8225 | F1(macro)=0.3111 | Acc=0.3269


Confusion matrix:
 [[ 3  2 17 18]
 [ 1  4 11 16]
 [ 7  3 14  6]
 [ 0  1  7  6]]
Train  loss=1.8225 acc=0.3269 f1=0.3111 | Val loss=2.2109 acc=0.2328 f1=0.2156

Epoch 3/25


    t_loss=1.4694 | F1(macro)=0.3579 | Acc=0.3957


Confusion matrix:
 [[10  6 20  4]
 [11  6 11  4]
 [10  5 14  1]
 [ 1  3  4  6]]
Train  loss=1.4694 acc=0.3957 f1=0.3579 | Val loss=1.8433 acc=0.3103 f1=0.3192
  🔥 New best F1: 0.3192 – model saved.

Epoch 4/25


    t_loss=1.5183 | F1(macro)=0.3717 | Acc=0.3849


Confusion matrix:
 [[ 7 10 11 12]
 [ 5  9  6 12]
 [ 6 10  6  8]
 [ 3  5  2  4]]
Train  loss=1.5183 acc=0.3849 f1=0.3717 | Val loss=1.8966 acc=0.2241 f1=0.2201

Epoch 5/25


    t_loss=1.3549 | F1(macro)=0.4132 | Acc=0.4344


Confusion matrix:
 [[ 4  8 21  7]
 [ 3  6 17  6]
 [ 2 10 15  3]
 [ 1  0  8  5]]
Train  loss=1.3549 acc=0.4344 f1=0.4132 | Val loss=1.9257 acc=0.2586 f1=0.2474

Epoch 6/25


    t_loss=1.3383 | F1(macro)=0.4001 | Acc=0.4194


Confusion matrix:
 [[ 9 13  5 13]
 [ 9 10  2 11]
 [ 5 10  8  7]
 [ 4  2  2  6]]
Train  loss=1.3383 acc=0.4194 f1=0.4001 | Val loss=1.8665 acc=0.2845 f1=0.2857

Epoch 7/25


    t_loss=1.3986 | F1(macro)=0.3952 | Acc=0.4215


Confusion matrix:
 [[15  6 10  9]
 [ 9 12  6  5]
 [11  9  8  2]
 [ 6  2  3  3]]
Train  loss=1.3986 acc=0.4215 f1=0.3952 | Val loss=1.7754 acc=0.3276 f1=0.3066

Epoch 8/25


    t_loss=1.2755 | F1(macro)=0.4540 | Acc=0.4753


Confusion matrix:
 [[ 9  7  2 22]
 [ 5  5  1 21]
 [ 7  5  5 13]
 [ 3  0  0 11]]
Train  loss=1.2755 acc=0.4753 f1=0.4540 | Val loss=1.8503 acc=0.2586 f1=0.2550

Epoch 9/25


    t_loss=1.2414 | F1(macro)=0.4557 | Acc=0.4688


Confusion matrix:
 [[14 11  6  9]
 [13  6  4  9]
 [11  8  7  4]
 [ 6  2  1  5]]
Train  loss=1.2414 acc=0.4688 f1=0.4557 | Val loss=1.9633 acc=0.2759 f1=0.2681

Epoch 10/25


    t_loss=1.2017 | F1(macro)=0.4931 | Acc=0.5054


Confusion matrix:
 [[ 9 11 11  9]
 [ 7  8  8  9]
 [ 6 11  9  4]
 [ 3  0  7  4]]
Train  loss=1.2017 acc=0.5054 f1=0.4931 | Val loss=1.7966 acc=0.2586 f1=0.2530

Epoch 11/25


    t_loss=1.1458 | F1(macro)=0.4931 | Acc=0.5097


Confusion matrix:
 [[ 8  7  9 16]
 [ 5  5  9 13]
 [ 4  7 14  5]
 [ 1  1  3  9]]
Train  loss=1.1458 acc=0.5097 f1=0.4931 | Val loss=1.8257 acc=0.3103 f1=0.3037

Epoch 12/25


    t_loss=1.1176 | F1(macro)=0.5284 | Acc=0.5462


Confusion matrix:
 [[19  7  4 10]
 [15  7  7  3]
 [ 8 12  4  6]
 [ 5  2  2  5]]
Train  loss=1.1176 acc=0.5462 f1=0.5284 | Val loss=1.8726 acc=0.3017 f1=0.2759

Epoch 13/25


    t_loss=1.1491 | F1(macro)=0.5024 | Acc=0.5226


Confusion matrix:
 [[20  9  1 10]
 [19  4  2  7]
 [13  7  6  4]
 [ 4  1  3  6]]
Train  loss=1.1491 acc=0.5226 f1=0.5024 | Val loss=1.8093 acc=0.3103 f1=0.2865

Epoch 14/25


    t_loss=1.1173 | F1(macro)=0.5269 | Acc=0.5441


Confusion matrix:
 [[25  4  5  6]
 [16  6  3  7]
 [15  4  9  2]
 [ 5  1  3  5]]
Train  loss=1.1173 acc=0.5441 f1=0.5269 | Val loss=1.8164 acc=0.3879 f1=0.3511
  🔥 New best F1: 0.3511 – model saved.

Epoch 15/25


    t_loss=1.0503 | F1(macro)=0.5683 | Acc=0.5763


Confusion matrix:
 [[10 10  6 14]
 [ 5  5  8 14]
 [ 6  8  9  7]
 [ 1  1  3  9]]
Train  loss=1.0503 acc=0.5763 f1=0.5683 | Val loss=1.8683 acc=0.2845 f1=0.2832

Epoch 16/25


    t_loss=1.0579 | F1(macro)=0.5961 | Acc=0.6022


Confusion matrix:
 [[14 10  7  9]
 [ 9 10  4  9]
 [10  9  8  3]
 [ 3  2  5  4]]
Train  loss=1.0579 acc=0.6022 f1=0.5961 | Val loss=1.9064 acc=0.3103 f1=0.2968

Epoch 17/25


    t_loss=1.0388 | F1(macro)=0.5567 | Acc=0.5699


Confusion matrix:
 [[15  7  7 11]
 [11  6  3 12]
 [11  6  8  5]
 [ 4  1  2  7]]
Train  loss=1.0388 acc=0.5699 f1=0.5567 | Val loss=1.9812 acc=0.3103 f1=0.3017

Epoch 18/25


    t_loss=1.0369 | F1(macro)=0.5724 | Acc=0.5914


Confusion matrix:
 [[11  6 12 11]
 [ 7  6  7 12]
 [10  6 11  3]
 [ 1  4  4  5]]
Train  loss=1.0369 acc=0.5914 f1=0.5724 | Val loss=1.9185 acc=0.2845 f1=0.2768

Epoch 19/25


    t_loss=0.9408 | F1(macro)=0.6408 | Acc=0.6495


Confusion matrix:
 [[18  8  6  8]
 [14  8  4  6]
 [13  5 10  2]
 [ 5  2  4  3]]
Train  loss=0.9408 acc=0.6495 f1=0.6408 | Val loss=1.9768 acc=0.3362 f1=0.3108

Epoch 20/25


    t_loss=0.9810 | F1(macro)=0.5985 | Acc=0.6172


Confusion matrix:
 [[20  8  5  7]
 [14  7  4  7]
 [13  5  9  3]
 [ 3  4  3  4]]
Train  loss=0.9810 acc=0.6172 f1=0.5985 | Val loss=1.9178 acc=0.3448 f1=0.3190

Epoch 21/25


    t_loss=0.9994 | F1(macro)=0.5472 | Acc=0.5763


Confusion matrix:
 [[13 10  8  9]
 [11  7  6  8]
 [ 9  7 11  3]
 [ 2  3  6  3]]
Train  loss=0.9994 acc=0.5763 f1=0.5472 | Val loss=2.0307 acc=0.2931 f1=0.2767

Epoch 22/25


    t_loss=0.9174 | F1(macro)=0.6484 | Acc=0.6731


Confusion matrix:
 [[16  9  8  7]
 [13  6  6  7]
 [10  8  9  3]
 [ 3  3  4  4]]
Train  loss=0.9174 acc=0.6731 f1=0.6484 | Val loss=1.9666 acc=0.3017 f1=0.2854

Epoch 23/25


    t_loss=0.9796 | F1(macro)=0.6104 | Acc=0.6215


Confusion matrix:
 [[18  7  6  9]
 [16  5  1 10]
 [12  7  9  2]
 [ 2  4  4  4]]
Train  loss=0.9796 acc=0.6215 f1=0.6104 | Val loss=1.9303 acc=0.3103 f1=0.2890

Epoch 24/25


    t_loss=0.9996 | F1(macro)=0.6007 | Acc=0.6065


Confusion matrix:
 [[12 11  5 12]
 [12  8  3  9]
 [ 9  6  8  7]
 [ 3  3  3  5]]
Train  loss=0.9996 acc=0.6065 f1=0.6007 | Val loss=1.9932 acc=0.2845 f1=0.2804

Epoch 25/25


    t_loss=0.9615 | F1(macro)=0.6018 | Acc=0.6129


Confusion matrix:
 [[18  8  8  6]
 [12  6  8  6]
 [ 7  6 12  5]
 [ 2  3  3  6]]
Train  loss=0.9615 acc=0.6129 f1=0.6018 | Val loss=1.9476 acc=0.3621 f1=0.3479
Restored best weights for fold 1 (F1=0.3511)

========== Fold 2 ==========

Epoch 1/25


    t_loss=2.4757 | F1(macro)=0.3163 | Acc=0.3247


Confusion matrix:
 [[12  2 12 15]
 [ 7  2 14  8]
 [ 3  3 16  8]
 [ 4  0  4  6]]
Train  loss=2.4757 acc=0.3247 f1=0.3163 | Val loss=2.4156 acc=0.3103 f1=0.2800
  🔥 New best F1: 0.2800 – model saved.

Epoch 2/25


    t_loss=1.7493 | F1(macro)=0.3426 | Acc=0.3527


Confusion matrix:
 [[ 4  5 25  7]
 [ 1  4 17  9]
 [ 2  1 21  6]
 [ 0  0 12  2]]
Train  loss=1.7493 acc=0.3527 f1=0.3426 | Val loss=2.3916 acc=0.2672 f1=0.2168

Epoch 3/25


    t_loss=1.6552 | F1(macro)=0.3315 | Acc=0.3398


Confusion matrix:
 [[ 4  5 16 16]
 [ 4 12  6  9]
 [ 3  9 12  6]
 [ 1  2  7  4]]
Train  loss=1.6552 acc=0.3398 f1=0.3315 | Val loss=2.4483 acc=0.2759 f1=0.2648

Epoch 4/25


    t_loss=1.5274 | F1(macro)=0.3604 | Acc=0.3742


Confusion matrix:
 [[13  6 20  2]
 [ 8  9  7  7]
 [11  5 12  2]
 [ 5  1  7  1]]
Train  loss=1.5274 acc=0.3742 f1=0.3604 | Val loss=2.5406 acc=0.3017 f1=0.2680

Epoch 5/25


    t_loss=1.4374 | F1(macro)=0.3983 | Acc=0.4151


Confusion matrix:
 [[ 4  2 22 13]
 [ 2  6 13 10]
 [ 4  1 15 10]
 [ 1  1  9  3]]
Train  loss=1.4374 acc=0.4151 f1=0.3983 | Val loss=2.1676 acc=0.2414 f1=0.2259

Epoch 6/25


    t_loss=1.3847 | F1(macro)=0.3951 | Acc=0.4172


Confusion matrix:
 [[ 2 16 16  7]
 [ 2  6 13 10]
 [ 4  7 13  6]
 [ 2  1  9  2]]
Train  loss=1.3847 acc=0.4172 f1=0.3951 | Val loss=2.1958 acc=0.1983 f1=0.1747

Epoch 7/25


    t_loss=1.3068 | F1(macro)=0.3987 | Acc=0.4172


Confusion matrix:
 [[10 15  9  7]
 [ 7 12  2 10]
 [ 7 11  6  6]
 [ 2  3  4  5]]
Train  loss=1.3068 acc=0.4172 f1=0.3987 | Val loss=1.9419 acc=0.2845 f1=0.2763

Epoch 8/25


    t_loss=1.2727 | F1(macro)=0.4236 | Acc=0.4495


Confusion matrix:
 [[ 9 14  3 15]
 [ 2 13  2 14]
 [ 8  5  6 11]
 [ 3  1  4  6]]
Train  loss=1.2727 acc=0.4495 f1=0.4236 | Val loss=2.0152 acc=0.2931 f1=0.2897
  🔥 New best F1: 0.2897 – model saved.

Epoch 9/25


    t_loss=1.3053 | F1(macro)=0.4689 | Acc=0.4731


Confusion matrix:
 [[ 9 15 11  6]
 [ 5 12  7  7]
 [ 3 11  9  7]
 [ 3  4  2  5]]
Train  loss=1.3053 acc=0.4731 f1=0.4689 | Val loss=2.0308 acc=0.3017 f1=0.2963
  🔥 New best F1: 0.2963 – model saved.

Epoch 10/25


    t_loss=1.2393 | F1(macro)=0.5089 | Acc=0.5161


Confusion matrix:
 [[21  6  8  6]
 [14  7  4  6]
 [12  3  9  6]
 [ 5  3  3  3]]
Train  loss=1.2393 acc=0.5161 f1=0.5089 | Val loss=2.1623 acc=0.3448 f1=0.3091
  🔥 New best F1: 0.3091 – model saved.

Epoch 11/25


    t_loss=1.1718 | F1(macro)=0.4976 | Acc=0.5140


Confusion matrix:
 [[11 14 11  5]
 [10 12  6  3]
 [ 9 10  7  4]
 [ 3  3  4  4]]
Train  loss=1.1718 acc=0.5140 f1=0.4976 | Val loss=2.1974 acc=0.2931 f1=0.2871

Epoch 12/25


    t_loss=1.0773 | F1(macro)=0.5094 | Acc=0.5269


Confusion matrix:
 [[13 14  6  8]
 [11 12  2  6]
 [12 11  2  5]
 [ 4  2  1  7]]
Train  loss=1.0773 acc=0.5269 f1=0.5094 | Val loss=2.1074 acc=0.2931 f1=0.2779

Epoch 13/25


    t_loss=1.0698 | F1(macro)=0.5555 | Acc=0.5699


Confusion matrix:
 [[16 12 10  3]
 [13 12  4  2]
 [10 10  7  3]
 [ 7  2  2  3]]
Train  loss=1.0698 acc=0.5699 f1=0.5555 | Val loss=2.1334 acc=0.3276 f1=0.3075

Epoch 14/25


    t_loss=1.1114 | F1(macro)=0.5243 | Acc=0.5505


Confusion matrix:
 [[18  8  9  6]
 [13 11  3  4]
 [13 10  6  1]
 [ 4  2  3  5]]
Train  loss=1.1114 acc=0.5505 f1=0.5243 | Val loss=1.9513 acc=0.3448 f1=0.3320
  🔥 New best F1: 0.3320 – model saved.

Epoch 15/25


    t_loss=1.0753 | F1(macro)=0.5460 | Acc=0.5591


Confusion matrix:
 [[14 16  8  3]
 [ 8 16  6  1]
 [10 11  8  1]
 [ 5  2  4  3]]
Train  loss=1.0753 acc=0.5591 f1=0.5460 | Val loss=2.0894 acc=0.3534 f1=0.3346
  🔥 New best F1: 0.3346 – model saved.

Epoch 16/25


    t_loss=1.0780 | F1(macro)=0.5415 | Acc=0.5548


Confusion matrix:
 [[16 16  6  3]
 [10 18  2  1]
 [10 12  6  2]
 [ 5  2  4  3]]
Train  loss=1.0780 acc=0.5548 f1=0.5415 | Val loss=1.9600 acc=0.3707 f1=0.3392
  🔥 New best F1: 0.3392 – model saved.

Epoch 17/25


    t_loss=1.0059 | F1(macro)=0.5759 | Acc=0.5871


Confusion matrix:
 [[17 13  6  5]
 [ 8 18  1  4]
 [15  8  5  2]
 [ 5  3  4  2]]
Train  loss=1.0059 acc=0.5871 f1=0.5759 | Val loss=2.1265 acc=0.3621 f1=0.3135

Epoch 18/25


    t_loss=0.9695 | F1(macro)=0.6150 | Acc=0.6323


Confusion matrix:
 [[14  8 15  4]
 [ 7 12 11  1]
 [ 9  5 13  3]
 [ 4  1  7  2]]
Train  loss=0.9695 acc=0.6323 f1=0.6150 | Val loss=2.0788 acc=0.3534 f1=0.3258

Epoch 19/25


    t_loss=0.9763 | F1(macro)=0.6125 | Acc=0.6194


Confusion matrix:
 [[17 11  6  7]
 [10 16  4  1]
 [12  8  6  4]
 [ 5  2  3  4]]
Train  loss=0.9763 acc=0.6194 f1=0.6125 | Val loss=2.2010 acc=0.3707 f1=0.3455
  🔥 New best F1: 0.3455 – model saved.

Epoch 20/25


    t_loss=1.0174 | F1(macro)=0.6057 | Acc=0.6172


Confusion matrix:
 [[17 13  7  4]
 [11 14  5  1]
 [ 9  9  9  3]
 [ 7  0  4  3]]
Train  loss=1.0174 acc=0.6172 f1=0.6057 | Val loss=2.2185 acc=0.3707 f1=0.3463
  🔥 New best F1: 0.3463 – model saved.

Epoch 21/25


    t_loss=1.0519 | F1(macro)=0.5785 | Acc=0.5806


Confusion matrix:
 [[21  8  9  3]
 [13 12  5  1]
 [13  5 10  2]
 [ 8  0  4  2]]
Train  loss=1.0519 acc=0.5806 f1=0.5785 | Val loss=2.2225 acc=0.3879 f1=0.3482
  🔥 New best F1: 0.3482 – model saved.

Epoch 22/25


    t_loss=1.0193 | F1(macro)=0.6172 | Acc=0.6172


Confusion matrix:
 [[13 15  9  4]
 [14 13  2  2]
 [ 9 10  8  3]
 [ 3  2  6  3]]
Train  loss=1.0193 acc=0.6172 f1=0.6172 | Val loss=2.2365 acc=0.3190 f1=0.3032

Epoch 23/25


    t_loss=0.9619 | F1(macro)=0.6560 | Acc=0.6602


Confusion matrix:
 [[15 11 13  2]
 [ 9 14  7  1]
 [12  9  8  1]
 [ 5  2  6  1]]
Train  loss=0.9619 acc=0.6602 f1=0.6560 | Val loss=2.2623 acc=0.3276 f1=0.2848

Epoch 24/25


    t_loss=0.9987 | F1(macro)=0.6136 | Acc=0.6280


Confusion matrix:
 [[15 10 13  3]
 [10 12  8  1]
 [11  6 13  0]
 [ 8  0  5  1]]
Train  loss=0.9987 acc=0.6280 f1=0.6136 | Val loss=2.5194 acc=0.3534 f1=0.3104

Epoch 25/25


    t_loss=1.0016 | F1(macro)=0.6092 | Acc=0.6129


Confusion matrix:
 [[16 12 12  1]
 [10 14  5  2]
 [10  9  9  2]
 [ 4  3  7  0]]
Train  loss=1.0016 acc=0.6129 f1=0.6092 | Val loss=2.4621 acc=0.3362 f1=0.2716
Restored best weights for fold 2 (F1=0.3482)

========== Fold 3 ==========

Epoch 1/25


    t_loss=2.3046 | F1(macro)=0.2812 | Acc=0.2968


Confusion matrix:
 [[ 6  9  8 18]
 [ 9  6  9  7]
 [ 7  8  7  8]
 [ 5  2  2  5]]
Train  loss=2.3046 acc=0.2968 f1=0.2812 | Val loss=2.8888 acc=0.2069 f1=0.2083
  🔥 New best F1: 0.2083 – model saved.

Epoch 2/25


    t_loss=1.8363 | F1(macro)=0.3219 | Acc=0.3355


Confusion matrix:
 [[ 8 10  2 21]
 [ 6  7  3 15]
 [ 6  3  3 18]
 [ 4  5  2  3]]
Train  loss=1.8363 acc=0.3355 f1=0.3219 | Val loss=2.1545 acc=0.1810 f1=0.1827

Epoch 3/25


    t_loss=1.4742 | F1(macro)=0.3821 | Acc=0.4043


Confusion matrix:
 [[10  8 12 11]
 [ 8 11  8  4]
 [ 6  3  9 12]
 [ 3  4  5  2]]
Train  loss=1.4742 acc=0.4043 f1=0.3821 | Val loss=1.8392 acc=0.2759 f1=0.2636
  🔥 New best F1: 0.2636 – model saved.

Epoch 4/25


    t_loss=1.5341 | F1(macro)=0.3696 | Acc=0.3957


Confusion matrix:
 [[12 10  5 14]
 [ 6  6  7 12]
 [ 6  5  7 12]
 [ 2  4  3  5]]
Train  loss=1.5341 acc=0.3957 f1=0.3696 | Val loss=2.0668 acc=0.2586 f1=0.2543

Epoch 5/25


    t_loss=1.4349 | F1(macro)=0.3845 | Acc=0.4194


Confusion matrix:
 [[ 7  0 10 24]
 [ 9  2  7 13]
 [ 4  0  8 18]
 [ 3  0  2  9]]
Train  loss=1.4349 acc=0.4194 f1=0.3845 | Val loss=2.0944 acc=0.2241 f1=0.2129

Epoch 6/25


    t_loss=1.3992 | F1(macro)=0.3578 | Acc=0.3849


Confusion matrix:
 [[14  5 10 12]
 [ 9  4  7 11]
 [ 9  0  9 12]
 [ 4  0  4  6]]
Train  loss=1.3992 acc=0.3849 f1=0.3578 | Val loss=1.9502 acc=0.2845 f1=0.2705
  🔥 New best F1: 0.2705 – model saved.

Epoch 7/25


    t_loss=1.3359 | F1(macro)=0.3959 | Acc=0.4258


Confusion matrix:
 [[25  4  3  9]
 [18  8  2  3]
 [19  1  7  3]
 [ 6  1  1  6]]
Train  loss=1.3359 acc=0.4258 f1=0.3959 | Val loss=1.8878 acc=0.3966 f1=0.3707
  🔥 New best F1: 0.3707 – model saved.

Epoch 8/25


    t_loss=1.3752 | F1(macro)=0.4265 | Acc=0.4366


Confusion matrix:
 [[13  5 18  5]
 [10  6  9  6]
 [ 8  1 17  4]
 [ 3  2  5  4]]
Train  loss=1.3752 acc=0.4366 f1=0.4265 | Val loss=1.8613 acc=0.3448 f1=0.3215

Epoch 9/25


    t_loss=1.3111 | F1(macro)=0.4637 | Acc=0.4774


Confusion matrix:
 [[19  5 15  2]
 [14  5  9  3]
 [15  0 11  4]
 [ 4  1  5  4]]
Train  loss=1.3111 acc=0.4774 f1=0.4637 | Val loss=2.0268 acc=0.3362 f1=0.3143

Epoch 10/25


    t_loss=1.2078 | F1(macro)=0.4770 | Acc=0.4925


Confusion matrix:
 [[13  2 13 13]
 [10  2  7 12]
 [10  0  9 11]
 [ 8  0  2  4]]
Train  loss=1.2078 acc=0.4925 f1=0.4770 | Val loss=2.0360 acc=0.2414 f1=0.2186

Epoch 11/25


    t_loss=1.1890 | F1(macro)=0.4645 | Acc=0.4860


Confusion matrix:
 [[22  8  4  7]
 [12 13  3  3]
 [17  3  4  6]
 [ 8  2  1  3]]
Train  loss=1.1890 acc=0.4860 f1=0.4645 | Val loss=1.8946 acc=0.3621 f1=0.3171

Epoch 12/25


    t_loss=1.2087 | F1(macro)=0.4974 | Acc=0.5097


Confusion matrix:
 [[21  9  6  5]
 [11 12  5  3]
 [16  5  6  3]
 [ 8  4  1  1]]
Train  loss=1.2087 acc=0.5097 f1=0.4974 | Val loss=2.0881 acc=0.3448 f1=0.2883

Epoch 13/25


    t_loss=1.1791 | F1(macro)=0.4828 | Acc=0.4925


Confusion matrix:
 [[27  5  2  7]
 [16  7  3  5]
 [22  0  3  5]
 [11  2  0  1]]
Train  loss=1.1791 acc=0.4925 f1=0.4828 | Val loss=1.9990 acc=0.3276 f1=0.2483

Epoch 14/25


    t_loss=1.1017 | F1(macro)=0.5173 | Acc=0.5312


Confusion matrix:
 [[21 10  3  7]
 [15 11  2  3]
 [14  4  7  5]
 [ 4  8  1  1]]
Train  loss=1.1017 acc=0.5312 f1=0.5173 | Val loss=1.8251 acc=0.3448 f1=0.2945

Epoch 15/25


    t_loss=1.0688 | F1(macro)=0.5078 | Acc=0.5398


Confusion matrix:
 [[17 13  8  3]
 [ 9 12  7  3]
 [16  2  6  6]
 [ 5  6  2  1]]
Train  loss=1.0688 acc=0.5398 f1=0.5078 | Val loss=1.8353 acc=0.3103 f1=0.2655

Epoch 16/25


    t_loss=1.0538 | F1(macro)=0.5492 | Acc=0.5677


Confusion matrix:
 [[12 10 16  3]
 [10 10  8  3]
 [14  2 13  1]
 [ 3  6  4  1]]
Train  loss=1.0538 acc=0.5677 f1=0.5492 | Val loss=2.0309 acc=0.3103 f1=0.2740

Epoch 17/25


    t_loss=1.0471 | F1(macro)=0.5642 | Acc=0.5742


Confusion matrix:
 [[16  7 10  8]
 [11  9  8  3]
 [13  0 13  4]
 [ 5  6  3  0]]
Train  loss=1.0471 acc=0.5742 f1=0.5642 | Val loss=1.8055 acc=0.3276 f1=0.2795

Epoch 18/25


    t_loss=1.0301 | F1(macro)=0.5386 | Acc=0.5613


Confusion matrix:
 [[17  5  8 11]
 [13  6  7  5]
 [ 9  0 17  4]
 [ 7  2  3  2]]
Train  loss=1.0301 acc=0.5613 f1=0.5386 | Val loss=1.8780 acc=0.3621 f1=0.3244

Epoch 19/25


    t_loss=0.9942 | F1(macro)=0.5828 | Acc=0.6000


Confusion matrix:
 [[12  5  9 15]
 [ 8 11  6  6]
 [ 7  1 16  6]
 [ 5  4  3  2]]
Train  loss=0.9942 acc=0.6000 f1=0.5828 | Val loss=1.8480 acc=0.3534 f1=0.3362

Epoch 20/25


    t_loss=1.0151 | F1(macro)=0.5780 | Acc=0.6022


Confusion matrix:
 [[16  7  6 12]
 [ 9  9  5  8]
 [12  2 10  6]
 [ 4  7  0  3]]
Train  loss=1.0151 acc=0.6022 f1=0.5780 | Val loss=1.8994 acc=0.3276 f1=0.3108

Epoch 21/25


    t_loss=0.9972 | F1(macro)=0.6006 | Acc=0.6108


Confusion matrix:
 [[13  8 11  9]
 [ 8 10  8  5]
 [11  0 12  7]
 [ 4  5  2  3]]
Train  loss=0.9972 acc=0.6108 f1=0.6006 | Val loss=1.8414 acc=0.3276 f1=0.3117

Epoch 22/25


    t_loss=1.0065 | F1(macro)=0.5981 | Acc=0.6129


Confusion matrix:
 [[ 7  6 17 11]
 [ 8 10  8  5]
 [ 9  0 16  5]
 [ 4  6  3  1]]
Train  loss=1.0065 acc=0.6129 f1=0.5981 | Val loss=1.9750 acc=0.2931 f1=0.2671

Epoch 23/25


    t_loss=1.0124 | F1(macro)=0.5806 | Acc=0.5892


Confusion matrix:
 [[11  6 14 10]
 [ 9  8  9  5]
 [11  2 12  5]
 [ 5  3  2  4]]
Train  loss=1.0124 acc=0.5892 f1=0.5806 | Val loss=1.8584 acc=0.3017 f1=0.2936

Epoch 24/25


    t_loss=1.0010 | F1(macro)=0.5919 | Acc=0.5978


Confusion matrix:
 [[16  5  7 13]
 [ 6  6  6 13]
 [12  0 11  7]
 [ 6  2  0  6]]
Train  loss=1.0010 acc=0.5978 f1=0.5919 | Val loss=1.8801 acc=0.3362 f1=0.3254

Epoch 25/25


    t_loss=1.0133 | F1(macro)=0.6039 | Acc=0.6108


Confusion matrix:
 [[18  5  8 10]
 [ 9  9  9  4]
 [13  1 11  5]
 [ 8  2  1  3]]
Train  loss=1.0133 acc=0.6108 f1=0.6039 | Val loss=1.8060 acc=0.3534 f1=0.3298
Restored best weights for fold 3 (F1=0.3707)

========== Fold 4 ==========

Epoch 1/25


    t_loss=2.2511 | F1(macro)=0.3061 | Acc=0.3140


Confusion matrix:
 [[12  4  5 20]
 [10  5  5 12]
 [ 6  5  8 11]
 [ 4  1  3  5]]
Train  loss=2.2511 acc=0.3140 f1=0.3061 | Val loss=2.3805 acc=0.2586 f1=0.2548
  🔥 New best F1: 0.2548 – model saved.

Epoch 2/25


    t_loss=1.6168 | F1(macro)=0.3430 | Acc=0.3656


Confusion matrix:
 [[ 5  7 12 17]
 [10  6  6 10]
 [ 8  5  9  8]
 [ 1  3  2  7]]
Train  loss=1.6168 acc=0.3656 f1=0.3430 | Val loss=2.3117 acc=0.2328 f1=0.2350

Epoch 3/25


    t_loss=1.6259 | F1(macro)=0.3144 | Acc=0.3333


Confusion matrix:
 [[10  7  0 24]
 [11  4  1 16]
 [ 6  5  1 18]
 [ 2  3  0  8]]
Train  loss=1.6259 acc=0.3333 f1=0.3144 | Val loss=2.2887 acc=0.1983 f1=0.1769

Epoch 4/25


    t_loss=1.4995 | F1(macro)=0.4046 | Acc=0.4172


Confusion matrix:
 [[ 3  9  2 27]
 [ 7  9  2 14]
 [ 4  3  1 22]
 [ 1  3  0  9]]
Train  loss=1.4995 acc=0.4172 f1=0.4046 | Val loss=2.2863 acc=0.1897 f1=0.1744

Epoch 5/25


    t_loss=1.3385 | F1(macro)=0.4273 | Acc=0.4473


Confusion matrix:
 [[12  9 12  8]
 [ 5 13  9  5]
 [ 8  2  9 11]
 [ 1  2  6  4]]
Train  loss=1.3385 acc=0.4473 f1=0.4273 | Val loss=1.9476 acc=0.3276 f1=0.3186
  🔥 New best F1: 0.3186 – model saved.

Epoch 6/25


    t_loss=1.3482 | F1(macro)=0.4121 | Acc=0.4323


Confusion matrix:
 [[ 3 11  8 19]
 [ 5  8  7 12]
 [ 5  4 10 11]
 [ 2  2  1  8]]
Train  loss=1.3482 acc=0.4323 f1=0.4121 | Val loss=1.8512 acc=0.2500 f1=0.2497

Epoch 7/25


    t_loss=1.3272 | F1(macro)=0.3668 | Acc=0.3914


Confusion matrix:
 [[ 6  2  4 29]
 [ 8  5  3 16]
 [ 4  1  2 23]
 [ 0  1  3  9]]
Train  loss=1.3272 acc=0.3914 f1=0.3668 | Val loss=2.2392 acc=0.1897 f1=0.1856

Epoch 8/25


    t_loss=1.2446 | F1(macro)=0.4720 | Acc=0.4817


Confusion matrix:
 [[12 12  7 10]
 [ 9 15  6  2]
 [ 8  9  6  7]
 [ 0  3  4  6]]
Train  loss=1.2446 acc=0.4817 f1=0.4720 | Val loss=1.8171 acc=0.3362 f1=0.3269
  🔥 New best F1: 0.3269 – model saved.

Epoch 9/25


    t_loss=1.2888 | F1(macro)=0.4874 | Acc=0.4968


Confusion matrix:
 [[ 3  7 16 15]
 [ 4 14  7  7]
 [ 5  4  8 13]
 [ 1  3  6  3]]
Train  loss=1.2888 acc=0.4968 f1=0.4874 | Val loss=1.9011 acc=0.2414 f1=0.2336

Epoch 10/25


    t_loss=1.2107 | F1(macro)=0.4838 | Acc=0.4946


Confusion matrix:
 [[ 3 11  5 22]
 [ 4 14  3 11]
 [ 6  7  4 13]
 [ 1  2  4  6]]
Train  loss=1.2107 acc=0.4946 f1=0.4838 | Val loss=2.0240 acc=0.2328 f1=0.2230

Epoch 11/25


    t_loss=1.1264 | F1(macro)=0.4925 | Acc=0.5140


Confusion matrix:
 [[12 17  3  9]
 [ 7 17  3  5]
 [10  9  4  7]
 [ 4  2  5  2]]
Train  loss=1.1264 acc=0.5140 f1=0.4925 | Val loss=1.9575 acc=0.3017 f1=0.2637

Epoch 12/25


    t_loss=1.1985 | F1(macro)=0.5060 | Acc=0.5226


Confusion matrix:
 [[ 6  7 19  9]
 [ 7 14  3  8]
 [ 6  3 10 11]
 [ 1  3  6  3]]
Train  loss=1.1985 acc=0.5226 f1=0.5060 | Val loss=1.8428 acc=0.2845 f1=0.2754

Epoch 13/25


    t_loss=1.0987 | F1(macro)=0.5328 | Acc=0.5570


Confusion matrix:
 [[ 6 16 12  7]
 [ 6 19  6  1]
 [12  5  8  5]
 [ 0  5  5  3]]
Train  loss=1.0987 acc=0.5570 f1=0.5328 | Val loss=1.8462 acc=0.3103 f1=0.2868

Epoch 14/25


    t_loss=1.1494 | F1(macro)=0.5381 | Acc=0.5441


Confusion matrix:
 [[ 5 11 19  6]
 [ 3 13 14  2]
 [ 6  7 12  5]
 [ 0  4  8  1]]
Train  loss=1.1494 acc=0.5441 f1=0.5381 | Val loss=1.9738 acc=0.2672 f1=0.2333

Epoch 15/25


    t_loss=1.0298 | F1(macro)=0.5585 | Acc=0.5742


Confusion matrix:
 [[ 4 19  9  9]
 [ 3 23  4  2]
 [10  8  7  5]
 [ 0  6  3  4]]
Train  loss=1.0298 acc=0.5742 f1=0.5585 | Val loss=1.9379 acc=0.3276 f1=0.2918

Epoch 16/25


    t_loss=1.0529 | F1(macro)=0.5777 | Acc=0.5914


Confusion matrix:
 [[16 10 10  5]
 [13 12  6  1]
 [12  5  8  5]
 [ 3  4  3  3]]
Train  loss=1.0529 acc=0.5914 f1=0.5777 | Val loss=1.8076 acc=0.3362 f1=0.3151

Epoch 17/25


    t_loss=1.0135 | F1(macro)=0.5750 | Acc=0.5935


Confusion matrix:
 [[ 7 11  9 14]
 [ 5 16  6  5]
 [ 8  5  9  8]
 [ 2  3  4  4]]
Train  loss=1.0135 acc=0.5935 f1=0.5750 | Val loss=1.8515 acc=0.3103 f1=0.2980

Epoch 18/25


    t_loss=1.0208 | F1(macro)=0.5638 | Acc=0.5720


Confusion matrix:
 [[ 8 15 12  6]
 [ 6 17  6  3]
 [14  6  6  4]
 [ 2  5  5  1]]
Train  loss=1.0208 acc=0.5720 f1=0.5638 | Val loss=1.8901 acc=0.2759 f1=0.2390

Epoch 19/25


    t_loss=1.0024 | F1(macro)=0.5799 | Acc=0.5871


Confusion matrix:
 [[13 17  7  4]
 [10 20  1  1]
 [14  9  5  2]
 [ 3  5  3  2]]
Train  loss=1.0024 acc=0.5871 f1=0.5799 | Val loss=1.9544 acc=0.3448 f1=0.3005

Epoch 20/25


    t_loss=1.0324 | F1(macro)=0.6016 | Acc=0.6129


Confusion matrix:
 [[10 15  9  7]
 [ 5 19  4  4]
 [13  7  8  2]
 [ 1  4  5  3]]
Train  loss=1.0324 acc=0.6129 f1=0.6016 | Val loss=1.8569 acc=0.3448 f1=0.3180

Epoch 21/25


    t_loss=0.9781 | F1(macro)=0.6114 | Acc=0.6215


Confusion matrix:
 [[12 17  7  5]
 [ 6 20  3  3]
 [14  7  5  4]
 [ 3  5  3  2]]
Train  loss=0.9781 acc=0.6215 f1=0.6114 | Val loss=1.8703 acc=0.3362 f1=0.2915

Epoch 22/25


    t_loss=0.9485 | F1(macro)=0.6263 | Acc=0.6323


Confusion matrix:
 [[11 12 11  7]
 [ 5 20  4  3]
 [14  5  7  4]
 [ 0  5  5  3]]
Train  loss=0.9485 acc=0.6323 f1=0.6263 | Val loss=1.8920 acc=0.3534 f1=0.3240

Epoch 23/25


    t_loss=0.9741 | F1(macro)=0.6011 | Acc=0.6194


Confusion matrix:
 [[14  9 12  6]
 [ 9 16  5  2]
 [11  6  9  4]
 [ 2  3  5  3]]
Train  loss=0.9741 acc=0.6194 f1=0.6011 | Val loss=1.7763 acc=0.3621 f1=0.3395
  🔥 New best F1: 0.3395 – model saved.

Epoch 24/25


    t_loss=0.9881 | F1(macro)=0.6339 | Acc=0.6409


Confusion matrix:
 [[ 8 12 13  8]
 [ 6 19  5  2]
 [ 9  6 11  4]
 [ 1  5  4  3]]
Train  loss=0.9881 acc=0.6409 f1=0.6339 | Val loss=1.8842 acc=0.3534 f1=0.3272

Epoch 25/25


    t_loss=0.9493 | F1(macro)=0.6325 | Acc=0.6473


Confusion matrix:
 [[10 12  8 11]
 [ 3 21  2  6]
 [12  7  6  5]
 [ 1  5  2  5]]
Train  loss=0.9493 acc=0.6473 f1=0.6325 | Val loss=1.8566 acc=0.3621 f1=0.3360
Restored best weights for fold 4 (F1=0.3395)


# tf_efficientnetv2_s.in21k

In [6]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [7]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [8]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

FOLD_VAL_F1 = f"fold_val_f1_{prefix_filename}.json"

# Save best F1 per fold to JSON
with open(FOLD_VAL_F1, "w") as f:
    json.dump(best_f1_per_fold, f, indent=2)

In [9]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # deterministic, returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=1,               # per-image TTA
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

if os.path.exists(FOLD_VAL_F1):
    with open(FOLD_VAL_F1, "r") as f:
        best_f1_per_fold = json.load(f)
    val_f1_per_fold = np.array([best_f1_per_fold[str(k)] for k in range(N_FOLDS)])
    # Normalize to get weights that sum to 1
    fold_weights = val_f1_per_fold / val_f1_per_fold.sum()
else:
    # fallback: uniform weights if metrics are missing
    print('Warning: fold validation F1 scores not found, using uniform weights.')
    fold_weights = np.ones(N_FOLDS, dtype=np.float32) / N_FOLDS

print("Fold weights:", fold_weights)

# -----------------------------
# 2) Accumulate weighted probs
# -----------------------------
all_probs = None
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model (weight={fold_weights[fold]:.3f})")

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)

    state_dict = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            # img_tensor: [1, 4, H, W]  (RGB+mask)
            img_tensor = img_tensor.squeeze(0).to(device)  # [4, H, W]

            # -------- TTA: apply multiple augmented views [4xHxW] --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1, 4, H, W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1, N_CLASSES]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)  # [N_CLASSES]
            fold_probs.append(avg_probs)

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N_test, N_CLASSES]

    # initialize global probs
    if all_probs is None:
        all_probs = np.zeros_like(fold_probs, dtype=np.float32)

     # weighted accumulation
    all_probs += fold_weights[fold] * fold_probs

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# -----------------------------
# 3) Final predictions
# -----------------------------
pred_indices = all_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print(f"Saved submission_5fold_tta_{prefix_filename}.csv")

Fold weights: [0.19300576 0.20103928 0.19935464 0.21223624 0.19436408]
Inference with fold 0 model (weight=0.193)
Inference with fold 1 model (weight=0.201)
Inference with fold 2 model (weight=0.199)
Inference with fold 3 model (weight=0.212)
Inference with fold 4 model (weight=0.194)
Saved submission_5fold_tta_effb0.csv


In [10]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.35968295541523154
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.2967418817137918
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.35972906403940885
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.32127829244290607
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.33138513004851405
Mean OOF F1: 0.33376346473197044
