In [1]:
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.persistence_manager import PersistenceManager
from notebooks.internal.nn.test_time_augmentation import apply_tta
from notebooks.internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
N_FOLDS = data.num_K_folds
BATCH_SIZE = 4
PRETRAINED_MODEL = "tf_efficientnetv2_s.in21k"
N_CLASSES = 4 # number of classes in the dataset (labels)
N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4

for fold in range(N_FOLDS):
    print(f"\n========== Fold {fold} ==========")

    train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
    val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

    train_dataset = HistologyDataset(train_df_split, transforms=train_transforms, is_train=True)
    val_dataset   = HistologyDataset(val_df_split,   transforms=val_test_transforms, is_train=True)

    sampler = make_weighted_sampler(train_df_split)
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        sampler=sampler,
        num_workers=N_WORKERS,
        pin_memory=cuda_is_available
    )
    val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE,
                              shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

    # --- create fresh model for this fold ---
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=True,
        num_classes=N_CLASSES
    ).to(device)

    # --- Stage 1: freeze backbone, train classifier head ---
    print("\n--- Stage 1: Training classifier head ---")

    # --- 1.1. freeze feature extractor layers ---
    for param in model.parameters():
        param.requires_grad = False

    # 2) unfreeze classifier head (EffNetV2 uses .classifier)
    for param in model.classifier.parameters():
        param.requires_grad = True

    # --- 1.2. define loss, optimizer, scheduler ---
    criterion = nn.CrossEntropyLoss()
    head_params = [p for p in model.parameters() if p.requires_grad]
    optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=10
    )

    # --- 1.3. train for several epochs ---
    EPOCHS = 8
    best_f1 = 0.0
    best_state = None
    for epoch in range(1, EPOCHS+1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_loss, train_acc, train_f1 = train_one_epoch(
            model, train_loader, optimizer, criterion, device
        )
        val_loss, val_acc, val_f1 = validate(
            model, val_loader, criterion, device
        )
        scheduler.step()
        print(
            f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
            f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
        )
        if val_f1 > best_f1:
            best_f1 = val_f1
            best_state = model.state_dict().copy()
            torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
            print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

    # --- Stage 2: unfreeze whole model, fine-tune ---
    print("\n--- Stage 2: Fine-tuning entire model ---")

    # --- 2.1. unfreeze entire model ---
    for param in model.parameters():
        param.requires_grad = True

    # --- 2.2. define loss, optimizer, scheduler ---
    optimizer = AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=15
    )

    # --- 2.3. mild class weights ---
    class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
    class_weights = (class_counts.sum() / class_counts)
    class_weights = class_weights / class_weights.mean()
    # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

    # --- 2.4. train for several epochs ---
    EPOCHS = 15
    best_f1 = 0.0
    best_state = None

    for epoch in range(1, EPOCHS + 1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_loss, train_acc, train_f1 = train_one_epoch(
            model, train_loader, optimizer, criterion, device
        )
        val_loss, val_acc, val_f1 = validate(
            model, val_loader, criterion, device
        )
        scheduler.step()
        print(
            f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
            f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
        )
        if val_f1 > best_f1:
            best_f1 = val_f1
            best_state = model.state_dict().copy()
            torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
            print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

    # --- save model for this fold ---
    torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=3.9967 | F1(macro)=0.2768 | Acc=0.2772


Confusion matrix:
 [[ 8 32 24 25]
 [ 5 30 28 20]
 [ 7 28 14 30]
 [ 2  5 15 10]]
Train  loss=3.9967 acc=0.2772 f1=0.2768 | Val loss=6.0264 acc=0.2191 f1=0.2068
  🔥 New best F1: 0.2068 – model saved.

Epoch 2/8


    t_loss=3.2213 | F1(macro)=0.3011 | Acc=0.3020


Confusion matrix:
 [[ 7 34 19 29]
 [ 7 22 24 30]
 [ 9 27  9 34]
 [ 4  9  4 15]]
Train  loss=3.2213 acc=0.3020 f1=0.3011 | Val loss=6.3091 acc=0.1873 f1=0.1799

Epoch 3/8


    t_loss=3.1608 | F1(macro)=0.3079 | Acc=0.3082


Confusion matrix:
 [[26 19 12 32]
 [28 10 21 24]
 [22 15 11 31]
 [ 9  7  2 14]]
Train  loss=3.1608 acc=0.3082 f1=0.3079 | Val loss=5.3463 acc=0.2155 f1=0.2087
  🔥 New best F1: 0.2087 – model saved.

Epoch 4/8


    t_loss=2.8275 | F1(macro)=0.3478 | Acc=0.3472


Confusion matrix:
 [[17 38 18 16]
 [11 38 19 15]
 [19 29 16 15]
 [ 9  9 10  4]]
Train  loss=2.8275 acc=0.3472 f1=0.3478 | Val loss=4.7971 acc=0.2650 f1=0.2358
  🔥 New best F1: 0.2358 – model saved.

Epoch 5/8


    t_loss=2.8737 | F1(macro)=0.3102 | Acc=0.3100


Confusion matrix:
 [[18 28 21 22]
 [13 28 24 18]
 [15 25 18 21]
 [ 8  9  9  6]]
Train  loss=2.8737 acc=0.3100 f1=0.3102 | Val loss=4.6261 acc=0.2473 f1=0.2338

Epoch 6/8


    t_loss=2.7841 | F1(macro)=0.2952 | Acc=0.2950


Confusion matrix:
 [[22 28 18 21]
 [ 8 30 30 15]
 [14 26 17 22]
 [ 8  8  8  8]]
Train  loss=2.7841 acc=0.2950 f1=0.2952 | Val loss=4.2760 acc=0.2721 f1=0.2605
  🔥 New best F1: 0.2605 – model saved.

Epoch 7/8


    t_loss=2.5413 | F1(macro)=0.3275 | Acc=0.3277


Confusion matrix:
 [[21 28 16 24]
 [17 32 22 12]
 [17 26 16 20]
 [ 9  8  8  7]]
Train  loss=2.5413 acc=0.3277 f1=0.3275 | Val loss=4.6411 acc=0.2686 f1=0.2526

Epoch 8/8


    t_loss=2.7171 | F1(macro)=0.3215 | Acc=0.3233


Confusion matrix:
 [[16 21 21 31]
 [14 22 28 19]
 [14 22 13 30]
 [ 8  6  9  9]]
Train  loss=2.7171 acc=0.3233 f1=0.3215 | Val loss=4.7186 acc=0.2120 f1=0.2087

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.5952 | F1(macro)=0.3075 | Acc=0.3136


Confusion matrix:
 [[29 23  6 31]
 [32 22  6 23]
 [32 25  3 19]
 [13  8  2  9]]
Train  loss=2.5952 acc=0.3136 f1=0.3075 | Val loss=3.0329 acc=0.2226 f1=0.1978
  🔥 New best F1: 0.1978 – model saved.

Epoch 2/15


    t_loss=1.7718 | F1(macro)=0.3392 | Acc=0.3472


Confusion matrix:
 [[22 11  2 54]
 [16 13  1 53]
 [12 12  3 52]
 [12  2  0 18]]
Train  loss=1.7718 acc=0.3472 f1=0.3392 | Val loss=2.6130 acc=0.1979 f1=0.1873

Epoch 3/15


    t_loss=1.4596 | F1(macro)=0.3571 | Acc=0.3702


Confusion matrix:
 [[ 5 11  4 69]
 [ 3 15  7 58]
 [ 0 23  4 52]
 [ 1  5  1 25]]
Train  loss=1.4596 acc=0.3702 f1=0.3571 | Val loss=2.5290 acc=0.1731 f1=0.1543

Epoch 4/15


    t_loss=1.3123 | F1(macro)=0.3875 | Acc=0.4066


Confusion matrix:
 [[40  9 14 26]
 [27 18 16 22]
 [23 10 23 23]
 [11  5  5 11]]
Train  loss=1.3123 acc=0.4066 f1=0.3875 | Val loss=1.8370 acc=0.3251 f1=0.3095
  🔥 New best F1: 0.3095 – model saved.

Epoch 5/15


    t_loss=1.3588 | F1(macro)=0.3819 | Acc=0.3871


Confusion matrix:
 [[11  2 33 43]
 [ 6  6 38 33]
 [ 7  7 25 40]
 [ 3  1  8 20]]
Train  loss=1.3588 acc=0.3871 f1=0.3819 | Val loss=1.9455 acc=0.2191 f1=0.2055

Epoch 6/15


    t_loss=1.1932 | F1(macro)=0.4329 | Acc=0.4579


Confusion matrix:
 [[ 3 13 22 51]
 [ 3 19 18 43]
 [ 1  6 25 47]
 [ 1  2  6 23]]
Train  loss=1.1932 acc=0.4579 f1=0.4329 | Val loss=1.9663 acc=0.2473 f1=0.2347

Epoch 7/15


    t_loss=1.1499 | F1(macro)=0.4363 | Acc=0.4668


Confusion matrix:
 [[13 20  9 47]
 [ 7 26  5 45]
 [ 5 20 19 35]
 [ 3  4  5 20]]
Train  loss=1.1499 acc=0.4668 f1=0.4363 | Val loss=1.8431 acc=0.2756 f1=0.2776

Epoch 8/15


    t_loss=1.1790 | F1(macro)=0.4305 | Acc=0.4526


Confusion matrix:
 [[11  7 11 60]
 [10  9 10 54]
 [ 8 13 11 47]
 [ 2  1  0 29]]
Train  loss=1.1790 acc=0.4526 f1=0.4305 | Val loss=1.9408 acc=0.2120 f1=0.2005

Epoch 9/15


    t_loss=1.0729 | F1(macro)=0.5115 | Acc=0.5341


Confusion matrix:
 [[25  4 14 46]
 [26  8  8 41]
 [24  8 10 37]
 [12  2  0 18]]
Train  loss=1.0729 acc=0.5341 f1=0.5115 | Val loss=1.9990 acc=0.2155 f1=0.2059

Epoch 10/15


    t_loss=1.0802 | F1(macro)=0.5196 | Acc=0.5306


Confusion matrix:
 [[38  8 13 30]
 [35 14 12 22]
 [32 10 13 24]
 [18  2  1 11]]
Train  loss=1.0802 acc=0.5306 f1=0.5196 | Val loss=1.8629 acc=0.2686 f1=0.2508

Epoch 11/15


    t_loss=1.0591 | F1(macro)=0.5232 | Acc=0.5368


Confusion matrix:
 [[26 12 10 41]
 [18 23 10 32]
 [21 16  8 34]
 [13  3  2 14]]
Train  loss=1.0591 acc=0.5368 f1=0.5232 | Val loss=1.8764 acc=0.2509 f1=0.2442

Epoch 12/15


    t_loss=1.0275 | F1(macro)=0.5422 | Acc=0.5545


Confusion matrix:
 [[18 14 15 42]
 [16 23  9 35]
 [13 16 14 36]
 [ 6  4  4 18]]
Train  loss=1.0275 acc=0.5545 f1=0.5422 | Val loss=1.7545 acc=0.2580 f1=0.2586

Epoch 13/15


    t_loss=1.0073 | F1(macro)=0.5370 | Acc=0.5554


Confusion matrix:
 [[22 17 14 36]
 [23 27  9 24]
 [21 17 14 27]
 [ 9  4  2 17]]
Train  loss=1.0073 acc=0.5554 f1=0.5370 | Val loss=1.7716 acc=0.2827 f1=0.2801

Epoch 14/15


    t_loss=1.0117 | F1(macro)=0.5516 | Acc=0.5624


Confusion matrix:
 [[23 22 15 29]
 [18 32 15 18]
 [19 24 18 18]
 [ 8  7  5 12]]
Train  loss=1.0117 acc=0.5624 f1=0.5516 | Val loss=1.7562 acc=0.3004 f1=0.2917

Epoch 15/15


    t_loss=0.9838 | F1(macro)=0.5809 | Acc=0.5934


Confusion matrix:
 [[19 16 19 35]
 [18 26 16 23]
 [17 23 14 25]
 [ 9  8  5 10]]
Train  loss=0.9838 acc=0.5934 f1=0.5809 | Val loss=1.7969 acc=0.2438 f1=0.2385

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.2099 | F1(macro)=0.2686 | Acc=0.2710


Confusion matrix:
 [[27 33 19 10]
 [18 38 19  8]
 [20 40 17  3]
 [ 5 15  6  5]]
Train  loss=4.2099 acc=0.2710 f1=0.2686 | Val loss=4.8986 acc=0.3074 f1=0.2800
  🔥 New best F1: 0.2800 – model saved.

Epoch 2/8


    t_loss=3.3732 | F1(macro)=0.2884 | Acc=0.2888


Confusion matrix:
 [[25 42 18  4]
 [12 41 22  8]
 [20 42 14  4]
 [ 5 16  6  4]]
Train  loss=3.3732 acc=0.2888 f1=0.2884 | Val loss=5.1883 acc=0.2968 f1=0.2635

Epoch 3/8


    t_loss=3.1639 | F1(macro)=0.2764 | Acc=0.2790


Confusion matrix:
 [[14 38 28  9]
 [10 38 25 10]
 [14 37 20  9]
 [ 3 14 10  4]]
Train  loss=3.1639 acc=0.2790 f1=0.2764 | Val loss=4.3516 acc=0.2686 f1=0.2374

Epoch 4/8


    t_loss=3.0897 | F1(macro)=0.2785 | Acc=0.2790


Confusion matrix:
 [[26 26 24 13]
 [12 28 26 17]
 [17 22 26 15]
 [ 7  6 12  6]]
Train  loss=3.0897 acc=0.2790 f1=0.2785 | Val loss=4.3070 acc=0.3039 f1=0.2849
  🔥 New best F1: 0.2849 – model saved.

Epoch 5/8


    t_loss=2.9515 | F1(macro)=0.2885 | Acc=0.2888


Confusion matrix:
 [[16 36 30  7]
 [12 22 31 18]
 [ 9 34 26 11]
 [ 3 13 13  2]]
Train  loss=2.9515 acc=0.2888 f1=0.2885 | Val loss=4.3834 acc=0.2332 f1=0.2072

Epoch 6/8


    t_loss=2.7967 | F1(macro)=0.2948 | Acc=0.2950


Confusion matrix:
 [[19 29 30 11]
 [15 28 25 15]
 [18 21 30 11]
 [ 5  5 14  7]]
Train  loss=2.7967 acc=0.2950 f1=0.2948 | Val loss=4.2214 acc=0.2968 f1=0.2799

Epoch 7/8


    t_loss=2.7141 | F1(macro)=0.2912 | Acc=0.2914


Confusion matrix:
 [[26 23 28 12]
 [18 23 32 10]
 [13 32 28  7]
 [ 3  7 16  5]]
Train  loss=2.7141 acc=0.2914 f1=0.2912 | Val loss=3.8391 acc=0.2898 f1=0.2702

Epoch 8/8


    t_loss=2.7945 | F1(macro)=0.3012 | Acc=0.3020


Confusion matrix:
 [[19 19 38 13]
 [15 14 39 15]
 [12 17 35 16]
 [ 3  3 20  5]]
Train  loss=2.7945 acc=0.3020 f1=0.3012 | Val loss=4.6781 acc=0.2580 f1=0.2341

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.6639 | F1(macro)=0.2968 | Acc=0.3020


Confusion matrix:
 [[15  8 17 49]
 [ 7 15 18 43]
 [17 10 20 33]
 [ 6  4  5 16]]
Train  loss=2.6639 acc=0.3020 f1=0.2968 | Val loss=2.9532 acc=0.2332 f1=0.2364
  🔥 New best F1: 0.2364 – model saved.

Epoch 2/15


    t_loss=1.7306 | F1(macro)=0.3077 | Acc=0.3224


Confusion matrix:
 [[ 5 22 28 34]
 [ 6 14 27 36]
 [ 9 12 28 31]
 [ 1  8 12 10]]
Train  loss=1.7306 acc=0.3224 f1=0.3077 | Val loss=2.3828 acc=0.2014 f1=0.1883

Epoch 3/15


    t_loss=1.4794 | F1(macro)=0.3495 | Acc=0.3596


Confusion matrix:
 [[14 64  0 11]
 [11 51 14  7]
 [12 41 16 11]
 [ 2 23  3  3]]
Train  loss=1.4794 acc=0.3596 f1=0.3495 | Val loss=2.1159 acc=0.2968 f1=0.2466
  🔥 New best F1: 0.2466 – model saved.

Epoch 4/15


    t_loss=1.3698 | F1(macro)=0.3686 | Acc=0.3853


Confusion matrix:
 [[21 50  6 12]
 [21 43 13  6]
 [25 31 17  7]
 [ 4 21  2  4]]
Train  loss=1.3698 acc=0.3853 f1=0.3686 | Val loss=1.7125 acc=0.3004 f1=0.2653
  🔥 New best F1: 0.2653 – model saved.

Epoch 5/15


    t_loss=1.2949 | F1(macro)=0.3911 | Acc=0.4039


Confusion matrix:
 [[34 28  2 25]
 [28 34  8 13]
 [32 22 11 15]
 [ 9  9  2 11]]
Train  loss=1.2949 acc=0.4039 f1=0.3911 | Val loss=1.6381 acc=0.3180 f1=0.2964
  🔥 New best F1: 0.2964 – model saved.

Epoch 6/15


    t_loss=1.2512 | F1(macro)=0.3689 | Acc=0.3959


Confusion matrix:
 [[27 22  5 35]
 [28 15  7 33]
 [31 20 11 18]
 [ 7  5  1 18]]
Train  loss=1.2512 acc=0.3959 f1=0.3689 | Val loss=1.7892 acc=0.2509 f1=0.2455

Epoch 7/15


    t_loss=1.1967 | F1(macro)=0.4169 | Acc=0.4376


Confusion matrix:
 [[38 30  4 17]
 [34 21 12 16]
 [30 16 24 10]
 [13  8  3  7]]
Train  loss=1.1967 acc=0.4376 f1=0.4169 | Val loss=1.5985 acc=0.3180 f1=0.3004
  🔥 New best F1: 0.3004 – model saved.

Epoch 8/15


    t_loss=1.1791 | F1(macro)=0.4418 | Acc=0.4562


Confusion matrix:
 [[21 33 13 22]
 [20 37 15 11]
 [16 25 27 12]
 [ 9 10  6  6]]
Train  loss=1.1791 acc=0.4562 f1=0.4418 | Val loss=1.6206 acc=0.3216 f1=0.2985

Epoch 9/15


    t_loss=1.1312 | F1(macro)=0.4747 | Acc=0.4880


Confusion matrix:
 [[26 26  8 29]
 [23 25 17 18]
 [21 11 30 18]
 [10  7  4 10]]
Train  loss=1.1312 acc=0.4880 f1=0.4747 | Val loss=1.5944 acc=0.3216 f1=0.3142
  🔥 New best F1: 0.3142 – model saved.

Epoch 10/15


    t_loss=1.1100 | F1(macro)=0.4793 | Acc=0.4916


Confusion matrix:
 [[19 29 12 29]
 [17 33 15 18]
 [17 30 20 13]
 [ 6 12  2 11]]
Train  loss=1.1100 acc=0.4916 f1=0.4793 | Val loss=1.6608 acc=0.2933 f1=0.2839

Epoch 11/15


    t_loss=1.0234 | F1(macro)=0.5221 | Acc=0.5438


Confusion matrix:
 [[25 22 14 28]
 [15 40 12 16]
 [15 29 20 16]
 [ 8 13  5  5]]
Train  loss=1.0234 acc=0.5438 f1=0.5221 | Val loss=1.7390 acc=0.3180 f1=0.2916

Epoch 12/15


    t_loss=0.9674 | F1(macro)=0.5396 | Acc=0.5686


Confusion matrix:
 [[16 37 14 22]
 [15 44  9 15]
 [11 34 19 16]
 [ 4 16  4  7]]
Train  loss=0.9674 acc=0.5686 f1=0.5396 | Val loss=1.7298 acc=0.3039 f1=0.2759

Epoch 13/15


    t_loss=1.0056 | F1(macro)=0.5575 | Acc=0.5748


Confusion matrix:
 [[21 31 14 23]
 [21 34 11 17]
 [17 21 24 18]
 [ 6 11  5  9]]
Train  loss=1.0056 acc=0.5748 f1=0.5575 | Val loss=1.6572 acc=0.3110 f1=0.2981

Epoch 14/15


    t_loss=0.9630 | F1(macro)=0.5720 | Acc=0.5881


Confusion matrix:
 [[12 34 27 16]
 [16 36 22  9]
 [10 14 40 16]
 [ 6  8 12  5]]
Train  loss=0.9630 acc=0.5881 f1=0.5720 | Val loss=1.6894 acc=0.3286 f1=0.2909

Epoch 15/15


    t_loss=0.9798 | F1(macro)=0.5518 | Acc=0.5669


Confusion matrix:
 [[18 32 18 21]
 [15 36 14 18]
 [16 22 28 14]
 [ 7 11  4  9]]
Train  loss=0.9798 acc=0.5669 f1=0.5518 | Val loss=1.5939 acc=0.3216 f1=0.3055

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.0947 | F1(macro)=0.2600 | Acc=0.2602


Confusion matrix:
 [[19 13  5 52]
 [ 8  9 14 51]
 [25 10  7 38]
 [ 5  3  5 18]]
Train  loss=4.0947 acc=0.2602 f1=0.2600 | Val loss=7.8427 acc=0.1879 f1=0.1824
  🔥 New best F1: 0.1824 – model saved.

Epoch 2/8


    t_loss=3.4177 | F1(macro)=0.3148 | Acc=0.3150


Confusion matrix:
 [[31 24  5 29]
 [21 20 11 30]
 [32 12  7 29]
 [11  7  3 10]]
Train  loss=3.4177 acc=0.3150 f1=0.3148 | Val loss=6.0895 acc=0.2411 f1=0.2250
  🔥 New best F1: 0.2250 – model saved.

Epoch 3/8


    t_loss=3.1805 | F1(macro)=0.3047 | Acc=0.3053


Confusion matrix:
 [[37 19 11 22]
 [39 19  7 17]
 [45 12  9 14]
 [12  6  5  8]]
Train  loss=3.1805 acc=0.3053 f1=0.3047 | Val loss=5.2721 acc=0.2589 f1=0.2358
  🔥 New best F1: 0.2358 – model saved.

Epoch 4/8


    t_loss=3.1652 | F1(macro)=0.2653 | Acc=0.2655


Confusion matrix:
 [[27 28 10 24]
 [15 21 19 27]
 [31 17 13 19]
 [16  5  3  7]]
Train  loss=3.1652 acc=0.2655 f1=0.2653 | Val loss=5.2456 acc=0.2411 f1=0.2289

Epoch 5/8


    t_loss=2.8510 | F1(macro)=0.3271 | Acc=0.3283


Confusion matrix:
 [[31 26 10 22]
 [22 17 21 22]
 [31 12 10 27]
 [16  3  3  9]]
Train  loss=2.8510 acc=0.3283 f1=0.3271 | Val loss=5.1383 acc=0.2376 f1=0.2236

Epoch 6/8


    t_loss=2.7848 | F1(macro)=0.3080 | Acc=0.3097


Confusion matrix:
 [[25 31  4 29]
 [18 31 11 22]
 [26 25 12 17]
 [ 9  8  4 10]]
Train  loss=2.7848 acc=0.3097 f1=0.3080 | Val loss=5.0017 acc=0.2766 f1=0.2623
  🔥 New best F1: 0.2623 – model saved.

Epoch 7/8


    t_loss=2.6611 | F1(macro)=0.3236 | Acc=0.3239


Confusion matrix:
 [[25 32 10 22]
 [11 28 20 23]
 [35 18  6 21]
 [ 7 10  4 10]]
Train  loss=2.6611 acc=0.3239 f1=0.3236 | Val loss=4.8131 acc=0.2447 f1=0.2289

Epoch 8/8


    t_loss=2.6353 | F1(macro)=0.3175 | Acc=0.3177


Confusion matrix:
 [[17 37  5 30]
 [11 28 14 29]
 [20 27  8 25]
 [ 9  6  3 13]]
Train  loss=2.6353 acc=0.3177 f1=0.3175 | Val loss=5.4019 acc=0.2340 f1=0.2231

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.5106 | F1(macro)=0.3210 | Acc=0.3283


Confusion matrix:
 [[48  6  7 28]
 [35  4 24 19]
 [41  6  7 26]
 [15  2  3 11]]
Train  loss=2.5106 acc=0.3283 f1=0.3210 | Val loss=3.1912 acc=0.2482 f1=0.2020
  🔥 New best F1: 0.2020 – model saved.

Epoch 2/15


    t_loss=1.7899 | F1(macro)=0.3462 | Acc=0.3575


Confusion matrix:
 [[12 33  1 43]
 [14 29  7 32]
 [17 27  5 31]
 [ 6 11  1 13]]
Train  loss=1.7899 acc=0.3575 f1=0.3462 | Val loss=2.3966 acc=0.2092 f1=0.1931

Epoch 3/15


    t_loss=1.4212 | F1(macro)=0.3617 | Acc=0.3832


Confusion matrix:
 [[10 45  2 32]
 [11 35  2 34]
 [22 23  3 32]
 [ 9  8  2 12]]
Train  loss=1.4212 acc=0.3832 f1=0.3617 | Val loss=2.2592 acc=0.2128 f1=0.1855

Epoch 4/15


    t_loss=1.3657 | F1(macro)=0.3904 | Acc=0.4000


Confusion matrix:
 [[ 7 24  7 51]
 [ 4 34 11 33]
 [ 7 23 14 36]
 [ 5  7  3 16]]
Train  loss=1.3657 acc=0.4000 f1=0.3904 | Val loss=1.8128 acc=0.2518 f1=0.2400
  🔥 New best F1: 0.2400 – model saved.

Epoch 5/15


    t_loss=1.2765 | F1(macro)=0.4181 | Acc=0.4319


Confusion matrix:
 [[14 10  4 61]
 [ 8 23  3 48]
 [12  8 12 48]
 [ 3  5  2 21]]
Train  loss=1.2765 acc=0.4319 f1=0.4181 | Val loss=1.8841 acc=0.2482 f1=0.2550
  🔥 New best F1: 0.2550 – model saved.

Epoch 6/15


    t_loss=1.2366 | F1(macro)=0.3893 | Acc=0.4159


Confusion matrix:
 [[21 24  1 43]
 [18 29  1 34]
 [20 13  4 43]
 [ 7  7  0 17]]
Train  loss=1.2366 acc=0.4159 f1=0.3893 | Val loss=1.8360 acc=0.2518 f1=0.2351

Epoch 7/15


    t_loss=1.2051 | F1(macro)=0.4305 | Acc=0.4496


Confusion matrix:
 [[37 39  2 11]
 [22 42  6 12]
 [22 26 13 19]
 [11 11  1  8]]
Train  loss=1.2051 acc=0.4496 f1=0.4305 | Val loss=1.6027 acc=0.3546 f1=0.3203
  🔥 New best F1: 0.3203 – model saved.

Epoch 8/15


    t_loss=1.1623 | F1(macro)=0.4448 | Acc=0.4673


Confusion matrix:
 [[34 37  0 18]
 [20 45  2 15]
 [22 28 12 18]
 [14 12  1  4]]
Train  loss=1.1623 acc=0.4673 f1=0.4448 | Val loss=1.7003 acc=0.3369 f1=0.2917

Epoch 9/15


    t_loss=1.1693 | F1(macro)=0.4409 | Acc=0.4549


Confusion matrix:
 [[32 18  2 37]
 [16 37  3 26]
 [28 18 11 23]
 [12  3  2 14]]
Train  loss=1.1693 acc=0.4549 f1=0.4409 | Val loss=1.6315 acc=0.3333 f1=0.3170

Epoch 10/15


    t_loss=1.0821 | F1(macro)=0.5333 | Acc=0.5407


Confusion matrix:
 [[33 12 16 28]
 [21 29 11 21]
 [30  8 22 20]
 [12  3  5 11]]
Train  loss=1.0821 acc=0.5407 f1=0.5333 | Val loss=1.6268 acc=0.3369 f1=0.3290
  🔥 New best F1: 0.3290 – model saved.

Epoch 11/15


    t_loss=1.0839 | F1(macro)=0.5019 | Acc=0.5159


Confusion matrix:
 [[13 28 12 36]
 [10 36 14 22]
 [14 16 20 30]
 [ 8  3  2 18]]
Train  loss=1.0839 acc=0.5159 f1=0.5019 | Val loss=1.6242 acc=0.3085 f1=0.3014

Epoch 12/15


    t_loss=1.0376 | F1(macro)=0.5152 | Acc=0.5327


Confusion matrix:
 [[21 34 13 21]
 [21 35 10 16]
 [16 17 19 28]
 [11  7  2 11]]
Train  loss=1.0376 acc=0.5327 f1=0.5152 | Val loss=1.5987 acc=0.3050 f1=0.2945

Epoch 13/15


    t_loss=0.9725 | F1(macro)=0.5756 | Acc=0.5920


Confusion matrix:
 [[17 37  8 27]
 [11 45  6 20]
 [14 21 15 30]
 [ 7 10  3 11]]
Train  loss=0.9725 acc=0.5920 f1=0.5756 | Val loss=1.6854 acc=0.3121 f1=0.2902

Epoch 14/15


    t_loss=0.9619 | F1(macro)=0.5809 | Acc=0.5965


Confusion matrix:
 [[34 25 12 18]
 [16 37 11 18]
 [27 14 20 19]
 [12  8  2  9]]
Train  loss=0.9619 acc=0.5965 f1=0.5809 | Val loss=1.5935 acc=0.3546 f1=0.3343
  🔥 New best F1: 0.3343 – model saved.

Epoch 15/15


    t_loss=0.9337 | F1(macro)=0.5814 | Acc=0.6018


Confusion matrix:
 [[30 21  7 31]
 [22 32  7 21]
 [23 14 18 25]
 [12  5  3 11]]
Train  loss=0.9337 acc=0.6018 f1=0.5814 | Val loss=1.6525 acc=0.3227 f1=0.3136

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.3815 | F1(macro)=0.2466 | Acc=0.2469


Confusion matrix:
 [[10  3 30 46]
 [ 7  2 31 43]
 [ 5  2 44 28]
 [ 5  0 13 13]]
Train  loss=4.3815 acc=0.2469 f1=0.2466 | Val loss=7.6817 acc=0.2447 f1=0.2063
  🔥 New best F1: 0.2063 – model saved.

Epoch 2/8


    t_loss=3.3295 | F1(macro)=0.2954 | Acc=0.2956


Confusion matrix:
 [[10  3 39 37]
 [ 2  5 33 43]
 [ 5  0 39 35]
 [ 4  1 16 10]]
Train  loss=3.3295 acc=0.2956 f1=0.2954 | Val loss=6.9805 acc=0.2270 f1=0.1993

Epoch 3/8


    t_loss=3.2463 | F1(macro)=0.2510 | Acc=0.2522


Confusion matrix:
 [[ 7  7 41 34]
 [ 4  8 38 33]
 [ 5  4 48 22]
 [ 0  2 17 12]]
Train  loss=3.2463 acc=0.2522 f1=0.2510 | Val loss=6.8421 acc=0.2660 f1=0.2249
  🔥 New best F1: 0.2249 – model saved.

Epoch 4/8


    t_loss=3.2460 | F1(macro)=0.2533 | Acc=0.2531


Confusion matrix:
 [[ 7  4 46 32]
 [ 4  4 36 39]
 [ 5  3 43 28]
 [ 1  0 22  8]]
Train  loss=3.2460 acc=0.2531 f1=0.2533 | Val loss=6.1920 acc=0.2199 f1=0.1784

Epoch 5/8


    t_loss=3.0214 | F1(macro)=0.2819 | Acc=0.2841


Confusion matrix:
 [[12  6 33 38]
 [ 5  5 37 36]
 [10  1 42 26]
 [ 3  0 14 14]]
Train  loss=3.0214 acc=0.2841 f1=0.2819 | Val loss=6.0913 acc=0.2589 f1=0.2275
  🔥 New best F1: 0.2275 – model saved.

Epoch 6/8


    t_loss=2.7635 | F1(macro)=0.2900 | Acc=0.2920


Confusion matrix:
 [[ 9  4 57 19]
 [ 5  5 48 25]
 [ 5  1 56 17]
 [ 1  0 28  2]]
Train  loss=2.7635 acc=0.2920 f1=0.2900 | Val loss=6.4230 acc=0.2553 f1=0.1833

Epoch 7/8


    t_loss=2.7768 | F1(macro)=0.2966 | Acc=0.2973


Confusion matrix:
 [[ 5  1 50 33]
 [ 2  1 48 32]
 [ 4  1 56 18]
 [ 1  0 26  4]]
Train  loss=2.7768 acc=0.2973 f1=0.2966 | Val loss=6.9993 acc=0.2340 f1=0.1556

Epoch 8/8


    t_loss=2.8873 | F1(macro)=0.2825 | Acc=0.2823


Confusion matrix:
 [[11  3 37 38]
 [ 5  3 36 39]
 [ 7  3 50 19]
 [ 3  1 16 11]]
Train  loss=2.8873 acc=0.2823 f1=0.2825 | Val loss=5.7743 acc=0.2660 f1=0.2185

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.6901 | F1(macro)=0.2856 | Acc=0.2903


Confusion matrix:
 [[35  0 15 39]
 [27  4 12 40]
 [24  0 28 27]
 [13  0  3 15]]
Train  loss=2.6901 acc=0.2903 f1=0.2856 | Val loss=3.1962 acc=0.2908 f1=0.2676
  🔥 New best F1: 0.2676 – model saved.

Epoch 2/15


    t_loss=1.8107 | F1(macro)=0.3302 | Acc=0.3354


Confusion matrix:
 [[ 2  1 16 70]
 [ 4  6 22 51]
 [ 0  4 34 41]
 [ 2  0  5 24]]
Train  loss=1.8107 acc=0.3354 f1=0.3302 | Val loss=2.5584 acc=0.2340 f1=0.2065

Epoch 3/15


    t_loss=1.5369 | F1(macro)=0.3426 | Acc=0.3504


Confusion matrix:
 [[37  2 11 39]
 [28 16  7 32]
 [22 16 13 28]
 [14  2  4 11]]
Train  loss=1.5369 acc=0.3504 f1=0.3426 | Val loss=1.9709 acc=0.2730 f1=0.2606

Epoch 4/15


    t_loss=1.3590 | F1(macro)=0.3581 | Acc=0.3708


Confusion matrix:
 [[55  4  5 25]
 [45 16  4 18]
 [35  6 24 14]
 [20  1  3  7]]
Train  loss=1.3590 acc=0.3708 f1=0.3581 | Val loss=1.6865 acc=0.3617 f1=0.3266
  🔥 New best F1: 0.3266 – model saved.

Epoch 5/15


    t_loss=1.2761 | F1(macro)=0.3711 | Acc=0.3947


Confusion matrix:
 [[ 9  0 45 35]
 [11  9 38 25]
 [ 8  0 52 19]
 [ 3  0 16 12]]
Train  loss=1.2761 acc=0.3947 f1=0.3711 | Val loss=1.8201 acc=0.2908 f1=0.2486

Epoch 6/15


    t_loss=1.2560 | F1(macro)=0.3546 | Acc=0.3876


Confusion matrix:
 [[24  1 19 45]
 [24 18 14 27]
 [17  7 31 24]
 [ 9  0  8 14]]
Train  loss=1.2560 acc=0.3876 f1=0.3546 | Val loss=1.6137 acc=0.3085 f1=0.3085

Epoch 7/15


    t_loss=1.1766 | F1(macro)=0.4131 | Acc=0.4425


Confusion matrix:
 [[11 10 27 41]
 [ 6 23 22 32]
 [ 7  9 43 20]
 [ 5  4  6 16]]
Train  loss=1.1766 acc=0.4425 f1=0.4131 | Val loss=1.5616 acc=0.3298 f1=0.3144

Epoch 8/15


    t_loss=1.2025 | F1(macro)=0.4166 | Acc=0.4327


Confusion matrix:
 [[13 17 23 36]
 [22 21 16 24]
 [15  7 41 16]
 [ 7  3  8 13]]
Train  loss=1.2025 acc=0.4327 f1=0.4166 | Val loss=1.5730 acc=0.3121 f1=0.3016

Epoch 9/15


    t_loss=1.1292 | F1(macro)=0.4429 | Acc=0.4717


Confusion matrix:
 [[ 9  4 46 30]
 [ 8 15 36 24]
 [10  1 49 19]
 [ 6  0 14 11]]
Train  loss=1.1292 acc=0.4717 f1=0.4429 | Val loss=1.6864 acc=0.2979 f1=0.2669

Epoch 10/15


    t_loss=1.1168 | F1(macro)=0.4572 | Acc=0.4770


Confusion matrix:
 [[14  1 36 38]
 [15 14 24 30]
 [15  1 44 19]
 [ 7  0 11 13]]
Train  loss=1.1168 acc=0.4770 f1=0.4572 | Val loss=1.6889 acc=0.3014 f1=0.2837

Epoch 11/15


    t_loss=1.0811 | F1(macro)=0.4845 | Acc=0.5062


Confusion matrix:
 [[29 10 21 29]
 [25 16 21 21]
 [22  4 37 16]
 [ 9  1 10 11]]
Train  loss=1.0811 acc=0.5062 f1=0.4845 | Val loss=1.6390 acc=0.3298 f1=0.3146

Epoch 12/15


    t_loss=1.0835 | F1(macro)=0.5081 | Acc=0.5195


Confusion matrix:
 [[19 10 31 29]
 [20 15 27 21]
 [16  4 43 16]
 [ 5  0 15 11]]
Train  loss=1.0835 acc=0.5195 f1=0.5081 | Val loss=1.6644 acc=0.3121 f1=0.2919

Epoch 13/15


    t_loss=1.0539 | F1(macro)=0.5036 | Acc=0.5230


Confusion matrix:
 [[18  6 24 41]
 [12 16 27 28]
 [10  4 38 27]
 [ 2  1  8 20]]
Train  loss=1.0539 acc=0.5230 f1=0.5036 | Val loss=1.6973 acc=0.3262 f1=0.3174

Epoch 14/15


    t_loss=1.0014 | F1(macro)=0.5347 | Acc=0.5566


Confusion matrix:
 [[18  9 21 41]
 [14 17 20 32]
 [16  6 36 21]
 [ 4  1 10 16]]
Train  loss=1.0014 acc=0.5566 f1=0.5347 | Val loss=1.6379 acc=0.3085 f1=0.3023

Epoch 15/15


    t_loss=1.0329 | F1(macro)=0.5340 | Acc=0.5478


Confusion matrix:
 [[16  5 27 41]
 [18 13 29 23]
 [19  5 39 16]
 [ 8  2  7 14]]
Train  loss=1.0329 acc=0.5478 f1=0.5340 | Val loss=1.6938 acc=0.2908 f1=0.2773

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.6220 | F1(macro)=0.2583 | Acc=0.2584


Confusion matrix:
 [[13 45 10 21]
 [18 44  9 12]
 [14 42  9 14]
 [ 7 15  5  4]]
Train  loss=4.6220 acc=0.2584 f1=0.2583 | Val loss=5.8907 acc=0.2482 f1=0.2067
  🔥 New best F1: 0.2067 – model saved.

Epoch 2/8


    t_loss=3.5643 | F1(macro)=0.2923 | Acc=0.2929


Confusion matrix:
 [[23 27 20 19]
 [27 33 21  2]
 [14 33 22 10]
 [ 9  5 14  3]]
Train  loss=3.5643 acc=0.2929 f1=0.2923 | Val loss=4.6518 acc=0.2872 f1=0.2557
  🔥 New best F1: 0.2557 – model saved.

Epoch 3/8


    t_loss=3.2977 | F1(macro)=0.2935 | Acc=0.2938


Confusion matrix:
 [[33 34 15  7]
 [26 33 13 11]
 [23 32 17  7]
 [12 10  7  2]]
Train  loss=3.2977 acc=0.2938 f1=0.2935 | Val loss=4.9674 acc=0.3014 f1=0.2582
  🔥 New best F1: 0.2582 – model saved.

Epoch 4/8


    t_loss=3.0531 | F1(macro)=0.3092 | Acc=0.3088


Confusion matrix:
 [[ 8 52 17 12]
 [14 47 11 11]
 [ 8 44 20  7]
 [ 2 12 12  5]]
Train  loss=3.0531 acc=0.3088 f1=0.3092 | Val loss=5.1879 acc=0.2837 f1=0.2416

Epoch 5/8


    t_loss=2.9158 | F1(macro)=0.2941 | Acc=0.2965


Confusion matrix:
 [[22 31 19 17]
 [20 30 22 11]
 [14 29 24 12]
 [ 8  9 12  2]]
Train  loss=2.9158 acc=0.2965 f1=0.2941 | Val loss=4.3023 acc=0.2766 f1=0.2449

Epoch 6/8


    t_loss=2.8653 | F1(macro)=0.3023 | Acc=0.3035


Confusion matrix:
 [[18 30 13 28]
 [13 39  9 22]
 [13 31 18 17]
 [ 5 12  7  7]]
Train  loss=2.8653 acc=0.3035 f1=0.3023 | Val loss=4.5779 acc=0.2908 f1=0.2700
  🔥 New best F1: 0.2700 – model saved.

Epoch 7/8


    t_loss=2.7365 | F1(macro)=0.3225 | Acc=0.3230


Confusion matrix:
 [[15 37 11 26]
 [10 45 13 15]
 [15 37 17 10]
 [ 7 10 11  3]]
Train  loss=2.7365 acc=0.3230 f1=0.3225 | Val loss=4.3276 acc=0.2837 f1=0.2438

Epoch 8/8


    t_loss=2.6815 | F1(macro)=0.3029 | Acc=0.3027


Confusion matrix:
 [[10 40 18 21]
 [10 47 17  9]
 [ 7 39 23 10]
 [ 2 13 13  3]]
Train  loss=2.6815 acc=0.3027 f1=0.3029 | Val loss=4.6102 acc=0.2943 f1=0.2452

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.6484 | F1(macro)=0.3063 | Acc=0.3159


Confusion matrix:
 [[ 0 41 19 29]
 [ 1 36 22 24]
 [ 0 30 35 14]
 [ 0 15  8  8]]
Train  loss=2.6484 acc=0.3159 f1=0.3063 | Val loss=4.1167 acc=0.2801 f1=0.2329
  🔥 New best F1: 0.2329 – model saved.

Epoch 2/15


    t_loss=1.9873 | F1(macro)=0.2995 | Acc=0.3080


Confusion matrix:
 [[24 33  4 28]
 [19 26  7 31]
 [13 32  4 30]
 [10  8  2 11]]
Train  loss=1.9873 acc=0.3080 f1=0.2995 | Val loss=2.4675 acc=0.2305 f1=0.2117

Epoch 3/15


    t_loss=1.5190 | F1(macro)=0.3829 | Acc=0.4009


Confusion matrix:
 [[23 13  6 47]
 [15 22 13 33]
 [17 18 12 32]
 [10  5  2 14]]
Train  loss=1.5190 acc=0.4009 f1=0.3829 | Val loss=1.9412 acc=0.2518 f1=0.2508
  🔥 New best F1: 0.2508 – model saved.

Epoch 4/15


    t_loss=1.4008 | F1(macro)=0.3851 | Acc=0.4053


Confusion matrix:
 [[21 26  3 39]
 [18 23  4 38]
 [14 19 12 34]
 [ 9  5  5 12]]
Train  loss=1.4008 acc=0.4053 f1=0.3851 | Val loss=1.8984 acc=0.2411 f1=0.2405

Epoch 5/15


    t_loss=1.3905 | F1(macro)=0.4000 | Acc=0.4062


Confusion matrix:
 [[13 14  7 55]
 [15 27  8 33]
 [12 16 13 38]
 [ 7  7  4 13]]
Train  loss=1.3905 acc=0.4062 f1=0.4000 | Val loss=1.7998 acc=0.2340 f1=0.2364

Epoch 6/15


    t_loss=1.2395 | F1(macro)=0.4197 | Acc=0.4416


Confusion matrix:
 [[ 7 16  6 60]
 [ 9 22  9 43]
 [ 6 13 13 47]
 [ 4  5  2 20]]
Train  loss=1.2395 acc=0.4416 f1=0.4197 | Val loss=1.8640 acc=0.2199 f1=0.2190

Epoch 7/15


    t_loss=1.2667 | F1(macro)=0.4120 | Acc=0.4230


Confusion matrix:
 [[10 26  7 46]
 [11 26 10 36]
 [ 7 17 17 38]
 [ 3  8  3 17]]
Train  loss=1.2667 acc=0.4230 f1=0.4120 | Val loss=1.6739 acc=0.2482 f1=0.2468

Epoch 8/15


    t_loss=1.1817 | F1(macro)=0.4538 | Acc=0.4664


Confusion matrix:
 [[37 18 16 18]
 [27 29 14 13]
 [20 15 26 18]
 [14  5  6  6]]
Train  loss=1.1817 acc=0.4664 f1=0.4538 | Val loss=1.6789 acc=0.3475 f1=0.3227
  🔥 New best F1: 0.3227 – model saved.

Epoch 9/15


    t_loss=1.1493 | F1(macro)=0.4504 | Acc=0.4735


Confusion matrix:
 [[43 23  1 22]
 [34 25  5 19]
 [20 21 15 23]
 [11  8  6  6]]
Train  loss=1.1493 acc=0.4735 f1=0.4504 | Val loss=1.7724 acc=0.3156 f1=0.2877

Epoch 10/15


    t_loss=1.1219 | F1(macro)=0.4865 | Acc=0.4973


Confusion matrix:
 [[24  8  6 51]
 [23 14 10 36]
 [21  6 17 35]
 [11  2  3 15]]
Train  loss=1.1219 acc=0.4973 f1=0.4865 | Val loss=1.9512 acc=0.2482 f1=0.2519

Epoch 11/15


    t_loss=1.0866 | F1(macro)=0.5103 | Acc=0.5274


Confusion matrix:
 [[ 9 17 13 50]
 [ 4 32 19 28]
 [ 5 18 25 31]
 [ 2  7  9 13]]
Train  loss=1.0866 acc=0.5274 f1=0.5103 | Val loss=1.7597 acc=0.2801 f1=0.2719

Epoch 12/15


    t_loss=1.0231 | F1(macro)=0.5172 | Acc=0.5327


Confusion matrix:
 [[31 16  9 33]
 [21 32  9 21]
 [15 18 24 22]
 [11  5  5 10]]
Train  loss=1.0231 acc=0.5327 f1=0.5172 | Val loss=1.6868 acc=0.3440 f1=0.3347
  🔥 New best F1: 0.3347 – model saved.

Epoch 13/15


    t_loss=1.0145 | F1(macro)=0.5434 | Acc=0.5637


Confusion matrix:
 [[25 19 17 28]
 [21 31 10 21]
 [19 17 25 18]
 [13  4  7  7]]
Train  loss=1.0145 acc=0.5637 f1=0.5434 | Val loss=1.6999 acc=0.3121 f1=0.2994

Epoch 14/15


    t_loss=1.0205 | F1(macro)=0.5384 | Acc=0.5549


Confusion matrix:
 [[32 16 20 21]
 [29 29 13 12]
 [20 16 33 10]
 [13  3 10  5]]
Train  loss=1.0205 acc=0.5549 f1=0.5384 | Val loss=1.7567 acc=0.3511 f1=0.3242

Epoch 15/15


    t_loss=1.0018 | F1(macro)=0.5432 | Acc=0.5646


Confusion matrix:
 [[25 17 13 34]
 [21 28 15 19]
 [21 14 26 18]
 [ 8  7  8  8]]
Train  loss=1.0018 acc=0.5646 f1=0.5432 | Val loss=1.7304 acc=0.3085 f1=0.2987


In [3]:
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(test_df, transforms=val_test_transforms, is_train=False)
test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
                         shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")
    model = timm.create_model(PRETRAINED_MODEL, pretrained=False, num_classes=N_CLASSES).to(device)
    model.load_state_dict(torch.load(f"effv2_s_fold{fold}.pth", map_location=device))
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            img_tensor = img_tensor.squeeze(0)  # [3,H,W]
            img_tensor = img_tensor.to(device)

            # -------- TTA: apply multiple augmented views --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1,4]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N, 4]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
pred_indices = mean_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv("submission_5fold_tta.csv", index=False)

print("Saved submission_5fold_tta.csv")

Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_tta.csv
