In [1]:
import enum
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from timm.layers import Conv2dSame
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.persistence_manager import PersistenceManager
from internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B0

In [4]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=True,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_efficientnet_b0_model()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        clf_module, clf_name = get_classifier_module(model)
        for param in clf_module.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effb0_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effb0_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")


========== Fold 0 ==========


model.safetensors:   0%|          | 0.00/21.4M [00:00<?, ?B/s]


--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.2022 | F1(macro)=0.2515 | Acc=0.2522


Confusion matrix:
 [[ 9 13  9 10]
 [ 6  7  9 10]
 [ 9  5  4 12]
 [ 2  4  4  4]]
Train  loss=2.2022 acc=0.2522 f1=0.2515 | Val loss=2.5774 acc=0.2051 f1=0.2003
  🔥 New best F1: 0.2003 – model saved.

Epoch 2/8


    t_loss=1.9645 | F1(macro)=0.3054 | Acc=0.3060


Confusion matrix:
 [[ 7 13  7 14]
 [ 7  9  5 11]
 [ 4  5  9 12]
 [ 2  3  2  7]]
Train  loss=1.9645 acc=0.3060 f1=0.3054 | Val loss=2.4647 acc=0.2735 f1=0.2752
  🔥 New best F1: 0.2752 – model saved.

Epoch 3/8


    t_loss=1.9239 | F1(macro)=0.2783 | Acc=0.2866


Confusion matrix:
 [[ 9  9 11 12]
 [ 8  5  9 10]
 [ 7  2 11 10]
 [ 4  2  3  5]]
Train  loss=1.9239 acc=0.2866 f1=0.2783 | Val loss=2.4622 acc=0.2564 f1=0.2502

Epoch 4/8


    t_loss=1.8749 | F1(macro)=0.2770 | Acc=0.2823


Confusion matrix:
 [[ 7 14  8 12]
 [ 7  7  8 10]
 [ 5  5 10 10]
 [ 2  5  3  4]]
Train  loss=1.8749 acc=0.2823 f1=0.2770 | Val loss=2.3130 acc=0.2393 f1=0.2368

Epoch 5/8


    t_loss=1.7691 | F1(macro)=0.3012 | Acc=0.3039


Confusion matrix:
 [[ 5 13  8 15]
 [ 8  7  6 11]
 [ 6  6  5 13]
 [ 2  6  4  2]]
Train  loss=1.7691 acc=0.3039 f1=0.3012 | Val loss=2.3873 acc=0.1624 f1=0.1604

Epoch 6/8


    t_loss=1.8693 | F1(macro)=0.2746 | Acc=0.2759


Confusion matrix:
 [[10 12 10  9]
 [10  6  8  8]
 [ 9  3  9  9]
 [ 2  3  3  6]]
Train  loss=1.8693 acc=0.2759 f1=0.2746 | Val loss=2.3596 acc=0.2650 f1=0.2632

Epoch 7/8


    t_loss=1.7106 | F1(macro)=0.2813 | Acc=0.2802


Confusion matrix:
 [[ 7 13  7 14]
 [ 6  8  5 13]
 [ 6  4  7 13]
 [ 2  4  4  4]]
Train  loss=1.7106 acc=0.2802 f1=0.2813 | Val loss=2.4352 acc=0.2222 f1=0.2225

Epoch 8/8


    t_loss=1.8113 | F1(macro)=0.2747 | Acc=0.2759


Confusion matrix:
 [[ 8 14 11  8]
 [ 9  7 10  6]
 [ 5  4 11 10]
 [ 3  3  5  3]]
Train  loss=1.8113 acc=0.2759 f1=0.2747 | Val loss=2.2653 acc=0.2479 f1=0.2376
Restored best Stage 1 weights for fold 0 (F1=0.2752)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.5599 | F1(macro)=0.3281 | Acc=0.3491


Confusion matrix:
 [[ 6 13  6 16]
 [ 5 10  6 11]
 [ 3  6  7 14]
 [ 2  5  2  5]]
Train  loss=1.5599 acc=0.3491 f1=0.3281 | Val loss=2.4015 acc=0.2393 f1=0.2387
  🔥 New best F1: 0.2387 – model saved.

Epoch 2/12


    t_loss=1.5455 | F1(macro)=0.3502 | Acc=0.3707


Confusion matrix:
 [[ 6 11 12 12]
 [ 4  8 10 10]
 [ 4  4 13  9]
 [ 2  4  5  3]]
Train  loss=1.5455 acc=0.3707 f1=0.3502 | Val loss=2.2559 acc=0.2564 f1=0.2445
  🔥 New best F1: 0.2445 – model saved.

Epoch 3/12


    t_loss=1.3477 | F1(macro)=0.4227 | Acc=0.4375


Confusion matrix:
 [[ 6 16 11  8]
 [ 6 14  4  8]
 [ 4  6  9 11]
 [ 3  5  3  3]]
Train  loss=1.3477 acc=0.4375 f1=0.4227 | Val loss=2.2852 acc=0.2735 f1=0.2589
  🔥 New best F1: 0.2589 – model saved.

Epoch 4/12


    t_loss=1.1956 | F1(macro)=0.4709 | Acc=0.4978


Confusion matrix:
 [[16 13  5  7]
 [ 9 10  5  8]
 [10 10  7  3]
 [ 8  2  3  1]]
Train  loss=1.1956 acc=0.4978 f1=0.4709 | Val loss=2.2893 acc=0.2906 f1=0.2550

Epoch 5/12


    t_loss=1.1296 | F1(macro)=0.4846 | Acc=0.5086


Confusion matrix:
 [[ 9 12  7 13]
 [12  6  6  8]
 [ 7  3  6 14]
 [ 6  4  1  3]]
Train  loss=1.1296 acc=0.5086 f1=0.4846 | Val loss=2.3093 acc=0.2051 f1=0.2015

Epoch 6/12


    t_loss=1.1681 | F1(macro)=0.4617 | Acc=0.4828


Confusion matrix:
 [[ 6 13 11 11]
 [ 2 13  8  9]
 [ 4  5 11 10]
 [ 3  4  4  3]]
Train  loss=1.1681 acc=0.4828 f1=0.4617 | Val loss=2.1910 acc=0.2821 f1=0.2684
  🔥 New best F1: 0.2684 – model saved.

Epoch 7/12


    t_loss=1.1132 | F1(macro)=0.5679 | Acc=0.5797


Confusion matrix:
 [[ 6 14 12  9]
 [ 4 12  8  8]
 [ 5  5 14  6]
 [ 3  3  3  5]]
Train  loss=1.1132 acc=0.5797 f1=0.5679 | Val loss=2.0848 acc=0.3162 f1=0.3058
  🔥 New best F1: 0.3058 – model saved.

Epoch 8/12


    t_loss=1.0321 | F1(macro)=0.5430 | Acc=0.5647


Confusion matrix:
 [[ 9 11 11 10]
 [ 9  9  6  8]
 [ 7  3 12  8]
 [ 6  3  2  3]]
Train  loss=1.0321 acc=0.5647 f1=0.5430 | Val loss=2.2213 acc=0.2821 f1=0.2733

Epoch 9/12


    t_loss=1.0839 | F1(macro)=0.5449 | Acc=0.5517


Confusion matrix:
 [[10 10 12  9]
 [ 8  7  8  9]
 [ 6  4 12  8]
 [ 5  2  2  5]]
Train  loss=1.0839 acc=0.5517 f1=0.5449 | Val loss=2.1833 acc=0.2906 f1=0.2844

Epoch 10/12


    t_loss=1.0428 | F1(macro)=0.5454 | Acc=0.5560


Confusion matrix:
 [[ 9 10 10 12]
 [ 7  7  7 11]
 [ 5  5 11  9]
 [ 2  3  2  7]]
Train  loss=1.0428 acc=0.5560 f1=0.5454 | Val loss=2.2272 acc=0.2906 f1=0.2894

Epoch 11/12


    t_loss=1.0066 | F1(macro)=0.5822 | Acc=0.5991


Confusion matrix:
 [[10 10 12  9]
 [ 6  7  9 10]
 [ 6  3 12  9]
 [ 3  3  4  4]]
Train  loss=1.0066 acc=0.5991 f1=0.5822 | Val loss=2.2092 acc=0.2821 f1=0.2724

Epoch 12/12


    t_loss=0.9792 | F1(macro)=0.5754 | Acc=0.5905


Confusion matrix:
 [[10 11 12  8]
 [ 8  9  6  9]
 [ 7  4 13  6]
 [ 6  3  2  3]]
Train  loss=0.9792 acc=0.5905 f1=0.5754 | Val loss=2.1681 acc=0.2991 f1=0.2864

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.2834 | F1(macro)=0.2367 | Acc=0.2387


Confusion matrix:
 [[11 13 12  4]
 [ 6 13 13  0]
 [ 6 12  9  3]
 [ 4  5  5  0]]
Train  loss=2.2834 acc=0.2387 f1=0.2367 | Val loss=2.3063 acc=0.2845 f1=0.2340
  🔥 New best F1: 0.2340 – model saved.

Epoch 2/8


    t_loss=2.1231 | F1(macro)=0.2408 | Acc=0.2409


Confusion matrix:
 [[19  8 10  3]
 [10 10  8  4]
 [11 10  6  3]
 [ 7  0  6  1]]
Train  loss=2.1231 acc=0.2409 f1=0.2408 | Val loss=2.0624 acc=0.3103 f1=0.2625
  🔥 New best F1: 0.2625 – model saved.

Epoch 3/8


    t_loss=1.9474 | F1(macro)=0.2670 | Acc=0.2688


Confusion matrix:
 [[13  5 14  8]
 [ 4  8 16  4]
 [ 5  5 17  3]
 [ 4  0  9  1]]
Train  loss=1.9474 acc=0.2688 f1=0.2670 | Val loss=2.1481 acc=0.3362 f1=0.2940
  🔥 New best F1: 0.2940 – model saved.

Epoch 4/8


    t_loss=1.9066 | F1(macro)=0.2584 | Acc=0.2581


Confusion matrix:
 [[17  3 12  8]
 [ 7  7 12  6]
 [ 7  5 14  4]
 [ 8  0  4  2]]
Train  loss=1.9066 acc=0.2581 f1=0.2584 | Val loss=2.0415 acc=0.3448 f1=0.3087
  🔥 New best F1: 0.3087 – model saved.

Epoch 5/8


    t_loss=1.7776 | F1(macro)=0.2886 | Acc=0.2925


Confusion matrix:
 [[15  7  9  9]
 [ 7 12  7  6]
 [ 8  9  8  5]
 [ 4  2  5  3]]
Train  loss=1.7776 acc=0.2925 f1=0.2886 | Val loss=2.0898 acc=0.3276 f1=0.3065

Epoch 6/8


    t_loss=1.8225 | F1(macro)=0.3051 | Acc=0.3054


Confusion matrix:
 [[11  9 11  9]
 [ 4 11 10  7]
 [ 4 10 13  3]
 [ 6  1  6  1]]
Train  loss=1.8225 acc=0.3054 f1=0.3051 | Val loss=2.0125 acc=0.3103 f1=0.2795

Epoch 7/8


    t_loss=1.7987 | F1(macro)=0.2666 | Acc=0.2710


Confusion matrix:
 [[19  4  8  9]
 [ 8 10  9  5]
 [ 9  7 10  4]
 [ 8  0  4  2]]
Train  loss=1.7987 acc=0.2710 f1=0.2666 | Val loss=1.9870 acc=0.3534 f1=0.3188
  🔥 New best F1: 0.3188 – model saved.

Epoch 8/8


    t_loss=1.7285 | F1(macro)=0.3196 | Acc=0.3226


Confusion matrix:
 [[16  4 10 10]
 [ 8 10  8  6]
 [ 8 11  7  4]
 [ 8  0  4  2]]
Train  loss=1.7285 acc=0.3226 f1=0.3196 | Val loss=2.0404 acc=0.3017 f1=0.2748
Restored best Stage 1 weights for fold 1 (F1=0.3188)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.6089 | F1(macro)=0.3622 | Acc=0.3720


Confusion matrix:
 [[14  2  5 19]
 [ 8  8  2 14]
 [12  5  6  7]
 [ 6  1  0  7]]
Train  loss=1.6089 acc=0.3720 f1=0.3622 | Val loss=2.2434 acc=0.3017 f1=0.2980
  🔥 New best F1: 0.2980 – model saved.

Epoch 2/12


    t_loss=1.4906 | F1(macro)=0.3853 | Acc=0.3978


Confusion matrix:
 [[13  3  9 15]
 [ 4 10  5 13]
 [ 7  8  8  7]
 [ 3  2  5  4]]
Train  loss=1.4906 acc=0.3978 f1=0.3853 | Val loss=2.1614 acc=0.3017 f1=0.2958

Epoch 3/12


    t_loss=1.3757 | F1(macro)=0.4183 | Acc=0.4366


Confusion matrix:
 [[16  1  7 16]
 [12  5  5 10]
 [10  3 10  7]
 [ 4  1  2  7]]
Train  loss=1.3757 acc=0.4366 f1=0.4183 | Val loss=2.1400 acc=0.3276 f1=0.3145
  🔥 New best F1: 0.3145 – model saved.

Epoch 4/12


    t_loss=1.2450 | F1(macro)=0.4710 | Acc=0.4839


Confusion matrix:
 [[19  9  7  5]
 [ 8 15  7  2]
 [ 7 11  9  3]
 [ 7  1  5  1]]
Train  loss=1.2450 acc=0.4839 f1=0.4710 | Val loss=1.8704 acc=0.3793 f1=0.3252
  🔥 New best F1: 0.3252 – model saved.

Epoch 5/12


    t_loss=1.2139 | F1(macro)=0.4734 | Acc=0.4925


Confusion matrix:
 [[15  1  6 18]
 [14  4  4 10]
 [12  5  7  6]
 [ 6  0  2  6]]
Train  loss=1.2139 acc=0.4925 f1=0.4734 | Val loss=1.9702 acc=0.2759 f1=0.2608

Epoch 6/12


    t_loss=1.0981 | F1(macro)=0.5011 | Acc=0.5290


Confusion matrix:
 [[ 8  2 19 11]
 [10  4 10  8]
 [ 7  1 18  4]
 [ 4  0  5  5]]
Train  loss=1.0981 acc=0.5290 f1=0.5011 | Val loss=2.0481 acc=0.3017 f1=0.2785

Epoch 7/12


    t_loss=1.0942 | F1(macro)=0.5099 | Acc=0.5312


Confusion matrix:
 [[16  3  9 12]
 [14  6  4  8]
 [10  5 10  5]
 [ 6  1  2  5]]
Train  loss=1.0942 acc=0.5312 f1=0.5099 | Val loss=1.9489 acc=0.3190 f1=0.3046

Epoch 8/12


    t_loss=1.0659 | F1(macro)=0.5708 | Acc=0.5806


Confusion matrix:
 [[11  6  8 15]
 [12  7  6  7]
 [ 8  8 10  4]
 [ 5  0  4  5]]
Train  loss=1.0659 acc=0.5806 f1=0.5708 | Val loss=1.9404 acc=0.2845 f1=0.2802

Epoch 9/12


    t_loss=1.0534 | F1(macro)=0.5565 | Acc=0.5677


Confusion matrix:
 [[13  6 11 10]
 [ 9  8  7  8]
 [ 9  3 13  5]
 [ 2  0  7  5]]
Train  loss=1.0534 acc=0.5677 f1=0.5565 | Val loss=1.8705 acc=0.3362 f1=0.3258
  🔥 New best F1: 0.3258 – model saved.

Epoch 10/12


    t_loss=1.0371 | F1(macro)=0.5443 | Acc=0.5591


Confusion matrix:
 [[10  5 10 15]
 [13  6  6  7]
 [ 7  8  9  6]
 [ 2  0  6  6]]
Train  loss=1.0371 acc=0.5591 f1=0.5443 | Val loss=1.9239 acc=0.2672 f1=0.2645

Epoch 11/12


    t_loss=1.0306 | F1(macro)=0.5722 | Acc=0.5849


Confusion matrix:
 [[10  6  6 18]
 [14  8  3  7]
 [ 9  6  8  7]
 [ 4  0  4  6]]
Train  loss=1.0306 acc=0.5849 f1=0.5722 | Val loss=1.9103 acc=0.2759 f1=0.2780

Epoch 12/12


    t_loss=0.9930 | F1(macro)=0.5551 | Acc=0.5742


Confusion matrix:
 [[10  4  9 17]
 [ 7  9  4 12]
 [ 5  9  9  7]
 [ 2  0  6  6]]
Train  loss=0.9930 acc=0.5742 f1=0.5551 | Val loss=1.9919 acc=0.2931 f1=0.2926

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.2979 | F1(macro)=0.2495 | Acc=0.2538


Confusion matrix:
 [[16  3 10 12]
 [ 7  1 14  9]
 [11  1 11  7]
 [ 2  1  6  5]]
Train  loss=2.2979 acc=0.2538 f1=0.2495 | Val loss=2.4625 acc=0.2845 f1=0.2481
  🔥 New best F1: 0.2481 – model saved.

Epoch 2/8


    t_loss=2.0510 | F1(macro)=0.2820 | Acc=0.2839


Confusion matrix:
 [[14  2 12 13]
 [10  0  8 13]
 [10  1 11  8]
 [ 2  0  8  4]]
Train  loss=2.0510 acc=0.2839 f1=0.2820 | Val loss=2.4568 acc=0.2500 f1=0.2091

Epoch 3/8


    t_loss=1.9478 | F1(macro)=0.2975 | Acc=0.2989


Confusion matrix:
 [[20  3 10  8]
 [13  0 10  8]
 [15  1 10  4]
 [ 5  0  5  4]]
Train  loss=1.9478 acc=0.2989 f1=0.2975 | Val loss=2.2254 acc=0.2931 f1=0.2359

Epoch 4/8


    t_loss=1.7624 | F1(macro)=0.3002 | Acc=0.3075


Confusion matrix:
 [[16  6  8 11]
 [12  0  7 12]
 [12  2 10  6]
 [ 4  0  5  5]]
Train  loss=1.7624 acc=0.3075 f1=0.3002 | Val loss=2.2867 acc=0.2672 f1=0.2295

Epoch 5/8


    t_loss=1.6918 | F1(macro)=0.3390 | Acc=0.3398


Confusion matrix:
 [[18  7  7  9]
 [10  4  7 10]
 [10  3 11  6]
 [ 3  3  7  1]]
Train  loss=1.6918 acc=0.3398 f1=0.3390 | Val loss=2.1898 acc=0.2931 f1=0.2526
  🔥 New best F1: 0.2526 – model saved.

Epoch 6/8


    t_loss=1.7309 | F1(macro)=0.3249 | Acc=0.3333


Confusion matrix:
 [[15  6 11  9]
 [12  5  5  9]
 [12  4  9  5]
 [ 3  2  7  2]]
Train  loss=1.7309 acc=0.3333 f1=0.3249 | Val loss=2.1173 acc=0.2672 f1=0.2407

Epoch 7/8


    t_loss=1.7941 | F1(macro)=0.3005 | Acc=0.3032


Confusion matrix:
 [[13  5 13 10]
 [13  1  8  9]
 [12  3 11  4]
 [ 6  1  5  2]]
Train  loss=1.7941 acc=0.3032 f1=0.3005 | Val loss=2.2198 acc=0.2328 f1=0.1964

Epoch 8/8


    t_loss=1.7634 | F1(macro)=0.2926 | Acc=0.2925


Confusion matrix:
 [[16  8  8  9]
 [12  2 11  6]
 [ 8  3 14  5]
 [ 4  3  6  1]]
Train  loss=1.7634 acc=0.2925 f1=0.2926 | Val loss=2.2081 acc=0.2845 f1=0.2358
Restored best Stage 1 weights for fold 2 (F1=0.2526)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.7005 | F1(macro)=0.3024 | Acc=0.3161


Confusion matrix:
 [[14 10  3 14]
 [ 8  9  2 12]
 [10  7  6  7]
 [ 1  3  5  5]]
Train  loss=1.7005 acc=0.3161 f1=0.3024 | Val loss=2.0908 acc=0.2931 f1=0.2829
  🔥 New best F1: 0.2829 – model saved.

Epoch 2/12


    t_loss=1.4812 | F1(macro)=0.3534 | Acc=0.3849


Confusion matrix:
 [[14  6  1 20]
 [11  4  3 13]
 [13  0  3 14]
 [ 4  1  2  7]]
Train  loss=1.4812 acc=0.3849 f1=0.3534 | Val loss=2.1575 acc=0.2414 f1=0.2219

Epoch 3/12


    t_loss=1.2262 | F1(macro)=0.4663 | Acc=0.4817


Confusion matrix:
 [[16  6  5 14]
 [ 8  6  5 12]
 [11  6  8  5]
 [ 4  0  4  6]]
Train  loss=1.2262 acc=0.4817 f1=0.4663 | Val loss=2.0165 acc=0.3103 f1=0.2970
  🔥 New best F1: 0.2970 – model saved.

Epoch 4/12


    t_loss=1.2734 | F1(macro)=0.4531 | Acc=0.4710


Confusion matrix:
 [[22  6  2 11]
 [18  3  4  6]
 [17  4  5  4]
 [ 7  0  3  4]]
Train  loss=1.2734 acc=0.4710 f1=0.4531 | Val loss=2.1762 acc=0.2931 f1=0.2470

Epoch 5/12


    t_loss=1.2175 | F1(macro)=0.4759 | Acc=0.4903


Confusion matrix:
 [[16  7  5 13]
 [12  6  6  7]
 [10  3 11  6]
 [ 5  1  3  5]]
Train  loss=1.2175 acc=0.4903 f1=0.4759 | Val loss=2.0719 acc=0.3276 f1=0.3133
  🔥 New best F1: 0.3133 – model saved.

Epoch 6/12


    t_loss=1.1232 | F1(macro)=0.5208 | Acc=0.5312


Confusion matrix:
 [[12  6  7 16]
 [12  6  6  7]
 [10  3  9  8]
 [ 4  2  4  4]]
Train  loss=1.1232 acc=0.5312 f1=0.5208 | Val loss=2.0203 acc=0.2672 f1=0.2596

Epoch 7/12


    t_loss=1.0847 | F1(macro)=0.5154 | Acc=0.5290


Confusion matrix:
 [[18  7  4 12]
 [16  7  1  7]
 [13  7  6  4]
 [ 6  0  4  4]]
Train  loss=1.0847 acc=0.5290 f1=0.5154 | Val loss=1.9608 acc=0.3017 f1=0.2785

Epoch 8/12


    t_loss=1.1449 | F1(macro)=0.5212 | Acc=0.5312


Confusion matrix:
 [[17  9  4 11]
 [12 10  3  6]
 [10  6  9  5]
 [ 5  1  4  4]]
Train  loss=1.1449 acc=0.5312 f1=0.5212 | Val loss=1.9782 acc=0.3448 f1=0.3277
  🔥 New best F1: 0.3277 – model saved.

Epoch 9/12


    t_loss=1.0069 | F1(macro)=0.5550 | Acc=0.5656


Confusion matrix:
 [[19  5  5 12]
 [13  6  3  9]
 [10  4  9  7]
 [ 5  1  4  4]]
Train  loss=1.0069 acc=0.5656 f1=0.5550 | Val loss=2.0010 acc=0.3276 f1=0.3035

Epoch 10/12


    t_loss=0.9264 | F1(macro)=0.6256 | Acc=0.6366


Confusion matrix:
 [[17  7  6 11]
 [14  5  6  6]
 [13  5  9  3]
 [ 4  1  5  4]]
Train  loss=0.9264 acc=0.6366 f1=0.6256 | Val loss=1.9832 acc=0.3017 f1=0.2795

Epoch 11/12


    t_loss=0.9889 | F1(macro)=0.5253 | Acc=0.5527


Confusion matrix:
 [[19  7  6  9]
 [15  5  4  7]
 [12  4  7  7]
 [ 6  1  3  4]]
Train  loss=0.9889 acc=0.5527 f1=0.5253 | Val loss=1.9753 acc=0.3017 f1=0.2730

Epoch 12/12


    t_loss=0.9806 | F1(macro)=0.5773 | Acc=0.5892


Confusion matrix:
 [[18  5  5 13]
 [12  5  6  8]
 [14  4  7  5]
 [ 5  1  4  4]]
Train  loss=0.9806 acc=0.5892 f1=0.5773 | Val loss=1.9493 acc=0.2931 f1=0.2671

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.1020 | F1(macro)=0.2390 | Acc=0.2409


Confusion matrix:
 [[ 7  7 19  8]
 [ 2  7 17  5]
 [ 8  6 11  5]
 [ 4  1  4  5]]
Train  loss=2.1020 acc=0.2409 f1=0.2390 | Val loss=2.2945 acc=0.2586 f1=0.2592
  🔥 New best F1: 0.2592 – model saved.

Epoch 2/8


    t_loss=2.0213 | F1(macro)=0.2814 | Acc=0.2817


Confusion matrix:
 [[ 6  6 22  7]
 [ 1  6 18  6]
 [ 4  5 17  4]
 [ 4  1  5  4]]
Train  loss=2.0213 acc=0.2817 f1=0.2814 | Val loss=2.4726 acc=0.2845 f1=0.2643
  🔥 New best F1: 0.2643 – model saved.

Epoch 3/8


    t_loss=1.8110 | F1(macro)=0.3246 | Acc=0.3247


Confusion matrix:
 [[ 5  4 24  8]
 [ 2  3 20  6]
 [ 3  2 19  6]
 [ 1  1  4  8]]
Train  loss=1.8110 acc=0.3247 f1=0.3246 | Val loss=2.5724 acc=0.3017 f1=0.2778
  🔥 New best F1: 0.2778 – model saved.

Epoch 4/8


    t_loss=1.7679 | F1(macro)=0.2929 | Acc=0.2989


Confusion matrix:
 [[ 7  9 16  9]
 [ 3  7 15  6]
 [ 4  5 11 10]
 [ 3  1  3  7]]
Train  loss=1.7679 acc=0.2989 f1=0.2929 | Val loss=2.2425 acc=0.2759 f1=0.2758

Epoch 5/8


    t_loss=1.7492 | F1(macro)=0.3143 | Acc=0.3183


Confusion matrix:
 [[ 4 10 22  5]
 [ 2  6 19  4]
 [ 2  4 17  7]
 [ 4  2  3  5]]
Train  loss=1.7492 acc=0.3183 f1=0.3143 | Val loss=2.3347 acc=0.2759 f1=0.2592

Epoch 6/8


    t_loss=1.6487 | F1(macro)=0.3400 | Acc=0.3419


Confusion matrix:
 [[ 6  8 19  8]
 [ 1  6 18  6]
 [ 2  4 17  7]
 [ 3  1  5  5]]
Train  loss=1.6487 acc=0.3419 f1=0.3400 | Val loss=2.2095 acc=0.2931 f1=0.2746

Epoch 7/8


    t_loss=1.7510 | F1(macro)=0.3097 | Acc=0.3183


Confusion matrix:
 [[10  8 15  8]
 [ 2  9 13  7]
 [ 5  5 12  8]
 [ 4  2  4  4]]
Train  loss=1.7510 acc=0.3183 f1=0.3097 | Val loss=2.1526 acc=0.3017 f1=0.2923
  🔥 New best F1: 0.2923 – model saved.

Epoch 8/8


    t_loss=1.5973 | F1(macro)=0.3435 | Acc=0.3462


Confusion matrix:
 [[ 9 10 16  6]
 [ 5  9 14  3]
 [ 6  6  9  9]
 [ 5  1  2  6]]
Train  loss=1.5973 acc=0.3462 f1=0.3435 | Val loss=2.0835 acc=0.2845 f1=0.2895
Restored best Stage 1 weights for fold 3 (F1=0.2923)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.6279 | F1(macro)=0.3520 | Acc=0.3656


Confusion matrix:
 [[ 4 10 16 11]
 [ 6  7 13  5]
 [ 7  3 13  7]
 [ 1  4  5  4]]
Train  loss=1.6279 acc=0.3656 f1=0.3520 | Val loss=2.3297 acc=0.2414 f1=0.2307
  🔥 New best F1: 0.2307 – model saved.

Epoch 2/12


    t_loss=1.4801 | F1(macro)=0.4055 | Acc=0.4086


Confusion matrix:
 [[ 5 11 12 13]
 [ 4  4 15  8]
 [ 3  6 11 10]
 [ 1  1  3  9]]
Train  loss=1.4801 acc=0.4086 f1=0.4055 | Val loss=2.1086 acc=0.2500 f1=0.2448
  🔥 New best F1: 0.2448 – model saved.

Epoch 3/12


    t_loss=1.3988 | F1(macro)=0.4270 | Acc=0.4366


Confusion matrix:
 [[ 8 13  9 11]
 [ 7  8 10  6]
 [ 5  9  8  8]
 [ 3  3  1  7]]
Train  loss=1.3988 acc=0.4366 f1=0.4270 | Val loss=2.1138 acc=0.2672 f1=0.2701
  🔥 New best F1: 0.2701 – model saved.

Epoch 4/12


    t_loss=1.2553 | F1(macro)=0.4858 | Acc=0.5140


Confusion matrix:
 [[ 5 11 12 13]
 [ 6 10  9  6]
 [ 4  7  8 11]
 [ 2  1  1 10]]
Train  loss=1.2553 acc=0.5140 f1=0.4858 | Val loss=2.0682 acc=0.2845 f1=0.2857
  🔥 New best F1: 0.2857 – model saved.

Epoch 5/12


    t_loss=1.2936 | F1(macro)=0.4255 | Acc=0.4387


Confusion matrix:
 [[ 9 10 12 10]
 [ 9  7  5 10]
 [ 6  7  5 12]
 [ 3  3  2  6]]
Train  loss=1.2936 acc=0.4387 f1=0.4255 | Val loss=1.9840 acc=0.2328 f1=0.2305

Epoch 6/12


    t_loss=1.1111 | F1(macro)=0.5458 | Acc=0.5527


Confusion matrix:
 [[13 12  5 11]
 [ 9 12  4  6]
 [ 6  7  3 14]
 [ 3  4  0  7]]
Train  loss=1.1111 acc=0.5527 f1=0.5458 | Val loss=1.9750 acc=0.3017 f1=0.2842

Epoch 7/12


    t_loss=1.0864 | F1(macro)=0.5576 | Acc=0.5699


Confusion matrix:
 [[12 12  7 10]
 [ 8 11  6  6]
 [10  6  4 10]
 [ 3  5  1  5]]
Train  loss=1.0864 acc=0.5699 f1=0.5576 | Val loss=1.9635 acc=0.2759 f1=0.2629

Epoch 8/12


    t_loss=1.1497 | F1(macro)=0.4930 | Acc=0.5054


Confusion matrix:
 [[15 10  7  9]
 [ 9 11  4  7]
 [10  8  3  9]
 [ 4  2  0  8]]
Train  loss=1.1497 acc=0.5054 f1=0.4930 | Val loss=1.9977 acc=0.3190 f1=0.3028
  🔥 New best F1: 0.3028 – model saved.

Epoch 9/12


    t_loss=0.9949 | F1(macro)=0.5691 | Acc=0.5957


Confusion matrix:
 [[10 12 10  9]
 [ 8 11  6  6]
 [ 8 10  5  7]
 [ 4  4  1  5]]
Train  loss=0.9949 acc=0.5957 f1=0.5691 | Val loss=1.9504 acc=0.2672 f1=0.2604

Epoch 10/12


    t_loss=1.0163 | F1(macro)=0.5817 | Acc=0.5914


Confusion matrix:
 [[13  9  8 11]
 [ 9 10  7  5]
 [ 9  5  8  8]
 [ 4  2  3  5]]
Train  loss=1.0163 acc=0.5914 f1=0.5817 | Val loss=1.9373 acc=0.3103 f1=0.3028

Epoch 11/12


    t_loss=1.0343 | F1(macro)=0.5755 | Acc=0.5828


Confusion matrix:
 [[ 5 15 13  8]
 [ 7 11  5  8]
 [ 6  8  5 11]
 [ 1  5  1  7]]
Train  loss=1.0343 acc=0.5828 f1=0.5755 | Val loss=2.0192 acc=0.2414 f1=0.2395

Epoch 12/12


    t_loss=0.9956 | F1(macro)=0.5935 | Acc=0.6022


Confusion matrix:
 [[ 8 16  7 10]
 [ 7 13  7  4]
 [ 5  9  6 10]
 [ 2  5  1  6]]
Train  loss=0.9956 acc=0.6022 f1=0.5935 | Val loss=2.0156 acc=0.2845 f1=0.2783

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.2067 | F1(macro)=0.2516 | Acc=0.2516


Confusion matrix:
 [[ 7  7 17 10]
 [ 3  9 17  3]
 [ 6  6 15  3]
 [ 2  0  5  6]]
Train  loss=2.2067 acc=0.2516 f1=0.2516 | Val loss=2.1485 acc=0.3190 f1=0.3177
  🔥 New best F1: 0.3177 – model saved.

Epoch 2/8


    t_loss=1.9194 | F1(macro)=0.2821 | Acc=0.2817


Confusion matrix:
 [[ 9 11  5 16]
 [ 4 10  9  9]
 [ 4  8  9  9]
 [ 2  1  2  8]]
Train  loss=1.9194 acc=0.2817 f1=0.2821 | Val loss=2.2554 acc=0.3103 f1=0.3102

Epoch 3/8


    t_loss=1.9039 | F1(macro)=0.3112 | Acc=0.3118


Confusion matrix:
 [[10 16  8  7]
 [ 7 15  6  4]
 [ 5 10  8  7]
 [ 2  3  3  5]]
Train  loss=1.9039 acc=0.3118 f1=0.3112 | Val loss=1.9898 acc=0.3276 f1=0.3178
  🔥 New best F1: 0.3178 – model saved.

Epoch 4/8


    t_loss=1.8374 | F1(macro)=0.2645 | Acc=0.2667


Confusion matrix:
 [[12 13  6 10]
 [ 6 13  8  5]
 [ 8  8  6  8]
 [ 4  3  3  3]]
Train  loss=1.8374 acc=0.2667 f1=0.2645 | Val loss=2.0385 acc=0.2931 f1=0.2738

Epoch 5/8


    t_loss=1.8495 | F1(macro)=0.2770 | Acc=0.2796


Confusion matrix:
 [[ 8 10 12 11]
 [ 4 12  8  8]
 [ 5  7  9  9]
 [ 1  2  3  7]]
Train  loss=1.8495 acc=0.2796 f1=0.2770 | Val loss=1.9756 acc=0.3103 f1=0.3085

Epoch 6/8


    t_loss=1.7191 | F1(macro)=0.3123 | Acc=0.3183


Confusion matrix:
 [[10 11 16  4]
 [ 4 14  9  5]
 [ 6  7 13  4]
 [ 2  3  4  4]]
Train  loss=1.7191 acc=0.3183 f1=0.3123 | Val loss=1.9288 acc=0.3534 f1=0.3408
  🔥 New best F1: 0.3408 – model saved.

Epoch 7/8


    t_loss=1.8326 | F1(macro)=0.2919 | Acc=0.3011


Confusion matrix:
 [[ 5 12 17  7]
 [ 2 13 14  3]
 [ 5  8 15  2]
 [ 2  1  6  4]]
Train  loss=1.8326 acc=0.3011 f1=0.2919 | Val loss=1.9896 acc=0.3190 f1=0.3044

Epoch 8/8


    t_loss=1.6698 | F1(macro)=0.3044 | Acc=0.3097


Confusion matrix:
 [[ 5 12 16  8]
 [ 3 13 11  5]
 [ 4  6 13  7]
 [ 3  1  6  3]]
Train  loss=1.6698 acc=0.3097 f1=0.3044 | Val loss=1.9873 acc=0.2931 f1=0.2734
Restored best Stage 1 weights for fold 4 (F1=0.3408)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.7629 | F1(macro)=0.3255 | Acc=0.3290


Confusion matrix:
 [[14 10  8  9]
 [ 4 12  8  8]
 [ 6  7  7 10]
 [ 1  0  5  7]]
Train  loss=1.7629 acc=0.3290 f1=0.3255 | Val loss=1.9903 acc=0.3448 f1=0.3392
  🔥 New best F1: 0.3392 – model saved.

Epoch 2/12


    t_loss=1.4853 | F1(macro)=0.4037 | Acc=0.4086


Confusion matrix:
 [[13  6 11 11]
 [ 9  8  4 11]
 [ 5  5  8 12]
 [ 3  0  5  5]]
Train  loss=1.4853 acc=0.4086 f1=0.4037 | Val loss=2.1736 acc=0.2931 f1=0.2870

Epoch 3/12


    t_loss=1.3723 | F1(macro)=0.3835 | Acc=0.4065


Confusion matrix:
 [[19  6 11  5]
 [ 5 14  6  7]
 [11  9  7  3]
 [ 6  0  1  6]]
Train  loss=1.3723 acc=0.4065 f1=0.3835 | Val loss=1.8830 acc=0.3966 f1=0.3825
  🔥 New best F1: 0.3825 – model saved.

Epoch 4/12


    t_loss=1.3745 | F1(macro)=0.4024 | Acc=0.4129


Confusion matrix:
 [[ 8 12 10 11]
 [ 4 14  5  9]
 [ 8 10  9  3]
 [ 4  2  4  3]]
Train  loss=1.3745 acc=0.4129 f1=0.4024 | Val loss=1.9997 acc=0.2931 f1=0.2776

Epoch 5/12


    t_loss=1.1295 | F1(macro)=0.4644 | Acc=0.4903


Confusion matrix:
 [[19  6  9  7]
 [11 13  3  5]
 [15  7  5  3]
 [ 7  0  3  3]]
Train  loss=1.1295 acc=0.4903 f1=0.4644 | Val loss=1.9597 acc=0.3448 f1=0.3126

Epoch 6/12


    t_loss=1.1537 | F1(macro)=0.5192 | Acc=0.5312


Confusion matrix:
 [[ 8 12 13  8]
 [ 4 15  7  6]
 [ 3 11 10  6]
 [ 4  1  5  3]]
Train  loss=1.1537 acc=0.5312 f1=0.5192 | Val loss=1.9287 acc=0.3103 f1=0.2909

Epoch 7/12


    t_loss=1.1161 | F1(macro)=0.5284 | Acc=0.5548


Confusion matrix:
 [[ 6 11 12 12]
 [ 4 13  6  9]
 [ 3  8 12  7]
 [ 2  1  4  6]]
Train  loss=1.1161 acc=0.5548 f1=0.5284 | Val loss=1.8460 acc=0.3190 f1=0.3112

Epoch 8/12


    t_loss=1.1586 | F1(macro)=0.5272 | Acc=0.5376


Confusion matrix:
 [[11 10 13  7]
 [ 5 13  7  7]
 [ 3  9 11  7]
 [ 3  2  4  4]]
Train  loss=1.1586 acc=0.5376 f1=0.5272 | Val loss=1.8496 acc=0.3362 f1=0.3230

Epoch 9/12


    t_loss=1.0492 | F1(macro)=0.5254 | Acc=0.5441


Confusion matrix:
 [[ 9 14 10  8]
 [ 4 14  7  7]
 [ 4 11  9  6]
 [ 4  1  4  4]]
Train  loss=1.0492 acc=0.5441 f1=0.5254 | Val loss=1.8329 acc=0.3103 f1=0.2974

Epoch 10/12


    t_loss=1.0534 | F1(macro)=0.5925 | Acc=0.5978


Confusion matrix:
 [[ 7 13 14  7]
 [ 4 16  7  5]
 [ 3 12 12  3]
 [ 3  2  5  3]]
Train  loss=1.0534 acc=0.5978 f1=0.5925 | Val loss=1.9351 acc=0.3276 f1=0.3036

Epoch 11/12


    t_loss=1.0042 | F1(macro)=0.6122 | Acc=0.6172


Confusion matrix:
 [[ 8 12 14  7]
 [ 4 14  5  9]
 [ 5  9  8  8]
 [ 5  0  3  5]]
Train  loss=1.0042 acc=0.6172 f1=0.6122 | Val loss=1.8344 acc=0.3017 f1=0.2942

Epoch 12/12


    t_loss=1.0462 | F1(macro)=0.5695 | Acc=0.5785


Confusion matrix:
 [[ 8 10 15  8]
 [ 4 13  8  7]
 [ 4  7 13  6]
 [ 5  1  4  3]]
Train  loss=1.0462 acc=0.5785 f1=0.5695 | Val loss=1.8467 acc=0.3190 f1=0.3011


# tf_efficientnetv2_s.in21k

In [5]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [6]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

In [7]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0"

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png        Luminal A
1  img_0001.png        Luminal A
2  img_0002.png        Luminal B
3  img_0003.png  Triple negative
4  img_0004.png        Luminal A


In [8]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
                         shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            img_tensor = img_tensor.squeeze(0)  # [3,H,W]
            img_tensor = img_tensor.to(device)

            # -------- TTA: apply multiple augmented views --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1,4]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N, 4]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
pred_indices = mean_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print("Saved submission_5fold_tta.csv")

Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_tta.csv


In [9]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.30806917211328977
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.30838264605343324
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.2872897487117133
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.2663476308637599
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.2331782846947878
Mean OOF F1: 0.28065349648739685
