In [1]:
import enum
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from timm.layers import Conv2dSame
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.persistence_manager import PersistenceManager
from internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B0

In [4]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_efficientnet_b0_model()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # --- 1.1. unfreeze last blocks only ---
        for param in model.blocks[-1].parameters():
            param.requires_grad = True
        for param in model.blocks[-2].parameters():
            param.requires_grad = True

        # --- 1.1. unfreeze classifier head ---
        clf_module, _ = get_classifier_module(model)
        for param in clf_module.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_{PREFIX}_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_{PREFIX}_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"{PREFIX}_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.7503 | F1(macro)=0.2587 | Acc=0.2586


Confusion matrix:
 [[ 5  2 34  0]
 [ 5 10 16  1]
 [ 3  0 25  2]
 [ 4  3  7  0]]
Train  loss=2.7503 acc=0.2586 f1=0.2587 | Val loss=2.0841 acc=0.3419 f1=0.2611
  🔥 New best F1: 0.2611 – model saved.

Epoch 2/8


    t_loss=2.0965 | F1(macro)=0.2589 | Acc=0.2672


Confusion matrix:
 [[22  0  7 12]
 [15  1  2 14]
 [17  1  4  8]
 [10  0  1  3]]
Train  loss=2.0965 acc=0.2672 f1=0.2589 | Val loss=2.0332 acc=0.2564 f1=0.1943

Epoch 3/8


    t_loss=1.7282 | F1(macro)=0.3441 | Acc=0.3427


Confusion matrix:
 [[ 2 29  4  6]
 [ 3 21  1  7]
 [ 0 10 10 10]
 [ 1  4  2  7]]
Train  loss=1.7282 acc=0.3427 f1=0.3441 | Val loss=1.8613 acc=0.3419 f1=0.3166
  🔥 New best F1: 0.3166 – model saved.

Epoch 4/8


    t_loss=1.6140 | F1(macro)=0.3595 | Acc=0.3578


Confusion matrix:
 [[ 0  3 10 28]
 [ 1  4  5 22]
 [ 0  1  7 22]
 [ 1  0  3 10]]
Train  loss=1.6140 acc=0.3578 f1=0.3595 | Val loss=2.5965 acc=0.1795 f1=0.1657

Epoch 5/8


    t_loss=1.5557 | F1(macro)=0.3452 | Acc=0.3470


Confusion matrix:
 [[ 1 11 16 13]
 [ 2 14  7  9]
 [ 0  3 15 12]
 [ 2  1  4  7]]
Train  loss=1.5557 acc=0.3470 f1=0.3452 | Val loss=1.9833 acc=0.3162 f1=0.2934

Epoch 6/8


    t_loss=1.4926 | F1(macro)=0.3362 | Acc=0.3362


Confusion matrix:
 [[ 1 10 22  8]
 [ 4 14  7  7]
 [ 1  1 20  8]
 [ 1  4  5  4]]
Train  loss=1.4926 acc=0.3362 f1=0.3362 | Val loss=1.7919 acc=0.3333 f1=0.2930

Epoch 7/8


    t_loss=1.3801 | F1(macro)=0.3683 | Acc=0.3728


Confusion matrix:
 [[ 2  4 29  6]
 [ 4  8 12  8]
 [ 1  1 23  5]
 [ 2  3  4  5]]
Train  loss=1.3801 acc=0.3728 f1=0.3683 | Val loss=1.7775 acc=0.3248 f1=0.2865

Epoch 8/8


    t_loss=1.3373 | F1(macro)=0.4106 | Acc=0.4095


Confusion matrix:
 [[ 1 11 22  7]
 [ 5 14  8  5]
 [ 0  1 24  5]
 [ 1  3  6  4]]
Train  loss=1.3373 acc=0.4095 f1=0.4106 | Val loss=1.8343 acc=0.3675 f1=0.3156
Restored best Stage 1 weights for fold 0 (F1=0.3166)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.3607 | F1(macro)=0.3594 | Acc=0.3750


Confusion matrix:
 [[ 3  4 24 10]
 [ 6  5 12  9]
 [ 2  1 20  7]
 [ 3  2  3  6]]
Train  loss=1.3607 acc=0.3750 f1=0.3594 | Val loss=1.8339 acc=0.2906 f1=0.2617
  🔥 New best F1: 0.2617 – model saved.

Epoch 2/12


    t_loss=1.3138 | F1(macro)=0.4012 | Acc=0.4159


Confusion matrix:
 [[ 4  8  3 26]
 [ 4  6  4 18]
 [ 2  0  2 26]
 [ 2  3  0  9]]
Train  loss=1.3138 acc=0.4159 f1=0.4012 | Val loss=1.9549 acc=0.1795 f1=0.1730

Epoch 3/12


    t_loss=1.2587 | F1(macro)=0.3999 | Acc=0.4375


Confusion matrix:
 [[ 0 11  8 22]
 [ 1 10  7 14]
 [ 0  2  6 22]
 [ 0  3  2  9]]
Train  loss=1.2587 acc=0.4375 f1=0.3999 | Val loss=2.1196 acc=0.2137 f1=0.1984

Epoch 4/12


    t_loss=1.3345 | F1(macro)=0.3926 | Acc=0.4052


Confusion matrix:
 [[ 1 18  9 13]
 [ 6 14  4  8]
 [ 0  6 11 13]
 [ 2  2  3  7]]
Train  loss=1.3345 acc=0.4052 f1=0.3926 | Val loss=1.8322 acc=0.2821 f1=0.2673
  🔥 New best F1: 0.2673 – model saved.

Epoch 5/12


    t_loss=1.3587 | F1(macro)=0.3696 | Acc=0.3793


Confusion matrix:
 [[ 4 18  7 12]
 [ 7 14  6  5]
 [ 2  8 10 10]
 [ 2  2  2  8]]
Train  loss=1.3587 acc=0.3793 f1=0.3696 | Val loss=1.7889 acc=0.3077 f1=0.3029
  🔥 New best F1: 0.3029 – model saved.

Epoch 6/12


    t_loss=1.2428 | F1(macro)=0.4209 | Acc=0.4418


Confusion matrix:
 [[ 3 20 15  3]
 [ 7 13 10  2]
 [ 2  3 21  4]
 [ 2  5  5  2]]
Train  loss=1.2428 acc=0.4418 f1=0.4209 | Val loss=1.7150 acc=0.3333 f1=0.2859

Epoch 7/12


    t_loss=1.3286 | F1(macro)=0.3897 | Acc=0.4095


Confusion matrix:
 [[ 2 12 23  4]
 [ 8  9 11  4]
 [ 0  1 22  7]
 [ 2  3  4  5]]
Train  loss=1.3286 acc=0.4095 f1=0.3897 | Val loss=1.6586 acc=0.3248 f1=0.2936

Epoch 8/12


    t_loss=1.2549 | F1(macro)=0.4258 | Acc=0.4332


Confusion matrix:
 [[ 1 20 13  7]
 [ 5 15  8  4]
 [ 0  7 15  8]
 [ 1  4  4  5]]
Train  loss=1.2549 acc=0.4332 f1=0.4258 | Val loss=1.7726 acc=0.3077 f1=0.2795

Epoch 9/12


    t_loss=1.0945 | F1(macro)=0.4420 | Acc=0.4784


Confusion matrix:
 [[ 1 19 13  8]
 [ 5 16  7  4]
 [ 0  8 13  9]
 [ 2  4  4  4]]
Train  loss=1.0945 acc=0.4784 f1=0.4420 | Val loss=1.7074 acc=0.2906 f1=0.2598

Epoch 10/12


    t_loss=1.1267 | F1(macro)=0.4255 | Acc=0.4677


Confusion matrix:
 [[ 2 15 15  9]
 [ 6 12  6  8]
 [ 0  3 16 11]
 [ 2  2  4  6]]
Train  loss=1.1267 acc=0.4677 f1=0.4255 | Val loss=1.7732 acc=0.3077 f1=0.2885

Epoch 11/12


    t_loss=1.2307 | F1(macro)=0.3958 | Acc=0.4246


Confusion matrix:
 [[ 2 14 18  7]
 [ 5 14  9  4]
 [ 0  3 19  8]
 [ 2  3  4  5]]
Train  loss=1.2307 acc=0.4246 f1=0.3958 | Val loss=1.7188 acc=0.3419 f1=0.3106
  🔥 New best F1: 0.3106 – model saved.

Epoch 12/12


    t_loss=1.2677 | F1(macro)=0.3913 | Acc=0.4073


Confusion matrix:
 [[ 3 15 18  5]
 [ 6 13 10  3]
 [ 0  6 16  8]
 [ 2  4  4  4]]
Train  loss=1.2677 acc=0.4073 f1=0.3913 | Val loss=1.7433 acc=0.3077 f1=0.2831

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.8806 | F1(macro)=0.2764 | Acc=0.2796


Confusion matrix:
 [[ 5 11 23  1]
 [ 7  9 12  4]
 [ 6  8 16  0]
 [ 0  2 12  0]]
Train  loss=2.8806 acc=0.2796 f1=0.2764 | Val loss=2.3214 acc=0.2586 f1=0.2017
  🔥 New best F1: 0.2017 – model saved.

Epoch 2/8


    t_loss=2.1561 | F1(macro)=0.2844 | Acc=0.2860


Confusion matrix:
 [[ 4 10  0 26]
 [ 2 10  2 18]
 [ 3  7  3 17]
 [ 2  4  1  7]]
Train  loss=2.1561 acc=0.2860 f1=0.2844 | Val loss=1.9379 acc=0.2069 f1=0.2029
  🔥 New best F1: 0.2029 – model saved.

Epoch 3/8


    t_loss=1.7641 | F1(macro)=0.2955 | Acc=0.2968


Confusion matrix:
 [[ 5  9  0 26]
 [ 3 10  1 18]
 [ 3 11  0 16]
 [ 1  2  0 11]]
Train  loss=1.7641 acc=0.2968 f1=0.2955 | Val loss=1.8894 acc=0.2241 f1=0.1909

Epoch 4/8


    t_loss=1.6116 | F1(macro)=0.3416 | Acc=0.3419


Confusion matrix:
 [[ 0 10 19 11]
 [ 4 12  8  8]
 [ 4  8 14  4]
 [ 0  3  6  5]]
Train  loss=1.6116 acc=0.3419 f1=0.3416 | Val loss=1.8032 acc=0.2672 f1=0.2427
  🔥 New best F1: 0.2427 – model saved.

Epoch 5/8


    t_loss=1.4837 | F1(macro)=0.3798 | Acc=0.3871


Confusion matrix:
 [[ 0  9 26  5]
 [ 1 17 11  3]
 [ 1  9 19  1]
 [ 0  3  9  2]]
Train  loss=1.4837 acc=0.3871 f1=0.3798 | Val loss=2.0187 acc=0.3276 f1=0.2614
  🔥 New best F1: 0.2614 – model saved.

Epoch 6/8


    t_loss=1.5289 | F1(macro)=0.3700 | Acc=0.3699


Confusion matrix:
 [[ 1 12 21  6]
 [ 2 17  7  6]
 [ 2 10 14  4]
 [ 0  4  5  5]]
Train  loss=1.5289 acc=0.3699 f1=0.3700 | Val loss=1.7722 acc=0.3190 f1=0.2868
  🔥 New best F1: 0.2868 – model saved.

Epoch 7/8


    t_loss=1.4097 | F1(macro)=0.3918 | Acc=0.3914


Confusion matrix:
 [[ 2  6 23  9]
 [ 5  9 10  8]
 [ 4  8 15  3]
 [ 2  1  8  3]]
Train  loss=1.4097 acc=0.3914 f1=0.3918 | Val loss=1.9162 acc=0.2500 f1=0.2270

Epoch 8/8


    t_loss=1.4244 | F1(macro)=0.3771 | Acc=0.3763


Confusion matrix:
 [[ 2  7 20 11]
 [ 6 11  8  7]
 [ 6  6 15  3]
 [ 3  1  6  4]]
Train  loss=1.4244 acc=0.3763 f1=0.3771 | Val loss=1.8058 acc=0.2759 f1=0.2603
Restored best Stage 1 weights for fold 1 (F1=0.2868)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.3763 | F1(macro)=0.3562 | Acc=0.3656


Confusion matrix:
 [[ 0  6 19 15]
 [ 2  8  6 16]
 [ 3  5 14  8]
 [ 1  2  6  5]]
Train  loss=1.3763 acc=0.3656 f1=0.3562 | Val loss=2.0304 acc=0.2328 f1=0.2119
  🔥 New best F1: 0.2119 – model saved.

Epoch 2/12


    t_loss=1.3696 | F1(macro)=0.3477 | Acc=0.3785


Confusion matrix:
 [[ 3  5 23  9]
 [ 4  4 18  6]
 [ 5  2 21  2]
 [ 0  1 10  3]]
Train  loss=1.3696 acc=0.3785 f1=0.3477 | Val loss=2.0684 acc=0.2672 f1=0.2214
  🔥 New best F1: 0.2214 – model saved.

Epoch 3/12


    t_loss=1.2555 | F1(macro)=0.3944 | Acc=0.4258


Confusion matrix:
 [[ 0  6 19 15]
 [ 0  4 11 17]
 [ 2  2 19  7]
 [ 0  1  7  6]]
Train  loss=1.2555 acc=0.4258 f1=0.3944 | Val loss=2.1443 acc=0.2500 f1=0.2058

Epoch 4/12


    t_loss=1.2887 | F1(macro)=0.4070 | Acc=0.4237


Confusion matrix:
 [[ 0  6 22 12]
 [ 1  5 11 15]
 [ 3  4 16  7]
 [ 0  1  5  8]]
Train  loss=1.2887 acc=0.4237 f1=0.4070 | Val loss=2.1036 acc=0.2500 f1=0.2188

Epoch 5/12


    t_loss=1.3410 | F1(macro)=0.3781 | Acc=0.3914


Confusion matrix:
 [[ 0  6 25  9]
 [ 5  6 12  9]
 [ 4  4 20  2]
 [ 0  1  7  6]]
Train  loss=1.3410 acc=0.3914 f1=0.3781 | Val loss=1.9356 acc=0.2759 f1=0.2426
  🔥 New best F1: 0.2426 – model saved.

Epoch 6/12


    t_loss=1.2115 | F1(macro)=0.4485 | Acc=0.4559


Confusion matrix:
 [[ 0  7 19 14]
 [ 0  6 15 11]
 [ 1  7 19  3]
 [ 0  2  6  6]]
Train  loss=1.2115 acc=0.4559 f1=0.4485 | Val loss=1.9960 acc=0.2672 f1=0.2248

Epoch 7/12


    t_loss=1.2626 | F1(macro)=0.4202 | Acc=0.4344


Confusion matrix:
 [[ 0  5 17 18]
 [ 4  6 12 10]
 [ 3  2 19  6]
 [ 0  1  5  8]]
Train  loss=1.2626 acc=0.4344 f1=0.4202 | Val loss=1.9552 acc=0.2845 f1=0.2511
  🔥 New best F1: 0.2511 – model saved.

Epoch 8/12


    t_loss=1.2671 | F1(macro)=0.3989 | Acc=0.4108


Confusion matrix:
 [[ 0  6 17 17]
 [ 2  3 10 17]
 [ 1  2 20  7]
 [ 0  1  4  9]]
Train  loss=1.2671 acc=0.4108 f1=0.3989 | Val loss=2.0526 acc=0.2759 f1=0.2279

Epoch 9/12


    t_loss=1.1797 | F1(macro)=0.4550 | Acc=0.4710


Confusion matrix:
 [[ 0  6 18 16]
 [ 3  5 10 14]
 [ 2  5 19  4]
 [ 0  1  5  8]]
Train  loss=1.1797 acc=0.4710 f1=0.4550 | Val loss=1.9951 acc=0.2759 f1=0.2383

Epoch 10/12


    t_loss=1.1948 | F1(macro)=0.4184 | Acc=0.4344


Confusion matrix:
 [[ 0  7 22 11]
 [ 5  4 13 10]
 [ 1  3 20  6]
 [ 0  1  7  6]]
Train  loss=1.1948 acc=0.4344 f1=0.4184 | Val loss=1.9938 acc=0.2586 f1=0.2151

Epoch 11/12


    t_loss=1.2525 | F1(macro)=0.3801 | Acc=0.3914


Confusion matrix:
 [[ 0  7 23 10]
 [ 4  5 15  8]
 [ 2  4 21  3]
 [ 0  2  6  6]]
Train  loss=1.2525 acc=0.3914 f1=0.3801 | Val loss=2.0243 acc=0.2759 f1=0.2337

Epoch 12/12


    t_loss=1.2103 | F1(macro)=0.4162 | Acc=0.4301


Confusion matrix:
 [[ 0  6 19 15]
 [ 1  2 14 15]
 [ 1  2 19  8]
 [ 0  1  5  8]]
Train  loss=1.2103 acc=0.4301 f1=0.4162 | Val loss=2.0603 acc=0.2500 f1=0.1991

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.8194 | F1(macro)=0.2615 | Acc=0.2624


Confusion matrix:
 [[21  3  5 12]
 [18  4  4  5]
 [19  1  3  7]
 [ 9  0  1  4]]
Train  loss=2.8194 acc=0.2624 f1=0.2615 | Val loss=1.9515 acc=0.2759 f1=0.2310
  🔥 New best F1: 0.2310 – model saved.

Epoch 2/8


    t_loss=2.1079 | F1(macro)=0.2835 | Acc=0.2839


Confusion matrix:
 [[ 4 28  0  9]
 [ 8 20  0  3]
 [ 7 17  1  5]
 [ 1  7  0  6]]
Train  loss=2.1079 acc=0.2839 f1=0.2835 | Val loss=2.0019 acc=0.2672 f1=0.2271

Epoch 3/8


    t_loss=1.7873 | F1(macro)=0.3230 | Acc=0.3312


Confusion matrix:
 [[ 5  9  4 23]
 [ 5  5  7 14]
 [ 4  6  5 15]
 [ 1  2  3  8]]
Train  loss=1.7873 acc=0.3312 f1=0.3230 | Val loss=2.0254 acc=0.1983 f1=0.1969

Epoch 4/8


    t_loss=1.6988 | F1(macro)=0.3098 | Acc=0.3118


Confusion matrix:
 [[ 7 12 20  2]
 [ 7  6 15  3]
 [ 3  6 21  0]
 [ 1  0  9  4]]
Train  loss=1.6988 acc=0.3118 f1=0.3098 | Val loss=1.7766 acc=0.3276 f1=0.3114
  🔥 New best F1: 0.3114 – model saved.

Epoch 5/8


    t_loss=1.6821 | F1(macro)=0.2878 | Acc=0.2882


Confusion matrix:
 [[16  9 15  1]
 [11  7 12  1]
 [13  5 11  1]
 [ 4  1  6  3]]
Train  loss=1.6821 acc=0.2882 f1=0.2878 | Val loss=1.5120 acc=0.3190 f1=0.3095

Epoch 6/8


    t_loss=1.6139 | F1(macro)=0.3264 | Acc=0.3269


Confusion matrix:
 [[15  8 14  4]
 [ 8  7 12  4]
 [ 7  5 14  4]
 [ 2  2  6  4]]
Train  loss=1.6139 acc=0.3269 f1=0.3264 | Val loss=1.4649 acc=0.3448 f1=0.3275
  🔥 New best F1: 0.3275 – model saved.

Epoch 7/8


    t_loss=1.4268 | F1(macro)=0.3790 | Acc=0.3806


Confusion matrix:
 [[ 7  7 25  2]
 [ 4  7 17  3]
 [ 1  9 19  1]
 [ 3  1  6  4]]
Train  loss=1.4268 acc=0.3806 f1=0.3790 | Val loss=1.5721 acc=0.3190 f1=0.3074

Epoch 8/8


    t_loss=1.4937 | F1(macro)=0.3139 | Acc=0.3118


Confusion matrix:
 [[ 9  9 21  2]
 [ 3  9 17  2]
 [ 1 10 18  1]
 [ 2  2  6  4]]
Train  loss=1.4937 acc=0.3118 f1=0.3139 | Val loss=1.5532 acc=0.3448 f1=0.3389
  🔥 New best F1: 0.3389 – model saved.
Restored best Stage 1 weights for fold 2 (F1=0.3389)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.4578 | F1(macro)=0.2800 | Acc=0.3097


Confusion matrix:
 [[ 6 11 18  6]
 [ 5  9 14  3]
 [ 2  8 16  4]
 [ 0  5  4  5]]
Train  loss=1.4578 acc=0.3097 f1=0.2800 | Val loss=1.6352 acc=0.3103 f1=0.3016
  🔥 New best F1: 0.3016 – model saved.

Epoch 2/12


    t_loss=1.4272 | F1(macro)=0.3366 | Acc=0.3505


Confusion matrix:
 [[ 0 21 10 10]
 [ 2 13  5 11]
 [ 0 16  9  5]
 [ 0  3  3  8]]
Train  loss=1.4272 acc=0.3505 f1=0.3366 | Val loss=1.7184 acc=0.2586 f1=0.2397

Epoch 3/12


    t_loss=1.3759 | F1(macro)=0.3487 | Acc=0.3634


Confusion matrix:
 [[12  8 12  9]
 [ 6 10 11  4]
 [ 6  7 13  4]
 [ 4  2  2  6]]
Train  loss=1.3759 acc=0.3634 f1=0.3487 | Val loss=1.5813 acc=0.3534 f1=0.3498
  🔥 New best F1: 0.3498 – model saved.

Epoch 4/12


    t_loss=1.3274 | F1(macro)=0.3628 | Acc=0.3892


Confusion matrix:
 [[11  5 15 10]
 [ 5  7 12  7]
 [ 6  4 13  7]
 [ 4  1  3  6]]
Train  loss=1.3274 acc=0.3892 f1=0.3628 | Val loss=1.6327 acc=0.3190 f1=0.3122

Epoch 5/12


    t_loss=1.4084 | F1(macro)=0.3367 | Acc=0.3548


Confusion matrix:
 [[24  7  2  8]
 [16  7  4  4]
 [18  2  5  5]
 [ 6  0  2  6]]
Train  loss=1.4084 acc=0.3548 f1=0.3367 | Val loss=1.6258 acc=0.3621 f1=0.3280

Epoch 6/12


    t_loss=1.3310 | F1(macro)=0.3657 | Acc=0.3849


Confusion matrix:
 [[ 8 17 11  5]
 [ 3 16  9  3]
 [ 6 15  8  1]
 [ 3  6  2  3]]
Train  loss=1.3310 acc=0.3849 f1=0.3657 | Val loss=1.7677 acc=0.3017 f1=0.2841

Epoch 7/12


    t_loss=1.2784 | F1(macro)=0.3988 | Acc=0.4065


Confusion matrix:
 [[16  6 17  2]
 [ 8  7 14  2]
 [11  4 13  2]
 [ 7  0  3  4]]
Train  loss=1.2784 acc=0.4065 f1=0.3988 | Val loss=1.6756 acc=0.3448 f1=0.3371

Epoch 8/12


    t_loss=1.2465 | F1(macro)=0.3310 | Acc=0.3785


Confusion matrix:
 [[12  6  9 14]
 [ 6  5  8 12]
 [10  4  8  8]
 [ 6  0  2  6]]
Train  loss=1.2465 acc=0.3785 f1=0.3310 | Val loss=1.5927 acc=0.2672 f1=0.2601

Epoch 9/12


    t_loss=1.3015 | F1(macro)=0.3907 | Acc=0.4086


Confusion matrix:
 [[ 6 17 10  8]
 [ 1 14 10  6]
 [ 4  9 10  7]
 [ 1  6  2  5]]
Train  loss=1.3015 acc=0.4086 f1=0.3907 | Val loss=1.6367 acc=0.3017 f1=0.2907

Epoch 10/12


    t_loss=1.2928 | F1(macro)=0.3835 | Acc=0.4065


Confusion matrix:
 [[11 10 13  7]
 [ 3 11 13  4]
 [ 7  5 16  2]
 [ 5  3  2  4]]
Train  loss=1.2928 acc=0.4065 f1=0.3835 | Val loss=1.6136 acc=0.3621 f1=0.3464

Epoch 11/12


    t_loss=1.2597 | F1(macro)=0.3827 | Acc=0.4043


Confusion matrix:
 [[12  6 14  9]
 [ 4 10 12  5]
 [ 6  4 14  6]
 [ 6  0  2  6]]
Train  loss=1.2597 acc=0.4043 f1=0.3827 | Val loss=1.5761 acc=0.3621 f1=0.3572
  🔥 New best F1: 0.3572 – model saved.

Epoch 12/12


    t_loss=1.2429 | F1(macro)=0.3689 | Acc=0.3935


Confusion matrix:
 [[13  7 11 10]
 [ 7  8  9  7]
 [ 8  5 11  6]
 [ 6  0  2  6]]
Train  loss=1.2429 acc=0.3935 f1=0.3689 | Val loss=1.5592 acc=0.3276 f1=0.3222

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=3.0208 | F1(macro)=0.2579 | Acc=0.2581


Confusion matrix:
 [[38  1  0  2]
 [25  2  0  4]
 [27  0  0  3]
 [12  0  0  2]]
Train  loss=3.0208 acc=0.2581 f1=0.2579 | Val loss=4.1442 acc=0.3621 f1=0.2023
  🔥 New best F1: 0.2023 – model saved.

Epoch 2/8


    t_loss=2.1859 | F1(macro)=0.2669 | Acc=0.2667


Confusion matrix:
 [[ 1 14 14 12]
 [ 2 16 11  2]
 [ 1  6 13 10]
 [ 2  1  4  7]]
Train  loss=2.1859 acc=0.2667 f1=0.2669 | Val loss=1.8609 acc=0.3190 f1=0.2963
  🔥 New best F1: 0.2963 – model saved.

Epoch 3/8


    t_loss=1.7076 | F1(macro)=0.3600 | Acc=0.3591


Confusion matrix:
 [[ 7  2 28  4]
 [ 3  4 23  1]
 [ 3  3 22  2]
 [ 1  0  8  5]]
Train  loss=1.7076 acc=0.3591 f1=0.3600 | Val loss=2.1518 acc=0.3276 f1=0.3089
  🔥 New best F1: 0.3089 – model saved.

Epoch 4/8


    t_loss=1.7673 | F1(macro)=0.3150 | Acc=0.3183


Confusion matrix:
 [[ 2 15 15  9]
 [ 0  9 21  1]
 [ 0  9 15  6]
 [ 0  2  7  5]]
Train  loss=1.7673 acc=0.3183 f1=0.3150 | Val loss=1.7707 acc=0.2672 f1=0.2481

Epoch 5/8


    t_loss=1.5989 | F1(macro)=0.3420 | Acc=0.3398


Confusion matrix:
 [[ 2  7 14 18]
 [ 2 10 12  7]
 [ 1  5 10 14]
 [ 0  1  4  9]]
Train  loss=1.5989 acc=0.3398 f1=0.3420 | Val loss=1.7271 acc=0.2672 f1=0.2583

Epoch 6/8


    t_loss=1.4981 | F1(macro)=0.3761 | Acc=0.3763


Confusion matrix:
 [[ 9 15  3 14]
 [ 6 15  7  3]
 [ 5  4  8 13]
 [ 2  1  1 10]]
Train  loss=1.4981 acc=0.3763 f1=0.3761 | Val loss=1.4588 acc=0.3621 f1=0.3593
  🔥 New best F1: 0.3593 – model saved.

Epoch 7/8


    t_loss=1.3640 | F1(macro)=0.3795 | Acc=0.3828


Confusion matrix:
 [[ 5  4 20 12]
 [ 4  4 20  3]
 [ 2  1 14 13]
 [ 0  0  6  8]]
Train  loss=1.3640 acc=0.3828 f1=0.3795 | Val loss=1.5565 acc=0.2672 f1=0.2559

Epoch 8/8


    t_loss=1.3871 | F1(macro)=0.3977 | Acc=0.3957


Confusion matrix:
 [[18  7  4 12]
 [12  6  8  5]
 [ 7  1  9 13]
 [ 4  0  2  8]]
Train  loss=1.3871 acc=0.3957 f1=0.3977 | Val loss=1.4126 acc=0.3534 f1=0.3383
Restored best Stage 1 weights for fold 3 (F1=0.3593)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.3940 | F1(macro)=0.3194 | Acc=0.3376


Confusion matrix:
 [[ 3  5 11 22]
 [ 3  9 11  8]
 [ 3  2  8 17]
 [ 0  0  3 11]]
Train  loss=1.3940 acc=0.3376 f1=0.3194 | Val loss=1.5715 acc=0.2672 f1=0.2656
  🔥 New best F1: 0.2656 – model saved.

Epoch 2/12


    t_loss=1.4560 | F1(macro)=0.3287 | Acc=0.3419


Confusion matrix:
 [[ 9  8  8 16]
 [11  5 11  4]
 [ 7  1  9 13]
 [ 0  0  4 10]]
Train  loss=1.4560 acc=0.3419 f1=0.3287 | Val loss=1.5188 acc=0.2845 f1=0.2820
  🔥 New best F1: 0.2820 – model saved.

Epoch 3/12


    t_loss=1.3454 | F1(macro)=0.3658 | Acc=0.3892


Confusion matrix:
 [[ 2  7 25  7]
 [ 3  2 22  4]
 [ 1  4 20  5]
 [ 1  1  9  3]]
Train  loss=1.3454 acc=0.3892 f1=0.3658 | Val loss=1.6785 acc=0.2328 f1=0.1828

Epoch 4/12


    t_loss=1.3662 | F1(macro)=0.3559 | Acc=0.3656


Confusion matrix:
 [[ 5  7 17 12]
 [ 3  4 19  5]
 [ 3  3 16  8]
 [ 0  0  7  7]]
Train  loss=1.3662 acc=0.3656 f1=0.3559 | Val loss=1.5261 acc=0.2759 f1=0.2585

Epoch 5/12


    t_loss=1.2742 | F1(macro)=0.3816 | Acc=0.4000


Confusion matrix:
 [[ 3  8 23  7]
 [ 3  3 20  5]
 [ 0  3 21  6]
 [ 0  1  9  4]]
Train  loss=1.2742 acc=0.4000 f1=0.3816 | Val loss=1.6055 acc=0.2672 f1=0.2220

Epoch 6/12


    t_loss=1.2410 | F1(macro)=0.4176 | Acc=0.4366


Confusion matrix:
 [[ 7  9 11 14]
 [ 6  4 16  5]
 [ 3  3 14 10]
 [ 2  0  8  4]]
Train  loss=1.2410 acc=0.4366 f1=0.4176 | Val loss=1.5271 acc=0.2500 f1=0.2330

Epoch 7/12


    t_loss=1.2591 | F1(macro)=0.4082 | Acc=0.4258


Confusion matrix:
 [[ 9  5  5 22]
 [13  7  3  8]
 [ 6  3  4 17]
 [ 1  0  2 11]]
Train  loss=1.2591 acc=0.4258 f1=0.4082 | Val loss=1.5190 acc=0.2672 f1=0.2622

Epoch 8/12


    t_loss=1.1972 | F1(macro)=0.4028 | Acc=0.4280


Confusion matrix:
 [[ 3  2 14 22]
 [ 3  1 19  8]
 [ 3  0 13 14]
 [ 0  0  4 10]]
Train  loss=1.1972 acc=0.4280 f1=0.4028 | Val loss=1.6363 acc=0.2328 f1=0.1995

Epoch 9/12


    t_loss=1.2325 | F1(macro)=0.4037 | Acc=0.4194


Confusion matrix:
 [[12  3 14 12]
 [ 9  2 15  5]
 [ 8  0 11 11]
 [ 1  0  5  8]]
Train  loss=1.2325 acc=0.4194 f1=0.4037 | Val loss=1.5187 acc=0.2845 f1=0.2656

Epoch 10/12


    t_loss=1.2553 | F1(macro)=0.4117 | Acc=0.4280


Confusion matrix:
 [[ 4  5 17 15]
 [ 4  4 18  5]
 [ 2  3 13 12]
 [ 1  0  6  7]]
Train  loss=1.2553 acc=0.4280 f1=0.4117 | Val loss=1.5391 acc=0.2414 f1=0.2284

Epoch 11/12


    t_loss=1.1826 | F1(macro)=0.4030 | Acc=0.4366


Confusion matrix:
 [[ 3  7 19 12]
 [ 2  5 20  4]
 [ 2  2 17  9]
 [ 1  0  6  7]]
Train  loss=1.1826 acc=0.4366 f1=0.4030 | Val loss=1.5310 acc=0.2759 f1=0.2546

Epoch 12/12


    t_loss=1.2263 | F1(macro)=0.4092 | Acc=0.4323


Confusion matrix:
 [[ 3  5 15 18]
 [ 4  6 15  6]
 [ 1  2 13 14]
 [ 1  0  5  8]]
Train  loss=1.2263 acc=0.4323 f1=0.4092 | Val loss=1.5526 acc=0.2586 f1=0.2482

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=3.0948 | F1(macro)=0.2363 | Acc=0.2366


Confusion matrix:
 [[ 6  5 13 17]
 [ 9  5 10  8]
 [ 6  4 11  9]
 [ 3  4  2  4]]
Train  loss=3.0948 acc=0.2366 f1=0.2363 | Val loss=2.0833 acc=0.2241 f1=0.2187
  🔥 New best F1: 0.2187 – model saved.

Epoch 2/8


    t_loss=2.1298 | F1(macro)=0.2748 | Acc=0.2774


Confusion matrix:
 [[ 0 19 16  6]
 [ 1 10 12  9]
 [ 1 10 14  5]
 [ 0  3  4  6]]
Train  loss=2.1298 acc=0.2774 f1=0.2748 | Val loss=1.9912 acc=0.2586 f1=0.2366
  🔥 New best F1: 0.2366 – model saved.

Epoch 3/8


    t_loss=1.8877 | F1(macro)=0.2829 | Acc=0.2903


Confusion matrix:
 [[ 1  8 22 10]
 [ 0  9 13 10]
 [ 0  2 18 10]
 [ 1  1  9  2]]
Train  loss=1.8877 acc=0.2903 f1=0.2829 | Val loss=2.0034 acc=0.2586 f1=0.2182

Epoch 4/8


    t_loss=1.6785 | F1(macro)=0.3123 | Acc=0.3247


Confusion matrix:
 [[ 3  8 11 19]
 [ 2 11  6 13]
 [ 3  1  7 19]
 [ 1  1  2  9]]
Train  loss=1.6785 acc=0.3247 f1=0.3123 | Val loss=1.8885 acc=0.2586 f1=0.2579
  🔥 New best F1: 0.2579 – model saved.

Epoch 5/8


    t_loss=1.5717 | F1(macro)=0.3324 | Acc=0.3333


Confusion matrix:
 [[ 8  9 20  4]
 [ 7 12 10  3]
 [ 4  3 16  7]
 [ 2  0  6  5]]
Train  loss=1.5717 acc=0.3333 f1=0.3324 | Val loss=1.6313 acc=0.3534 f1=0.3473
  🔥 New best F1: 0.3473 – model saved.

Epoch 6/8


    t_loss=1.5451 | F1(macro)=0.3482 | Acc=0.3505


Confusion matrix:
 [[15 10  8  8]
 [ 7 10  7  8]
 [ 8  5 11  6]
 [ 2  0  7  4]]
Train  loss=1.5451 acc=0.3505 f1=0.3482 | Val loss=1.5059 acc=0.3448 f1=0.3290

Epoch 7/8


    t_loss=1.4215 | F1(macro)=0.3685 | Acc=0.3742


Confusion matrix:
 [[11 14 10  6]
 [ 3 12 10  7]
 [ 4  5 12  9]
 [ 1  1  5  6]]
Train  loss=1.4215 acc=0.3742 f1=0.3685 | Val loss=1.5196 acc=0.3534 f1=0.3481
  🔥 New best F1: 0.3481 – model saved.

Epoch 8/8


    t_loss=1.4012 | F1(macro)=0.3855 | Acc=0.3871


Confusion matrix:
 [[ 6 19 12  4]
 [ 5 15  6  6]
 [ 4  8 12  6]
 [ 1  3  5  4]]
Train  loss=1.4012 acc=0.3871 f1=0.3855 | Val loss=1.5014 acc=0.3190 f1=0.3029
Restored best Stage 1 weights for fold 4 (F1=0.3481)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.4276 | F1(macro)=0.3515 | Acc=0.3720


Confusion matrix:
 [[11 11  4 15]
 [ 8 12  0 12]
 [ 4  4  4 18]
 [ 0  3  1  9]]
Train  loss=1.4276 acc=0.3720 f1=0.3515 | Val loss=1.6435 acc=0.3103 f1=0.3012
  🔥 New best F1: 0.3012 – model saved.

Epoch 2/12


    t_loss=1.3349 | F1(macro)=0.3578 | Acc=0.3828


Confusion matrix:
 [[16  3  6 16]
 [11  8  3 10]
 [ 6  2  3 19]
 [ 0  2  2  9]]
Train  loss=1.3349 acc=0.3828 f1=0.3578 | Val loss=1.5945 acc=0.3103 f1=0.2945

Epoch 3/12


    t_loss=1.3961 | F1(macro)=0.3637 | Acc=0.3742


Confusion matrix:
 [[20  3  7 11]
 [12  9  4  7]
 [ 8  1  8 13]
 [ 1  1  3  8]]
Train  loss=1.3961 acc=0.3742 f1=0.3637 | Val loss=1.5120 acc=0.3879 f1=0.3736
  🔥 New best F1: 0.3736 – model saved.

Epoch 4/12


    t_loss=1.3432 | F1(macro)=0.3537 | Acc=0.3742


Confusion matrix:
 [[ 6 10 13 12]
 [ 3 10  8 11]
 [ 2  5 11 12]
 [ 0  2  4  7]]
Train  loss=1.3432 acc=0.3742 f1=0.3537 | Val loss=1.5334 acc=0.2931 f1=0.2894

Epoch 5/12


    t_loss=1.3133 | F1(macro)=0.4035 | Acc=0.4108


Confusion matrix:
 [[10  7  3 21]
 [ 6 10  4 12]
 [ 4  5  4 17]
 [ 0  2  1 10]]
Train  loss=1.3133 acc=0.4108 f1=0.4035 | Val loss=1.5758 acc=0.2931 f1=0.2874

Epoch 6/12


    t_loss=1.2993 | F1(macro)=0.3705 | Acc=0.3871


Confusion matrix:
 [[ 4  7  7 23]
 [ 5  6  6 15]
 [ 4  2  5 19]
 [ 0  0  2 11]]
Train  loss=1.2993 acc=0.3871 f1=0.3705 | Val loss=1.6963 acc=0.2241 f1=0.2188

Epoch 7/12


    t_loss=1.3755 | F1(macro)=0.4018 | Acc=0.4065


Confusion matrix:
 [[ 7  6 11 17]
 [ 6  7  5 14]
 [ 6  0  8 16]
 [ 1  0  3  9]]
Train  loss=1.3755 acc=0.4065 f1=0.4018 | Val loss=1.6090 acc=0.2672 f1=0.2705

Epoch 8/12


    t_loss=1.1920 | F1(macro)=0.4009 | Acc=0.4409


Confusion matrix:
 [[ 4 11 12 14]
 [ 3 12  8  9]
 [ 2  4 12 12]
 [ 0  3  3  7]]
Train  loss=1.1920 acc=0.4409 f1=0.4009 | Val loss=1.5355 acc=0.3017 f1=0.2927

Epoch 9/12


    t_loss=1.2102 | F1(macro)=0.4020 | Acc=0.4344


Confusion matrix:
 [[ 3 12 11 15]
 [ 2 11 10  9]
 [ 1  4 13 12]
 [ 0  0  5  8]]
Train  loss=1.2102 acc=0.4344 f1=0.4020 | Val loss=1.5856 acc=0.3017 f1=0.2895

Epoch 10/12


    t_loss=1.1968 | F1(macro)=0.4335 | Acc=0.4559


Confusion matrix:
 [[ 5  8  6 22]
 [ 5  9  6 12]
 [ 3  2  6 19]
 [ 0  0  3 10]]
Train  loss=1.1968 acc=0.4559 f1=0.4335 | Val loss=1.6272 acc=0.2586 f1=0.2591

Epoch 11/12


    t_loss=1.2783 | F1(macro)=0.3954 | Acc=0.4237


Confusion matrix:
 [[ 3  7 10 21]
 [ 4 10  7 11]
 [ 3  3  9 15]
 [ 0  0  2 11]]
Train  loss=1.2783 acc=0.4237 f1=0.3954 | Val loss=1.6070 acc=0.2845 f1=0.2806

Epoch 12/12


    t_loss=1.2750 | F1(macro)=0.3936 | Acc=0.4151


Confusion matrix:
 [[ 5 11 10 15]
 [ 4 15  4  9]
 [ 2  5 11 12]
 [ 1  2  4  6]]
Train  loss=1.2750 acc=0.4151 f1=0.3936 | Val loss=1.5549 acc=0.3190 f1=0.3103


# tf_efficientnetv2_s.in21k

In [5]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [6]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [7]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png  Triple negative
1  img_0001.png  Triple negative
2  img_0002.png  Triple negative
3  img_0003.png  Triple negative
4  img_0004.png        Luminal A


In [8]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
                         shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            img_tensor = img_tensor.squeeze(0)  # [3,H,W]
            img_tensor = img_tensor.to(device)

            # -------- TTA: apply multiple augmented views --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1,4]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N, 4]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
pred_indices = mean_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print("Saved submission_5fold_tta.csv")

Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_tta.csv


In [9]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.30954007346140633
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.19635214402205745
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.3396639879666886
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.2589714882818331
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.2665603472773417
Mean OOF F1: 0.2742176082018654
