In [1]:
import enum
import json
import os
from copy import deepcopy

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B0

In [4]:
best_f1_per_fold: dict[int, int] = {}

In [5]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.2,          # Dropout
        # drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    For EfficientNet from timm: unfreeze last 2 blocks + classifier head.
    """
    freeze_all(model)

    # Last 2 conv blocks
    if hasattr(model, "blocks"):
        for blk in model.blocks[-2:]:
            for p in blk.parameters():
                p.requires_grad = True

    # Classifier head
    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True


if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 15
    LR = 3e-4
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b0_model(pretrained=True)
        unfreeze_last_two_blocks_and_head(model)

        # ---- loss, optimizer, scheduler ----
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.1
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(
                    best_state,
                    f"best_effb0_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best weights for this fold
        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1


========== Fold 0 ==========

Epoch 1/15


    t_loss=2.3922 | F1(macro)=0.2746 | Acc=0.2759


Confusion matrix:
 [[ 7  6  1 27]
 [ 6  4  2 20]
 [ 8  6  0 16]
 [ 2  3  0  9]]
Train  loss=2.3922 acc=0.2759 f1=0.2746 | Val loss=2.7907 acc=0.1709 f1=0.1462
  🔥 New best F1: 0.1462 – model saved.

Epoch 2/15


    t_loss=1.6811 | F1(macro)=0.3100 | Acc=0.3341


Confusion matrix:
 [[16  3 16  6]
 [16  3  8  5]
 [13  0  7 10]
 [ 5  2  4  3]]
Train  loss=1.6811 acc=0.3341 f1=0.3100 | Val loss=2.1212 acc=0.2479 f1=0.2187
  🔥 New best F1: 0.2187 – model saved.

Epoch 3/15


    t_loss=1.4996 | F1(macro)=0.4027 | Acc=0.4116


Confusion matrix:
 [[12  8 15  6]
 [10  8  5  9]
 [ 4  2 10 14]
 [ 4  2  4  4]]
Train  loss=1.4996 acc=0.4116 f1=0.4027 | Val loss=1.6639 acc=0.2906 f1=0.2821
  🔥 New best F1: 0.2821 – model saved.

Epoch 4/15


    t_loss=1.4048 | F1(macro)=0.3960 | Acc=0.4073


Confusion matrix:
 [[ 5  8 15 13]
 [ 9  7  7  9]
 [ 3  1 11 15]
 [ 2  1  5  6]]
Train  loss=1.4048 acc=0.4073 f1=0.3960 | Val loss=1.8615 acc=0.2479 f1=0.2466

Epoch 5/15


    t_loss=1.3126 | F1(macro)=0.4061 | Acc=0.4181


Confusion matrix:
 [[ 3  4 27  7]
 [ 3  5 17  7]
 [ 1  1 13 15]
 [ 2  0 10  2]]
Train  loss=1.3126 acc=0.4181 f1=0.4061 | Val loss=2.0869 acc=0.1966 f1=0.1788

Epoch 6/15


    t_loss=1.1828 | F1(macro)=0.4840 | Acc=0.5000


Confusion matrix:
 [[ 9  3 24  5]
 [ 6  6 14  6]
 [ 5  2 15  8]
 [ 4  0  7  3]]
Train  loss=1.1828 acc=0.5000 f1=0.4840 | Val loss=2.0519 acc=0.2821 f1=0.2640

Epoch 7/15


    t_loss=1.0696 | F1(macro)=0.5257 | Acc=0.5409


Confusion matrix:
 [[ 5  7 11 18]
 [ 3 10  6 13]
 [ 3  2  6 19]
 [ 1  1  3  9]]
Train  loss=1.0696 acc=0.5409 f1=0.5257 | Val loss=2.1229 acc=0.2564 f1=0.2585

Epoch 8/15


    t_loss=1.0978 | F1(macro)=0.5138 | Acc=0.5323


Confusion matrix:
 [[ 6 10 20  5]
 [ 3 15  8  6]
 [ 3  5 13  9]
 [ 2  2  5  5]]
Train  loss=1.0978 acc=0.5323 f1=0.5138 | Val loss=1.8604 acc=0.3333 f1=0.3214
  🔥 New best F1: 0.3214 – model saved.

Epoch 9/15


    t_loss=0.9870 | F1(macro)=0.5650 | Acc=0.5819


Confusion matrix:
 [[15  5 16  5]
 [ 5 12 10  5]
 [ 3  1 18  8]
 [ 3  3  3  5]]
Train  loss=0.9870 acc=0.5819 f1=0.5650 | Val loss=1.7989 acc=0.4274 f1=0.4096
  🔥 New best F1: 0.4096 – model saved.

Epoch 10/15


    t_loss=0.9921 | F1(macro)=0.5862 | Acc=0.6034


Confusion matrix:
 [[17  7 15  2]
 [12 12  4  4]
 [ 9  6 11  4]
 [ 7  3  2  2]]
Train  loss=0.9921 acc=0.6034 f1=0.5862 | Val loss=1.9127 acc=0.3590 f1=0.3260

Epoch 11/15


    t_loss=0.9595 | F1(macro)=0.5988 | Acc=0.6034


Confusion matrix:
 [[16 10 12  3]
 [12 13  6  1]
 [14  4  7  5]
 [ 8  2  4  0]]
Train  loss=0.9595 acc=0.6034 f1=0.5988 | Val loss=1.8872 acc=0.3077 f1=0.2538

Epoch 12/15


    t_loss=0.9549 | F1(macro)=0.6309 | Acc=0.6336


Confusion matrix:
 [[15  9 16  1]
 [13 15  2  2]
 [ 8  2 16  4]
 [ 7  3  4  0]]
Train  loss=0.9549 acc=0.6336 f1=0.6309 | Val loss=1.9884 acc=0.3932 f1=0.3299

Epoch 13/15


    t_loss=0.8831 | F1(macro)=0.6630 | Acc=0.6681


Confusion matrix:
 [[15  7 16  3]
 [12 13  6  1]
 [ 9  4 14  3]
 [ 7  3  4  0]]
Train  loss=0.8831 acc=0.6681 f1=0.6630 | Val loss=1.9080 acc=0.3590 f1=0.2995

Epoch 14/15


    t_loss=0.9007 | F1(macro)=0.6529 | Acc=0.6552


Confusion matrix:
 [[13  6 18  4]
 [ 8 10  9  5]
 [ 7  3 14  6]
 [ 4  1  5  4]]
Train  loss=0.9007 acc=0.6552 f1=0.6529 | Val loss=1.9337 acc=0.3504 f1=0.3379

Epoch 15/15


    t_loss=0.9665 | F1(macro)=0.6215 | Acc=0.6315


Confusion matrix:
 [[14  6 19  2]
 [ 5 12 10  5]
 [ 6  3 16  5]
 [ 4  3  5  2]]
Train  loss=0.9665 acc=0.6315 f1=0.6215 | Val loss=1.9380 acc=0.3761 f1=0.3429
Restored best weights for fold 0 (F1=0.4096)

========== Fold 1 ==========

Epoch 1/15


    t_loss=2.0912 | F1(macro)=0.3043 | Acc=0.3204


Confusion matrix:
 [[ 1  8  8 23]
 [ 1 12  2 17]
 [ 2  9  4 15]
 [ 0  1  2 11]]
Train  loss=2.0912 acc=0.3204 f1=0.3043 | Val loss=2.1623 acc=0.2414 f1=0.2204
  🔥 New best F1: 0.2204 – model saved.

Epoch 2/15


    t_loss=1.5346 | F1(macro)=0.3547 | Acc=0.3763


Confusion matrix:
 [[ 1 23  4 12]
 [ 0 19  3 10]
 [ 4 15  6  5]
 [ 0  5  4  5]]
Train  loss=1.5346 acc=0.3763 f1=0.3547 | Val loss=2.3266 acc=0.2672 f1=0.2304
  🔥 New best F1: 0.2304 – model saved.

Epoch 3/15


    t_loss=1.4395 | F1(macro)=0.3874 | Acc=0.3957


Confusion matrix:
 [[ 5 11 11 13]
 [ 2 11  6 13]
 [ 3  8 11  8]
 [ 1  1  5  7]]
Train  loss=1.4395 acc=0.3957 f1=0.3874 | Val loss=2.0900 acc=0.2931 f1=0.2873
  🔥 New best F1: 0.2873 – model saved.

Epoch 4/15


    t_loss=1.1957 | F1(macro)=0.4408 | Acc=0.4645


Confusion matrix:
 [[ 5  7 11 17]
 [ 5  8  2 17]
 [ 4 10  7  9]
 [ 1  1  5  7]]
Train  loss=1.1957 acc=0.4645 f1=0.4408 | Val loss=2.0748 acc=0.2328 f1=0.2327

Epoch 5/15


    t_loss=1.2088 | F1(macro)=0.4322 | Acc=0.4602


Confusion matrix:
 [[ 6 13  6 15]
 [ 8 10  2 12]
 [ 5 13  5  7]
 [ 1  3  4  6]]
Train  loss=1.2088 acc=0.4602 f1=0.4322 | Val loss=2.0759 acc=0.2328 f1=0.2292

Epoch 6/15


    t_loss=1.1115 | F1(macro)=0.5018 | Acc=0.5247


Confusion matrix:
 [[ 8  4 16 12]
 [11  6  3 12]
 [ 9  4 10  7]
 [ 5  0  4  5]]
Train  loss=1.1115 acc=0.5247 f1=0.5018 | Val loss=2.0174 acc=0.2500 f1=0.2494

Epoch 7/15


    t_loss=1.0674 | F1(macro)=0.4734 | Acc=0.5032


Confusion matrix:
 [[ 9  8 13 10]
 [ 8  9  4 11]
 [10  8  4  8]
 [ 4  0  5  5]]
Train  loss=1.0674 acc=0.5032 f1=0.4734 | Val loss=2.0672 acc=0.2328 f1=0.2301

Epoch 8/15


    t_loss=1.0580 | F1(macro)=0.5356 | Acc=0.5505


Confusion matrix:
 [[ 6  8 12 14]
 [ 8  7  3 14]
 [ 9  9  5  7]
 [ 3  1  5  5]]
Train  loss=1.0580 acc=0.5505 f1=0.5356 | Val loss=2.0193 acc=0.1983 f1=0.1986

Epoch 9/15


    t_loss=1.0221 | F1(macro)=0.5682 | Acc=0.5763


Confusion matrix:
 [[ 5 13 15  7]
 [10 10  5  7]
 [ 7 12  8  3]
 [ 3  3  5  3]]
Train  loss=1.0221 acc=0.5763 f1=0.5682 | Val loss=2.0009 acc=0.2241 f1=0.2175

Epoch 10/15


    t_loss=0.8841 | F1(macro)=0.6295 | Acc=0.6473


Confusion matrix:
 [[13  6 11 10]
 [10  7  3 12]
 [ 9  6  8  7]
 [ 3  2  3  6]]
Train  loss=0.8841 acc=0.6473 f1=0.6295 | Val loss=1.9315 acc=0.2931 f1=0.2867

Epoch 11/15


    t_loss=0.8993 | F1(macro)=0.6057 | Acc=0.6258


Confusion matrix:
 [[10  6 12 12]
 [11  7  3 11]
 [12  6  5  7]
 [ 3  1  5  5]]
Train  loss=0.8993 acc=0.6258 f1=0.6057 | Val loss=1.9136 acc=0.2328 f1=0.2296

Epoch 12/15


    t_loss=0.8788 | F1(macro)=0.6685 | Acc=0.6753


Confusion matrix:
 [[ 9  9 13  9]
 [12  8  5  7]
 [10 10  7  3]
 [ 3  3  6  2]]
Train  loss=0.8788 acc=0.6753 f1=0.6685 | Val loss=1.9534 acc=0.2241 f1=0.2113

Epoch 13/15


    t_loss=0.8683 | F1(macro)=0.6411 | Acc=0.6538


Confusion matrix:
 [[11  5 13 11]
 [13  7  3  9]
 [11  9  5  5]
 [ 4  1  5  4]]
Train  loss=0.8683 acc=0.6538 f1=0.6411 | Val loss=1.9760 acc=0.2328 f1=0.2256

Epoch 14/15


    t_loss=0.8642 | F1(macro)=0.6857 | Acc=0.6968


Confusion matrix:
 [[ 7  8 10 15]
 [ 6 10  1 15]
 [ 8 10  4  8]
 [ 1  1  3  9]]
Train  loss=0.8642 acc=0.6968 f1=0.6857 | Val loss=1.9891 acc=0.2586 f1=0.2539

Epoch 15/15


    t_loss=0.8882 | F1(macro)=0.6314 | Acc=0.6430


Confusion matrix:
 [[ 9 10 11 10]
 [10 11  3  8]
 [13  9  5  3]
 [ 4  3  4  3]]
Train  loss=0.8882 acc=0.6430 f1=0.6314 | Val loss=1.9560 acc=0.2414 f1=0.2305
Restored best weights for fold 1 (F1=0.2873)

========== Fold 2 ==========

Epoch 1/15


    t_loss=2.2300 | F1(macro)=0.3314 | Acc=0.3333


Confusion matrix:
 [[ 8  7  4 22]
 [ 7  3  5 16]
 [ 5  7  6 12]
 [ 3  1  1  9]]
Train  loss=2.2300 acc=0.3333 f1=0.3314 | Val loss=2.1061 acc=0.2241 f1=0.2200
  🔥 New best F1: 0.2200 – model saved.

Epoch 2/15


    t_loss=1.6519 | F1(macro)=0.3529 | Acc=0.3699


Confusion matrix:
 [[13  9  8 11]
 [ 9  6  9  7]
 [ 9  4 11  6]
 [ 8  1  2  3]]
Train  loss=1.6519 acc=0.3699 f1=0.3529 | Val loss=1.9740 acc=0.2845 f1=0.2683
  🔥 New best F1: 0.2683 – model saved.

Epoch 3/15


    t_loss=1.4615 | F1(macro)=0.4080 | Acc=0.4129


Confusion matrix:
 [[12  4  5 20]
 [10  5  7  9]
 [10  3  4 13]
 [ 3  0  3  8]]
Train  loss=1.4615 acc=0.4129 f1=0.4080 | Val loss=1.8696 acc=0.2500 f1=0.2404

Epoch 4/15


    t_loss=1.3284 | F1(macro)=0.4423 | Acc=0.4495


Confusion matrix:
 [[26  5  1  9]
 [15  7  3  6]
 [16  3  3  8]
 [ 9  0  0  5]]
Train  loss=1.3284 acc=0.4495 f1=0.4423 | Val loss=1.9178 acc=0.3534 f1=0.2976
  🔥 New best F1: 0.2976 – model saved.

Epoch 5/15


    t_loss=1.2642 | F1(macro)=0.4766 | Acc=0.4817


Confusion matrix:
 [[ 8 15 12  6]
 [ 3 17  7  4]
 [ 4  9 12  5]
 [ 6  0  3  5]]
Train  loss=1.2642 acc=0.4817 f1=0.4766 | Val loss=1.9240 acc=0.3621 f1=0.3499
  🔥 New best F1: 0.3499 – model saved.

Epoch 6/15


    t_loss=1.2328 | F1(macro)=0.4843 | Acc=0.4968


Confusion matrix:
 [[11 14 12  4]
 [13  7  7  4]
 [ 9  4 10  7]
 [ 5  0  2  7]]
Train  loss=1.2328 acc=0.4968 f1=0.4843 | Val loss=1.7658 acc=0.3017 f1=0.3113

Epoch 7/15


    t_loss=1.0848 | F1(macro)=0.5307 | Acc=0.5441


Confusion matrix:
 [[19  7  3 12]
 [ 9  6  6 10]
 [11  2  4 13]
 [ 7  0  1  6]]
Train  loss=1.0848 acc=0.5441 f1=0.5307 | Val loss=2.0025 acc=0.3017 f1=0.2744

Epoch 8/15


    t_loss=1.1337 | F1(macro)=0.5004 | Acc=0.5075


Confusion matrix:
 [[ 9 15  4 13]
 [ 9 12  4  6]
 [ 4  9 11  6]
 [ 2  4  3  5]]
Train  loss=1.1337 acc=0.5075 f1=0.5004 | Val loss=1.8899 acc=0.3190 f1=0.3163

Epoch 9/15


    t_loss=1.0052 | F1(macro)=0.5887 | Acc=0.5957


Confusion matrix:
 [[10 10  8 13]
 [ 8 10  6  7]
 [ 6  5 10  9]
 [ 2  1  5  6]]
Train  loss=1.0052 acc=0.5957 f1=0.5887 | Val loss=2.0783 acc=0.3103 f1=0.3083

Epoch 10/15


    t_loss=0.9351 | F1(macro)=0.6026 | Acc=0.6194


Confusion matrix:
 [[10 14  9  8]
 [ 8 13  8  2]
 [ 7  7 15  1]
 [ 3  1  6  4]]
Train  loss=0.9351 acc=0.6194 f1=0.6026 | Val loss=1.7817 acc=0.3621 f1=0.3502
  🔥 New best F1: 0.3502 – model saved.

Epoch 11/15


    t_loss=0.9219 | F1(macro)=0.6430 | Acc=0.6559


Confusion matrix:
 [[ 9 15  4 13]
 [ 5 15  5  6]
 [ 5  6  9 10]
 [ 2  2  3  7]]
Train  loss=0.9219 acc=0.6559 f1=0.6430 | Val loss=1.7920 acc=0.3448 f1=0.3395

Epoch 12/15


    t_loss=0.8742 | F1(macro)=0.6238 | Acc=0.6495


Confusion matrix:
 [[ 6 14  9 12]
 [ 3 17  5  6]
 [ 5  7 11  7]
 [ 2  2  3  7]]
Train  loss=0.8742 acc=0.6495 f1=0.6238 | Val loss=1.8966 acc=0.3534 f1=0.3433

Epoch 13/15


    t_loss=0.9390 | F1(macro)=0.6072 | Acc=0.6258


Confusion matrix:
 [[10  8 10 13]
 [ 8 11  7  5]
 [11  5 10  4]
 [ 3  1  4  6]]
Train  loss=0.9390 acc=0.6258 f1=0.6072 | Val loss=1.8357 acc=0.3190 f1=0.3201

Epoch 14/15


    t_loss=0.8651 | F1(macro)=0.6694 | Acc=0.6796


Confusion matrix:
 [[10 13  5 13]
 [ 5 16  4  6]
 [ 8  6  8  8]
 [ 3  1  4  6]]
Train  loss=0.8651 acc=0.6796 f1=0.6694 | Val loss=1.7718 acc=0.3448 f1=0.3363

Epoch 15/15


    t_loss=0.9121 | F1(macro)=0.6200 | Acc=0.6366


Confusion matrix:
 [[ 8 13  8 12]
 [ 4 15  7  5]
 [ 6  7 12  5]
 [ 3  1  4  6]]
Train  loss=0.9121 acc=0.6366 f1=0.6200 | Val loss=1.8230 acc=0.3534 f1=0.3462
Restored best weights for fold 2 (F1=0.3502)

========== Fold 3 ==========

Epoch 1/15


    t_loss=2.1948 | F1(macro)=0.3237 | Acc=0.3355


Confusion matrix:
 [[ 0 14 12 15]
 [ 1 12  6 12]
 [ 0  4  8 18]
 [ 0  5  3  6]]
Train  loss=2.1948 acc=0.3355 f1=0.3237 | Val loss=2.6826 acc=0.2241 f1=0.2049
  🔥 New best F1: 0.2049 – model saved.

Epoch 2/15


    t_loss=1.6225 | F1(macro)=0.3409 | Acc=0.3613


Confusion matrix:
 [[ 5  5 11 20]
 [ 5  4  9 13]
 [ 4  4  5 17]
 [ 2  0  2 10]]
Train  loss=1.6225 acc=0.3613 f1=0.3409 | Val loss=2.0473 acc=0.2069 f1=0.2007

Epoch 3/15


    t_loss=1.4992 | F1(macro)=0.3743 | Acc=0.3806


Confusion matrix:
 [[10  8  8 15]
 [ 8  8  4 11]
 [ 5  6  6 13]
 [ 3  1  4  6]]
Train  loss=1.4992 acc=0.3806 f1=0.3743 | Val loss=1.9205 acc=0.2586 f1=0.2572
  🔥 New best F1: 0.2572 – model saved.

Epoch 4/15


    t_loss=1.3459 | F1(macro)=0.4260 | Acc=0.4323


Confusion matrix:
 [[19  9  2 11]
 [13 10  4  4]
 [11  6  5  8]
 [ 4  2  3  5]]
Train  loss=1.3459 acc=0.4323 f1=0.4260 | Val loss=1.8212 acc=0.3362 f1=0.3105
  🔥 New best F1: 0.3105 – model saved.

Epoch 5/15


    t_loss=1.2322 | F1(macro)=0.4686 | Acc=0.4860


Confusion matrix:
 [[ 8 12  8 13]
 [ 4 10  9  8]
 [ 3  5 10 12]
 [ 3  3  2  6]]
Train  loss=1.2322 acc=0.4860 f1=0.4686 | Val loss=1.9166 acc=0.2931 f1=0.2911

Epoch 6/15


    t_loss=1.1728 | F1(macro)=0.4943 | Acc=0.5097


Confusion matrix:
 [[ 6  9 16 10]
 [ 5  9 12  5]
 [ 7  4 12  7]
 [ 3  2  4  5]]
Train  loss=1.1728 acc=0.5097 f1=0.4943 | Val loss=1.9705 acc=0.2759 f1=0.2723

Epoch 7/15


    t_loss=1.0670 | F1(macro)=0.5310 | Acc=0.5419


Confusion matrix:
 [[16  8  8  9]
 [12  9  6  4]
 [14  3  7  6]
 [ 7  0  1  6]]
Train  loss=1.0670 acc=0.5419 f1=0.5310 | Val loss=1.9172 acc=0.3276 f1=0.3214
  🔥 New best F1: 0.3214 – model saved.

Epoch 8/15


    t_loss=1.0732 | F1(macro)=0.5409 | Acc=0.5548


Confusion matrix:
 [[12  7  9 13]
 [ 7 12  6  6]
 [ 8  6  7  9]
 [ 2  1  4  7]]
Train  loss=1.0732 acc=0.5548 f1=0.5409 | Val loss=1.9365 acc=0.3276 f1=0.3249
  🔥 New best F1: 0.3249 – model saved.

Epoch 9/15


    t_loss=1.0669 | F1(macro)=0.5954 | Acc=0.5957


Confusion matrix:
 [[ 5 12 14 10]
 [ 8 12  9  2]
 [ 5  8 12  5]
 [ 2  4  4  4]]
Train  loss=1.0669 acc=0.5957 f1=0.5954 | Val loss=2.0198 acc=0.2845 f1=0.2746

Epoch 10/15


    t_loss=1.0338 | F1(macro)=0.6212 | Acc=0.6215


Confusion matrix:
 [[12 10  7 12]
 [ 6 10 10  5]
 [ 7  5 11  7]
 [ 3  1  5  5]]
Train  loss=1.0338 acc=0.6215 f1=0.6212 | Val loss=1.7885 acc=0.3276 f1=0.3201

Epoch 11/15


    t_loss=0.9798 | F1(macro)=0.5976 | Acc=0.6043


Confusion matrix:
 [[11 11  8 11]
 [ 8  8 10  5]
 [ 7  3 10 10]
 [ 4  1  3  6]]
Train  loss=0.9798 acc=0.6043 f1=0.5976 | Val loss=1.7800 acc=0.3017 f1=0.2987

Epoch 12/15


    t_loss=0.8935 | F1(macro)=0.6259 | Acc=0.6495


Confusion matrix:
 [[13 12  5 11]
 [ 8 13  7  3]
 [ 9  6  5 10]
 [ 3  1  3  7]]
Train  loss=0.8935 acc=0.6495 f1=0.6259 | Val loss=1.7224 acc=0.3276 f1=0.3188

Epoch 13/15


    t_loss=0.8889 | F1(macro)=0.6344 | Acc=0.6495


Confusion matrix:
 [[14 11  4 12]
 [12 13  4  2]
 [13  6  2  9]
 [ 4  3  2  5]]
Train  loss=0.8889 acc=0.6495 f1=0.6344 | Val loss=1.7849 acc=0.2931 f1=0.2682

Epoch 14/15


    t_loss=0.9119 | F1(macro)=0.6361 | Acc=0.6495


Confusion matrix:
 [[11 13  7 10]
 [ 9 14  5  3]
 [ 8  4  9  9]
 [ 3  1  4  6]]
Train  loss=0.9119 acc=0.6495 f1=0.6361 | Val loss=1.7000 acc=0.3448 f1=0.3407
  🔥 New best F1: 0.3407 – model saved.

Epoch 15/15


    t_loss=0.9217 | F1(macro)=0.6287 | Acc=0.6301


Confusion matrix:
 [[16 12  3 10]
 [11 12  6  2]
 [11  4  8  7]
 [ 4  0  4  6]]
Train  loss=0.9217 acc=0.6301 f1=0.6287 | Val loss=1.7288 acc=0.3621 f1=0.3534
  🔥 New best F1: 0.3534 – model saved.
Restored best weights for fold 3 (F1=0.3534)

========== Fold 4 ==========

Epoch 1/15


    t_loss=2.2546 | F1(macro)=0.3168 | Acc=0.3247


Confusion matrix:
 [[ 7 11 19  4]
 [ 4 11 13  4]
 [ 5  5 10 10]
 [ 1  4  5  3]]
Train  loss=2.2546 acc=0.3247 f1=0.3168 | Val loss=2.3951 acc=0.2672 f1=0.2567
  🔥 New best F1: 0.2567 – model saved.

Epoch 2/15


    t_loss=1.6424 | F1(macro)=0.3563 | Acc=0.3699


Confusion matrix:
 [[ 2 19 12  8]
 [ 5 10 10  7]
 [ 5  5 10 10]
 [ 0  2  6  5]]
Train  loss=1.6424 acc=0.3699 f1=0.3563 | Val loss=2.1996 acc=0.2328 f1=0.2241

Epoch 3/15


    t_loss=1.4083 | F1(macro)=0.4333 | Acc=0.4559


Confusion matrix:
 [[ 2  9 16 14]
 [ 1 11 13  7]
 [ 1  8 13  8]
 [ 0  3  4  6]]
Train  loss=1.4083 acc=0.4559 f1=0.4333 | Val loss=2.1653 acc=0.2759 f1=0.2576
  🔥 New best F1: 0.2576 – model saved.

Epoch 4/15


    t_loss=1.4681 | F1(macro)=0.3868 | Acc=0.3957


Confusion matrix:
 [[19  4  5 13]
 [19  5  2  6]
 [12  3  6  9]
 [ 3  2  3  5]]
Train  loss=1.4681 acc=0.3957 f1=0.3868 | Val loss=1.8842 acc=0.3017 f1=0.2750
  🔥 New best F1: 0.2750 – model saved.

Epoch 5/15


    t_loss=1.1739 | F1(macro)=0.4801 | Acc=0.4946


Confusion matrix:
 [[10 11  9 11]
 [13  8  4  7]
 [ 5  4  9 12]
 [ 2  2  5  4]]
Train  loss=1.1739 acc=0.4946 f1=0.4801 | Val loss=1.7947 acc=0.2672 f1=0.2621

Epoch 6/15


    t_loss=1.1075 | F1(macro)=0.5170 | Acc=0.5333


Confusion matrix:
 [[ 6  3 20 12]
 [ 5  3 15  9]
 [ 2  4 15  9]
 [ 3  1  6  3]]
Train  loss=1.1075 acc=0.5333 f1=0.5170 | Val loss=2.0362 acc=0.2328 f1=0.2073

Epoch 7/15


    t_loss=1.1621 | F1(macro)=0.5259 | Acc=0.5419


Confusion matrix:
 [[ 2  8 21 10]
 [ 5  9 15  3]
 [ 3  7 16  4]
 [ 1  1  9  2]]
Train  loss=1.1621 acc=0.5419 f1=0.5259 | Val loss=1.9549 acc=0.2500 f1=0.2173

Epoch 8/15


    t_loss=1.0692 | F1(macro)=0.5628 | Acc=0.5699


Confusion matrix:
 [[ 4  4 13 20]
 [ 8  5 10  9]
 [ 6  5 10  9]
 [ 1  0  6  6]]
Train  loss=1.0692 acc=0.5699 f1=0.5628 | Val loss=2.2508 acc=0.2155 f1=0.2128

Epoch 9/15


    t_loss=1.0086 | F1(macro)=0.6043 | Acc=0.6129


Confusion matrix:
 [[ 7  5 20  9]
 [12  6 10  4]
 [ 7  6 16  1]
 [ 2  1  8  2]]
Train  loss=1.0086 acc=0.6129 f1=0.6043 | Val loss=2.1726 acc=0.2672 f1=0.2404

Epoch 10/15


    t_loss=0.9691 | F1(macro)=0.5516 | Acc=0.5699


Confusion matrix:
 [[ 3  2 28  8]
 [ 9  3 14  6]
 [ 6  5 16  3]
 [ 1  1  7  4]]
Train  loss=0.9691 acc=0.5699 f1=0.5516 | Val loss=2.2079 acc=0.2241 f1=0.2029

Epoch 11/15


    t_loss=0.9488 | F1(macro)=0.6070 | Acc=0.6129


Confusion matrix:
 [[13  4 11 13]
 [11  4  8  9]
 [ 9  6  9  6]
 [ 2  2  4  5]]
Train  loss=0.9488 acc=0.6129 f1=0.6070 | Val loss=1.9630 acc=0.2672 f1=0.2541

Epoch 12/15


    t_loss=0.8442 | F1(macro)=0.6746 | Acc=0.6882


Confusion matrix:
 [[ 8  5 20  8]
 [12  7 10  3]
 [ 8  7 14  1]
 [ 1  2  7  3]]
Train  loss=0.8442 acc=0.6882 f1=0.6746 | Val loss=2.0718 acc=0.2759 f1=0.2632

Epoch 13/15


    t_loss=0.8833 | F1(macro)=0.6708 | Acc=0.6796


Confusion matrix:
 [[10  3 22  6]
 [13  7  6  6]
 [ 8  4 14  4]
 [ 2  2  6  3]]
Train  loss=0.8833 acc=0.6796 f1=0.6708 | Val loss=2.0444 acc=0.2931 f1=0.2771
  🔥 New best F1: 0.2771 – model saved.

Epoch 14/15


    t_loss=0.8995 | F1(macro)=0.6575 | Acc=0.6667


Confusion matrix:
 [[ 9  7 16  9]
 [12  9  7  4]
 [ 8  8 12  2]
 [ 2  1  5  5]]
Train  loss=0.8995 acc=0.6667 f1=0.6575 | Val loss=2.0175 acc=0.3017 f1=0.3029
  🔥 New best F1: 0.3029 – model saved.

Epoch 15/15


    t_loss=0.9251 | F1(macro)=0.6289 | Acc=0.6366


Confusion matrix:
 [[13  3 14 11]
 [14  8  5  5]
 [11  7 10  2]
 [ 3  1  5  4]]
Train  loss=0.9251 acc=0.6366 f1=0.6289 | Val loss=2.0034 acc=0.3017 f1=0.2930
Restored best weights for fold 4 (F1=0.3029)


# tf_efficientnetv2_s.in21k

In [6]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [7]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [8]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

FOLD_VAL_F1 = f"fold_val_f1_{prefix_filename}.json"

# Save best F1 per fold to JSON
with open(FOLD_VAL_F1, "w") as f:
    json.dump(best_f1_per_fold, f, indent=2)

# test_dataset = HistologyDataset(
#     df=test_df,
#     image_size=IMAGE_SIZE,
#     is_train=False,   # returns (img, sample_index)
#     use_mask_crop=True
# )
#
# test_loader = DataLoader(
#     test_dataset,
#     batch_size=BATCH_SIZE,
#     shuffle=False,
#     num_workers=N_WORKERS,
#     pin_memory=cuda_is_available
# )
#
# all_fold_probs = []   # list of arrays [N, num_classes]
# all_sample_indices = None
#
# for fold in range(N_FOLDS):
#     print(f"Inference with fold {fold} model")
#
#     # recreate model and load weights
#     if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
#         model = create_model_tf_efficientnetv2_s(pretrained=False)
#     elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
#         model = create_model_convnext(pretrained=False)
#     else:
#         model = create_efficientnet_b0_model(pretrained=False)
#     state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
#     model.load_state_dict(state)
#     model.eval()
#
#     fold_probs = []
#     sample_indices_list = []
#
#     with torch.no_grad():
#         for imgs, sample_indices in test_loader:
#             imgs = imgs.to(device, non_blocking=True)
#
#             logits = model(imgs)               # [B, num_classes]
#             probs = softmax(logits, dim=1)     # [B, num_classes]
#             fold_probs.append(probs.cpu().numpy())
#
#             # collect sample indices only once
#             if all_sample_indices is None:
#                 sample_indices_list.extend(sample_indices)
#
#     fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
#     all_fold_probs.append(fold_probs)
#
#     if all_sample_indices is None:
#         all_sample_indices = sample_indices_list
#
# # average probabilities across folds
# mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
# pred_indices = mean_probs.argmax(axis=1)
#
# pred_labels = [idx2label[int(i)] for i in pred_indices]
# sample_index_with_ext = [
#     f"{si}.png" if not si.endswith(".png") else si
#     for si in all_sample_indices
# ]
#
# submission_df = pd.DataFrame({
#     "sample_index": sample_index_with_ext,
#     "label": pred_labels
# })
#
# submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
# print("Saved submission_5fold_no_tta.csv")
# print(submission_df.head())


In [9]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # deterministic, returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=1,               # per-image TTA
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

if os.path.exists(FOLD_VAL_F1):
    with open(FOLD_VAL_F1, "r") as f:
        best_f1_per_fold = json.load(f)
    val_f1_per_fold = np.array([best_f1_per_fold[str(k)] for k in range(N_FOLDS)])
    # Normalize to get weights that sum to 1
    fold_weights = val_f1_per_fold / val_f1_per_fold.sum()
else:
    # fallback: uniform weights if metrics are missing
    print('Warning: fold validation F1 scores not found, using uniform weights.')
    fold_weights = np.ones(N_FOLDS, dtype=np.float32) / N_FOLDS

print("Fold weights:", fold_weights)

# -----------------------------
# 2) Accumulate weighted probs
# -----------------------------
all_probs = None
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model (weight={fold_weights[fold]:.3f})")

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)

    state_dict = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            # img_tensor: [1, 4, H, W]  (RGB+mask)
            img_tensor = img_tensor.squeeze(0).to(device)  # [4, H, W]

            # -------- TTA: apply multiple augmented views [4xHxW] --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1, 4, H, W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1, N_CLASSES]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)  # [N_CLASSES]
            fold_probs.append(avg_probs)

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N_test, N_CLASSES]

    # initialize global probs
    if all_probs is None:
        all_probs = np.zeros_like(fold_probs, dtype=np.float32)

     # weighted accumulation
    all_probs += fold_weights[fold] * fold_probs

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# -----------------------------
# 3) Final predictions
# -----------------------------
pred_indices = all_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print(f"Saved submission_5fold_tta_{prefix_filename}.csv")

Fold weights: [0.24045656 0.1686367  0.20559124 0.20748547 0.17783002]
Inference with fold 0 model (weight=0.240)
Inference with fold 1 model (weight=0.169)
Inference with fold 2 model (weight=0.206)
Inference with fold 3 model (weight=0.207)
Inference with fold 4 model (weight=0.178)
Saved submission_5fold_tta_effb0.csv


In [10]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.34220711198313625
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.2453332980129777
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.33040540540540536
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.2578139114724481
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.26517273576097106
Mean OOF F1: 0.28818649252698764
