In [3]:
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.persistence_manager import PersistenceManager
from notebooks.internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [4]:
N_FOLDS = data.num_K_folds
IMAGE_SIZE = data.image_size
BATCH_SIZE = 4
PRETRAINED_MODEL = "tf_efficientnetv2_s.in21k"
N_CLASSES = 4 # number of classes in the dataset (labels)
N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4

for fold in range(N_FOLDS):
    print(f"\n========== Fold {fold} ==========")

    train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
    val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

    train_dataset = HistologyDataset(train_df_split, transforms=train_transforms, is_train=True, image_size=IMAGE_SIZE)
    val_dataset   = HistologyDataset(val_df_split,   transforms=val_test_transforms, is_train=True, image_size=IMAGE_SIZE)

    sampler = make_weighted_sampler(train_df_split)
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        sampler=sampler,
        num_workers=N_WORKERS,
        pin_memory=cuda_is_available
    )
    val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE,
                              shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

    # --- create fresh model for this fold ---
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=True,
        num_classes=N_CLASSES
    ).to(device)

    # --- Stage 1: freeze backbone, train classifier head ---
    print("\n--- Stage 1: Training classifier head ---")

    # --- 1.1. freeze feature extractor layers ---
    for param in model.parameters():
        param.requires_grad = False

    # 2) unfreeze classifier head (EffNetV2 uses .classifier)
    for param in model.classifier.parameters():
        param.requires_grad = True

    # --- 1.2. define loss, optimizer, scheduler ---
    criterion = nn.CrossEntropyLoss()
    head_params = [p for p in model.parameters() if p.requires_grad]
    optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=10
    )

    # --- 1.3. train for several epochs ---
    EPOCHS = 8
    best_f1 = 0.0
    best_state = None
    for epoch in range(1, EPOCHS+1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_loss, train_acc, train_f1 = train_one_epoch(
            model, train_loader, optimizer, criterion, device
        )
        val_loss, val_acc, val_f1 = validate(
            model, val_loader, criterion, device
        )
        scheduler.step()
        print(
            f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
            f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
        )
        if val_f1 > best_f1:
            best_f1 = val_f1
            best_state = model.state_dict().copy()
            torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
            print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

    # --- Stage 2: unfreeze whole model, fine-tune ---
    print("\n--- Stage 2: Fine-tuning entire model ---")

    # --- 2.1. unfreeze entire model ---
    for param in model.parameters():
        param.requires_grad = True

    # --- 2.2. define loss, optimizer, scheduler ---
    optimizer = AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=15
    )

    # --- 2.3. mild class weights ---
    class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
    class_weights = (class_counts.sum() / class_counts)
    class_weights = class_weights / class_weights.mean()
    # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

    # --- 2.4. train for several epochs ---
    EPOCHS = 15
    best_f1 = 0.0
    best_state = None

    for epoch in range(1, EPOCHS + 1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_loss, train_acc, train_f1 = train_one_epoch(
            model, train_loader, optimizer, criterion, device
        )
        val_loss, val_acc, val_f1 = validate(
            model, val_loader, criterion, device
        )
        scheduler.step()
        print(
            f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
            f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
        )
        if val_f1 > best_f1:
            best_f1 = val_f1
            best_state = model.state_dict().copy()
            torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
            print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

    # --- save model for this fold ---
    torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.5071 | F1(macro)=0.2355 | Acc=0.2356


Confusion matrix:
 [[28  4  8 49]
 [28 11  4 40]
 [22 11  6 40]
 [ 8  1  2 21]]
Train  loss=4.5071 acc=0.2356 f1=0.2355 | Val loss=6.7114 acc=0.2332 f1=0.2180
  🔥 New best F1: 0.2180 – model saved.

Epoch 2/8


    t_loss=3.2626 | F1(macro)=0.3056 | Acc=0.3065


Confusion matrix:
 [[17  5  8 59]
 [21 18  7 37]
 [16 10  9 44]
 [ 3  1  2 26]]
Train  loss=3.2626 acc=0.3065 f1=0.3056 | Val loss=6.5027 acc=0.2473 f1=0.2437
  🔥 New best F1: 0.2437 – model saved.

Epoch 3/8


    t_loss=3.1706 | F1(macro)=0.2989 | Acc=0.2994


Confusion matrix:
 [[28  9 14 38]
 [26 13 16 28]
 [22  7 20 30]
 [ 8  1  6 17]]
Train  loss=3.1706 acc=0.2994 f1=0.2989 | Val loss=5.8696 acc=0.2756 f1=0.2711
  🔥 New best F1: 0.2711 – model saved.

Epoch 4/8


    t_loss=2.9551 | F1(macro)=0.3182 | Acc=0.3198


Confusion matrix:
 [[22  8 18 41]
 [19 13 15 36]
 [12  5 25 37]
 [ 3  2  6 21]]
Train  loss=2.9551 acc=0.3198 f1=0.3182 | Val loss=5.2521 acc=0.2862 f1=0.2847
  🔥 New best F1: 0.2847 – model saved.

Epoch 5/8


    t_loss=2.7678 | F1(macro)=0.3058 | Acc=0.3065


Confusion matrix:
 [[37  3 32 17]
 [30 15 27 11]
 [30 10 30  9]
 [ 8  1 14  9]]
Train  loss=2.7678 acc=0.3065 f1=0.3058 | Val loss=5.3736 acc=0.3216 f1=0.3024
  🔥 New best F1: 0.3024 – model saved.

Epoch 6/8


    t_loss=2.7636 | F1(macro)=0.3416 | Acc=0.3419


Confusion matrix:
 [[23  6 13 47]
 [23 14  9 37]
 [18 11 12 38]
 [ 5  0  7 20]]
Train  loss=2.7636 acc=0.3419 f1=0.3416 | Val loss=6.2946 acc=0.2438 f1=0.2417

Epoch 7/8


    t_loss=2.7269 | F1(macro)=0.3068 | Acc=0.3091


Confusion matrix:
 [[15  9 23 42]
 [19 14 17 33]
 [12  9 26 32]
 [ 4  1  9 18]]
Train  loss=2.7269 acc=0.3091 f1=0.3068 | Val loss=5.1708 acc=0.2580 f1=0.2560

Epoch 8/8


    t_loss=2.7065 | F1(macro)=0.2880 | Acc=0.2888


Confusion matrix:
 [[26  7 31 25]
 [22 13 25 23]
 [21 11 25 22]
 [ 5  1 14 12]]
Train  loss=2.7065 acc=0.2888 f1=0.2880 | Val loss=5.0955 acc=0.2686 f1=0.2607

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.6438 | F1(macro)=0.3185 | Acc=0.3224


Confusion matrix:
 [[20  6 14 49]
 [24 11 11 37]
 [14  8 18 39]
 [ 5  4  8 15]]
Train  loss=2.6438 acc=0.3224 f1=0.3185 | Val loss=3.4683 acc=0.2261 f1=0.2277
  🔥 New best F1: 0.2277 – model saved.

Epoch 2/15


    t_loss=1.7498 | F1(macro)=0.3530 | Acc=0.3623


Confusion matrix:
 [[21  6  1 61]
 [24 15  6 38]
 [24  2 10 43]
 [ 5  5  0 22]]
Train  loss=1.7498 acc=0.3623 f1=0.3530 | Val loss=2.5300 acc=0.2403 f1=0.2402
  🔥 New best F1: 0.2402 – model saved.

Epoch 3/15


    t_loss=1.4434 | F1(macro)=0.3483 | Acc=0.3729


Confusion matrix:
 [[35  3  3 48]
 [26 10  5 42]
 [24  4  9 42]
 [10  1  1 20]]
Train  loss=1.4434 acc=0.3729 f1=0.3483 | Val loss=2.1000 acc=0.2615 f1=0.2454
  🔥 New best F1: 0.2454 – model saved.

Epoch 4/15


    t_loss=1.3514 | F1(macro)=0.3749 | Acc=0.3888


Confusion matrix:
 [[ 3  8  1 77]
 [ 1 15  1 66]
 [ 5  6 11 57]
 [ 0  3  0 29]]
Train  loss=1.3514 acc=0.3888 f1=0.3749 | Val loss=2.1256 acc=0.2049 f1=0.1959

Epoch 5/15


    t_loss=1.2595 | F1(macro)=0.4106 | Acc=0.4305


Confusion matrix:
 [[35  2  8 44]
 [27 10  8 38]
 [22  3 12 42]
 [ 8  3  0 21]]
Train  loss=1.2595 acc=0.4305 f1=0.4106 | Val loss=1.8349 acc=0.2756 f1=0.2616
  🔥 New best F1: 0.2616 – model saved.

Epoch 6/15


    t_loss=1.2766 | F1(macro)=0.4058 | Acc=0.4181


Confusion matrix:
 [[25  7 16 41]
 [27 14 15 27]
 [22  2 21 34]
 [ 7  2  9 14]]
Train  loss=1.2766 acc=0.4181 f1=0.4058 | Val loss=1.7138 acc=0.2615 f1=0.2606

Epoch 7/15


    t_loss=1.1961 | F1(macro)=0.4478 | Acc=0.4659


Confusion matrix:
 [[32  7  4 46]
 [23 16  5 39]
 [20  6 14 39]
 [11  3  0 18]]
Train  loss=1.1961 acc=0.4659 f1=0.4478 | Val loss=1.7554 acc=0.2827 f1=0.2813
  🔥 New best F1: 0.2813 – model saved.

Epoch 8/15


    t_loss=1.1587 | F1(macro)=0.4486 | Acc=0.4659


Confusion matrix:
 [[10  8 12 59]
 [ 6 18 12 47]
 [12  5 16 46]
 [ 2  3  2 25]]
Train  loss=1.1587 acc=0.4659 f1=0.4486 | Val loss=1.7530 acc=0.2438 f1=0.2449

Epoch 9/15


    t_loss=1.0989 | F1(macro)=0.4917 | Acc=0.5084


Confusion matrix:
 [[13 17  2 57]
 [ 7 24  0 52]
 [ 8  7 10 54]
 [ 1  4  0 27]]
Train  loss=1.0989 acc=0.5084 f1=0.4917 | Val loss=1.9307 acc=0.2615 f1=0.2597

Epoch 10/15


    t_loss=1.0404 | F1(macro)=0.5213 | Acc=0.5421


Confusion matrix:
 [[12 30  8 39]
 [10 40  5 28]
 [ 6 22 15 36]
 [ 4 10  2 16]]
Train  loss=1.0404 acc=0.5421 f1=0.5213 | Val loss=1.6895 acc=0.2933 f1=0.2795

Epoch 11/15


    t_loss=1.0887 | F1(macro)=0.4968 | Acc=0.5093


Confusion matrix:
 [[13 25  7 44]
 [10 31  6 36]
 [ 8 23 12 36]
 [ 5  6  1 20]]
Train  loss=1.0887 acc=0.5093 f1=0.4968 | Val loss=1.6752 acc=0.2686 f1=0.2609

Epoch 12/15


    t_loss=1.0214 | F1(macro)=0.5264 | Acc=0.5474


Confusion matrix:
 [[21 10 29 29]
 [17 23 16 27]
 [15  6 25 33]
 [ 6  5  7 14]]
Train  loss=1.0214 acc=0.5474 f1=0.5264 | Val loss=1.6652 acc=0.2933 f1=0.2935
  🔥 New best F1: 0.2935 – model saved.

Epoch 13/15


    t_loss=1.0091 | F1(macro)=0.5725 | Acc=0.5855


Confusion matrix:
 [[31 17 12 29]
 [18 24 10 31]
 [21 20 16 22]
 [ 8  5  4 15]]
Train  loss=1.0091 acc=0.5855 f1=0.5725 | Val loss=1.6456 acc=0.3039 f1=0.2976
  🔥 New best F1: 0.2976 – model saved.

Epoch 14/15


    t_loss=0.9430 | F1(macro)=0.5950 | Acc=0.6129


Confusion matrix:
 [[22 15 11 41]
 [14 26  7 36]
 [17 15 14 33]
 [ 5  5  3 19]]
Train  loss=0.9430 acc=0.6129 f1=0.5950 | Val loss=1.7288 acc=0.2862 f1=0.2855

Epoch 15/15


    t_loss=0.9617 | F1(macro)=0.5773 | Acc=0.5908


Confusion matrix:
 [[15 13 11 50]
 [10 21  8 44]
 [14  9 17 39]
 [ 6  3  3 20]]
Train  loss=0.9617 acc=0.5908 f1=0.5773 | Val loss=1.7333 acc=0.2580 f1=0.2635

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.0625 | F1(macro)=0.2795 | Acc=0.2808


Confusion matrix:
 [[ 2 61 14 12]
 [ 1 58 16  8]
 [ 2 53 16  9]
 [ 0 28  1  2]]
Train  loss=4.0625 acc=0.2808 f1=0.2795 | Val loss=6.6952 acc=0.2756 f1=0.1922
  🔥 New best F1: 0.1922 – model saved.

Epoch 2/8


    t_loss=3.4012 | F1(macro)=0.2798 | Acc=0.2808


Confusion matrix:
 [[ 6 35 39  9]
 [ 3 31 35 14]
 [ 3 29 38 10]
 [ 2 11 11  7]]
Train  loss=3.4012 acc=0.2808 f1=0.2798 | Val loss=5.4000 acc=0.2898 f1=0.2540
  🔥 New best F1: 0.2540 – model saved.

Epoch 3/8


    t_loss=3.2784 | F1(macro)=0.2645 | Acc=0.2657


Confusion matrix:
 [[ 4 48 27 10]
 [ 8 29 31 15]
 [ 1 33 35 11]
 [ 1 14 11  5]]
Train  loss=3.2784 acc=0.2657 f1=0.2645 | Val loss=5.4088 acc=0.2580 f1=0.2193

Epoch 4/8


    t_loss=2.8911 | F1(macro)=0.2965 | Acc=0.2958


Confusion matrix:
 [[ 4 46 15 24]
 [ 5 41 18 19]
 [ 4 52 13 11]
 [ 2 19  3  7]]
Train  loss=2.8911 acc=0.2958 f1=0.2965 | Val loss=5.2883 acc=0.2297 f1=0.1927

Epoch 5/8


    t_loss=2.7591 | F1(macro)=0.2994 | Acc=0.2994


Confusion matrix:
 [[ 6 44 25 14]
 [ 3 26 39 15]
 [ 4 29 37 10]
 [ 7 14  6  4]]
Train  loss=2.7591 acc=0.2994 f1=0.2994 | Val loss=5.2634 acc=0.2580 f1=0.2198

Epoch 6/8


    t_loss=2.7856 | F1(macro)=0.3115 | Acc=0.3118


Confusion matrix:
 [[ 8 59 15  7]
 [10 44 23  6]
 [ 7 49 22  2]
 [ 4 21  4  2]]
Train  loss=2.7856 acc=0.3118 f1=0.3115 | Val loss=5.2390 acc=0.2686 f1=0.2171

Epoch 7/8


    t_loss=2.7152 | F1(macro)=0.2905 | Acc=0.2941


Confusion matrix:
 [[ 7 28 21 33]
 [ 9 26 24 24]
 [ 6 23 30 21]
 [ 3  8  6 14]]
Train  loss=2.7152 acc=0.2941 f1=0.2905 | Val loss=4.5672 acc=0.2721 f1=0.2582
  🔥 New best F1: 0.2582 – model saved.

Epoch 8/8


    t_loss=2.6760 | F1(macro)=0.3045 | Acc=0.3065


Confusion matrix:
 [[ 8 33 20 28]
 [10 19 35 19]
 [ 6 23 34 17]
 [ 3 10  7 11]]
Train  loss=2.6760 acc=0.3065 f1=0.3045 | Val loss=4.8887 acc=0.2544 f1=0.2395

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.4945 | F1(macro)=0.2996 | Acc=0.3065


Confusion matrix:
 [[ 8 48  1 32]
 [ 6 40 15 22]
 [ 2 41 14 23]
 [ 1 19  1 10]]
Train  loss=2.4945 acc=0.3065 f1=0.2996 | Val loss=3.0262 acc=0.2544 f1=0.2298
  🔥 New best F1: 0.2298 – model saved.

Epoch 2/15


    t_loss=1.6070 | F1(macro)=0.3431 | Acc=0.3587


Confusion matrix:
 [[13 58  0 18]
 [17 40 17  9]
 [16 38 14 12]
 [ 5 23  0  3]]
Train  loss=1.6070 acc=0.3587 f1=0.3431 | Val loss=2.7018 acc=0.2473 f1=0.2127

Epoch 3/15


    t_loss=1.4044 | F1(macro)=0.3730 | Acc=0.3818


Confusion matrix:
 [[25 33  0 31]
 [20 32  2 29]
 [15 28  9 28]
 [ 8 13  0 10]]
Train  loss=1.4044 acc=0.3818 f1=0.3730 | Val loss=1.9487 acc=0.2686 f1=0.2525
  🔥 New best F1: 0.2525 – model saved.

Epoch 4/15


    t_loss=1.3107 | F1(macro)=0.3804 | Acc=0.4012


Confusion matrix:
 [[34 33  1 21]
 [26 37  4 16]
 [29 24  8 19]
 [12 13  0  6]]
Train  loss=1.3107 acc=0.4012 f1=0.3804 | Val loss=1.8284 acc=0.3004 f1=0.2621
  🔥 New best F1: 0.2621 – model saved.

Epoch 5/15


    t_loss=1.2888 | F1(macro)=0.3968 | Acc=0.4101


Confusion matrix:
 [[49 12  4 24]
 [38 21  4 20]
 [38  8  9 25]
 [16  1  2 12]]
Train  loss=1.2888 acc=0.4101 f1=0.3968 | Val loss=1.7724 acc=0.3216 f1=0.2895
  🔥 New best F1: 0.2895 – model saved.

Epoch 6/15


    t_loss=1.2307 | F1(macro)=0.4025 | Acc=0.4207


Confusion matrix:
 [[41 28  1 19]
 [34 34  4 11]
 [33 19 11 17]
 [15  8  0  8]]
Train  loss=1.2307 acc=0.4207 f1=0.4025 | Val loss=1.7530 acc=0.3322 f1=0.2993
  🔥 New best F1: 0.2993 – model saved.

Epoch 7/15


    t_loss=1.1952 | F1(macro)=0.3889 | Acc=0.4225


Confusion matrix:
 [[10 55  3 21]
 [16 46 10 11]
 [14 34 14 18]
 [ 5 19  0  7]]
Train  loss=1.1952 acc=0.4225 f1=0.3889 | Val loss=1.7414 acc=0.2721 f1=0.2396

Epoch 8/15


    t_loss=1.2068 | F1(macro)=0.4487 | Acc=0.4632


Confusion matrix:
 [[27 10  2 50]
 [18 19 11 35]
 [20  6 17 37]
 [10  2  3 16]]
Train  loss=1.2068 acc=0.4632 f1=0.4487 | Val loss=1.6442 acc=0.2792 f1=0.2840

Epoch 9/15


    t_loss=1.1116 | F1(macro)=0.4594 | Acc=0.4872


Confusion matrix:
 [[32 25  1 31]
 [23 23  8 29]
 [15 17 21 27]
 [11  8  0 12]]
Train  loss=1.1116 acc=0.4872 f1=0.4594 | Val loss=1.5638 acc=0.3110 f1=0.3094
  🔥 New best F1: 0.3094 – model saved.

Epoch 10/15


    t_loss=1.1107 | F1(macro)=0.4891 | Acc=0.4987


Confusion matrix:
 [[19 37 12 21]
 [14 35 21 13]
 [15 16 31 18]
 [ 4 11  8  8]]
Train  loss=1.1107 acc=0.4987 f1=0.4891 | Val loss=1.5852 acc=0.3286 f1=0.3095
  🔥 New best F1: 0.3095 – model saved.

Epoch 11/15


    t_loss=1.0808 | F1(macro)=0.4932 | Acc=0.5120


Confusion matrix:
 [[25 19  6 39]
 [29 20 10 24]
 [23 11 18 28]
 [13  4  1 13]]
Train  loss=1.0808 acc=0.5120 f1=0.4932 | Val loss=1.6513 acc=0.2686 f1=0.2692

Epoch 12/15


    t_loss=1.0236 | F1(macro)=0.5241 | Acc=0.5421


Confusion matrix:
 [[17 35  8 29]
 [17 44  7 15]
 [11 31 17 21]
 [ 8 10  2 11]]
Train  loss=1.0236 acc=0.5421 f1=0.5241 | Val loss=1.6476 acc=0.3145 f1=0.2942

Epoch 13/15


    t_loss=1.0757 | F1(macro)=0.5097 | Acc=0.5217


Confusion matrix:
 [[20 41  2 26]
 [19 50  4 10]
 [21 22 15 22]
 [ 9 11  1 10]]
Train  loss=1.0757 acc=0.5217 f1=0.5097 | Val loss=1.6137 acc=0.3357 f1=0.3081

Epoch 14/15


    t_loss=1.0300 | F1(macro)=0.5284 | Acc=0.5438


Confusion matrix:
 [[31 28  3 27]
 [20 41  5 17]
 [19 20 16 25]
 [13  5  1 12]]
Train  loss=1.0300 acc=0.5438 f1=0.5284 | Val loss=1.6240 acc=0.3534 f1=0.3357
  🔥 New best F1: 0.3357 – model saved.

Epoch 15/15


    t_loss=0.9552 | F1(macro)=0.5475 | Acc=0.5713


Confusion matrix:
 [[22 31  7 29]
 [22 39  9 13]
 [19 17 20 24]
 [11  8  2 10]]
Train  loss=0.9552 acc=0.5713 f1=0.5475 | Val loss=1.6287 acc=0.3216 f1=0.3085

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.5648 | F1(macro)=0.2540 | Acc=0.2549


Confusion matrix:
 [[30  7 27 25]
 [24 23 16 19]
 [32 13 12 23]
 [15  4  8  4]]
Train  loss=4.5648 acc=0.2549 f1=0.2540 | Val loss=6.1206 acc=0.2447 f1=0.2297
  🔥 New best F1: 0.2297 – model saved.

Epoch 2/8


    t_loss=3.5166 | F1(macro)=0.2543 | Acc=0.2558


Confusion matrix:
 [[31  4 23 31]
 [22 22  6 32]
 [30 17 13 20]
 [12  3 11  5]]
Train  loss=3.5166 acc=0.2558 f1=0.2543 | Val loss=5.8154 acc=0.2518 f1=0.2401
  🔥 New best F1: 0.2401 – model saved.

Epoch 3/8


    t_loss=3.3593 | F1(macro)=0.2584 | Acc=0.2584


Confusion matrix:
 [[34  5 32 18]
 [20 20 18 24]
 [29 15 16 20]
 [16  4  6  5]]
Train  loss=3.3593 acc=0.2584 f1=0.2584 | Val loss=5.5410 acc=0.2660 f1=0.2479
  🔥 New best F1: 0.2479 – model saved.

Epoch 4/8


    t_loss=3.0644 | F1(macro)=0.2874 | Acc=0.2885


Confusion matrix:
 [[46  4 10 29]
 [31 12  8 31]
 [33 14  1 32]
 [18  1  4  8]]
Train  loss=3.0644 acc=0.2885 f1=0.2874 | Val loss=6.7914 acc=0.2376 f1=0.1945

Epoch 5/8


    t_loss=2.9106 | F1(macro)=0.3210 | Acc=0.3212


Confusion matrix:
 [[32  4 17 36]
 [24 18 10 30]
 [28 17  6 29]
 [14  4  4  9]]
Train  loss=2.9106 acc=0.3212 f1=0.3210 | Val loss=5.8451 acc=0.2305 f1=0.2165

Epoch 6/8


    t_loss=3.0452 | F1(macro)=0.2759 | Acc=0.2788


Confusion matrix:
 [[44  6 16 23]
 [29 26 11 16]
 [37 19  8 16]
 [21  3  2  5]]
Train  loss=3.0452 acc=0.2788 f1=0.2759 | Val loss=5.6714 acc=0.2943 f1=0.2572
  🔥 New best F1: 0.2572 – model saved.

Epoch 7/8


    t_loss=2.8260 | F1(macro)=0.2818 | Acc=0.2823


Confusion matrix:
 [[45  7 22 15]
 [32 25 11 14]
 [34 19 14 13]
 [22  2  5  2]]
Train  loss=2.8260 acc=0.2823 f1=0.2818 | Val loss=5.5385 acc=0.3050 f1=0.2603
  🔥 New best F1: 0.2603 – model saved.

Epoch 8/8


    t_loss=2.6414 | F1(macro)=0.2844 | Acc=0.2858


Confusion matrix:
 [[42  8 22 17]
 [28 26 10 18]
 [35 18  7 20]
 [16  8  2  5]]
Train  loss=2.6414 acc=0.2858 f1=0.2844 | Val loss=5.4310 acc=0.2837 f1=0.2479

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.6450 | F1(macro)=0.2888 | Acc=0.2947


Confusion matrix:
 [[28  7 20 34]
 [18 23 26 15]
 [14 22 20 24]
 [ 7  7  9  8]]
Train  loss=2.6450 acc=0.2947 f1=0.2888 | Val loss=2.4892 acc=0.2801 f1=0.2715
  🔥 New best F1: 0.2715 – model saved.

Epoch 2/15


    t_loss=1.7267 | F1(macro)=0.2976 | Acc=0.3062


Confusion matrix:
 [[21  4 35 29]
 [16 15 31 20]
 [14  3 34 29]
 [ 7  1 17  6]]
Train  loss=1.7267 acc=0.3062 f1=0.2976 | Val loss=2.1009 acc=0.2695 f1=0.2552

Epoch 3/15


    t_loss=1.5136 | F1(macro)=0.3248 | Acc=0.3398


Confusion matrix:
 [[38  4 33 14]
 [25 23 17 17]
 [19 17 23 21]
 [12  1  9  9]]
Train  loss=1.5136 acc=0.3398 f1=0.3248 | Val loss=1.9144 acc=0.3298 f1=0.3143
  🔥 New best F1: 0.3143 – model saved.

Epoch 4/15


    t_loss=1.3501 | F1(macro)=0.3584 | Acc=0.3735


Confusion matrix:
 [[ 9  3 58 19]
 [ 8 20 37 17]
 [ 3  5 51 21]
 [ 3  3 18  7]]
Train  loss=1.3501 acc=0.3735 f1=0.3584 | Val loss=1.8410 acc=0.3085 f1=0.2700

Epoch 5/15


    t_loss=1.2996 | F1(macro)=0.3680 | Acc=0.4027


Confusion matrix:
 [[14  9 42 24]
 [14 23 27 18]
 [ 9 16 31 24]
 [ 7  5  5 14]]
Train  loss=1.2996 acc=0.4027 f1=0.3680 | Val loss=1.5619 acc=0.2908 f1=0.2847

Epoch 6/15


    t_loss=1.2582 | F1(macro)=0.4044 | Acc=0.4283


Confusion matrix:
 [[29  4  4 52]
 [13 19  4 46]
 [13 16  8 43]
 [ 8  0  3 20]]
Train  loss=1.2582 acc=0.4283 f1=0.4044 | Val loss=1.6570 acc=0.2695 f1=0.2664

Epoch 7/15


    t_loss=1.2067 | F1(macro)=0.4326 | Acc=0.4540


Confusion matrix:
 [[32 11 13 33]
 [24 23 18 17]
 [15 12 21 32]
 [ 7  0  9 15]]
Train  loss=1.2067 acc=0.4540 f1=0.4326 | Val loss=1.5496 acc=0.3227 f1=0.3187
  🔥 New best F1: 0.3187 – model saved.

Epoch 8/15


    t_loss=1.1854 | F1(macro)=0.4280 | Acc=0.4487


Confusion matrix:
 [[26 19 17 27]
 [17 33 16 16]
 [14 16 31 19]
 [10  6  5 10]]
Train  loss=1.1854 acc=0.4487 f1=0.4280 | Val loss=1.5266 acc=0.3546 f1=0.3417
  🔥 New best F1: 0.3417 – model saved.

Epoch 9/15


    t_loss=1.1702 | F1(macro)=0.4431 | Acc=0.4558


Confusion matrix:
 [[62  5  9 13]
 [29 29  9 15]
 [32 14 16 18]
 [18  5  1  7]]
Train  loss=1.1702 acc=0.4558 f1=0.4431 | Val loss=1.6452 acc=0.4043 f1=0.3534
  🔥 New best F1: 0.3534 – model saved.

Epoch 10/15


    t_loss=1.1212 | F1(macro)=0.4461 | Acc=0.4673


Confusion matrix:
 [[25 10 28 26]
 [18 29 20 15]
 [ 8 12 29 31]
 [ 8  4  9 10]]
Train  loss=1.1212 acc=0.4673 f1=0.4461 | Val loss=1.6794 acc=0.3298 f1=0.3219

Epoch 11/15


    t_loss=1.0858 | F1(macro)=0.4960 | Acc=0.5080


Confusion matrix:
 [[34  5 29 21]
 [24 26 16 16]
 [15  8 35 22]
 [11  4  7  9]]
Train  loss=1.0858 acc=0.5080 f1=0.4960 | Val loss=1.6011 acc=0.3688 f1=0.3525

Epoch 12/15


    t_loss=1.0732 | F1(macro)=0.5119 | Acc=0.5265


Confusion matrix:
 [[26 22 14 27]
 [21 29 13 19]
 [14 12 26 28]
 [ 8  7  3 13]]
Train  loss=1.0732 acc=0.5265 f1=0.5119 | Val loss=1.6033 acc=0.3333 f1=0.3283

Epoch 13/15


    t_loss=1.0545 | F1(macro)=0.5226 | Acc=0.5407


Confusion matrix:
 [[25  6 23 35]
 [24 25 16 17]
 [13  5 24 38]
 [ 8  4  1 18]]
Train  loss=1.0545 acc=0.5407 f1=0.5226 | Val loss=1.6049 acc=0.3262 f1=0.3292

Epoch 14/15


    t_loss=1.0105 | F1(macro)=0.5475 | Acc=0.5611


Confusion matrix:
 [[38 11 19 21]
 [27 24 12 19]
 [18 12 27 23]
 [13  4  6  8]]
Train  loss=1.0105 acc=0.5611 f1=0.5475 | Val loss=1.6140 acc=0.3440 f1=0.3259

Epoch 15/15


    t_loss=1.0112 | F1(macro)=0.5377 | Acc=0.5522


Confusion matrix:
 [[41  9 20 19]
 [20 28 16 18]
 [17 10 28 25]
 [12  2  8  9]]
Train  loss=1.0112 acc=0.5522 f1=0.5377 | Val loss=1.5823 acc=0.3759 f1=0.3576
  🔥 New best F1: 0.3576 – model saved.

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.1328 | F1(macro)=0.2431 | Acc=0.2434


Confusion matrix:
 [[36 13 15 25]
 [37 18 16 12]
 [47  8  9 15]
 [13  8  4  6]]
Train  loss=4.1328 acc=0.2434 f1=0.2431 | Val loss=6.3160 acc=0.2447 f1=0.2206
  🔥 New best F1: 0.2206 – model saved.

Epoch 2/8


    t_loss=3.2251 | F1(macro)=0.2787 | Acc=0.2796


Confusion matrix:
 [[14 29 34 12]
 [14 35 22 12]
 [32 20 22  5]
 [ 6  9  9  7]]
Train  loss=3.2251 acc=0.2796 f1=0.2787 | Val loss=4.9924 acc=0.2766 f1=0.2631
  🔥 New best F1: 0.2631 – model saved.

Epoch 3/8


    t_loss=3.1787 | F1(macro)=0.2926 | Acc=0.2929


Confusion matrix:
 [[23 24 17 25]
 [30 25 13 15]
 [40 15  8 16]
 [13  5  7  6]]
Train  loss=3.1787 acc=0.2929 f1=0.2926 | Val loss=4.8757 acc=0.2199 f1=0.2057

Epoch 4/8


    t_loss=2.9553 | F1(macro)=0.2913 | Acc=0.2920


Confusion matrix:
 [[24 12 21 32]
 [33 18 14 18]
 [38 10 13 18]
 [11  6  6  8]]
Train  loss=2.9553 acc=0.2920 f1=0.2913 | Val loss=4.9074 acc=0.2234 f1=0.2176

Epoch 5/8


    t_loss=2.7698 | F1(macro)=0.3048 | Acc=0.3053


Confusion matrix:
 [[ 6 27 19 37]
 [12 30 18 23]
 [14 17 17 31]
 [ 3 10  7 11]]
Train  loss=2.7698 acc=0.3053 f1=0.3048 | Val loss=4.8333 acc=0.2270 f1=0.2161

Epoch 6/8


    t_loss=2.7050 | F1(macro)=0.3093 | Acc=0.3088


Confusion matrix:
 [[20 19 25 25]
 [26 19 21 17]
 [27 15 15 22]
 [ 8  8  6  9]]
Train  loss=2.7050 acc=0.3088 f1=0.3093 | Val loss=4.3812 acc=0.2234 f1=0.2194

Epoch 7/8


    t_loss=2.6837 | F1(macro)=0.2956 | Acc=0.2991


Confusion matrix:
 [[16 13 24 36]
 [15 20 21 27]
 [21 11  9 38]
 [ 7  7  4 13]]
Train  loss=2.6837 acc=0.2991 f1=0.2956 | Val loss=4.8028 acc=0.2057 f1=0.2064

Epoch 8/8


    t_loss=2.5190 | F1(macro)=0.3166 | Acc=0.3168


Confusion matrix:
 [[13 14 21 41]
 [18 23 10 32]
 [31  6  9 33]
 [ 7  8  2 14]]
Train  loss=2.5190 acc=0.3168 f1=0.3166 | Val loss=4.8237 acc=0.2092 f1=0.2105

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.7883 | F1(macro)=0.3214 | Acc=0.3274


Confusion matrix:
 [[18 20 16 35]
 [19 19 15 30]
 [24 13 16 26]
 [ 5  3  7 16]]
Train  loss=2.7883 acc=0.3274 f1=0.3214 | Val loss=4.3188 acc=0.2447 f1=0.2450
  🔥 New best F1: 0.2450 – model saved.

Epoch 2/15


    t_loss=2.1404 | F1(macro)=0.3228 | Acc=0.3310


Confusion matrix:
 [[ 7 32 17 33]
 [10 22 23 28]
 [16 27 12 24]
 [ 5  9  4 13]]
Train  loss=2.1404 acc=0.3310 f1=0.3228 | Val loss=2.8241 acc=0.1915 f1=0.1860

Epoch 3/15


    t_loss=1.6971 | F1(macro)=0.3506 | Acc=0.3664


Confusion matrix:
 [[ 3 27  6 53]
 [ 3 35  6 39]
 [ 5 25 10 39]
 [ 2 11  1 17]]
Train  loss=1.6971 acc=0.3664 f1=0.3506 | Val loss=2.8695 acc=0.2305 f1=0.2079

Epoch 4/15


    t_loss=1.5140 | F1(macro)=0.3795 | Acc=0.4000


Confusion matrix:
 [[ 9 11 52 17]
 [ 4 20 49 10]
 [ 2 16 47 14]
 [ 4  5 14  8]]
Train  loss=1.5140 acc=0.4000 f1=0.3795 | Val loss=2.1623 acc=0.2979 f1=0.2633
  🔥 New best F1: 0.2633 – model saved.

Epoch 5/15


    t_loss=1.4371 | F1(macro)=0.3690 | Acc=0.3832


Confusion matrix:
 [[ 0  9 14 66]
 [ 1 18 15 49]
 [ 0 11 20 48]
 [ 1  4  3 23]]
Train  loss=1.4371 acc=0.3832 f1=0.3690 | Val loss=2.4558 acc=0.2163 f1=0.2013

Epoch 6/15


    t_loss=1.3220 | F1(macro)=0.3844 | Acc=0.4071


Confusion matrix:
 [[ 8 12 48 21]
 [ 7 29 38  9]
 [ 7 15 37 20]
 [ 2  6 14  9]]
Train  loss=1.3220 acc=0.4071 f1=0.3844 | Val loss=1.9960 acc=0.2943 f1=0.2710
  🔥 New best F1: 0.2710 – model saved.

Epoch 7/15


    t_loss=1.2696 | F1(macro)=0.4157 | Acc=0.4301


Confusion matrix:
 [[ 0 34 25 30]
 [ 3 41 29 10]
 [ 2 26 32 19]
 [ 2 11 10  8]]
Train  loss=1.2696 acc=0.4301 f1=0.4157 | Val loss=2.0311 acc=0.2872 f1=0.2374

Epoch 8/15


    t_loss=1.1916 | F1(macro)=0.4529 | Acc=0.4708


Confusion matrix:
 [[ 0  7 51 31]
 [ 3 16 47 17]
 [ 1  4 52 22]
 [ 2  0 14 15]]
Train  loss=1.1916 acc=0.4708 f1=0.4529 | Val loss=2.2072 acc=0.2943 f1=0.2444

Epoch 9/15


    t_loss=1.1813 | F1(macro)=0.4544 | Acc=0.4690


Confusion matrix:
 [[17  8 32 32]
 [19 12 37 15]
 [18  3 36 22]
 [ 7  1 12 11]]
Train  loss=1.1813 acc=0.4690 f1=0.4544 | Val loss=1.9259 acc=0.2695 f1=0.2541

Epoch 10/15


    t_loss=1.0860 | F1(macro)=0.4964 | Acc=0.5124


Confusion matrix:
 [[ 3 12 24 50]
 [ 4 29 20 30]
 [ 5 15 31 28]
 [ 2  6  9 14]]
Train  loss=1.0860 acc=0.5124 f1=0.4964 | Val loss=1.9815 acc=0.2730 f1=0.2554

Epoch 11/15


    t_loss=1.0373 | F1(macro)=0.5279 | Acc=0.5522


Confusion matrix:
 [[10 19 31 29]
 [13 27 27 16]
 [11 15 29 24]
 [ 5  4 10 12]]
Train  loss=1.0373 acc=0.5522 f1=0.5279 | Val loss=1.8670 acc=0.2766 f1=0.2662

Epoch 12/15


    t_loss=1.0151 | F1(macro)=0.5388 | Acc=0.5522


Confusion matrix:
 [[10 10 32 37]
 [10 28 22 23]
 [ 4 19 32 24]
 [ 4  5  8 14]]
Train  loss=1.0151 acc=0.5522 f1=0.5388 | Val loss=1.8777 acc=0.2979 f1=0.2860
  🔥 New best F1: 0.2860 – model saved.

Epoch 13/15


    t_loss=1.0388 | F1(macro)=0.5357 | Acc=0.5487


Confusion matrix:
 [[ 5 13 29 42]
 [12 17 33 21]
 [ 7  8 43 21]
 [ 7  2 11 11]]
Train  loss=1.0388 acc=0.5487 f1=0.5357 | Val loss=1.8595 acc=0.2695 f1=0.2438

Epoch 14/15


    t_loss=0.9701 | F1(macro)=0.5782 | Acc=0.5956


Confusion matrix:
 [[13 19 26 31]
 [12 25 28 18]
 [12 11 40 16]
 [ 5  3 10 13]]
Train  loss=0.9701 acc=0.5956 f1=0.5782 | Val loss=1.7909 acc=0.3227 f1=0.3072
  🔥 New best F1: 0.3072 – model saved.

Epoch 15/15


    t_loss=0.9712 | F1(macro)=0.5932 | Acc=0.6035


Confusion matrix:
 [[12 13 28 36]
 [11 26 29 17]
 [12 12 38 17]
 [ 6  4  9 12]]
Train  loss=0.9712 acc=0.6035 f1=0.5932 | Val loss=1.8002 acc=0.3121 f1=0.2973

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.3565 | F1(macro)=0.2508 | Acc=0.2513


Confusion matrix:
 [[50  6 17 16]
 [44  4 22 13]
 [42  4 15 18]
 [ 9  3 11  8]]
Train  loss=4.3565 acc=0.2513 f1=0.2508 | Val loss=6.5270 acc=0.2730 f1=0.2254
  🔥 New best F1: 0.2254 – model saved.

Epoch 2/8


    t_loss=3.3261 | F1(macro)=0.2863 | Acc=0.2876


Confusion matrix:
 [[42 10 25 12]
 [41  3 26 13]
 [28  5 29 17]
 [ 8  4 13  6]]
Train  loss=3.3261 acc=0.2876 f1=0.2863 | Val loss=5.7052 acc=0.2837 f1=0.2375
  🔥 New best F1: 0.2375 – model saved.

Epoch 3/8


    t_loss=3.2379 | F1(macro)=0.2907 | Acc=0.2903


Confusion matrix:
 [[42 15 15 17]
 [37  9 26 11]
 [33 14 22 10]
 [ 9  4 11  7]]
Train  loss=3.2379 acc=0.2903 f1=0.2907 | Val loss=5.1889 acc=0.2837 f1=0.2539
  🔥 New best F1: 0.2539 – model saved.

Epoch 4/8


    t_loss=3.1973 | F1(macro)=0.2793 | Acc=0.2796


Confusion matrix:
 [[41 10 14 24]
 [38  7 20 18]
 [27  9 23 20]
 [ 7  4 10 10]]
Train  loss=3.1973 acc=0.2796 f1=0.2793 | Val loss=5.2012 acc=0.2872 f1=0.2598
  🔥 New best F1: 0.2598 – model saved.

Epoch 5/8


    t_loss=2.8454 | F1(macro)=0.2748 | Acc=0.2752


Confusion matrix:
 [[35 11 20 23]
 [40  9 19 15]
 [28  5 26 20]
 [ 8  5  9  9]]
Train  loss=2.8454 acc=0.2752 f1=0.2748 | Val loss=5.2070 acc=0.2801 f1=0.2582

Epoch 6/8


    t_loss=2.9382 | F1(macro)=0.2799 | Acc=0.2796


Confusion matrix:
 [[45 16 12 16]
 [43  9 15 16]
 [37 10 13 19]
 [14  2  6  9]]
Train  loss=2.9382 acc=0.2796 f1=0.2799 | Val loss=4.6905 acc=0.2695 f1=0.2376

Epoch 7/8


    t_loss=2.6395 | F1(macro)=0.3115 | Acc=0.3115


Confusion matrix:
 [[49 11 15 14]
 [36 13 24 10]
 [32 13 25  9]
 [10  3  9  9]]
Train  loss=2.6395 acc=0.3115 f1=0.3115 | Val loss=4.1471 acc=0.3404 f1=0.3102
  🔥 New best F1: 0.3102 – model saved.

Epoch 8/8


    t_loss=2.6324 | F1(macro)=0.3263 | Acc=0.3265


Confusion matrix:
 [[45 10 23 11]
 [34  8 33  8]
 [33  8 28 10]
 [11  5 10  5]]
Train  loss=2.6324 acc=0.3265 f1=0.3263 | Val loss=5.0636 acc=0.3050 f1=0.2606

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.7247 | F1(macro)=0.3045 | Acc=0.3097


Confusion matrix:
 [[32 27 24  6]
 [18 28 25 12]
 [26 24 26  3]
 [11 10  8  2]]
Train  loss=2.7247 acc=0.3097 f1=0.3045 | Val loss=3.0460 acc=0.3121 f1=0.2711
  🔥 New best F1: 0.2711 – model saved.

Epoch 2/15


    t_loss=1.8185 | F1(macro)=0.3466 | Acc=0.3549


Confusion matrix:
 [[13 18 15 43]
 [22 24 16 21]
 [19 18 14 28]
 [10  8  4  9]]
Train  loss=1.8185 acc=0.3549 f1=0.3466 | Val loss=2.3744 acc=0.2128 f1=0.2107

Epoch 3/15


    t_loss=1.5056 | F1(macro)=0.3618 | Acc=0.3796


Confusion matrix:
 [[10  2 21 56]
 [10  1 25 47]
 [ 7  2 23 47]
 [ 3  0  8 20]]
Train  loss=1.5056 acc=0.3796 f1=0.3618 | Val loss=2.3999 acc=0.1915 f1=0.1712

Epoch 4/15


    t_loss=1.3421 | F1(macro)=0.3800 | Acc=0.4009


Confusion matrix:
 [[11  1 30 47]
 [12  9 26 36]
 [ 7  3 34 35]
 [ 5  0  6 20]]
Train  loss=1.3421 acc=0.4009 f1=0.3800 | Val loss=2.0296 acc=0.2624 f1=0.2475

Epoch 5/15


    t_loss=1.3186 | F1(macro)=0.3749 | Acc=0.4035


Confusion matrix:
 [[16  7  7 59]
 [23 14 12 34]
 [14 17 12 36]
 [ 7  3  2 19]]
Train  loss=1.3186 acc=0.4035 f1=0.3749 | Val loss=1.7552 acc=0.2163 f1=0.2168

Epoch 6/15


    t_loss=1.2600 | F1(macro)=0.4104 | Acc=0.4274


Confusion matrix:
 [[ 4  7 11 67]
 [ 9 11 20 43]
 [ 7  5 28 39]
 [ 4  2  3 22]]
Train  loss=1.2600 acc=0.4274 f1=0.4104 | Val loss=1.8714 acc=0.2305 f1=0.2224

Epoch 7/15


    t_loss=1.2348 | F1(macro)=0.4310 | Acc=0.4442


Confusion matrix:
 [[18  7  4 60]
 [24  8 16 35]
 [20 10 14 35]
 [ 6  4  2 19]]
Train  loss=1.2348 acc=0.4442 f1=0.4310 | Val loss=1.8153 acc=0.2092 f1=0.2067

Epoch 8/15


    t_loss=1.1670 | F1(macro)=0.4363 | Acc=0.4566


Confusion matrix:
 [[ 3 15 17 54]
 [ 4 31 19 29]
 [ 3 14 21 41]
 [ 1  6  5 19]]
Train  loss=1.1670 acc=0.4566 f1=0.4363 | Val loss=1.7537 acc=0.2624 f1=0.2481

Epoch 9/15


    t_loss=1.1984 | F1(macro)=0.4296 | Acc=0.4460


Confusion matrix:
 [[ 5 30 27 27]
 [ 7 20 28 28]
 [ 4 24 22 29]
 [ 0  5 12 14]]
Train  loss=1.1984 acc=0.4460 f1=0.4296 | Val loss=1.8111 acc=0.2163 f1=0.2053

Epoch 10/15


    t_loss=1.0723 | F1(macro)=0.4667 | Acc=0.4938


Confusion matrix:
 [[14 10 20 45]
 [11 18 17 37]
 [10 16 19 34]
 [ 5  3  7 16]]
Train  loss=1.0723 acc=0.4938 f1=0.4667 | Val loss=1.7411 acc=0.2376 f1=0.2395

Epoch 11/15


    t_loss=1.0628 | F1(macro)=0.5010 | Acc=0.5186


Confusion matrix:
 [[19 10 22 38]
 [18 12 23 30]
 [18 14 24 23]
 [ 9  0  6 16]]
Train  loss=1.0628 acc=0.5186 f1=0.5010 | Val loss=1.7503 acc=0.2518 f1=0.2484

Epoch 12/15


    t_loss=1.0193 | F1(macro)=0.5339 | Acc=0.5496


Confusion matrix:
 [[12 15 14 48]
 [13 23 15 32]
 [ 4 13 21 41]
 [ 5  0  5 21]]
Train  loss=1.0193 acc=0.5496 f1=0.5339 | Val loss=1.7804 acc=0.2730 f1=0.2737
  🔥 New best F1: 0.2737 – model saved.

Epoch 13/15


    t_loss=0.9920 | F1(macro)=0.5655 | Acc=0.5823


Confusion matrix:
 [[ 8 17 15 49]
 [12 31  9 31]
 [ 9 15 23 32]
 [ 5  1  5 20]]
Train  loss=0.9920 acc=0.5823 f1=0.5655 | Val loss=1.7119 acc=0.2908 f1=0.2871
  🔥 New best F1: 0.2871 – model saved.

Epoch 14/15


    t_loss=0.9993 | F1(macro)=0.5637 | Acc=0.5743


Confusion matrix:
 [[10 14 10 55]
 [15 24 15 29]
 [12 14 26 27]
 [ 4  0  6 21]]
Train  loss=0.9993 acc=0.5743 f1=0.5637 | Val loss=1.7943 acc=0.2872 f1=0.2874
  🔥 New best F1: 0.2874 – model saved.

Epoch 15/15


    t_loss=0.9927 | F1(macro)=0.5565 | Acc=0.5664


Confusion matrix:
 [[11 10 16 52]
 [14 26 13 30]
 [13  8 19 39]
 [ 7  1  4 19]]
Train  loss=0.9927 acc=0.5664 f1=0.5565 | Val loss=1.8046 acc=0.2660 f1=0.2707


In [5]:
test_dataset = HistologyDataset(
    test_df,
    transforms=val_test_transforms,
    is_train=False,   # returns (img, sample_index)
    image_size=IMAGE_SIZE
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=False,
        num_classes=N_CLASSES
    ).to(device)
    state = torch.load(f"effv2_s_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv("submission_5fold_no_tta.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png        Luminal B
1  img_0001.png  Triple negative
2  img_0002.png  Triple negative
3  img_0003.png  Triple negative
4  img_0004.png        Luminal B


In [6]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
# all_fold_probs = []
# all_sample_indices = None
#
# test_dataset = HistologyDataset(test_df, transforms=val_test_transforms, is_train=False, image_size=IMAGE_SIZE)
# test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
#                          shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)
#
# for fold in range(N_FOLDS):
#     print(f"Inference with fold {fold} model")
#     model = timm.create_model(PRETRAINED_MODEL, pretrained=False, num_classes=N_CLASSES).to(device)
#     model.load_state_dict(torch.load(f"effv2_s_fold{fold}.pth", map_location=device))
#     model.eval()
#
#     fold_probs = []
#     sample_indices_list = []
#
#     with torch.no_grad():
#         for img_tensor, sample_idx in test_loader:
#             img_tensor = img_tensor.squeeze(0)  # [3,H,W]
#             img_tensor = img_tensor.to(device)
#
#             # -------- TTA: apply multiple augmented views --------
#             tta_tensors = apply_tta(img_tensor)
#
#             # accumulate probability predictions
#             probs_sum = 0
#             for aug_img in tta_tensors:
#                 aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
#                 logits = model(aug_img)
#                 probs = softmax(logits, dim=1)  # [1,4]
#                 probs_sum += probs[0].cpu().numpy()
#
#             # average across TTA views
#             avg_probs = probs_sum / len(tta_tensors)
#             fold_probs.append(avg_probs)
#
#             if all_sample_indices is None:
#                 sample_indices_list.append(sample_idx[0])
#
#     fold_probs = np.vstack(fold_probs)  # [N, 4]
#     all_fold_probs.append(fold_probs)
#
#     if all_sample_indices is None:
#         all_sample_indices = sample_indices_list
#
# mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
# pred_indices = mean_probs.argmax(axis=1)
# pred_labels = [idx2label[int(i)] for i in pred_indices]
#
# sample_index_with_ext = [
#     f"{si}.png" if not si.endswith(".png") else si
#     for si in all_sample_indices
# ]
#
# submission_df = pd.DataFrame({
#     "sample_index": sample_index_with_ext,
#     "label": pred_labels
# })
# submission_df.to_csv("submission_5fold_tta.csv", index=False)
#
# print("Saved submission_5fold_tta.csv")