In [1]:
import enum
import json
import os
from copy import deepcopy

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.mixup_cutmix_wrapper import MixupCutmixWrapper
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_multicrop_tta, apply_mask_multicrop_tta
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    EFFICIENTNET_B1_NS = "tf_efficientnet_b1.ns_jft_in1k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B1_NS

In [4]:
best_f1_per_fold: dict[int, int] = {}
N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
N_CLASSES = 4  # number of classes in the dataset (labels)

# efficientnet_b0 / efficientnet_b1

In [5]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,          # Dropout
        drop_path_rate=0.1      # Stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    For EfficientNet from timm: unfreeze last 2 blocks + classifier head.
    """
    freeze_all(model)

    # Last 2 conv blocks
    if hasattr(model, "blocks"):
        for blk in model.blocks[-2:]:
            for p in blk.parameters():
                p.requires_grad = True

    # Classifier head
    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True


if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    GRAD_ACCUM_STEPS = 2
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 25
    LR = 3e-4
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b0_model(pretrained=True)
        unfreeze_last_two_blocks_and_head(model)

        # ---- loss, optimizer, scheduler ----
        class_counts_np = train_df["label_idx"].value_counts().sort_index().values
        class_counts = torch.tensor(class_counts_np, dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.1
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None
        mixup_fn = MixupCutmixWrapper(
            alpha=0.4,       # mixup/cutmix Beta distribution
            mixup_prob=0.4,  # 40% of batches => mixup
            cutmix_prob=0.2  # 20% of batches => cutmix
        )

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device, grad_accum_steps=GRAD_ACCUM_STEPS, mixup_fn=mixup_fn
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(
                    best_state,
                    f"best_effb0_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best weights for this fold
        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1

# tf_efficientnet_b1_ns

In [6]:
def create_efficientnet_b1_ns_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        MODEL_TO_USE.value,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,          # 3 RGB + 1 mask
        drop_rate=0.3,       # stronger dropout than B0
        drop_path_rate=0.1   # stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    Freeze earlier EfficientNet blocks, unfreeze the last two + head.
    Works for timm tf_efficientnet_b* models.
    """
    # 1) Freeze everything by default
    for p in model.parameters():
        p.requires_grad = False

    # 2) Unfreeze last two blocks
    # model.blocks is a nn.Sequential
    num_blocks = len(model.blocks)
    for idx in range(num_blocks - 2, num_blocks):
        for p in model.blocks[idx].parameters():
            p.requires_grad = True

    # 3) Unfreeze conv_head + bn2 + classifier
    for p in model.conv_head.parameters():
        p.requires_grad = True
    for p in model.bn2.parameters():
        p.requires_grad = True
    for p in model.classifier.parameters():
        p.requires_grad = True

def unfreeze_last_stage_and_head(model: nn.Module):
    """
    EfficientNet B1-NS recommended fine-tuning strategy:
    - Freeze all early MBConv stages
    - Unfreeze the last MBConv stage (stage 6)
    - Unfreeze conv_head + bn2 + classifier
    """

    # Freeze everything first
    for p in model.parameters():
        p.requires_grad = False

    # ---- Unfreeze last stage (stage 6) ----
    # EfficientNet blocks are sequential but grouped in stages.
    # B1 layout roughly:
    #   Stage0: stem
    #   Stage1: blocks[0]
    #   Stage2: blocks[1:3]
    #   Stage3: blocks[3:5]
    #   Stage4: blocks[5:8]
    #   Stage5: blocks[8:11]
    #   Stage6: blocks[11:15]  <-- last stage
    last_stage_start = len(model.blocks) - 4  # 4 blocks in last stage (B1)
    for idx in range(last_stage_start, len(model.blocks)):
        for p in model.blocks[idx].parameters():
            p.requires_grad = True

    # ---- Unfreeze head ----
    for p in model.conv_head.parameters():
        p.requires_grad = True
    for p in model.bn2.parameters():
        p.requires_grad = True
    for p in model.classifier.parameters():
        p.requires_grad = True

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1_NS:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    GRAD_ACCUM_STEPS = 2
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 25
    LR = 7.5e-4
    WEIGHT_DECAY = 2e-4
    PREFIX = "tf_effb1_ns"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b1_ns_model(pretrained=True)
        unfreeze_last_stage_and_head(model)

        # ---- loss, optimizer, scheduler ----
        class_counts_np = train_df["label_idx"].value_counts().sort_index().values
        class_counts = torch.tensor(class_counts_np, dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.05
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=WEIGHT_DECAY
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None
        mixup_fn = MixupCutmixWrapper(
            alpha=0.3,       # mixup/cutmix Beta distribution
            mixup_prob=0.3,  # 30% of batches => mixup
            cutmix_prob=0.2  # 20% of batches => cutmix
        )

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device, grad_accum_steps=GRAD_ACCUM_STEPS, mixup_fn=mixup_fn
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(
                    best_state,
                    f"best_{PREFIX}_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best weights for this fold
        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        torch.save(model.state_dict(), f"{PREFIX}_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1


========== Fold 0 ==========

Epoch 1/25


    t_loss=2.2381 | F1(macro)=0.3110 | Acc=0.3168


Confusion matrix:
 [[ 7 14  6 14]
 [ 4 20  5  3]
 [ 2 11  9  8]
 [ 6  5  2  1]]
Train  loss=2.2381 acc=0.3168 f1=0.3110 | Val loss=1.8969 acc=0.3162 f1=0.2793
  🔥 New best F1: 0.2793 – model saved.

Epoch 2/25


    t_loss=1.6249 | F1(macro)=0.3270 | Acc=0.3534


Confusion matrix:
 [[ 5  4  5 27]
 [ 4  6 11 11]
 [ 2  1  6 21]
 [ 0  1  4  9]]
Train  loss=1.6249 acc=0.3534 f1=0.3270 | Val loss=1.7874 acc=0.2222 f1=0.2247

Epoch 3/25


    t_loss=1.6215 | F1(macro)=0.3144 | Acc=0.3190


Confusion matrix:
 [[ 0  2  2 37]
 [ 1  1  1 29]
 [ 0  2  2 26]
 [ 0  3  0 11]]
Train  loss=1.6215 acc=0.3190 f1=0.3144 | Val loss=2.1754 acc=0.1197 f1=0.0881

Epoch 4/25


    t_loss=1.3927 | F1(macro)=0.3809 | Acc=0.3922


Confusion matrix:
 [[ 9 13  1 18]
 [12 11  1  8]
 [10  7  4  9]
 [ 2  5  2  5]]
Train  loss=1.3927 acc=0.3922 f1=0.3809 | Val loss=1.8428 acc=0.2479 f1=0.2406

Epoch 5/25


    t_loss=1.4120 | F1(macro)=0.3680 | Acc=0.3858


Confusion matrix:
 [[ 2 17 12 10]
 [ 2 16  9  5]
 [ 3  6 15  6]
 [ 0  3  5  6]]
Train  loss=1.4120 acc=0.3858 f1=0.3680 | Val loss=1.6307 acc=0.3333 f1=0.3077
  🔥 New best F1: 0.3077 – model saved.

Epoch 6/25


    t_loss=1.3409 | F1(macro)=0.3885 | Acc=0.4203


Confusion matrix:
 [[ 8  2 21 10]
 [ 2  5 17  8]
 [ 2  0 22  6]
 [ 0  0  5  9]]
Train  loss=1.3409 acc=0.4203 f1=0.3885 | Val loss=1.8114 acc=0.3761 f1=0.3511
  🔥 New best F1: 0.3511 – model saved.

Epoch 7/25


    t_loss=1.2719 | F1(macro)=0.4255 | Acc=0.4483


Confusion matrix:
 [[12  3 15 11]
 [ 5  7 14  6]
 [ 4  2 17  7]
 [ 1  1  7  5]]
Train  loss=1.2719 acc=0.4483 f1=0.4255 | Val loss=1.6917 acc=0.3504 f1=0.3336

Epoch 8/25


    t_loss=1.1798 | F1(macro)=0.4331 | Acc=0.4655


Confusion matrix:
 [[13  3  5 20]
 [ 7  5  9 11]
 [ 5  3  7 15]
 [ 1  0  4  9]]
Train  loss=1.1798 acc=0.4655 f1=0.4331 | Val loss=1.8920 acc=0.2906 f1=0.2840

Epoch 9/25


    t_loss=1.0753 | F1(macro)=0.4962 | Acc=0.5259


Confusion matrix:
 [[13 13  6  9]
 [11  9  6  6]
 [ 6 10  3 11]
 [ 3  2  3  6]]
Train  loss=1.0753 acc=0.5259 f1=0.4962 | Val loss=1.6887 acc=0.2650 f1=0.2525

Epoch 10/25


    t_loss=1.0721 | F1(macro)=0.5065 | Acc=0.5194


Confusion matrix:
 [[10 13  3 15]
 [10 15  1  6]
 [ 7  8  2 13]
 [ 3  5  0  6]]
Train  loss=1.0721 acc=0.5194 f1=0.5065 | Val loss=1.9218 acc=0.2821 f1=0.2565

Epoch 11/25


    t_loss=0.9938 | F1(macro)=0.5627 | Acc=0.5754


Confusion matrix:
 [[14 12  5 10]
 [18  8  3  3]
 [10  5  4 11]
 [ 3  1  2  8]]
Train  loss=0.9938 acc=0.5754 f1=0.5627 | Val loss=1.8796 acc=0.2906 f1=0.2828

Epoch 12/25


    t_loss=0.9549 | F1(macro)=0.5934 | Acc=0.6034


Confusion matrix:
 [[20  4  4 13]
 [15  7  1  9]
 [11  1  2 16]
 [ 4  2  1  7]]
Train  loss=0.9549 acc=0.6034 f1=0.5934 | Val loss=1.8730 acc=0.3077 f1=0.2716

Epoch 13/25


    t_loss=0.9361 | F1(macro)=0.6133 | Acc=0.6185


Confusion matrix:
 [[13 15  8  5]
 [ 7 13  7  5]
 [ 8  5  6 11]
 [ 3  3  0  8]]
Train  loss=0.9361 acc=0.6185 f1=0.6133 | Val loss=1.7860 acc=0.3419 f1=0.3377

Epoch 14/25


    t_loss=0.8992 | F1(macro)=0.6081 | Acc=0.6272


Confusion matrix:
 [[11  9 17  4]
 [ 9  5 15  3]
 [ 3  6 13  8]
 [ 3  4  4  3]]
Train  loss=0.8992 acc=0.6272 f1=0.6081 | Val loss=1.7567 acc=0.2735 f1=0.2559

Epoch 15/25


    t_loss=0.8704 | F1(macro)=0.6607 | Acc=0.6681


Confusion matrix:
 [[20  5 10  6]
 [15  7  5  5]
 [12  1  6 11]
 [ 7  1  0  6]]
Train  loss=0.8704 acc=0.6681 f1=0.6607 | Val loss=1.7229 acc=0.3333 f1=0.3116

Epoch 16/25


    t_loss=0.8425 | F1(macro)=0.6425 | Acc=0.6595


Confusion matrix:
 [[19  7  9  6]
 [12  7  9  4]
 [11  3 10  6]
 [ 3  2  3  6]]
Train  loss=0.8425 acc=0.6595 f1=0.6425 | Val loss=1.7294 acc=0.3590 f1=0.3444

Epoch 17/25


    t_loss=0.7639 | F1(macro)=0.7054 | Acc=0.7177


Confusion matrix:
 [[22  4 10  5]
 [15  6  8  3]
 [14  2  9  5]
 [ 7  1  3  3]]
Train  loss=0.7639 acc=0.7177 f1=0.7054 | Val loss=1.8171 acc=0.3419 f1=0.3028

Epoch 18/25


    t_loss=0.6780 | F1(macro)=0.7356 | Acc=0.7565


Confusion matrix:
 [[ 9  7 18  7]
 [ 7  5 15  5]
 [ 5  0 21  4]
 [ 3  0  6  5]]
Train  loss=0.6780 acc=0.7565 f1=0.7356 | Val loss=1.7606 acc=0.3419 f1=0.3141

Epoch 19/25


    t_loss=0.6904 | F1(macro)=0.7434 | Acc=0.7543


Confusion matrix:
 [[14 13  8  6]
 [15  4 10  3]
 [ 8  7  7  8]
 [ 2  2  3  7]]
Train  loss=0.6904 acc=0.7543 f1=0.7434 | Val loss=1.7496 acc=0.2735 f1=0.2744

Epoch 20/25


    t_loss=0.7579 | F1(macro)=0.7145 | Acc=0.7284


Confusion matrix:
 [[16  9  6 10]
 [17  6  6  3]
 [11  5  8  6]
 [ 4  2  2  6]]
Train  loss=0.7579 acc=0.7284 f1=0.7145 | Val loss=1.8032 acc=0.3077 f1=0.2993

Epoch 21/25


    t_loss=0.6435 | F1(macro)=0.7578 | Acc=0.7737


Confusion matrix:
 [[16 15  7  3]
 [14  9  6  3]
 [11  5  9  5]
 [ 2  5  3  4]]
Train  loss=0.6435 acc=0.7737 f1=0.7578 | Val loss=1.8161 acc=0.3248 f1=0.3142

Epoch 22/25


    t_loss=0.6792 | F1(macro)=0.7901 | Acc=0.7953


Confusion matrix:
 [[14 14 11  2]
 [11 11  8  2]
 [14  3  9  4]
 [ 3  4  4  3]]
Train  loss=0.6792 acc=0.7953 f1=0.7901 | Val loss=1.7902 acc=0.3162 f1=0.3029

Epoch 23/25


    t_loss=0.6965 | F1(macro)=0.7445 | Acc=0.7543


Confusion matrix:
 [[18  6 11  6]
 [15  3 12  2]
 [11  2 13  4]
 [ 5  2  4  3]]
Train  loss=0.6965 acc=0.7543 f1=0.7445 | Val loss=1.8182 acc=0.3162 f1=0.2779

Epoch 24/25


    t_loss=0.6556 | F1(macro)=0.7871 | Acc=0.7888


Confusion matrix:
 [[13 10 11  7]
 [10  7 12  3]
 [10  4 11  5]
 [ 2  3  4  5]]
Train  loss=0.6556 acc=0.7888 f1=0.7871 | Val loss=1.7799 acc=0.3077 f1=0.3024

Epoch 25/25


    t_loss=0.6649 | F1(macro)=0.7963 | Acc=0.7974


Confusion matrix:
 [[17  8 11  5]
 [14  5 10  3]
 [12  4  9  5]
 [ 3  3  4  4]]
Train  loss=0.6649 acc=0.7974 f1=0.7963 | Val loss=1.8722 acc=0.2991 f1=0.2806
Restored best weights for fold 0 (F1=0.3511)

========== Fold 1 ==========

Epoch 1/25


    t_loss=2.2904 | F1(macro)=0.2900 | Acc=0.3075


Confusion matrix:
 [[19 10  2 10]
 [12 11  0  9]
 [14  7  2  7]
 [ 7  2  0  4]]
Train  loss=2.2904 acc=0.3075 f1=0.2900 | Val loss=1.9675 acc=0.3103 f1=0.2668
  🔥 New best F1: 0.2668 – model saved.

Epoch 2/25


    t_loss=1.7294 | F1(macro)=0.3064 | Acc=0.3097


Confusion matrix:
 [[11 14  5 11]
 [ 4 18  1  9]
 [ 7 11  1 11]
 [ 3  2  1  7]]
Train  loss=1.7294 acc=0.3097 f1=0.3064 | Val loss=1.6644 acc=0.3190 f1=0.2820
  🔥 New best F1: 0.2820 – model saved.

Epoch 3/25


    t_loss=1.4875 | F1(macro)=0.3255 | Acc=0.3398


Confusion matrix:
 [[11  4  0 26]
 [11  4  0 17]
 [10  2  0 18]
 [ 1  2  0 10]]
Train  loss=1.4875 acc=0.3398 f1=0.3255 | Val loss=2.1038 acc=0.2155 f1=0.1793

Epoch 4/25


    t_loss=1.4143 | F1(macro)=0.3628 | Acc=0.3828


Confusion matrix:
 [[ 3  9 21  8]
 [ 2  6 14 10]
 [ 1  5 20  4]
 [ 1  0  8  4]]
Train  loss=1.4143 acc=0.3828 f1=0.3628 | Val loss=1.7385 acc=0.2845 f1=0.2478

Epoch 5/25


    t_loss=1.2922 | F1(macro)=0.3883 | Acc=0.4151


Confusion matrix:
 [[ 4 11 13 13]
 [ 3 15  7  7]
 [ 2  9  8 11]
 [ 2  3  2  6]]
Train  loss=1.2922 acc=0.4151 f1=0.3883 | Val loss=1.7685 acc=0.2845 f1=0.2723

Epoch 6/25


    t_loss=1.2912 | F1(macro)=0.4083 | Acc=0.4280


Confusion matrix:
 [[ 6  5 15 15]
 [ 5  5  8 14]
 [ 2  2 15 11]
 [ 2  0  4  7]]
Train  loss=1.2912 acc=0.4280 f1=0.4083 | Val loss=1.5926 acc=0.2845 f1=0.2729

Epoch 7/25


    t_loss=1.2310 | F1(macro)=0.4466 | Acc=0.4710


Confusion matrix:
 [[ 9 13  4 15]
 [ 8 11  3 10]
 [ 3  4  9 14]
 [ 5  2  2  4]]
Train  loss=1.2310 acc=0.4710 f1=0.4466 | Val loss=1.8050 acc=0.2845 f1=0.2864
  🔥 New best F1: 0.2864 – model saved.

Epoch 8/25


    t_loss=1.1858 | F1(macro)=0.4394 | Acc=0.4624


Confusion matrix:
 [[11  2 14 14]
 [10  5  6 11]
 [ 5  1 12 12]
 [ 3  2  4  4]]
Train  loss=1.1858 acc=0.4624 f1=0.4394 | Val loss=1.8142 acc=0.2759 f1=0.2660

Epoch 9/25


    t_loss=1.1438 | F1(macro)=0.4698 | Acc=0.4817


Confusion matrix:
 [[ 5  5  8 23]
 [ 4 10  8 10]
 [ 4  2  8 16]
 [ 2  0  0 11]]
Train  loss=1.1438 acc=0.4817 f1=0.4698 | Val loss=1.8199 acc=0.2931 f1=0.2961
  🔥 New best F1: 0.2961 – model saved.

Epoch 10/25


    t_loss=1.1689 | F1(macro)=0.4844 | Acc=0.5011


Confusion matrix:
 [[13 10 13  5]
 [ 9 10  8  5]
 [12  4 11  3]
 [ 6  2  3  2]]
Train  loss=1.1689 acc=0.5011 f1=0.4844 | Val loss=1.7454 acc=0.3103 f1=0.2868

Epoch 11/25


    t_loss=1.0736 | F1(macro)=0.5257 | Acc=0.5376


Confusion matrix:
 [[ 7  5 18 11]
 [ 5  4 13 10]
 [ 5  3 17  5]
 [ 4  1  5  3]]
Train  loss=1.0736 acc=0.5376 f1=0.5257 | Val loss=2.0116 acc=0.2672 f1=0.2390

Epoch 12/25


    t_loss=1.0272 | F1(macro)=0.5419 | Acc=0.5484


Confusion matrix:
 [[ 7 12 14  8]
 [ 3  9 16  4]
 [ 7  3 15  5]
 [ 5  0  5  3]]
Train  loss=1.0272 acc=0.5484 f1=0.5419 | Val loss=1.8042 acc=0.2931 f1=0.2751

Epoch 13/25


    t_loss=0.9887 | F1(macro)=0.5693 | Acc=0.5849


Confusion matrix:
 [[ 5  7 15 14]
 [ 3  9 12  8]
 [ 5  2 12 11]
 [ 1  1  4  7]]
Train  loss=0.9887 acc=0.5849 f1=0.5693 | Val loss=1.7960 acc=0.2845 f1=0.2819

Epoch 14/25


    t_loss=0.9534 | F1(macro)=0.6146 | Acc=0.6172


Confusion matrix:
 [[20  4  7 10]
 [13  9  3  7]
 [14  1 10  5]
 [ 8  0  3  2]]
Train  loss=0.9534 acc=0.6172 f1=0.6146 | Val loss=1.7186 acc=0.3534 f1=0.3234
  🔥 New best F1: 0.3234 – model saved.

Epoch 15/25


    t_loss=0.9038 | F1(macro)=0.6489 | Acc=0.6495


Confusion matrix:
 [[19  5 10  7]
 [16  5  6  5]
 [13  2 12  3]
 [ 7  1  4  1]]
Train  loss=0.9038 acc=0.6495 f1=0.6489 | Val loss=1.8265 acc=0.3190 f1=0.2685

Epoch 16/25


    t_loss=0.8465 | F1(macro)=0.6370 | Acc=0.6559


Confusion matrix:
 [[16  7 16  2]
 [12  9  9  2]
 [13  3 13  1]
 [ 6  2  5  0]]
Train  loss=0.8465 acc=0.6559 f1=0.6370 | Val loss=1.9052 acc=0.3276 f1=0.2649

Epoch 17/25


    t_loss=0.7957 | F1(macro)=0.6841 | Acc=0.6903


Confusion matrix:
 [[10  9 13  9]
 [ 4 15  6  7]
 [ 9  3 13  5]
 [ 2  2  6  3]]
Train  loss=0.7957 acc=0.6903 f1=0.6841 | Val loss=1.7457 acc=0.3534 f1=0.3348
  🔥 New best F1: 0.3348 – model saved.

Epoch 18/25


    t_loss=0.7478 | F1(macro)=0.6967 | Acc=0.7075


Confusion matrix:
 [[13  4 17  7]
 [ 4  9 11  8]
 [ 8  2 16  4]
 [ 6  0  6  1]]
Train  loss=0.7478 acc=0.7075 f1=0.6967 | Val loss=1.8773 acc=0.3362 f1=0.3012

Epoch 19/25


    t_loss=0.7049 | F1(macro)=0.7233 | Acc=0.7355


Confusion matrix:
 [[11 10 17  3]
 [ 8 16  4  4]
 [10  5 14  1]
 [ 7  1  4  1]]
Train  loss=0.7049 acc=0.7355 f1=0.7233 | Val loss=1.7375 acc=0.3621 f1=0.3206

Epoch 20/25


    t_loss=0.7094 | F1(macro)=0.7564 | Acc=0.7634


Confusion matrix:
 [[14  6 11 10]
 [ 8 10  5  9]
 [ 7  3 13  7]
 [ 6  2  4  1]]
Train  loss=0.7094 acc=0.7634 f1=0.7564 | Val loss=1.8594 acc=0.3276 f1=0.3021

Epoch 21/25


    t_loss=0.6438 | F1(macro)=0.7626 | Acc=0.7677


Confusion matrix:
 [[17  5 11  8]
 [ 9 15  5  3]
 [10  3 15  2]
 [ 7  1  2  3]]
Train  loss=0.6438 acc=0.7677 f1=0.7626 | Val loss=1.7341 acc=0.4310 f1=0.4059
  🔥 New best F1: 0.4059 – model saved.

Epoch 22/25


    t_loss=0.6540 | F1(macro)=0.7494 | Acc=0.7570


Confusion matrix:
 [[16  8  8  9]
 [ 5 18  5  4]
 [ 8  3 13  6]
 [ 6  3  3  1]]
Train  loss=0.6540 acc=0.7570 f1=0.7494 | Val loss=1.8669 acc=0.4138 f1=0.3712

Epoch 23/25


    t_loss=0.6904 | F1(macro)=0.7459 | Acc=0.7505


Confusion matrix:
 [[16  4 17  4]
 [ 8 13  7  4]
 [12  3 13  2]
 [ 4  2  6  1]]
Train  loss=0.6904 acc=0.7505 f1=0.7459 | Val loss=1.9355 acc=0.3707 f1=0.3290

Epoch 24/25


    t_loss=0.6725 | F1(macro)=0.7621 | Acc=0.7677


Confusion matrix:
 [[11  8 15  7]
 [ 5 14  7  6]
 [10  5 13  2]
 [ 5  3  4  1]]
Train  loss=0.6725 acc=0.7677 f1=0.7621 | Val loss=1.9251 acc=0.3362 f1=0.3007

Epoch 25/25


    t_loss=0.6824 | F1(macro)=0.7797 | Acc=0.7785


Confusion matrix:
 [[19  4 12  6]
 [ 8 10  9  5]
 [ 9  2 14  5]
 [ 7  1  4  1]]
Train  loss=0.6824 acc=0.7785 f1=0.7797 | Val loss=1.8387 acc=0.3793 f1=0.3333
Restored best weights for fold 1 (F1=0.4059)

========== Fold 2 ==========

Epoch 1/25


    t_loss=2.2227 | F1(macro)=0.2758 | Acc=0.2882


Confusion matrix:
 [[ 0 20 19  1]
 [ 1 18 12  1]
 [ 0 14 16  0]
 [ 0  8  6  0]]
Train  loss=2.2227 acc=0.2882 f1=0.2758 | Val loss=2.1240 acc=0.2931 f1=0.1942
  🔥 New best F1: 0.1942 – model saved.

Epoch 2/25


    t_loss=1.6132 | F1(macro)=0.2931 | Acc=0.3097


Confusion matrix:
 [[ 3  0 26 11]
 [ 3  0 22  7]
 [ 5  0 21  4]
 [ 3  0  6  5]]
Train  loss=1.6132 acc=0.3097 f1=0.2931 | Val loss=2.1289 acc=0.2500 f1=0.1888

Epoch 3/25


    t_loss=1.4567 | F1(macro)=0.3065 | Acc=0.3441


Confusion matrix:
 [[ 1  1 20 18]
 [ 2  6 16  8]
 [ 3  4 15  8]
 [ 0  2  5  7]]
Train  loss=1.4567 acc=0.3441 f1=0.3065 | Val loss=1.7603 acc=0.2500 f1=0.2284
  🔥 New best F1: 0.2284 – model saved.

Epoch 4/25


    t_loss=1.4920 | F1(macro)=0.3275 | Acc=0.3355


Confusion matrix:
 [[ 4 13  7 16]
 [ 2 16 10  4]
 [ 4  6 13  7]
 [ 0  8  3  3]]
Train  loss=1.4920 acc=0.3355 f1=0.3275 | Val loss=1.6452 acc=0.3103 f1=0.2839
  🔥 New best F1: 0.2839 – model saved.

Epoch 5/25


    t_loss=1.3768 | F1(macro)=0.3552 | Acc=0.3785


Confusion matrix:
 [[ 3  1 13 23]
 [ 7  3 10 12]
 [ 8  4  9  9]
 [ 2  1  1 10]]
Train  loss=1.3768 acc=0.3785 f1=0.3552 | Val loss=1.8227 acc=0.2155 f1=0.2065

Epoch 6/25


    t_loss=1.3565 | F1(macro)=0.3399 | Acc=0.3591


Confusion matrix:
 [[ 6  1 17 16]
 [ 4  1 17 10]
 [ 6  0 16  8]
 [ 2  0  4  8]]
Train  loss=1.3565 acc=0.3591 f1=0.3399 | Val loss=1.8944 acc=0.2672 f1=0.2331

Epoch 7/25


    t_loss=1.2782 | F1(macro)=0.3772 | Acc=0.4065


Confusion matrix:
 [[20  6  1 13]
 [13  6  2 11]
 [16  4  2  8]
 [ 6  2  1  5]]
Train  loss=1.2782 acc=0.4065 f1=0.3772 | Val loss=1.6632 acc=0.2845 f1=0.2421

Epoch 8/25


    t_loss=1.2025 | F1(macro)=0.4190 | Acc=0.4559


Confusion matrix:
 [[13  3  3 21]
 [ 8  4  1 19]
 [18  2  3  7]
 [ 3  0  1 10]]
Train  loss=1.2025 acc=0.4559 f1=0.4190 | Val loss=1.9254 acc=0.2586 f1=0.2379

Epoch 9/25


    t_loss=1.1508 | F1(macro)=0.4606 | Acc=0.4839


Confusion matrix:
 [[ 9  8  8 15]
 [ 5  6  8 13]
 [ 9  4 11  6]
 [ 2  1  3  8]]
Train  loss=1.1508 acc=0.4839 f1=0.4606 | Val loss=1.6176 acc=0.2931 f1=0.2911
  🔥 New best F1: 0.2911 – model saved.

Epoch 10/25


    t_loss=1.1450 | F1(macro)=0.4841 | Acc=0.4989


Confusion matrix:
 [[12  2 15 11]
 [ 6  5 12  9]
 [13  2 13  2]
 [ 3  0  6  5]]
Train  loss=1.1450 acc=0.4989 f1=0.4841 | Val loss=2.1051 acc=0.3017 f1=0.2886

Epoch 11/25


    t_loss=1.0798 | F1(macro)=0.5004 | Acc=0.5161


Confusion matrix:
 [[21  2 10  7]
 [16  0  6 10]
 [22  2  3  3]
 [ 6  0  3  5]]
Train  loss=1.0798 acc=0.5161 f1=0.5004 | Val loss=2.3510 acc=0.2500 f1=0.1929

Epoch 12/25


    t_loss=0.9774 | F1(macro)=0.5559 | Acc=0.5677


Confusion matrix:
 [[14  4 15  7]
 [11  4  8  9]
 [13  2 10  5]
 [ 4  0  7  3]]
Train  loss=0.9774 acc=0.5677 f1=0.5559 | Val loss=1.9215 acc=0.2672 f1=0.2439

Epoch 13/25


    t_loss=1.0114 | F1(macro)=0.5264 | Acc=0.5398


Confusion matrix:
 [[ 7  8 18  7]
 [ 4 10 14  4]
 [ 6  8 14  2]
 [ 1  3  6  4]]
Train  loss=1.0114 acc=0.5398 f1=0.5264 | Val loss=1.7850 acc=0.3017 f1=0.2922
  🔥 New best F1: 0.2922 – model saved.

Epoch 14/25


    t_loss=0.9301 | F1(macro)=0.5893 | Acc=0.6022


Confusion matrix:
 [[11  5 14 10]
 [ 7  3 10 12]
 [ 9  3 11  7]
 [ 0  4  5  5]]
Train  loss=0.9301 acc=0.6022 f1=0.5893 | Val loss=2.0901 acc=0.2586 f1=0.2447

Epoch 15/25


    t_loss=0.8830 | F1(macro)=0.6132 | Acc=0.6323


Confusion matrix:
 [[12  6 13  9]
 [13  6  7  6]
 [16  2  8  4]
 [ 5  0  6  3]]
Train  loss=0.8830 acc=0.6323 f1=0.6132 | Val loss=2.0725 acc=0.2500 f1=0.2392

Epoch 16/25


    t_loss=0.8660 | F1(macro)=0.6456 | Acc=0.6581


Confusion matrix:
 [[11  4 15 10]
 [ 8  8  9  7]
 [ 5  7 14  4]
 [ 1  1  6  6]]
Train  loss=0.8660 acc=0.6581 f1=0.6456 | Val loss=1.8143 acc=0.3362 f1=0.3293
  🔥 New best F1: 0.3293 – model saved.

Epoch 17/25


    t_loss=0.7353 | F1(macro)=0.6970 | Acc=0.6989


Confusion matrix:
 [[14  4 16  6]
 [11  5 12  4]
 [13  3 11  3]
 [ 2  1  9  2]]
Train  loss=0.7353 acc=0.6989 f1=0.6970 | Val loss=1.9116 acc=0.2759 f1=0.2481

Epoch 18/25


    t_loss=0.7354 | F1(macro)=0.7321 | Acc=0.7312


Confusion matrix:
 [[18  4 15  3]
 [16  4  8  4]
 [14  4 10  2]
 [ 4  1  7  2]]
Train  loss=0.7354 acc=0.7312 f1=0.7321 | Val loss=2.0710 acc=0.2931 f1=0.2537

Epoch 19/25


    t_loss=0.7494 | F1(macro)=0.6967 | Acc=0.7075


Confusion matrix:
 [[19  2 14  5]
 [16  2  7  7]
 [18  1  8  3]
 [ 6  0  4  4]]
Train  loss=0.7494 acc=0.7075 f1=0.6967 | Val loss=2.0306 acc=0.2845 f1=0.2471

Epoch 20/25


    t_loss=0.7363 | F1(macro)=0.7358 | Acc=0.7376


Confusion matrix:
 [[ 9  3 24  4]
 [10  3 14  5]
 [10  2 16  2]
 [ 1  1  9  3]]
Train  loss=0.7363 acc=0.7376 f1=0.7358 | Val loss=2.1195 acc=0.2672 f1=0.2405

Epoch 21/25


    t_loss=0.7219 | F1(macro)=0.7428 | Acc=0.7441


Confusion matrix:
 [[13  3 15  9]
 [16  1  8  7]
 [13  2 11  4]
 [ 4  1  5  4]]
Train  loss=0.7219 acc=0.7441 f1=0.7428 | Val loss=1.9765 acc=0.2500 f1=0.2207

Epoch 22/25


    t_loss=0.6590 | F1(macro)=0.7865 | Acc=0.7892


Confusion matrix:
 [[16  2 19  3]
 [18  1 10  3]
 [16  1 12  1]
 [ 6  0  6  2]]
Train  loss=0.6590 acc=0.7892 f1=0.7865 | Val loss=2.2707 acc=0.2672 f1=0.2186

Epoch 23/25


    t_loss=0.6665 | F1(macro)=0.7957 | Acc=0.8000


Confusion matrix:
 [[17  5 18  0]
 [18  3  9  2]
 [14  4 10  2]
 [ 7  0  6  1]]
Train  loss=0.6665 acc=0.8000 f1=0.7957 | Val loss=2.1586 acc=0.2672 f1=0.2174

Epoch 24/25


    t_loss=0.6274 | F1(macro)=0.8094 | Acc=0.8108


Confusion matrix:
 [[18  4 14  4]
 [16  2 11  3]
 [12  5  9  4]
 [ 5  0  6  3]]
Train  loss=0.6274 acc=0.8108 f1=0.8094 | Val loss=2.1157 acc=0.2759 f1=0.2400

Epoch 25/25


    t_loss=0.7140 | F1(macro)=0.7329 | Acc=0.7419


Confusion matrix:
 [[18  3 16  3]
 [17  4  9  2]
 [16  2  9  3]
 [ 7  0  6  1]]
Train  loss=0.7140 acc=0.7419 f1=0.7329 | Val loss=2.1312 acc=0.2759 f1=0.2266
Restored best weights for fold 2 (F1=0.3293)

========== Fold 3 ==========

Epoch 1/25


    t_loss=2.3497 | F1(macro)=0.2819 | Acc=0.2903


Confusion matrix:
 [[19 12  2  8]
 [18  8  2  3]
 [14  9  5  2]
 [ 3  5  4  2]]
Train  loss=2.3497 acc=0.2903 f1=0.2819 | Val loss=1.6913 acc=0.2931 f1=0.2542
  🔥 New best F1: 0.2542 – model saved.

Epoch 2/25


    t_loss=1.6084 | F1(macro)=0.3064 | Acc=0.3226


Confusion matrix:
 [[11  0 14 16]
 [ 6  0  8 17]
 [ 4  2 10 14]
 [ 5  0  5  4]]
Train  loss=1.6084 acc=0.3226 f1=0.3064 | Val loss=1.8338 acc=0.2155 f1=0.1875

Epoch 3/25


    t_loss=1.5158 | F1(macro)=0.3238 | Acc=0.3441


Confusion matrix:
 [[ 0  2 10 29]
 [ 1  4  7 19]
 [ 0  3  6 21]
 [ 0  2  1 11]]
Train  loss=1.5158 acc=0.3441 f1=0.3238 | Val loss=1.8119 acc=0.1810 f1=0.1617

Epoch 4/25


    t_loss=1.3563 | F1(macro)=0.3826 | Acc=0.4022


Confusion matrix:
 [[23  4  2 12]
 [10  7  2 12]
 [ 9  3  3 15]
 [ 5  1  1  7]]
Train  loss=1.3563 acc=0.4022 f1=0.3826 | Val loss=1.7308 acc=0.3448 f1=0.3046
  🔥 New best F1: 0.3046 – model saved.

Epoch 5/25


    t_loss=1.4467 | F1(macro)=0.3498 | Acc=0.3634


Confusion matrix:
 [[ 0  9  2 30]
 [ 1  5  2 23]
 [ 0  5  4 21]
 [ 0  1  0 13]]
Train  loss=1.4467 acc=0.3634 f1=0.3498 | Val loss=2.0224 acc=0.1897 f1=0.1660

Epoch 6/25


    t_loss=1.3311 | F1(macro)=0.3934 | Acc=0.4086


Confusion matrix:
 [[ 4  6 10 21]
 [ 2  5  2 22]
 [ 1  3  4 22]
 [ 3  0  2  9]]
Train  loss=1.3311 acc=0.4086 f1=0.3934 | Val loss=1.9617 acc=0.1897 f1=0.1876

Epoch 7/25


    t_loss=1.2090 | F1(macro)=0.4206 | Acc=0.4516


Confusion matrix:
 [[ 4  9  9 19]
 [ 2  8  4 17]
 [ 1  6  6 17]
 [ 1  3  2  8]]
Train  loss=1.2090 acc=0.4516 f1=0.4206 | Val loss=1.7985 acc=0.2241 f1=0.2231

Epoch 8/25


    t_loss=1.1311 | F1(macro)=0.4795 | Acc=0.4989


Confusion matrix:
 [[ 0  0  7 34]
 [ 0  0  5 26]
 [ 0  0  2 28]
 [ 0  1  2 11]]
Train  loss=1.1311 acc=0.4989 f1=0.4795 | Val loss=4.0947 acc=0.1121 f1=0.0704

Epoch 9/25


    t_loss=1.1444 | F1(macro)=0.4434 | Acc=0.4667


Confusion matrix:
 [[ 9 10  1 21]
 [ 6  8  1 16]
 [ 1  5  2 22]
 [ 2  2  0 10]]
Train  loss=1.1444 acc=0.4667 f1=0.4434 | Val loss=2.3970 acc=0.2500 f1=0.2374

Epoch 10/25


    t_loss=1.1498 | F1(macro)=0.4948 | Acc=0.4968


Confusion matrix:
 [[ 8 15  2 16]
 [ 6 16  0  9]
 [ 1  7  1 21]
 [ 1  2  2  9]]
Train  loss=1.1498 acc=0.4968 f1=0.4948 | Val loss=2.3235 acc=0.2931 f1=0.2624

Epoch 11/25


    t_loss=1.1832 | F1(macro)=0.4806 | Acc=0.4968


Confusion matrix:
 [[ 4  8  5 24]
 [ 3  9  2 17]
 [ 2  5  2 21]
 [ 0  2  2 10]]
Train  loss=1.1832 acc=0.4968 f1=0.4806 | Val loss=2.4226 acc=0.2155 f1=0.2043

Epoch 12/25


    t_loss=0.9774 | F1(macro)=0.5654 | Acc=0.5935


Confusion matrix:
 [[12  1 15 13]
 [ 6  4  8 13]
 [ 6  2  8 14]
 [ 1  0  5  8]]
Train  loss=0.9774 acc=0.5935 f1=0.5654 | Val loss=2.1967 acc=0.2759 f1=0.2687

Epoch 13/25


    t_loss=0.9667 | F1(macro)=0.6070 | Acc=0.6129


Confusion matrix:
 [[25  1  3 12]
 [18  5  1  7]
 [12  2  2 14]
 [ 6  0  2  6]]
Train  loss=0.9667 acc=0.6129 f1=0.6070 | Val loss=2.5605 acc=0.3276 f1=0.2696

Epoch 14/25


    t_loss=0.9260 | F1(macro)=0.5752 | Acc=0.5892


Confusion matrix:
 [[15  6  9 11]
 [ 7  6  6 12]
 [ 9  3  6 12]
 [ 4  1  3  6]]
Train  loss=0.9260 acc=0.5892 f1=0.5752 | Val loss=2.2814 acc=0.2845 f1=0.2726

Epoch 15/25


    t_loss=0.7872 | F1(macro)=0.6481 | Acc=0.6753


Confusion matrix:
 [[14 10  7 10]
 [ 9  8  6  8]
 [ 9  5  4 12]
 [ 4  0  3  7]]
Train  loss=0.7872 acc=0.6753 f1=0.6481 | Val loss=2.3131 acc=0.2845 f1=0.2736

Epoch 16/25


    t_loss=0.8256 | F1(macro)=0.6791 | Acc=0.6882


Confusion matrix:
 [[14  6 12  9]
 [ 9  3  9 10]
 [ 8  4  6 12]
 [ 4  0  3  7]]
Train  loss=0.8256 acc=0.6882 f1=0.6791 | Val loss=2.3483 acc=0.2586 f1=0.2435

Epoch 17/25


    t_loss=0.7914 | F1(macro)=0.6756 | Acc=0.6925


Confusion matrix:
 [[28  3  3  7]
 [13  7  4  7]
 [13  3  7  7]
 [ 5  0  2  7]]
Train  loss=0.7914 acc=0.6925 f1=0.6756 | Val loss=2.1196 acc=0.4224 f1=0.3790
  🔥 New best F1: 0.3790 – model saved.

Epoch 18/25


    t_loss=0.7762 | F1(macro)=0.6837 | Acc=0.6903


Confusion matrix:
 [[22  7  7  5]
 [18  5  3  5]
 [13  4  8  5]
 [ 5  0  3  6]]
Train  loss=0.7762 acc=0.6903 f1=0.6837 | Val loss=2.2948 acc=0.3534 f1=0.3284

Epoch 19/25


    t_loss=0.7597 | F1(macro)=0.7245 | Acc=0.7269


Confusion matrix:
 [[22  7  4  8]
 [13  9  3  6]
 [14  4  6  6]
 [ 6  0  1  7]]
Train  loss=0.7597 acc=0.7269 f1=0.7245 | Val loss=2.4267 acc=0.3793 f1=0.3564

Epoch 20/25


    t_loss=0.6746 | F1(macro)=0.7657 | Acc=0.7699


Confusion matrix:
 [[17  9  3 12]
 [12  7  5  7]
 [13  4  6  7]
 [ 4  1  2  7]]
Train  loss=0.6746 acc=0.7699 f1=0.7657 | Val loss=2.6168 acc=0.3190 f1=0.3047

Epoch 21/25


    t_loss=0.7205 | F1(macro)=0.7424 | Acc=0.7441


Confusion matrix:
 [[14 10 12  5]
 [10  7 10  4]
 [13  2 11  4]
 [ 4  0  3  7]]
Train  loss=0.7205 acc=0.7441 f1=0.7424 | Val loss=2.3216 acc=0.3362 f1=0.3416

Epoch 22/25


    t_loss=0.6185 | F1(macro)=0.7990 | Acc=0.8065


Confusion matrix:
 [[15  7 10  9]
 [ 9  5 10  7]
 [ 9  4  9  8]
 [ 4  0  3  7]]
Train  loss=0.6185 acc=0.8065 f1=0.7990 | Val loss=2.3510 acc=0.3103 f1=0.2997

Epoch 23/25


    t_loss=0.6564 | F1(macro)=0.7555 | Acc=0.7656


Confusion matrix:
 [[18 10  6  7]
 [12  7  7  5]
 [10  4  9  7]
 [ 4  0  3  7]]
Train  loss=0.6564 acc=0.7656 f1=0.7555 | Val loss=2.3728 acc=0.3534 f1=0.3425

Epoch 24/25


    t_loss=0.6724 | F1(macro)=0.7529 | Acc=0.7634


Confusion matrix:
 [[14 10 12  5]
 [10 10  7  4]
 [11  4 10  5]
 [ 4  0  3  7]]
Train  loss=0.6724 acc=0.7634 f1=0.7529 | Val loss=2.2932 acc=0.3534 f1=0.3591

Epoch 25/25


    t_loss=0.6365 | F1(macro)=0.7922 | Acc=0.8000


Confusion matrix:
 [[18  5 14  4]
 [14  4 10  3]
 [12  2 11  5]
 [ 4  0  3  7]]
Train  loss=0.6365 acc=0.8000 f1=0.7922 | Val loss=2.3096 acc=0.3448 f1=0.3357
Restored best weights for fold 3 (F1=0.3790)

========== Fold 4 ==========

Epoch 1/25


    t_loss=2.4059 | F1(macro)=0.2337 | Acc=0.2602


Confusion matrix:
 [[ 1 11 13 16]
 [ 1  5 11 14]
 [ 3  4  9 14]
 [ 0  2  3  9]]
Train  loss=2.4059 acc=0.2602 f1=0.2337 | Val loss=1.8278 acc=0.2069 f1=0.1934
  🔥 New best F1: 0.1934 – model saved.

Epoch 2/25


    t_loss=1.7929 | F1(macro)=0.2512 | Acc=0.2602


Confusion matrix:
 [[ 6  3 19 13]
 [ 8  4 14  5]
 [ 4  2 13 11]
 [ 2  1  7  4]]
Train  loss=1.7929 acc=0.2602 f1=0.2512 | Val loss=1.5714 acc=0.2328 f1=0.2188
  🔥 New best F1: 0.2188 – model saved.

Epoch 3/25


    t_loss=1.5373 | F1(macro)=0.3189 | Acc=0.3290


Confusion matrix:
 [[ 2 34  3  2]
 [ 2 22  1  6]
 [ 4 18  4  4]
 [ 3  7  0  4]]
Train  loss=1.5373 acc=0.3290 f1=0.3189 | Val loss=1.7166 acc=0.2759 f1=0.2367
  🔥 New best F1: 0.2367 – model saved.

Epoch 4/25


    t_loss=1.3924 | F1(macro)=0.3418 | Acc=0.3570


Confusion matrix:
 [[ 9 21  6  5]
 [ 6 18  4  3]
 [ 6 12  5  7]
 [ 2  4  4  4]]
Train  loss=1.3924 acc=0.3570 f1=0.3418 | Val loss=1.8478 acc=0.3103 f1=0.2866
  🔥 New best F1: 0.2866 – model saved.

Epoch 5/25


    t_loss=1.3824 | F1(macro)=0.3979 | Acc=0.4194


Confusion matrix:
 [[ 1 18 16  6]
 [ 2 12 11  6]
 [ 1 11  8 10]
 [ 0  1  8  5]]
Train  loss=1.3824 acc=0.4194 f1=0.3979 | Val loss=1.8365 acc=0.2241 f1=0.2091

Epoch 6/25


    t_loss=1.3592 | F1(macro)=0.4003 | Acc=0.4129


Confusion matrix:
 [[23  4  4 10]
 [11  5  2 13]
 [18  1  2  9]
 [ 5  0  2  7]]
Train  loss=1.3592 acc=0.4129 f1=0.4003 | Val loss=1.5992 acc=0.3190 f1=0.2694

Epoch 7/25


    t_loss=1.2557 | F1(macro)=0.4062 | Acc=0.4409


Confusion matrix:
 [[ 2  7 25  7]
 [ 2 12 12  5]
 [ 0  6 16  8]
 [ 0  2 10  2]]
Train  loss=1.2557 acc=0.4409 f1=0.4062 | Val loss=1.8752 acc=0.2759 f1=0.2395

Epoch 8/25


    t_loss=1.2140 | F1(macro)=0.4355 | Acc=0.4452


Confusion matrix:
 [[ 6  9 15 11]
 [ 4 13  7  7]
 [ 8  7  9  6]
 [ 4  1  5  4]]
Train  loss=1.2140 acc=0.4452 f1=0.4355 | Val loss=1.7401 acc=0.2759 f1=0.2700

Epoch 9/25


    t_loss=1.1787 | F1(macro)=0.4686 | Acc=0.4817


Confusion matrix:
 [[21  2 14  4]
 [14  8  4  5]
 [15  1  7  7]
 [ 5  0  8  1]]
Train  loss=1.1787 acc=0.4817 f1=0.4686 | Val loss=1.7024 acc=0.3190 f1=0.2763

Epoch 10/25


    t_loss=1.1444 | F1(macro)=0.4911 | Acc=0.4989


Confusion matrix:
 [[ 7 15 16  3]
 [ 4 19  4  4]
 [ 6 10 10  4]
 [ 2  3  6  3]]
Train  loss=1.1444 acc=0.4989 f1=0.4911 | Val loss=1.8459 acc=0.3362 f1=0.3095
  🔥 New best F1: 0.3095 – model saved.

Epoch 11/25


    t_loss=1.0364 | F1(macro)=0.5194 | Acc=0.5355


Confusion matrix:
 [[16  6 12  7]
 [10 15  6  0]
 [15  5  5  5]
 [ 5  2  4  3]]
Train  loss=1.0364 acc=0.5355 f1=0.5194 | Val loss=2.0101 acc=0.3362 f1=0.3147
  🔥 New best F1: 0.3147 – model saved.

Epoch 12/25


    t_loss=0.9865 | F1(macro)=0.5591 | Acc=0.5871


Confusion matrix:
 [[ 4  6 27  4]
 [ 4 15 12  0]
 [ 1  8 18  3]
 [ 2  2 10  0]]
Train  loss=0.9865 acc=0.5871 f1=0.5591 | Val loss=2.2315 acc=0.3190 f1=0.2522

Epoch 13/25


    t_loss=0.9442 | F1(macro)=0.5739 | Acc=0.5914


Confusion matrix:
 [[10 15 11  5]
 [ 6 16  7  2]
 [ 5  7 11  7]
 [ 6  4  2  2]]
Train  loss=0.9442 acc=0.5914 f1=0.5739 | Val loss=1.9340 acc=0.3362 f1=0.3066

Epoch 14/25


    t_loss=0.9620 | F1(macro)=0.5886 | Acc=0.6108


Confusion matrix:
 [[ 9 19 11  2]
 [10 16  3  2]
 [ 7 11  9  3]
 [ 4  3  6  1]]
Train  loss=0.9620 acc=0.6108 f1=0.5886 | Val loss=2.1497 acc=0.3017 f1=0.2624

Epoch 15/25


    t_loss=0.8352 | F1(macro)=0.6558 | Acc=0.6645


Confusion matrix:
 [[15 14  7  5]
 [ 9 16  2  4]
 [11  8  7  4]
 [ 4  5  2  3]]
Train  loss=0.8352 acc=0.6645 f1=0.6558 | Val loss=2.0029 acc=0.3534 f1=0.3248
  🔥 New best F1: 0.3248 – model saved.

Epoch 16/25


    t_loss=0.8300 | F1(macro)=0.6585 | Acc=0.6688


Confusion matrix:
 [[ 9  6 20  6]
 [ 7 14  5  5]
 [ 6  6 13  5]
 [ 3  2  5  4]]
Train  loss=0.8300 acc=0.6688 f1=0.6585 | Val loss=2.1687 acc=0.3448 f1=0.3347
  🔥 New best F1: 0.3347 – model saved.

Epoch 17/25


    t_loss=0.8030 | F1(macro)=0.6633 | Acc=0.6731


Confusion matrix:
 [[ 3 13 18  7]
 [ 8 17  3  3]
 [ 3 11 11  5]
 [ 4  1  5  4]]
Train  loss=0.8030 acc=0.6731 f1=0.6633 | Val loss=2.2002 acc=0.3017 f1=0.2846

Epoch 18/25


    t_loss=0.7932 | F1(macro)=0.6775 | Acc=0.6882


Confusion matrix:
 [[ 6  7 21  7]
 [ 7 13  7  4]
 [ 4  8 16  2]
 [ 2  2  7  3]]
Train  loss=0.7932 acc=0.6882 f1=0.6775 | Val loss=2.3434 acc=0.3276 f1=0.3053

Epoch 19/25


    t_loss=0.7478 | F1(macro)=0.7220 | Acc=0.7269


Confusion matrix:
 [[10 10 15  6]
 [ 9 15  5  2]
 [11  6 10  3]
 [ 6  0  5  3]]
Train  loss=0.7478 acc=0.7269 f1=0.7220 | Val loss=2.2009 acc=0.3276 f1=0.3164

Epoch 20/25


    t_loss=0.7129 | F1(macro)=0.7186 | Acc=0.7290


Confusion matrix:
 [[22  6 12  1]
 [18 11  2  0]
 [12  6  9  3]
 [ 9  1  4  0]]
Train  loss=0.7129 acc=0.7290 f1=0.7186 | Val loss=2.3391 acc=0.3621 f1=0.2868

Epoch 21/25


    t_loss=0.6707 | F1(macro)=0.7567 | Acc=0.7656


Confusion matrix:
 [[ 7 13 16  5]
 [13 12  5  1]
 [ 8  8 10  4]
 [ 4  2  7  1]]
Train  loss=0.6707 acc=0.7656 f1=0.7567 | Val loss=2.1827 acc=0.2586 f1=0.2324

Epoch 22/25


    t_loss=0.6517 | F1(macro)=0.7592 | Acc=0.7677


Confusion matrix:
 [[13  7 14  7]
 [14 10  4  3]
 [ 8  6 13  3]
 [ 5  1  7  1]]
Train  loss=0.6517 acc=0.7677 f1=0.7592 | Val loss=2.1466 acc=0.3190 f1=0.2846

Epoch 23/25


    t_loss=0.6407 | F1(macro)=0.7953 | Acc=0.8043


Confusion matrix:
 [[ 8 12 17  4]
 [14 11  6  0]
 [ 5 10 12  3]
 [ 4  3  7  0]]
Train  loss=0.6407 acc=0.8043 f1=0.7953 | Val loss=2.2592 acc=0.2672 f1=0.2210

Epoch 24/25


    t_loss=0.6544 | F1(macro)=0.7608 | Acc=0.7677


Confusion matrix:
 [[ 9 14 10  8]
 [13 13  3  2]
 [10  6 10  4]
 [ 6  0  6  2]]
Train  loss=0.6544 acc=0.7677 f1=0.7608 | Val loss=2.1635 acc=0.2931 f1=0.2766

Epoch 25/25


    t_loss=0.6097 | F1(macro)=0.7715 | Acc=0.7806


Confusion matrix:
 [[ 8 15 14  4]
 [11 15  3  2]
 [ 7  8 11  4]
 [ 6  2  6  0]]
Train  loss=0.6097 acc=0.7806 f1=0.7715 | Val loss=2.2208 acc=0.2931 f1=0.2464
Restored best weights for fold 4 (F1=0.3347)


# tf_efficientnetv2_s.in21k

In [7]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts_np = train_df["label_idx"].value_counts().sort_index().values
        class_counts = torch.tensor(class_counts_np, dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [8]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts_np = train_df["label_idx"].value_counts().sort_index().values
        class_counts = torch.tensor(class_counts_np, dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [9]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1 else "tf_effb1_ns"

FOLD_VAL_F1 = f"fold_val_f1_{prefix_filename}.json"

# Save best F1 per fold to JSON
with open(FOLD_VAL_F1, "w") as f:
    json.dump(best_f1_per_fold, f, indent=2)

In [10]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=data.image_size,
    is_train=False,   # deterministic, returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=1,               # per-image TTA
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

if os.path.exists(FOLD_VAL_F1):
    with open(FOLD_VAL_F1, "r") as f:
        best_f1_per_fold = json.load(f)
    val_f1_per_fold = np.array([best_f1_per_fold[str(k)] for k in range(data.num_K_folds)])
    # Normalize to get weights that sum to 1
    fold_weights = val_f1_per_fold / val_f1_per_fold.sum()
else:
    # fallback: uniform weights if metrics are missing
    print('Warning: fold validation F1 scores not found, using uniform weights.')
    fold_weights = np.ones(data.num_K_folds, dtype=np.float32) / data.num_K_folds

print("Fold weights:", fold_weights)

# -----------------------------
# 2) Accumulate weighted probs
# -----------------------------
all_probs = None
all_sample_indices = None

for fold in range(data.num_K_folds):
    print(f"Inference with fold {fold} model (weight={fold_weights[fold]:.3f})")

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0:
        model = create_efficientnet_b0_model(pretrained=False)
    else:
        model = create_efficientnet_b1_ns_model(pretrained=False)

    state_dict = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            # img_tensor: [1, 4, H, W]  (RGB+mask)
            img_tensor = img_tensor.squeeze(0).to(device)  # [4, H, W]

            # -------- TTA: mask-based multi-crop + simple flips --------
            USE_MASK_TTA = False
            if USE_MASK_TTA:
                tta_tensors = apply_mask_multicrop_tta(img_tensor, crop_size=data.image_size, n_crops=2)
            else:
                tta_tensors = apply_multicrop_tta(img_tensor, base_size=data.image_size, inner_ratio=0.8)


            # accumulate probability predictions
            probs_sum = 0.0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1, 4, H, W]
                with torch.no_grad():
                    logits = model(aug_img)
                    probs = softmax(logits, dim=1)  # [1, N_CLASSES]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N_test, N_CLASSES]

    # initialize global probs
    if all_probs is None:
        all_probs = np.zeros_like(fold_probs, dtype=np.float32)

     # weighted accumulation
    all_probs += fold_weights[fold] * fold_probs

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# -----------------------------
# 3) Final predictions
# -----------------------------
pred_indices = all_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print(f"Saved submission_5fold_tta_{prefix_filename}.csv")

Fold weights: [0.19506465 0.22549999 0.18295069 0.21054129 0.18594338]
Inference with fold 0 model (weight=0.195)
Inference with fold 1 model (weight=0.225)
Inference with fold 2 model (weight=0.183)
Inference with fold 3 model (weight=0.211)
Inference with fold 4 model (weight=0.186)
Saved submission_5fold_tta_tf_effb1_ns.csv


In [11]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(data.num_K_folds):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=data.image_size,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.29210321231227154
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.4133289955658377
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.2738230638252588
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.3561538219775989
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.35601169663669663
Mean OOF F1: 0.3382841580635327
