In [1]:
import enum
import json
import os
from copy import deepcopy

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from timm.utils import ModelEmaV2
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader
from tqdm import tqdm

from internal.data_types import HistologyDataset
from internal.nn.dual_path_net import DualPathNet
from internal.nn.mixup_cutmix_wrapper import MixupCutmixWrapper
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_multicrop_tta, apply_mask_multicrop_tta
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    EFFICIENTNET_B1_NS = "tf_efficientnet_b1.ns_jft_in1k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B1_NS

In [4]:
best_f1_per_fold: dict[int, int] = {}
N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
N_CLASSES = 4  # number of classes in the dataset (labels)
EMA_DECAY = 0.995

# efficientnet_b0 / efficientnet_b1

In [5]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,          # Dropout
        drop_path_rate=0.1      # Stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    For EfficientNet from timm: unfreeze last 2 blocks + classifier head.
    """
    freeze_all(model)

    # Last 2 conv blocks
    if hasattr(model, "blocks"):
        for blk in model.blocks[-2:]:
            for p in blk.parameters():
                p.requires_grad = True

    # Classifier head
    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True


if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    GRAD_ACCUM_STEPS = 2
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 25
    LR = 3e-4
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b0_model(pretrained=True)
        unfreeze_last_two_blocks_and_head(model)

        # ---- loss, optimizer, scheduler ----
        class_counts_np = train_df["label_idx"].value_counts().sort_index().values
        class_counts = torch.tensor(class_counts_np, dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.1
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None
        mixup_fn = MixupCutmixWrapper(
            alpha=0.4,       # mixup/cutmix Beta distribution
            mixup_prob=0.4,  # 40% of batches => mixup
            cutmix_prob=0.2  # 20% of batches => cutmix
        )

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device, grad_accum_steps=GRAD_ACCUM_STEPS, mixup_fn=mixup_fn
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(
                    best_state,
                    f"best_effb0_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best weights for this fold
        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1

# tf_efficientnet_b1_ns

In [6]:
def create_efficientnet_b1_ns_model(pretrained: bool = True) -> nn.Module:
    # model = DualPathNet(
    #     backbone_name=MODEL_TO_USE.value,
    #     num_classes=N_CLASSES,
    #     pretrained=pretrained,
    #     mask_feat_dim=128,
    #     drop_rate=0.4,       # stronger dropout than B0
    #     drop_path_rate=0.15  # stochastic depth
    # ).to(device)
    model = timm.create_model(
        MODEL_TO_USE.value,           # tf_efficientnet_b1_ns
        pretrained=True,
        num_classes=N_CLASSES,
        in_chans=4,                   # 3 RGB + 1 mask
        drop_rate=0.4,
        drop_path_rate=0.15
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = True

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    Freeze earlier EfficientNet blocks, unfreeze the last two + head.
    Works for timm tf_efficientnet_b* models.
    """
    # 1) Freeze everything by default
    for p in model.parameters():
        p.requires_grad = False

    # 2) Unfreeze last two blocks
    # model.blocks is a nn.Sequential
    num_blocks = len(model.blocks)
    for idx in range(num_blocks - 2, num_blocks):
        for p in model.blocks[idx].parameters():
            p.requires_grad = True

    # 3) Unfreeze conv_head + bn2 + classifier
    for p in model.conv_head.parameters():
        p.requires_grad = True
    for p in model.bn2.parameters():
        p.requires_grad = True
    for p in model.classifier.parameters():
        p.requires_grad = True

def unfreeze_last_block_and_head(model: nn.Module, n_blocks: int = 2):
    # 1) freeze everything
    for p in model.parameters():
        p.requires_grad = False

    # 2) unfreeze last n_blocks of the RGB backbone
    # efficientnet-style timm models have .blocks
    if hasattr(model.rgb_backbone, "blocks"):
        for block in model.rgb_backbone.blocks[-n_blocks:]:
            for p in block.parameters():
                p.requires_grad = True
    else:
        # fallback: unfreeze entire backbone if the structure is different
        for p in model.rgb_backbone.parameters():
            p.requires_grad = True

    # 3) always train mask branch + fusion classifier
    for p in model.mask_branch.parameters():
        p.requires_grad = True
    for p in model.mask_fc.parameters():
        p.requires_grad = True
    for p in model.classifier.parameters():
        p.requires_grad = True


def unfreeze_last_stage_and_head(model: nn.Module):
    """
    EfficientNet B1-NS recommended fine-tuning strategy:
    - Freeze all early MBConv stages
    - Unfreeze the last MBConv stage (stage 6)
    - Unfreeze conv_head + bn2 + classifier
    """

    # Freeze everything first
    for p in model.parameters():
        p.requires_grad = False

    # ---- Unfreeze last stage (stage 6) ----
    # EfficientNet blocks are sequential but grouped in stages.
    # B1 layout roughly:
    #   Stage0: stem
    #   Stage1: blocks[0]
    #   Stage2: blocks[1:3]
    #   Stage3: blocks[3:5]
    #   Stage4: blocks[5:8]
    #   Stage5: blocks[8:11]
    #   Stage6: blocks[11:15]  <-- last stage
    last_stage_start = len(model.blocks) - 4  # 4 blocks in last stage (B1)
    for idx in range(last_stage_start, len(model.blocks)):
        for p in model.blocks[idx].parameters():
            p.requires_grad = True

    # ---- Unfreeze head ----
    for p in model.conv_head.parameters():
        p.requires_grad = True
    for p in model.bn2.parameters():
        p.requires_grad = True
    for p in model.classifier.parameters():
        p.requires_grad = True

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1_NS:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    GRAD_ACCUM_STEPS = 2
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 30
    LR = 3e-4
    WEIGHT_DECAY = 5e-4
    PREFIX = "tf_effb1_ns"
    USE_EMA = False
    USE_MIXUP_CUTMIX = False
    USE_FREEZE_TECHNIQUE = False

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,          # Augmentations applied
            use_mask_crop=True,
            apply_artifact_augs=False,
            patch_mode=False,       # Use patch-based training
            patches_per_image=3,    # Add 3 random patches per image
            patch_size=384          # 384x384 patches
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True,
            apply_artifact_augs=False,
            patch_mode=False
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b1_ns_model(pretrained=True)
        unfreeze_all(model)
        if USE_FREEZE_TECHNIQUE:
            unfreeze_last_block_and_head(model)

        # --- EMA ---
        ema_model = ModelEmaV2(model, decay=EMA_DECAY, device=device) if USE_EMA else None

        # ---- loss, optimizer, scheduler ----
        class_counts_np = train_df_split["label_idx"].value_counts().sort_index().values
        class_counts = torch.tensor(class_counts_np, dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.05
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=WEIGHT_DECAY
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None
        mixup_fn = MixupCutmixWrapper(
            alpha=0.4,       # mixup/cutmix Beta distribution
            mixup_prob=0.4,  # 40% of batches => mixup
            cutmix_prob=0.2  # 20% of batches => cutmix
        ) if USE_MIXUP_CUTMIX else None

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model,
                train_loader,
                optimizer,
                criterion,
                device,
                grad_accum_steps=GRAD_ACCUM_STEPS,
                mixup_fn=mixup_fn,
                ema_model=ema_model
            )

            val_loss, val_acc, val_f1 = validate(
                ema_model.module if ema_model else model,   # use EMA weights for validation
                val_loader,
                criterion,
                device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(
                    ema_model.module.state_dict()
                    if ema_model else model.state_dict()
                )
                torch.save(
                    best_state,
                    f"best_{PREFIX}_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best EMA weights for this fold
        if best_state is not None:
            if USE_EMA:
                ema_model.module.load_state_dict(best_state)
            else:
                model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        if USE_EMA:
            torch.save(ema_model.module.state_dict(), f"{PREFIX}_fold{fold}.pth")
        else:
            torch.save(model.state_dict(), f"{PREFIX}_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1


========== Fold 0 ==========

Epoch 1/30


    t_loss=2.1944 | F1(macro)=0.2670 | Acc=0.2759


Confusion matrix:
 [[ 1  9  2 29]
 [ 2 15  0 15]
 [ 3 10  0 17]
 [ 1  5  0  8]]
Train  loss=2.1944 acc=0.2759 f1=0.2670 | Val loss=2.2463 acc=0.2051 f1=0.1642
  🔥 New best F1: 0.1642 – model saved.

Epoch 2/30


    t_loss=1.7477 | F1(macro)=0.2964 | Acc=0.3125


Confusion matrix:
 [[ 2  4  6 29]
 [ 0  9  6 17]
 [ 0  1  8 21]
 [ 0  1  3 10]]
Train  loss=1.7477 acc=0.3125 f1=0.2964 | Val loss=2.1572 acc=0.2479 f1=0.2494
  🔥 New best F1: 0.2494 – model saved.

Epoch 3/30


    t_loss=1.5742 | F1(macro)=0.3583 | Acc=0.3707


Confusion matrix:
 [[ 6 11  8 16]
 [ 6 11 11  4]
 [ 2  8 10 10]
 [ 0  5  4  5]]
Train  loss=1.5742 acc=0.3707 f1=0.3583 | Val loss=1.6754 acc=0.2735 f1=0.2670
  🔥 New best F1: 0.2670 – model saved.

Epoch 4/30


    t_loss=1.4197 | F1(macro)=0.3602 | Acc=0.3728


Confusion matrix:
 [[ 6  8 15 12]
 [ 5  4 17  6]
 [ 6  7  9  8]
 [ 1  3  6  4]]
Train  loss=1.4197 acc=0.3728 f1=0.3602 | Val loss=1.7823 acc=0.1966 f1=0.1918

Epoch 5/30


    t_loss=1.4350 | F1(macro)=0.3226 | Acc=0.3491


Confusion matrix:
 [[ 1  9  2 29]
 [ 2  9  2 19]
 [ 2  4  1 23]
 [ 0  0  1 13]]
Train  loss=1.4350 acc=0.3491 f1=0.3226 | Val loss=1.9139 acc=0.2051 f1=0.1744

Epoch 6/30


    t_loss=1.2956 | F1(macro)=0.4084 | Acc=0.4397


Confusion matrix:
 [[ 5 13 10 13]
 [ 6  9 11  6]
 [ 7  8 11  4]
 [ 0  5  2  7]]
Train  loss=1.2956 acc=0.4397 f1=0.4084 | Val loss=1.6288 acc=0.2735 f1=0.2750
  🔥 New best F1: 0.2750 – model saved.

Epoch 7/30


    t_loss=1.2485 | F1(macro)=0.4334 | Acc=0.4461


Confusion matrix:
 [[ 3  6 22 10]
 [ 4  3 16  9]
 [ 4  3 14  9]
 [ 2  1  6  5]]
Train  loss=1.2485 acc=0.4461 f1=0.4334 | Val loss=1.7955 acc=0.2137 f1=0.1938

Epoch 8/30


    t_loss=1.1888 | F1(macro)=0.4802 | Acc=0.4978


Confusion matrix:
 [[ 1 13 11 16]
 [ 3 12  6 11]
 [ 1  8 10 11]
 [ 1  1  2 10]]
Train  loss=1.1888 acc=0.4978 f1=0.4802 | Val loss=1.7913 acc=0.2821 f1=0.2669

Epoch 9/30


    t_loss=1.2499 | F1(macro)=0.4328 | Acc=0.4504


Confusion matrix:
 [[11  8  7 15]
 [12  7  7  6]
 [15  3  5  7]
 [ 4  4  1  5]]
Train  loss=1.2499 acc=0.4504 f1=0.4328 | Val loss=1.7988 acc=0.2393 f1=0.2343

Epoch 10/30


    t_loss=1.0495 | F1(macro)=0.4984 | Acc=0.5216


Confusion matrix:
 [[11  2 16 12]
 [ 5  5 16  6]
 [ 9  2 11  8]
 [ 3  0  6  5]]
Train  loss=1.0495 acc=0.5216 f1=0.4984 | Val loss=2.0462 acc=0.2735 f1=0.2659

Epoch 11/30


    t_loss=0.9739 | F1(macro)=0.5440 | Acc=0.5560


Confusion matrix:
 [[16  3 11 11]
 [14  3  9  6]
 [14  0 10  6]
 [ 3  1  6  4]]
Train  loss=0.9739 acc=0.5560 f1=0.5440 | Val loss=1.8885 acc=0.2821 f1=0.2539

Epoch 12/30


    t_loss=0.9442 | F1(macro)=0.5901 | Acc=0.6121


Confusion matrix:
 [[ 6 11  5 19]
 [ 9  6  4 13]
 [ 9  4  5 12]
 [ 1  0  3 10]]
Train  loss=0.9442 acc=0.6121 f1=0.5901 | Val loss=2.0120 acc=0.2308 f1=0.2288

Epoch 13/30


    t_loss=1.0391 | F1(macro)=0.5297 | Acc=0.5409


Confusion matrix:
 [[12 17  2 10]
 [ 5 14  5  8]
 [ 8  8 10  4]
 [ 3  3  5  3]]
Train  loss=1.0391 acc=0.5409 f1=0.5297 | Val loss=1.8370 acc=0.3333 f1=0.3162
  🔥 New best F1: 0.3162 – model saved.

Epoch 14/30


    t_loss=0.8851 | F1(macro)=0.6163 | Acc=0.6358


Confusion matrix:
 [[17  6  8 10]
 [13  4  8  7]
 [11  7  9  3]
 [ 2  3  5  4]]
Train  loss=0.8851 acc=0.6358 f1=0.6163 | Val loss=1.8324 acc=0.2906 f1=0.2673

Epoch 15/30


    t_loss=0.9736 | F1(macro)=0.5720 | Acc=0.5819


Confusion matrix:
 [[11 13  9  8]
 [10  4 11  7]
 [ 4  8 11  7]
 [ 2  3  5  4]]
Train  loss=0.9736 acc=0.5819 f1=0.5720 | Val loss=1.7834 acc=0.2564 f1=0.2475

Epoch 16/30


    t_loss=0.8376 | F1(macro)=0.6184 | Acc=0.6336


Confusion matrix:
 [[17 12  4  8]
 [11  5 10  6]
 [ 7  5 10  8]
 [ 4  2  3  5]]
Train  loss=0.8376 acc=0.6336 f1=0.6184 | Val loss=1.7664 acc=0.3162 f1=0.2996

Epoch 17/30


    t_loss=0.8728 | F1(macro)=0.6222 | Acc=0.6336


Confusion matrix:
 [[11  9 12  9]
 [ 9  6 10  7]
 [ 8  4 13  5]
 [ 2  3  5  4]]
Train  loss=0.8728 acc=0.6336 f1=0.6222 | Val loss=1.8107 acc=0.2906 f1=0.2772

Epoch 18/30


    t_loss=0.7488 | F1(macro)=0.6805 | Acc=0.7004


Confusion matrix:
 [[20  7  8  6]
 [ 8  6 13  5]
 [11  4 13  2]
 [ 3  2  5  4]]
Train  loss=0.7488 acc=0.7004 f1=0.6805 | Val loss=1.7862 acc=0.3675 f1=0.3380
  🔥 New best F1: 0.3380 – model saved.

Epoch 19/30


    t_loss=0.8024 | F1(macro)=0.6693 | Acc=0.6767


Confusion matrix:
 [[16  8  9  8]
 [ 8  7 10  7]
 [ 7  5 11  7]
 [ 3  3  4  4]]
Train  loss=0.8024 acc=0.6767 f1=0.6693 | Val loss=1.8338 acc=0.3248 f1=0.3062

Epoch 20/30


    t_loss=0.7519 | F1(macro)=0.7173 | Acc=0.7263


Confusion matrix:
 [[19  6  8  8]
 [12  7  9  4]
 [10  6 13  1]
 [ 3  4  5  2]]
Train  loss=0.7519 acc=0.7263 f1=0.7173 | Val loss=1.7845 acc=0.3504 f1=0.3099

Epoch 21/30


    t_loss=0.6920 | F1(macro)=0.6873 | Acc=0.7026


Confusion matrix:
 [[20  5  7  9]
 [11  5  9  7]
 [ 7  3 14  6]
 [ 3  4  4  3]]
Train  loss=0.6920 acc=0.7026 f1=0.6873 | Val loss=1.8204 acc=0.3590 f1=0.3208

Epoch 22/30


    t_loss=0.6702 | F1(macro)=0.7059 | Acc=0.7263


Confusion matrix:
 [[16  3  9 13]
 [11  6  8  7]
 [ 9  4 11  6]
 [ 2  2  4  6]]
Train  loss=0.6702 acc=0.7263 f1=0.7059 | Val loss=1.8362 acc=0.3333 f1=0.3190

Epoch 23/30


    t_loss=0.6033 | F1(macro)=0.7471 | Acc=0.7672


Confusion matrix:
 [[20  6 12  3]
 [14  5 10  3]
 [13  4 11  2]
 [ 3  4  4  3]]
Train  loss=0.6033 acc=0.7672 f1=0.7471 | Val loss=1.8366 acc=0.3333 f1=0.3010

Epoch 24/30


    t_loss=0.6645 | F1(macro)=0.7297 | Acc=0.7349


Confusion matrix:
 [[18  4 13  6]
 [13  3 12  4]
 [11  2 14  3]
 [ 3  2  6  3]]
Train  loss=0.6645 acc=0.7349 f1=0.7297 | Val loss=1.9202 acc=0.3248 f1=0.2829

Epoch 25/30


    t_loss=0.6527 | F1(macro)=0.7533 | Acc=0.7478


Confusion matrix:
 [[22  3 10  6]
 [15  4 10  3]
 [12  2 10  6]
 [ 3  1  6  4]]
Train  loss=0.6527 acc=0.7478 f1=0.7533 | Val loss=1.8903 acc=0.3419 f1=0.3023

Epoch 26/30


    t_loss=0.6305 | F1(macro)=0.7660 | Acc=0.7737


Confusion matrix:
 [[20  6  8  7]
 [11  7 10  4]
 [12  4 10  4]
 [ 3  4  4  3]]
Train  loss=0.6305 acc=0.7737 f1=0.7660 | Val loss=1.8496 acc=0.3419 f1=0.3085

Epoch 27/30


    t_loss=0.6132 | F1(macro)=0.7441 | Acc=0.7629


Confusion matrix:
 [[18  5  9  9]
 [11  6  9  6]
 [10  3 10  7]
 [ 3  4  4  3]]
Train  loss=0.6132 acc=0.7629 f1=0.7441 | Val loss=1.8846 acc=0.3162 f1=0.2875

Epoch 28/30


    t_loss=0.6032 | F1(macro)=0.7822 | Acc=0.7888


Confusion matrix:
 [[20  8  5  8]
 [13  8  7  4]
 [10  4 11  5]
 [ 3  3  4  4]]
Train  loss=0.6032 acc=0.7888 f1=0.7822 | Val loss=1.8469 acc=0.3675 f1=0.3413
  🔥 New best F1: 0.3413 – model saved.

Epoch 29/30


    t_loss=0.5736 | F1(macro)=0.7602 | Acc=0.7737


Confusion matrix:
 [[20  8  7  6]
 [12  7  9  4]
 [11  4 11  4]
 [ 4  2  4  4]]
Train  loss=0.5736 acc=0.7737 f1=0.7602 | Val loss=1.8442 acc=0.3590 f1=0.3323

Epoch 30/30


    t_loss=0.6239 | F1(macro)=0.7836 | Acc=0.7888


Confusion matrix:
 [[22  2  7 10]
 [12  5  9  6]
 [10  2 11  7]
 [ 3  3  4  4]]
Train  loss=0.6239 acc=0.7888 f1=0.7836 | Val loss=1.8450 acc=0.3590 f1=0.3208
Restored best weights for fold 0 (F1=0.3413)

========== Fold 1 ==========

Epoch 1/30


    t_loss=2.1627 | F1(macro)=0.2800 | Acc=0.2925


Confusion matrix:
 [[ 3 14  9 15]
 [ 0 15 10  7]
 [ 2  7 13  8]
 [ 1  2  4  6]]
Train  loss=2.1627 acc=0.2925 f1=0.2800 | Val loss=1.9401 acc=0.3190 f1=0.2988
  🔥 New best F1: 0.2988 – model saved.

Epoch 2/30


    t_loss=1.7189 | F1(macro)=0.2907 | Acc=0.3118


Confusion matrix:
 [[11  1  1 28]
 [ 8  5  4 15]
 [11  0  0 19]
 [ 4  0  1  8]]
Train  loss=1.7189 acc=0.3118 f1=0.2907 | Val loss=2.1765 acc=0.2069 f1=0.1873

Epoch 3/30


    t_loss=1.5022 | F1(macro)=0.3359 | Acc=0.3548


Confusion matrix:
 [[ 2  8 13 18]
 [ 2 10  7 13]
 [ 0  8  8 14]
 [ 2  1  2  8]]
Train  loss=1.5022 acc=0.3548 f1=0.3359 | Val loss=2.0107 acc=0.2414 f1=0.2333

Epoch 4/30


    t_loss=1.4232 | F1(macro)=0.3665 | Acc=0.3828


Confusion matrix:
 [[ 2  4 21 14]
 [ 2  7 12 11]
 [ 0  2 18 10]
 [ 3  1  5  4]]
Train  loss=1.4232 acc=0.3828 f1=0.3665 | Val loss=1.8341 acc=0.2672 f1=0.2400

Epoch 5/30


    t_loss=1.3791 | F1(macro)=0.3962 | Acc=0.4129


Confusion matrix:
 [[15  2 21  3]
 [10  8 14  0]
 [11  2 16  1]
 [ 6  1  5  1]]
Train  loss=1.3791 acc=0.4129 f1=0.3962 | Val loss=1.8649 acc=0.3448 f1=0.3001
  🔥 New best F1: 0.3001 – model saved.

Epoch 6/30


    t_loss=1.3306 | F1(macro)=0.3853 | Acc=0.3978


Confusion matrix:
 [[12  4  7 18]
 [ 5 11  6 10]
 [ 5  2 10 13]
 [ 4  0  2  7]]
Train  loss=1.3306 acc=0.3978 f1=0.3853 | Val loss=1.7741 acc=0.3448 f1=0.3501
  🔥 New best F1: 0.3501 – model saved.

Epoch 7/30


    t_loss=1.3232 | F1(macro)=0.4458 | Acc=0.4473


Confusion matrix:
 [[ 3 17 10 11]
 [ 2 21  5  4]
 [ 3  7 10 10]
 [ 3  1  3  6]]
Train  loss=1.3232 acc=0.4473 f1=0.4458 | Val loss=1.6869 acc=0.3448 f1=0.3179

Epoch 8/30


    t_loss=1.2408 | F1(macro)=0.4594 | Acc=0.4774


Confusion matrix:
 [[ 3  5 24  9]
 [ 3  9 16  4]
 [ 5  1 14 10]
 [ 2  3  4  4]]
Train  loss=1.2408 acc=0.4774 f1=0.4594 | Val loss=1.8094 acc=0.2586 f1=0.2473

Epoch 9/30


    t_loss=1.1753 | F1(macro)=0.4840 | Acc=0.4925


Confusion matrix:
 [[ 9 14  7 11]
 [ 2 23  4  3]
 [12  2  8  8]
 [ 2  5  1  5]]
Train  loss=1.1753 acc=0.4925 f1=0.4840 | Val loss=1.7705 acc=0.3879 f1=0.3620
  🔥 New best F1: 0.3620 – model saved.

Epoch 10/30


    t_loss=1.0494 | F1(macro)=0.5247 | Acc=0.5613


Confusion matrix:
 [[ 4  3 20 14]
 [ 4  7 14  7]
 [ 5  1 17  7]
 [ 2  0  4  7]]
Train  loss=1.0494 acc=0.5613 f1=0.5247 | Val loss=1.8592 acc=0.3017 f1=0.2900

Epoch 11/30


    t_loss=1.0455 | F1(macro)=0.5411 | Acc=0.5591


Confusion matrix:
 [[ 1 14 14 12]
 [ 3 15  5  9]
 [ 2  5  8 15]
 [ 0  4  2  7]]
Train  loss=1.0455 acc=0.5591 f1=0.5411 | Val loss=2.0293 acc=0.2672 f1=0.2481

Epoch 12/30


    t_loss=1.0736 | F1(macro)=0.5157 | Acc=0.5290


Confusion matrix:
 [[ 5  8 22  6]
 [ 4 16  6  6]
 [ 7  2 15  6]
 [ 2  1  5  5]]
Train  loss=1.0736 acc=0.5290 f1=0.5157 | Val loss=1.8417 acc=0.3534 f1=0.3436

Epoch 13/30


    t_loss=0.9850 | F1(macro)=0.5803 | Acc=0.5978


Confusion matrix:
 [[ 3  6 15 17]
 [ 4 10  7 11]
 [ 5  2 15  8]
 [ 2  0  4  7]]
Train  loss=0.9850 acc=0.5978 f1=0.5803 | Val loss=2.0941 acc=0.3017 f1=0.2954

Epoch 14/30


    t_loss=0.8895 | F1(macro)=0.6125 | Acc=0.6366


Confusion matrix:
 [[ 5  6 14 16]
 [ 5 11  4 12]
 [ 3  5 13  9]
 [ 1  3  2  7]]
Train  loss=0.8895 acc=0.6366 f1=0.6125 | Val loss=2.0418 acc=0.3103 f1=0.3065

Epoch 15/30


    t_loss=0.8921 | F1(macro)=0.6169 | Acc=0.6301


Confusion matrix:
 [[ 6  8 22  5]
 [ 6 16  5  5]
 [ 5  4 16  5]
 [ 1  2  5  5]]
Train  loss=0.8921 acc=0.6301 f1=0.6169 | Val loss=1.9432 acc=0.3707 f1=0.3582

Epoch 16/30


    t_loss=0.8435 | F1(macro)=0.6433 | Acc=0.6516


Confusion matrix:
 [[ 6  5 23  7]
 [ 9 11  5  7]
 [ 6  1 18  5]
 [ 3  0  4  6]]
Train  loss=0.8435 acc=0.6516 f1=0.6433 | Val loss=2.0732 acc=0.3534 f1=0.3498

Epoch 17/30


    t_loss=0.7653 | F1(macro)=0.6758 | Acc=0.6882


Confusion matrix:
 [[ 8  9 19  5]
 [ 6 19  3  4]
 [ 8  6 12  4]
 [ 3  2  4  4]]
Train  loss=0.7653 acc=0.6882 f1=0.6758 | Val loss=2.0432 acc=0.3707 f1=0.3552

Epoch 18/30


    t_loss=0.7291 | F1(macro)=0.6953 | Acc=0.7075


Confusion matrix:
 [[ 5 10 23  3]
 [ 3 22  5  2]
 [ 7  5 15  3]
 [ 1  3  5  4]]
Train  loss=0.7291 acc=0.7075 f1=0.6953 | Val loss=2.1693 acc=0.3966 f1=0.3728
  🔥 New best F1: 0.3728 – model saved.

Epoch 19/30


    t_loss=0.7596 | F1(macro)=0.6847 | Acc=0.6968


Confusion matrix:
 [[ 5  9 18  9]
 [ 6 17  3  6]
 [ 7  2 14  7]
 [ 2  2  4  5]]
Train  loss=0.7596 acc=0.6968 f1=0.6847 | Val loss=2.2404 acc=0.3534 f1=0.3420

Epoch 20/30


    t_loss=0.7399 | F1(macro)=0.7044 | Acc=0.7161


Confusion matrix:
 [[13  5 11 12]
 [10 15  0  7]
 [ 9  2  9 10]
 [ 3  2  2  6]]
Train  loss=0.7399 acc=0.7161 f1=0.7044 | Val loss=2.2825 acc=0.3707 f1=0.3685

Epoch 21/30


    t_loss=0.6883 | F1(macro)=0.7020 | Acc=0.7226


Confusion matrix:
 [[11  5 18  7]
 [15 11  1  5]
 [ 9  2 13  6]
 [ 4  2  3  4]]
Train  loss=0.6883 acc=0.7226 f1=0.7020 | Val loss=2.2495 acc=0.3362 f1=0.3317

Epoch 22/30


    t_loss=0.6226 | F1(macro)=0.7415 | Acc=0.7548


Confusion matrix:
 [[10  9 14  8]
 [12 12  1  7]
 [ 8  3 11  8]
 [ 4  2  1  6]]
Train  loss=0.6226 acc=0.7548 f1=0.7415 | Val loss=2.0974 acc=0.3362 f1=0.3380

Epoch 23/30


    t_loss=0.6682 | F1(macro)=0.7528 | Acc=0.7570


Confusion matrix:
 [[ 9  4 18 10]
 [13 10  2  7]
 [ 7  3 14  6]
 [ 3  1  3  6]]
Train  loss=0.6682 acc=0.7570 f1=0.7528 | Val loss=2.1847 acc=0.3362 f1=0.3376

Epoch 24/30


    t_loss=0.6934 | F1(macro)=0.7519 | Acc=0.7527


Confusion matrix:
 [[12  7 16  6]
 [13 12  1  6]
 [ 9  5 10  6]
 [ 4  1  4  4]]
Train  loss=0.6934 acc=0.7527 f1=0.7519 | Val loss=2.2656 acc=0.3276 f1=0.3203

Epoch 25/30


    t_loss=0.6462 | F1(macro)=0.7371 | Acc=0.7398


Confusion matrix:
 [[10  5 18  8]
 [14 10  1  7]
 [ 8  4 13  5]
 [ 3  1  4  5]]
Train  loss=0.6462 acc=0.7398 f1=0.7371 | Val loss=2.2817 acc=0.3276 f1=0.3262

Epoch 26/30


    t_loss=0.6365 | F1(macro)=0.7693 | Acc=0.7763


Confusion matrix:
 [[12  4 19  6]
 [18  5  2  7]
 [ 9  1 14  6]
 [ 3  1  4  5]]
Train  loss=0.6365 acc=0.7763 f1=0.7693 | Val loss=2.2577 acc=0.3103 f1=0.2994

Epoch 27/30


    t_loss=0.6304 | F1(macro)=0.7510 | Acc=0.7570


Confusion matrix:
 [[13  4 18  6]
 [16  7  1  8]
 [13  1 13  3]
 [ 3  1  4  5]]
Train  loss=0.6304 acc=0.7570 f1=0.7510 | Val loss=2.3005 acc=0.3276 f1=0.3233

Epoch 28/30


    t_loss=0.6596 | F1(macro)=0.7530 | Acc=0.7570


Confusion matrix:
 [[13  4 16  8]
 [17  6  1  8]
 [10  1 11  8]
 [ 4  1  3  5]]
Train  loss=0.6596 acc=0.7570 f1=0.7530 | Val loss=2.2932 acc=0.3017 f1=0.2943

Epoch 29/30


    t_loss=0.6607 | F1(macro)=0.7609 | Acc=0.7591


Confusion matrix:
 [[ 8  3 20 10]
 [14  8  3  7]
 [ 7  2 14  7]
 [ 3  1  4  5]]
Train  loss=0.6607 acc=0.7591 f1=0.7609 | Val loss=2.2528 acc=0.3017 f1=0.2999

Epoch 30/30


    t_loss=0.5400 | F1(macro)=0.8336 | Acc=0.8409


Confusion matrix:
 [[13  4 16  8]
 [16  8  1  7]
 [10  3 10  7]
 [ 3  1  4  5]]
Train  loss=0.5400 acc=0.8409 f1=0.8336 | Val loss=2.2601 acc=0.3103 f1=0.3061
Restored best weights for fold 1 (F1=0.3728)

========== Fold 2 ==========

Epoch 1/30


    t_loss=2.3138 | F1(macro)=0.2510 | Acc=0.2559


Confusion matrix:
 [[18  6  9  7]
 [11 16  2  3]
 [17  4  4  5]
 [ 5  0  4  5]]
Train  loss=2.3138 acc=0.2559 f1=0.2510 | Val loss=1.8692 acc=0.3707 f1=0.3512
  🔥 New best F1: 0.3512 – model saved.

Epoch 2/30


    t_loss=1.5959 | F1(macro)=0.3392 | Acc=0.3548


Confusion matrix:
 [[23  2  6  9]
 [21  3  2  6]
 [16  1  4  9]
 [ 4  0  1  9]]
Train  loss=1.5959 acc=0.3548 f1=0.3392 | Val loss=1.7313 acc=0.3362 f1=0.2923

Epoch 3/30


    t_loss=1.5987 | F1(macro)=0.3512 | Acc=0.3548


Confusion matrix:
 [[10  0 24  6]
 [ 4  6 18  4]
 [ 8  1 16  5]
 [ 1  1  7  5]]
Train  loss=1.5987 acc=0.3548 f1=0.3512 | Val loss=1.5973 acc=0.3190 f1=0.3121

Epoch 4/30


    t_loss=1.4288 | F1(macro)=0.3593 | Acc=0.3763


Confusion matrix:
 [[ 8  4 19  9]
 [ 8  6 14  4]
 [ 1  7 13  9]
 [ 2  0  4  8]]
Train  loss=1.4288 acc=0.3763 f1=0.3593 | Val loss=1.5326 acc=0.3017 f1=0.3012

Epoch 5/30


    t_loss=1.2638 | F1(macro)=0.4034 | Acc=0.4215


Confusion matrix:
 [[ 6  6 14 14]
 [ 6 12  8  6]
 [ 4  6  7 13]
 [ 1  1  3  9]]
Train  loss=1.2638 acc=0.4215 f1=0.4034 | Val loss=1.6776 acc=0.2931 f1=0.2947

Epoch 6/30


    t_loss=1.2443 | F1(macro)=0.4220 | Acc=0.4495


Confusion matrix:
 [[ 4  9 13 14]
 [ 9  9  8  6]
 [ 5  9 11  5]
 [ 2  4  4  4]]
Train  loss=1.2443 acc=0.4495 f1=0.4220 | Val loss=1.6954 acc=0.2414 f1=0.2346

Epoch 7/30


    t_loss=1.2369 | F1(macro)=0.4264 | Acc=0.4409


Confusion matrix:
 [[12  1 13 14]
 [18  5  4  5]
 [11  2  5 12]
 [ 2  1  4  7]]
Train  loss=1.2369 acc=0.4409 f1=0.4264 | Val loss=1.7506 acc=0.2500 f1=0.2452

Epoch 8/30


    t_loss=1.1194 | F1(macro)=0.5112 | Acc=0.5226


Confusion matrix:
 [[11  8 15  6]
 [16 10  4  2]
 [12  4  9  5]
 [ 6  2  4  2]]
Train  loss=1.1194 acc=0.5226 f1=0.5112 | Val loss=1.7192 acc=0.2759 f1=0.2611

Epoch 9/30


    t_loss=1.0387 | F1(macro)=0.5355 | Acc=0.5419


Confusion matrix:
 [[14  8  6 12]
 [13 11  5  3]
 [14  6  7  3]
 [ 4  3  3  4]]
Train  loss=1.0387 acc=0.5419 f1=0.5355 | Val loss=1.7691 acc=0.3103 f1=0.2982

Epoch 10/30


    t_loss=1.0876 | F1(macro)=0.5020 | Acc=0.5140


Confusion matrix:
 [[21  6  7  6]
 [22  5  3  2]
 [20  1  7  2]
 [ 6  2  4  2]]
Train  loss=1.0876 acc=0.5140 f1=0.5020 | Val loss=1.8913 acc=0.3017 f1=0.2578

Epoch 11/30


    t_loss=1.0336 | F1(macro)=0.5331 | Acc=0.5570


Confusion matrix:
 [[23  4  8  5]
 [20  3  7  2]
 [15  2  7  6]
 [ 4  1  6  3]]
Train  loss=1.0336 acc=0.5570 f1=0.5331 | Val loss=1.8329 acc=0.3103 f1=0.2588

Epoch 12/30


    t_loss=0.9452 | F1(macro)=0.5932 | Acc=0.6000


Confusion matrix:
 [[ 7  9 14 10]
 [ 9  9  8  6]
 [ 8  5 12  5]
 [ 2  1  6  5]]
Train  loss=0.9452 acc=0.6000 f1=0.5932 | Val loss=1.7831 acc=0.2845 f1=0.2816

Epoch 13/30


    t_loss=0.8530 | F1(macro)=0.6098 | Acc=0.6237


Confusion matrix:
 [[10  5 16  9]
 [10  5 11  6]
 [10  4 12  4]
 [ 3  2  4  5]]
Train  loss=0.8530 acc=0.6237 f1=0.6098 | Val loss=2.0253 acc=0.2759 f1=0.2686

Epoch 14/30


    t_loss=0.9265 | F1(macro)=0.6108 | Acc=0.6194


Confusion matrix:
 [[14 11  8  7]
 [ 9 16  4  3]
 [14  8  6  2]
 [ 6  3  4  1]]
Train  loss=0.9265 acc=0.6194 f1=0.6108 | Val loss=2.0911 acc=0.3190 f1=0.2748

Epoch 15/30


    t_loss=0.8667 | F1(macro)=0.6322 | Acc=0.6366


Confusion matrix:
 [[17 10  9  4]
 [18  5  5  4]
 [16  7  4  3]
 [ 6  3  2  3]]
Train  loss=0.8667 acc=0.6366 f1=0.6322 | Val loss=2.0162 acc=0.2500 f1=0.2251

Epoch 16/30


    t_loss=0.7584 | F1(macro)=0.7147 | Acc=0.7161


Confusion matrix:
 [[12  9 12  7]
 [15  4  8  5]
 [ 8  9  8  5]
 [ 4  2  7  1]]
Train  loss=0.7584 acc=0.7161 f1=0.7147 | Val loss=2.1349 acc=0.2155 f1=0.1888

Epoch 17/30


    t_loss=0.7649 | F1(macro)=0.7078 | Acc=0.7161


Confusion matrix:
 [[14  6 14  6]
 [14  5 11  2]
 [13  3 11  3]
 [ 5  2  5  2]]
Train  loss=0.7649 acc=0.7161 f1=0.7078 | Val loss=2.0985 acc=0.2759 f1=0.2480

Epoch 18/30


    t_loss=0.7410 | F1(macro)=0.6900 | Acc=0.6946


Confusion matrix:
 [[14  4 15  7]
 [16  6  5  5]
 [14  3 10  3]
 [ 2  2  5  5]]
Train  loss=0.7410 acc=0.6946 f1=0.6900 | Val loss=1.9986 acc=0.3017 f1=0.2957

Epoch 19/30


    t_loss=0.8127 | F1(macro)=0.6585 | Acc=0.6688


Confusion matrix:
 [[13  6 17  4]
 [12 10  7  3]
 [14  3 11  2]
 [ 3  2  5  4]]
Train  loss=0.8127 acc=0.6688 f1=0.6585 | Val loss=1.9880 acc=0.3276 f1=0.3263

Epoch 20/30


    t_loss=0.6705 | F1(macro)=0.7318 | Acc=0.7419


Confusion matrix:
 [[19  6  9  6]
 [18  6  3  5]
 [18  3  5  4]
 [ 5  2  3  4]]
Train  loss=0.6705 acc=0.7419 f1=0.7318 | Val loss=2.0954 acc=0.2931 f1=0.2668

Epoch 21/30


    t_loss=0.6784 | F1(macro)=0.7466 | Acc=0.7484


Confusion matrix:
 [[13  5 15  7]
 [16  3  8  5]
 [13  1 10  6]
 [ 2  0  6  6]]
Train  loss=0.6784 acc=0.7484 f1=0.7466 | Val loss=2.2781 acc=0.2759 f1=0.2654

Epoch 22/30


    t_loss=0.6063 | F1(macro)=0.7635 | Acc=0.7763


Confusion matrix:
 [[13  5 15  7]
 [13  4  9  6]
 [11  3 12  4]
 [ 3  0  5  6]]
Train  loss=0.6063 acc=0.7763 f1=0.7635 | Val loss=2.1514 acc=0.3017 f1=0.2923

Epoch 23/30


    t_loss=0.6403 | F1(macro)=0.7464 | Acc=0.7591


Confusion matrix:
 [[16  6 12  6]
 [15  4  8  5]
 [14  3 10  3]
 [ 4  2  6  2]]
Train  loss=0.6403 acc=0.7591 f1=0.7464 | Val loss=2.1857 acc=0.2759 f1=0.2415

Epoch 24/30


    t_loss=0.6231 | F1(macro)=0.7755 | Acc=0.7806


Confusion matrix:
 [[14  5 16  5]
 [13  5 10  4]
 [11  4 12  3]
 [ 4  2  5  3]]
Train  loss=0.6231 acc=0.7806 f1=0.7755 | Val loss=2.1283 acc=0.2931 f1=0.2714

Epoch 25/30


    t_loss=0.6142 | F1(macro)=0.7954 | Acc=0.7935


Confusion matrix:
 [[18  5 13  4]
 [16  4  8  4]
 [14  3 10  3]
 [ 5  1  5  3]]
Train  loss=0.6142 acc=0.7935 f1=0.7954 | Val loss=2.2816 acc=0.3017 f1=0.2705

Epoch 26/30


    t_loss=0.6113 | F1(macro)=0.7975 | Acc=0.8000


Confusion matrix:
 [[16  9  8  7]
 [15 10  4  3]
 [13  7  7  3]
 [ 5  2  4  3]]
Train  loss=0.6113 acc=0.8000 f1=0.7975 | Val loss=2.1732 acc=0.3103 f1=0.2893

Epoch 27/30


    t_loss=0.5632 | F1(macro)=0.8185 | Acc=0.8215


Confusion matrix:
 [[15  6  9 10]
 [12  2 10  8]
 [14  3  8  5]
 [ 3  0  4  7]]
Train  loss=0.5632 acc=0.8215 f1=0.8185 | Val loss=2.2116 acc=0.2759 f1=0.2577

Epoch 28/30


    t_loss=0.5876 | F1(macro)=0.7937 | Acc=0.8043


Confusion matrix:
 [[14  8 13  5]
 [12  5 11  4]
 [10  4 13  3]
 [ 3  2  6  3]]
Train  loss=0.5876 acc=0.8043 f1=0.7937 | Val loss=2.1289 acc=0.3017 f1=0.2784

Epoch 29/30


    t_loss=0.5605 | F1(macro)=0.8059 | Acc=0.8108


Confusion matrix:
 [[12  5 16  7]
 [14  4  9  5]
 [11  3 12  4]
 [ 2  1  4  7]]
Train  loss=0.5605 acc=0.8108 f1=0.8059 | Val loss=2.0771 acc=0.3017 f1=0.2995

Epoch 30/30


    t_loss=0.5577 | F1(macro)=0.8155 | Acc=0.8172


Confusion matrix:
 [[19  6  8  7]
 [16  3  7  6]
 [17  3  8  2]
 [ 5  0  3  6]]
Train  loss=0.5577 acc=0.8172 f1=0.8155 | Val loss=2.1348 acc=0.3103 f1=0.2892
Restored best weights for fold 2 (F1=0.3512)

========== Fold 3 ==========

Epoch 1/30


    t_loss=2.2483 | F1(macro)=0.2898 | Acc=0.2989


Confusion matrix:
 [[ 9  5 19  8]
 [ 7  3 15  6]
 [ 8  4 12  6]
 [ 3  3  4  4]]
Train  loss=2.2483 acc=0.2989 f1=0.2898 | Val loss=2.1216 acc=0.2414 f1=0.2264
  🔥 New best F1: 0.2264 – model saved.

Epoch 2/30


    t_loss=1.9122 | F1(macro)=0.3010 | Acc=0.3075


Confusion matrix:
 [[ 6 19  4 12]
 [ 2 13  1 15]
 [ 1 10  2 17]
 [ 3  3  0  8]]
Train  loss=1.9122 acc=0.3075 f1=0.3010 | Val loss=2.0048 acc=0.2500 f1=0.2298
  🔥 New best F1: 0.2298 – model saved.

Epoch 3/30


    t_loss=1.6229 | F1(macro)=0.3106 | Acc=0.3183


Confusion matrix:
 [[21 11  3  6]
 [16  8  4  3]
 [17  7  2  4]
 [10  1  0  3]]
Train  loss=1.6229 acc=0.3183 f1=0.3106 | Val loss=1.7876 acc=0.2931 f1=0.2446
  🔥 New best F1: 0.2446 – model saved.

Epoch 4/30


    t_loss=1.4658 | F1(macro)=0.3202 | Acc=0.3441


Confusion matrix:
 [[ 9 15 12  5]
 [10 11  6  4]
 [ 6  7 11  6]
 [ 3  3  4  4]]
Train  loss=1.4658 acc=0.3441 f1=0.3202 | Val loss=1.7110 acc=0.3017 f1=0.2952
  🔥 New best F1: 0.2952 – model saved.

Epoch 5/30


    t_loss=1.4095 | F1(macro)=0.3630 | Acc=0.3763


Confusion matrix:
 [[11  5  5 20]
 [11  7  3 10]
 [ 8  1  4 17]
 [ 4  1  1  8]]
Train  loss=1.4095 acc=0.3763 f1=0.3630 | Val loss=1.8745 acc=0.2586 f1=0.2556

Epoch 6/30


    t_loss=1.3307 | F1(macro)=0.3983 | Acc=0.4172


Confusion matrix:
 [[ 5  3 17 16]
 [ 2  8  8 13]
 [ 1  4  5 20]
 [ 0  0  3 11]]
Train  loss=1.3307 acc=0.4172 f1=0.3983 | Val loss=2.1531 acc=0.2500 f1=0.2520

Epoch 7/30


    t_loss=1.3100 | F1(macro)=0.4060 | Acc=0.4194


Confusion matrix:
 [[ 3 10 10 18]
 [ 5 11  3 12]
 [ 2  5  9 14]
 [ 2  3  4  5]]
Train  loss=1.3100 acc=0.4194 f1=0.4060 | Val loss=2.1903 acc=0.2414 f1=0.2400

Epoch 8/30


    t_loss=1.1851 | F1(macro)=0.4220 | Acc=0.4516


Confusion matrix:
 [[16 12  2 11]
 [ 9 12  2  8]
 [ 6  6  4 14]
 [ 6  3  0  5]]
Train  loss=1.1851 acc=0.4516 f1=0.4220 | Val loss=1.9021 acc=0.3190 f1=0.2970
  🔥 New best F1: 0.2970 – model saved.

Epoch 9/30


    t_loss=1.1519 | F1(macro)=0.4868 | Acc=0.4968


Confusion matrix:
 [[23  5  6  7]
 [16  4  2  9]
 [14  3  5  8]
 [ 9  1  1  3]]
Train  loss=1.1519 acc=0.4968 f1=0.4868 | Val loss=2.1653 acc=0.3017 f1=0.2505

Epoch 10/30


    t_loss=1.0870 | F1(macro)=0.4827 | Acc=0.5161


Confusion matrix:
 [[ 6  9  8 18]
 [ 5  4 10 12]
 [ 2  3  7 18]
 [ 5  1  3  5]]
Train  loss=1.0870 acc=0.5161 f1=0.4827 | Val loss=2.2624 acc=0.1897 f1=0.1902

Epoch 11/30


    t_loss=1.0935 | F1(macro)=0.5077 | Acc=0.5140


Confusion matrix:
 [[ 4  3 28  6]
 [ 4  4 18  5]
 [ 1  3 19  7]
 [ 2  0  9  3]]
Train  loss=1.0935 acc=0.5140 f1=0.5077 | Val loss=2.2924 acc=0.2586 f1=0.2214

Epoch 12/30


    t_loss=0.9175 | F1(macro)=0.6185 | Acc=0.6280


Confusion matrix:
 [[18  3 14  6]
 [11  5  8  7]
 [ 8  3 14  5]
 [ 7  0  6  1]]
Train  loss=0.9175 acc=0.6280 f1=0.6185 | Val loss=2.4403 acc=0.3276 f1=0.2778

Epoch 13/30


    t_loss=0.9952 | F1(macro)=0.5671 | Acc=0.5785


Confusion matrix:
 [[ 6 11 11 13]
 [ 3 16  2 10]
 [ 6  7  6 11]
 [ 5  1  3  5]]
Train  loss=0.9952 acc=0.5785 f1=0.5671 | Val loss=2.1242 acc=0.2845 f1=0.2753

Epoch 14/30


    t_loss=0.8821 | F1(macro)=0.5929 | Acc=0.6043


Confusion matrix:
 [[12  7 16  6]
 [12  7  3  9]
 [ 5  6 11  8]
 [ 5  0  4  5]]
Train  loss=0.8821 acc=0.6043 f1=0.5929 | Val loss=2.1383 acc=0.3017 f1=0.2941

Epoch 15/30


    t_loss=0.8386 | F1(macro)=0.6079 | Acc=0.6172


Confusion matrix:
 [[11  7 16  7]
 [ 6 11  2 12]
 [ 8  7  5 10]
 [ 5  3  2  4]]
Train  loss=0.8386 acc=0.6172 f1=0.6079 | Val loss=2.3430 acc=0.2672 f1=0.2587

Epoch 16/30


    t_loss=0.8802 | F1(macro)=0.6136 | Acc=0.6194


Confusion matrix:
 [[15 18  3  5]
 [ 9 11  2  9]
 [13  7  5  5]
 [ 6  3  3  2]]
Train  loss=0.8802 acc=0.6194 f1=0.6136 | Val loss=2.3127 acc=0.2845 f1=0.2546

Epoch 17/30


    t_loss=0.8156 | F1(macro)=0.6718 | Acc=0.6774


Confusion matrix:
 [[ 8 12 16  5]
 [ 8 13  3  7]
 [ 5  7  7 11]
 [ 4  3  3  4]]
Train  loss=0.8156 acc=0.6774 f1=0.6718 | Val loss=2.1546 acc=0.2759 f1=0.2672

Epoch 18/30


    t_loss=0.7250 | F1(macro)=0.7025 | Acc=0.7075


Confusion matrix:
 [[18  9  8  6]
 [12 11  0  8]
 [ 9  5  8  8]
 [ 7  1  3  3]]
Train  loss=0.7250 acc=0.7075 f1=0.7025 | Val loss=2.1781 acc=0.3448 f1=0.3200
  🔥 New best F1: 0.3200 – model saved.

Epoch 19/30


    t_loss=0.8009 | F1(macro)=0.6631 | Acc=0.6645


Confusion matrix:
 [[22  4  9  6]
 [16  6  1  8]
 [11  6  5  8]
 [ 5  1  3  5]]
Train  loss=0.8009 acc=0.6645 f1=0.6631 | Val loss=2.3541 acc=0.3276 f1=0.2913

Epoch 20/30


    t_loss=0.7173 | F1(macro)=0.6968 | Acc=0.7032


Confusion matrix:
 [[14  4  9 14]
 [ 9  5  3 14]
 [ 6  4  9 11]
 [ 7  0  2  5]]
Train  loss=0.7173 acc=0.7032 f1=0.6968 | Val loss=2.4907 acc=0.2845 f1=0.2757

Epoch 21/30


    t_loss=0.6936 | F1(macro)=0.6970 | Acc=0.7075


Confusion matrix:
 [[21  1  7 12]
 [15  2  3 11]
 [ 9  4  7 10]
 [ 8  0  1  5]]
Train  loss=0.6936 acc=0.7075 f1=0.6970 | Val loss=2.5321 acc=0.3017 f1=0.2590

Epoch 22/30


    t_loss=0.6815 | F1(macro)=0.7300 | Acc=0.7355


Confusion matrix:
 [[16 11  7  7]
 [ 9 11  1 10]
 [ 8  7  6  9]
 [ 6  2  0  6]]
Train  loss=0.6815 acc=0.7355 f1=0.7300 | Val loss=2.3297 acc=0.3362 f1=0.3221
  🔥 New best F1: 0.3221 – model saved.

Epoch 23/30


    t_loss=0.7653 | F1(macro)=0.7306 | Acc=0.7290


Confusion matrix:
 [[19  6 11  5]
 [13 11  2  5]
 [10  6  9  5]
 [ 9  2  1  2]]
Train  loss=0.7653 acc=0.7290 f1=0.7306 | Val loss=2.2711 acc=0.3534 f1=0.3186

Epoch 24/30


    t_loss=0.6790 | F1(macro)=0.7246 | Acc=0.7269


Confusion matrix:
 [[17  6 12  6]
 [11  9  2  9]
 [ 8  5 10  7]
 [ 8  1  2  3]]
Train  loss=0.6790 acc=0.7269 f1=0.7246 | Val loss=2.2929 acc=0.3362 f1=0.3143

Epoch 25/30


    t_loss=0.6892 | F1(macro)=0.7486 | Acc=0.7462


Confusion matrix:
 [[16  6 14  5]
 [ 9  9  3 10]
 [ 7  6 11  6]
 [ 9  0  2  3]]
Train  loss=0.6892 acc=0.7462 f1=0.7486 | Val loss=2.2409 acc=0.3362 f1=0.3152

Epoch 26/30


    t_loss=0.6162 | F1(macro)=0.7557 | Acc=0.7656


Confusion matrix:
 [[15  7 14  5]
 [13 10  1  7]
 [ 9  6 10  5]
 [ 7  1  2  4]]
Train  loss=0.6162 acc=0.7656 f1=0.7557 | Val loss=2.2642 acc=0.3362 f1=0.3240
  🔥 New best F1: 0.3240 – model saved.

Epoch 27/30


    t_loss=0.6214 | F1(macro)=0.7728 | Acc=0.7763


Confusion matrix:
 [[17  4 13  7]
 [12  8  2  9]
 [ 7  6 10  7]
 [ 9  0  3  2]]
Train  loss=0.6214 acc=0.7763 f1=0.7728 | Val loss=2.3786 acc=0.3190 f1=0.2923

Epoch 28/30


    t_loss=0.6310 | F1(macro)=0.7534 | Acc=0.7699


Confusion matrix:
 [[16  7 13  5]
 [10 16  3  2]
 [10  6 12  2]
 [ 7  3  3  1]]
Train  loss=0.6310 acc=0.7699 f1=0.7534 | Val loss=2.3455 acc=0.3879 f1=0.3414
  🔥 New best F1: 0.3414 – model saved.

Epoch 29/30


    t_loss=0.6450 | F1(macro)=0.7377 | Acc=0.7484


Confusion matrix:
 [[16  6 13  6]
 [10  9  2 10]
 [ 7  5 10  8]
 [ 7  0  1  6]]
Train  loss=0.6450 acc=0.7484 f1=0.7377 | Val loss=2.3202 acc=0.3534 f1=0.3445
  🔥 New best F1: 0.3445 – model saved.

Epoch 30/30


    t_loss=0.5747 | F1(macro)=0.7857 | Acc=0.7935


Confusion matrix:
 [[16  9 11  5]
 [12 12  1  6]
 [11  6 10  3]
 [ 9  1  2  2]]
Train  loss=0.5747 acc=0.7935 f1=0.7857 | Val loss=2.2838 acc=0.3448 f1=0.3175
Restored best weights for fold 3 (F1=0.3445)

========== Fold 4 ==========

Epoch 1/30


    t_loss=2.0169 | F1(macro)=0.2862 | Acc=0.3290


Confusion matrix:
 [[ 6  2  4 29]
 [ 9  2  1 19]
 [ 7  1  2 20]
 [ 4  0  0 10]]
Train  loss=2.0169 acc=0.3290 f1=0.2862 | Val loss=2.5860 acc=0.1724 f1=0.1539
  🔥 New best F1: 0.1539 – model saved.

Epoch 2/30


    t_loss=1.7265 | F1(macro)=0.3110 | Acc=0.3183


Confusion matrix:
 [[ 2 22 15  2]
 [ 3 20  5  3]
 [ 3 14  9  4]
 [ 0  8  4  2]]
Train  loss=1.7265 acc=0.3183 f1=0.3110 | Val loss=2.2216 acc=0.2845 f1=0.2371
  🔥 New best F1: 0.2371 – model saved.

Epoch 3/30


    t_loss=1.6251 | F1(macro)=0.3501 | Acc=0.3634


Confusion matrix:
 [[16  0  9 16]
 [ 6  3  7 15]
 [12  0 10  8]
 [ 2  0  6  6]]
Train  loss=1.6251 acc=0.3634 f1=0.3501 | Val loss=1.9103 acc=0.3017 f1=0.2795
  🔥 New best F1: 0.2795 – model saved.

Epoch 4/30


    t_loss=1.5389 | F1(macro)=0.3768 | Acc=0.3806


Confusion matrix:
 [[ 4 15 11 11]
 [ 4 16  0 11]
 [ 4  2 10 14]
 [ 0  3  3  8]]
Train  loss=1.5389 acc=0.3806 f1=0.3768 | Val loss=1.6894 acc=0.3276 f1=0.3187
  🔥 New best F1: 0.3187 – model saved.

Epoch 5/30


    t_loss=1.2650 | F1(macro)=0.3700 | Acc=0.4172


Confusion matrix:
 [[ 1 15 17  8]
 [ 4 17  6  4]
 [ 2 14 13  1]
 [ 0  3  6  5]]
Train  loss=1.2650 acc=0.4172 f1=0.3700 | Val loss=1.7016 acc=0.3103 f1=0.2851

Epoch 6/30


    t_loss=1.3419 | F1(macro)=0.4355 | Acc=0.4387


Confusion matrix:
 [[ 4 14 19  4]
 [ 4 17  7  3]
 [ 5 11 13  1]
 [ 2  5  5  2]]
Train  loss=1.3419 acc=0.4387 f1=0.4355 | Val loss=1.9053 acc=0.3103 f1=0.2742

Epoch 7/30


    t_loss=1.3065 | F1(macro)=0.4445 | Acc=0.4624


Confusion matrix:
 [[ 4 21 12  4]
 [ 2 25  4  0]
 [ 5 18  6  1]
 [ 0 10  3  1]]
Train  loss=1.3065 acc=0.4624 f1=0.4445 | Val loss=1.6214 acc=0.3103 f1=0.2371

Epoch 8/30


    t_loss=1.1654 | F1(macro)=0.4919 | Acc=0.5097


Confusion matrix:
 [[ 1 12 21  7]
 [ 4 15 10  2]
 [ 4  4 18  4]
 [ 0  4  7  3]]
Train  loss=1.1654 acc=0.5097 f1=0.4919 | Val loss=1.7076 acc=0.3190 f1=0.2783

Epoch 9/30


    t_loss=1.0798 | F1(macro)=0.5063 | Acc=0.5333


Confusion matrix:
 [[ 9 13 14  5]
 [ 5 19  4  3]
 [ 5  9 11  5]
 [ 2  1  7  4]]
Train  loss=1.0798 acc=0.5333 f1=0.5063 | Val loss=1.6857 acc=0.3707 f1=0.3506
  🔥 New best F1: 0.3506 – model saved.

Epoch 10/30


    t_loss=1.1193 | F1(macro)=0.4867 | Acc=0.5097


Confusion matrix:
 [[17 11  6  7]
 [ 8 19  1  3]
 [ 5  9  9  7]
 [ 5  4  2  3]]
Train  loss=1.1193 acc=0.5097 f1=0.4867 | Val loss=1.6074 acc=0.4138 f1=0.3781
  🔥 New best F1: 0.3781 – model saved.

Epoch 11/30


    t_loss=1.0342 | F1(macro)=0.5754 | Acc=0.5763


Confusion matrix:
 [[ 6 12 22  1]
 [ 2 19  8  2]
 [ 3  9 17  1]
 [ 1  4  8  1]]
Train  loss=1.0342 acc=0.5763 f1=0.5754 | Val loss=1.8636 acc=0.3707 f1=0.3096

Epoch 12/30


    t_loss=0.9658 | F1(macro)=0.5493 | Acc=0.5763


Confusion matrix:
 [[ 7 27  5  2]
 [ 3 24  3  1]
 [10 15  3  2]
 [ 2  8  3  1]]
Train  loss=0.9658 acc=0.5763 f1=0.5493 | Val loss=1.8056 acc=0.3017 f1=0.2289

Epoch 13/30


    t_loss=0.8953 | F1(macro)=0.6037 | Acc=0.6194


Confusion matrix:
 [[ 5 16 17  3]
 [ 5 17  7  2]
 [ 7  8 14  1]
 [ 1  4  8  1]]
Train  loss=0.8953 acc=0.6194 f1=0.6037 | Val loss=1.9759 acc=0.3190 f1=0.2701

Epoch 14/30


    t_loss=0.7674 | F1(macro)=0.6412 | Acc=0.6710


Confusion matrix:
 [[ 5 24  9  3]
 [ 4 22  2  3]
 [ 6 15  7  2]
 [ 1  6  6  1]]
Train  loss=0.7674 acc=0.6710 f1=0.6412 | Val loss=2.0275 acc=0.3017 f1=0.2427

Epoch 15/30


    t_loss=0.8861 | F1(macro)=0.6027 | Acc=0.6129


Confusion matrix:
 [[20  8 10  3]
 [11 15  2  3]
 [12  8  7  3]
 [ 5  1  8  0]]
Train  loss=0.8861 acc=0.6129 f1=0.6027 | Val loss=1.7840 acc=0.3621 f1=0.2928

Epoch 16/30


    t_loss=0.7985 | F1(macro)=0.6560 | Acc=0.6624


Confusion matrix:
 [[10 13 15  3]
 [ 9 15  2  5]
 [ 9  8 11  2]
 [ 3  4  5  2]]
Train  loss=0.7985 acc=0.6624 f1=0.6560 | Val loss=1.9615 acc=0.3276 f1=0.3008

Epoch 17/30


    t_loss=0.7632 | F1(macro)=0.6608 | Acc=0.6753


Confusion matrix:
 [[ 5 12 22  2]
 [ 6 16  5  4]
 [ 4  9 16  1]
 [ 1  3  9  1]]
Train  loss=0.7632 acc=0.6753 f1=0.6608 | Val loss=1.9152 acc=0.3276 f1=0.2768

Epoch 18/30


    t_loss=0.7794 | F1(macro)=0.6727 | Acc=0.6817


Confusion matrix:
 [[11 10 15  5]
 [ 4 18  3  6]
 [ 6  9 13  2]
 [ 1  4  7  2]]
Train  loss=0.7794 acc=0.6817 f1=0.6727 | Val loss=1.7825 acc=0.3793 f1=0.3424

Epoch 19/30


    t_loss=0.7541 | F1(macro)=0.6998 | Acc=0.6989


Confusion matrix:
 [[15 10 14  2]
 [13 12  3  3]
 [ 9  8 11  2]
 [ 4  3  6  1]]
Train  loss=0.7541 acc=0.6989 f1=0.6998 | Val loss=1.8894 acc=0.3362 f1=0.2939

Epoch 20/30


    t_loss=0.7924 | F1(macro)=0.6803 | Acc=0.6817


Confusion matrix:
 [[18  9 10  4]
 [ 7 16  3  5]
 [ 6 10 11  3]
 [ 3  4  4  3]]
Train  loss=0.7924 acc=0.6817 f1=0.6803 | Val loss=1.8200 acc=0.4138 f1=0.3808
  🔥 New best F1: 0.3808 – model saved.

Epoch 21/30


    t_loss=0.6381 | F1(macro)=0.7639 | Acc=0.7699


Confusion matrix:
 [[14 11 14  2]
 [ 9 14  3  5]
 [ 8  8 11  3]
 [ 3  3  7  1]]
Train  loss=0.6381 acc=0.7699 f1=0.7639 | Val loss=1.9889 acc=0.3448 f1=0.3024

Epoch 22/30


    t_loss=0.6535 | F1(macro)=0.7513 | Acc=0.7613


Confusion matrix:
 [[13 16 11  1]
 [ 6 18  3  4]
 [ 9 11  8  2]
 [ 3  4  6  1]]
Train  loss=0.6535 acc=0.7613 f1=0.7513 | Val loss=2.0037 acc=0.3448 f1=0.2945

Epoch 23/30


    t_loss=0.7034 | F1(macro)=0.7418 | Acc=0.7484


Confusion matrix:
 [[21  8 10  2]
 [12 12  3  4]
 [11  6 10  3]
 [ 4  3  5  2]]
Train  loss=0.7034 acc=0.7484 f1=0.7418 | Val loss=1.8531 acc=0.3879 f1=0.3442

Epoch 24/30


    t_loss=0.6847 | F1(macro)=0.7570 | Acc=0.7613


Confusion matrix:
 [[13 11 15  2]
 [ 8 14  3  6]
 [ 6  7 14  3]
 [ 2  5  5  2]]
Train  loss=0.6847 acc=0.7613 f1=0.7570 | Val loss=1.7743 acc=0.3707 f1=0.3373

Epoch 25/30


    t_loss=0.5903 | F1(macro)=0.7783 | Acc=0.7849


Confusion matrix:
 [[16 10 13  2]
 [ 8 14  3  6]
 [ 9  8 10  3]
 [ 3  4  6  1]]
Train  loss=0.5903 acc=0.7849 f1=0.7783 | Val loss=1.8555 acc=0.3534 f1=0.3082

Epoch 26/30


    t_loss=0.6231 | F1(macro)=0.7503 | Acc=0.7591


Confusion matrix:
 [[19 10 11  1]
 [12 10  3  6]
 [10  5 12  3]
 [ 2  4  7  1]]
Train  loss=0.6231 acc=0.7591 f1=0.7503 | Val loss=1.9310 acc=0.3621 f1=0.3117

Epoch 27/30


    t_loss=0.6219 | F1(macro)=0.7901 | Acc=0.7957


Confusion matrix:
 [[11 14 14  2]
 [ 6 16  3  6]
 [ 6  8 13  3]
 [ 2  5  6  1]]
Train  loss=0.6219 acc=0.7957 f1=0.7901 | Val loss=1.9082 acc=0.3534 f1=0.3092

Epoch 28/30


    t_loss=0.6397 | F1(macro)=0.7711 | Acc=0.7742


Confusion matrix:
 [[15 16  8  2]
 [ 9 15  2  5]
 [ 7 11 10  2]
 [ 3  4  6  1]]
Train  loss=0.6397 acc=0.7742 f1=0.7711 | Val loss=1.9889 acc=0.3534 f1=0.3075

Epoch 29/30


    t_loss=0.5687 | F1(macro)=0.8175 | Acc=0.8215


Confusion matrix:
 [[18 10 11  2]
 [11 13  2  5]
 [ 9  9  9  3]
 [ 4  3  6  1]]
Train  loss=0.5687 acc=0.8215 f1=0.8175 | Val loss=1.9229 acc=0.3534 f1=0.3045

Epoch 30/30


    t_loss=0.6039 | F1(macro)=0.7894 | Acc=0.7935


Confusion matrix:
 [[16 11 12  2]
 [ 7 16  3  5]
 [ 8  8 11  3]
 [ 4  3  6  1]]
Train  loss=0.6039 acc=0.7935 f1=0.7894 | Val loss=1.9668 acc=0.3793 f1=0.3299
Restored best weights for fold 4 (F1=0.3808)


# tf_efficientnetv2_s.in21k

In [7]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts_np = train_df["label_idx"].value_counts().sort_index().values
        class_counts = torch.tensor(class_counts_np, dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [8]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts_np = train_df["label_idx"].value_counts().sort_index().values
        class_counts = torch.tensor(class_counts_np, dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [9]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1 else "tf_effb1_ns"

FOLD_VAL_F1 = f"fold_val_f1_{prefix_filename}.json"

# Save best F1 per fold to JSON
with open(FOLD_VAL_F1, "w") as f:
    json.dump(best_f1_per_fold, f, indent=2)

In [10]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(data.num_K_folds):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=data.image_size,
        is_train=False,   # Disable augmentations
        use_mask_crop=True,
        apply_artifact_augs=False
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.33398744113029827
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.3371517539716083
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.3576882537503677
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.263042328042328
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.3084538268748795
Mean OOF F1: 0.32006472075389636


In [11]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=data.image_size,
    is_train=False,   # deterministic, returns (img, sample_index)
    use_mask_crop=True,
    patch_mode=False,
    apply_artifact_augs=False
)
test_loader = DataLoader(
    test_dataset,
    batch_size=1,               # per-image TTA
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

if os.path.exists(FOLD_VAL_F1):
    with open(FOLD_VAL_F1, "r") as f:
        best_f1_per_fold = json.load(f)
    val_f1_per_fold = np.array([best_f1_per_fold[str(k)] for k in range(data.num_K_folds)])
    # Normalize to get weights that sum to 1
    fold_weights = val_f1_per_fold / val_f1_per_fold.sum()
else:
    # fallback: uniform weights if metrics are missing
    print('Warning: fold validation F1 scores not found, using uniform weights.')
    fold_weights = np.ones(data.num_K_folds, dtype=np.float32) / data.num_K_folds

print("Fold weights:", fold_weights)

# -----------------------------
# 2) Accumulate weighted probs
# -----------------------------
all_probs = None
all_sample_indices = None

for fold in range(data.num_K_folds):
    print(f"Inference with fold {fold} model (weight={fold_weights[fold]:.3f})")

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0:
        model = create_efficientnet_b0_model(pretrained=False)
    else:
        model = create_efficientnet_b1_ns_model(pretrained=False)

    state_dict = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in tqdm(test_loader):
        # for img_tensor, sample_idx in test_loader:
            # img_tensor: [1, 4, H, W]  (RGB+mask)
            img_tensor = img_tensor.squeeze(0).to(device)  # [4, H, W]

            # -------- TTA: mask-based multi-crop + simple flips --------
            USE_MASK_TTA = False
            if USE_MASK_TTA:
                tta_tensors = apply_mask_multicrop_tta(img_tensor, crop_size=data.image_size, n_crops=2)
            else:
                tta_tensors = apply_multicrop_tta(img_tensor, base_size=data.image_size, inner_ratio=0.8)


            # accumulate probability predictions
            probs_sum = 0.0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1, 4, H, W]
                with torch.no_grad():
                    logits = model(aug_img)
                    probs = softmax(logits, dim=1)  # [1, N_CLASSES]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N_test, N_CLASSES]

    # initialize global probs
    if all_probs is None:
        all_probs = np.zeros_like(fold_probs, dtype=np.float32)

     # weighted accumulation
    all_probs += fold_weights[fold] * fold_probs

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# -----------------------------
# 3) Final predictions
# -----------------------------
pred_indices = all_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print(f"Saved submission_5fold_tta_{prefix_filename}.csv")

Fold weights: [0.19061094 0.20819597 0.19612535 0.19237817 0.21268958]
Inference with fold 0 model (weight=0.191)


100%|██████████| 477/477 [06:57<00:00,  1.14it/s]


Inference with fold 1 model (weight=0.208)


100%|██████████| 477/477 [06:58<00:00,  1.14it/s]


Inference with fold 2 model (weight=0.196)


100%|██████████| 477/477 [07:09<00:00,  1.11it/s]


Inference with fold 3 model (weight=0.192)


100%|██████████| 477/477 [07:10<00:00,  1.11it/s]


Inference with fold 4 model (weight=0.213)


100%|██████████| 477/477 [07:10<00:00,  1.11it/s]

Saved submission_5fold_tta_tf_effb1_ns.csv
