In [1]:
import enum
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from timm.layers import Conv2dSame
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.persistence_manager import PersistenceManager
from internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B1

In [4]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=True,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_efficientnet_b0_model()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        clf_module, clf_name = get_classifier_module(model)
        for param in clf_module.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_{PREFIX}_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_{PREFIX}_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"{PREFIX}_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.2610 | F1(macro)=0.2429 | Acc=0.2435


Confusion matrix:
 [[ 4 12 10 15]
 [11  8  9  4]
 [ 5 18  3  4]
 [ 2  4  5  3]]
Train  loss=2.2610 acc=0.2435 f1=0.2429 | Val loss=3.0159 acc=0.1538 f1=0.1496
  🔥 New best F1: 0.1496 – model saved.

Epoch 2/8


    t_loss=2.1005 | F1(macro)=0.2642 | Acc=0.2651


Confusion matrix:
 [[ 6  8 10 17]
 [11  6  6  9]
 [ 8 10  5  7]
 [ 3  5  2  4]]
Train  loss=2.1005 acc=0.2651 f1=0.2642 | Val loss=2.8328 acc=0.1795 f1=0.1790
  🔥 New best F1: 0.1790 – model saved.

Epoch 3/8


    t_loss=2.0648 | F1(macro)=0.2731 | Acc=0.2780


Confusion matrix:
 [[ 7  6 11 17]
 [13  5  6  8]
 [13  7  3  7]
 [ 5  4  3  2]]
Train  loss=2.0648 acc=0.2780 f1=0.2731 | Val loss=2.4370 acc=0.1453 f1=0.1397

Epoch 4/8


    t_loss=1.8823 | F1(macro)=0.2680 | Acc=0.2716


Confusion matrix:
 [[10  6 11 14]
 [15  5  5  7]
 [14  8  2  6]
 [ 5  3  3  3]]
Train  loss=1.8823 acc=0.2716 f1=0.2680 | Val loss=2.5205 acc=0.1709 f1=0.1588

Epoch 5/8


    t_loss=1.9055 | F1(macro)=0.3027 | Acc=0.3039


Confusion matrix:
 [[ 6  7 14 14]
 [ 8  7  9  8]
 [ 7  6 11  6]
 [ 3  3  5  3]]
Train  loss=1.9055 acc=0.3039 f1=0.3027 | Val loss=2.3991 acc=0.2308 f1=0.2228
  🔥 New best F1: 0.2228 – model saved.

Epoch 6/8


    t_loss=1.9527 | F1(macro)=0.2788 | Acc=0.2780


Confusion matrix:
 [[ 9  8 14 10]
 [ 9  9  7  7]
 [ 8 10  6  6]
 [ 3  4  5  2]]
Train  loss=1.9527 acc=0.2780 f1=0.2788 | Val loss=2.3216 acc=0.2222 f1=0.2097

Epoch 7/8


    t_loss=1.7040 | F1(macro)=0.3450 | Acc=0.3448


Confusion matrix:
 [[10  9 13  9]
 [11  9  4  8]
 [11 10  6  3]
 [ 3  5  4  2]]
Train  loss=1.7040 acc=0.3448 f1=0.3450 | Val loss=2.3014 acc=0.2308 f1=0.2154

Epoch 8/8


    t_loss=1.9375 | F1(macro)=0.3002 | Acc=0.2996


Confusion matrix:
 [[ 8  9 16  8]
 [10  8 10  4]
 [10  7  7  6]
 [ 3  5  4  2]]
Train  loss=1.9375 acc=0.2996 f1=0.3002 | Val loss=2.4525 acc=0.2137 f1=0.2028
Restored best Stage 1 weights for fold 0 (F1=0.2228)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=2.0943 | F1(macro)=0.2998 | Acc=0.3082


Confusion matrix:
 [[25  9  0  7]
 [15 10  0  7]
 [20  5  0  5]
 [10  2  0  2]]
Train  loss=2.0943 acc=0.3082 f1=0.2998 | Val loss=2.6588 acc=0.3162 f1=0.2274
  🔥 New best F1: 0.2274 – model saved.

Epoch 2/12


    t_loss=1.6605 | F1(macro)=0.3369 | Acc=0.3427


Confusion matrix:
 [[10  0 26  5]
 [ 7  3 21  1]
 [ 6  1 18  5]
 [ 4  1  6  3]]
Train  loss=1.6605 acc=0.3427 f1=0.3369 | Val loss=2.5692 acc=0.2906 f1=0.2568
  🔥 New best F1: 0.2568 – model saved.

Epoch 3/12


    t_loss=1.3849 | F1(macro)=0.3631 | Acc=0.3944


Confusion matrix:
 [[ 9 12 14  6]
 [ 8 10 10  4]
 [ 8  4 12  6]
 [ 2  3  7  2]]
Train  loss=1.3849 acc=0.3944 f1=0.3631 | Val loss=2.2902 acc=0.2821 f1=0.2616
  🔥 New best F1: 0.2616 – model saved.

Epoch 4/12


    t_loss=1.3079 | F1(macro)=0.4031 | Acc=0.4267


Confusion matrix:
 [[ 3  7 15 16]
 [ 3 15  9  5]
 [ 5  5  7 13]
 [ 2  1  3  8]]
Train  loss=1.3079 acc=0.4267 f1=0.4031 | Val loss=2.2427 acc=0.2821 f1=0.2789
  🔥 New best F1: 0.2789 – model saved.

Epoch 5/12


    t_loss=1.2334 | F1(macro)=0.4679 | Acc=0.4763


Confusion matrix:
 [[16  2 11 12]
 [12  5  5 10]
 [10  0  9 11]
 [ 3  0  3  8]]
Train  loss=1.2334 acc=0.4763 f1=0.4679 | Val loss=2.4023 acc=0.3248 f1=0.3120
  🔥 New best F1: 0.3120 – model saved.

Epoch 6/12


    t_loss=1.2063 | F1(macro)=0.4615 | Acc=0.4741


Confusion matrix:
 [[ 6 13 11 11]
 [12  8  7  5]
 [ 4  6 12  8]
 [ 1  1  5  7]]
Train  loss=1.2063 acc=0.4741 f1=0.4615 | Val loss=2.1146 acc=0.2821 f1=0.2836

Epoch 7/12


    t_loss=1.0871 | F1(macro)=0.5373 | Acc=0.5560


Confusion matrix:
 [[16  7 13  5]
 [14  6  8  4]
 [13  3 10  4]
 [ 5  1  6  2]]
Train  loss=1.0871 acc=0.5560 f1=0.5373 | Val loss=2.2136 acc=0.2906 f1=0.2602

Epoch 8/12


    t_loss=1.0438 | F1(macro)=0.5656 | Acc=0.5690


Confusion matrix:
 [[12  7 16  6]
 [13  5 12  2]
 [ 8  1 13  8]
 [ 3  0  6  5]]
Train  loss=1.0438 acc=0.5690 f1=0.5656 | Val loss=2.1092 acc=0.2991 f1=0.2893

Epoch 9/12


    t_loss=0.9382 | F1(macro)=0.5999 | Acc=0.6164


Confusion matrix:
 [[13  7 14  7]
 [17  5  6  4]
 [ 9  0 13  8]
 [ 4  0  6  4]]
Train  loss=0.9382 acc=0.6164 f1=0.5999 | Val loss=2.1167 acc=0.2991 f1=0.2825

Epoch 10/12


    t_loss=1.0154 | F1(macro)=0.6098 | Acc=0.6099


Confusion matrix:
 [[11  7 13 10]
 [12  5  9  6]
 [ 9  0  9 12]
 [ 3  0  5  6]]
Train  loss=1.0154 acc=0.6099 f1=0.6098 | Val loss=2.1426 acc=0.2650 f1=0.2599

Epoch 11/12


    t_loss=0.8312 | F1(macro)=0.6837 | Acc=0.6940


Confusion matrix:
 [[10  4 17 10]
 [12  5  8  7]
 [10  0 10 10]
 [ 2  1  5  6]]
Train  loss=0.8312 acc=0.6940 f1=0.6837 | Val loss=2.1091 acc=0.2650 f1=0.2614

Epoch 12/12


    t_loss=0.9535 | F1(macro)=0.6450 | Acc=0.6487


Confusion matrix:
 [[12  9 11  9]
 [15  5  8  4]
 [ 8  0 13  9]
 [ 4  0  5  5]]
Train  loss=0.9535 acc=0.6487 f1=0.6450 | Val loss=2.0636 acc=0.2991 f1=0.2873

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.3850 | F1(macro)=0.2556 | Acc=0.2581


Confusion matrix:
 [[20 15  1  4]
 [18  8  3  3]
 [ 8 15  4  3]
 [ 8  4  1  1]]
Train  loss=2.3850 acc=0.2581 f1=0.2556 | Val loss=3.1144 acc=0.2845 f1=0.2317
  🔥 New best F1: 0.2317 – model saved.

Epoch 2/8


    t_loss=2.1823 | F1(macro)=0.2489 | Acc=0.2495


Confusion matrix:
 [[13 23  0  4]
 [ 9 16  6  1]
 [ 5 19  5  1]
 [ 4  8  2  0]]
Train  loss=2.1823 acc=0.2495 f1=0.2489 | Val loss=3.0503 acc=0.2931 f1=0.2313

Epoch 3/8


    t_loss=2.0467 | F1(macro)=0.2514 | Acc=0.2538


Confusion matrix:
 [[18 18  0  4]
 [16  7  7  2]
 [ 9 14  6  1]
 [ 7  3  2  2]]
Train  loss=2.0467 acc=0.2538 f1=0.2514 | Val loss=2.8052 acc=0.2845 f1=0.2574
  🔥 New best F1: 0.2574 – model saved.

Epoch 4/8


    t_loss=1.9394 | F1(macro)=0.2755 | Acc=0.2774


Confusion matrix:
 [[17 18  0  5]
 [16  9  6  1]
 [ 6 20  3  1]
 [ 5  4  2  3]]
Train  loss=1.9394 acc=0.2774 f1=0.2755 | Val loss=2.7932 acc=0.2759 f1=0.2545

Epoch 5/8


    t_loss=2.0130 | F1(macro)=0.2672 | Acc=0.2667


Confusion matrix:
 [[10 19  4  7]
 [13 13  6  0]
 [ 4 20  3  3]
 [ 4  8  2  0]]
Train  loss=2.0130 acc=0.2667 f1=0.2672 | Val loss=2.8594 acc=0.2241 f1=0.1744

Epoch 6/8


    t_loss=1.8827 | F1(macro)=0.3086 | Acc=0.3054


Confusion matrix:
 [[11 15 11  3]
 [10  8 13  1]
 [ 5 19  6  0]
 [ 6  6  2  0]]
Train  loss=1.8827 acc=0.3054 f1=0.3086 | Val loss=2.6181 acc=0.2155 f1=0.1748

Epoch 7/8


    t_loss=1.9079 | F1(macro)=0.2830 | Acc=0.2839


Confusion matrix:
 [[14 18  2  6]
 [14 10  6  2]
 [ 4 20  3  3]
 [ 6  6  1  1]]
Train  loss=1.9079 acc=0.2839 f1=0.2830 | Val loss=2.8128 acc=0.2414 f1=0.2028

Epoch 8/8


    t_loss=1.8723 | F1(macro)=0.2879 | Acc=0.2903


Confusion matrix:
 [[13 20  2  5]
 [14 11  6  1]
 [ 5 18  4  3]
 [ 6  5  2  1]]
Train  loss=1.8723 acc=0.2903 f1=0.2879 | Val loss=2.8086 acc=0.2500 f1=0.2136
Restored best Stage 1 weights for fold 1 (F1=0.2574)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.9572 | F1(macro)=0.3271 | Acc=0.3355


Confusion matrix:
 [[ 0 10 10 20]
 [ 4  7  6 15]
 [ 2 11  2 15]
 [ 1  5  1  7]]
Train  loss=1.9572 acc=0.3355 f1=0.3271 | Val loss=3.2397 acc=0.1379 f1=0.1236
  🔥 New best F1: 0.1236 – model saved.

Epoch 2/12


    t_loss=1.5873 | F1(macro)=0.3536 | Acc=0.3720


Confusion matrix:
 [[ 8  7 10 15]
 [ 9  5 11  7]
 [12  5  6  7]
 [ 5  3  3  3]]
Train  loss=1.5873 acc=0.3720 f1=0.3536 | Val loss=2.5828 acc=0.1897 f1=0.1847
  🔥 New best F1: 0.1847 – model saved.

Epoch 3/12


    t_loss=1.4977 | F1(macro)=0.3678 | Acc=0.3763


Confusion matrix:
 [[10  8  8 14]
 [ 9  8  6  9]
 [ 3  8  6 13]
 [ 1  1  4  8]]
Train  loss=1.4977 acc=0.3763 f1=0.3678 | Val loss=2.2172 acc=0.2759 f1=0.2741
  🔥 New best F1: 0.2741 – model saved.

Epoch 4/12


    t_loss=1.3931 | F1(macro)=0.4000 | Acc=0.4151


Confusion matrix:
 [[18 10  8  4]
 [ 6 13  7  6]
 [ 6  9  9  6]
 [ 5  4  3  2]]
Train  loss=1.3931 acc=0.4151 f1=0.4000 | Val loss=2.0750 acc=0.3621 f1=0.3258
  🔥 New best F1: 0.3258 – model saved.

Epoch 5/12


    t_loss=1.2690 | F1(macro)=0.4280 | Acc=0.4538


Confusion matrix:
 [[16 11  5  8]
 [14  7  8  3]
 [14  6  6  4]
 [ 6  4  2  2]]
Train  loss=1.2690 acc=0.4538 f1=0.4280 | Val loss=2.2241 acc=0.2672 f1=0.2383

Epoch 6/12


    t_loss=1.1764 | F1(macro)=0.5012 | Acc=0.5118


Confusion matrix:
 [[10 17  7  6]
 [ 5 18  5  4]
 [ 7 14  7  2]
 [ 4  5  3  2]]
Train  loss=1.1764 acc=0.5118 f1=0.5012 | Val loss=1.9159 acc=0.3190 f1=0.2834

Epoch 7/12


    t_loss=1.1309 | F1(macro)=0.5042 | Acc=0.5118


Confusion matrix:
 [[18 12  5  5]
 [17  9  5  1]
 [14  5  8  3]
 [ 8  3  0  3]]
Train  loss=1.1309 acc=0.5118 f1=0.5042 | Val loss=1.9449 acc=0.3276 f1=0.3076

Epoch 8/12


    t_loss=1.0138 | F1(macro)=0.5401 | Acc=0.5656


Confusion matrix:
 [[ 1 17  7 15]
 [ 3 12  9  8]
 [ 5  9 10  6]
 [ 4  5  2  3]]
Train  loss=1.0138 acc=0.5656 f1=0.5401 | Val loss=1.9568 acc=0.2241 f1=0.2082

Epoch 9/12


    t_loss=0.9642 | F1(macro)=0.5864 | Acc=0.6000


Confusion matrix:
 [[ 7 17  7  9]
 [ 6 16  3  7]
 [ 7 12  6  5]
 [ 5  5  1  3]]
Train  loss=0.9642 acc=0.6000 f1=0.5864 | Val loss=1.8948 acc=0.2759 f1=0.2547

Epoch 10/12


    t_loss=0.9700 | F1(macro)=0.6317 | Acc=0.6323


Confusion matrix:
 [[ 6 14 11  9]
 [ 5  9 11  7]
 [ 4  9 11  6]
 [ 2  3  5  4]]
Train  loss=0.9700 acc=0.6323 f1=0.6317 | Val loss=1.8442 acc=0.2586 f1=0.2507

Epoch 11/12


    t_loss=0.8908 | F1(macro)=0.6167 | Acc=0.6258


Confusion matrix:
 [[10 16  9  5]
 [ 7 11  9  5]
 [ 7 14  6  3]
 [ 4  5  4  1]]
Train  loss=0.8908 acc=0.6258 f1=0.6167 | Val loss=1.8365 acc=0.2414 f1=0.2136

Epoch 12/12


    t_loss=0.8743 | F1(macro)=0.6644 | Acc=0.6710


Confusion matrix:
 [[ 7 13 12  8]
 [ 6 10 10  6]
 [ 3  8 13  6]
 [ 3  2  4  5]]
Train  loss=0.8743 acc=0.6710 f1=0.6644 | Val loss=1.7851 acc=0.3017 f1=0.2946

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.2006 | F1(macro)=0.2430 | Acc=0.2495


Confusion matrix:
 [[ 7  6 22  6]
 [10  5 13  3]
 [ 5  6 14  5]
 [ 4  2  7  1]]
Train  loss=2.2006 acc=0.2495 f1=0.2430 | Val loss=2.9211 acc=0.2328 f1=0.2009
  🔥 New best F1: 0.2009 – model saved.

Epoch 2/8


    t_loss=1.9895 | F1(macro)=0.2763 | Acc=0.2839


Confusion matrix:
 [[ 8 14 11  8]
 [13  8  8  2]
 [ 7  8 10  5]
 [ 4  2  6  2]]
Train  loss=1.9895 acc=0.2839 f1=0.2763 | Val loss=2.7422 acc=0.2414 f1=0.2275
  🔥 New best F1: 0.2275 – model saved.

Epoch 3/8


    t_loss=2.0789 | F1(macro)=0.2056 | Acc=0.2108


Confusion matrix:
 [[ 8  7 16 10]
 [10  7 11  3]
 [ 5  8 13  4]
 [ 2  2  5  5]]
Train  loss=2.0789 acc=0.2108 f1=0.2056 | Val loss=2.6696 acc=0.2845 f1=0.2804
  🔥 New best F1: 0.2804 – model saved.

Epoch 4/8


    t_loss=1.9460 | F1(macro)=0.2554 | Acc=0.2559


Confusion matrix:
 [[11  7 15  8]
 [ 9  6 13  3]
 [ 6  7 13  4]
 [ 3  2  6  3]]
Train  loss=1.9460 acc=0.2559 f1=0.2554 | Val loss=2.6498 acc=0.2845 f1=0.2665

Epoch 5/8


    t_loss=1.8466 | F1(macro)=0.2808 | Acc=0.2817


Confusion matrix:
 [[11  8 16  6]
 [13  5 10  3]
 [ 6 10 11  3]
 [ 4  3  6  1]]
Train  loss=1.8466 acc=0.2817 f1=0.2808 | Val loss=2.5799 acc=0.2414 f1=0.2111

Epoch 6/8


    t_loss=1.7630 | F1(macro)=0.3170 | Acc=0.3204


Confusion matrix:
 [[ 7  6 20  8]
 [ 8  6 15  2]
 [ 6  5 15  4]
 [ 4  1  6  3]]
Train  loss=1.7630 acc=0.3204 f1=0.3170 | Val loss=2.6131 acc=0.2672 f1=0.2499

Epoch 7/8


    t_loss=1.8364 | F1(macro)=0.2882 | Acc=0.2925


Confusion matrix:
 [[ 6  7 16 12]
 [ 7  8 12  4]
 [ 6 10 11  3]
 [ 2  4  6  2]]
Train  loss=1.8364 acc=0.2925 f1=0.2882 | Val loss=2.7528 acc=0.2328 f1=0.2170

Epoch 8/8


    t_loss=1.8514 | F1(macro)=0.2944 | Acc=0.2946


Confusion matrix:
 [[ 8  7 16 10]
 [ 8  4 15  4]
 [ 4  7 13  6]
 [ 4  1  6  3]]
Train  loss=1.8514 acc=0.2946 f1=0.2944 | Val loss=2.6971 acc=0.2414 f1=0.2233
Restored best Stage 1 weights for fold 2 (F1=0.2804)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.9387 | F1(macro)=0.3112 | Acc=0.3226


Confusion matrix:
 [[ 6  1 14 20]
 [10  1 11  9]
 [ 6  3 10 11]
 [ 2  1  5  6]]
Train  loss=1.9387 acc=0.3226 f1=0.3112 | Val loss=2.7490 acc=0.1983 f1=0.1811
  🔥 New best F1: 0.1811 – model saved.

Epoch 2/12


    t_loss=1.6837 | F1(macro)=0.3365 | Acc=0.3484


Confusion matrix:
 [[ 3 14  4 20]
 [ 1 13  7 10]
 [ 2 13  6  9]
 [ 1  3  4  6]]
Train  loss=1.6837 acc=0.3484 f1=0.3365 | Val loss=2.3926 acc=0.2414 f1=0.2288
  🔥 New best F1: 0.2288 – model saved.

Epoch 3/12


    t_loss=1.5509 | F1(macro)=0.3143 | Acc=0.3269


Confusion matrix:
 [[16  9  7  9]
 [ 8 11  1 11]
 [15  8  3  4]
 [ 5  4  2  3]]
Train  loss=1.5509 acc=0.3269 f1=0.3143 | Val loss=2.3782 acc=0.2845 f1=0.2529
  🔥 New best F1: 0.2529 – model saved.

Epoch 4/12


    t_loss=1.5075 | F1(macro)=0.3612 | Acc=0.3742


Confusion matrix:
 [[18  9  6  8]
 [ 9 14  5  3]
 [10 10  6  4]
 [ 7  3  2  2]]
Train  loss=1.5075 acc=0.3742 f1=0.3612 | Val loss=2.1904 acc=0.3448 f1=0.3038
  🔥 New best F1: 0.3038 – model saved.

Epoch 5/12


    t_loss=1.3399 | F1(macro)=0.4108 | Acc=0.4258


Confusion matrix:
 [[ 4 11  8 18]
 [ 1 11  7 12]
 [ 0 12  7 11]
 [ 2  1  7  4]]
Train  loss=1.3399 acc=0.4258 f1=0.4108 | Val loss=2.2301 acc=0.2241 f1=0.2182

Epoch 6/12


    t_loss=1.2689 | F1(macro)=0.4415 | Acc=0.4581


Confusion matrix:
 [[19  3 10  9]
 [13  3  7  8]
 [11  3 10  6]
 [ 8  0  4  2]]
Train  loss=1.2689 acc=0.4581 f1=0.4415 | Val loss=2.0656 acc=0.2931 f1=0.2484

Epoch 7/12


    t_loss=1.1701 | F1(macro)=0.4483 | Acc=0.4602


Confusion matrix:
 [[12  4 12 13]
 [ 8  8  8  7]
 [ 9  4  8  9]
 [ 6  1  3  4]]
Train  loss=1.1701 acc=0.4602 f1=0.4483 | Val loss=1.9214 acc=0.2759 f1=0.2704

Epoch 8/12


    t_loss=1.0889 | F1(macro)=0.5053 | Acc=0.5247


Confusion matrix:
 [[14  3  8 16]
 [ 7  7  6 11]
 [ 9  3  4 14]
 [ 3  0  3  8]]
Train  loss=1.0889 acc=0.5247 f1=0.5053 | Val loss=2.0010 acc=0.2845 f1=0.2768

Epoch 9/12


    t_loss=1.0174 | F1(macro)=0.5529 | Acc=0.5591


Confusion matrix:
 [[15  5 12  9]
 [ 8 10  9  4]
 [ 4  7 15  4]
 [ 4  2  8  0]]
Train  loss=1.0174 acc=0.5591 f1=0.5529 | Val loss=2.0559 acc=0.3448 f1=0.2964

Epoch 10/12


    t_loss=0.9958 | F1(macro)=0.5371 | Acc=0.5527


Confusion matrix:
 [[13  8 11  9]
 [ 4 13 10  4]
 [ 4  9 11  6]
 [ 4  3  6  1]]
Train  loss=0.9958 acc=0.5527 f1=0.5371 | Val loss=2.1155 acc=0.3276 f1=0.2956

Epoch 11/12


    t_loss=1.0105 | F1(macro)=0.5744 | Acc=0.5957


Confusion matrix:
 [[12  9  8 12]
 [ 5  9 11  6]
 [ 6  5 10  9]
 [ 5  1  6  2]]
Train  loss=1.0105 acc=0.5957 f1=0.5744 | Val loss=2.0683 acc=0.2845 f1=0.2690

Epoch 12/12


    t_loss=0.9247 | F1(macro)=0.5970 | Acc=0.6172


Confusion matrix:
 [[12  8 11 10]
 [ 8  8  9  6]
 [ 5  7 10  8]
 [ 5  1  7  1]]
Train  loss=0.9247 acc=0.6172 f1=0.5970 | Val loss=2.0070 acc=0.2672 f1=0.2447

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.6215 | F1(macro)=0.2313 | Acc=0.2323


Confusion matrix:
 [[13 11  9  8]
 [13  8  2  8]
 [10 10  2  8]
 [ 9  3  0  2]]
Train  loss=2.6215 acc=0.2323 f1=0.2313 | Val loss=2.9449 acc=0.2155 f1=0.1873
  🔥 New best F1: 0.1873 – model saved.

Epoch 2/8


    t_loss=2.2151 | F1(macro)=0.2800 | Acc=0.2796


Confusion matrix:
 [[20  9  7  5]
 [19  4  2  6]
 [12 10  3  5]
 [ 8  3  3  0]]
Train  loss=2.2151 acc=0.2796 f1=0.2800 | Val loss=2.5460 acc=0.2328 f1=0.1684

Epoch 3/8


    t_loss=2.0718 | F1(macro)=0.2349 | Acc=0.2366


Confusion matrix:
 [[13 12 10  6]
 [17  7  2  5]
 [10  9  6  5]
 [ 6  3  2  3]]
Train  loss=2.0718 acc=0.2366 f1=0.2349 | Val loss=2.7127 acc=0.2500 f1=0.2366
  🔥 New best F1: 0.2366 – model saved.

Epoch 4/8


    t_loss=2.0882 | F1(macro)=0.2648 | Acc=0.2645


Confusion matrix:
 [[ 9  8 15  9]
 [14  4  6  7]
 [ 9  5  7  9]
 [ 8  2  2  2]]
Train  loss=2.0882 acc=0.2645 f1=0.2648 | Val loss=2.5698 acc=0.1897 f1=0.1783

Epoch 5/8


    t_loss=1.8732 | F1(macro)=0.2817 | Acc=0.2839


Confusion matrix:
 [[17 11  8  5]
 [15  9  1  6]
 [11 10  2  7]
 [ 8  3  1  2]]
Train  loss=1.8732 acc=0.2839 f1=0.2817 | Val loss=2.5356 acc=0.2586 f1=0.2159

Epoch 6/8


    t_loss=1.9164 | F1(macro)=0.2866 | Acc=0.2882


Confusion matrix:
 [[14  6 16  5]
 [18  5  6  2]
 [11  9  5  5]
 [10  0  3  1]]
Train  loss=1.9164 acc=0.2882 f1=0.2866 | Val loss=2.4626 acc=0.2155 f1=0.1837

Epoch 7/8


    t_loss=1.8618 | F1(macro)=0.2917 | Acc=0.2903


Confusion matrix:
 [[18  7 11  5]
 [18  5  5  3]
 [12  8  5  5]
 [ 9  2  2  1]]
Train  loss=1.8618 acc=0.2903 f1=0.2917 | Val loss=2.4949 acc=0.2500 f1=0.2040

Epoch 8/8


    t_loss=1.9532 | F1(macro)=0.2519 | Acc=0.2559


Confusion matrix:
 [[13  8 15  5]
 [16  5  7  3]
 [ 8 10  7  5]
 [ 8  2  2  2]]
Train  loss=1.9532 acc=0.2559 f1=0.2519 | Val loss=2.5969 acc=0.2328 f1=0.2121
Restored best Stage 1 weights for fold 3 (F1=0.2366)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.9458 | F1(macro)=0.2992 | Acc=0.3054


Confusion matrix:
 [[12 22  4  3]
 [13 14  2  2]
 [10 12  5  3]
 [ 3 10  0  1]]
Train  loss=1.9458 acc=0.3054 f1=0.2992 | Val loss=2.9586 acc=0.2759 f1=0.2373
  🔥 New best F1: 0.2373 – model saved.

Epoch 2/12


    t_loss=1.6606 | F1(macro)=0.3499 | Acc=0.3656


Confusion matrix:
 [[14 11  8  8]
 [ 6 19  3  3]
 [ 9 10  3  8]
 [ 4  6  1  3]]
Train  loss=1.6606 acc=0.3656 f1=0.3499 | Val loss=2.1115 acc=0.3362 f1=0.2930
  🔥 New best F1: 0.2930 – model saved.

Epoch 3/12


    t_loss=1.4648 | F1(macro)=0.4108 | Acc=0.4215


Confusion matrix:
 [[13  2 14 12]
 [10  1 17  3]
 [ 8  1 12  9]
 [ 4  0  8  2]]
Train  loss=1.4648 acc=0.4215 f1=0.4108 | Val loss=1.9860 acc=0.2414 f1=0.1989

Epoch 4/12


    t_loss=1.3307 | F1(macro)=0.4055 | Acc=0.4258


Confusion matrix:
 [[12  6 17  6]
 [ 6  8 11  6]
 [ 5  6 14  5]
 [ 3  2  6  3]]
Train  loss=1.3307 acc=0.4258 f1=0.4055 | Val loss=2.0367 acc=0.3190 f1=0.2989
  🔥 New best F1: 0.2989 – model saved.

Epoch 5/12


    t_loss=1.2019 | F1(macro)=0.4881 | Acc=0.5011


Confusion matrix:
 [[11 12 16  2]
 [ 6 17  6  2]
 [ 4  7 15  4]
 [ 3  4  6  1]]
Train  loss=1.2019 acc=0.5011 f1=0.4881 | Val loss=1.8068 acc=0.3793 f1=0.3288
  🔥 New best F1: 0.3288 – model saved.

Epoch 6/12


    t_loss=1.1294 | F1(macro)=0.4534 | Acc=0.4882


Confusion matrix:
 [[16  5 14  6]
 [12  7  7  5]
 [10  5  7  8]
 [ 2  2  5  5]]
Train  loss=1.1294 acc=0.4882 f1=0.4534 | Val loss=1.6395 acc=0.3017 f1=0.2901

Epoch 7/12


    t_loss=1.0377 | F1(macro)=0.5467 | Acc=0.5634


Confusion matrix:
 [[13  8 14  6]
 [ 6 12  6  7]
 [ 7  5 11  7]
 [ 3  0  4  7]]
Train  loss=1.0377 acc=0.5634 f1=0.5467 | Val loss=1.6265 acc=0.3707 f1=0.3700
  🔥 New best F1: 0.3700 – model saved.

Epoch 8/12


    t_loss=1.0123 | F1(macro)=0.5725 | Acc=0.5806


Confusion matrix:
 [[14  8 13  6]
 [ 9  9 10  3]
 [11  5  7  7]
 [ 4  2  4  4]]
Train  loss=1.0123 acc=0.5806 f1=0.5725 | Val loss=1.7241 acc=0.2931 f1=0.2839

Epoch 9/12


    t_loss=0.9104 | F1(macro)=0.6177 | Acc=0.6344


Confusion matrix:
 [[16  9 12  4]
 [14 11  3  3]
 [12  4  7  7]
 [ 3  2  2  7]]
Train  loss=0.9104 acc=0.6344 f1=0.6177 | Val loss=1.6239 acc=0.3534 f1=0.3543

Epoch 10/12


    t_loss=0.8596 | F1(macro)=0.6322 | Acc=0.6387


Confusion matrix:
 [[21  9  7  4]
 [15 11  2  3]
 [15  7  2  6]
 [ 6  0  2  6]]
Train  loss=0.8596 acc=0.6387 f1=0.6322 | Val loss=1.7619 acc=0.3448 f1=0.3161

Epoch 11/12


    t_loss=0.7917 | F1(macro)=0.6902 | Acc=0.7032


Confusion matrix:
 [[18  8 11  4]
 [11 10  7  3]
 [12  5  9  4]
 [ 6  2  3  3]]
Train  loss=0.7917 acc=0.7032 f1=0.6902 | Val loss=1.7014 acc=0.3448 f1=0.3201

Epoch 12/12


    t_loss=0.8793 | F1(macro)=0.6741 | Acc=0.6796


Confusion matrix:
 [[14 12 11  4]
 [11 15  5  0]
 [ 9  8  9  4]
 [ 6  3  3  2]]
Train  loss=0.8793 acc=0.6796 f1=0.6741 | Val loss=1.7633 acc=0.3448 f1=0.3144

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.1933 | F1(macro)=0.2685 | Acc=0.2731


Confusion matrix:
 [[ 5 18 13  5]
 [ 4 13 10  5]
 [ 4 14  7  5]
 [ 1  6  1  5]]
Train  loss=2.1933 acc=0.2731 f1=0.2685 | Val loss=2.2702 acc=0.2586 f1=0.2569
  🔥 New best F1: 0.2569 – model saved.

Epoch 2/8


    t_loss=2.1164 | F1(macro)=0.2518 | Acc=0.2602


Confusion matrix:
 [[10  7 15  9]
 [ 6  9  8  9]
 [ 4  8  9  9]
 [ 1  4  3  5]]
Train  loss=2.1164 acc=0.2602 f1=0.2518 | Val loss=2.2167 acc=0.2845 f1=0.2804
  🔥 New best F1: 0.2804 – model saved.

Epoch 3/8


    t_loss=2.0020 | F1(macro)=0.2981 | Acc=0.2989


Confusion matrix:
 [[14 11 12  4]
 [ 5 12  9  6]
 [ 7 14  4  5]
 [ 1  4  2  6]]
Train  loss=2.0020 acc=0.2989 f1=0.2981 | Val loss=2.0968 acc=0.3103 f1=0.3085
  🔥 New best F1: 0.3085 – model saved.

Epoch 4/8


    t_loss=1.8508 | F1(macro)=0.2941 | Acc=0.2925


Confusion matrix:
 [[16  2 14  9]
 [10  7 10  5]
 [11  5  9  5]
 [ 2  3  3  5]]
Train  loss=1.8508 acc=0.2925 f1=0.2941 | Val loss=2.0530 acc=0.3190 f1=0.3072

Epoch 5/8


    t_loss=1.9940 | F1(macro)=0.2521 | Acc=0.2538


Confusion matrix:
 [[13  7 17  4]
 [10  6 10  6]
 [ 7  7 14  2]
 [ 2  4  2  5]]
Train  loss=1.9940 acc=0.2538 f1=0.2521 | Val loss=2.0085 acc=0.3276 f1=0.3218
  🔥 New best F1: 0.3218 – model saved.

Epoch 6/8


    t_loss=1.8232 | F1(macro)=0.3084 | Acc=0.3140


Confusion matrix:
 [[17  7  9  8]
 [ 9 10  7  6]
 [ 9 12  4  5]
 [ 2  4  2  5]]
Train  loss=1.8232 acc=0.3140 f1=0.3084 | Val loss=2.0769 acc=0.3103 f1=0.2919

Epoch 7/8


    t_loss=1.7546 | F1(macro)=0.3062 | Acc=0.3097


Confusion matrix:
 [[12 10 11  8]
 [10  8  7  7]
 [10  5  8  7]
 [ 1  2  4  6]]
Train  loss=1.7546 acc=0.3097 f1=0.3062 | Val loss=1.9703 acc=0.2931 f1=0.2911

Epoch 8/8


    t_loss=1.7802 | F1(macro)=0.3272 | Acc=0.3290


Confusion matrix:
 [[11  9 17  4]
 [ 9 10  9  4]
 [ 8 11  9  2]
 [ 1  4  2  6]]
Train  loss=1.7802 acc=0.3290 f1=0.3272 | Val loss=2.0331 acc=0.3103 f1=0.3249
  🔥 New best F1: 0.3249 – model saved.
Restored best Stage 1 weights for fold 4 (F1=0.3249)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=2.0214 | F1(macro)=0.2645 | Acc=0.2731


Confusion matrix:
 [[11  4 13 13]
 [ 4  2  8 18]
 [ 5  3  9 13]
 [ 1  2  2  8]]
Train  loss=2.0214 acc=0.2731 f1=0.2645 | Val loss=2.4542 acc=0.2586 f1=0.2461
  🔥 New best F1: 0.2461 – model saved.

Epoch 2/12


    t_loss=1.7198 | F1(macro)=0.3103 | Acc=0.3269


Confusion matrix:
 [[ 6 12 18  5]
 [ 9 14  7  2]
 [ 5  6 13  6]
 [ 2  2  5  4]]
Train  loss=1.7198 acc=0.3269 f1=0.3103 | Val loss=2.0456 acc=0.3190 f1=0.3094
  🔥 New best F1: 0.3094 – model saved.

Epoch 3/12


    t_loss=1.3253 | F1(macro)=0.3866 | Acc=0.4237


Confusion matrix:
 [[ 6 21  4 10]
 [ 6 16  5  5]
 [ 2 11  3 14]
 [ 2  3  1  7]]
Train  loss=1.3253 acc=0.4237 f1=0.3866 | Val loss=2.2636 acc=0.2759 f1=0.2553

Epoch 4/12


    t_loss=1.3754 | F1(macro)=0.3951 | Acc=0.4022


Confusion matrix:
 [[27  1 10  3]
 [16  0 11  5]
 [16  1 11  2]
 [ 6  1  3  3]]
Train  loss=1.3754 acc=0.4022 f1=0.3951 | Val loss=2.2981 acc=0.3534 f1=0.2697

Epoch 5/12


    t_loss=1.2792 | F1(macro)=0.4040 | Acc=0.4086


Confusion matrix:
 [[ 6  2 12 21]
 [ 4  2  9 17]
 [ 3  2  6 19]
 [ 3  2  3  5]]
Train  loss=1.2792 acc=0.4086 f1=0.4040 | Val loss=2.2221 acc=0.1638 f1=0.1610

Epoch 6/12


    t_loss=1.2149 | F1(macro)=0.4250 | Acc=0.4452


Confusion matrix:
 [[ 8  4  4 25]
 [ 2  5  2 23]
 [ 0  2  1 27]
 [ 0  1  0 12]]
Train  loss=1.2149 acc=0.4452 f1=0.4250 | Val loss=2.3067 acc=0.2241 f1=0.2088

Epoch 7/12


    t_loss=1.0711 | F1(macro)=0.5147 | Acc=0.5376


Confusion matrix:
 [[ 7  8  7 19]
 [10  3  7 12]
 [10  4  3 13]
 [ 4  2  1  6]]
Train  loss=1.0711 acc=0.5376 f1=0.5147 | Val loss=2.1278 acc=0.1638 f1=0.1581

Epoch 8/12


    t_loss=1.1372 | F1(macro)=0.5253 | Acc=0.5376


Confusion matrix:
 [[16 14  5  6]
 [15  8  4  5]
 [13  7  4  6]
 [ 7  2  1  3]]
Train  loss=1.1372 acc=0.5376 f1=0.5253 | Val loss=1.9314 acc=0.2672 f1=0.2414

Epoch 9/12


    t_loss=1.0486 | F1(macro)=0.5685 | Acc=0.5763


Confusion matrix:
 [[13 13  6  9]
 [ 7 13  6  6]
 [12  9  2  7]
 [ 5  2  0  6]]
Train  loss=1.0486 acc=0.5763 f1=0.5685 | Val loss=1.8626 acc=0.2931 f1=0.2734

Epoch 10/12


    t_loss=1.0191 | F1(macro)=0.5769 | Acc=0.5849


Confusion matrix:
 [[14  4  9 14]
 [11  4  5 12]
 [10  5  4 11]
 [ 4  2  0  7]]
Train  loss=1.0191 acc=0.5849 f1=0.5769 | Val loss=1.9974 acc=0.2500 f1=0.2331

Epoch 11/12


    t_loss=0.9643 | F1(macro)=0.5728 | Acc=0.5871


Confusion matrix:
 [[12 14  4 11]
 [ 9  7  8  8]
 [10  6  3 11]
 [ 5  2  0  6]]
Train  loss=0.9643 acc=0.5871 f1=0.5728 | Val loss=1.9155 acc=0.2414 f1=0.2299

Epoch 12/12


    t_loss=0.9191 | F1(macro)=0.5945 | Acc=0.6129


Confusion matrix:
 [[12 14  7  8]
 [ 8  9  9  6]
 [ 9  8  4  9]
 [ 6  2  0  5]]
Train  loss=0.9191 acc=0.6129 f1=0.5945 | Val loss=1.9996 acc=0.2586 f1=0.2492


# tf_efficientnetv2_s.in21k

In [5]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [6]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

In [7]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png        Luminal B
1  img_0001.png  Triple negative
2  img_0002.png        Luminal A
3  img_0003.png  Triple negative
4  img_0004.png        Luminal A


In [8]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
                         shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            img_tensor = img_tensor.squeeze(0)  # [3,H,W]
            img_tensor = img_tensor.to(device)

            # -------- TTA: apply multiple augmented views --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1,4]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N, 4]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
pred_indices = mean_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print("Saved submission_5fold_tta.csv")

Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_tta.csv


In [9]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.31215237634050624
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.3003313164859775
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.29386558563387827
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.3065126050420168
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.2577762634247397
Mean OOF F1: 0.2941276293854237
