In [1]:
import enum
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from timm.layers import Conv2dSame
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.persistence_manager import PersistenceManager
from notebooks.internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cpu


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B0

In [4]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=True,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,   # True because we need labels
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_efficientnet_b0_model()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        clf_module, clf_name = get_classifier_module(model)
        for param in clf_module.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effb0_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effb0_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")


========== Fold 0 ==========


model.safetensors:   0%|          | 0.00/21.4M [00:00<?, ?B/s]


--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.1839 | F1(macro)=0.2467 | Acc=0.2500


Confusion matrix:
 [[ 8  5 15 13]
 [ 9  9  4 10]
 [10  6  8  6]
 [ 4  2  3  5]]
Train  loss=2.1839 acc=0.2500 f1=0.2467 | Val loss=2.4301 acc=0.2564 f1=0.2576
  🔥 New best F1: 0.2576 – model saved.

Epoch 2/8


    t_loss=2.0096 | F1(macro)=0.2730 | Acc=0.2737


Confusion matrix:
 [[ 7 12 15  7]
 [ 4 10  8 10]
 [ 7 11  4  8]
 [ 2  6  2  4]]
Train  loss=2.0096 acc=0.2737 f1=0.2730 | Val loss=2.2479 acc=0.2137 f1=0.2082

Epoch 3/8


    t_loss=1.9333 | F1(macro)=0.2805 | Acc=0.2802


Confusion matrix:
 [[ 8 14 13  6]
 [ 6  6 11  9]
 [ 4  6  8 12]
 [ 6  1  2  5]]
Train  loss=1.9333 acc=0.2802 f1=0.2805 | Val loss=2.1764 acc=0.2308 f1=0.2292

Epoch 4/8


    t_loss=1.8587 | F1(macro)=0.2995 | Acc=0.2996


Confusion matrix:
 [[ 6  7 22  6]
 [ 5 14  8  5]
 [ 2  3 21  4]
 [ 1  5  3  5]]
Train  loss=1.8587 acc=0.2996 f1=0.2995 | Val loss=2.0291 acc=0.3932 f1=0.3678
  🔥 New best F1: 0.3678 – model saved.

Epoch 5/8


    t_loss=1.6677 | F1(macro)=0.3288 | Acc=0.3319


Confusion matrix:
 [[11 14  5 11]
 [ 6 12  7  7]
 [ 6  6 10  8]
 [ 2  5  1  6]]
Train  loss=1.6677 acc=0.3319 f1=0.3288 | Val loss=2.0338 acc=0.3333 f1=0.3298

Epoch 6/8


    t_loss=1.8195 | F1(macro)=0.3059 | Acc=0.3103


Confusion matrix:
 [[12  9 11  9]
 [ 5 15  6  6]
 [ 8  8 10  4]
 [ 4  3  5  2]]
Train  loss=1.8195 acc=0.3103 f1=0.3059 | Val loss=1.8176 acc=0.3333 f1=0.3069

Epoch 7/8


    t_loss=1.7243 | F1(macro)=0.3237 | Acc=0.3233


Confusion matrix:
 [[11 14  8  8]
 [ 8 12  4  8]
 [ 6  8 12  4]
 [ 2  4  4  4]]
Train  loss=1.7243 acc=0.3233 f1=0.3237 | Val loss=2.1260 acc=0.3333 f1=0.3227

Epoch 8/8


    t_loss=1.7949 | F1(macro)=0.2685 | Acc=0.2694


Confusion matrix:
 [[ 8 14 10  9]
 [11 11  6  4]
 [ 7  8 10  5]
 [ 1  3  5  5]]
Train  loss=1.7949 acc=0.2694 f1=0.2685 | Val loss=1.9978 acc=0.2906 f1=0.2892
Restored best Stage 1 weights for fold 0 (F1=0.3678)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.6657 | F1(macro)=0.2735 | Acc=0.3039


Confusion matrix:
 [[ 6 12  6 17]
 [ 5 10  2 15]
 [ 7  3  8 12]
 [ 1  5  1  7]]
Train  loss=1.6657 acc=0.3039 f1=0.2735 | Val loss=2.1020 acc=0.2650 f1=0.2696
  🔥 New best F1: 0.2696 – model saved.

Epoch 2/12


    t_loss=1.4009 | F1(macro)=0.3712 | Acc=0.3901


Confusion matrix:
 [[ 9 12 11  9]
 [ 6 13  8  5]
 [ 4  3 12 11]
 [ 3  1  4  6]]
Train  loss=1.4009 acc=0.3901 f1=0.3712 | Val loss=2.1016 acc=0.3419 f1=0.3370
  🔥 New best F1: 0.3370 – model saved.

Epoch 3/12


    t_loss=1.3069 | F1(macro)=0.4215 | Acc=0.4569


Confusion matrix:
 [[ 8  9  9 15]
 [ 6  9  6 11]
 [ 7  2 12  9]
 [ 1  2  4  7]]
Train  loss=1.3069 acc=0.4569 f1=0.4215 | Val loss=2.0491 acc=0.3077 f1=0.3077

Epoch 4/12


    t_loss=1.3421 | F1(macro)=0.4521 | Acc=0.4634


Confusion matrix:
 [[ 7 17  8  9]
 [ 6  9 10  7]
 [ 8  1 12  9]
 [ 1  1  3  9]]
Train  loss=1.3421 acc=0.4634 f1=0.4521 | Val loss=1.9204 acc=0.3162 f1=0.3195

Epoch 5/12


    t_loss=1.2287 | F1(macro)=0.4375 | Acc=0.4547


Confusion matrix:
 [[11 14  7  9]
 [10  9  5  8]
 [ 8  7 11  4]
 [ 3  3  1  7]]
Train  loss=1.2287 acc=0.4547 f1=0.4375 | Val loss=1.7892 acc=0.3248 f1=0.3298

Epoch 6/12


    t_loss=1.1107 | F1(macro)=0.5098 | Acc=0.5345


Confusion matrix:
 [[10  8 13 10]
 [10  8  7  7]
 [ 9  2 11  8]
 [ 2  0  4  8]]
Train  loss=1.1107 acc=0.5345 f1=0.5098 | Val loss=1.9443 acc=0.3162 f1=0.3192

Epoch 7/12


    t_loss=1.0779 | F1(macro)=0.5189 | Acc=0.5409


Confusion matrix:
 [[ 7 10 11 13]
 [ 9 10  6  7]
 [10  4 10  6]
 [ 6  1  0  7]]
Train  loss=1.0779 acc=0.5409 f1=0.5189 | Val loss=1.9965 acc=0.2906 f1=0.2979

Epoch 8/12


    t_loss=1.0866 | F1(macro)=0.5571 | Acc=0.5733


Confusion matrix:
 [[12 16  7  6]
 [ 6 10  6 10]
 [ 7  3 12  8]
 [ 2  1  3  8]]
Train  loss=1.0866 acc=0.5733 f1=0.5571 | Val loss=1.8197 acc=0.3590 f1=0.3593
  🔥 New best F1: 0.3593 – model saved.

Epoch 9/12


    t_loss=0.9745 | F1(macro)=0.5658 | Acc=0.5884


Confusion matrix:
 [[ 6 21  6  8]
 [ 9 12  5  6]
 [ 7  5 10  8]
 [ 2  2  3  7]]
Train  loss=0.9745 acc=0.5884 f1=0.5658 | Val loss=1.8981 acc=0.2991 f1=0.3035

Epoch 10/12


    t_loss=0.9862 | F1(macro)=0.5806 | Acc=0.5970


Confusion matrix:
 [[ 8 14 11  8]
 [ 6 13  6  7]
 [ 9  5 10  6]
 [ 6  1  3  4]]
Train  loss=0.9862 acc=0.5970 f1=0.5806 | Val loss=1.9313 acc=0.2991 f1=0.2918

Epoch 11/12


    t_loss=0.9854 | F1(macro)=0.5850 | Acc=0.5991


Confusion matrix:
 [[11 14  8  8]
 [12  9  4  7]
 [10  3 10  7]
 [ 5  1  2  6]]
Train  loss=0.9854 acc=0.5991 f1=0.5850 | Val loss=1.9112 acc=0.3077 f1=0.3099

Epoch 12/12


    t_loss=1.0098 | F1(macro)=0.5607 | Acc=0.5711


Confusion matrix:
 [[ 7 17 10  7]
 [ 9 14  4  5]
 [ 6  7 11  6]
 [ 4  2  1  7]]
Train  loss=1.0098 acc=0.5711 f1=0.5607 | Val loss=1.8770 acc=0.3333 f1=0.3374

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.3148 | F1(macro)=0.2290 | Acc=0.2301


Confusion matrix:
 [[10  7  8 15]
 [ 5 15  1 11]
 [10  9  3  8]
 [ 6  4  0  4]]
Train  loss=2.3148 acc=0.2301 f1=0.2290 | Val loss=2.4350 acc=0.2759 f1=0.2565
  🔥 New best F1: 0.2565 – model saved.

Epoch 2/8


    t_loss=1.9877 | F1(macro)=0.2706 | Acc=0.2710


Confusion matrix:
 [[12 17  9  2]
 [ 3 23  2  4]
 [ 7 12  7  4]
 [ 2  7  2  3]]
Train  loss=1.9877 acc=0.2710 f1=0.2706 | Val loss=2.0642 acc=0.3879 f1=0.3457
  🔥 New best F1: 0.3457 – model saved.

Epoch 3/8


    t_loss=1.8097 | F1(macro)=0.2856 | Acc=0.2860


Confusion matrix:
 [[14  9 10  7]
 [ 9  7  5 11]
 [10  8  3  9]
 [ 5  5  0  4]]
Train  loss=1.8097 acc=0.2860 f1=0.2856 | Val loss=2.2197 acc=0.2414 f1=0.2228

Epoch 4/8


    t_loss=1.7220 | F1(macro)=0.3433 | Acc=0.3484


Confusion matrix:
 [[18  8  6  8]
 [11  9  3  9]
 [11  7  3  9]
 [ 4  4  2  4]]
Train  loss=1.7220 acc=0.3484 f1=0.3433 | Val loss=2.1501 acc=0.2931 f1=0.2617

Epoch 5/8


    t_loss=1.7321 | F1(macro)=0.3195 | Acc=0.3269


Confusion matrix:
 [[14 10  8  8]
 [14  9  0  9]
 [ 7 16  3  4]
 [ 7  3  3  1]]
Train  loss=1.7321 acc=0.3269 f1=0.3195 | Val loss=2.1509 acc=0.2328 f1=0.1976

Epoch 6/8


    t_loss=1.6822 | F1(macro)=0.3007 | Acc=0.3011


Confusion matrix:
 [[16  5 11  8]
 [ 6 12  5  9]
 [ 6 10  6  8]
 [ 4  3  4  3]]
Train  loss=1.6822 acc=0.3011 f1=0.3007 | Val loss=1.9843 acc=0.3190 f1=0.2972

Epoch 7/8


    t_loss=1.7308 | F1(macro)=0.2976 | Acc=0.2968


Confusion matrix:
 [[10  9 10 11]
 [ 4 13  3 12]
 [13  3  8  6]
 [ 5  4  2  3]]
Train  loss=1.7308 acc=0.2968 f1=0.2976 | Val loss=2.0381 acc=0.2931 f1=0.2841

Epoch 8/8


    t_loss=1.6652 | F1(macro)=0.3168 | Acc=0.3183


Confusion matrix:
 [[15 12  5  8]
 [ 5 14  5  8]
 [11 11  3  5]
 [ 5  4  0  5]]
Train  loss=1.6652 acc=0.3183 f1=0.3168 | Val loss=1.9983 acc=0.3190 f1=0.2920
Restored best Stage 1 weights for fold 1 (F1=0.3457)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.5675 | F1(macro)=0.3404 | Acc=0.3548


Confusion matrix:
 [[ 8 11  7 14]
 [ 9 10  1 12]
 [ 9  8  4  9]
 [ 5  3  2  4]]
Train  loss=1.5675 acc=0.3548 f1=0.3404 | Val loss=2.1651 acc=0.2241 f1=0.2177
  🔥 New best F1: 0.2177 – model saved.

Epoch 2/12


    t_loss=1.4136 | F1(macro)=0.3900 | Acc=0.4108


Confusion matrix:
 [[ 5 10 11 14]
 [10 11  2  9]
 [ 4 10  7  9]
 [ 1  1  2 10]]
Train  loss=1.4136 acc=0.4108 f1=0.3900 | Val loss=1.9812 acc=0.2845 f1=0.2842
  🔥 New best F1: 0.2842 – model saved.

Epoch 3/12


    t_loss=1.3959 | F1(macro)=0.4176 | Acc=0.4258


Confusion matrix:
 [[ 8  3 11 18]
 [10 10  2 10]
 [10  9  4  7]
 [ 1  0  4  9]]
Train  loss=1.3959 acc=0.4258 f1=0.4176 | Val loss=2.1059 acc=0.2672 f1=0.2674

Epoch 4/12


    t_loss=1.3095 | F1(macro)=0.4682 | Acc=0.4753


Confusion matrix:
 [[10  8 11 11]
 [ 5 12  1 14]
 [ 5  8  7 10]
 [ 2  5  3  4]]
Train  loss=1.3095 acc=0.4753 f1=0.4682 | Val loss=2.2131 acc=0.2845 f1=0.2780

Epoch 5/12


    t_loss=1.2114 | F1(macro)=0.5037 | Acc=0.5097


Confusion matrix:
 [[ 8 11  9 12]
 [10 12  1  9]
 [ 8 10  5  7]
 [ 5  1  4  4]]
Train  loss=1.2114 acc=0.5097 f1=0.5037 | Val loss=2.0275 acc=0.2500 f1=0.2417

Epoch 6/12


    t_loss=1.1634 | F1(macro)=0.4911 | Acc=0.5054


Confusion matrix:
 [[13 11  5 11]
 [ 9  9  2 12]
 [ 7 10  4  9]
 [ 6  1  2  5]]
Train  loss=1.1634 acc=0.5054 f1=0.4911 | Val loss=1.9638 acc=0.2672 f1=0.2536

Epoch 7/12


    t_loss=1.0927 | F1(macro)=0.5253 | Acc=0.5376


Confusion matrix:
 [[ 9  5 13 13]
 [ 6  7  6 13]
 [ 7  6  7 10]
 [ 2  2  4  6]]
Train  loss=1.0927 acc=0.5376 f1=0.5253 | Val loss=2.1211 acc=0.2500 f1=0.2495

Epoch 8/12


    t_loss=1.0334 | F1(macro)=0.5647 | Acc=0.5720


Confusion matrix:
 [[ 7 12 10 11]
 [15 10  2  5]
 [11 10  5  4]
 [ 4  1  5  4]]
Train  loss=1.0334 acc=0.5720 f1=0.5647 | Val loss=1.9942 acc=0.2241 f1=0.2231

Epoch 9/12


    t_loss=0.9758 | F1(macro)=0.5976 | Acc=0.6086


Confusion matrix:
 [[11  8 10 11]
 [11  8  4  9]
 [ 7 12  2  9]
 [ 8  1  3  2]]
Train  loss=0.9758 acc=0.6086 f1=0.5976 | Val loss=2.0493 acc=0.1983 f1=0.1796

Epoch 10/12


    t_loss=1.0337 | F1(macro)=0.5670 | Acc=0.5720


Confusion matrix:
 [[ 9  8 10 13]
 [10 11  3  8]
 [10  9  5  6]
 [ 2  1  4  7]]
Train  loss=1.0337 acc=0.5720 f1=0.5670 | Val loss=2.0154 acc=0.2759 f1=0.2745

Epoch 11/12


    t_loss=0.9946 | F1(macro)=0.5928 | Acc=0.6043


Confusion matrix:
 [[14 11  9  6]
 [10 11  2  9]
 [ 9 12  3  6]
 [ 7  0  4  3]]
Train  loss=0.9946 acc=0.6043 f1=0.5928 | Val loss=1.9086 acc=0.2672 f1=0.2416

Epoch 12/12


    t_loss=0.9858 | F1(macro)=0.5774 | Acc=0.5957


Confusion matrix:
 [[10 14  9  7]
 [ 7 12  3 10]
 [ 3  9  8 10]
 [ 5  3  2  4]]
Train  loss=0.9858 acc=0.5957 f1=0.5774 | Val loss=2.0863 acc=0.2931 f1=0.2840

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.1816 | F1(macro)=0.2483 | Acc=0.2495


Confusion matrix:
 [[13  9 10  9]
 [13  9  4  5]
 [ 7  9  7  7]
 [ 6  2  2  4]]
Train  loss=2.1816 acc=0.2495 f1=0.2483 | Val loss=2.1767 acc=0.2845 f1=0.2736
  🔥 New best F1: 0.2736 – model saved.

Epoch 2/8


    t_loss=1.9721 | F1(macro)=0.2695 | Acc=0.2731


Confusion matrix:
 [[14 15  9  3]
 [10  6 10  5]
 [11  5 11  3]
 [ 5  6  2  1]]
Train  loss=1.9721 acc=0.2731 f1=0.2695 | Val loss=2.2969 acc=0.2759 f1=0.2420

Epoch 3/8


    t_loss=1.8911 | F1(macro)=0.2784 | Acc=0.2796


Confusion matrix:
 [[ 5  8 16 12]
 [11  9  6  5]
 [ 5 11  9  5]
 [ 5  2  2  5]]
Train  loss=1.8911 acc=0.2796 f1=0.2784 | Val loss=2.4121 acc=0.2414 f1=0.2435

Epoch 4/8


    t_loss=1.7303 | F1(macro)=0.3117 | Acc=0.3161


Confusion matrix:
 [[19  7  8  7]
 [17  4  7  3]
 [11  8  7  4]
 [ 9  1  1  3]]
Train  loss=1.7303 acc=0.3161 f1=0.3117 | Val loss=2.1146 acc=0.2845 f1=0.2516

Epoch 5/8


    t_loss=1.7732 | F1(macro)=0.3126 | Acc=0.3118


Confusion matrix:
 [[16  8  9  8]
 [15  2  9  5]
 [10  5  7  8]
 [ 6  1  3  4]]
Train  loss=1.7732 acc=0.3118 f1=0.3126 | Val loss=2.2412 acc=0.2500 f1=0.2238

Epoch 6/8


    t_loss=1.8196 | F1(macro)=0.2917 | Acc=0.2903


Confusion matrix:
 [[ 9 10 14  8]
 [ 5  3 17  6]
 [ 6  9 11  4]
 [ 5  4  1  4]]
Train  loss=1.8196 acc=0.2903 f1=0.2917 | Val loss=2.4173 acc=0.2328 f1=0.2254

Epoch 7/8


    t_loss=1.7007 | F1(macro)=0.3142 | Acc=0.3140


Confusion matrix:
 [[18  8  4 11]
 [11  5  9  6]
 [ 9  6  7  8]
 [ 2  3  1  8]]
Train  loss=1.7007 acc=0.3140 f1=0.3142 | Val loss=2.2155 acc=0.3276 f1=0.3120
  🔥 New best F1: 0.3120 – model saved.

Epoch 8/8


    t_loss=1.7079 | F1(macro)=0.3321 | Acc=0.3333


Confusion matrix:
 [[11 11  8 11]
 [12  7  6  6]
 [ 8  6  8  8]
 [ 3  4  2  5]]
Train  loss=1.7079 acc=0.3333 f1=0.3321 | Val loss=2.2523 acc=0.2672 f1=0.2635
Restored best Stage 1 weights for fold 2 (F1=0.3120)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.6863 | F1(macro)=0.2931 | Acc=0.3118


Confusion matrix:
 [[10  7  6 18]
 [ 8  8  5 10]
 [10  8  6  6]
 [ 2  5  1  6]]
Train  loss=1.6863 acc=0.3118 f1=0.2931 | Val loss=2.1984 acc=0.2586 f1=0.2563
  🔥 New best F1: 0.2563 – model saved.

Epoch 2/12


    t_loss=1.4217 | F1(macro)=0.3733 | Acc=0.3871


Confusion matrix:
 [[18  7  6 10]
 [13  6  4  8]
 [13  8  1  8]
 [10  0  0  4]]
Train  loss=1.4217 acc=0.3871 f1=0.3733 | Val loss=2.3428 acc=0.2500 f1=0.2101

Epoch 3/12


    t_loss=1.3579 | F1(macro)=0.4233 | Acc=0.4387


Confusion matrix:
 [[11 12  5 13]
 [ 8 12  5  6]
 [10 10  2  8]
 [ 3  4  0  7]]
Train  loss=1.3579 acc=0.4387 f1=0.4233 | Val loss=2.2244 acc=0.2759 f1=0.2590
  🔥 New best F1: 0.2590 – model saved.

Epoch 4/12


    t_loss=1.3355 | F1(macro)=0.4249 | Acc=0.4430


Confusion matrix:
 [[11 13  5 12]
 [12 14  5  0]
 [ 6 12  8  4]
 [ 3  4  4  3]]
Train  loss=1.3355 acc=0.4430 f1=0.4249 | Val loss=1.9500 acc=0.3103 f1=0.2923
  🔥 New best F1: 0.2923 – model saved.

Epoch 5/12


    t_loss=1.1580 | F1(macro)=0.5085 | Acc=0.5226


Confusion matrix:
 [[10  9  6 16]
 [ 6  9  6 10]
 [ 9  8  2 11]
 [ 2  3  2  7]]
Train  loss=1.1580 acc=0.5226 f1=0.5085 | Val loss=2.1803 acc=0.2414 f1=0.2306

Epoch 6/12


    t_loss=1.1489 | F1(macro)=0.5076 | Acc=0.5226


Confusion matrix:
 [[11 12 10  8]
 [ 6 10 11  4]
 [ 5 10  7  8]
 [ 8  2  2  2]]
Train  loss=1.1489 acc=0.5226 f1=0.5076 | Val loss=2.1571 acc=0.2586 f1=0.2405

Epoch 7/12


    t_loss=1.1530 | F1(macro)=0.4965 | Acc=0.5054


Confusion matrix:
 [[ 9 10  5 17]
 [10  7  6  8]
 [10  7  4  9]
 [ 2  2  3  7]]
Train  loss=1.1530 acc=0.5054 f1=0.4965 | Val loss=1.9344 acc=0.2328 f1=0.2292

Epoch 8/12


    t_loss=1.0356 | F1(macro)=0.5537 | Acc=0.5720


Confusion matrix:
 [[11  5  9 16]
 [ 6  7  8 10]
 [ 7  6  8  9]
 [ 5  1  0  8]]
Train  loss=1.0356 acc=0.5720 f1=0.5537 | Val loss=2.0182 acc=0.2931 f1=0.2915

Epoch 9/12


    t_loss=1.0504 | F1(macro)=0.5404 | Acc=0.5527


Confusion matrix:
 [[11  9 10 11]
 [ 7  9  9  6]
 [ 3  7 11  9]
 [ 1  3  1  9]]
Train  loss=1.0504 acc=0.5527 f1=0.5404 | Val loss=1.7539 acc=0.3448 f1=0.3456
  🔥 New best F1: 0.3456 – model saved.

Epoch 10/12


    t_loss=1.0323 | F1(macro)=0.5695 | Acc=0.5742


Confusion matrix:
 [[ 4 14  9 14]
 [ 5  8 12  6]
 [ 3 11 10  6]
 [ 3  0  4  7]]
Train  loss=1.0323 acc=0.5742 f1=0.5695 | Val loss=2.1226 acc=0.2500 f1=0.2496

Epoch 11/12


    t_loss=1.0089 | F1(macro)=0.5711 | Acc=0.5914


Confusion matrix:
 [[15 15  4  7]
 [ 9 10  8  4]
 [ 3 12  8  7]
 [ 5  3  1  5]]
Train  loss=1.0089 acc=0.5914 f1=0.5711 | Val loss=1.9651 acc=0.3276 f1=0.3192

Epoch 12/12


    t_loss=1.0149 | F1(macro)=0.5598 | Acc=0.5699


Confusion matrix:
 [[ 9 14  5 13]
 [ 5  8  7 11]
 [ 7  6 11  6]
 [ 4  1  1  8]]
Train  loss=1.0149 acc=0.5699 f1=0.5598 | Val loss=2.0289 acc=0.3103 f1=0.3136

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.0431 | F1(macro)=0.2857 | Acc=0.2903


Confusion matrix:
 [[ 5  5 16 15]
 [ 8  2 15  6]
 [ 4  7  7 12]
 [ 3  4  1  6]]
Train  loss=2.0431 acc=0.2903 f1=0.2857 | Val loss=2.5899 acc=0.1724 f1=0.1687
  🔥 New best F1: 0.1687 – model saved.

Epoch 2/8


    t_loss=1.9308 | F1(macro)=0.2534 | Acc=0.2559


Confusion matrix:
 [[ 7 10 14 10]
 [ 8  8 11  4]
 [ 9  7  7  7]
 [ 7  4  1  2]]
Train  loss=1.9308 acc=0.2559 f1=0.2534 | Val loss=2.4369 acc=0.2069 f1=0.1979
  🔥 New best F1: 0.1979 – model saved.

Epoch 3/8


    t_loss=1.8008 | F1(macro)=0.2653 | Acc=0.2667


Confusion matrix:
 [[10  7 18  6]
 [ 9  7 10  5]
 [11  4  5 10]
 [ 4  4  4  2]]
Train  loss=1.8008 acc=0.2667 f1=0.2653 | Val loss=2.3794 acc=0.2069 f1=0.1970

Epoch 4/8


    t_loss=1.7573 | F1(macro)=0.3186 | Acc=0.3204


Confusion matrix:
 [[ 8  9  9 15]
 [ 9  3 13  6]
 [ 4  6  5 15]
 [ 3  3  4  4]]
Train  loss=1.7573 acc=0.3204 f1=0.3186 | Val loss=2.5065 acc=0.1724 f1=0.1684

Epoch 5/8


    t_loss=1.8510 | F1(macro)=0.2790 | Acc=0.2796


Confusion matrix:
 [[ 3  5 22 11]
 [ 4  7 15  5]
 [ 5  2 11 12]
 [ 2  5  3  4]]
Train  loss=1.8510 acc=0.2796 f1=0.2790 | Val loss=2.2063 acc=0.2155 f1=0.2087
  🔥 New best F1: 0.2087 – model saved.

Epoch 6/8


    t_loss=1.7363 | F1(macro)=0.3458 | Acc=0.3484


Confusion matrix:
 [[ 3  8 16 14]
 [ 7  2 15  7]
 [ 4  4  8 14]
 [ 2  2  4  6]]
Train  loss=1.7363 acc=0.3484 f1=0.3458 | Val loss=2.4630 acc=0.1638 f1=0.1569

Epoch 7/8


    t_loss=1.7623 | F1(macro)=0.2834 | Acc=0.2860


Confusion matrix:
 [[10 10 12  9]
 [ 5  8 12  6]
 [ 8  5  8  9]
 [ 4  2  3  5]]
Train  loss=1.7623 acc=0.2860 f1=0.2834 | Val loss=2.0690 acc=0.2672 f1=0.2646
  🔥 New best F1: 0.2646 – model saved.

Epoch 8/8


    t_loss=1.7629 | F1(macro)=0.2908 | Acc=0.2903


Confusion matrix:
 [[ 7  5 12 17]
 [ 7  9  9  6]
 [ 6  6  6 12]
 [ 2  4  1  7]]
Train  loss=1.7629 acc=0.2903 f1=0.2908 | Val loss=2.1935 acc=0.2500 f1=0.2516
Restored best Stage 1 weights for fold 3 (F1=0.2646)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.6257 | F1(macro)=0.3436 | Acc=0.3484


Confusion matrix:
 [[ 9  9 12 11]
 [ 8  7 14  2]
 [ 7  3 13  7]
 [ 3  2  6  3]]
Train  loss=1.6257 acc=0.3484 f1=0.3436 | Val loss=2.1852 acc=0.2759 f1=0.2607
  🔥 New best F1: 0.2607 – model saved.

Epoch 2/12


    t_loss=1.5797 | F1(macro)=0.3678 | Acc=0.3742


Confusion matrix:
 [[ 5  7  6 23]
 [ 3 10  7 11]
 [ 3  5  6 16]
 [ 1  1  4  8]]
Train  loss=1.5797 acc=0.3742 f1=0.3678 | Val loss=2.3872 acc=0.2500 f1=0.2519

Epoch 3/12


    t_loss=1.3847 | F1(macro)=0.3775 | Acc=0.3935


Confusion matrix:
 [[ 8  5 10 18]
 [ 8  6  9  8]
 [ 4  2 12 12]
 [ 2  4  1  7]]
Train  loss=1.3847 acc=0.3935 f1=0.3775 | Val loss=2.1828 acc=0.2845 f1=0.2821
  🔥 New best F1: 0.2821 – model saved.

Epoch 4/12


    t_loss=1.3236 | F1(macro)=0.4300 | Acc=0.4366


Confusion matrix:
 [[ 5  9 18  9]
 [ 6 12  8  5]
 [ 1  7 14  8]
 [ 2  3  5  4]]
Train  loss=1.3236 acc=0.4366 f1=0.4300 | Val loss=2.0316 acc=0.3017 f1=0.2856
  🔥 New best F1: 0.2856 – model saved.

Epoch 5/12


    t_loss=1.1641 | F1(macro)=0.5275 | Acc=0.5376


Confusion matrix:
 [[ 9  7 12 13]
 [11  3 13  4]
 [ 6  3 12  9]
 [ 3  3  2  6]]
Train  loss=1.1641 acc=0.5376 f1=0.5275 | Val loss=2.2108 acc=0.2586 f1=0.2484

Epoch 6/12


    t_loss=1.0921 | F1(macro)=0.5186 | Acc=0.5355


Confusion matrix:
 [[ 3  7 18 13]
 [ 8  9  9  5]
 [ 4  3  9 14]
 [ 1  0  3 10]]
Train  loss=1.0921 acc=0.5355 f1=0.5186 | Val loss=2.1455 acc=0.2672 f1=0.2708

Epoch 7/12


    t_loss=1.0594 | F1(macro)=0.5108 | Acc=0.5376


Confusion matrix:
 [[11  9  6 15]
 [ 8 10  7  6]
 [ 5  4  8 13]
 [ 0  5  5  4]]
Train  loss=1.0594 acc=0.5376 f1=0.5108 | Val loss=1.9797 acc=0.2845 f1=0.2793

Epoch 8/12


    t_loss=1.0198 | F1(macro)=0.5845 | Acc=0.5892


Confusion matrix:
 [[ 6  7 15 13]
 [ 9  7 12  3]
 [ 5  7  6 12]
 [ 2  1  4  7]]
Train  loss=1.0198 acc=0.5892 f1=0.5845 | Val loss=2.1597 acc=0.2241 f1=0.2299

Epoch 9/12


    t_loss=0.9890 | F1(macro)=0.5620 | Acc=0.5742


Confusion matrix:
 [[ 4 11 10 16]
 [ 9  9  8  5]
 [ 6  5  5 14]
 [ 2  2  1  9]]
Train  loss=0.9890 acc=0.5742 f1=0.5620 | Val loss=2.1402 acc=0.2328 f1=0.2337

Epoch 10/12


    t_loss=1.0042 | F1(macro)=0.5873 | Acc=0.6000


Confusion matrix:
 [[ 3  6 15 17]
 [ 4 10 10  7]
 [ 4  5 11 10]
 [ 1  2  3  8]]
Train  loss=1.0042 acc=0.6000 f1=0.5873 | Val loss=2.0891 acc=0.2759 f1=0.2720

Epoch 11/12


    t_loss=1.0497 | F1(macro)=0.5535 | Acc=0.5763


Confusion matrix:
 [[ 7  9 12 13]
 [10  8  7  6]
 [ 7  3  6 14]
 [ 2  2  5  5]]
Train  loss=1.0497 acc=0.5763 f1=0.5535 | Val loss=2.0295 acc=0.2241 f1=0.2258

Epoch 12/12


    t_loss=1.0425 | F1(macro)=0.5328 | Acc=0.5441


Confusion matrix:
 [[ 8  5 11 17]
 [ 7 10  8  6]
 [ 2  3  8 17]
 [ 0  0  5  9]]
Train  loss=1.0425 acc=0.5441 f1=0.5328 | Val loss=1.9708 acc=0.3017 f1=0.3070
  🔥 New best F1: 0.3070 – model saved.

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.1131 | F1(macro)=0.3086 | Acc=0.3118


Confusion matrix:
 [[10 13  6 12]
 [ 9  8  9  6]
 [ 3  9 10  8]
 [ 4  1  5  3]]
Train  loss=2.1131 acc=0.3118 f1=0.3086 | Val loss=2.4540 acc=0.2672 f1=0.2572
  🔥 New best F1: 0.2572 – model saved.

Epoch 2/8


    t_loss=1.8761 | F1(macro)=0.3370 | Acc=0.3376


Confusion matrix:
 [[12  7 15  7]
 [10  3 12  7]
 [ 3  7 11  9]
 [ 3  2  7  1]]
Train  loss=1.8761 acc=0.3376 f1=0.3370 | Val loss=2.2848 acc=0.2328 f1=0.2032

Epoch 3/8


    t_loss=1.8245 | F1(macro)=0.3061 | Acc=0.3075


Confusion matrix:
 [[11 10  9 11]
 [ 7  4 11 10]
 [ 4  2  8 16]
 [ 6  1  2  4]]
Train  loss=1.8245 acc=0.3075 f1=0.3061 | Val loss=2.2285 acc=0.2328 f1=0.2242

Epoch 4/8


    t_loss=1.8071 | F1(macro)=0.3174 | Acc=0.3183


Confusion matrix:
 [[ 9 10 11 11]
 [ 5  8  9 10]
 [ 1 11  6 12]
 [ 3  3  4  3]]
Train  loss=1.8071 acc=0.3183 f1=0.3174 | Val loss=2.5445 acc=0.2241 f1=0.2194

Epoch 5/8


    t_loss=1.7467 | F1(macro)=0.3560 | Acc=0.3570


Confusion matrix:
 [[16  8  8  9]
 [10 10  5  7]
 [10  4  7  9]
 [ 3  4  3  3]]
Train  loss=1.7467 acc=0.3570 f1=0.3560 | Val loss=2.2482 acc=0.3103 f1=0.2888
  🔥 New best F1: 0.2888 – model saved.

Epoch 6/8


    t_loss=1.7119 | F1(macro)=0.3003 | Acc=0.3011


Confusion matrix:
 [[11  7 11 12]
 [13  7  6  6]
 [ 8  3  5 14]
 [ 5  0  4  4]]
Train  loss=1.7119 acc=0.3011 f1=0.3003 | Val loss=2.3421 acc=0.2328 f1=0.2274

Epoch 7/8


    t_loss=1.7040 | F1(macro)=0.3111 | Acc=0.3161


Confusion matrix:
 [[12 12  8  9]
 [ 8 11  7  6]
 [ 6  8  4 12]
 [ 5  1  2  5]]
Train  loss=1.7040 acc=0.3161 f1=0.3111 | Val loss=2.3909 acc=0.2759 f1=0.2640

Epoch 8/8


    t_loss=1.7334 | F1(macro)=0.3045 | Acc=0.3054


Confusion matrix:
 [[12 13  5 11]
 [ 6 12  3 11]
 [ 4 10  5 11]
 [ 3  4  2  4]]
Train  loss=1.7334 acc=0.3054 f1=0.3045 | Val loss=2.2601 acc=0.2845 f1=0.2710
Restored best Stage 1 weights for fold 4 (F1=0.2888)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/12


    t_loss=1.6343 | F1(macro)=0.3243 | Acc=0.3398


Confusion matrix:
 [[ 8 11  5 17]
 [ 8  5  8 11]
 [ 2 13  8  7]
 [ 3  3  3  4]]
Train  loss=1.6343 acc=0.3398 f1=0.3243 | Val loss=2.2195 acc=0.2155 f1=0.2161
  🔥 New best F1: 0.2161 – model saved.

Epoch 2/12


    t_loss=1.3984 | F1(macro)=0.4092 | Acc=0.4258


Confusion matrix:
 [[ 9 11  5 16]
 [ 6 13  3 10]
 [ 0 12  2 16]
 [ 2  3  0  8]]
Train  loss=1.3984 acc=0.4258 f1=0.4092 | Val loss=2.3226 acc=0.2759 f1=0.2576
  🔥 New best F1: 0.2576 – model saved.

Epoch 3/12


    t_loss=1.3838 | F1(macro)=0.4048 | Acc=0.4237


Confusion matrix:
 [[ 7  8 12 14]
 [ 9  5  7 11]
 [ 6  4  7 13]
 [ 3  1  4  5]]
Train  loss=1.3838 acc=0.4237 f1=0.4048 | Val loss=2.2781 acc=0.2069 f1=0.2060

Epoch 4/12


    t_loss=1.1954 | F1(macro)=0.4847 | Acc=0.4989


Confusion matrix:
 [[ 5 10  9 17]
 [ 7  7  9  9]
 [ 3  4  9 14]
 [ 2  2  4  5]]
Train  loss=1.1954 acc=0.4989 f1=0.4847 | Val loss=2.3501 acc=0.2241 f1=0.2236

Epoch 5/12


    t_loss=1.2474 | F1(macro)=0.4604 | Acc=0.4774


Confusion matrix:
 [[ 8 18  5 10]
 [ 4 17  4  7]
 [ 3 12  7  8]
 [ 0  7  0  6]]
Train  loss=1.2474 acc=0.4774 f1=0.4604 | Val loss=1.9302 acc=0.3276 f1=0.3145
  🔥 New best F1: 0.3145 – model saved.

Epoch 6/12


    t_loss=1.1217 | F1(macro)=0.5599 | Acc=0.5699


Confusion matrix:
 [[10 12  8 11]
 [ 7 10  5 10]
 [ 6  2 12 10]
 [ 3  1  3  6]]
Train  loss=1.1217 acc=0.5699 f1=0.5599 | Val loss=2.0228 acc=0.3276 f1=0.3258
  🔥 New best F1: 0.3258 – model saved.

Epoch 7/12


    t_loss=1.0923 | F1(macro)=0.5280 | Acc=0.5462


Confusion matrix:
 [[ 9 11  9 12]
 [10 11  0 11]
 [ 6  6  9  9]
 [ 2  2  4  5]]
Train  loss=1.0923 acc=0.5462 f1=0.5280 | Val loss=2.0527 acc=0.2931 f1=0.2914

Epoch 8/12


    t_loss=1.0894 | F1(macro)=0.5717 | Acc=0.5849


Confusion matrix:
 [[ 4 14  5 18]
 [10 11  3  8]
 [ 6  2  7 15]
 [ 5  1  0  7]]
Train  loss=1.0894 acc=0.5849 f1=0.5717 | Val loss=2.0635 acc=0.2500 f1=0.2571

Epoch 9/12


    t_loss=1.1016 | F1(macro)=0.5244 | Acc=0.5419


Confusion matrix:
 [[ 7 15  9 10]
 [ 7 16  5  4]
 [ 6  6  8 10]
 [ 2  1  3  7]]
Train  loss=1.1016 acc=0.5419 f1=0.5244 | Val loss=2.0121 acc=0.3276 f1=0.3221

Epoch 10/12


    t_loss=1.0144 | F1(macro)=0.5595 | Acc=0.5742


Confusion matrix:
 [[ 8 21  7  5]
 [ 5 16  7  4]
 [ 6 13  5  6]
 [ 5  3  2  3]]
Train  loss=1.0144 acc=0.5742 f1=0.5595 | Val loss=2.1204 acc=0.2759 f1=0.2531

Epoch 11/12


    t_loss=0.9532 | F1(macro)=0.6348 | Acc=0.6430


Confusion matrix:
 [[ 7 11 13 10]
 [12  8  6  6]
 [11  6  7  6]
 [ 2  3  4  4]]
Train  loss=0.9532 acc=0.6430 f1=0.6348 | Val loss=2.0906 acc=0.2241 f1=0.2242

Epoch 12/12


    t_loss=1.0111 | F1(macro)=0.5516 | Acc=0.5699


Confusion matrix:
 [[12 11 10  8]
 [ 5  6 15  6]
 [ 2  6 11 11]
 [ 3  1  2  7]]
Train  loss=1.0111 acc=0.5699 f1=0.5516 | Val loss=1.9491 acc=0.3103 f1=0.3075


# tf_efficientnetv2_s.in21k

In [5]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES
    ).to(device)
    old_conv: Conv2dSame = model.conv_stem
    # Create new Conv2dSame with 4 input channels
    new_conv = Conv2dSame(
        in_channels=4,
        out_channels=old_conv.out_channels,
        kernel_size=old_conv.kernel_size,
        stride=old_conv.stride,
        padding=old_conv.padding,
        dilation=old_conv.dilation,
        groups=old_conv.groups,
        bias=(old_conv.bias is not None)
    )
    # Copy pretrained weights for the first 3 channels, init 4th as their mean
    with torch.no_grad():
        # old_conv.weight shape: [out_chs, 3, kH, kW]
        new_conv.weight[:, :3, :, :] = old_conv.weight
        new_conv.weight[:, 3:, :, :] = old_conv.weight.mean(dim=1, keepdim=True)

        if old_conv.bias is not None:
            new_conv.bias[:] = old_conv.bias
    # Replace in the model
    model.conv_stem = new_conv
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,   # True because we need labels
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [6]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,   # True because we need labels
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

In [11]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0"

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png          HER2(+)
1  img_0001.png        Luminal B
2  img_0002.png        Luminal B
3  img_0003.png  Triple negative
4  img_0004.png        Luminal A


In [13]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
                         shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")
    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            img_tensor = img_tensor.squeeze(0)  # [3,H,W]
            img_tensor = img_tensor.to(device)

            # -------- TTA: apply multiple augmented views --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1,4]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N, 4]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
pred_indices = mean_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print("Saved submission_5fold_tta.csv")

Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_tta.csv


In [15]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=True,   # True because we need labels
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.30972955872396396
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.249258981184447
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.2821720844585383
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.25631439505445985
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.3117559523809524
Mean OOF F1: 0.2818461943604723
