In [1]:
import enum
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.CONVNEXT_TINY

# tf_efficientnetv2_s.in21k

In [3]:
if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(train_df_split, transforms=train_transforms, is_train=True, image_size=IMAGE_SIZE)
        val_dataset   = HistologyDataset(val_df_split,   transforms=val_test_transforms, is_train=True, image_size=IMAGE_SIZE)

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE,
                                  shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

        # --- create fresh model for this fold ---
        model = timm.create_model(
            PRETRAINED_MODEL,
            pretrained=True,
            num_classes=N_CLASSES
        ).to(device)

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [4]:
if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            train_df_split,
            transforms=train_transforms,
            is_train=True,
            image_size=IMAGE_SIZE
        )
        val_dataset = HistologyDataset(
            val_df_split,
            transforms=val_test_transforms,
            is_train=True,
            image_size=IMAGE_SIZE
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = timm.create_model(
            PRETRAINED_MODEL,
            pretrained=True,
            num_classes=N_CLASSES
        ).to(device)

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = model.state_dict().copy()
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---

Epoch 1/8


    t_loss=1.4178 | F1(macro)=0.3221 | Acc=0.3276


Confusion matrix:
 [[23  7  3  8]
 [12  7  3 10]
 [14  1  2 13]
 [ 8  2  0  4]]
Train  loss=1.4178 acc=0.3276 f1=0.3221 | Val loss=1.5004 acc=0.3077 f1=0.2559
  🔥 New best F1: 0.2559 – model saved.

Epoch 2/8


    t_loss=1.3144 | F1(macro)=0.3676 | Acc=0.3707


Confusion matrix:
 [[19 13  0  9]
 [14 10  0  8]
 [14  8  0  8]
 [ 8  3  0  3]]
Train  loss=1.3144 acc=0.3707 f1=0.3676 | Val loss=1.5715 acc=0.2735 f1=0.2104

Epoch 3/8


    t_loss=1.2830 | F1(macro)=0.3865 | Acc=0.3987


Confusion matrix:
 [[14 17  2  8]
 [ 5 19  1  7]
 [10 11  1  8]
 [ 4  5  0  5]]
Train  loss=1.2830 acc=0.3987 f1=0.3865 | Val loss=1.5084 acc=0.3333 f1=0.2819
  🔥 New best F1: 0.2819 – model saved.

Epoch 4/8


    t_loss=1.1959 | F1(macro)=0.4669 | Acc=0.4720


Confusion matrix:
 [[ 6 10 21  4]
 [ 5 15 10  2]
 [ 4  3 21  2]
 [ 3  4  5  2]]
Train  loss=1.1959 acc=0.4720 f1=0.4669 | Val loss=1.4279 acc=0.3761 f1=0.3304
  🔥 New best F1: 0.3304 – model saved.

Epoch 5/8


    t_loss=1.2104 | F1(macro)=0.4643 | Acc=0.4741


Confusion matrix:
 [[ 8 13 14  6]
 [ 1 15  8  8]
 [ 5  3 16  6]
 [ 1  3  7  3]]
Train  loss=1.2104 acc=0.4741 f1=0.4643 | Val loss=1.4662 acc=0.3590 f1=0.3323
  🔥 New best F1: 0.3323 – model saved.

Epoch 6/8


    t_loss=1.1470 | F1(macro)=0.4941 | Acc=0.5022


Confusion matrix:
 [[14  2 10 15]
 [12  3 10  7]
 [10  0 10 10]
 [ 4  2  1  7]]
Train  loss=1.1470 acc=0.5022 f1=0.4941 | Val loss=1.4741 acc=0.2906 f1=0.2729

Epoch 7/8


    t_loss=1.1890 | F1(macro)=0.4680 | Acc=0.4698


Confusion matrix:
 [[26  5  6  4]
 [17  9  6  0]
 [23  1  3  3]
 [ 9  2  1  2]]
Train  loss=1.1890 acc=0.4698 f1=0.4680 | Val loss=1.3903 acc=0.3419 f1=0.2800

Epoch 8/8


    t_loss=1.1614 | F1(macro)=0.5049 | Acc=0.5000


Confusion matrix:
 [[18  8  6  9]
 [ 8 12  8  4]
 [15  2  9  4]
 [ 6  2  2  4]]
Train  loss=1.1614 acc=0.5000 f1=0.5049 | Val loss=1.3919 acc=0.3675 f1=0.3484
  🔥 New best F1: 0.3484 – model saved.
Restored best Stage 1 weights for fold 0 (F1=0.3484)

--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---

Epoch 1/12


    t_loss=1.5091 | F1(macro)=0.2073 | Acc=0.2220


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.5091 acc=0.2220 f1=0.2073 | Val loss=1.5456 acc=0.1197 f1=0.0534
  🔥 New best F1: 0.0534 – model saved.

Epoch 2/12


    t_loss=1.3566 | F1(macro)=0.1669 | Acc=0.2565


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3566 acc=0.2565 f1=0.1669 | Val loss=1.4810 acc=0.1197 f1=0.0534

Epoch 3/12


    t_loss=1.3683 | F1(macro)=0.2083 | Acc=0.2780


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3683 acc=0.2780 f1=0.2083 | Val loss=1.4665 acc=0.1197 f1=0.0534

Epoch 4/12


    t_loss=1.3281 | F1(macro)=0.1118 | Acc=0.2737


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3281 acc=0.2737 f1=0.1118 | Val loss=1.5108 acc=0.1197 f1=0.0534

Epoch 5/12


    t_loss=1.3808 | F1(macro)=0.0915 | Acc=0.2241


Confusion matrix:
 [[ 0  0 30 11]
 [ 0  0 20 12]
 [ 0  0 20 10]
 [ 0  0  9  5]]
Train  loss=1.3808 acc=0.2241 f1=0.0915 | Val loss=1.4612 acc=0.2137 f1=0.1398
  🔥 New best F1: 0.1398 – model saved.

Epoch 6/12


    t_loss=1.3426 | F1(macro)=0.1409 | Acc=0.2500


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3426 acc=0.2500 f1=0.1409 | Val loss=1.4558 acc=0.1197 f1=0.0534

Epoch 7/12


    t_loss=1.3800 | F1(macro)=0.1102 | Acc=0.2091


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3800 acc=0.2091 f1=0.1102 | Val loss=1.4406 acc=0.1197 f1=0.0534

Epoch 8/12


    t_loss=1.2887 | F1(macro)=0.1791 | Acc=0.2716


Confusion matrix:
 [[ 0 20  0 21]
 [ 0 16  0 16]
 [ 0  9  0 21]
 [ 0  3  0 11]]
Train  loss=1.2887 acc=0.2716 f1=0.1791 | Val loss=1.4678 acc=0.2308 f1=0.1663
  🔥 New best F1: 0.1663 – model saved.

Epoch 9/12


    t_loss=1.2794 | F1(macro)=0.2812 | Acc=0.3233


Confusion matrix:
 [[16 14  3  8]
 [ 8 12  3  9]
 [14  9  1  6]
 [ 1  4  0  9]]
Train  loss=1.2794 acc=0.3233 f1=0.2812 | Val loss=1.4307 acc=0.3248 f1=0.2958
  🔥 New best F1: 0.2958 – model saved.

Epoch 10/12


    t_loss=1.2093 | F1(macro)=0.2989 | Acc=0.3728


Confusion matrix:
 [[ 0 14 15 12]
 [ 0 17  8  7]
 [ 0  8 11 11]
 [ 0  4  3  7]]
Train  loss=1.2093 acc=0.3728 f1=0.2989 | Val loss=1.4499 acc=0.2991 f1=0.2641

Epoch 11/12


    t_loss=1.1413 | F1(macro)=0.2859 | Acc=0.3879


Confusion matrix:
 [[ 0 28  2 11]
 [ 0 25  3  4]
 [ 0 18  2 10]
 [ 0  7  0  7]]
Train  loss=1.1413 acc=0.3879 f1=0.2859 | Val loss=1.4437 acc=0.2906 f1=0.2168

Epoch 12/12


    t_loss=1.1473 | F1(macro)=0.3189 | Acc=0.4159


Confusion matrix:
 [[ 0 15  6 20]
 [ 0 17  6  9]
 [ 0  6  2 22]
 [ 0  4  0 10]]
Train  loss=1.1473 acc=0.4159 f1=0.3189 | Val loss=1.4656 acc=0.2479 f1=0.2043

========== Fold 1 ==========

--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---

Epoch 1/8


    t_loss=1.4453 | F1(macro)=0.3334 | Acc=0.3312


Confusion matrix:
 [[ 5 10  6 19]
 [ 4 12  2 14]
 [ 2 12  4 12]
 [ 3  1  1  9]]
Train  loss=1.4453 acc=0.3312 f1=0.3334 | Val loss=1.5050 acc=0.2586 f1=0.2485
  🔥 New best F1: 0.2485 – model saved.

Epoch 2/8


    t_loss=1.3241 | F1(macro)=0.3713 | Acc=0.3742


Confusion matrix:
 [[ 9  7  4 20]
 [13  3  6 10]
 [ 7  6  7 10]
 [ 2  1  1 10]]
Train  loss=1.3241 acc=0.3742 f1=0.3713 | Val loss=1.5485 acc=0.2500 f1=0.2450

Epoch 3/8


    t_loss=1.2447 | F1(macro)=0.4176 | Acc=0.4258


Confusion matrix:
 [[15  3 16  6]
 [15  1 11  5]
 [ 7  3 15  5]
 [ 6  0  5  3]]
Train  loss=1.2447 acc=0.4258 f1=0.4176 | Val loss=1.4658 acc=0.2931 f1=0.2460

Epoch 4/8


    t_loss=1.2716 | F1(macro)=0.4233 | Acc=0.4258


Confusion matrix:
 [[15  3  3 19]
 [13  3  4 12]
 [11  4  4 11]
 [ 5  0  2  7]]
Train  loss=1.2716 acc=0.4258 f1=0.4233 | Val loss=1.5800 acc=0.2500 f1=0.2271

Epoch 5/8


    t_loss=1.2253 | F1(macro)=0.4490 | Acc=0.4473


Confusion matrix:
 [[24  5  2  9]
 [16  7  3  6]
 [17  6  4  3]
 [ 9  0  1  4]]
Train  loss=1.2253 acc=0.4473 f1=0.4490 | Val loss=1.4247 acc=0.3362 f1=0.2888
  🔥 New best F1: 0.2888 – model saved.

Epoch 6/8


    t_loss=1.2022 | F1(macro)=0.4654 | Acc=0.4624


Confusion matrix:
 [[10 11  1 18]
 [11  5  4 12]
 [10  8  3  9]
 [ 5  1  1  7]]
Train  loss=1.2022 acc=0.4624 f1=0.4654 | Val loss=1.5094 acc=0.2155 f1=0.2064

Epoch 7/8


    t_loss=1.1023 | F1(macro)=0.5352 | Acc=0.5312


Confusion matrix:
 [[ 4  8 15 13]
 [ 3  8 12  9]
 [ 2  7 20  1]
 [ 2  0  6  6]]
Train  loss=1.1023 acc=0.5312 f1=0.5352 | Val loss=1.5171 acc=0.3276 f1=0.3022
  🔥 New best F1: 0.3022 – model saved.

Epoch 8/8


    t_loss=1.0985 | F1(macro)=0.4919 | Acc=0.5097


Confusion matrix:
 [[ 7  7  7 19]
 [ 9  5  7 11]
 [ 3  9  7 11]
 [ 2  0  4  8]]
Train  loss=1.0985 acc=0.5097 f1=0.4919 | Val loss=1.5000 acc=0.2328 f1=0.2317
Restored best Stage 1 weights for fold 1 (F1=0.3022)

--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---

Epoch 1/12


    t_loss=1.5090 | F1(macro)=0.1890 | Acc=0.2301


Confusion matrix:
 [[ 0  0  0 40]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.5090 acc=0.2301 f1=0.1890 | Val loss=1.5904 acc=0.1207 f1=0.0538
  🔥 New best F1: 0.0538 – model saved.

Epoch 2/12


    t_loss=1.3811 | F1(macro)=0.2228 | Acc=0.2839


Confusion matrix:
 [[ 0  0  0 40]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3811 acc=0.2839 f1=0.2228 | Val loss=1.4971 acc=0.1207 f1=0.0538

Epoch 3/12


    t_loss=1.3314 | F1(macro)=0.1636 | Acc=0.2796


Confusion matrix:
 [[11  3  0 26]
 [11  0  0 21]
 [10  1  0 19]
 [ 2  0  0 12]]
Train  loss=1.3314 acc=0.2796 f1=0.1636 | Val loss=1.4156 acc=0.1983 f1=0.1395
  🔥 New best F1: 0.1395 – model saved.

Epoch 4/12


    t_loss=1.3201 | F1(macro)=0.2534 | Acc=0.3075


Confusion matrix:
 [[ 0  1  0 39]
 [ 0  4  0 28]
 [ 0  3  0 27]
 [ 0  2  0 12]]
Train  loss=1.3201 acc=0.3075 f1=0.2534 | Val loss=1.6599 acc=0.1379 f1=0.0976

Epoch 5/12


    t_loss=1.2637 | F1(macro)=0.2572 | Acc=0.3376


Confusion matrix:
 [[ 7 12 14  7]
 [12 16  2  2]
 [ 8 14  5  3]
 [ 4  4  2  4]]
Train  loss=1.2637 acc=0.3376 f1=0.2572 | Val loss=1.3916 acc=0.2759 f1=0.2657
  🔥 New best F1: 0.2657 – model saved.

Epoch 6/12


    t_loss=1.2675 | F1(macro)=0.3493 | Acc=0.3871


Confusion matrix:
 [[ 0 36  2  2]
 [ 0 31  0  1]
 [ 0 28  0  2]
 [ 0  8  1  5]]
Train  loss=1.2675 acc=0.3871 f1=0.3493 | Val loss=1.4245 acc=0.3103 f1=0.2190

Epoch 7/12


    t_loss=1.2384 | F1(macro)=0.3800 | Acc=0.4194


Confusion matrix:
 [[10  6 18  6]
 [14  9  6  3]
 [15  5  8  2]
 [ 3  0  5  6]]
Train  loss=1.2384 acc=0.4194 f1=0.3800 | Val loss=1.3768 acc=0.2845 f1=0.3040
  🔥 New best F1: 0.3040 – model saved.

Epoch 8/12


    t_loss=1.0906 | F1(macro)=0.4194 | Acc=0.4581


Confusion matrix:
 [[ 4  6 16 14]
 [ 7 10  7  8]
 [ 9  6  8  7]
 [ 1  1  5  7]]
Train  loss=1.0906 acc=0.4581 f1=0.4194 | Val loss=1.4535 acc=0.2500 f1=0.2543

Epoch 9/12


    t_loss=1.0804 | F1(macro)=0.4936 | Acc=0.5247


Confusion matrix:
 [[ 1 14  9 16]
 [ 5 18  1  8]
 [ 3 14  5  8]
 [ 1  4  1  8]]
Train  loss=1.0804 acc=0.5247 f1=0.4936 | Val loss=1.4861 acc=0.2759 f1=0.2482

Epoch 10/12


    t_loss=1.0412 | F1(macro)=0.5177 | Acc=0.5355


Confusion matrix:
 [[11  4 16  9]
 [10 10 11  1]
 [16  5  8  1]
 [ 3  0  7  4]]
Train  loss=1.0412 acc=0.5355 f1=0.5177 | Val loss=1.4687 acc=0.2845 f1=0.2913

Epoch 11/12


    t_loss=0.9444 | F1(macro)=0.5922 | Acc=0.6108


Confusion matrix:
 [[ 6  5 16 13]
 [ 9 10  4  9]
 [11  4  6  9]
 [ 1  1  5  7]]
Train  loss=0.9444 acc=0.6108 f1=0.5922 | Val loss=1.4887 acc=0.2500 f1=0.2574

Epoch 12/12


    t_loss=0.8488 | F1(macro)=0.6467 | Acc=0.6688


Confusion matrix:
 [[ 4  6 14 16]
 [ 7 10  4 11]
 [ 9  4  8  9]
 [ 1  1  6  6]]
Train  loss=0.8488 acc=0.6688 f1=0.6467 | Val loss=1.5517 acc=0.2414 f1=0.2452

========== Fold 2 ==========

--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---

Epoch 1/8


    t_loss=1.3506 | F1(macro)=0.3855 | Acc=0.3978


Confusion matrix:
 [[12  4 13 12]
 [ 7  7 12  5]
 [ 4  5 16  5]
 [ 4  2  4  4]]
Train  loss=1.3506 acc=0.3978 f1=0.3855 | Val loss=1.4347 acc=0.3362 f1=0.3163
  🔥 New best F1: 0.3163 – model saved.

Epoch 2/8


    t_loss=1.3626 | F1(macro)=0.3670 | Acc=0.3699


Confusion matrix:
 [[30  2  3  6]
 [21  2  2  6]
 [21  2  0  7]
 [ 7  1  1  5]]
Train  loss=1.3626 acc=0.3699 f1=0.3670 | Val loss=1.4638 acc=0.3190 f1=0.2171

Epoch 3/8


    t_loss=1.3000 | F1(macro)=0.4185 | Acc=0.4194


Confusion matrix:
 [[32  2  5  2]
 [25  4  2  0]
 [21  5  4  0]
 [11  1  1  1]]
Train  loss=1.3000 acc=0.4194 f1=0.4185 | Val loss=1.4334 acc=0.3534 f1=0.2466

Epoch 4/8


    t_loss=1.2435 | F1(macro)=0.4355 | Acc=0.4366


Confusion matrix:
 [[20 11  4  6]
 [12 13  2  4]
 [15  6  1  8]
 [ 6  4  0  4]]
Train  loss=1.2435 acc=0.4366 f1=0.4355 | Val loss=1.4431 acc=0.3276 f1=0.2755

Epoch 5/8


    t_loss=1.1573 | F1(macro)=0.5094 | Acc=0.5161


Confusion matrix:
 [[22  1 12  6]
 [17  4  4  6]
 [12  2 11  5]
 [ 8  0  3  3]]
Train  loss=1.1573 acc=0.5161 f1=0.5094 | Val loss=1.3754 acc=0.3448 f1=0.2984

Epoch 6/8


    t_loss=1.1590 | F1(macro)=0.4782 | Acc=0.4925


Confusion matrix:
 [[27  5  1  8]
 [15  8  0  8]
 [16  7  2  5]
 [ 8  1  1  4]]
Train  loss=1.1590 acc=0.4925 f1=0.4782 | Val loss=1.4284 acc=0.3534 f1=0.2838

Epoch 7/8


    t_loss=1.1656 | F1(macro)=0.4957 | Acc=0.4946


Confusion matrix:
 [[22  5 10  4]
 [ 8 10 10  3]
 [11  5 11  3]
 [ 7  2  3  2]]
Train  loss=1.1656 acc=0.4946 f1=0.4957 | Val loss=1.3096 acc=0.3879 f1=0.3423
  🔥 New best F1: 0.3423 – model saved.

Epoch 8/8


    t_loss=1.1375 | F1(macro)=0.5279 | Acc=0.5333


Confusion matrix:
 [[19  4  9  9]
 [ 5 13  8  5]
 [12  5  8  5]
 [ 5  1  3  5]]
Train  loss=1.1375 acc=0.5333 f1=0.5279 | Val loss=1.3687 acc=0.3879 f1=0.3710
  🔥 New best F1: 0.3710 – model saved.
Restored best Stage 1 weights for fold 2 (F1=0.3710)

--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---

Epoch 1/12


    t_loss=1.4804 | F1(macro)=0.2097 | Acc=0.2581


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.4804 acc=0.2581 f1=0.2097 | Val loss=1.4920 acc=0.1207 f1=0.0538
  🔥 New best F1: 0.0538 – model saved.

Epoch 2/12


    t_loss=1.3685 | F1(macro)=0.1424 | Acc=0.2602


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3685 acc=0.2602 f1=0.1424 | Val loss=1.5107 acc=0.1207 f1=0.0538

Epoch 3/12


    t_loss=1.3139 | F1(macro)=0.1339 | Acc=0.2710


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3139 acc=0.2710 f1=0.1339 | Val loss=1.5548 acc=0.1207 f1=0.0538

Epoch 4/12


    t_loss=1.3660 | F1(macro)=0.1761 | Acc=0.2839


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3660 acc=0.2839 f1=0.1761 | Val loss=1.5241 acc=0.1207 f1=0.0538

Epoch 5/12


    t_loss=1.3502 | F1(macro)=0.0997 | Acc=0.2473


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3502 acc=0.2473 f1=0.0997 | Val loss=1.4643 acc=0.1207 f1=0.0538

Epoch 6/12


    t_loss=1.3296 | F1(macro)=0.1745 | Acc=0.2731


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3296 acc=0.2731 f1=0.1745 | Val loss=1.5046 acc=0.1207 f1=0.0538

Epoch 7/12


    t_loss=1.3366 | F1(macro)=0.1353 | Acc=0.2301


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3366 acc=0.2301 f1=0.1353 | Val loss=1.5147 acc=0.1207 f1=0.0538

Epoch 8/12


    t_loss=1.2162 | F1(macro)=0.1691 | Acc=0.3204


Confusion matrix:
 [[ 0  0  1 40]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  1 13]]
Train  loss=1.2162 acc=0.3204 f1=0.1691 | Val loss=1.4851 acc=0.1121 f1=0.0508

Epoch 9/12


    t_loss=1.2837 | F1(macro)=0.2196 | Acc=0.2925


Confusion matrix:
 [[ 0 18 20  3]
 [ 0 15 15  1]
 [ 0 11 18  1]
 [ 0  1 10  3]]
Train  loss=1.2837 acc=0.2925 f1=0.2196 | Val loss=1.4067 acc=0.3103 f1=0.2636
  🔥 New best F1: 0.2636 – model saved.

Epoch 10/12


    t_loss=1.1616 | F1(macro)=0.3226 | Acc=0.3957


Confusion matrix:
 [[ 4 20  5 12]
 [ 0 21  1  9]
 [ 2 17  4  7]
 [ 1  3  2  8]]
Train  loss=1.1616 acc=0.3957 f1=0.3226 | Val loss=1.4011 acc=0.3190 f1=0.2834
  🔥 New best F1: 0.2834 – model saved.

Epoch 11/12


    t_loss=1.2163 | F1(macro)=0.3387 | Acc=0.3957


Confusion matrix:
 [[ 0 18  8 15]
 [ 0 12  6 13]
 [ 0  9  7 14]
 [ 0  2  1 11]]
Train  loss=1.2163 acc=0.3957 f1=0.3387 | Val loss=1.4296 acc=0.2586 f1=0.2327

Epoch 12/12


    t_loss=1.0962 | F1(macro)=0.3462 | Acc=0.4473


Confusion matrix:
 [[ 0 11  5 25]
 [ 0 10  6 15]
 [ 0  8  4 18]
 [ 0  3  2  9]]
Train  loss=1.0962 acc=0.4473 f1=0.3462 | Val loss=1.4870 acc=0.1983 f1=0.1775

========== Fold 3 ==========

--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---

Epoch 1/8


    t_loss=1.4567 | F1(macro)=0.2892 | Acc=0.2989


Confusion matrix:
 [[12 24  0  5]
 [11 19  0  1]
 [14 12  0  4]
 [ 7  4  0  3]]
Train  loss=1.4567 acc=0.2989 f1=0.2892 | Val loss=1.3934 acc=0.2931 f1=0.2317
  🔥 New best F1: 0.2317 – model saved.

Epoch 2/8


    t_loss=1.3769 | F1(macro)=0.3467 | Acc=0.3527


Confusion matrix:
 [[ 0 32  8  1]
 [ 0 29  2  0]
 [ 0 18  8  4]
 [ 0  6  5  3]]
Train  loss=1.3769 acc=0.3527 f1=0.3467 | Val loss=1.5885 acc=0.3448 f1=0.2687
  🔥 New best F1: 0.2687 – model saved.

Epoch 3/8


    t_loss=1.3155 | F1(macro)=0.4022 | Acc=0.4000


Confusion matrix:
 [[11 18  6  6]
 [ 8 15  5  3]
 [ 4  7 10  9]
 [ 0  4  3  7]]
Train  loss=1.3155 acc=0.4000 f1=0.4022 | Val loss=1.3566 acc=0.3707 f1=0.3683
  🔥 New best F1: 0.3683 – model saved.

Epoch 4/8


    t_loss=1.2306 | F1(macro)=0.4744 | Acc=0.4710


Confusion matrix:
 [[15  1  8 17]
 [11  6  3 11]
 [ 3  1 10 16]
 [ 1  0  2 11]]
Train  loss=1.2306 acc=0.4710 f1=0.4744 | Val loss=1.4887 acc=0.3621 f1=0.3566

Epoch 5/8


    t_loss=1.2332 | F1(macro)=0.4069 | Acc=0.4452


Confusion matrix:
 [[ 9  8 17  7]
 [ 6 12  9  4]
 [ 0  6 20  4]
 [ 3  0  5  6]]
Train  loss=1.2332 acc=0.4452 f1=0.4069 | Val loss=1.3136 acc=0.4052 f1=0.3907
  🔥 New best F1: 0.3907 – model saved.

Epoch 6/8


    t_loss=1.1566 | F1(macro)=0.5166 | Acc=0.5183


Confusion matrix:
 [[22  5  5  9]
 [15  9  1  6]
 [13  1  7  9]
 [ 3  0  2  9]]
Train  loss=1.1566 acc=0.5183 f1=0.5166 | Val loss=1.3422 acc=0.4052 f1=0.3884

Epoch 7/8


    t_loss=1.1758 | F1(macro)=0.4491 | Acc=0.4667


Confusion matrix:
 [[13  8 12  8]
 [ 9 13  6  3]
 [ 4  5 17  4]
 [ 2  0  6  6]]
Train  loss=1.1758 acc=0.4667 f1=0.4491 | Val loss=1.2933 acc=0.4224 f1=0.4137
  🔥 New best F1: 0.4137 – model saved.

Epoch 8/8


    t_loss=1.1488 | F1(macro)=0.5002 | Acc=0.5032


Confusion matrix:
 [[15  6 11  9]
 [13  8  5  5]
 [ 9  2  8 11]
 [ 3  0  3  8]]
Train  loss=1.1488 acc=0.5032 f1=0.5002 | Val loss=1.3742 acc=0.3362 f1=0.3330
Restored best Stage 1 weights for fold 3 (F1=0.4137)

--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---

Epoch 1/12


    t_loss=1.5106 | F1(macro)=0.1772 | Acc=0.2602


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.5106 acc=0.2602 f1=0.1772 | Val loss=1.5198 acc=0.1207 f1=0.0538
  🔥 New best F1: 0.0538 – model saved.

Epoch 2/12


    t_loss=1.3918 | F1(macro)=0.1646 | Acc=0.2495


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.3918 acc=0.2495 f1=0.1646 | Val loss=1.4530 acc=0.1207 f1=0.0538

Epoch 3/12


    t_loss=1.3694 | F1(macro)=0.1462 | Acc=0.2344


Confusion matrix:
 [[ 0  0 41  0]
 [ 0  0 31  0]
 [ 0  0 29  1]
 [ 0  0 14  0]]
Train  loss=1.3694 acc=0.2344 f1=0.1462 | Val loss=1.4488 acc=0.2500 f1=0.1000
  🔥 New best F1: 0.1000 – model saved.

Epoch 4/12


    t_loss=1.3057 | F1(macro)=0.1679 | Acc=0.2710


Confusion matrix:
 [[ 8  0  0 33]
 [ 9  0  0 22]
 [ 5  0  0 25]
 [ 0  0  0 14]]
Train  loss=1.3057 acc=0.2710 f1=0.1679 | Val loss=1.4565 acc=0.1897 f1=0.1283
  🔥 New best F1: 0.1283 – model saved.

Epoch 5/12


    t_loss=1.2785 | F1(macro)=0.1843 | Acc=0.2860


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 31]
 [ 0  0  0 30]
 [ 0  0  0 14]]
Train  loss=1.2785 acc=0.2860 f1=0.1843 | Val loss=1.5340 acc=0.1207 f1=0.0538

Epoch 6/12


    t_loss=1.3228 | F1(macro)=0.1936 | Acc=0.2688


Confusion matrix:
 [[ 0  8  1 32]
 [ 0  7  3 21]
 [ 0  2  6 22]
 [ 0  0  1 13]]
Train  loss=1.3228 acc=0.2688 f1=0.1936 | Val loss=1.3757 acc=0.2241 f1=0.2098
  🔥 New best F1: 0.2098 – model saved.

Epoch 7/12


    t_loss=1.2582 | F1(macro)=0.2255 | Acc=0.3269


Confusion matrix:
 [[ 1  7 20 13]
 [ 0  3 25  3]
 [ 2  3 13 12]
 [ 0  0  2 12]]
Train  loss=1.2582 acc=0.3269 f1=0.2255 | Val loss=1.3313 acc=0.2500 f1=0.2288
  🔥 New best F1: 0.2288 – model saved.

Epoch 8/12


    t_loss=1.2478 | F1(macro)=0.3342 | Acc=0.3484


Confusion matrix:
 [[ 2  2 10 27]
 [ 0  2  9 20]
 [ 0  0  2 28]
 [ 1  0  1 12]]
Train  loss=1.2478 acc=0.3484 f1=0.3342 | Val loss=1.4168 acc=0.1552 f1=0.1299

Epoch 9/12


    t_loss=1.2027 | F1(macro)=0.3465 | Acc=0.3720


Confusion matrix:
 [[ 4  5  3 29]
 [ 2  4 11 14]
 [ 1  1  3 25]
 [ 0  0  3 11]]
Train  loss=1.2027 acc=0.3720 f1=0.3465 | Val loss=1.3788 acc=0.1897 f1=0.1796

Epoch 10/12


    t_loss=1.0925 | F1(macro)=0.4216 | Acc=0.4753


Confusion matrix:
 [[ 1  9  5 26]
 [ 2 10  9 10]
 [ 2  4  2 22]
 [ 2  0  2 10]]
Train  loss=1.0925 acc=0.4753 f1=0.4216 | Val loss=1.4161 acc=0.1983 f1=0.1848

Epoch 11/12


    t_loss=1.1049 | F1(macro)=0.4346 | Acc=0.4903


Confusion matrix:
 [[ 0  8 14 19]
 [ 0  4 14 13]
 [ 3  4  9 14]
 [ 1  0  3 10]]
Train  loss=1.1049 acc=0.4903 f1=0.4346 | Val loss=1.4083 acc=0.1983 f1=0.1783

Epoch 12/12


    t_loss=1.0561 | F1(macro)=0.4389 | Acc=0.4946


Confusion matrix:
 [[ 2 14  9 16]
 [ 3 10 11  7]
 [ 3  6 10 11]
 [ 0  1  4  9]]
Train  loss=1.0561 acc=0.4946 f1=0.4389 | Val loss=1.4318 acc=0.2672 f1=0.2581
  🔥 New best F1: 0.2581 – model saved.

========== Fold 4 ==========

--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---

Epoch 1/8


    t_loss=1.4473 | F1(macro)=0.3243 | Acc=0.3376


Confusion matrix:
 [[ 0  7  2 32]
 [ 0  7  1 24]
 [ 1  5  0 24]
 [ 0  3  0 10]]
Train  loss=1.4473 acc=0.3376 f1=0.3243 | Val loss=1.8305 acc=0.1466 f1=0.1134
  🔥 New best F1: 0.1134 – model saved.

Epoch 2/8


    t_loss=1.3453 | F1(macro)=0.3843 | Acc=0.3828


Confusion matrix:
 [[22  5  0 14]
 [14 10  2  6]
 [11  7  1 11]
 [ 5  2  0  6]]
Train  loss=1.3453 acc=0.3828 f1=0.3843 | Val loss=1.5087 acc=0.3362 f1=0.2827
  🔥 New best F1: 0.2827 – model saved.

Epoch 3/8


    t_loss=1.2788 | F1(macro)=0.3974 | Acc=0.4043


Confusion matrix:
 [[ 6 11  1 23]
 [ 5 12  2 13]
 [ 4  8  1 17]
 [ 0  4  0  9]]
Train  loss=1.2788 acc=0.4043 f1=0.3974 | Val loss=1.6911 acc=0.2414 f1=0.2178

Epoch 4/8


    t_loss=1.2733 | F1(macro)=0.3965 | Acc=0.3935


Confusion matrix:
 [[33  4  0  4]
 [24  6  2  0]
 [18  4  2  6]
 [ 6  2  0  5]]
Train  loss=1.2733 acc=0.3935 f1=0.3965 | Val loss=1.4118 acc=0.3966 f1=0.3164
  🔥 New best F1: 0.3164 – model saved.

Epoch 5/8


    t_loss=1.2290 | F1(macro)=0.4570 | Acc=0.4688


Confusion matrix:
 [[10  0 14 17]
 [10  4 12  6]
 [ 7  4  9 10]
 [ 2  2  2  7]]
Train  loss=1.2290 acc=0.4688 f1=0.4570 | Val loss=1.5002 acc=0.2586 f1=0.2522

Epoch 6/8


    t_loss=1.1250 | F1(macro)=0.5194 | Acc=0.5269


Confusion matrix:
 [[10  9  7 15]
 [ 8 11  6  7]
 [ 2 10 10  8]
 [ 2  3  1  7]]
Train  loss=1.1250 acc=0.5269 f1=0.5194 | Val loss=1.4015 acc=0.3276 f1=0.3266
  🔥 New best F1: 0.3266 – model saved.

Epoch 7/8


    t_loss=1.1269 | F1(macro)=0.5388 | Acc=0.5419


Confusion matrix:
 [[13  6  5 17]
 [ 9 12  4  7]
 [ 3  8  9 10]
 [ 1  3  1  8]]
Train  loss=1.1269 acc=0.5419 f1=0.5388 | Val loss=1.4487 acc=0.3621 f1=0.3599
  🔥 New best F1: 0.3599 – model saved.

Epoch 8/8


    t_loss=1.1259 | F1(macro)=0.4975 | Acc=0.5118


Confusion matrix:
 [[14  6  4 17]
 [ 9 13  1  9]
 [ 6  8  4 12]
 [ 2  1  2  8]]
Train  loss=1.1259 acc=0.5118 f1=0.4975 | Val loss=1.4871 acc=0.3362 f1=0.3221
Restored best Stage 1 weights for fold 4 (F1=0.3599)

--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---

Epoch 1/12


    t_loss=1.4736 | F1(macro)=0.2021 | Acc=0.2581


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.4736 acc=0.2581 f1=0.2021 | Val loss=1.4529 acc=0.1121 f1=0.0504
  🔥 New best F1: 0.0504 – model saved.

Epoch 2/12


    t_loss=1.3846 | F1(macro)=0.1696 | Acc=0.2495


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3846 acc=0.2495 f1=0.1696 | Val loss=1.4927 acc=0.1121 f1=0.0504

Epoch 3/12


    t_loss=1.3921 | F1(macro)=0.1830 | Acc=0.2624


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3921 acc=0.2624 f1=0.1830 | Val loss=1.5389 acc=0.1121 f1=0.0504

Epoch 4/12


    t_loss=1.3637 | F1(macro)=0.1290 | Acc=0.2430


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3637 acc=0.2430 f1=0.1290 | Val loss=1.4872 acc=0.1121 f1=0.0504

Epoch 5/12


    t_loss=1.3324 | F1(macro)=0.1086 | Acc=0.2774


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3324 acc=0.2774 f1=0.1086 | Val loss=1.4583 acc=0.1121 f1=0.0504

Epoch 6/12


    t_loss=1.3354 | F1(macro)=0.1012 | Acc=0.2538


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3354 acc=0.2538 f1=0.1012 | Val loss=1.5649 acc=0.1121 f1=0.0504

Epoch 7/12


    t_loss=1.3445 | F1(macro)=0.1012 | Acc=0.2538


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3445 acc=0.2538 f1=0.1012 | Val loss=1.5123 acc=0.1121 f1=0.0504

Epoch 8/12


    t_loss=1.3475 | F1(macro)=0.0984 | Acc=0.2452


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3475 acc=0.2452 f1=0.0984 | Val loss=1.5146 acc=0.1121 f1=0.0504

Epoch 9/12


    t_loss=1.3448 | F1(macro)=0.0965 | Acc=0.2387


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  0  0 32]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3448 acc=0.2387 f1=0.0965 | Val loss=1.5146 acc=0.1121 f1=0.0504

Epoch 10/12


    t_loss=1.3584 | F1(macro)=0.1274 | Acc=0.2387


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  2  0 30]
 [ 0  1  0 29]
 [ 0  0  0 13]]
Train  loss=1.3584 acc=0.2387 f1=0.1274 | Val loss=1.4463 acc=0.1293 f1=0.0802
  🔥 New best F1: 0.0802 – model saved.

Epoch 11/12


    t_loss=1.3490 | F1(macro)=0.1713 | Acc=0.2624


Confusion matrix:
 [[ 0  0  0 41]
 [ 0  2  0 30]
 [ 0  0  0 30]
 [ 0  0  0 13]]
Train  loss=1.3490 acc=0.2624 f1=0.1713 | Val loss=1.4368 acc=0.1293 f1=0.0806
  🔥 New best F1: 0.0806 – model saved.

Epoch 12/12


    t_loss=1.3093 | F1(macro)=0.1474 | Acc=0.2710


Confusion matrix:
 [[ 0 19  0 22]
 [ 0 14  0 18]
 [ 0  6  0 24]
 [ 0  3  0 10]]
Train  loss=1.3093 acc=0.2710 f1=0.1474 | Val loss=1.4292 acc=0.2069 f1=0.1521
  🔥 New best F1: 0.1521 – model saved.


In [5]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny"

test_dataset = HistologyDataset(
    test_df,
    transforms=val_test_transforms,
    is_train=False,   # returns (img, sample_index)
    image_size=IMAGE_SIZE
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=False,
        num_classes=N_CLASSES
    ).to(device)
    state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv("submission_5fold_no_tta.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png        Luminal A
1  img_0001.png        Luminal A
2  img_0002.png        Luminal A
3  img_0003.png  Triple negative
4  img_0004.png        Luminal A


In [7]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(test_df, transforms=val_test_transforms, is_train=False, image_size=IMAGE_SIZE)
test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
                         shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")
    model = timm.create_model(PRETRAINED_MODEL, pretrained=False, num_classes=N_CLASSES).to(device)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            img_tensor = img_tensor.squeeze(0)  # [3,H,W]
            img_tensor = img_tensor.to(device)

            # -------- TTA: apply multiple augmented views --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1,4]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N, 4]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
pred_indices = mean_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv("submission_5fold_tta.csv", index=False)

print("Saved submission_5fold_tta.csv")

Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_tta.csv


In [ ]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(val_df_split, transforms=val_test_transforms, is_train=True, image_size=IMAGE_SIZE)
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    model = timm.create_model(PRETRAINED_MODEL, pretrained=False, num_classes=N_CLASSES).to(device)
    model.load_state_dict(torch.load(f"effv2_s_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))
