In [1]:
import enum
import json
import os
from copy import deepcopy

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.mixup_cutmix_wrapper import MixupCutmixWrapper
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_multicrop_tta, apply_mask_multicrop_tta
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    EFFICIENTNET_B1_NS = "tf_efficientnet_b1.ns_jft_in1k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B1_NS

In [4]:
best_f1_per_fold: dict[int, int] = {}
N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
N_CLASSES = 4  # number of classes in the dataset (labels)

# efficientnet_b0 / efficientnet_b1

In [5]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,          # Dropout
        drop_path_rate=0.1      # Stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    For EfficientNet from timm: unfreeze last 2 blocks + classifier head.
    """
    freeze_all(model)

    # Last 2 conv blocks
    if hasattr(model, "blocks"):
        for blk in model.blocks[-2:]:
            for p in blk.parameters():
                p.requires_grad = True

    # Classifier head
    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True


if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    GRAD_ACCUM_STEPS = 2
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 25
    LR = 3e-4
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b0_model(pretrained=True)
        unfreeze_last_two_blocks_and_head(model)

        # ---- loss, optimizer, scheduler ----
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.1
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None
        mixup_fn = MixupCutmixWrapper(
            alpha=0.4,       # mixup/cutmix Beta distribution
            mixup_prob=0.4,  # 40% of batches => mixup
            cutmix_prob=0.2  # 20% of batches => cutmix
        )

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device, grad_accum_steps=GRAD_ACCUM_STEPS, mixup_fn=mixup_fn
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(
                    best_state,
                    f"best_effb0_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best weights for this fold
        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1

# tf_efficientnet_b1_ns

In [6]:
def create_efficientnet_b1_ns_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        MODEL_TO_USE.value,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,          # 3 RGB + 1 mask
        drop_rate=0.3,       # stronger dropout than B0
        drop_path_rate=0.1   # stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_two_blocks_and_head(model: nn.Mefficientnet_b0odule):
    """
    Freeze earlier EfficientNet blocks, unfreeze the last two + head.
    Works for timm tf_efficientnet_b* models.
    """
    # 1) Freeze everything by default
    for p in model.parameters():
        p.requires_grad = False

    # 2) Unfreeze last two blocks
    # model.blocks is a nn.Sequential
    num_blocks = len(model.blocks)
    for idx in range(num_blocks - 2, num_blocks):
        for p in model.blocks[idx].parameters():
            p.requires_grad = True

    # 3) Unfreeze conv_head + bn2 + classifier
    for p in model.conv_head.parameters():
        p.requires_grad = True
    for p in model.bn2.parameters():
        p.requires_grad = True
    for p in model.classifier.parameters():
        p.requires_grad = True

def unfreeze_last_stage_and_head(model: nn.Module):
    """
    EfficientNet B1-NS recommended fine-tuning strategy:
    - Freeze all early MBConv stages
    - Unfreeze the last MBConv stage (stage 6)
    - Unfreeze conv_head + bn2 + classifier
    """

    # Freeze everything first
    for p in model.parameters():
        p.requires_grad = False

    # ---- Unfreeze last stage (stage 6) ----
    # EfficientNet blocks are sequential but grouped in stages.
    # B1 layout roughly:
    #   Stage0: stem
    #   Stage1: blocks[0]
    #   Stage2: blocks[1:3]
    #   Stage3: blocks[3:5]
    #   Stage4: blocks[5:8]
    #   Stage5: blocks[8:11]
    #   Stage6: blocks[11:15]  <-- last stage
    last_stage_start = len(model.blocks) - 4  # 4 blocks in last stage (B1)
    for idx in range(last_stage_start, len(model.blocks)):
        for p in model.blocks[idx].parameters():
            p.requires_grad = True

    # ---- Unfreeze head ----
    for p in model.conv_head.parameters():
        p.requires_grad = True
    for p in model.bn2.parameters():
        p.requires_grad = True
    for p in model.classifier.parameters():
        p.requires_grad = True

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1_NS:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    GRAD_ACCUM_STEPS = 2
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 25
    LR = 7.5e-4
    WEIGHT_DECAY = 2e-4
    PREFIX = "tf_effb1_ns"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b1_ns_model(pretrained=True)
        unfreeze_last_stage_and_head(model)

        # ---- loss, optimizer, scheduler ----
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.05
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=WEIGHT_DECAY
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None
        mixup_fn = MixupCutmixWrapper(
            alpha=0.3,       # mixup/cutmix Beta distribution
            mixup_prob=0.3,  # 30% of batches => mixup
            cutmix_prob=0.2  # 20% of batches => cutmix
        )

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device, grad_accum_steps=GRAD_ACCUM_STEPS, mixup_fn=mixup_fn
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(
                    best_state,
                    f"best_{PREFIX}_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best weights for this fold
        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        torch.save(model.state_dict(), f"{PREFIX}_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1


========== Fold 0 ==========

Epoch 1/25


    t_loss=2.1702 | F1(macro)=0.2939 | Acc=0.2996


Confusion matrix:
 [[ 5  0  1 35]
 [ 6  0  2 24]
 [ 3  1  2 24]
 [ 0  0  1 13]]
Train  loss=2.1702 acc=0.2996 f1=0.2939 | Val loss=2.5653 acc=0.1709 f1=0.1323
  🔥 New best F1: 0.1323 – model saved.

Epoch 2/25


    t_loss=1.6350 | F1(macro)=0.3309 | Acc=0.3384


Confusion matrix:
 [[ 6  3 10 22]
 [ 3  4  7 18]
 [ 3  6 10 11]
 [ 1  1  1 11]]
Train  loss=1.6350 acc=0.3384 f1=0.3309 | Val loss=1.8752 acc=0.2650 f1=0.2576
  🔥 New best F1: 0.2576 – model saved.

Epoch 3/25


    t_loss=1.5031 | F1(macro)=0.3427 | Acc=0.3599


Confusion matrix:
 [[22 11  1  7]
 [19  5  1  7]
 [17  6  2  5]
 [ 8  1  1  4]]
Train  loss=1.5031 acc=0.3599 f1=0.3427 | Val loss=1.6382 acc=0.2821 f1=0.2309

Epoch 4/25


    t_loss=1.4332 | F1(macro)=0.3225 | Acc=0.3405


Confusion matrix:
 [[10  1  7 23]
 [10  0  9 13]
 [ 6  0  7 17]
 [ 2  0  1 11]]
Train  loss=1.4332 acc=0.3405 f1=0.3225 | Val loss=1.8070 acc=0.2393 f1=0.2078

Epoch 5/25


    t_loss=1.3013 | F1(macro)=0.3689 | Acc=0.3966


Confusion matrix:
 [[ 2  2 10 27]
 [ 6  6  6 14]
 [ 5  7  4 14]
 [ 4  1  1  8]]
Train  loss=1.3013 acc=0.3966 f1=0.3689 | Val loss=1.9220 acc=0.1709 f1=0.1709

Epoch 6/25


    t_loss=1.3293 | F1(macro)=0.4030 | Acc=0.4181


Confusion matrix:
 [[12  7  4 18]
 [11  8  1 12]
 [ 7  7  5 11]
 [ 4  1  1  8]]
Train  loss=1.3293 acc=0.4181 f1=0.4030 | Val loss=1.7139 acc=0.2821 f1=0.2772
  🔥 New best F1: 0.2772 – model saved.

Epoch 7/25


    t_loss=1.2220 | F1(macro)=0.4588 | Acc=0.4741


Confusion matrix:
 [[ 8  5 16 12]
 [ 9  3  9 11]
 [ 8  2 15  5]
 [ 3  1  4  6]]
Train  loss=1.2220 acc=0.4741 f1=0.4588 | Val loss=1.7241 acc=0.2735 f1=0.2567

Epoch 8/25


    t_loss=1.2473 | F1(macro)=0.4429 | Acc=0.4526


Confusion matrix:
 [[ 8  1  4 28]
 [11  2  5 14]
 [ 8  2  8 12]
 [ 2  2  2  8]]
Train  loss=1.2473 acc=0.4526 f1=0.4429 | Val loss=2.1098 acc=0.2222 f1=0.2170

Epoch 9/25


    t_loss=1.2228 | F1(macro)=0.4574 | Acc=0.4698


Confusion matrix:
 [[ 6 17  7 11]
 [ 4 18  0 10]
 [11 10  0  9]
 [ 3  5  2  4]]
Train  loss=1.2228 acc=0.4698 f1=0.4574 | Val loss=1.9505 acc=0.2393 f1=0.1976

Epoch 10/25


    t_loss=1.1372 | F1(macro)=0.4872 | Acc=0.5000


Confusion matrix:
 [[18  4  6 13]
 [21  3  0  8]
 [15  5  4  6]
 [ 8  0  0  6]]
Train  loss=1.1372 acc=0.5000 f1=0.4872 | Val loss=1.9288 acc=0.2650 f1=0.2353

Epoch 11/25


    t_loss=0.9986 | F1(macro)=0.5594 | Acc=0.5776


Confusion matrix:
 [[19  5  5 12]
 [17  2  0 13]
 [12  6  7  5]
 [ 5  1  4  4]]
Train  loss=0.9986 acc=0.5776 f1=0.5594 | Val loss=2.0113 acc=0.2735 f1=0.2406

Epoch 12/25


    t_loss=0.9800 | F1(macro)=0.5941 | Acc=0.6013


Confusion matrix:
 [[15  4 10 12]
 [12  5  8  7]
 [ 8  3  9 10]
 [ 6  1  2  5]]
Train  loss=0.9800 acc=0.6013 f1=0.5941 | Val loss=1.9091 acc=0.2906 f1=0.2754

Epoch 13/25


    t_loss=0.9338 | F1(macro)=0.5949 | Acc=0.6078


Confusion matrix:
 [[15  2  8 16]
 [11  7  4 10]
 [ 7  3  7 13]
 [ 9  0  2  3]]
Train  loss=0.9338 acc=0.6078 f1=0.5949 | Val loss=1.9755 acc=0.2735 f1=0.2653

Epoch 14/25


    t_loss=0.9108 | F1(macro)=0.6523 | Acc=0.6552


Confusion matrix:
 [[21  4  9  7]
 [12  6  5  9]
 [14  1 13  2]
 [ 9  0  4  1]]
Train  loss=0.9108 acc=0.6552 f1=0.6523 | Val loss=1.9601 acc=0.3504 f1=0.2997
  🔥 New best F1: 0.2997 – model saved.

Epoch 15/25


    t_loss=0.8476 | F1(macro)=0.6645 | Acc=0.6746


Confusion matrix:
 [[10  7 18  6]
 [ 8  9  7  8]
 [ 6  4 15  5]
 [ 4  3  5  2]]
Train  loss=0.8476 acc=0.6746 f1=0.6645 | Val loss=1.9903 acc=0.3077 f1=0.2829

Epoch 16/25


    t_loss=0.7925 | F1(macro)=0.7155 | Acc=0.7177


Confusion matrix:
 [[16  7 13  5]
 [11  7  6  8]
 [12  3 13  2]
 [ 8  1  2  3]]
Train  loss=0.7925 acc=0.7177 f1=0.7155 | Val loss=1.9932 acc=0.3333 f1=0.3093
  🔥 New best F1: 0.3093 – model saved.

Epoch 17/25


    t_loss=0.7690 | F1(macro)=0.6969 | Acc=0.7091


Confusion matrix:
 [[14  9 13  5]
 [13 10  1  8]
 [ 6  9 11  4]
 [ 6  3  3  2]]
Train  loss=0.7690 acc=0.7091 f1=0.6969 | Val loss=2.0262 acc=0.3162 f1=0.2920

Epoch 18/25


    t_loss=0.7455 | F1(macro)=0.7410 | Acc=0.7371


Confusion matrix:
 [[18  9  8  6]
 [14  7  2  9]
 [ 9  6 10  5]
 [ 7  2  1  4]]
Train  loss=0.7455 acc=0.7371 f1=0.7410 | Val loss=2.0007 acc=0.3333 f1=0.3143
  🔥 New best F1: 0.3143 – model saved.

Epoch 19/25


    t_loss=0.6422 | F1(macro)=0.7561 | Acc=0.7629


Confusion matrix:
 [[22  7  7  5]
 [16  5  1 10]
 [14  5  8  3]
 [ 6  2  3  3]]
Train  loss=0.6422 acc=0.7629 f1=0.7561 | Val loss=2.1760 acc=0.3248 f1=0.2846

Epoch 20/25


    t_loss=0.6677 | F1(macro)=0.7756 | Acc=0.7802


Confusion matrix:
 [[22  4  8  7]
 [15  6  1 10]
 [16  2  9  3]
 [ 8  1  3  2]]
Train  loss=0.6677 acc=0.7802 f1=0.7756 | Val loss=2.1136 acc=0.3333 f1=0.2905

Epoch 21/25


    t_loss=0.7285 | F1(macro)=0.7441 | Acc=0.7478


Confusion matrix:
 [[17  6 11  7]
 [12  7  3 10]
 [15  2 11  2]
 [ 6  2  5  1]]
Train  loss=0.7285 acc=0.7478 f1=0.7441 | Val loss=2.1275 acc=0.3077 f1=0.2712

Epoch 22/25


    t_loss=0.6744 | F1(macro)=0.7780 | Acc=0.7802


Confusion matrix:
 [[21  1 11  8]
 [13  5  4 10]
 [16  2  8  4]
 [ 6  2  4  2]]
Train  loss=0.6744 acc=0.7802 f1=0.7780 | Val loss=2.0861 acc=0.3077 f1=0.2643

Epoch 23/25


    t_loss=0.6509 | F1(macro)=0.8103 | Acc=0.8103


Confusion matrix:
 [[20  4 11  6]
 [11 10  4  7]
 [14  4 11  1]
 [ 5  3  4  2]]
Train  loss=0.6509 acc=0.8103 f1=0.8103 | Val loss=2.0389 acc=0.3675 f1=0.3292
  🔥 New best F1: 0.3292 – model saved.

Epoch 24/25


    t_loss=0.6252 | F1(macro)=0.8097 | Acc=0.8125


Confusion matrix:
 [[19  5 11  6]
 [11  9  4  8]
 [14  4 10  2]
 [ 7  2  3  2]]
Train  loss=0.6252 acc=0.8125 f1=0.8097 | Val loss=2.0545 acc=0.3419 f1=0.3073

Epoch 25/25


    t_loss=0.5928 | F1(macro)=0.8422 | Acc=0.8448


Confusion matrix:
 [[17  3 12  9]
 [14  4  2 12]
 [16  2  7  5]
 [ 6  1  3  4]]
Train  loss=0.5928 acc=0.8448 f1=0.8422 | Val loss=2.1182 acc=0.2735 f1=0.2483
Restored best weights for fold 0 (F1=0.3292)

========== Fold 1 ==========

Epoch 1/25


    t_loss=2.1839 | F1(macro)=0.3059 | Acc=0.3161


Confusion matrix:
 [[13  3  4 21]
 [ 8  7  4 13]
 [12  5  5  8]
 [ 0  3  4  6]]
Train  loss=2.1839 acc=0.3161 f1=0.3059 | Val loss=1.9716 acc=0.2672 f1=0.2602
  🔥 New best F1: 0.2602 – model saved.

Epoch 2/25


    t_loss=1.5879 | F1(macro)=0.3059 | Acc=0.3204


Confusion matrix:
 [[ 9  1  2 29]
 [ 4  1  2 25]
 [ 4  0  3 23]
 [ 2  0  3  8]]
Train  loss=1.5879 acc=0.3204 f1=0.3059 | Val loss=2.0036 acc=0.1810 f1=0.1680

Epoch 3/25


    t_loss=1.5163 | F1(macro)=0.2862 | Acc=0.3161


Confusion matrix:
 [[ 6 17  0 18]
 [ 3 12  1 16]
 [ 3 16  0 11]
 [ 0  2  0 11]]
Train  loss=1.5163 acc=0.3161 f1=0.2862 | Val loss=1.8602 acc=0.2500 f1=0.2123

Epoch 4/25


    t_loss=1.3828 | F1(macro)=0.3663 | Acc=0.3785


Confusion matrix:
 [[12  9  6 14]
 [11  4  2 15]
 [10  4  1 15]
 [ 1  2  1  9]]
Train  loss=1.3828 acc=0.3785 f1=0.3663 | Val loss=1.7152 acc=0.2241 f1=0.1999

Epoch 5/25


    t_loss=1.2999 | F1(macro)=0.3689 | Acc=0.4065


Confusion matrix:
 [[ 2  3 18 18]
 [ 0  3  9 20]
 [ 1  3 17  9]
 [ 0  1  8  4]]
Train  loss=1.2999 acc=0.4065 f1=0.3689 | Val loss=1.8395 acc=0.2241 f1=0.1934

Epoch 6/25


    t_loss=1.2795 | F1(macro)=0.4154 | Acc=0.4344


Confusion matrix:
 [[10  6  9 16]
 [ 5  7  6 14]
 [ 5  2  8 15]
 [ 3  3  2  5]]
Train  loss=1.2795 acc=0.4344 f1=0.4154 | Val loss=1.8072 acc=0.2586 f1=0.2605
  🔥 New best F1: 0.2605 – model saved.

Epoch 7/25


    t_loss=1.2643 | F1(macro)=0.4178 | Acc=0.4280


Confusion matrix:
 [[15  6  5 15]
 [ 9  9  3 11]
 [13  2  5 10]
 [ 3  1  5  4]]
Train  loss=1.2643 acc=0.4280 f1=0.4178 | Val loss=1.9752 acc=0.2845 f1=0.2724
  🔥 New best F1: 0.2724 – model saved.

Epoch 8/25


    t_loss=1.1810 | F1(macro)=0.4296 | Acc=0.4473


Confusion matrix:
 [[ 7  9  1 24]
 [ 4 10  1 17]
 [ 7  7  0 16]
 [ 0  4  0  9]]
Train  loss=1.1810 acc=0.4473 f1=0.4296 | Val loss=2.0870 acc=0.2241 f1=0.1969

Epoch 9/25


    t_loss=1.1931 | F1(macro)=0.4417 | Acc=0.4602


Confusion matrix:
 [[13 17  8  3]
 [ 8 17  5  2]
 [11 14  5  0]
 [ 4  2  5  2]]
Train  loss=1.1931 acc=0.4602 f1=0.4417 | Val loss=1.6303 acc=0.3190 f1=0.2852
  🔥 New best F1: 0.2852 – model saved.

Epoch 10/25


    t_loss=1.1324 | F1(macro)=0.4841 | Acc=0.4989


Confusion matrix:
 [[14 13  7  7]
 [ 8  9  5 10]
 [ 5  8 13  4]
 [ 1  2  4  6]]
Train  loss=1.1324 acc=0.4989 f1=0.4841 | Val loss=2.0238 acc=0.3621 f1=0.3569
  🔥 New best F1: 0.3569 – model saved.

Epoch 11/25


    t_loss=1.0216 | F1(macro)=0.5017 | Acc=0.5333


Confusion matrix:
 [[ 3 19 14  5]
 [ 2 21  6  3]
 [ 2 18  8  2]
 [ 0  4  7  2]]
Train  loss=1.0216 acc=0.5333 f1=0.5017 | Val loss=2.6019 acc=0.2931 f1=0.2445

Epoch 12/25


    t_loss=0.9513 | F1(macro)=0.6059 | Acc=0.6172


Confusion matrix:
 [[ 9 16  3 13]
 [ 7 11  2 12]
 [ 5 13  6  6]
 [ 2  4  2  5]]
Train  loss=0.9513 acc=0.6172 f1=0.6059 | Val loss=2.3002 acc=0.2672 f1=0.2635

Epoch 13/25


    t_loss=0.9889 | F1(macro)=0.5549 | Acc=0.5742


Confusion matrix:
 [[16 10 10  5]
 [13  7  7  5]
 [ 6 10 11  3]
 [ 1  3  6  3]]
Train  loss=0.9889 acc=0.5742 f1=0.5549 | Val loss=1.7543 acc=0.3190 f1=0.2980

Epoch 14/25


    t_loss=0.9346 | F1(macro)=0.5912 | Acc=0.6043


Confusion matrix:
 [[12 10  9 10]
 [ 7  9  8  8]
 [ 6  4 13  7]
 [ 4  0  7  2]]
Train  loss=0.9346 acc=0.6043 f1=0.5912 | Val loss=1.8948 acc=0.3103 f1=0.2895

Epoch 15/25


    t_loss=0.8696 | F1(macro)=0.6119 | Acc=0.6280


Confusion matrix:
 [[17  5 13  6]
 [11  3 11  7]
 [ 9  4 12  5]
 [ 5  1  5  2]]
Train  loss=0.8696 acc=0.6280 f1=0.6119 | Val loss=1.8692 acc=0.2931 f1=0.2506

Epoch 16/25


    t_loss=0.8413 | F1(macro)=0.6410 | Acc=0.6559


Confusion matrix:
 [[ 7 15  8 11]
 [ 9  9  4 10]
 [ 3  6 11 10]
 [ 3  3  4  3]]
Train  loss=0.8413 acc=0.6559 f1=0.6410 | Val loss=2.1978 acc=0.2586 f1=0.2532

Epoch 17/25


    t_loss=0.8427 | F1(macro)=0.6425 | Acc=0.6688


Confusion matrix:
 [[13 13  7  8]
 [ 9  7  6 10]
 [ 7  6  8  9]
 [ 4  1  2  6]]
Train  loss=0.8427 acc=0.6688 f1=0.6425 | Val loss=2.0715 acc=0.2931 f1=0.2878

Epoch 18/25


    t_loss=0.8025 | F1(macro)=0.6849 | Acc=0.6903


Confusion matrix:
 [[ 8 13  8 12]
 [ 8 10  7  7]
 [ 5 10 11  4]
 [ 3  3  5  2]]
Train  loss=0.8025 acc=0.6903 f1=0.6849 | Val loss=1.9948 acc=0.2672 f1=0.2515

Epoch 19/25


    t_loss=0.7493 | F1(macro)=0.7240 | Acc=0.7269


Confusion matrix:
 [[14 11  9  7]
 [10  9  7  6]
 [ 9  7 10  4]
 [ 3  0  6  4]]
Train  loss=0.7493 acc=0.7269 f1=0.7240 | Val loss=1.8135 acc=0.3190 f1=0.3066

Epoch 20/25


    t_loss=0.6623 | F1(macro)=0.7221 | Acc=0.7398


Confusion matrix:
 [[16 11 10  4]
 [10 10  8  4]
 [ 6 11 12  1]
 [ 3  2  6  2]]
Train  loss=0.6623 acc=0.7398 f1=0.7221 | Val loss=1.9152 acc=0.3448 f1=0.3136

Epoch 21/25


    t_loss=0.6873 | F1(macro)=0.7583 | Acc=0.7656


Confusion matrix:
 [[17  9  7  8]
 [11  8  6  7]
 [ 9  9 10  2]
 [ 3  3  3  4]]
Train  loss=0.6873 acc=0.7656 f1=0.7583 | Val loss=2.0061 acc=0.3362 f1=0.3186

Epoch 22/25


    t_loss=0.7226 | F1(macro)=0.7574 | Acc=0.7591


Confusion matrix:
 [[15 13  6  7]
 [11 11  5  5]
 [ 8 10 11  1]
 [ 3  3  5  2]]
Train  loss=0.7226 acc=0.7591 f1=0.7574 | Val loss=1.9370 acc=0.3362 f1=0.3081

Epoch 23/25


    t_loss=0.7114 | F1(macro)=0.7701 | Acc=0.7720


Confusion matrix:
 [[12 10 11  8]
 [ 9 10  7  6]
 [ 6  7 16  1]
 [ 3  1  7  2]]
Train  loss=0.7114 acc=0.7720 f1=0.7701 | Val loss=2.0145 acc=0.3448 f1=0.3138

Epoch 24/25


    t_loss=0.7724 | F1(macro)=0.7283 | Acc=0.7312


Confusion matrix:
 [[12 13  8  8]
 [ 9 10  8  5]
 [ 4  8 12  6]
 [ 2  3  5  3]]
Train  loss=0.7724 acc=0.7312 f1=0.7283 | Val loss=1.9864 acc=0.3190 f1=0.3021

Epoch 25/25


    t_loss=0.6557 | F1(macro)=0.7754 | Acc=0.7871


Confusion matrix:
 [[14 14  8  5]
 [10 11  6  5]
 [ 6  9 12  3]
 [ 3  2  7  1]]
Train  loss=0.6557 acc=0.7871 f1=0.7754 | Val loss=1.9695 acc=0.3276 f1=0.2892
Restored best weights for fold 1 (F1=0.3569)

========== Fold 2 ==========

Epoch 1/25


    t_loss=2.3032 | F1(macro)=0.2788 | Acc=0.2925


Confusion matrix:
 [[13  2  0 26]
 [10  5  1 15]
 [ 9  3  0 18]
 [ 1  2  0 11]]
Train  loss=2.3032 acc=0.2925 f1=0.2788 | Val loss=1.9301 acc=0.2500 f1=0.2115
  🔥 New best F1: 0.2115 – model saved.

Epoch 2/25


    t_loss=1.5802 | F1(macro)=0.2981 | Acc=0.3097


Confusion matrix:
 [[ 0  4 19 18]
 [ 0  2 11 18]
 [ 0  0 11 19]
 [ 0  0  5  9]]
Train  loss=1.5802 acc=0.3097 f1=0.2981 | Val loss=1.8605 acc=0.1897 f1=0.1571

Epoch 3/25


    t_loss=1.5015 | F1(macro)=0.2848 | Acc=0.3097


Confusion matrix:
 [[ 5  5 23  8]
 [ 8  5 13  5]
 [ 3  4 15  8]
 [ 1  1  8  4]]
Train  loss=1.5015 acc=0.3097 f1=0.2848 | Val loss=1.5916 acc=0.2500 f1=0.2330
  🔥 New best F1: 0.2330 – model saved.

Epoch 4/25


    t_loss=1.4621 | F1(macro)=0.3433 | Acc=0.3570


Confusion matrix:
 [[14 21  0  6]
 [ 9 17  0  5]
 [16  9  0  5]
 [ 9  2  0  3]]
Train  loss=1.4621 acc=0.3570 f1=0.3433 | Val loss=1.9036 acc=0.2931 f1=0.2304

Epoch 5/25


    t_loss=1.4577 | F1(macro)=0.3052 | Acc=0.3290


Confusion matrix:
 [[ 2  9 24  6]
 [ 2  8 17  4]
 [ 1  5 18  6]
 [ 3  0  6  5]]
Train  loss=1.4577 acc=0.3290 f1=0.3052 | Val loss=1.5412 acc=0.2845 f1=0.2620
  🔥 New best F1: 0.2620 – model saved.

Epoch 6/25


    t_loss=1.3820 | F1(macro)=0.3418 | Acc=0.3634


Confusion matrix:
 [[ 5  3 21 12]
 [ 5  4 10 12]
 [ 9  1 15  5]
 [ 4  1  4  5]]
Train  loss=1.3820 acc=0.3634 f1=0.3418 | Val loss=1.5909 acc=0.2500 f1=0.2349

Epoch 7/25


    t_loss=1.2686 | F1(macro)=0.4151 | Acc=0.4323


Confusion matrix:
 [[14  3  7 17]
 [11  3  5 12]
 [ 6  4  8 12]
 [ 0  1  2 11]]
Train  loss=1.2686 acc=0.4323 f1=0.4151 | Val loss=1.5442 acc=0.3103 f1=0.2932
  🔥 New best F1: 0.2932 – model saved.

Epoch 8/25


    t_loss=1.1511 | F1(macro)=0.4564 | Acc=0.4796


Confusion matrix:
 [[ 5  9 18  9]
 [ 4 10  9  8]
 [ 2  8 13  7]
 [ 2  3  3  6]]
Train  loss=1.1511 acc=0.4796 f1=0.4564 | Val loss=1.9158 acc=0.2931 f1=0.2855

Epoch 9/25


    t_loss=1.1564 | F1(macro)=0.4271 | Acc=0.4774


Confusion matrix:
 [[ 7  8  0 26]
 [ 6  8  0 17]
 [ 3  2  3 22]
 [ 2  0  0 12]]
Train  loss=1.1564 acc=0.4774 f1=0.4271 | Val loss=2.0032 acc=0.2586 f1=0.2523

Epoch 10/25


    t_loss=1.1596 | F1(macro)=0.4931 | Acc=0.5097


Confusion matrix:
 [[13  7  6 15]
 [ 5  6  6 14]
 [ 5  5 10 10]
 [ 4  2  1  7]]
Train  loss=1.1596 acc=0.5097 f1=0.4931 | Val loss=1.9287 acc=0.3103 f1=0.3071
  🔥 New best F1: 0.3071 – model saved.

Epoch 11/25


    t_loss=1.0295 | F1(macro)=0.4972 | Acc=0.5312


Confusion matrix:
 [[20  3  6 12]
 [15  2  1 13]
 [ 9  2  4 15]
 [ 6  0  0  8]]
Train  loss=1.0295 acc=0.5312 f1=0.4972 | Val loss=1.9520 acc=0.2931 f1=0.2495

Epoch 12/25


    t_loss=1.0368 | F1(macro)=0.5193 | Acc=0.5376


Confusion matrix:
 [[ 9  3 12 17]
 [10  2  7 12]
 [ 5  2  9 14]
 [ 5  1  2  6]]
Train  loss=1.0368 acc=0.5376 f1=0.5193 | Val loss=2.1936 acc=0.2241 f1=0.2125

Epoch 13/25


    t_loss=1.0023 | F1(macro)=0.5377 | Acc=0.5548


Confusion matrix:
 [[ 6 10 12 13]
 [ 7  7  9  8]
 [ 5  5  8 12]
 [ 1  4  3  6]]
Train  loss=1.0023 acc=0.5548 f1=0.5377 | Val loss=2.2627 acc=0.2328 f1=0.2325

Epoch 14/25


    t_loss=0.9968 | F1(macro)=0.5382 | Acc=0.5591


Confusion matrix:
 [[14  9 11  7]
 [10  6  9  6]
 [ 7  3  8 12]
 [ 5  3  3  3]]
Train  loss=0.9968 acc=0.5591 f1=0.5382 | Val loss=1.8233 acc=0.2672 f1=0.2499

Epoch 15/25


    t_loss=0.9321 | F1(macro)=0.5861 | Acc=0.6000


Confusion matrix:
 [[24  4  9  4]
 [12  8  7  4]
 [10  4 10  6]
 [ 8  1  3  2]]
Train  loss=0.9321 acc=0.6000 f1=0.5861 | Val loss=1.8071 acc=0.3793 f1=0.3277
  🔥 New best F1: 0.3277 – model saved.

Epoch 16/25


    t_loss=0.9132 | F1(macro)=0.6255 | Acc=0.6258


Confusion matrix:
 [[21  2  9  9]
 [10  4  8  9]
 [ 9  2  8 11]
 [ 6  0  2  6]]
Train  loss=0.9132 acc=0.6258 f1=0.6255 | Val loss=1.8926 acc=0.3362 f1=0.3034

Epoch 17/25


    t_loss=0.7754 | F1(macro)=0.6776 | Acc=0.6968


Confusion matrix:
 [[20  2 14  5]
 [13  4  6  8]
 [11  3  8  8]
 [ 8  1  2  3]]
Train  loss=0.7754 acc=0.6968 f1=0.6776 | Val loss=1.9680 acc=0.3017 f1=0.2624

Epoch 18/25


    t_loss=0.7811 | F1(macro)=0.6876 | Acc=0.6946


Confusion matrix:
 [[ 9  5 21  6]
 [ 9  5 11  6]
 [ 7  2 14  7]
 [ 3  1  7  3]]
Train  loss=0.7811 acc=0.6946 f1=0.6876 | Val loss=1.9216 acc=0.2672 f1=0.2480

Epoch 19/25


    t_loss=0.7360 | F1(macro)=0.6724 | Acc=0.6860


Confusion matrix:
 [[22  9  7  3]
 [14 10  4  3]
 [14  1  7  8]
 [11  0  3  0]]
Train  loss=0.7360 acc=0.6860 f1=0.6724 | Val loss=2.1542 acc=0.3362 f1=0.2745

Epoch 20/25


    t_loss=0.7847 | F1(macro)=0.7268 | Acc=0.7290


Confusion matrix:
 [[16  5 17  3]
 [11  7  8  5]
 [12  2 10  6]
 [ 4  1  6  3]]
Train  loss=0.7847 acc=0.7290 f1=0.7268 | Val loss=2.0401 acc=0.3103 f1=0.2901

Epoch 21/25


    t_loss=0.7482 | F1(macro)=0.7409 | Acc=0.7398


Confusion matrix:
 [[26  3  8  4]
 [15  5  7  4]
 [15  1  8  6]
 [ 7  0  5  2]]
Train  loss=0.7482 acc=0.7398 f1=0.7409 | Val loss=2.1356 acc=0.3534 f1=0.2898

Epoch 22/25


    t_loss=0.7459 | F1(macro)=0.6805 | Acc=0.6946


Confusion matrix:
 [[17  2 18  4]
 [11  9  8  3]
 [ 9  2 13  6]
 [ 5  1  5  3]]
Train  loss=0.7459 acc=0.6946 f1=0.6805 | Val loss=1.9206 acc=0.3621 f1=0.3402
  🔥 New best F1: 0.3402 – model saved.

Epoch 23/25


    t_loss=0.6900 | F1(macro)=0.7871 | Acc=0.7914


Confusion matrix:
 [[22  3 14  2]
 [14  8  6  3]
 [13  2  9  6]
 [ 7  1  5  1]]
Train  loss=0.6900 acc=0.7914 f1=0.7871 | Val loss=1.9969 acc=0.3448 f1=0.2918

Epoch 24/25


    t_loss=0.7131 | F1(macro)=0.7169 | Acc=0.7290


Confusion matrix:
 [[20  7 10  4]
 [12  9  8  2]
 [13  2  8  7]
 [ 8  1  4  1]]
Train  loss=0.7131 acc=0.7290 f1=0.7169 | Val loss=2.0096 acc=0.3276 f1=0.2809

Epoch 25/25


    t_loss=0.6978 | F1(macro)=0.7647 | Acc=0.7699


Confusion matrix:
 [[20  3 14  4]
 [12  7  8  4]
 [13  2  8  7]
 [ 6  1  4  3]]
Train  loss=0.6978 acc=0.7699 f1=0.7647 | Val loss=1.8705 acc=0.3276 f1=0.2976
Restored best weights for fold 2 (F1=0.3402)

========== Fold 3 ==========

Epoch 1/25


    t_loss=2.4312 | F1(macro)=0.2506 | Acc=0.2710


Confusion matrix:
 [[ 5 16  2 18]
 [ 3 11  3 14]
 [ 4 13  1 12]
 [ 2  4  0  8]]
Train  loss=2.4312 acc=0.2710 f1=0.2506 | Val loss=2.1138 acc=0.2155 f1=0.1933
  🔥 New best F1: 0.1933 – model saved.

Epoch 2/25


    t_loss=1.6397 | F1(macro)=0.2934 | Acc=0.3161


Confusion matrix:
 [[ 7  8  3 23]
 [ 2 11  3 15]
 [ 3  3  3 21]
 [ 2  3  2  7]]
Train  loss=1.6397 acc=0.3161 f1=0.2934 | Val loss=1.7001 acc=0.2414 f1=0.2422
  🔥 New best F1: 0.2422 – model saved.

Epoch 3/25


    t_loss=1.5021 | F1(macro)=0.3406 | Acc=0.3505


Confusion matrix:
 [[ 7  6  0 28]
 [ 2 12  0 17]
 [ 4  4  0 22]
 [ 3  3  0  8]]
Train  loss=1.5021 acc=0.3505 f1=0.3406 | Val loss=2.0487 acc=0.2328 f1=0.2135

Epoch 4/25


    t_loss=1.5486 | F1(macro)=0.3124 | Acc=0.3226


Confusion matrix:
 [[15  9  1 16]
 [ 7 11  3 10]
 [ 9  9  3  9]
 [ 4  4  1  5]]
Train  loss=1.5486 acc=0.3226 f1=0.3124 | Val loss=1.6044 acc=0.2931 f1=0.2704
  🔥 New best F1: 0.2704 – model saved.

Epoch 5/25


    t_loss=1.3597 | F1(macro)=0.3513 | Acc=0.3613


Confusion matrix:
 [[23  2  0 16]
 [13  7  0 11]
 [ 4  3  3 20]
 [ 4  3  2  5]]
Train  loss=1.3597 acc=0.3613 f1=0.3513 | Val loss=2.0445 acc=0.3276 f1=0.2921
  🔥 New best F1: 0.2921 – model saved.

Epoch 6/25


    t_loss=1.3016 | F1(macro)=0.3325 | Acc=0.3548


Confusion matrix:
 [[12  9  9 11]
 [ 5 11  6  9]
 [ 8  6 10  6]
 [ 3  1  4  6]]
Train  loss=1.3016 acc=0.3548 f1=0.3325 | Val loss=1.6411 acc=0.3362 f1=0.3317
  🔥 New best F1: 0.3317 – model saved.

Epoch 7/25


    t_loss=1.2346 | F1(macro)=0.4173 | Acc=0.4366


Confusion matrix:
 [[21  5  1 14]
 [18  5  1  7]
 [16  0  3 11]
 [ 6  2  0  6]]
Train  loss=1.2346 acc=0.4366 f1=0.4173 | Val loss=1.9473 acc=0.3017 f1=0.2616

Epoch 8/25


    t_loss=1.2288 | F1(macro)=0.4479 | Acc=0.4688


Confusion matrix:
 [[20  6  6  9]
 [14  4  9  4]
 [16  2  9  3]
 [ 6  1  4  3]]
Train  loss=1.2288 acc=0.4688 f1=0.4479 | Val loss=1.9368 acc=0.3103 f1=0.2716

Epoch 9/25


    t_loss=1.0957 | F1(macro)=0.4765 | Acc=0.4968


Confusion matrix:
 [[10  2  6 23]
 [10  5  6 10]
 [ 6  3  5 16]
 [ 4  1  0  9]]
Train  loss=1.0957 acc=0.4968 f1=0.4765 | Val loss=2.2088 acc=0.2500 f1=0.2456

Epoch 10/25


    t_loss=1.1608 | F1(macro)=0.4646 | Acc=0.4860


Confusion matrix:
 [[ 4 17  2 18]
 [ 2 18  1 10]
 [ 9  9  1 11]
 [ 1  7  1  5]]
Train  loss=1.1608 acc=0.4860 f1=0.4646 | Val loss=2.1277 acc=0.2414 f1=0.2022

Epoch 11/25


    t_loss=0.9873 | F1(macro)=0.5293 | Acc=0.5462


Confusion matrix:
 [[10  9  9 13]
 [11  7  2 11]
 [13  3  5  9]
 [ 2  5  1  6]]
Train  loss=0.9873 acc=0.5462 f1=0.5293 | Val loss=2.0317 acc=0.2414 f1=0.2384

Epoch 12/25


    t_loss=0.9999 | F1(macro)=0.5431 | Acc=0.5656


Confusion matrix:
 [[ 2 14 16  9]
 [ 7  8 11  5]
 [ 7  5 14  4]
 [ 1  5  4  4]]
Train  loss=0.9999 acc=0.5656 f1=0.5431 | Val loss=2.2648 acc=0.2414 f1=0.2296

Epoch 13/25


    t_loss=1.0488 | F1(macro)=0.5332 | Acc=0.5505


Confusion matrix:
 [[ 9 12  4 16]
 [ 9 13  2  7]
 [10  9  6  5]
 [ 2  5  1  6]]
Train  loss=1.0488 acc=0.5505 f1=0.5332 | Val loss=2.0810 acc=0.2931 f1=0.2885

Epoch 14/25


    t_loss=0.9280 | F1(macro)=0.5680 | Acc=0.5914


Confusion matrix:
 [[ 7 11  6 17]
 [ 5 14  3  9]
 [ 6 11  5  8]
 [ 1  4  1  8]]
Train  loss=0.9280 acc=0.5914 f1=0.5680 | Val loss=2.2774 acc=0.2931 f1=0.2839

Epoch 15/25


    t_loss=0.9294 | F1(macro)=0.6142 | Acc=0.6237


Confusion matrix:
 [[12  8 11 10]
 [10 11  5  5]
 [11  5  8  6]
 [ 4  3  3  4]]
Train  loss=0.9294 acc=0.6237 f1=0.6142 | Val loss=2.0958 acc=0.3017 f1=0.2932

Epoch 16/25


    t_loss=0.8900 | F1(macro)=0.6620 | Acc=0.6710


Confusion matrix:
 [[11 13  7 10]
 [ 8 13  4  6]
 [ 9  9  9  3]
 [ 3  4  2  5]]
Train  loss=0.8900 acc=0.6710 f1=0.6620 | Val loss=2.0211 acc=0.3276 f1=0.3216

Epoch 17/25


    t_loss=0.8365 | F1(macro)=0.6710 | Acc=0.6839


Confusion matrix:
 [[ 8 10 12 11]
 [ 7 10  6  8]
 [ 7  6 13  4]
 [ 2  3  3  6]]
Train  loss=0.8365 acc=0.6839 f1=0.6710 | Val loss=2.0973 acc=0.3190 f1=0.3162

Epoch 18/25


    t_loss=0.7996 | F1(macro)=0.6733 | Acc=0.6796


Confusion matrix:
 [[ 7 18 12  4]
 [ 7 11  7  6]
 [ 9  5 12  4]
 [ 2  5  4  3]]
Train  loss=0.7996 acc=0.6796 f1=0.6733 | Val loss=2.0260 acc=0.2845 f1=0.2723

Epoch 19/25


    t_loss=0.7535 | F1(macro)=0.7257 | Acc=0.7269


Confusion matrix:
 [[ 4 12 15 10]
 [ 6 12  7  6]
 [ 5  4 17  4]
 [ 1  3  5  5]]
Train  loss=0.7535 acc=0.7269 f1=0.7257 | Val loss=2.1545 acc=0.3276 f1=0.3108

Epoch 20/25


    t_loss=0.7300 | F1(macro)=0.7036 | Acc=0.7183


Confusion matrix:
 [[ 4 16 14  7]
 [ 7 15  6  3]
 [ 2 10 13  5]
 [ 1  5  4  4]]
Train  loss=0.7300 acc=0.7183 f1=0.7036 | Val loss=2.1581 acc=0.3103 f1=0.2914

Epoch 21/25


    t_loss=0.7120 | F1(macro)=0.7509 | Acc=0.7656


Confusion matrix:
 [[ 6 14 15  6]
 [ 6 11  8  6]
 [ 5  6 15  4]
 [ 2  2  5  5]]
Train  loss=0.7120 acc=0.7656 f1=0.7509 | Val loss=1.9977 acc=0.3190 f1=0.3101

Epoch 22/25


    t_loss=0.7178 | F1(macro)=0.7343 | Acc=0.7376


Confusion matrix:
 [[12 11 12  6]
 [ 9 12  5  5]
 [ 8  6 13  3]
 [ 5  2  3  4]]
Train  loss=0.7178 acc=0.7376 f1=0.7343 | Val loss=2.0578 acc=0.3534 f1=0.3424
  🔥 New best F1: 0.3424 – model saved.

Epoch 23/25


    t_loss=0.7052 | F1(macro)=0.7359 | Acc=0.7419


Confusion matrix:
 [[15 12 11  3]
 [ 9 14  5  3]
 [11  8 10  1]
 [ 3  3  4  4]]
Train  loss=0.7052 acc=0.7419 f1=0.7359 | Val loss=2.1465 acc=0.3707 f1=0.3612
  🔥 New best F1: 0.3612 – model saved.

Epoch 24/25


    t_loss=0.6618 | F1(macro)=0.7724 | Acc=0.7763


Confusion matrix:
 [[ 9 16 13  3]
 [ 8 11  5  7]
 [ 7  9 11  3]
 [ 2  3  5  4]]
Train  loss=0.6618 acc=0.7763 f1=0.7724 | Val loss=2.1264 acc=0.3017 f1=0.2962

Epoch 25/25


    t_loss=0.7285 | F1(macro)=0.7506 | Acc=0.7548


Confusion matrix:
 [[ 6 11 14 10]
 [ 5 13  6  7]
 [ 7  6 13  4]
 [ 4  3  3  4]]
Train  loss=0.7285 acc=0.7548 f1=0.7506 | Val loss=2.2076 acc=0.3103 f1=0.2989
Restored best weights for fold 3 (F1=0.3612)

========== Fold 4 ==========

Epoch 1/25


    t_loss=2.4928 | F1(macro)=0.2524 | Acc=0.2624


Confusion matrix:
 [[ 1  4 18 17]
 [ 5  4  9 14]
 [ 0  5 11 14]
 [ 0  1  4  9]]
Train  loss=2.4928 acc=0.2624 f1=0.2524 | Val loss=2.0375 acc=0.2155 f1=0.1969
  🔥 New best F1: 0.1969 – model saved.

Epoch 2/25


    t_loss=1.6421 | F1(macro)=0.3315 | Acc=0.3398


Confusion matrix:
 [[ 2  5  8 25]
 [ 1 10  5 16]
 [ 0  7  3 20]
 [ 0  1  2 11]]
Train  loss=1.6421 acc=0.3398 f1=0.3315 | Val loss=1.8673 acc=0.2241 f1=0.2094
  🔥 New best F1: 0.2094 – model saved.

Epoch 3/25


    t_loss=1.5017 | F1(macro)=0.3018 | Acc=0.3204


Confusion matrix:
 [[ 6  7 12 15]
 [ 5 11  5 11]
 [ 4  8  5 13]
 [ 3  5  6  0]]
Train  loss=1.5017 acc=0.3204 f1=0.3018 | Val loss=1.7175 acc=0.1897 f1=0.1821

Epoch 4/25


    t_loss=1.4072 | F1(macro)=0.3770 | Acc=0.3914


Confusion matrix:
 [[ 4 10 14 12]
 [ 8  7  8  9]
 [ 2  8  9 11]
 [ 2  3  4  5]]
Train  loss=1.4072 acc=0.3914 f1=0.3770 | Val loss=1.9874 acc=0.2155 f1=0.2123
  🔥 New best F1: 0.2123 – model saved.

Epoch 5/25


    t_loss=1.3365 | F1(macro)=0.3681 | Acc=0.3892


Confusion matrix:
 [[13 13  9  5]
 [10 12  7  3]
 [ 6  8 12  4]
 [ 5  3  4  2]]
Train  loss=1.3365 acc=0.3892 f1=0.3681 | Val loss=1.7701 acc=0.3362 f1=0.3086
  🔥 New best F1: 0.3086 – model saved.

Epoch 6/25


    t_loss=1.2820 | F1(macro)=0.4501 | Acc=0.4624


Confusion matrix:
 [[ 0 13 19  8]
 [ 2 13 10  7]
 [ 1  9 13  7]
 [ 0  8  6  0]]
Train  loss=1.2820 acc=0.4624 f1=0.4501 | Val loss=1.9376 acc=0.2241 f1=0.1700

Epoch 7/25


    t_loss=1.1928 | F1(macro)=0.4183 | Acc=0.4387


Confusion matrix:
 [[14 11  7  8]
 [ 9 14  2  7]
 [ 6 13  3  8]
 [ 6  3  1  4]]
Train  loss=1.1928 acc=0.4387 f1=0.4183 | Val loss=1.7252 acc=0.3017 f1=0.2729

Epoch 8/25


    t_loss=1.1797 | F1(macro)=0.4795 | Acc=0.4925


Confusion matrix:
 [[10 10 10 10]
 [ 9  7  9  7]
 [13  4  8  5]
 [ 4  2  8  0]]
Train  loss=1.1797 acc=0.4925 f1=0.4795 | Val loss=1.7857 acc=0.2155 f1=0.1910

Epoch 9/25


    t_loss=1.0722 | F1(macro)=0.4685 | Acc=0.4946


Confusion matrix:
 [[15  7  4 14]
 [ 7 10  8  7]
 [10  5  6  9]
 [ 6  4  3  1]]
Train  loss=1.0722 acc=0.4946 f1=0.4685 | Val loss=1.8443 acc=0.2759 f1=0.2523

Epoch 10/25


    t_loss=1.0976 | F1(macro)=0.5069 | Acc=0.5161


Confusion matrix:
 [[ 7  9 14 10]
 [ 7 10  8  7]
 [ 3  4 17  6]
 [ 5  3  3  3]]
Train  loss=1.0976 acc=0.5161 f1=0.5069 | Val loss=1.9897 acc=0.3190 f1=0.2982

Epoch 11/25


    t_loss=1.0838 | F1(macro)=0.5412 | Acc=0.5462


Confusion matrix:
 [[ 8 21 11  0]
 [ 7 18  6  1]
 [ 3 12 14  1]
 [ 2  6  6  0]]
Train  loss=1.0838 acc=0.5462 f1=0.5412 | Val loss=2.0117 acc=0.3448 f1=0.2723

Epoch 12/25


    t_loss=0.8911 | F1(macro)=0.5499 | Acc=0.5935


Confusion matrix:
 [[10  8 19  3]
 [ 5  9 17  1]
 [ 4  5 18  3]
 [ 3  1 10  0]]
Train  loss=0.8911 acc=0.5935 f1=0.5499 | Val loss=2.0491 acc=0.3190 f1=0.2582

Epoch 13/25


    t_loss=0.9273 | F1(macro)=0.6259 | Acc=0.6387


Confusion matrix:
 [[16 10 12  2]
 [10 12  9  1]
 [11  6  9  4]
 [ 4  3  4  3]]
Train  loss=0.9273 acc=0.6387 f1=0.6259 | Val loss=2.1459 acc=0.3448 f1=0.3268
  🔥 New best F1: 0.3268 – model saved.

Epoch 14/25


    t_loss=0.8965 | F1(macro)=0.5860 | Acc=0.6086


Confusion matrix:
 [[11  6 18  5]
 [ 5  9 15  3]
 [ 5  3 18  4]
 [ 5  2  6  1]]
Train  loss=0.8965 acc=0.6086 f1=0.5860 | Val loss=1.9693 acc=0.3362 f1=0.2918

Epoch 15/25


    t_loss=0.9360 | F1(macro)=0.6137 | Acc=0.6172


Confusion matrix:
 [[16 15  4  5]
 [ 6 17  7  2]
 [ 4 10  8  8]
 [ 3  6  4  1]]
Train  loss=0.9360 acc=0.6172 f1=0.6137 | Val loss=1.9774 acc=0.3621 f1=0.3143

Epoch 16/25


    t_loss=0.8459 | F1(macro)=0.6534 | Acc=0.6602


Confusion matrix:
 [[14 12 11  3]
 [ 8 15  7  2]
 [ 7  9 11  3]
 [ 4  5  3  2]]
Train  loss=0.8459 acc=0.6602 f1=0.6534 | Val loss=2.0627 acc=0.3621 f1=0.3290
  🔥 New best F1: 0.3290 – model saved.

Epoch 17/25


    t_loss=0.7402 | F1(macro)=0.7023 | Acc=0.7140


Confusion matrix:
 [[19  8  6  7]
 [ 9 15  6  2]
 [ 5 10  8  7]
 [ 3  2  6  3]]
Train  loss=0.7402 acc=0.7140 f1=0.7023 | Val loss=1.9537 acc=0.3879 f1=0.3538
  🔥 New best F1: 0.3538 – model saved.

Epoch 18/25


    t_loss=0.7617 | F1(macro)=0.7229 | Acc=0.7247


Confusion matrix:
 [[14 13  9  4]
 [ 6 20  4  2]
 [ 3 14 11  2]
 [ 4  6  3  1]]
Train  loss=0.7617 acc=0.7247 f1=0.7229 | Val loss=2.0373 acc=0.3966 f1=0.3404

Epoch 19/25


    t_loss=0.6857 | F1(macro)=0.7419 | Acc=0.7505


Confusion matrix:
 [[18 10  7  5]
 [11 14  5  2]
 [10  8  9  3]
 [ 4  4  4  2]]
Train  loss=0.6857 acc=0.7505 f1=0.7419 | Val loss=1.9989 acc=0.3707 f1=0.3317

Epoch 20/25


    t_loss=0.6570 | F1(macro)=0.7514 | Acc=0.7570


Confusion matrix:
 [[18  8 10  4]
 [ 9 14  8  1]
 [ 7  7 15  1]
 [ 5  1  7  1]]
Train  loss=0.6570 acc=0.7570 f1=0.7514 | Val loss=2.0190 acc=0.4138 f1=0.3578
  🔥 New best F1: 0.3578 – model saved.

Epoch 21/25


    t_loss=0.7146 | F1(macro)=0.7454 | Acc=0.7527


Confusion matrix:
 [[15  9  8  8]
 [ 7 15  6  4]
 [ 7  7 13  3]
 [ 3  2  7  2]]
Train  loss=0.7146 acc=0.7527 f1=0.7454 | Val loss=1.8588 acc=0.3879 f1=0.3534

Epoch 22/25


    t_loss=0.6613 | F1(macro)=0.7578 | Acc=0.7677


Confusion matrix:
 [[17 12  9  2]
 [ 9 14  8  1]
 [10  7 12  1]
 [ 4  3  7  0]]
Train  loss=0.6613 acc=0.7677 f1=0.7578 | Val loss=1.8938 acc=0.3707 f1=0.3001

Epoch 23/25


    t_loss=0.6830 | F1(macro)=0.7826 | Acc=0.7871


Confusion matrix:
 [[21  6  7  6]
 [11 12  6  3]
 [11  4 11  4]
 [ 3  4  6  1]]
Train  loss=0.6830 acc=0.7871 f1=0.7826 | Val loss=1.9272 acc=0.3879 f1=0.3351

Epoch 24/25


    t_loss=0.6512 | F1(macro)=0.7740 | Acc=0.7828


Confusion matrix:
 [[17  8 11  4]
 [ 9 11  9  3]
 [ 6  8 15  1]
 [ 4  3  6  1]]
Train  loss=0.6512 acc=0.7828 f1=0.7740 | Val loss=2.0523 acc=0.3793 f1=0.3279

Epoch 25/25


    t_loss=0.6507 | F1(macro)=0.7788 | Acc=0.7849


Confusion matrix:
 [[19  9  7  5]
 [ 9 13  8  2]
 [ 7  7 12  4]
 [ 5  3  5  1]]
Train  loss=0.6507 acc=0.7849 f1=0.7788 | Val loss=1.8986 acc=0.3879 f1=0.3363
Restored best weights for fold 4 (F1=0.3578)


# tf_efficientnetv2_s.in21k

In [7]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [8]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [9]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1 else "tf_effb1_ns"

FOLD_VAL_F1 = f"fold_val_f1_{prefix_filename}.json"

# Save best F1 per fold to JSON
with open(FOLD_VAL_F1, "w") as f:
    json.dump(best_f1_per_fold, f, indent=2)

In [10]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=data.image_size,
    is_train=False,   # deterministic, returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=1,               # per-image TTA
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

if os.path.exists(FOLD_VAL_F1):
    with open(FOLD_VAL_F1, "r") as f:
        best_f1_per_fold = json.load(f)
    val_f1_per_fold = np.array([best_f1_per_fold[str(k)] for k in range(data.num_K_folds)])
    # Normalize to get weights that sum to 1
    fold_weights = val_f1_per_fold / val_f1_per_fold.sum()
else:
    # fallback: uniform weights if metrics are missing
    print('Warning: fold validation F1 scores not found, using uniform weights.')
    fold_weights = np.ones(data.num_K_folds, dtype=np.float32) / data.num_K_folds

print("Fold weights:", fold_weights)

# -----------------------------
# 2) Accumulate weighted probs
# -----------------------------
all_probs = None
all_sample_indices = None

for fold in range(data.num_K_folds):
    print(f"Inference with fold {fold} model (weight={fold_weights[fold]:.3f})")

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0:
        model = create_efficientnet_b0_model(pretrained=False)
    else:
        model = create_efficientnet_b1_ns_model(pretrained=False)

    state_dict = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            # img_tensor: [1, 4, H, W]  (RGB+mask)
            img_tensor = img_tensor.squeeze(0).to(device)  # [4, H, W]

            # -------- TTA: mask-based multi-crop + simple flips --------
            USE_MASK_TTA = False
            if USE_MASK_TTA:
                tta_tensors = apply_mask_multicrop_tta(img_tensor, crop_size=data.image_size, n_crops=2)
            else:
                tta_tensors = apply_multicrop_tta(img_tensor, base_size=data.image_size, inner_ratio=0.8)


            # accumulate probability predictions
            probs_sum = 0.0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1, 4, H, W]
                with torch.no_grad():
                    logits = model(aug_img)
                    probs = softmax(logits, dim=1)  # [1, N_CLASSES]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)
            fold_probs.append(avg_probs)

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N_test, N_CLASSES]

    # initialize global probs
    if all_probs is None:
        all_probs = np.zeros_like(fold_probs, dtype=np.float32)

     # weighted accumulation
    all_probs += fold_weights[fold] * fold_probs

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# -----------------------------
# 3) Final predictions
# -----------------------------
pred_indices = all_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print(f"Saved submission_5fold_tta_{prefix_filename}.csv")

Fold weights: [0.18862717 0.20449834 0.19493961 0.20695047 0.20498441]
Inference with fold 0 model (weight=0.189)
Inference with fold 1 model (weight=0.204)
Inference with fold 2 model (weight=0.195)
Inference with fold 3 model (weight=0.207)
Inference with fold 4 model (weight=0.205)
Saved submission_5fold_tta_tf_effb1_ns.csv


In [11]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(data.num_K_folds):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=data.image_size,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.3316949152542373
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.2756870586233302
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.277041302172585
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.365990778420157
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.3307377365281777
Mean OOF F1: 0.3162303581996974
