In [1]:
import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.persistence_manager import PersistenceManager
from notebooks.internal.nn.weighted_random_sampler import make_weighted_sampler

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
N_FOLDS = data.num_K_folds
IMAGE_SIZE = data.image_size
BATCH_SIZE = 4
PRETRAINED_MODEL = "tf_efficientnetv2_s.in21k"
N_CLASSES = 4 # number of classes in the dataset (labels)
N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4

for fold in range(N_FOLDS):
    print(f"\n========== Fold {fold} ==========")

    train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
    val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

    train_dataset = HistologyDataset(train_df_split, transforms=train_transforms, is_train=True, image_size=IMAGE_SIZE)
    val_dataset   = HistologyDataset(val_df_split,   transforms=val_test_transforms, is_train=True, image_size=IMAGE_SIZE)

    sampler = make_weighted_sampler(train_df_split)
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        sampler=sampler,
        num_workers=N_WORKERS,
        pin_memory=cuda_is_available
    )
    val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE,
                              shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)

    # --- create fresh model for this fold ---
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=True,
        num_classes=N_CLASSES
    ).to(device)

    # --- Stage 1: freeze backbone, train classifier head ---
    print("\n--- Stage 1: Training classifier head ---")

    # --- 1.1. freeze feature extractor layers ---
    for param in model.parameters():
        param.requires_grad = False

    # 2) unfreeze classifier head (EffNetV2 uses .classifier)
    for param in model.classifier.parameters():
        param.requires_grad = True

    # --- 1.2. define loss, optimizer, scheduler ---
    criterion = nn.CrossEntropyLoss()
    head_params = [p for p in model.parameters() if p.requires_grad]
    optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=10
    )

    # --- 1.3. train for several epochs ---
    EPOCHS = 8
    best_f1 = 0.0
    best_state = None
    for epoch in range(1, EPOCHS+1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_loss, train_acc, train_f1 = train_one_epoch(
            model, train_loader, optimizer, criterion, device
        )
        val_loss, val_acc, val_f1 = validate(
            model, val_loader, criterion, device
        )
        scheduler.step()
        print(
            f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
            f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
        )
        if val_f1 > best_f1:
            best_f1 = val_f1
            best_state = model.state_dict().copy()
            torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
            print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

    if best_state is not None:
        model.load_state_dict(best_state)
        print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

    # --- Stage 2: unfreeze whole model, fine-tune ---
    print("\n--- Stage 2: Fine-tuning entire model ---")

    # --- 2.1. unfreeze entire model ---
    for param in model.parameters():
        param.requires_grad = True

    # --- 2.2. define loss, optimizer, scheduler ---
    optimizer = AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=15
    )

    # --- 2.3. mild class weights ---
    class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
    class_weights = (class_counts.sum() / class_counts)
    class_weights = class_weights / class_weights.mean()
    # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

    # --- 2.4. train for several epochs ---
    EPOCHS = 15
    best_f1 = 0.0
    best_state = None

    for epoch in range(1, EPOCHS + 1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_loss, train_acc, train_f1 = train_one_epoch(
            model, train_loader, optimizer, criterion, device
        )
        val_loss, val_acc, val_f1 = validate(
            model, val_loader, criterion, device
        )
        scheduler.step()
        print(
            f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
            f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
        )
        if val_f1 > best_f1:
            best_f1 = val_f1
            best_state = model.state_dict().copy()
            torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
            print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

    if best_state is not None:
        model.load_state_dict(best_state)   # restore best val-F1 weights

    # --- save model for this fold ---
    torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=3.9448 | F1(macro)=0.2748 | Acc=0.2781


Confusion matrix:
 [[31 43  4 11]
 [18 34 18 13]
 [27 30 13  9]
 [ 7 18  3  4]]
Train  loss=3.9448 acc=0.2781 f1=0.2748 | Val loss=5.5459 acc=0.2898 f1=0.2564
  🔥 New best F1: 0.2564 – model saved.

Epoch 2/8


    t_loss=3.4874 | F1(macro)=0.3113 | Acc=0.3109


Confusion matrix:
 [[30 34  9 16]
 [27 31 13 12]
 [22 25 14 18]
 [ 4 20  4  4]]
Train  loss=3.4874 acc=0.3109 f1=0.3113 | Val loss=5.3407 acc=0.2792 f1=0.2507

Epoch 3/8


    t_loss=3.2966 | F1(macro)=0.2824 | Acc=0.2834


Confusion matrix:
 [[18 37 22 12]
 [12 34 27 10]
 [10 32 29  8]
 [ 2 16 10  4]]
Train  loss=3.2966 acc=0.2834 f1=0.2824 | Val loss=4.9435 acc=0.3004 f1=0.2700
  🔥 New best F1: 0.2700 – model saved.

Epoch 4/8


    t_loss=2.9066 | F1(macro)=0.3206 | Acc=0.3215


Confusion matrix:
 [[35 30  7 17]
 [23 29 17 14]
 [29 24 15 11]
 [ 5 10  4 13]]
Train  loss=2.9066 acc=0.3215 f1=0.3206 | Val loss=4.7854 acc=0.3251 f1=0.3153
  🔥 New best F1: 0.3153 – model saved.

Epoch 5/8


    t_loss=2.9160 | F1(macro)=0.3186 | Acc=0.3189


Confusion matrix:
 [[18 35 11 25]
 [ 8 31 22 22]
 [11 29 18 21]
 [ 3 15  5  9]]
Train  loss=2.9160 acc=0.3189 f1=0.3186 | Val loss=5.4465 acc=0.2686 f1=0.2580

Epoch 6/8


    t_loss=2.7716 | F1(macro)=0.3195 | Acc=0.3206


Confusion matrix:
 [[22 52  6  9]
 [12 50 14  7]
 [12 41 16 10]
 [ 5 21  2  4]]
Train  loss=2.7716 acc=0.3206 f1=0.3195 | Val loss=5.3099 acc=0.3251 f1=0.2804

Epoch 7/8


    t_loss=2.8314 | F1(macro)=0.2929 | Acc=0.2941


Confusion matrix:
 [[29 20 10 30]
 [25 26 14 18]
 [24 15 20 20]
 [ 8 13  4  7]]
Train  loss=2.8314 acc=0.2941 f1=0.2929 | Val loss=4.7022 acc=0.2898 f1=0.2771

Epoch 8/8


    t_loss=2.6441 | F1(macro)=0.3363 | Acc=0.3348


Confusion matrix:
 [[14 30 10 35]
 [ 5 32 16 30]
 [15 22 17 25]
 [ 5 16  2  9]]
Train  loss=2.6441 acc=0.3348 f1=0.3363 | Val loss=5.0384 acc=0.2544 f1=0.2450
Restored best Stage 1 weights for fold 0 (F1=0.3153)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.8382 | F1(macro)=0.3081 | Acc=0.3153


Confusion matrix:
 [[12  7 26 44]
 [17 13 24 29]
 [12 11 24 32]
 [ 4  7  7 14]]
Train  loss=2.8382 acc=0.3153 f1=0.3081 | Val loss=3.1174 acc=0.2226 f1=0.2199
  🔥 New best F1: 0.2199 – model saved.

Epoch 2/15


    t_loss=1.9260 | F1(macro)=0.3407 | Acc=0.3463


Confusion matrix:
 [[ 6 45 19 19]
 [ 8 45 22  8]
 [ 9 36 20 14]
 [ 5 12  9  6]]
Train  loss=1.9260 acc=0.3463 f1=0.3407 | Val loss=2.4777 acc=0.2721 f1=0.2325
  🔥 New best F1: 0.2325 – model saved.

Epoch 3/15


    t_loss=1.4808 | F1(macro)=0.3711 | Acc=0.3853


Confusion matrix:
 [[ 8 15 16 50]
 [11 10 19 43]
 [10  6 20 43]
 [ 5  4  6 17]]
Train  loss=1.4808 acc=0.3853 f1=0.3711 | Val loss=2.0054 acc=0.1943 f1=0.1923

Epoch 4/15


    t_loss=1.3301 | F1(macro)=0.3779 | Acc=0.3977


Confusion matrix:
 [[53 10  7 19]
 [40 13 18 12]
 [48  8 16  7]
 [20  7  0  5]]
Train  loss=1.3301 acc=0.3977 f1=0.3779 | Val loss=1.8920 acc=0.3074 f1=0.2597
  🔥 New best F1: 0.2597 – model saved.

Epoch 5/15


    t_loss=1.2916 | F1(macro)=0.4260 | Acc=0.4376


Confusion matrix:
 [[10 14  6 59]
 [ 3 30  6 44]
 [ 3 14 15 47]
 [ 3  7  3 19]]
Train  loss=1.2916 acc=0.4376 f1=0.4260 | Val loss=1.8342 acc=0.2615 f1=0.2637
  🔥 New best F1: 0.2637 – model saved.

Epoch 6/15


    t_loss=1.2652 | F1(macro)=0.4369 | Acc=0.4464


Confusion matrix:
 [[10 18 12 49]
 [ 3 24 10 46]
 [ 6 10 20 43]
 [ 3  5  4 20]]
Train  loss=1.2652 acc=0.4464 f1=0.4369 | Val loss=1.7311 acc=0.2615 f1=0.2634

Epoch 7/15


    t_loss=1.1976 | F1(macro)=0.4536 | Acc=0.4659


Confusion matrix:
 [[14 37 13 25]
 [ 2 47  9 25]
 [ 9 34 15 21]
 [ 2 21  4  5]]
Train  loss=1.1976 acc=0.4659 f1=0.4536 | Val loss=1.7614 acc=0.2862 f1=0.2518

Epoch 8/15


    t_loss=1.1379 | F1(macro)=0.4670 | Acc=0.4880


Confusion matrix:
 [[ 6 22 10 51]
 [ 1 35  3 44]
 [ 4 17 13 45]
 [ 1  9  3 19]]
Train  loss=1.1379 acc=0.4880 f1=0.4670 | Val loss=1.9375 acc=0.2580 f1=0.2450

Epoch 9/15


    t_loss=1.1367 | F1(macro)=0.4639 | Acc=0.4801


Confusion matrix:
 [[10 40 16 23]
 [ 6 45 12 20]
 [ 7 38 14 20]
 [ 2 17  4  9]]
Train  loss=1.1367 acc=0.4801 f1=0.4639 | Val loss=1.8087 acc=0.2756 f1=0.2440

Epoch 10/15


    t_loss=1.0480 | F1(macro)=0.4970 | Acc=0.5235


Confusion matrix:
 [[12 24 14 39]
 [11 37 10 25]
 [16 22 15 26]
 [ 7 12  2 11]]
Train  loss=1.0480 acc=0.5235 f1=0.4970 | Val loss=1.7406 acc=0.2650 f1=0.2522

Epoch 11/15


    t_loss=1.0317 | F1(macro)=0.5201 | Acc=0.5376


Confusion matrix:
 [[ 7 27 16 39]
 [ 8 25 22 28]
 [ 9 22 18 30]
 [ 3 10  6 13]]
Train  loss=1.0317 acc=0.5376 f1=0.5201 | Val loss=1.7857 acc=0.2226 f1=0.2146

Epoch 12/15


    t_loss=1.0121 | F1(macro)=0.5381 | Acc=0.5616


Confusion matrix:
 [[13 36 15 25]
 [10 46  7 20]
 [12 28 17 22]
 [ 8 10  4 10]]
Train  loss=1.0121 acc=0.5616 f1=0.5381 | Val loss=1.7238 acc=0.3039 f1=0.2781
  🔥 New best F1: 0.2781 – model saved.

Epoch 13/15


    t_loss=1.0012 | F1(macro)=0.5506 | Acc=0.5651


Confusion matrix:
 [[21 35 12 21]
 [ 8 46  8 21]
 [16 31 17 15]
 [ 5 18  2  7]]
Train  loss=1.0012 acc=0.5651 f1=0.5506 | Val loss=1.7619 acc=0.3216 f1=0.2920
  🔥 New best F1: 0.2920 – model saved.

Epoch 14/15


    t_loss=1.0000 | F1(macro)=0.5554 | Acc=0.5695


Confusion matrix:
 [[10 25 17 37]
 [ 5 26 15 37]
 [ 7 21 20 31]
 [ 5  7  6 14]]
Train  loss=1.0000 acc=0.5695 f1=0.5554 | Val loss=1.8261 acc=0.2473 f1=0.2427

Epoch 15/15


    t_loss=0.9898 | F1(macro)=0.5493 | Acc=0.5642


Confusion matrix:
 [[15 31 18 25]
 [13 21 24 25]
 [18 24 16 21]
 [ 5 10  6 11]]
Train  loss=0.9898 acc=0.5642 f1=0.5493 | Val loss=1.8122 acc=0.2226 f1=0.2199

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.2692 | F1(macro)=0.2529 | Acc=0.2551


Confusion matrix:
 [[23  5 12 49]
 [16  8 13 46]
 [22 11 11 36]
 [ 7  1  4 19]]
Train  loss=4.2692 acc=0.2551 f1=0.2529 | Val loss=7.4641 acc=0.2155 f1=0.2086
  🔥 New best F1: 0.2086 – model saved.

Epoch 2/8


    t_loss=3.5602 | F1(macro)=0.2772 | Acc=0.2772


Confusion matrix:
 [[14  4 20 51]
 [ 6  5 27 45]
 [ 9 12 24 35]
 [ 1  1  4 25]]
Train  loss=3.5602 acc=0.2772 f1=0.2772 | Val loss=7.1105 acc=0.2403 f1=0.2269
  🔥 New best F1: 0.2269 – model saved.

Epoch 3/8


    t_loss=3.2043 | F1(macro)=0.3039 | Acc=0.3038


Confusion matrix:
 [[14  7 13 55]
 [ 7  5 24 47]
 [12 10 24 34]
 [ 3  0  8 20]]
Train  loss=3.2043 acc=0.3038 f1=0.3039 | Val loss=6.9791 acc=0.2226 f1=0.2138

Epoch 4/8


    t_loss=2.9787 | F1(macro)=0.3188 | Acc=0.3189


Confusion matrix:
 [[ 9 10 21 49]
 [ 4  7 27 45]
 [10 11 23 36]
 [ 2  1  2 26]]
Train  loss=2.9787 acc=0.3189 f1=0.3188 | Val loss=6.7481 acc=0.2297 f1=0.2154

Epoch 5/8


    t_loss=2.9085 | F1(macro)=0.3113 | Acc=0.3109


Confusion matrix:
 [[16  5 12 56]
 [11  6 20 46]
 [11  6 17 46]
 [ 2  0  7 22]]
Train  loss=2.9085 acc=0.3109 f1=0.3113 | Val loss=6.4053 acc=0.2155 f1=0.2092

Epoch 6/8


    t_loss=2.9858 | F1(macro)=0.2809 | Acc=0.2808


Confusion matrix:
 [[13  4 17 55]
 [ 8  8 17 50]
 [12 10 18 40]
 [ 2  1  6 22]]
Train  loss=2.9858 acc=0.2808 f1=0.2809 | Val loss=6.7334 acc=0.2155 f1=0.2109

Epoch 7/8


    t_loss=2.6544 | F1(macro)=0.3036 | Acc=0.3047


Confusion matrix:
 [[19  9 16 45]
 [ 9  7 21 46]
 [17 14 22 27]
 [ 5  2  6 18]]
Train  loss=2.6544 acc=0.3047 f1=0.3036 | Val loss=5.5769 acc=0.2332 f1=0.2285
  🔥 New best F1: 0.2285 – model saved.

Epoch 8/8


    t_loss=2.8510 | F1(macro)=0.3105 | Acc=0.3109


Confusion matrix:
 [[14 12 32 31]
 [ 3  6 27 47]
 [14 13 28 25]
 [ 5  2  7 17]]
Train  loss=2.8510 acc=0.3109 f1=0.3105 | Val loss=5.1942 acc=0.2297 f1=0.2186
Restored best Stage 1 weights for fold 1 (F1=0.2285)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.8302 | F1(macro)=0.2898 | Acc=0.3003


Confusion matrix:
 [[10  5 16 58]
 [16  9 16 42]
 [12  9 14 45]
 [ 9  1  4 17]]
Train  loss=2.8302 acc=0.3003 f1=0.2898 | Val loss=4.2613 acc=0.1767 f1=0.1767
  🔥 New best F1: 0.1767 – model saved.

Epoch 2/15


    t_loss=2.0083 | F1(macro)=0.3324 | Acc=0.3366


Confusion matrix:
 [[33 19  9 28]
 [27  8 23 25]
 [27 13 19 21]
 [14  5  2 10]]
Train  loss=2.0083 acc=0.3366 f1=0.3324 | Val loss=2.5285 acc=0.2473 f1=0.2330
  🔥 New best F1: 0.2330 – model saved.

Epoch 3/15


    t_loss=1.6208 | F1(macro)=0.3476 | Acc=0.3561


Confusion matrix:
 [[ 0 24 37 28]
 [ 0 16 49 18]
 [ 2 16 33 29]
 [ 0  4 19  8]]
Train  loss=1.6208 acc=0.3561 f1=0.3476 | Val loss=2.5450 acc=0.2014 f1=0.1667

Epoch 4/15


    t_loss=1.4489 | F1(macro)=0.3806 | Acc=0.3933


Confusion matrix:
 [[ 7 17 59  6]
 [ 4 10 63  6]
 [ 5 11 53 11]
 [ 4  3 20  4]]
Train  loss=1.4489 acc=0.3933 f1=0.3806 | Val loss=2.0375 acc=0.2615 f1=0.2033

Epoch 5/15


    t_loss=1.3791 | F1(macro)=0.3752 | Acc=0.3853


Confusion matrix:
 [[ 0 20 13 56]
 [ 1 27 13 42]
 [ 1 26 14 39]
 [ 0  7  5 19]]
Train  loss=1.3791 acc=0.3853 f1=0.3752 | Val loss=2.1067 acc=0.2120 f1=0.1896

Epoch 6/15


    t_loss=1.2523 | F1(macro)=0.4257 | Acc=0.4438


Confusion matrix:
 [[ 8 34 10 37]
 [ 8 37  5 33]
 [ 4 35 16 25]
 [ 1 12  1 17]]
Train  loss=1.2523 acc=0.4438 f1=0.4257 | Val loss=1.7464 acc=0.2756 f1=0.2593
  🔥 New best F1: 0.2593 – model saved.

Epoch 7/15


    t_loss=1.2079 | F1(macro)=0.4287 | Acc=0.4517


Confusion matrix:
 [[11  3 43 32]
 [ 6  7 46 24]
 [ 4  4 41 31]
 [ 4  1 14 12]]
Train  loss=1.2079 acc=0.4517 f1=0.4287 | Val loss=1.7974 acc=0.2509 f1=0.2216

Epoch 8/15


    t_loss=1.1778 | F1(macro)=0.4502 | Acc=0.4650


Confusion matrix:
 [[25 14 17 33]
 [13 13 30 27]
 [15 12 29 24]
 [ 7  6  7 11]]
Train  loss=1.1778 acc=0.4650 f1=0.4502 | Val loss=1.6924 acc=0.2756 f1=0.2673
  🔥 New best F1: 0.2673 – model saved.

Epoch 9/15


    t_loss=1.1475 | F1(macro)=0.4699 | Acc=0.4889


Confusion matrix:
 [[21 23 14 31]
 [16 22 19 26]
 [18 17 23 22]
 [ 7  7  4 13]]
Train  loss=1.1475 acc=0.4889 f1=0.4699 | Val loss=1.7126 acc=0.2792 f1=0.2769
  🔥 New best F1: 0.2769 – model saved.

Epoch 10/15


    t_loss=1.1134 | F1(macro)=0.5185 | Acc=0.5270


Confusion matrix:
 [[10 41  9 29]
 [10 40 15 18]
 [ 8 35 15 22]
 [ 7 12  4  8]]
Train  loss=1.1134 acc=0.5270 f1=0.5185 | Val loss=1.7627 acc=0.2580 f1=0.2331

Epoch 11/15


    t_loss=1.0169 | F1(macro)=0.5299 | Acc=0.5509


Confusion matrix:
 [[12 33 10 34]
 [10 39 11 23]
 [ 7 29 19 25]
 [ 3  9  6 13]]
Train  loss=1.0169 acc=0.5509 f1=0.5299 | Val loss=1.6912 acc=0.2933 f1=0.2776
  🔥 New best F1: 0.2776 – model saved.

Epoch 12/15


    t_loss=1.0220 | F1(macro)=0.5392 | Acc=0.5545


Confusion matrix:
 [[12 42 10 25]
 [ 6 45 11 21]
 [ 6 38 18 18]
 [ 3 17  2  9]]
Train  loss=1.0220 acc=0.5545 f1=0.5392 | Val loss=1.7642 acc=0.2968 f1=0.2694

Epoch 13/15


    t_loss=1.0278 | F1(macro)=0.5418 | Acc=0.5518


Confusion matrix:
 [[23 25 10 31]
 [20 26 13 24]
 [16 26 15 23]
 [ 4 11  2 14]]
Train  loss=1.0278 acc=0.5518 f1=0.5418 | Val loss=1.7874 acc=0.2756 f1=0.2711

Epoch 14/15


    t_loss=0.9612 | F1(macro)=0.5797 | Acc=0.5943


Confusion matrix:
 [[14 39  7 29]
 [12 42  7 22]
 [ 8 31 12 29]
 [ 5 11  2 13]]
Train  loss=0.9612 acc=0.5943 f1=0.5797 | Val loss=1.8049 acc=0.2862 f1=0.2646

Epoch 15/15


    t_loss=1.0236 | F1(macro)=0.5705 | Acc=0.5802


Confusion matrix:
 [[18 28  6 37]
 [11 30 11 31]
 [15 26 13 26]
 [ 5  7  3 16]]
Train  loss=1.0236 acc=0.5802 f1=0.5705 | Val loss=1.7835 acc=0.2721 f1=0.2657

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.3089 | F1(macro)=0.2656 | Acc=0.2664


Confusion matrix:
 [[23 34  7 25]
 [11 32 24 15]
 [23 28 13 16]
 [ 9 14  3  5]]
Train  loss=4.3089 acc=0.2664 f1=0.2656 | Val loss=5.0448 acc=0.2589 f1=0.2368
  🔥 New best F1: 0.2368 – model saved.

Epoch 2/8


    t_loss=3.3363 | F1(macro)=0.2686 | Acc=0.2690


Confusion matrix:
 [[19 47  6 17]
 [ 9 33 25 15]
 [20 29 14 17]
 [ 6 17  2  6]]
Train  loss=3.3363 acc=0.2690 f1=0.2686 | Val loss=5.4126 acc=0.2553 f1=0.2358

Epoch 3/8


    t_loss=3.1095 | F1(macro)=0.2628 | Acc=0.2628


Confusion matrix:
 [[30 30 11 18]
 [13 25 29 15]
 [24 25 13 18]
 [11  9  8  3]]
Train  loss=3.1095 acc=0.2628 f1=0.2628 | Val loss=5.0538 acc=0.2518 f1=0.2267

Epoch 4/8


    t_loss=3.0371 | F1(macro)=0.2725 | Acc=0.2735


Confusion matrix:
 [[23 37 10 19]
 [ 7 33 25 17]
 [11 37 17 15]
 [ 4 15  7  5]]
Train  loss=3.0371 acc=0.2735 f1=0.2725 | Val loss=4.4825 acc=0.2766 f1=0.2566
  🔥 New best F1: 0.2566 – model saved.

Epoch 5/8


    t_loss=2.9361 | F1(macro)=0.2828 | Acc=0.2832


Confusion matrix:
 [[29 27  2 31]
 [12 39  8 23]
 [17 27  8 28]
 [ 9 13  2  7]]
Train  loss=2.9361 acc=0.2832 f1=0.2828 | Val loss=4.9566 acc=0.2943 f1=0.2658
  🔥 New best F1: 0.2658 – model saved.

Epoch 6/8


    t_loss=2.7741 | F1(macro)=0.2922 | Acc=0.2938


Confusion matrix:
 [[26 31 11 21]
 [ 7 37 21 17]
 [13 34 16 17]
 [ 9 15  3  4]]
Train  loss=2.7741 acc=0.2938 f1=0.2922 | Val loss=4.5711 acc=0.2943 f1=0.2665
  🔥 New best F1: 0.2665 – model saved.

Epoch 7/8


    t_loss=2.8583 | F1(macro)=0.2795 | Acc=0.2814


Confusion matrix:
 [[20 30 16 23]
 [12 39 20 11]
 [20 31 18 11]
 [ 4 15  7  5]]
Train  loss=2.8583 acc=0.2814 f1=0.2795 | Val loss=4.0203 acc=0.2908 f1=0.2626

Epoch 8/8


    t_loss=2.6935 | F1(macro)=0.2898 | Acc=0.2903


Confusion matrix:
 [[22 32 11 24]
 [ 7 36 16 23]
 [16 32 16 16]
 [ 7 15  5  4]]
Train  loss=2.6935 acc=0.2903 f1=0.2898 | Val loss=4.1109 acc=0.2766 f1=0.2523
Restored best Stage 1 weights for fold 2 (F1=0.2665)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.5178 | F1(macro)=0.3086 | Acc=0.3168


Confusion matrix:
 [[35 27  7 20]
 [26 23 19 14]
 [31 21 16 12]
 [18  6  3  4]]
Train  loss=2.5178 acc=0.3168 f1=0.3086 | Val loss=3.0980 acc=0.2766 f1=0.2490
  🔥 New best F1: 0.2490 – model saved.

Epoch 2/15


    t_loss=1.8041 | F1(macro)=0.3370 | Acc=0.3460


Confusion matrix:
 [[ 8 43 12 26]
 [10 22 24 26]
 [13 16 21 30]
 [ 6 12  5  8]]
Train  loss=1.8041 acc=0.3460 f1=0.3370 | Val loss=2.1828 acc=0.2092 f1=0.2016

Epoch 3/15


    t_loss=1.5254 | F1(macro)=0.3573 | Acc=0.3637


Confusion matrix:
 [[48  6 23 12]
 [30  6 36 10]
 [34  2 37  7]
 [22  0  7  2]]
Train  loss=1.5254 acc=0.3637 f1=0.3573 | Val loss=2.0172 acc=0.3298 f1=0.2561
  🔥 New best F1: 0.2561 – model saved.

Epoch 4/15


    t_loss=1.3837 | F1(macro)=0.3564 | Acc=0.3823


Confusion matrix:
 [[25  5 30 29]
 [19 17 26 20]
 [18  4 37 21]
 [10  1  7 13]]
Train  loss=1.3837 acc=0.3823 f1=0.3564 | Val loss=1.6920 acc=0.3262 f1=0.3154
  🔥 New best F1: 0.3154 – model saved.

Epoch 5/15


    t_loss=1.2916 | F1(macro)=0.3741 | Acc=0.3991


Confusion matrix:
 [[34  6 33 16]
 [19 22 30 11]
 [24  5 42  9]
 [12  0 13  6]]
Train  loss=1.2916 acc=0.3991 f1=0.3741 | Val loss=1.5678 acc=0.3688 f1=0.3383
  🔥 New best F1: 0.3383 – model saved.

Epoch 6/15


    t_loss=1.2519 | F1(macro)=0.4007 | Acc=0.4221


Confusion matrix:
 [[29 13 37 10]
 [13 23 38  8]
 [18 11 43  8]
 [13  3  8  7]]
Train  loss=1.2519 acc=0.4221 f1=0.4007 | Val loss=1.5737 acc=0.3617 f1=0.3357

Epoch 7/15


    t_loss=1.2002 | F1(macro)=0.4153 | Acc=0.4381


Confusion matrix:
 [[19  8 58  4]
 [12 16 50  4]
 [15 10 51  4]
 [ 7  2 15  7]]
Train  loss=1.2002 acc=0.4381 f1=0.4153 | Val loss=1.7189 acc=0.3298 f1=0.3051

Epoch 8/15


    t_loss=1.1343 | F1(macro)=0.4498 | Acc=0.4708


Confusion matrix:
 [[27 13 28 21]
 [16 23 24 19]
 [23 10 32 15]
 [10  3  7 11]]
Train  loss=1.1343 acc=0.4708 f1=0.4498 | Val loss=1.5740 acc=0.3298 f1=0.3199

Epoch 9/15


    t_loss=1.1605 | F1(macro)=0.4603 | Acc=0.4708


Confusion matrix:
 [[50  8 13 18]
 [26 21 24 11]
 [37  6 20 17]
 [18  1  4  8]]
Train  loss=1.1605 acc=0.4708 f1=0.4603 | Val loss=1.6166 acc=0.3511 f1=0.3206

Epoch 10/15


    t_loss=1.1064 | F1(macro)=0.4665 | Acc=0.4867


Confusion matrix:
 [[29  5 26 29]
 [11 31 21 19]
 [22 11 27 20]
 [10  3  5 13]]
Train  loss=1.1064 acc=0.4867 f1=0.4665 | Val loss=1.5744 acc=0.3546 f1=0.3504
  🔥 New best F1: 0.3504 – model saved.

Epoch 11/15


    t_loss=1.0927 | F1(macro)=0.4837 | Acc=0.4956


Confusion matrix:
 [[48  3 20 18]
 [30 22 15 15]
 [32  3 30 15]
 [16  1  3 11]]
Train  loss=1.0927 acc=0.4956 f1=0.4837 | Val loss=1.5543 acc=0.3936 f1=0.3732
  🔥 New best F1: 0.3732 – model saved.

Epoch 12/15


    t_loss=1.0662 | F1(macro)=0.5127 | Acc=0.5283


Confusion matrix:
 [[45  4 19 21]
 [25 27 16 14]
 [33  4 28 15]
 [16  0  6  9]]
Train  loss=1.0662 acc=0.5283 f1=0.5127 | Val loss=1.5752 acc=0.3865 f1=0.3675

Epoch 13/15


    t_loss=0.9745 | F1(macro)=0.5579 | Acc=0.5770


Confusion matrix:
 [[44 10 15 20]
 [24 29 16 13]
 [32  9 23 16]
 [18  1  2 10]]
Train  loss=0.9745 acc=0.5770 f1=0.5579 | Val loss=1.6201 acc=0.3759 f1=0.3571

Epoch 14/15


    t_loss=0.9808 | F1(macro)=0.5573 | Acc=0.5761


Confusion matrix:
 [[36  8 20 25]
 [24 32 13 13]
 [28  8 28 16]
 [18  3  1  9]]
Train  loss=0.9808 acc=0.5761 f1=0.5573 | Val loss=1.5977 acc=0.3723 f1=0.3591

Epoch 15/15


    t_loss=0.9803 | F1(macro)=0.5705 | Acc=0.5876


Confusion matrix:
 [[41  6 20 22]
 [24 26 17 15]
 [34  8 26 12]
 [12  4  4 11]]
Train  loss=0.9803 acc=0.5876 f1=0.5705 | Val loss=1.6263 acc=0.3688 f1=0.3545

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=4.4204 | F1(macro)=0.2745 | Acc=0.2743


Confusion matrix:
 [[56  5  9 19]
 [40  9 17 17]
 [30 15  9 25]
 [20  2  4  5]]
Train  loss=4.4204 acc=0.2743 f1=0.2745 | Val loss=6.1011 acc=0.2801 f1=0.2225
  🔥 New best F1: 0.2225 – model saved.

Epoch 2/8


    t_loss=3.5910 | F1(macro)=0.2663 | Acc=0.2681


Confusion matrix:
 [[47  8  6 28]
 [34  6 23 20]
 [31  7 15 26]
 [16  3  4  8]]
Train  loss=3.5910 acc=0.2681 f1=0.2663 | Val loss=6.0447 acc=0.2695 f1=0.2308
  🔥 New best F1: 0.2308 – model saved.

Epoch 3/8


    t_loss=3.3149 | F1(macro)=0.2742 | Acc=0.2743


Confusion matrix:
 [[44  5 13 27]
 [40  5 18 20]
 [29 10 14 26]
 [20  4  4  3]]
Train  loss=3.3149 acc=0.2743 f1=0.2742 | Val loss=5.6154 acc=0.2340 f1=0.1912

Epoch 4/8


    t_loss=3.0854 | F1(macro)=0.2906 | Acc=0.2920


Confusion matrix:
 [[25  6 16 42]
 [24  3 24 32]
 [27  6 17 29]
 [12  2  5 12]]
Train  loss=3.0854 acc=0.2920 f1=0.2906 | Val loss=5.7273 acc=0.2021 f1=0.1870

Epoch 5/8


    t_loss=2.8382 | F1(macro)=0.2977 | Acc=0.2982


Confusion matrix:
 [[21  9 18 41]
 [16  5 28 34]
 [17  4 14 44]
 [ 8  4  6 13]]
Train  loss=2.8382 acc=0.2982 f1=0.2977 | Val loss=5.8689 acc=0.1879 f1=0.1815

Epoch 6/8


    t_loss=2.9112 | F1(macro)=0.2716 | Acc=0.2735


Confusion matrix:
 [[35 12  6 36]
 [29  7 16 31]
 [25  8  9 37]
 [12  2  3 14]]
Train  loss=2.9112 acc=0.2735 f1=0.2716 | Val loss=5.3819 acc=0.2305 f1=0.2102

Epoch 7/8


    t_loss=2.8463 | F1(macro)=0.2808 | Acc=0.2814


Confusion matrix:
 [[32  8 14 35]
 [26  7 19 31]
 [23  7 13 36]
 [15  4  4  8]]
Train  loss=2.8463 acc=0.2814 f1=0.2808 | Val loss=5.1769 acc=0.2128 f1=0.1974

Epoch 8/8


    t_loss=2.8031 | F1(macro)=0.2625 | Acc=0.2637


Confusion matrix:
 [[28 10 11 40]
 [22  7 13 41]
 [22  6  7 44]
 [11  5  3 12]]
Train  loss=2.8031 acc=0.2637 f1=0.2625 | Val loss=5.3625 acc=0.1915 f1=0.1796
Restored best Stage 1 weights for fold 3 (F1=0.2308)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.7462 | F1(macro)=0.3096 | Acc=0.3150


Confusion matrix:
 [[16 22 12 39]
 [13 14 32 24]
 [ 9 13 18 39]
 [ 5  8 11  7]]
Train  loss=2.7462 acc=0.3150 f1=0.3096 | Val loss=3.7238 acc=0.1950 f1=0.1948
  🔥 New best F1: 0.1948 – model saved.

Epoch 2/15


    t_loss=1.9745 | F1(macro)=0.3376 | Acc=0.3425


Confusion matrix:
 [[38 13 16 22]
 [24 19 21 19]
 [19 10 27 23]
 [17  4  2  8]]
Train  loss=1.9745 acc=0.3425 f1=0.3376 | Val loss=2.2877 acc=0.3262 f1=0.3072
  🔥 New best F1: 0.3072 – model saved.

Epoch 3/15


    t_loss=1.6619 | F1(macro)=0.3673 | Acc=0.3796


Confusion matrix:
 [[ 9 24 29 27]
 [ 8 27 28 20]
 [ 7 23 32 17]
 [ 4  8 10  9]]
Train  loss=1.6619 acc=0.3796 f1=0.3673 | Val loss=1.9661 acc=0.2730 f1=0.2534

Epoch 4/15


    t_loss=1.4495 | F1(macro)=0.3717 | Acc=0.3858


Confusion matrix:
 [[10 22 10 47]
 [12 14 18 39]
 [11 12 19 37]
 [ 7  6  5 13]]
Train  loss=1.4495 acc=0.3858 f1=0.3717 | Val loss=1.9080 acc=0.1986 f1=0.2013

Epoch 5/15


    t_loss=1.3522 | F1(macro)=0.3799 | Acc=0.3973


Confusion matrix:
 [[26  0 23 40]
 [19 12 15 37]
 [16  4 13 46]
 [10  0  2 19]]
Train  loss=1.3522 acc=0.3973 f1=0.3799 | Val loss=1.9261 acc=0.2482 f1=0.2460

Epoch 6/15


    t_loss=1.3397 | F1(macro)=0.3885 | Acc=0.4009


Confusion matrix:
 [[46  1 11 31]
 [36  3 14 30]
 [23  3 16 37]
 [13  0  7 11]]
Train  loss=1.3397 acc=0.4009 f1=0.3885 | Val loss=1.8261 acc=0.2695 f1=0.2301

Epoch 7/15


    t_loss=1.2124 | F1(macro)=0.4119 | Acc=0.4292


Confusion matrix:
 [[10  1 25 53]
 [13  8 33 29]
 [ 7  4 41 27]
 [ 3  0 11 17]]
Train  loss=1.2124 acc=0.4292 f1=0.4119 | Val loss=1.7251 acc=0.2695 f1=0.2453

Epoch 8/15


    t_loss=1.1866 | F1(macro)=0.4456 | Acc=0.4628


Confusion matrix:
 [[25 21 12 31]
 [25 16 21 21]
 [16 14 23 26]
 [14  3  3 11]]
Train  loss=1.1866 acc=0.4628 f1=0.4456 | Val loss=1.7347 acc=0.2660 f1=0.2615

Epoch 9/15


    t_loss=1.1183 | F1(macro)=0.4710 | Acc=0.4912


Confusion matrix:
 [[29  6 27 27]
 [22 17 24 20]
 [15  9 35 20]
 [12  3  4 12]]
Train  loss=1.1183 acc=0.4912 f1=0.4710 | Val loss=1.6056 acc=0.3298 f1=0.3170
  🔥 New best F1: 0.3170 – model saved.

Epoch 10/15


    t_loss=1.0921 | F1(macro)=0.5181 | Acc=0.5301


Confusion matrix:
 [[18  4 34 33]
 [17 10 35 21]
 [ 9  8 39 23]
 [ 5  2 11 13]]
Train  loss=1.0921 acc=0.5301 f1=0.5181 | Val loss=1.7322 acc=0.2837 f1=0.2642

Epoch 11/15


    t_loss=1.0967 | F1(macro)=0.5282 | Acc=0.5345


Confusion matrix:
 [[13 13 52 11]
 [13 11 52  7]
 [12  9 52  6]
 [ 9  1 15  6]]
Train  loss=1.0967 acc=0.5345 f1=0.5282 | Val loss=1.8516 acc=0.2908 f1=0.2480

Epoch 12/15


    t_loss=1.1010 | F1(macro)=0.5067 | Acc=0.5186


Confusion matrix:
 [[18  6 38 27]
 [22 10 38 13]
 [13  5 47 14]
 [10  1 10 10]]
Train  loss=1.1010 acc=0.5186 f1=0.5067 | Val loss=1.7126 acc=0.3014 f1=0.2703

Epoch 13/15


    t_loss=1.0707 | F1(macro)=0.5121 | Acc=0.5221


Confusion matrix:
 [[33  7 25 24]
 [30 12 24 17]
 [22  7 24 26]
 [10  2  6 13]]
Train  loss=1.0707 acc=0.5221 f1=0.5121 | Val loss=1.6607 acc=0.2908 f1=0.2782

Epoch 14/15


    t_loss=1.0142 | F1(macro)=0.5419 | Acc=0.5558


Confusion matrix:
 [[25  3 45 16]
 [26  8 37 12]
 [18  4 41 16]
 [10  1  9 11]]
Train  loss=1.0142 acc=0.5558 f1=0.5419 | Val loss=1.7648 acc=0.3014 f1=0.2759

Epoch 15/15


    t_loss=0.9933 | F1(macro)=0.5607 | Acc=0.5788


Confusion matrix:
 [[30  5 28 26]
 [30 11 33  9]
 [21  6 38 14]
 [12  2  9  8]]
Train  loss=0.9933 acc=0.5788 f1=0.5607 | Val loss=1.6967 acc=0.3085 f1=0.2809

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=3.9871 | F1(macro)=0.2836 | Acc=0.2841


Confusion matrix:
 [[46 14  7 22]
 [39 24 14  6]
 [48 14  7 10]
 [14 10  3  4]]
Train  loss=3.9871 acc=0.2841 f1=0.2836 | Val loss=6.0307 acc=0.2872 f1=0.2394
  🔥 New best F1: 0.2394 – model saved.

Epoch 2/8


    t_loss=3.4718 | F1(macro)=0.2752 | Acc=0.2752


Confusion matrix:
 [[34 12 16 27]
 [30 16 21 16]
 [33  8 20 18]
 [11  3  7 10]]
Train  loss=3.4718 acc=0.2752 f1=0.2752 | Val loss=5.0547 acc=0.2837 f1=0.2708
  🔥 New best F1: 0.2708 – model saved.

Epoch 3/8


    t_loss=3.1920 | F1(macro)=0.2830 | Acc=0.2832


Confusion matrix:
 [[48 10 20 11]
 [42 15 22  4]
 [47  3 24  5]
 [18  1  9  3]]
Train  loss=3.1920 acc=0.2832 f1=0.2830 | Val loss=5.2211 acc=0.3191 f1=0.2710
  🔥 New best F1: 0.2710 – model saved.

Epoch 4/8


    t_loss=3.1199 | F1(macro)=0.2850 | Acc=0.2867


Confusion matrix:
 [[53  9  9 18]
 [51 13 13  6]
 [49  3 15 12]
 [21  1  3  6]]
Train  loss=3.1199 acc=0.2867 f1=0.2850 | Val loss=5.2395 acc=0.3085 f1=0.2645

Epoch 5/8


    t_loss=2.9770 | F1(macro)=0.2962 | Acc=0.2965


Confusion matrix:
 [[61  5 12 11]
 [51 11 14  7]
 [54  5 13  7]
 [22  3  4  2]]
Train  loss=2.9770 acc=0.2965 f1=0.2962 | Val loss=5.4973 acc=0.3085 f1=0.2320

Epoch 6/8


    t_loss=2.7428 | F1(macro)=0.3022 | Acc=0.3035


Confusion matrix:
 [[53 14  7 15]
 [47 17 12  7]
 [46  7 13 13]
 [17  6  5  3]]
Train  loss=2.7428 acc=0.3035 f1=0.3022 | Val loss=5.2077 acc=0.3050 f1=0.2499

Epoch 7/8


    t_loss=2.6583 | F1(macro)=0.3080 | Acc=0.3080


Confusion matrix:
 [[46 15 12 16]
 [37 14 24  8]
 [35 13 17 14]
 [17  3  6  5]]
Train  loss=2.6583 acc=0.3080 f1=0.3080 | Val loss=4.2778 acc=0.2908 f1=0.2527

Epoch 8/8


    t_loss=2.6667 | F1(macro)=0.3102 | Acc=0.3106


Confusion matrix:
 [[48 16  9 16]
 [45 18 13  7]
 [49  9  9 12]
 [18  5  4  4]]
Train  loss=2.6667 acc=0.3106 f1=0.3102 | Val loss=4.7531 acc=0.2801 f1=0.2331
Restored best Stage 1 weights for fold 4 (F1=0.2710)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/15


    t_loss=2.5300 | F1(macro)=0.2780 | Acc=0.2832


Confusion matrix:
 [[61 10  3 15]
 [41 13  8 21]
 [40  8 14 17]
 [15  6  4  6]]
Train  loss=2.5300 acc=0.2832 f1=0.2780 | Val loss=2.6622 acc=0.3333 f1=0.2763
  🔥 New best F1: 0.2763 – model saved.

Epoch 2/15


    t_loss=1.6970 | F1(macro)=0.3422 | Acc=0.3469


Confusion matrix:
 [[45  6  0 38]
 [30 17  2 34]
 [28 13  5 33]
 [14  3  0 14]]
Train  loss=1.6970 acc=0.3469 f1=0.3422 | Val loss=2.4524 acc=0.2872 f1=0.2546

Epoch 3/15


    t_loss=1.4605 | F1(macro)=0.3587 | Acc=0.3699


Confusion matrix:
 [[45 10  4 30]
 [41  5 17 20]
 [33  5 19 22]
 [15  2  5  9]]
Train  loss=1.4605 acc=0.3699 f1=0.3587 | Val loss=1.8891 acc=0.2766 f1=0.2415

Epoch 4/15


    t_loss=1.3365 | F1(macro)=0.3435 | Acc=0.3752


Confusion matrix:
 [[39 11  5 34]
 [39  8 19 17]
 [24 12 16 27]
 [15  2  3 11]]
Train  loss=1.3365 acc=0.3752 f1=0.3435 | Val loss=1.7924 acc=0.2624 f1=0.2406

Epoch 5/15


    t_loss=1.2966 | F1(macro)=0.3522 | Acc=0.3841


Confusion matrix:
 [[27  6 11 45]
 [22  5 21 35]
 [14 11 18 36]
 [ 7  6  4 14]]
Train  loss=1.2966 acc=0.3841 f1=0.3522 | Val loss=1.7163 acc=0.2270 f1=0.2186

Epoch 6/15


    t_loss=1.2259 | F1(macro)=0.4020 | Acc=0.4248


Confusion matrix:
 [[32  8  5 44]
 [22 17 10 34]
 [18 13 10 38]
 [13  4  1 13]]
Train  loss=1.2259 acc=0.4248 f1=0.4020 | Val loss=1.6487 acc=0.2553 f1=0.2482

Epoch 7/15


    t_loss=1.2281 | F1(macro)=0.4352 | Acc=0.4460


Confusion matrix:
 [[48  3 16 22]
 [42 12 16 13]
 [32  3 27 17]
 [14  1  6 10]]
Train  loss=1.2281 acc=0.4460 f1=0.4352 | Val loss=1.6080 acc=0.3440 f1=0.3130
  🔥 New best F1: 0.3130 – model saved.

Epoch 8/15


    t_loss=1.1719 | F1(macro)=0.4245 | Acc=0.4504


Confusion matrix:
 [[34  1 16 38]
 [26 12 24 21]
 [26  3 28 22]
 [13  1  6 11]]
Train  loss=1.1719 acc=0.4504 f1=0.4245 | Val loss=1.6443 acc=0.3014 f1=0.2866

Epoch 9/15


    t_loss=1.1694 | F1(macro)=0.4432 | Acc=0.4628


Confusion matrix:
 [[23 11 13 42]
 [20 18 14 31]
 [13 10 22 34]
 [ 7  6  5 13]]
Train  loss=1.1694 acc=0.4628 f1=0.4432 | Val loss=1.6129 acc=0.2695 f1=0.2717

Epoch 10/15


    t_loss=1.0944 | F1(macro)=0.4936 | Acc=0.5088


Confusion matrix:
 [[29  8 10 42]
 [25 14 11 33]
 [23  5 20 31]
 [ 9  2  2 18]]
Train  loss=1.0944 acc=0.5088 f1=0.4936 | Val loss=1.6932 acc=0.2872 f1=0.2854

Epoch 11/15


    t_loss=1.0837 | F1(macro)=0.4971 | Acc=0.5097


Confusion matrix:
 [[24 19 10 36]
 [18 31 13 21]
 [ 9 25 21 24]
 [ 9 10  2 10]]
Train  loss=1.0837 acc=0.5097 f1=0.4971 | Val loss=1.6942 acc=0.3050 f1=0.2978

Epoch 12/15


    t_loss=1.0515 | F1(macro)=0.5402 | Acc=0.5522


Confusion matrix:
 [[21 13 12 43]
 [18 25 13 27]
 [15 13 22 29]
 [ 8  8  1 14]]
Train  loss=1.0515 acc=0.5522 f1=0.5402 | Val loss=1.6619 acc=0.2908 f1=0.2928

Epoch 13/15


    t_loss=1.0346 | F1(macro)=0.5611 | Acc=0.5673


Confusion matrix:
 [[27 13  9 40]
 [23 23  9 28]
 [22 12 15 30]
 [10  9  1 11]]
Train  loss=1.0346 acc=0.5673 f1=0.5611 | Val loss=1.7799 acc=0.2695 f1=0.2667

Epoch 14/15


    t_loss=1.0157 | F1(macro)=0.5428 | Acc=0.5531


Confusion matrix:
 [[32  6 10 41]
 [29 16 13 25]
 [24  2 26 27]
 [12  3  4 12]]
Train  loss=1.0157 acc=0.5531 f1=0.5428 | Val loss=1.7075 acc=0.3050 f1=0.3014

Epoch 15/15


    t_loss=0.9912 | F1(macro)=0.5753 | Acc=0.5850


Confusion matrix:
 [[25 15 10 39]
 [27 22  9 25]
 [23  9 22 25]
 [10  5  4 12]]
Train  loss=0.9912 acc=0.5850 f1=0.5753 | Val loss=1.7171 acc=0.2872 f1=0.2881


In [3]:
test_dataset = HistologyDataset(
    test_df,
    transforms=val_test_transforms,
    is_train=False,   # returns (img, sample_index)
    image_size=IMAGE_SIZE
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

all_fold_probs = []   # list of arrays [N, num_classes]
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model")

    # recreate model and load weights
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=False,
        num_classes=N_CLASSES
    ).to(device)
    state = torch.load(f"effv2_s_fold{fold}.pth", map_location=device)
    model.load_state_dict(state)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for imgs, sample_indices in test_loader:
            imgs = imgs.to(device, non_blocking=True)

            logits = model(imgs)               # [B, num_classes]
            probs = softmax(logits, dim=1)     # [B, num_classes]
            fold_probs.append(probs.cpu().numpy())

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.extend(sample_indices)

    fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
    all_fold_probs.append(fold_probs)

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# average probabilities across folds
mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
pred_indices = mean_probs.argmax(axis=1)

pred_labels = [idx2label[int(i)] for i in pred_indices]
sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})

submission_df.to_csv("submission_5fold_no_tta.csv", index=False)
print("Saved submission_5fold_no_tta.csv")
print(submission_df.head())


Inference with fold 0 model
Inference with fold 1 model
Inference with fold 2 model
Inference with fold 3 model
Inference with fold 4 model
Saved submission_5fold_no_tta.csv
   sample_index            label
0  img_0000.png          HER2(+)
1  img_0001.png  Triple negative
2  img_0002.png  Triple negative
3  img_0003.png  Triple negative
4  img_0004.png        Luminal B


In [4]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
# all_fold_probs = []
# all_sample_indices = None
#
# test_dataset = HistologyDataset(test_df, transforms=val_test_transforms, is_train=False, image_size=IMAGE_SIZE)
# test_loader = DataLoader(test_dataset, batch_size=1,  # IMPORTANT: batch_size=1 for per-image TTA
#                          shuffle=False, num_workers=N_WORKERS, pin_memory=cuda_is_available)
#
# for fold in range(N_FOLDS):
#     print(f"Inference with fold {fold} model")
#     model = timm.create_model(PRETRAINED_MODEL, pretrained=False, num_classes=N_CLASSES).to(device)
#     model.load_state_dict(torch.load(f"effv2_s_fold{fold}.pth", map_location=device))
#     model.eval()
#
#     fold_probs = []
#     sample_indices_list = []
#
#     with torch.no_grad():
#         for img_tensor, sample_idx in test_loader:
#             img_tensor = img_tensor.squeeze(0)  # [3,H,W]
#             img_tensor = img_tensor.to(device)
#
#             # -------- TTA: apply multiple augmented views --------
#             tta_tensors = apply_tta(img_tensor)
#
#             # accumulate probability predictions
#             probs_sum = 0
#             for aug_img in tta_tensors:
#                 aug_img = aug_img.unsqueeze(0).to(device)  # [1,3,H,W]
#                 logits = model(aug_img)
#                 probs = softmax(logits, dim=1)  # [1,4]
#                 probs_sum += probs[0].cpu().numpy()
#
#             # average across TTA views
#             avg_probs = probs_sum / len(tta_tensors)
#             fold_probs.append(avg_probs)
#
#             if all_sample_indices is None:
#                 sample_indices_list.append(sample_idx[0])
#
#     fold_probs = np.vstack(fold_probs)  # [N, 4]
#     all_fold_probs.append(fold_probs)
#
#     if all_sample_indices is None:
#         all_sample_indices = sample_indices_list
#
# mean_probs = np.mean(all_fold_probs, axis=0)  # [N, 4]
# pred_indices = mean_probs.argmax(axis=1)
# pred_labels = [idx2label[int(i)] for i in pred_indices]
#
# sample_index_with_ext = [
#     f"{si}.png" if not si.endswith(".png") else si
#     for si in all_sample_indices
# ]
#
# submission_df = pd.DataFrame({
#     "sample_index": sample_index_with_ext,
#     "label": pred_labels
# })
# submission_df.to_csv("submission_5fold_tta.csv", index=False)
#
# print("Saved submission_5fold_tta.csv")

In [5]:
from internal.nn.test_time_augmentation import apply_tta
from sklearn.metrics import f1_score
from torch.nn.functional import softmax

def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(val_df_split, transforms=val_test_transforms, is_train=True, image_size=IMAGE_SIZE)
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    model = timm.create_model(PRETRAINED_MODEL, pretrained=False, num_classes=N_CLASSES).to(device)
    model.load_state_dict(torch.load(f"effv2_s_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.23317986778352634
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.28524557719067734
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.3191490693499622
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.2706382331996765
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.29324884792626726
Mean OOF F1: 0.2802923190900219
