In [1]:
import enum
import os
from copy import deepcopy

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B0

In [4]:
best_f1_per_fold: dict[int, int] = {}

In [5]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.2,        # Dropout
        # drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_block_and_head(model: nn.Module):
    """
    For Stage 1: unfreeze last block + classifier head.
    """
    freeze_all(model)

    # last conv block
    if hasattr(model, "blocks"):
        for p in model.blocks[-1].parameters():
            p.requires_grad = True

    # classifier / head
    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    For Stage 2: unfreeze last 2 blocks + classifier head.
    """
    freeze_all(model)

    if hasattr(model, "blocks"):
        for blk in model.blocks[-2:]:
            for p in blk.parameters():
                p.requires_grad = True

    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True


if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 5
    LR_STAGE1 = 1e-3
    LR_STAGE2 = 1e-4
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_efficientnet_b0_model()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers, except last block ---
        unfreeze_last_block_and_head(model)

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR_STAGE1,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_{PREFIX}_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze last two blocks + head ---
        unfreeze_last_two_blocks_and_head(model)

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR_STAGE2,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_{PREFIX}_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights
            print(f"Restored best Stage 2 weights for fold {fold} (F1={best_f1:.4f})")

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"{PREFIX}_fold{fold}.pth")


========== Fold 0 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.4618 | F1(macro)=0.3049 | Acc=0.3060


Confusion matrix:
 [[ 9  5 24  3]
 [18  2 12  0]
 [11  3 15  1]
 [ 5  0  7  2]]
Train  loss=2.4618 acc=0.3060 f1=0.3049 | Val loss=2.9860 acc=0.2393 f1=0.2126
  🔥 New best F1: 0.2126 – model saved.

Epoch 2/8


    t_loss=1.6719 | F1(macro)=0.3945 | Acc=0.3966


Confusion matrix:
 [[12 10 10  9]
 [11  4 10  7]
 [ 8  8  4 10]
 [ 5  2  2  5]]
Train  loss=1.6719 acc=0.3966 f1=0.3945 | Val loss=2.5206 acc=0.2137 f1=0.2049

Epoch 3/8


    t_loss=1.6181 | F1(macro)=0.3916 | Acc=0.3922


Confusion matrix:
 [[ 3 19 12  7]
 [ 9 12  7  4]
 [ 7 12  4  7]
 [ 4  3  2  5]]
Train  loss=1.6181 acc=0.3922 f1=0.3916 | Val loss=2.1018 acc=0.2051 f1=0.2043

Epoch 4/8


    t_loss=1.3676 | F1(macro)=0.4470 | Acc=0.4397


Confusion matrix:
 [[ 1 24 12  4]
 [ 3 21  5  3]
 [ 4 14  7  5]
 [ 3  5  3  3]]
Train  loss=1.3676 acc=0.4397 f1=0.4470 | Val loss=2.3379 acc=0.2735 f1=0.2321
  🔥 New best F1: 0.2321 – model saved.

Epoch 5/8


    t_loss=1.2480 | F1(macro)=0.4643 | Acc=0.4784


Confusion matrix:
 [[ 0 19 18  4]
 [ 5 13 12  2]
 [ 2 10 15  3]
 [ 3  3  6  2]]
Train  loss=1.2480 acc=0.4784 f1=0.4643 | Val loss=2.0834 acc=0.2564 f1=0.2170

Epoch 6/8


    t_loss=1.1747 | F1(macro)=0.5288 | Acc=0.5323


Confusion matrix:
 [[ 2 13 23  3]
 [ 7 10 13  2]
 [ 5  6 12  7]
 [ 4  2  6  2]]
Train  loss=1.1747 acc=0.5323 f1=0.5288 | Val loss=2.0897 acc=0.2222 f1=0.2035

Epoch 7/8


    t_loss=1.1200 | F1(macro)=0.5148 | Acc=0.5237


Confusion matrix:
 [[ 4 15 19  3]
 [10  8 13  1]
 [ 7  8 10  5]
 [ 6  1  4  3]]
Train  loss=1.1200 acc=0.5237 f1=0.5148 | Val loss=1.9989 acc=0.2137 f1=0.2154

Epoch 8/8


    t_loss=1.0390 | F1(macro)=0.5834 | Acc=0.5884


Confusion matrix:
 [[ 4 14 18  5]
 [14  9  8  1]
 [ 7  7  8  8]
 [ 5  1  5  3]]
Train  loss=1.0390 acc=0.5884 f1=0.5834 | Val loss=1.9618 acc=0.2051 f1=0.2060
Restored best Stage 1 weights for fold 0 (F1=0.2321)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=1.2043 | F1(macro)=0.4527 | Acc=0.4784


Confusion matrix:
 [[ 0 17 19  5]
 [ 1 11 17  3]
 [ 3  8 10  9]
 [ 3  1  5  5]]
Train  loss=1.2043 acc=0.4784 f1=0.4527 | Val loss=2.0689 acc=0.2222 f1=0.2109
  🔥 New best F1: 0.2109 – model saved.

Epoch 2/5


    t_loss=1.2131 | F1(macro)=0.4430 | Acc=0.4591


Confusion matrix:
 [[ 9 11 16  5]
 [10  9 10  3]
 [ 9  6 10  5]
 [ 4  0  7  3]]
Train  loss=1.2131 acc=0.4591 f1=0.4430 | Val loss=2.0412 acc=0.2650 f1=0.2577
  🔥 New best F1: 0.2577 – model saved.

Epoch 3/5


    t_loss=1.1367 | F1(macro)=0.5181 | Acc=0.5323


Confusion matrix:
 [[ 7 17 10  7]
 [ 5 11 11  5]
 [ 4  5  9 12]
 [ 1  2  5  6]]
Train  loss=1.1367 acc=0.5323 f1=0.5181 | Val loss=1.9688 acc=0.2821 f1=0.2798
  🔥 New best F1: 0.2798 – model saved.

Epoch 4/5


    t_loss=1.0640 | F1(macro)=0.5771 | Acc=0.5927


Confusion matrix:
 [[ 6 17  9  9]
 [ 6 15  6  5]
 [ 5  7  9  9]
 [ 3  2  4  5]]
Train  loss=1.0640 acc=0.5927 f1=0.5771 | Val loss=1.9766 acc=0.2991 f1=0.2890
  🔥 New best F1: 0.2890 – model saved.

Epoch 5/5


    t_loss=1.0585 | F1(macro)=0.5309 | Acc=0.5453


Confusion matrix:
 [[ 7 13 15  6]
 [ 6  8 15  3]
 [ 7  5 12  6]
 [ 2  1  7  4]]
Train  loss=1.0585 acc=0.5453 f1=0.5309 | Val loss=1.9556 acc=0.2650 f1=0.2599
Restored best Stage 2 weights for fold 0 (F1=0.2890)

========== Fold 1 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.2336 | F1(macro)=0.3391 | Acc=0.3376


Confusion matrix:
 [[ 6  6 13 15]
 [ 6  6  5 15]
 [ 1 11  7 11]
 [ 1  2  3  8]]
Train  loss=2.2336 acc=0.3376 f1=0.3391 | Val loss=3.1312 acc=0.2328 f1=0.2320
  🔥 New best F1: 0.2320 – model saved.

Epoch 2/8


    t_loss=1.8866 | F1(macro)=0.3422 | Acc=0.3441


Confusion matrix:
 [[ 6 14 10 10]
 [ 5 19  3  5]
 [ 5 14  9  2]
 [ 1  6  3  4]]
Train  loss=1.8866 acc=0.3441 f1=0.3422 | Val loss=2.6282 acc=0.3276 f1=0.3034
  🔥 New best F1: 0.3034 – model saved.

Epoch 3/8


    t_loss=1.5284 | F1(macro)=0.4087 | Acc=0.4172


Confusion matrix:
 [[ 7 22  7  4]
 [ 5 17  3  7]
 [12 16  1  1]
 [ 2  6  3  3]]
Train  loss=1.5284 acc=0.4172 f1=0.4087 | Val loss=2.4739 acc=0.2414 f1=0.2075

Epoch 4/8


    t_loss=1.3752 | F1(macro)=0.4693 | Acc=0.4688


Confusion matrix:
 [[ 9  7 17  7]
 [16  7  5  4]
 [16  6  7  1]
 [ 4  3  6  1]]
Train  loss=1.3752 acc=0.4688 f1=0.4693 | Val loss=2.3267 acc=0.2069 f1=0.1889

Epoch 5/8


    t_loss=1.3314 | F1(macro)=0.4656 | Acc=0.4667


Confusion matrix:
 [[ 7  7 17  9]
 [ 7 11  6  8]
 [ 6  8 12  4]
 [ 1  5  5  3]]
Train  loss=1.3314 acc=0.4667 f1=0.4656 | Val loss=2.0298 acc=0.2845 f1=0.2699

Epoch 6/8


    t_loss=1.1678 | F1(macro)=0.4908 | Acc=0.4882


Confusion matrix:
 [[12 11  9  8]
 [14 12  1  5]
 [12 11  5  2]
 [ 3  7  3  1]]
Train  loss=1.1678 acc=0.4882 f1=0.4908 | Val loss=2.1347 acc=0.2586 f1=0.2250

Epoch 7/8


    t_loss=1.2083 | F1(macro)=0.5001 | Acc=0.4989


Confusion matrix:
 [[11  6 14  9]
 [16  9  2  5]
 [12 10  6  2]
 [ 5  3  3  3]]
Train  loss=1.2083 acc=0.4989 f1=0.5001 | Val loss=2.0540 acc=0.2500 f1=0.2405

Epoch 8/8


    t_loss=1.1381 | F1(macro)=0.4904 | Acc=0.4925


Confusion matrix:
 [[ 7  7 17  9]
 [16  9  2  5]
 [ 9 12  7  2]
 [ 3  4  5  2]]
Train  loss=1.1381 acc=0.4925 f1=0.4904 | Val loss=1.9811 acc=0.2155 f1=0.2056
Restored best Stage 1 weights for fold 1 (F1=0.3034)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=1.3926 | F1(macro)=0.4350 | Acc=0.4538


Confusion matrix:
 [[ 5  7  3 25]
 [10  5  0 17]
 [ 8  7  4 11]
 [ 4  0  0 10]]
Train  loss=1.3926 acc=0.4538 f1=0.4350 | Val loss=2.2001 acc=0.2069 f1=0.2053
  🔥 New best F1: 0.2053 – model saved.

Epoch 2/5


    t_loss=1.2354 | F1(macro)=0.4048 | Acc=0.4172


Confusion matrix:
 [[ 5  6 10 19]
 [ 9  7  5 11]
 [ 7  6  9  8]
 [ 2  2  4  6]]
Train  loss=1.2354 acc=0.4172 f1=0.4048 | Val loss=2.1471 acc=0.2328 f1=0.2350
  🔥 New best F1: 0.2350 – model saved.

Epoch 3/5


    t_loss=1.2579 | F1(macro)=0.4423 | Acc=0.4624


Confusion matrix:
 [[ 5  5 10 20]
 [11  2  4 15]
 [ 8  7  6  9]
 [ 4  1  1  8]]
Train  loss=1.2579 acc=0.4624 f1=0.4423 | Val loss=2.0984 acc=0.1810 f1=0.1775

Epoch 4/5


    t_loss=1.2043 | F1(macro)=0.4305 | Acc=0.4495


Confusion matrix:
 [[ 7  8 10 15]
 [12  9  4  7]
 [11  7  5  7]
 [ 6  2  2  4]]
Train  loss=1.2043 acc=0.4495 f1=0.4305 | Val loss=2.0587 acc=0.2155 f1=0.2152

Epoch 5/5


    t_loss=1.1730 | F1(macro)=0.4740 | Acc=0.4925


Confusion matrix:
 [[ 8  6 11 15]
 [15  5  4  8]
 [12  6  6  6]
 [ 5  1  4  4]]
Train  loss=1.1730 acc=0.4925 f1=0.4740 | Val loss=2.0738 acc=0.1983 f1=0.1971
Restored best Stage 2 weights for fold 1 (F1=0.2350)

========== Fold 2 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.4735 | F1(macro)=0.3224 | Acc=0.3226


Confusion matrix:
 [[24  8  9  0]
 [10  9 12  0]
 [16  6  8  0]
 [ 9  1  3  1]]
Train  loss=2.4735 acc=0.3226 f1=0.3224 | Val loss=2.2793 acc=0.3621 f1=0.2997
  🔥 New best F1: 0.2997 – model saved.

Epoch 2/8


    t_loss=1.7348 | F1(macro)=0.3688 | Acc=0.3742


Confusion matrix:
 [[ 8  9 16  8]
 [ 5  4 13  9]
 [11  1 12  6]
 [ 2  1  6  5]]
Train  loss=1.7348 acc=0.3742 f1=0.3688 | Val loss=2.2727 acc=0.2500 f1=0.2406

Epoch 3/8


    t_loss=1.5933 | F1(macro)=0.3743 | Acc=0.3828


Confusion matrix:
 [[16  7  0 18]
 [11  7  4  9]
 [21  4  0  5]
 [ 5  0  2  7]]
Train  loss=1.5933 acc=0.3828 f1=0.3743 | Val loss=2.2940 acc=0.2586 f1=0.2226

Epoch 4/8


    t_loss=1.3944 | F1(macro)=0.4355 | Acc=0.4366


Confusion matrix:
 [[25  5  7  4]
 [14  5  8  4]
 [22  2  3  3]
 [ 7  2  2  3]]
Train  loss=1.3944 acc=0.4366 f1=0.4355 | Val loss=2.0731 acc=0.3103 f1=0.2538

Epoch 5/8


    t_loss=1.2898 | F1(macro)=0.4470 | Acc=0.4581


Confusion matrix:
 [[28  4  4  5]
 [15  4  5  7]
 [25  1  1  3]
 [ 7  0  2  5]]
Train  loss=1.2898 acc=0.4581 f1=0.4470 | Val loss=2.6418 acc=0.3276 f1=0.2561

Epoch 6/8


    t_loss=1.2438 | F1(macro)=0.4747 | Acc=0.4774


Confusion matrix:
 [[15  6  9 11]
 [10  7  8  6]
 [16  5  4  5]
 [ 6  0  4  4]]
Train  loss=1.2438 acc=0.4774 f1=0.4747 | Val loss=2.0036 acc=0.2586 f1=0.2430

Epoch 7/8


    t_loss=1.1000 | F1(macro)=0.5311 | Acc=0.5333


Confusion matrix:
 [[15  7  9 10]
 [ 9  9  9  4]
 [15  3  5  7]
 [ 5  1  2  6]]
Train  loss=1.1000 acc=0.5333 f1=0.5311 | Val loss=2.0182 acc=0.3017 f1=0.2951

Epoch 8/8


    t_loss=1.0982 | F1(macro)=0.5523 | Acc=0.5527


Confusion matrix:
 [[23  9  8  1]
 [10 14  6  1]
 [20  5  4  1]
 [ 7  2  3  2]]
Train  loss=1.0982 acc=0.5527 f1=0.5523 | Val loss=1.9531 acc=0.3707 f1=0.3205
  🔥 New best F1: 0.3205 – model saved.
Restored best Stage 1 weights for fold 2 (F1=0.3205)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=1.1294 | F1(macro)=0.5082 | Acc=0.5161


Confusion matrix:
 [[10 14  5 12]
 [ 6 16  6  3]
 [ 8  9  4  9]
 [ 5  1  2  6]]
Train  loss=1.1294 acc=0.5161 f1=0.5082 | Val loss=2.3391 acc=0.3103 f1=0.2948
  🔥 New best F1: 0.2948 – model saved.

Epoch 2/5


    t_loss=1.1198 | F1(macro)=0.5135 | Acc=0.5269


Confusion matrix:
 [[23  8  2  8]
 [14  7  5  5]
 [21  3  3  3]
 [ 6  1  3  4]]
Train  loss=1.1198 acc=0.5269 f1=0.5135 | Val loss=2.0909 acc=0.3190 f1=0.2732

Epoch 3/5


    t_loss=1.0726 | F1(macro)=0.5285 | Acc=0.5398


Confusion matrix:
 [[16 14  5  6]
 [ 9 14  6  2]
 [16  8  5  1]
 [ 7  2  2  3]]
Train  loss=1.0726 acc=0.5398 f1=0.5285 | Val loss=2.1504 acc=0.3276 f1=0.3011
  🔥 New best F1: 0.3011 – model saved.

Epoch 4/5


    t_loss=1.0194 | F1(macro)=0.5498 | Acc=0.5613


Confusion matrix:
 [[17 13  3  8]
 [ 9 13  6  3]
 [14  5  5  6]
 [ 5  1  2  6]]
Train  loss=1.0194 acc=0.5613 f1=0.5498 | Val loss=2.0852 acc=0.3534 f1=0.3374
  🔥 New best F1: 0.3374 – model saved.

Epoch 5/5


    t_loss=0.9325 | F1(macro)=0.5981 | Acc=0.6129


Confusion matrix:
 [[15 14  6  6]
 [ 9 12 10  0]
 [14  6  5  5]
 [ 5  2  3  4]]
Train  loss=0.9325 acc=0.6129 f1=0.5981 | Val loss=2.1326 acc=0.3103 f1=0.2969
Restored best Stage 2 weights for fold 2 (F1=0.3374)

========== Fold 3 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.2230 | F1(macro)=0.3313 | Acc=0.3398


Confusion matrix:
 [[26  0  8  7]
 [17  4  7  3]
 [18  3  5  4]
 [ 6  1  3  4]]
Train  loss=2.2230 acc=0.3398 f1=0.3313 | Val loss=2.2567 acc=0.3362 f1=0.2813
  🔥 New best F1: 0.2813 – model saved.

Epoch 2/8


    t_loss=1.6687 | F1(macro)=0.3593 | Acc=0.3613


Confusion matrix:
 [[ 9  5 16 11]
 [ 9  4 14  4]
 [ 5  6  8 11]
 [ 5  0  2  7]]
Train  loss=1.6687 acc=0.3613 f1=0.3593 | Val loss=2.3391 acc=0.2414 f1=0.2403

Epoch 3/8


    t_loss=1.4714 | F1(macro)=0.3989 | Acc=0.4000


Confusion matrix:
 [[16  7 13  5]
 [11 11  7  2]
 [ 8  7 10  5]
 [ 6  1  5  2]]
Train  loss=1.4714 acc=0.4000 f1=0.3989 | Val loss=1.6440 acc=0.3362 f1=0.3067
  🔥 New best F1: 0.3067 – model saved.

Epoch 4/8


    t_loss=1.4643 | F1(macro)=0.3964 | Acc=0.3935


Confusion matrix:
 [[26  3  7  5]
 [15  5  8  3]
 [17  7  4  2]
 [ 7  1  4  2]]
Train  loss=1.4643 acc=0.3935 f1=0.3964 | Val loss=1.8347 acc=0.3190 f1=0.2520

Epoch 5/8


    t_loss=1.2361 | F1(macro)=0.4756 | Acc=0.4774


Confusion matrix:
 [[19  5 10  7]
 [10  8 10  3]
 [12  7  7  4]
 [ 6  1  3  4]]
Train  loss=1.2361 acc=0.4774 f1=0.4756 | Val loss=1.6681 acc=0.3276 f1=0.3057

Epoch 6/8


    t_loss=1.1897 | F1(macro)=0.5046 | Acc=0.5032


Confusion matrix:
 [[17  3 12  9]
 [12  5 10  4]
 [12  2  8  8]
 [ 4  1  2  7]]
Train  loss=1.1897 acc=0.5032 f1=0.5046 | Val loss=1.6773 acc=0.3190 f1=0.3062

Epoch 7/8


    t_loss=1.1956 | F1(macro)=0.5211 | Acc=0.5204


Confusion matrix:
 [[24  9  1  7]
 [16 10  4  1]
 [19  6  2  3]
 [ 6  3  2  3]]
Train  loss=1.1956 acc=0.5204 f1=0.5211 | Val loss=1.6614 acc=0.3362 f1=0.2772

Epoch 8/8


    t_loss=1.1562 | F1(macro)=0.5520 | Acc=0.5527


Confusion matrix:
 [[23  2  7  9]
 [16  7  6  2]
 [18  2  6  4]
 [ 6  2  2  4]]
Train  loss=1.1562 acc=0.5527 f1=0.5520 | Val loss=1.6167 acc=0.3448 f1=0.3096
  🔥 New best F1: 0.3096 – model saved.
Restored best Stage 1 weights for fold 3 (F1=0.3096)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=1.1929 | F1(macro)=0.4742 | Acc=0.4839


Confusion matrix:
 [[17  5 16  3]
 [18  5  7  1]
 [16  3 10  1]
 [ 7  1  3  3]]
Train  loss=1.1929 acc=0.4839 f1=0.4742 | Val loss=1.8970 acc=0.3017 f1=0.2854
  🔥 New best F1: 0.2854 – model saved.

Epoch 2/5


    t_loss=1.1569 | F1(macro)=0.5201 | Acc=0.5247


Confusion matrix:
 [[17  4 11  9]
 [14  6  7  4]
 [11  3  9  7]
 [ 5  1  3  5]]
Train  loss=1.1569 acc=0.5247 f1=0.5201 | Val loss=1.8094 acc=0.3190 f1=0.3024
  🔥 New best F1: 0.3024 – model saved.

Epoch 3/5


    t_loss=1.0086 | F1(macro)=0.5495 | Acc=0.5677


Confusion matrix:
 [[23  6  2 10]
 [17  8  4  2]
 [17  8  2  3]
 [ 6  1  1  6]]
Train  loss=1.0086 acc=0.5677 f1=0.5495 | Val loss=1.8599 acc=0.3362 f1=0.2960

Epoch 4/5


    t_loss=1.0261 | F1(macro)=0.5411 | Acc=0.5570


Confusion matrix:
 [[26  5  2  8]
 [19  6  4  2]
 [18  6  3  3]
 [ 6  0  2  6]]
Train  loss=1.0261 acc=0.5570 f1=0.5411 | Val loss=1.9428 acc=0.3534 f1=0.3082
  🔥 New best F1: 0.3082 – model saved.

Epoch 5/5


    t_loss=1.0092 | F1(macro)=0.5632 | Acc=0.5720


Confusion matrix:
 [[24  3  3 11]
 [16  7  5  3]
 [14  5  4  7]
 [ 6  0  1  7]]
Train  loss=1.0092 acc=0.5720 f1=0.5632 | Val loss=1.8494 acc=0.3621 f1=0.3247
  🔥 New best F1: 0.3247 – model saved.
Restored best Stage 2 weights for fold 3 (F1=0.3247)

========== Fold 4 ==========

--- Stage 1: Training classifier head ---

Epoch 1/8


    t_loss=2.4163 | F1(macro)=0.3425 | Acc=0.3462


Confusion matrix:
 [[ 9  0 19 13]
 [ 7  2 14  9]
 [ 7  0 15  8]
 [ 1  1  5  6]]
Train  loss=2.4163 acc=0.3462 f1=0.3425 | Val loss=2.9716 acc=0.2759 f1=0.2494
  🔥 New best F1: 0.2494 – model saved.

Epoch 2/8


    t_loss=1.6842 | F1(macro)=0.3819 | Acc=0.3806


Confusion matrix:
 [[ 8  2 21 10]
 [ 3 12  9  8]
 [ 3  6 16  5]
 [ 2  1  4  6]]
Train  loss=1.6842 acc=0.3806 f1=0.3819 | Val loss=2.3024 acc=0.3621 f1=0.3548
  🔥 New best F1: 0.3548 – model saved.

Epoch 3/8


    t_loss=1.5293 | F1(macro)=0.4434 | Acc=0.4430


Confusion matrix:
 [[ 9  3 18 11]
 [ 3  8 12  9]
 [ 4  4 16  6]
 [ 1  1  6  5]]
Train  loss=1.5293 acc=0.4430 f1=0.4434 | Val loss=2.0521 acc=0.3276 f1=0.3153

Epoch 4/8


    t_loss=1.5230 | F1(macro)=0.3979 | Acc=0.4000


Confusion matrix:
 [[17  4 15  5]
 [ 7 14  5  6]
 [ 9  4 13  4]
 [ 5  1  3  4]]
Train  loss=1.5230 acc=0.4000 f1=0.3979 | Val loss=1.6322 acc=0.4138 f1=0.3959
  🔥 New best F1: 0.3959 – model saved.

Epoch 5/8


    t_loss=1.3045 | F1(macro)=0.4650 | Acc=0.4710


Confusion matrix:
 [[ 5 13 18  5]
 [ 1 17  8  6]
 [ 7  6 10  7]
 [ 2  1  6  4]]
Train  loss=1.3045 acc=0.4710 f1=0.4650 | Val loss=1.7848 acc=0.3103 f1=0.2944

Epoch 6/8


    t_loss=1.2086 | F1(macro)=0.4843 | Acc=0.4817


Confusion matrix:
 [[17  4 18  2]
 [13  7  9  3]
 [10  4 15  1]
 [ 4  1  5  3]]
Train  loss=1.2086 acc=0.4817 f1=0.4843 | Val loss=1.7282 acc=0.3621 f1=0.3385

Epoch 7/8


    t_loss=1.0658 | F1(macro)=0.5659 | Acc=0.5656


Confusion matrix:
 [[13  4 21  3]
 [11  9 10  2]
 [10  9 10  1]
 [ 3  2  5  3]]
Train  loss=1.0658 acc=0.5656 f1=0.5659 | Val loss=1.7313 acc=0.3017 f1=0.2977

Epoch 8/8


    t_loss=1.1738 | F1(macro)=0.5205 | Acc=0.5247


Confusion matrix:
 [[18  5 13  5]
 [14 11  5  2]
 [10  8  7  5]
 [ 3  1  6  3]]
Train  loss=1.1738 acc=0.5247 f1=0.5205 | Val loss=1.5818 acc=0.3362 f1=0.3121
Restored best Stage 1 weights for fold 4 (F1=0.3959)

--- Stage 2: Fine-tuning entire model ---

Epoch 1/5


    t_loss=1.2683 | F1(macro)=0.4507 | Acc=0.4559


Confusion matrix:
 [[11 12 13  5]
 [ 5 16  6  5]
 [ 6  6 10  8]
 [ 2  1  5  5]]
Train  loss=1.2683 acc=0.4559 f1=0.4507 | Val loss=1.6964 acc=0.3621 f1=0.3516
  🔥 New best F1: 0.3516 – model saved.

Epoch 2/5


    t_loss=1.1883 | F1(macro)=0.5134 | Acc=0.5333


Confusion matrix:
 [[13  4 21  3]
 [ 6 10 11  5]
 [ 4  5 15  6]
 [ 1  1  5  6]]
Train  loss=1.1883 acc=0.5333 f1=0.5134 | Val loss=1.6993 acc=0.3793 f1=0.3785
  🔥 New best F1: 0.3785 – model saved.

Epoch 3/5


    t_loss=1.1238 | F1(macro)=0.5630 | Acc=0.5677


Confusion matrix:
 [[10  8 18  5]
 [ 4 13 13  2]
 [ 6  5 15  4]
 [ 1  1  7  4]]
Train  loss=1.1238 acc=0.5677 f1=0.5630 | Val loss=1.7363 acc=0.3621 f1=0.3526

Epoch 4/5


    t_loss=1.1354 | F1(macro)=0.5533 | Acc=0.5570


Confusion matrix:
 [[ 9  9 17  6]
 [ 2 14 12  4]
 [ 5  5 16  4]
 [ 4  0  5  4]]
Train  loss=1.1354 acc=0.5570 f1=0.5533 | Val loss=1.7387 acc=0.3707 f1=0.3550

Epoch 5/5


    t_loss=1.0719 | F1(macro)=0.5310 | Acc=0.5462


Confusion matrix:
 [[ 7  9 19  6]
 [ 5 11  9  7]
 [ 5  6 12  7]
 [ 2  1  3  7]]
Train  loss=1.0719 acc=0.5462 f1=0.5310 | Val loss=1.7888 acc=0.3190 f1=0.3212
Restored best Stage 2 weights for fold 4 (F1=0.3785)


# tf_efficientnetv2_s.in21k

In [6]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [7]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [8]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

# test_dataset = HistologyDataset(
#     df=test_df,
#     image_size=IMAGE_SIZE,
#     is_train=False,   # returns (img, sample_index)
#     use_mask_crop=True
# )
#
# test_loader = DataLoader(
#     test_dataset,
#     batch_size=BATCH_SIZE,
#     shuffle=False,
#     num_workers=N_WORKERS,
#     pin_memory=cuda_is_available
# )
#
# all_fold_probs = []   # list of arrays [N, num_classes]
# all_sample_indices = None
#
# for fold in range(N_FOLDS):
#     print(f"Inference with fold {fold} model")
#
#     # recreate model and load weights
#     if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
#         model = create_model_tf_efficientnetv2_s(pretrained=False)
#     elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
#         model = create_model_convnext(pretrained=False)
#     else:
#         model = create_efficientnet_b0_model(pretrained=False)
#     state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
#     model.load_state_dict(state)
#     model.eval()
#
#     fold_probs = []
#     sample_indices_list = []
#
#     with torch.no_grad():
#         for imgs, sample_indices in test_loader:
#             imgs = imgs.to(device, non_blocking=True)
#
#             logits = model(imgs)               # [B, num_classes]
#             probs = softmax(logits, dim=1)     # [B, num_classes]
#             fold_probs.append(probs.cpu().numpy())
#
#             # collect sample indices only once
#             if all_sample_indices is None:
#                 sample_indices_list.extend(sample_indices)
#
#     fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
#     all_fold_probs.append(fold_probs)
#
#     if all_sample_indices is None:
#         all_sample_indices = sample_indices_list
#
# # average probabilities across folds
# mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
# pred_indices = mean_probs.argmax(axis=1)
#
# pred_labels = [idx2label[int(i)] for i in pred_indices]
# sample_index_with_ext = [
#     f"{si}.png" if not si.endswith(".png") else si
#     for si in all_sample_indices
# ]
#
# submission_df = pd.DataFrame({
#     "sample_index": sample_index_with_ext,
#     "label": pred_labels
# })
#
# submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
# print("Saved submission_5fold_no_tta.csv")
# print(submission_df.head())


In [9]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # deterministic, returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=1,               # per-image TTA
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

val_f1_per_fold = np.array(
    [best_f1_per_fold[fold] for fold in range(N_FOLDS)],
    dtype=np.float32
)

# Normalize to get weights that sum to 1
fold_weights = val_f1_per_fold / val_f1_per_fold.sum()
print("Fold weights:", fold_weights)

# -----------------------------
# 2) Accumulate weighted probs
# -----------------------------
all_probs = None
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model (weight={fold_weights[fold]:.3f})")

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)

    state_dict = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            # img_tensor: [1, 4, H, W]  (RGB+mask)
            img_tensor = img_tensor.squeeze(0).to(device)  # [4, H, W]

            # -------- TTA: apply multiple augmented views [4xHxW] --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1, 4, H, W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1, N_CLASSES]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)  # [N_CLASSES]
            fold_probs.append(avg_probs)

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N_test, N_CLASSES]

    # initialize global probs
    if all_probs is None:
        all_probs = np.zeros_like(fold_probs, dtype=np.float32)

     # weighted accumulation
    all_probs += fold_weights[fold] * fold_probs

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# -----------------------------
# 3) Final predictions
# -----------------------------
pred_indices = all_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print(f"Saved submission_5fold_tta_{prefix_filename}.csv")

Fold weights: [0.18471073 0.15020123 0.21564856 0.20753433 0.2419052 ]
Inference with fold 0 model (weight=0.185)
Inference with fold 1 model (weight=0.150)
Inference with fold 2 model (weight=0.216)
Inference with fold 3 model (weight=0.208)
Inference with fold 4 model (weight=0.242)
Saved submission_5fold_tta_effb0.csv


In [10]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.3398613469156763
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.21390253890253888
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.2526581605528974
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.2711349924585219
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.4104180677317791
Mean OOF F1: 0.29759502131228277
