In [1]:
import enum
import json
import os
from copy import deepcopy

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import f1_score
from timm.data import Mixup
from torch.nn.functional import softmax
from torch.optim import AdamW
from torch.utils.data import DataLoader

from internal.data_types import HistologyDataset
from internal.nn.mixup_cutmix_wrapper import MixupCutmixWrapper
from internal.nn.model import train_one_epoch, validate
from internal.nn.test_time_augmentation import apply_tta
from internal.nn.weighted_random_sampler import make_weighted_sampler
from internal.persistence_manager import PersistenceManager

data = PersistenceManager.load_dataset()
test_df = data.test_df
train_df = data.train_df
train_transforms = data.train_transforms
val_test_transforms = data.val_test_transforms
idx2label = data.idx2label

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
cuda_is_available = torch.cuda.is_available()
print(f'Using device: {device}')

Arrays and scalers loaded successfully from: /home/andre/university/AN2DL-Challenge-2/notebooks/processed/dataset.joblib
Using device: cuda


In [2]:
def get_classifier_module(model: nn.Module):
    # Common names in timm models
    for name in ["classifier", "fc", "head"]:
        if hasattr(model, name):
            return getattr(model, name), name
    # Fallback: assume there is a single linear at the very end
    last_linear = None
    for m in reversed(list(model.modules())):
        if isinstance(m, nn.Linear):
            last_linear = m
            break
    if last_linear is None:
        raise RuntimeError("Could not find classifier layer in model.")
    return last_linear, None

In [3]:
class PreTrainedArchitectures(enum.Enum):
    EFFICIENTNETV2_S = "tf_efficientnetv2_s.in21k"
    CONVNEXT_TINY = "convnext_tiny"
    EFFICIENTNET_B0 = "efficientnet_b0"
    EFFICIENTNET_B1 = "efficientnet_b1"

MODEL_TO_USE: PreTrainedArchitectures = PreTrainedArchitectures.EFFICIENTNET_B0

In [4]:
best_f1_per_fold: dict[int, int] = {}

In [5]:
def create_efficientnet_b0_model(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,          # Dropout
        drop_path_rate=0.1      # Stochastic depth
    ).to(device)
    return model

def freeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False

def unfreeze_last_two_blocks_and_head(model: nn.Module):
    """
    For EfficientNet from timm: unfreeze last 2 blocks + classifier head.
    """
    freeze_all(model)

    # Last 2 conv blocks
    if hasattr(model, "blocks"):
        for blk in model.blocks[-2:]:
            for p in blk.parameters():
                p.requires_grad = True

    # Classifier head
    clf_module, _ = get_classifier_module(model)
    for p in clf_module.parameters():
        p.requires_grad = True


if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 or MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B1:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS = 25
    LR = 3e-4
    PREFIX = "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,  # Augmentations applied
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False, # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        # ---- create model + unfreeze last 2 blocks + head ----
        model = create_efficientnet_b0_model(pretrained=True)
        unfreeze_last_two_blocks_and_head(model)

        # ---- loss, optimizer, scheduler ----
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()

        criterion = nn.CrossEntropyLoss(
            weight=class_weights.to(device),
            label_smoothing=0.1
        )

        optimizer = AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
            weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=EPOCHS
        )

        # ---- training loop ----
        best_f1 = 0.0
        best_state = None
        mixup_fn = MixupCutmixWrapper(
            alpha=0.4,       # mixup/cutmix Beta distribution
            mixup_prob=0.4,  # 40% of batches => mixup
            cutmix_prob=0.2  # 20% of batches => cutmix
        )

        for epoch in range(1, EPOCHS + 1):
            print(f"\nEpoch {epoch}/{EPOCHS}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device, mixup_fn=mixup_fn
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()

            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )

            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(
                    best_state,
                    f"best_effb0_fold{fold}_f1_{val_f1:.4f}.pth"
                )
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        # restore best weights for this fold
        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best weights for fold {fold} (F1={best_f1:.4f})")

        # save final model for inference
        torch.save(model.state_dict(), f"effb0_fold{fold}.pth")

        # record best F1 for this fold
        best_f1_per_fold[fold] = best_f1


========== Fold 0 ==========

Epoch 1/25


    t_loss=2.2645 | F1(macro)=0.2712 | Acc=0.2845


Confusion matrix:
 [[ 5  5 21 10]
 [ 5 13  9  5]
 [ 1  2 18  9]
 [ 2  3  5  4]]
Train  loss=2.2645 acc=0.2845 f1=0.2712 | Val loss=2.1135 acc=0.3419 f1=0.3205
  🔥 New best F1: 0.3205 – model saved.

Epoch 2/25


    t_loss=1.5799 | F1(macro)=0.3423 | Acc=0.3728


Confusion matrix:
 [[ 9  1 25  6]
 [10  9  8  5]
 [ 5  1 15  9]
 [ 3  3  2  6]]
Train  loss=1.5799 acc=0.3728 f1=0.3423 | Val loss=2.0892 acc=0.3333 f1=0.3328
  🔥 New best F1: 0.3328 – model saved.

Epoch 3/25


    t_loss=1.3973 | F1(macro)=0.4031 | Acc=0.4224


Confusion matrix:
 [[ 4  3 22 12]
 [ 7  9 10  6]
 [ 3  2 16  9]
 [ 1  2  5  6]]
Train  loss=1.3973 acc=0.4224 f1=0.4031 | Val loss=2.1300 acc=0.2991 f1=0.2897

Epoch 4/25


    t_loss=1.3471 | F1(macro)=0.4233 | Acc=0.4375


Confusion matrix:
 [[11  3  8 19]
 [ 7  3  2 20]
 [ 4  2  0 24]
 [ 1  2  1 10]]
Train  loss=1.3471 acc=0.4375 f1=0.4233 | Val loss=2.2760 acc=0.2051 f1=0.1791

Epoch 5/25


    t_loss=1.2100 | F1(macro)=0.4914 | Acc=0.5065


Confusion matrix:
 [[20  5  8  8]
 [12  5  7  8]
 [13  2  5 10]
 [ 7  0  2  5]]
Train  loss=1.2100 acc=0.5065 f1=0.4914 | Val loss=2.1744 acc=0.2991 f1=0.2680

Epoch 6/25


    t_loss=1.1997 | F1(macro)=0.4808 | Acc=0.4957


Confusion matrix:
 [[19  1 11 10]
 [10  5 10  7]
 [ 8  0 11 11]
 [ 4  0  5  5]]
Train  loss=1.1997 acc=0.4957 f1=0.4808 | Val loss=2.1426 acc=0.3419 f1=0.3169

Epoch 7/25


    t_loss=1.1644 | F1(macro)=0.4962 | Acc=0.5086


Confusion matrix:
 [[13  5 15  8]
 [ 7 10  8  7]
 [ 7  2  9 12]
 [ 2  1  5  6]]
Train  loss=1.1644 acc=0.5086 f1=0.4962 | Val loss=1.8898 acc=0.3248 f1=0.3239

Epoch 8/25


    t_loss=1.0529 | F1(macro)=0.5416 | Acc=0.5560


Confusion matrix:
 [[ 8  4 22  7]
 [ 7  4 15  6]
 [ 2  0 23  5]
 [ 2  0  7  5]]
Train  loss=1.0529 acc=0.5560 f1=0.5416 | Val loss=2.0383 acc=0.3419 f1=0.3028

Epoch 9/25


    t_loss=0.9927 | F1(macro)=0.5785 | Acc=0.5927


Confusion matrix:
 [[ 2  6 30  3]
 [ 8  6 15  3]
 [ 1  1 24  4]
 [ 1  2  9  2]]
Train  loss=0.9927 acc=0.5927 f1=0.5785 | Val loss=2.3124 acc=0.2906 f1=0.2323

Epoch 10/25


    t_loss=0.9887 | F1(macro)=0.6232 | Acc=0.6336


Confusion matrix:
 [[11  9 14  7]
 [ 7 11  5  9]
 [ 5  2 16  7]
 [ 3  3  3  5]]
Train  loss=0.9887 acc=0.6336 f1=0.6232 | Val loss=2.0398 acc=0.3675 f1=0.3558
  🔥 New best F1: 0.3558 – model saved.

Epoch 11/25


    t_loss=0.9662 | F1(macro)=0.5994 | Acc=0.6099


Confusion matrix:
 [[ 9  7 20  5]
 [ 6 12  7  7]
 [ 2  5 19  4]
 [ 1  2  7  4]]
Train  loss=0.9662 acc=0.6099 f1=0.5994 | Val loss=2.0189 acc=0.3761 f1=0.3530

Epoch 12/25


    t_loss=0.9192 | F1(macro)=0.6363 | Acc=0.6466


Confusion matrix:
 [[ 7 10 19  5]
 [ 6 13  7  6]
 [ 4  7 14  5]
 [ 2  3  6  3]]
Train  loss=0.9192 acc=0.6466 f1=0.6363 | Val loss=2.0053 acc=0.3162 f1=0.2959

Epoch 13/25


    t_loss=0.8702 | F1(macro)=0.6564 | Acc=0.6659


Confusion matrix:
 [[12  7 18  4]
 [10  8 10  4]
 [ 6  2 16  6]
 [ 3  2  4  5]]
Train  loss=0.8702 acc=0.6659 f1=0.6564 | Val loss=2.0623 acc=0.3504 f1=0.3401

Epoch 14/25


    t_loss=0.9113 | F1(macro)=0.6356 | Acc=0.6379


Confusion matrix:
 [[15  9 11  6]
 [ 9  7  8  8]
 [10  3 10  7]
 [ 5  4  1  4]]
Train  loss=0.9113 acc=0.6379 f1=0.6356 | Val loss=2.0013 acc=0.3077 f1=0.2920

Epoch 15/25


    t_loss=0.8773 | F1(macro)=0.6762 | Acc=0.6853


Confusion matrix:
 [[14  4 13 10]
 [ 7  8 10  7]
 [ 9  1  8 12]
 [ 4  3  3  4]]
Train  loss=0.8773 acc=0.6853 f1=0.6762 | Val loss=2.1380 acc=0.2906 f1=0.2817

Epoch 16/25


    t_loss=0.8187 | F1(macro)=0.6984 | Acc=0.7091


Confusion matrix:
 [[11  9 17  4]
 [ 5 13  6  8]
 [ 8  2 14  6]
 [ 3  4  3  4]]
Train  loss=0.8187 acc=0.7091 f1=0.6984 | Val loss=2.1304 acc=0.3590 f1=0.3448

Epoch 17/25


    t_loss=0.7673 | F1(macro)=0.7325 | Acc=0.7371


Confusion matrix:
 [[10 10 19  2]
 [ 9 11  8  4]
 [11  2 13  4]
 [ 2  4  4  4]]
Train  loss=0.7673 acc=0.7371 f1=0.7325 | Val loss=2.0842 acc=0.3248 f1=0.3210

Epoch 18/25


    t_loss=0.7528 | F1(macro)=0.7254 | Acc=0.7328


Confusion matrix:
 [[14  7 16  4]
 [ 6  7 10  9]
 [ 9  2 11  8]
 [ 2  3  4  5]]
Train  loss=0.7528 acc=0.7328 f1=0.7254 | Val loss=2.0369 acc=0.3162 f1=0.3058

Epoch 19/25


    t_loss=0.7595 | F1(macro)=0.7484 | Acc=0.7543


Confusion matrix:
 [[10 11 18  2]
 [ 9 12  7  4]
 [ 8  2 15  5]
 [ 1  5  4  4]]
Train  loss=0.7595 acc=0.7543 f1=0.7484 | Val loss=2.0499 acc=0.3504 f1=0.3396

Epoch 20/25


    t_loss=0.7231 | F1(macro)=0.7510 | Acc=0.7565


Confusion matrix:
 [[15  5 18  3]
 [ 7  8  8  9]
 [12  1 11  6]
 [ 4  1  4  5]]
Train  loss=0.7231 acc=0.7565 f1=0.7510 | Val loss=2.0564 acc=0.3333 f1=0.3251

Epoch 21/25


    t_loss=0.7557 | F1(macro)=0.7403 | Acc=0.7478


Confusion matrix:
 [[15  7 16  3]
 [ 6  9 10  7]
 [11  2 11  6]
 [ 3  2  4  5]]
Train  loss=0.7557 acc=0.7478 f1=0.7403 | Val loss=2.0317 acc=0.3419 f1=0.3341

Epoch 22/25


    t_loss=0.7010 | F1(macro)=0.7785 | Acc=0.7866


Confusion matrix:
 [[16  7 15  3]
 [ 8  8  7  9]
 [10  1 13  6]
 [ 4  2  3  5]]
Train  loss=0.7010 acc=0.7866 f1=0.7785 | Val loss=2.0425 acc=0.3590 f1=0.3444

Epoch 23/25


    t_loss=0.7366 | F1(macro)=0.7382 | Acc=0.7435


Confusion matrix:
 [[20  3 15  3]
 [12  4  8  8]
 [13  0 11  6]
 [ 4  2  3  5]]
Train  loss=0.7366 acc=0.7435 f1=0.7382 | Val loss=2.0795 acc=0.3419 f1=0.3114

Epoch 24/25


    t_loss=0.6562 | F1(macro)=0.7582 | Acc=0.7737


Confusion matrix:
 [[19  6 14  2]
 [12  9  8  3]
 [14  1 11  4]
 [ 5  2  2  5]]
Train  loss=0.6562 acc=0.7737 f1=0.7582 | Val loss=2.0442 acc=0.3761 f1=0.3683
  🔥 New best F1: 0.3683 – model saved.

Epoch 25/25


    t_loss=0.7090 | F1(macro)=0.7670 | Acc=0.7694


Confusion matrix:
 [[19  8 12  2]
 [ 8  8  9  7]
 [13  2 10  5]
 [ 4  2  3  5]]
Train  loss=0.7090 acc=0.7694 f1=0.7670 | Val loss=2.0375 acc=0.3590 f1=0.3426
Restored best weights for fold 0 (F1=0.3683)

========== Fold 1 ==========

Epoch 1/25


    t_loss=2.1613 | F1(macro)=0.2934 | Acc=0.3097


Confusion matrix:
 [[11 23  4  2]
 [ 8 18  2  4]
 [14 15  1  0]
 [ 3  9  0  2]]
Train  loss=2.1613 acc=0.3097 f1=0.2934 | Val loss=2.5770 acc=0.2759 f1=0.2241
  🔥 New best F1: 0.2241 – model saved.

Epoch 2/25


    t_loss=1.5839 | F1(macro)=0.3862 | Acc=0.3914


Confusion matrix:
 [[ 8  3 12 17]
 [ 5  9  4 14]
 [ 9  5  5 11]
 [ 2  1  3  8]]
Train  loss=1.5839 acc=0.3914 f1=0.3862 | Val loss=2.1011 acc=0.2586 f1=0.2613
  🔥 New best F1: 0.2613 – model saved.

Epoch 3/25


    t_loss=1.4781 | F1(macro)=0.3675 | Acc=0.3806


Confusion matrix:
 [[10 13 12  5]
 [ 8 12  8  4]
 [ 8 13  7  2]
 [ 3  3  4  4]]
Train  loss=1.4781 acc=0.3806 f1=0.3675 | Val loss=1.9394 acc=0.2845 f1=0.2810
  🔥 New best F1: 0.2810 – model saved.

Epoch 4/25


    t_loss=1.3737 | F1(macro)=0.4402 | Acc=0.4452


Confusion matrix:
 [[12 13 11  4]
 [ 7 17  6  2]
 [12 10  7  1]
 [ 3  4  4  3]]
Train  loss=1.3737 acc=0.4452 f1=0.4402 | Val loss=2.0282 acc=0.3362 f1=0.3158
  🔥 New best F1: 0.3158 – model saved.

Epoch 5/25


    t_loss=1.2638 | F1(macro)=0.4787 | Acc=0.4903


Confusion matrix:
 [[ 6  7 14 13]
 [ 2  9 14  7]
 [ 6 10 11  3]
 [ 3  0  6  5]]
Train  loss=1.2638 acc=0.4903 f1=0.4787 | Val loss=2.1584 acc=0.2672 f1=0.2631

Epoch 6/25


    t_loss=1.2117 | F1(macro)=0.4976 | Acc=0.5183


Confusion matrix:
 [[ 8  8 13 11]
 [ 6 10  9  7]
 [10  6 11  3]
 [ 1  3  7  3]]
Train  loss=1.2117 acc=0.5183 f1=0.4976 | Val loss=2.1035 acc=0.2759 f1=0.2643

Epoch 7/25


    t_loss=1.1587 | F1(macro)=0.5042 | Acc=0.5075


Confusion matrix:
 [[ 6  8 17  9]
 [ 3  8 13  8]
 [ 6  8 10  6]
 [ 1  2  6  5]]
Train  loss=1.1587 acc=0.5075 f1=0.5042 | Val loss=2.0751 acc=0.2500 f1=0.2479

Epoch 8/25


    t_loss=1.0948 | F1(macro)=0.5444 | Acc=0.5591


Confusion matrix:
 [[ 5  7  5 23]
 [ 3 10  2 17]
 [ 5 11  4 10]
 [ 0  1  2 11]]
Train  loss=1.0948 acc=0.5591 f1=0.5444 | Val loss=2.0950 acc=0.2586 f1=0.2490

Epoch 9/25


    t_loss=1.0051 | F1(macro)=0.5809 | Acc=0.5935


Confusion matrix:
 [[ 8  2  8 22]
 [ 4  5  2 21]
 [ 7  6  9  8]
 [ 3  0  2  9]]
Train  loss=1.0051 acc=0.5935 f1=0.5809 | Val loss=2.0188 acc=0.2672 f1=0.2691

Epoch 10/25


    t_loss=1.0186 | F1(macro)=0.5805 | Acc=0.5914


Confusion matrix:
 [[ 8  7 12 13]
 [ 6  8  7 11]
 [ 9  3 10  8]
 [ 3  2  5  4]]
Train  loss=1.0186 acc=0.5914 f1=0.5805 | Val loss=2.0840 acc=0.2586 f1=0.2557

Epoch 11/25


    t_loss=0.9892 | F1(macro)=0.5424 | Acc=0.5591


Confusion matrix:
 [[18 11  5  6]
 [11 12  5  4]
 [13 11  4  2]
 [ 4  3  4  3]]
Train  loss=0.9892 acc=0.5591 f1=0.5424 | Val loss=1.9630 acc=0.3190 f1=0.2850

Epoch 12/25


    t_loss=0.8538 | F1(macro)=0.6436 | Acc=0.6559


Confusion matrix:
 [[19  8  7  6]
 [15  6  9  2]
 [13  7  8  2]
 [ 6  0  5  3]]
Train  loss=0.8538 acc=0.6559 f1=0.6436 | Val loss=2.0911 acc=0.3103 f1=0.2821

Epoch 13/25


    t_loss=0.8766 | F1(macro)=0.6561 | Acc=0.6645


Confusion matrix:
 [[16  8  4 12]
 [14  9  5  4]
 [15 10  4  1]
 [ 6  2  5  1]]
Train  loss=0.8766 acc=0.6645 f1=0.6561 | Val loss=1.9273 acc=0.2586 f1=0.2190

Epoch 14/25


    t_loss=0.9165 | F1(macro)=0.6218 | Acc=0.6280


Confusion matrix:
 [[13  2 16  9]
 [11 10 10  1]
 [10  6 11  3]
 [ 5  1  8  0]]
Train  loss=0.9165 acc=0.6280 f1=0.6218 | Val loss=1.9746 acc=0.2931 f1=0.2537

Epoch 15/25


    t_loss=0.8655 | F1(macro)=0.6947 | Acc=0.6989


Confusion matrix:
 [[16  7  8  9]
 [13 11  6  2]
 [13  4  8  5]
 [ 3  3  6  2]]
Train  loss=0.8655 acc=0.6989 f1=0.6947 | Val loss=1.9049 acc=0.3190 f1=0.2908

Epoch 16/25


    t_loss=0.7743 | F1(macro)=0.7149 | Acc=0.7247


Confusion matrix:
 [[12  6 13  9]
 [ 9 10 11  2]
 [ 9  7  9  5]
 [ 2  2  8  2]]
Train  loss=0.7743 acc=0.7247 f1=0.7149 | Val loss=1.9185 acc=0.2845 f1=0.2657

Epoch 17/25


    t_loss=0.7913 | F1(macro)=0.7124 | Acc=0.7140


Confusion matrix:
 [[10  8 12 10]
 [11 11  6  4]
 [10  8  7  5]
 [ 4  2  5  3]]
Train  loss=0.7913 acc=0.7140 f1=0.7124 | Val loss=2.0169 acc=0.2672 f1=0.2568

Epoch 18/25


    t_loss=0.8299 | F1(macro)=0.6952 | Acc=0.6989


Confusion matrix:
 [[11  6 14  9]
 [ 9 12 10  1]
 [ 9  7  8  6]
 [ 2  3  7  2]]
Train  loss=0.8299 acc=0.6989 f1=0.6952 | Val loss=1.9712 acc=0.2845 f1=0.2667

Epoch 19/25


    t_loss=0.7583 | F1(macro)=0.7454 | Acc=0.7505


Confusion matrix:
 [[14  4 15  7]
 [14 11  6  1]
 [11  7  8  4]
 [ 3  2  7  2]]
Train  loss=0.7583 acc=0.7505 f1=0.7454 | Val loss=2.0879 acc=0.3017 f1=0.2799

Epoch 20/25


    t_loss=0.7557 | F1(macro)=0.7276 | Acc=0.7376


Confusion matrix:
 [[18  9  4  9]
 [18  8  4  2]
 [18  2  3  7]
 [ 9  2  1  2]]
Train  loss=0.7557 acc=0.7376 f1=0.7276 | Val loss=2.0119 acc=0.2672 f1=0.2280

Epoch 21/25


    t_loss=0.8142 | F1(macro)=0.7567 | Acc=0.7591


Confusion matrix:
 [[19  4 13  4]
 [17  5  9  1]
 [13  6  8  3]
 [ 7  0  6  1]]
Train  loss=0.8142 acc=0.7591 f1=0.7567 | Val loss=2.0707 acc=0.2845 f1=0.2345

Epoch 22/25


    t_loss=0.7190 | F1(macro)=0.7684 | Acc=0.7785


Confusion matrix:
 [[16  4 15  5]
 [11 10 10  1]
 [11  5 10  4]
 [ 5  1  7  1]]
Train  loss=0.7190 acc=0.7785 f1=0.7684 | Val loss=1.9897 acc=0.3190 f1=0.2820

Epoch 23/25


    t_loss=0.7697 | F1(macro)=0.7432 | Acc=0.7462


Confusion matrix:
 [[17  7 11  5]
 [15 11  5  1]
 [12  8  7  3]
 [ 6  1  5  2]]
Train  loss=0.7697 acc=0.7462 f1=0.7432 | Val loss=1.9873 acc=0.3190 f1=0.2880

Epoch 24/25


    t_loss=0.7041 | F1(macro)=0.8114 | Acc=0.8129


Confusion matrix:
 [[15  4 15  6]
 [13  8  8  3]
 [12  4  8  6]
 [ 6  0  7  1]]
Train  loss=0.7041 acc=0.8129 f1=0.8114 | Val loss=2.0108 acc=0.2759 f1=0.2460

Epoch 25/25


    t_loss=0.7690 | F1(macro)=0.7654 | Acc=0.7699


Confusion matrix:
 [[14  5 16  5]
 [11  8 11  2]
 [12  5  8  5]
 [ 5  0  8  1]]
Train  loss=0.7690 acc=0.7699 f1=0.7654 | Val loss=1.9742 acc=0.2672 f1=0.2387
Restored best weights for fold 1 (F1=0.3158)

========== Fold 2 ==========

Epoch 1/25


    t_loss=2.2116 | F1(macro)=0.3268 | Acc=0.3355


Confusion matrix:
 [[14  1  9 17]
 [12  5  6  8]
 [12  3  5 10]
 [ 4  0  2  8]]
Train  loss=2.2116 acc=0.3355 f1=0.3268 | Val loss=2.5172 acc=0.2759 f1=0.2651
  🔥 New best F1: 0.2651 – model saved.

Epoch 2/25


    t_loss=1.6703 | F1(macro)=0.3644 | Acc=0.3720


Confusion matrix:
 [[11  2 18 10]
 [ 7  8  8  8]
 [ 6  5 15  4]
 [ 2  0  8  4]]
Train  loss=1.6703 acc=0.3720 f1=0.3644 | Val loss=2.1961 acc=0.3276 f1=0.3140
  🔥 New best F1: 0.3140 – model saved.

Epoch 3/25


    t_loss=1.4380 | F1(macro)=0.3985 | Acc=0.4065


Confusion matrix:
 [[11  9 10 11]
 [ 8  9  4 10]
 [ 6  8 10  6]
 [ 3  1  5  5]]
Train  loss=1.4380 acc=0.4065 f1=0.3985 | Val loss=2.0213 acc=0.3017 f1=0.2964

Epoch 4/25


    t_loss=1.3232 | F1(macro)=0.4263 | Acc=0.4366


Confusion matrix:
 [[13  7  8 13]
 [ 6 12  4  9]
 [ 7  7  9  7]
 [ 4  1  2  7]]
Train  loss=1.3232 acc=0.4366 f1=0.4263 | Val loss=1.9433 acc=0.3534 f1=0.3499
  🔥 New best F1: 0.3499 – model saved.

Epoch 5/25


    t_loss=1.2567 | F1(macro)=0.4923 | Acc=0.5054


Confusion matrix:
 [[ 9 21  8  3]
 [ 9 17  4  1]
 [ 5 20  3  2]
 [ 4  4  4  2]]
Train  loss=1.2567 acc=0.5054 f1=0.4923 | Val loss=2.0151 acc=0.2672 f1=0.2336

Epoch 6/25


    t_loss=1.1459 | F1(macro)=0.4782 | Acc=0.4989


Confusion matrix:
 [[ 9  6 16 10]
 [10  9  7  5]
 [10  6  7  7]
 [ 3  1  4  6]]
Train  loss=1.1459 acc=0.4989 f1=0.4782 | Val loss=1.8366 acc=0.2672 f1=0.2727

Epoch 7/25


    t_loss=1.2377 | F1(macro)=0.4612 | Acc=0.4753


Confusion matrix:
 [[ 6  5 15 15]
 [ 4  7 11  9]
 [ 2  7 12  9]
 [ 2  1  5  6]]
Train  loss=1.2377 acc=0.4753 f1=0.4612 | Val loss=1.9078 acc=0.2672 f1=0.2620

Epoch 8/25


    t_loss=1.1051 | F1(macro)=0.5356 | Acc=0.5484


Confusion matrix:
 [[ 7 11 16  7]
 [ 5 14  9  3]
 [ 8 10 10  2]
 [ 6  1  6  1]]
Train  loss=1.1051 acc=0.5484 f1=0.5356 | Val loss=1.9400 acc=0.2759 f1=0.2457

Epoch 9/25


    t_loss=1.0216 | F1(macro)=0.5726 | Acc=0.5978


Confusion matrix:
 [[ 6  9 22  4]
 [ 3 10 14  4]
 [ 4  6 18  2]
 [ 3  2  8  1]]
Train  loss=1.0216 acc=0.5978 f1=0.5726 | Val loss=2.0897 acc=0.3017 f1=0.2567

Epoch 10/25


    t_loss=0.9647 | F1(macro)=0.6153 | Acc=0.6301


Confusion matrix:
 [[ 3  4 13 21]
 [ 6  6 10  9]
 [ 2  3  9 16]
 [ 3  1  4  6]]
Train  loss=0.9647 acc=0.6301 f1=0.6153 | Val loss=2.0846 acc=0.2069 f1=0.2076

Epoch 11/25


    t_loss=1.0028 | F1(macro)=0.6042 | Acc=0.6065


Confusion matrix:
 [[16  6 10  9]
 [ 8 10  9  4]
 [10  8  6  6]
 [ 6  1  4  3]]
Train  loss=1.0028 acc=0.6065 f1=0.6042 | Val loss=2.0043 acc=0.3017 f1=0.2806

Epoch 12/25


    t_loss=0.9502 | F1(macro)=0.6117 | Acc=0.6215


Confusion matrix:
 [[ 7  9 14 11]
 [ 5 10 11  5]
 [ 3  8 11  8]
 [ 1  1  8  4]]
Train  loss=0.9502 acc=0.6215 f1=0.6117 | Val loss=2.0007 acc=0.2759 f1=0.2681

Epoch 13/25


    t_loss=0.9027 | F1(macro)=0.6438 | Acc=0.6559


Confusion matrix:
 [[19  4  7 11]
 [17  8  2  4]
 [15  4  4  7]
 [ 5  1  2  6]]
Train  loss=0.9027 acc=0.6559 f1=0.6438 | Val loss=1.9289 acc=0.3190 f1=0.2971

Epoch 14/25


    t_loss=0.8261 | F1(macro)=0.6670 | Acc=0.6796


Confusion matrix:
 [[18  3 10 10]
 [11  8  5  7]
 [ 9  5  8  8]
 [ 2  1  7  4]]
Train  loss=0.8261 acc=0.6796 f1=0.6670 | Val loss=1.8270 acc=0.3276 f1=0.3076

Epoch 15/25


    t_loss=0.7369 | F1(macro)=0.7609 | Acc=0.7699


Confusion matrix:
 [[11 11 13  6]
 [ 7 12  6  6]
 [ 9  8  7  6]
 [ 3  2  6  3]]
Train  loss=0.7369 acc=0.7699 f1=0.7609 | Val loss=1.9662 acc=0.2845 f1=0.2705

Epoch 16/25


    t_loss=0.8386 | F1(macro)=0.6928 | Acc=0.6946


Confusion matrix:
 [[15 10 11  5]
 [ 9 10 10  2]
 [16  5  6  3]
 [ 3  2  7  2]]
Train  loss=0.8386 acc=0.6946 f1=0.6928 | Val loss=1.9965 acc=0.2845 f1=0.2608

Epoch 17/25


    t_loss=0.7772 | F1(macro)=0.7150 | Acc=0.7204


Confusion matrix:
 [[17 11  8  5]
 [13 11  5  2]
 [17  5  4  4]
 [ 3  3  5  3]]
Train  loss=0.7772 acc=0.7204 f1=0.7150 | Val loss=1.9426 acc=0.3017 f1=0.2756

Epoch 18/25


    t_loss=0.8119 | F1(macro)=0.6890 | Acc=0.6968


Confusion matrix:
 [[15  9 11  6]
 [10  9 11  1]
 [13  5  8  4]
 [ 4  1  6  3]]
Train  loss=0.8119 acc=0.6968 f1=0.6890 | Val loss=1.9901 acc=0.3017 f1=0.2864

Epoch 19/25


    t_loss=0.7924 | F1(macro)=0.7333 | Acc=0.7376


Confusion matrix:
 [[17  9 11  4]
 [13  7 10  1]
 [15  6  6  3]
 [ 6  1  5  2]]
Train  loss=0.7924 acc=0.7376 f1=0.7333 | Val loss=1.9215 acc=0.2759 f1=0.2473

Epoch 20/25


    t_loss=0.7438 | F1(macro)=0.7829 | Acc=0.7871


Confusion matrix:
 [[24  8  8  1]
 [12  9  8  2]
 [20  3  4  3]
 [ 8  1  4  1]]
Train  loss=0.7438 acc=0.7871 f1=0.7829 | Val loss=1.9539 acc=0.3276 f1=0.2617

Epoch 21/25


    t_loss=0.7916 | F1(macro)=0.7413 | Acc=0.7462


Confusion matrix:
 [[26  8  4  3]
 [15 10  6  0]
 [20  4  4  2]
 [ 9  1  3  1]]
Train  loss=0.7916 acc=0.7462 f1=0.7413 | Val loss=1.9323 acc=0.3534 f1=0.2773

Epoch 22/25


    t_loss=0.7281 | F1(macro)=0.7679 | Acc=0.7699


Confusion matrix:
 [[20  6 12  3]
 [14  9  6  2]
 [19  3  5  3]
 [ 9  1  3  1]]
Train  loss=0.7281 acc=0.7699 f1=0.7679 | Val loss=1.9280 acc=0.3017 f1=0.2535

Epoch 23/25


    t_loss=0.7628 | F1(macro)=0.7498 | Acc=0.7548


Confusion matrix:
 [[23  8  5  5]
 [15 10  5  1]
 [18  7  4  1]
 [ 9  1  3  1]]
Train  loss=0.7628 acc=0.7548 f1=0.7498 | Val loss=1.9629 acc=0.3276 f1=0.2615

Epoch 24/25


    t_loss=0.7196 | F1(macro)=0.7577 | Acc=0.7634


Confusion matrix:
 [[25  7  6  3]
 [13  9  8  1]
 [18  4  4  4]
 [ 9  1  3  1]]
Train  loss=0.7196 acc=0.7634 f1=0.7577 | Val loss=1.8836 acc=0.3362 f1=0.2654

Epoch 25/25


    t_loss=0.7174 | F1(macro)=0.7599 | Acc=0.7699


Confusion matrix:
 [[21  6  8  6]
 [14  8  7  2]
 [17  3  5  5]
 [ 8  1  4  1]]
Train  loss=0.7174 acc=0.7699 f1=0.7599 | Val loss=1.9211 acc=0.3017 f1=0.2497
Restored best weights for fold 2 (F1=0.3499)

========== Fold 3 ==========

Epoch 1/25


    t_loss=2.2071 | F1(macro)=0.3256 | Acc=0.3355


Confusion matrix:
 [[ 4  6  8 23]
 [ 4  7  8 12]
 [ 2  4  7 17]
 [ 2  3  2  7]]
Train  loss=2.2071 acc=0.3355 f1=0.3256 | Val loss=2.5830 acc=0.2155 f1=0.2179
  🔥 New best F1: 0.2179 – model saved.

Epoch 2/25


    t_loss=1.6023 | F1(macro)=0.3904 | Acc=0.4172


Confusion matrix:
 [[13 10  5 13]
 [ 5 12  6  8]
 [ 9  9  1 11]
 [ 3  2  3  6]]
Train  loss=1.6023 acc=0.4172 f1=0.3904 | Val loss=1.8859 acc=0.2759 f1=0.2541
  🔥 New best F1: 0.2541 – model saved.

Epoch 3/25


    t_loss=1.4037 | F1(macro)=0.4107 | Acc=0.4258


Confusion matrix:
 [[ 5 23  3 10]
 [ 2 20  3  6]
 [ 3 14  4  9]
 [ 1  5  0  8]]
Train  loss=1.4037 acc=0.4258 f1=0.4107 | Val loss=2.0408 acc=0.3190 f1=0.2907
  🔥 New best F1: 0.2907 – model saved.

Epoch 4/25


    t_loss=1.3638 | F1(macro)=0.3946 | Acc=0.4151


Confusion matrix:
 [[12  6  6 17]
 [ 8 10  4  9]
 [ 9  4  1 16]
 [ 4  1  1  8]]
Train  loss=1.3638 acc=0.4151 f1=0.3946 | Val loss=2.1363 acc=0.2672 f1=0.2516

Epoch 5/25


    t_loss=1.2505 | F1(macro)=0.4391 | Acc=0.4645


Confusion matrix:
 [[23  4  5  9]
 [14  9  2  6]
 [ 9  6  1 14]
 [ 5  2  0  7]]
Train  loss=1.2505 acc=0.4645 f1=0.4391 | Val loss=1.6522 acc=0.3448 f1=0.2947
  🔥 New best F1: 0.2947 – model saved.

Epoch 6/25


    t_loss=1.1801 | F1(macro)=0.4509 | Acc=0.4796


Confusion matrix:
 [[14  1  6 20]
 [17  3  3  8]
 [ 6  1  4 19]
 [ 7  0  0  7]]
Train  loss=1.1801 acc=0.4796 f1=0.4509 | Val loss=1.8552 acc=0.2414 f1=0.2220

Epoch 7/25


    t_loss=1.2064 | F1(macro)=0.4569 | Acc=0.4667


Confusion matrix:
 [[13  5 14  9]
 [11  6 10  4]
 [11  1  9  9]
 [ 4  0  2  8]]
Train  loss=1.2064 acc=0.4667 f1=0.4569 | Val loss=1.6229 acc=0.3103 f1=0.3112
  🔥 New best F1: 0.3112 – model saved.

Epoch 8/25


    t_loss=1.0680 | F1(macro)=0.5157 | Acc=0.5376


Confusion matrix:
 [[20  3  7 11]
 [19  5  4  3]
 [12  1  9  8]
 [10  0  0  4]]
Train  loss=1.0680 acc=0.5376 f1=0.5157 | Val loss=1.7575 acc=0.3276 f1=0.3005

Epoch 9/25


    t_loss=1.0447 | F1(macro)=0.5552 | Acc=0.5720


Confusion matrix:
 [[27  2  7  5]
 [19  4  6  2]
 [16  0  8  6]
 [ 7  1  3  3]]
Train  loss=1.0447 acc=0.5720 f1=0.5552 | Val loss=1.8347 acc=0.3621 f1=0.2994

Epoch 10/25


    t_loss=1.0336 | F1(macro)=0.5690 | Acc=0.5828


Confusion matrix:
 [[24  3  7  7]
 [17  8  1  5]
 [12  2  5 11]
 [ 6  0  1  7]]
Train  loss=1.0336 acc=0.5828 f1=0.5690 | Val loss=1.7272 acc=0.3793 f1=0.3473
  🔥 New best F1: 0.3473 – model saved.

Epoch 11/25


    t_loss=1.0060 | F1(macro)=0.5851 | Acc=0.5935


Confusion matrix:
 [[22  6  7  6]
 [17  6  6  2]
 [14  2  2 12]
 [ 5  1  4  4]]
Train  loss=1.0060 acc=0.5935 f1=0.5851 | Val loss=1.7996 acc=0.2931 f1=0.2494

Epoch 12/25


    t_loss=0.8034 | F1(macro)=0.6359 | Acc=0.6559


Confusion matrix:
 [[17  6 10  8]
 [11  9  5  6]
 [ 8  3  5 14]
 [ 3  1  3  7]]
Train  loss=0.8034 acc=0.6559 f1=0.6359 | Val loss=1.7347 acc=0.3276 f1=0.3148

Epoch 13/25


    t_loss=0.9263 | F1(macro)=0.6560 | Acc=0.6602


Confusion matrix:
 [[20  2 13  6]
 [18  3  5  5]
 [ 8  1 10 11]
 [ 9  0  2  3]]
Train  loss=0.9263 acc=0.6602 f1=0.6560 | Val loss=1.8870 acc=0.3103 f1=0.2665

Epoch 14/25


    t_loss=0.8793 | F1(macro)=0.6612 | Acc=0.6710


Confusion matrix:
 [[ 9  6 18  8]
 [11  9  6  5]
 [10  4 12  4]
 [ 6  2  2  4]]
Train  loss=0.8793 acc=0.6710 f1=0.6612 | Val loss=1.7116 acc=0.2931 f1=0.2904

Epoch 15/25


    t_loss=0.8249 | F1(macro)=0.6844 | Acc=0.6925


Confusion matrix:
 [[16  6 10  9]
 [15  8  4  4]
 [ 8  3  6 13]
 [ 4  0  2  8]]
Train  loss=0.8249 acc=0.6925 f1=0.6844 | Val loss=1.8001 acc=0.3276 f1=0.3196

Epoch 16/25


    t_loss=0.7968 | F1(macro)=0.7083 | Acc=0.7161


Confusion matrix:
 [[13  5 10 13]
 [14  8  3  6]
 [ 9  2  6 13]
 [ 6  1  2  5]]
Train  loss=0.7968 acc=0.7161 f1=0.7083 | Val loss=1.8355 acc=0.2759 f1=0.2713

Epoch 17/25


    t_loss=0.7883 | F1(macro)=0.7117 | Acc=0.7247


Confusion matrix:
 [[12  7  9 13]
 [10 11  3  7]
 [ 6  5  6 13]
 [ 5  1  1  7]]
Train  loss=0.7883 acc=0.7247 f1=0.7117 | Val loss=1.8114 acc=0.3103 f1=0.3071

Epoch 18/25


    t_loss=0.7634 | F1(macro)=0.7181 | Acc=0.7312


Confusion matrix:
 [[17  6  9  9]
 [15  8  4  4]
 [ 8  4  7 11]
 [ 6  1  2  5]]
Train  loss=0.7634 acc=0.7312 f1=0.7181 | Val loss=1.7578 acc=0.3190 f1=0.3031

Epoch 19/25


    t_loss=0.7550 | F1(macro)=0.7209 | Acc=0.7269


Confusion matrix:
 [[18  5 10  8]
 [14 10  4  3]
 [12  5  6  7]
 [ 5  1  1  7]]
Train  loss=0.7550 acc=0.7269 f1=0.7209 | Val loss=1.7480 acc=0.3534 f1=0.3447

Epoch 20/25


    t_loss=0.7671 | F1(macro)=0.7499 | Acc=0.7527


Confusion matrix:
 [[21  5  7  8]
 [15  8  2  6]
 [10  5  6  9]
 [ 6  1  2  5]]
Train  loss=0.7671 acc=0.7527 f1=0.7499 | Val loss=1.8068 acc=0.3448 f1=0.3163

Epoch 21/25


    t_loss=0.7509 | F1(macro)=0.7631 | Acc=0.7634


Confusion matrix:
 [[17  4 10 10]
 [12  9  4  6]
 [ 9  4  6 11]
 [ 6  1  2  5]]
Train  loss=0.7509 acc=0.7634 f1=0.7631 | Val loss=1.7985 acc=0.3190 f1=0.3039

Epoch 22/25


    t_loss=0.7577 | F1(macro)=0.7535 | Acc=0.7591


Confusion matrix:
 [[20  4 13  4]
 [17  6  5  3]
 [14  3  8  5]
 [ 7  1  2  4]]
Train  loss=0.7577 acc=0.7591 f1=0.7535 | Val loss=1.8992 acc=0.3276 f1=0.3033

Epoch 23/25


    t_loss=0.7392 | F1(macro)=0.7807 | Acc=0.7871


Confusion matrix:
 [[19  3 11  8]
 [14  9  4  4]
 [11  3  6 10]
 [ 7  1  2  4]]
Train  loss=0.7392 acc=0.7871 f1=0.7807 | Val loss=1.7938 acc=0.3276 f1=0.3056

Epoch 24/25


    t_loss=0.7118 | F1(macro)=0.7549 | Acc=0.7613


Confusion matrix:
 [[22  7  6  6]
 [16 10  2  3]
 [12  3  6  9]
 [ 6  1  2  5]]
Train  loss=0.7118 acc=0.7613 f1=0.7549 | Val loss=1.7634 acc=0.3707 f1=0.3423

Epoch 25/25


    t_loss=0.6614 | F1(macro)=0.8303 | Acc=0.8387


Confusion matrix:
 [[18  3 16  4]
 [13  8  8  2]
 [ 9  3  9  9]
 [ 6  1  2  5]]
Train  loss=0.6614 acc=0.8387 f1=0.8303 | Val loss=1.8115 acc=0.3448 f1=0.3332
Restored best weights for fold 3 (F1=0.3473)

========== Fold 4 ==========

Epoch 1/25


    t_loss=2.2307 | F1(macro)=0.3134 | Acc=0.3290


Confusion matrix:
 [[21  2 12  6]
 [13  6  5  8]
 [16  2  5  7]
 [ 2  1  6  4]]
Train  loss=2.2307 acc=0.3290 f1=0.3134 | Val loss=2.1668 acc=0.3103 f1=0.2784
  🔥 New best F1: 0.2784 – model saved.

Epoch 2/25


    t_loss=1.6618 | F1(macro)=0.3671 | Acc=0.3785


Confusion matrix:
 [[ 7  3 10 21]
 [ 7  6  8 11]
 [ 5  1  8 16]
 [ 2  1  2  8]]
Train  loss=1.6618 acc=0.3785 f1=0.3671 | Val loss=2.2782 acc=0.2500 f1=0.2532

Epoch 3/25


    t_loss=1.5567 | F1(macro)=0.3645 | Acc=0.3720


Confusion matrix:
 [[ 5 14  9 13]
 [ 6 11 10  5]
 [ 5  7  8 10]
 [ 2  2  3  6]]
Train  loss=1.5567 acc=0.3720 f1=0.3645 | Val loss=1.9587 acc=0.2586 f1=0.2562

Epoch 4/25


    t_loss=1.3791 | F1(macro)=0.3962 | Acc=0.4172


Confusion matrix:
 [[ 9  7  8 17]
 [ 7  5  5 15]
 [ 8  2  2 18]
 [ 1  1  1 10]]
Train  loss=1.3791 acc=0.4172 f1=0.3962 | Val loss=2.0387 acc=0.2241 f1=0.2116

Epoch 5/25


    t_loss=1.1971 | F1(macro)=0.4949 | Acc=0.5054


Confusion matrix:
 [[ 8  8 17  8]
 [ 4 10 12  6]
 [10  4 10  6]
 [ 3  2  1  7]]
Train  loss=1.1971 acc=0.5054 f1=0.4949 | Val loss=1.8443 acc=0.3017 f1=0.3088
  🔥 New best F1: 0.3088 – model saved.

Epoch 6/25


    t_loss=1.2111 | F1(macro)=0.4856 | Acc=0.4946


Confusion matrix:
 [[14  7 13  7]
 [12 12  3  5]
 [11  4  8  7]
 [ 4  1  1  7]]
Train  loss=1.2111 acc=0.4946 f1=0.4856 | Val loss=1.8127 acc=0.3534 f1=0.3550
  🔥 New best F1: 0.3550 – model saved.

Epoch 7/25


    t_loss=1.2177 | F1(macro)=0.4864 | Acc=0.4968


Confusion matrix:
 [[12 10 11  8]
 [ 5 14  6  7]
 [15  5  7  3]
 [ 4  3  1  5]]
Train  loss=1.2177 acc=0.4968 f1=0.4864 | Val loss=1.8003 acc=0.3276 f1=0.3204

Epoch 8/25


    t_loss=1.1402 | F1(macro)=0.5114 | Acc=0.5226


Confusion matrix:
 [[ 4  8 16 13]
 [ 3  9 11  9]
 [ 5  5 11  9]
 [ 1  2  3  7]]
Train  loss=1.1402 acc=0.5226 f1=0.5114 | Val loss=1.9207 acc=0.2672 f1=0.2635

Epoch 9/25


    t_loss=1.0524 | F1(macro)=0.5790 | Acc=0.5914


Confusion matrix:
 [[13  7 14  7]
 [11  8  9  4]
 [11  6 10  3]
 [ 6  1  3  3]]
Train  loss=1.0524 acc=0.5914 f1=0.5790 | Val loss=1.7709 acc=0.2931 f1=0.2791

Epoch 10/25


    t_loss=1.0126 | F1(macro)=0.5909 | Acc=0.6022


Confusion matrix:
 [[11  6  6 18]
 [ 9  9  4 10]
 [12  3  5 10]
 [ 3  1  3  6]]
Train  loss=1.0126 acc=0.6022 f1=0.5909 | Val loss=2.1427 acc=0.2672 f1=0.2653

Epoch 11/25


    t_loss=0.9811 | F1(macro)=0.6263 | Acc=0.6280


Confusion matrix:
 [[ 9  7 18  7]
 [ 4 14 10  4]
 [10  6  8  6]
 [ 2  3  4  4]]
Train  loss=0.9811 acc=0.6280 f1=0.6263 | Val loss=1.9293 acc=0.3017 f1=0.2971

Epoch 12/25


    t_loss=1.0022 | F1(macro)=0.5823 | Acc=0.5892


Confusion matrix:
 [[18  7 10  6]
 [10 13  2  7]
 [13  9  4  4]
 [ 4  2  2  5]]
Train  loss=1.0022 acc=0.5892 f1=0.5823 | Val loss=1.9021 acc=0.3448 f1=0.3209

Epoch 13/25


    t_loss=0.9269 | F1(macro)=0.6274 | Acc=0.6301


Confusion matrix:
 [[ 5 10 16 10]
 [ 2 14  7  9]
 [ 8  8  8  6]
 [ 3  2  2  6]]
Train  loss=0.9269 acc=0.6301 f1=0.6274 | Val loss=1.9559 acc=0.2845 f1=0.2801

Epoch 14/25


    t_loss=0.8676 | F1(macro)=0.6949 | Acc=0.7011


Confusion matrix:
 [[ 7 12 12 10]
 [ 4 13  7  8]
 [ 6 10 11  3]
 [ 2  2  3  6]]
Train  loss=0.8676 acc=0.7011 f1=0.6949 | Val loss=2.0460 acc=0.3190 f1=0.3148

Epoch 15/25


    t_loss=0.8073 | F1(macro)=0.7076 | Acc=0.7161


Confusion matrix:
 [[13  8 16  4]
 [ 9 12  8  3]
 [10  9  8  3]
 [ 5  1  2  5]]
Train  loss=0.8073 acc=0.7161 f1=0.7076 | Val loss=1.9440 acc=0.3276 f1=0.3319

Epoch 16/25


    t_loss=0.8297 | F1(macro)=0.6934 | Acc=0.7075


Confusion matrix:
 [[ 8 10 15  8]
 [ 4 17  4  7]
 [ 3 14  9  4]
 [ 4  1  2  6]]
Train  loss=0.8297 acc=0.7075 f1=0.6934 | Val loss=1.8951 acc=0.3448 f1=0.3355

Epoch 17/25


    t_loss=0.7791 | F1(macro)=0.7436 | Acc=0.7527


Confusion matrix:
 [[10 15  7  9]
 [ 5 21  2  4]
 [ 7 15  5  3]
 [ 4  2  2  5]]
Train  loss=0.7791 acc=0.7527 f1=0.7436 | Val loss=1.9908 acc=0.3534 f1=0.3260

Epoch 18/25


    t_loss=0.7771 | F1(macro)=0.7275 | Acc=0.7333


Confusion matrix:
 [[16 11  9  5]
 [ 8 13  6  5]
 [10 11  7  2]
 [ 5  1  2  5]]
Train  loss=0.7771 acc=0.7333 f1=0.7275 | Val loss=1.9616 acc=0.3534 f1=0.3437

Epoch 19/25


    t_loss=0.7417 | F1(macro)=0.7516 | Acc=0.7591


Confusion matrix:
 [[ 9 12 13  7]
 [ 6 13  6  7]
 [ 6 12  9  3]
 [ 7  0  1  5]]
Train  loss=0.7417 acc=0.7591 f1=0.7516 | Val loss=1.9177 acc=0.3103 f1=0.3071

Epoch 20/25


    t_loss=0.7526 | F1(macro)=0.7354 | Acc=0.7527


Confusion matrix:
 [[11 12  9  9]
 [ 6 15  4  7]
 [ 4 13  8  5]
 [ 5  1  2  5]]
Train  loss=0.7526 acc=0.7527 f1=0.7354 | Val loss=1.8936 acc=0.3362 f1=0.3244

Epoch 21/25


    t_loss=0.6954 | F1(macro)=0.7606 | Acc=0.7699


Confusion matrix:
 [[ 8 15 12  6]
 [ 5 15  7  5]
 [ 6 12 12  0]
 [ 5  1  2  5]]
Train  loss=0.6954 acc=0.7699 f1=0.7606 | Val loss=1.8937 acc=0.3448 f1=0.3430

Epoch 22/25


    t_loss=0.7721 | F1(macro)=0.7669 | Acc=0.7677


Confusion matrix:
 [[15  9 11  6]
 [11 10  5  6]
 [ 9 12  8  1]
 [ 6  0  2  5]]
Train  loss=0.7721 acc=0.7677 f1=0.7669 | Val loss=1.9277 acc=0.3276 f1=0.3229

Epoch 23/25


    t_loss=0.7336 | F1(macro)=0.7785 | Acc=0.7785


Confusion matrix:
 [[11 13 11  6]
 [ 7 13  5  7]
 [ 5 12 10  3]
 [ 7  0  1  5]]
Train  loss=0.7336 acc=0.7785 f1=0.7785 | Val loss=1.9296 acc=0.3362 f1=0.3316

Epoch 24/25


    t_loss=0.7712 | F1(macro)=0.7493 | Acc=0.7505


Confusion matrix:
 [[11 10 14  6]
 [ 7 12  6  7]
 [ 7  9 13  1]
 [ 5  1  2  5]]
Train  loss=0.7712 acc=0.7505 f1=0.7493 | Val loss=1.8968 acc=0.3534 f1=0.3493

Epoch 25/25


    t_loss=0.6761 | F1(macro)=0.7880 | Acc=0.8000


Confusion matrix:
 [[12 11 10  8]
 [ 6 15  4  7]
 [ 6 11  9  4]
 [ 4  1  2  6]]
Train  loss=0.6761 acc=0.8000 f1=0.7880 | Val loss=1.9471 acc=0.3621 f1=0.3549
Restored best weights for fold 4 (F1=0.3550)


# tf_efficientnetv2_s.in21k

In [6]:
def create_model_tf_efficientnetv2_s(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4 # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 10
    EPOCHS_STAGE2 = 15

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # False to disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader   = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_tf_efficientnetv2_s()

        # --- Stage 1: freeze backbone, train classifier head ---
        print("\n--- Stage 1: Training classifier head ---")

        # --- 1.1. freeze feature extractor layers ---
        for param in model.parameters():
            param.requires_grad = False

        # 2) unfreeze classifier head (EffNetV2 uses .classifier)
        for param in model.classifier.parameters():
            param.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1+1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model ---")

        # --- 2.1. unfreeze entire model ---
        for param in model.parameters():
            param.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32) # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None

        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_effv2_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)   # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"effv2_s_fold{fold}.pth")

# convnext_tiny

In [7]:
def create_model_convnext(pretrained: bool = True) -> nn.Module:
    model = timm.create_model(
        PRETRAINED_MODEL,
        pretrained=pretrained,
        num_classes=N_CLASSES,
        in_chans=4,
        drop_rate=0.3,        # Dropout
        drop_path_rate=0.1    # Stochastic depth
    ).to(device)
    return model

if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
    N_FOLDS = data.num_K_folds
    IMAGE_SIZE = data.image_size
    BATCH_SIZE = 4
    PRETRAINED_MODEL = MODEL_TO_USE.value
    N_CLASSES = 4  # number of classes in the dataset (labels)
    N_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 4
    EPOCHS_STAGE1 = 8
    EPOCHS_STAGE2 = 12

    for fold in range(N_FOLDS):
        print(f"\n========== Fold {fold} ==========")

        train_df_split = train_df[train_df["fold"] != fold].reset_index(drop=True)
        val_df_split   = train_df[train_df["fold"] == fold].reset_index(drop=True)

        train_dataset = HistologyDataset(
            df=train_df_split,
            image_size=IMAGE_SIZE,
            is_train=True,
            use_mask_crop=True
        )
        val_dataset = HistologyDataset(
            df=val_df_split,
            image_size=IMAGE_SIZE,
            is_train=False,   # Disable augmentations
            use_mask_crop=True
        )

        sampler = make_weighted_sampler(train_df_split)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            sampler=sampler,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=N_WORKERS,
            pin_memory=cuda_is_available
        )

        # --- create fresh model for this fold ---
        model = create_model_convnext()

        # --- Stage 1: freeze backbone, train classifier HEAD (ConvNeXt) ---
        print("\n--- Stage 1: Training classifier head (ConvNeXt-Tiny) ---")

        # --- 1.1. freeze feature extractor layers ---
        for p in model.parameters():
            p.requires_grad = False

        # --- 1.1. unfreeze only the classifier head (ConvNeXt uses .head) ---
        for p in model.head.parameters():
            p.requires_grad = True

        # --- 1.2. define loss, optimizer, scheduler ---
        criterion = nn.CrossEntropyLoss()
        head_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(head_params, lr=1e-3, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE1)

        # --- 1.3. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE1 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE1}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage1_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)
            print(f"Restored best Stage 1 weights for fold {fold} (F1={best_f1:.4f})")

        # --- Stage 2: unfreeze whole model, fine-tune ---
        print("\n--- Stage 2: Fine-tuning entire model (ConvNeXt-Tiny) ---")

        # --- 2.1. unfreeze entire model ---
        for p in model.parameters():
            p.requires_grad = True

        # --- 2.2. define loss, optimizer, scheduler ---
        optimizer = AdamW(model.parameters(), lr=5e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS_STAGE2)

        # --- 2.3. mild class weights ---
        class_counts = torch.tensor([445, 414, 397, 156], dtype=torch.float32)  # 445 LumB, 414 LumA, 397 Her2, 156 TN
        class_weights = (class_counts.sum() / class_counts)
        class_weights = class_weights / class_weights.mean()
        # criterion = FocalLoss(alpha=class_weights, gamma=2.0)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device), label_smoothing=0.1)

        # --- 2.4. train for several epochs ---
        best_f1 = 0.0
        best_state = None
        for epoch in range(1, EPOCHS_STAGE2 + 1):
            print(f"\nEpoch {epoch}/{EPOCHS_STAGE2}")
            train_loss, train_acc, train_f1 = train_one_epoch(
                model, train_loader, optimizer, criterion, device
            )
            val_loss, val_acc, val_f1 = validate(
                model, val_loader, criterion, device
            )
            scheduler.step()
            print(
                f"Train  loss={train_loss:.4f} acc={train_acc:.4f} f1={train_f1:.4f} | "
                f"Val loss={val_loss:.4f} acc={val_acc:.4f} f1={val_f1:.4f}"
            )
            if val_f1 > best_f1:
                best_f1 = val_f1
                best_f1_per_fold[fold] = best_f1
                best_state = deepcopy(model.state_dict())
                torch.save(best_state, f"best_convnext_stage2_fold{fold}_f1_{val_f1:.4f}.pth")
                print(f"  🔥 New best F1: {best_f1:.4f} – model saved.")

        if best_state is not None:
            model.load_state_dict(best_state)  # restore best val-F1 weights

        # --- save model for this fold ---
        torch.save(model.state_dict(), f"convnext_tiny_fold{fold}.pth")

# Model Inference with 5-Fold Ensembling

In [8]:
prefix_filename = "effv2_s" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S else "convnext_tiny" if MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY else "effb0" if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNET_B0 else "effb1"

FOLD_VAL_F1 = f"fold_val_f1_{prefix_filename}.json"

# Save best F1 per fold to JSON
with open(FOLD_VAL_F1, "w") as f:
    json.dump(best_f1_per_fold, f, indent=2)

# test_dataset = HistologyDataset(
#     df=test_df,
#     image_size=IMAGE_SIZE,
#     is_train=False,   # returns (img, sample_index)
#     use_mask_crop=True
# )
#
# test_loader = DataLoader(
#     test_dataset,
#     batch_size=BATCH_SIZE,
#     shuffle=False,
#     num_workers=N_WORKERS,
#     pin_memory=cuda_is_available
# )
#
# all_fold_probs = []   # list of arrays [N, num_classes]
# all_sample_indices = None
#
# for fold in range(N_FOLDS):
#     print(f"Inference with fold {fold} model")
#
#     # recreate model and load weights
#     if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
#         model = create_model_tf_efficientnetv2_s(pretrained=False)
#     elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
#         model = create_model_convnext(pretrained=False)
#     else:
#         model = create_efficientnet_b0_model(pretrained=False)
#     state = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
#     model.load_state_dict(state)
#     model.eval()
#
#     fold_probs = []
#     sample_indices_list = []
#
#     with torch.no_grad():
#         for imgs, sample_indices in test_loader:
#             imgs = imgs.to(device, non_blocking=True)
#
#             logits = model(imgs)               # [B, num_classes]
#             probs = softmax(logits, dim=1)     # [B, num_classes]
#             fold_probs.append(probs.cpu().numpy())
#
#             # collect sample indices only once
#             if all_sample_indices is None:
#                 sample_indices_list.extend(sample_indices)
#
#     fold_probs = np.concatenate(fold_probs, axis=0)  # [N, num_classes]
#     all_fold_probs.append(fold_probs)
#
#     if all_sample_indices is None:
#         all_sample_indices = sample_indices_list
#
# # average probabilities across folds
# mean_probs = np.mean(all_fold_probs, axis=0)   # [N, num_classes]
# pred_indices = mean_probs.argmax(axis=1)
#
# pred_labels = [idx2label[int(i)] for i in pred_indices]
# sample_index_with_ext = [
#     f"{si}.png" if not si.endswith(".png") else si
#     for si in all_sample_indices
# ]
#
# submission_df = pd.DataFrame({
#     "sample_index": sample_index_with_ext,
#     "label": pred_labels
# })
#
# submission_df.to_csv(f"submission_5fold_no_tta_{prefix_filename}.csv", index=False)
# print("Saved submission_5fold_no_tta.csv")
# print(submission_df.head())


In [9]:
########################################################
# ===== Inference with TTA and 5-Fold Ensembling ===== #
########################################################
all_fold_probs = []
all_sample_indices = None

test_dataset = HistologyDataset(
    df=test_df,
    image_size=IMAGE_SIZE,
    is_train=False,   # deterministic, returns (img, sample_index)
    use_mask_crop=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=1,               # per-image TTA
    shuffle=False,
    num_workers=N_WORKERS,
    pin_memory=cuda_is_available
)

if os.path.exists(FOLD_VAL_F1):
    with open(FOLD_VAL_F1, "r") as f:
        best_f1_per_fold = json.load(f)
    val_f1_per_fold = np.array([best_f1_per_fold[str(k)] for k in range(N_FOLDS)])
    # Normalize to get weights that sum to 1
    fold_weights = val_f1_per_fold / val_f1_per_fold.sum()
else:
    # fallback: uniform weights if metrics are missing
    print('Warning: fold validation F1 scores not found, using uniform weights.')
    fold_weights = np.ones(N_FOLDS, dtype=np.float32) / N_FOLDS

print("Fold weights:", fold_weights)

# -----------------------------
# 2) Accumulate weighted probs
# -----------------------------
all_probs = None
all_sample_indices = None

for fold in range(N_FOLDS):
    print(f"Inference with fold {fold} model (weight={fold_weights[fold]:.3f})")

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)

    state_dict = torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    fold_probs = []
    sample_indices_list = []

    with torch.no_grad():
        for img_tensor, sample_idx in test_loader:
            # img_tensor: [1, 4, H, W]  (RGB+mask)
            img_tensor = img_tensor.squeeze(0).to(device)  # [4, H, W]

            # -------- TTA: apply multiple augmented views [4xHxW] --------
            tta_tensors = apply_tta(img_tensor)

            # accumulate probability predictions
            probs_sum = 0
            for aug_img in tta_tensors:
                aug_img = aug_img.unsqueeze(0).to(device)  # [1, 4, H, W]
                logits = model(aug_img)
                probs = softmax(logits, dim=1)  # [1, N_CLASSES]
                probs_sum += probs[0].cpu().numpy()

            # average across TTA views
            avg_probs = probs_sum / len(tta_tensors)  # [N_CLASSES]
            fold_probs.append(avg_probs)

            # collect sample indices only once
            if all_sample_indices is None:
                sample_indices_list.append(sample_idx[0])

    fold_probs = np.vstack(fold_probs)  # [N_test, N_CLASSES]

    # initialize global probs
    if all_probs is None:
        all_probs = np.zeros_like(fold_probs, dtype=np.float32)

     # weighted accumulation
    all_probs += fold_weights[fold] * fold_probs

    if all_sample_indices is None:
        all_sample_indices = sample_indices_list

# -----------------------------
# 3) Final predictions
# -----------------------------
pred_indices = all_probs.argmax(axis=1)
pred_labels = [idx2label[int(i)] for i in pred_indices]

sample_index_with_ext = [
    f"{si}.png" if not si.endswith(".png") else si
    for si in all_sample_indices
]

submission_df = pd.DataFrame({
    "sample_index": sample_index_with_ext,
    "label": pred_labels
})
submission_df.to_csv(f"submission_5fold_tta_{prefix_filename}.csv", index=False)

print(f"Saved submission_5fold_tta_{prefix_filename}.csv")

Fold weights: [0.21212557 0.18187094 0.20153159 0.20001652 0.20445538]
Inference with fold 0 model (weight=0.212)
Inference with fold 1 model (weight=0.182)
Inference with fold 2 model (weight=0.202)
Inference with fold 3 model (weight=0.200)
Inference with fold 4 model (weight=0.204)
Saved submission_5fold_tta_effb0.csv


In [10]:
def predict_loader_with_tta(model, loader, device):
    model.eval()
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for imgs, labels in loader:  # note: here we have labels, not sample_index
            imgs = imgs.squeeze(0).to(device)  # if batch_size=1
            tta_imgs = apply_tta(imgs)         # same apply_tta as for test

            probs_sum = 0
            for aug in tta_imgs:
                aug = aug.unsqueeze(0).to(device)
                logits = model(aug)
                probs = softmax(logits, dim=1)
                probs_sum += probs[0].cpu().numpy()

            avg_probs = probs_sum / len(tta_imgs)
            all_probs.append(avg_probs)
            all_targets.append(labels.item())

    all_probs = np.vstack(all_probs)
    all_targets = np.array(all_targets)
    pred_indices = all_probs.argmax(axis=1)

    macro_f1 = f1_score(all_targets, pred_indices, average="macro")
    return macro_f1

fold_f1s = []

for fold in range(N_FOLDS):
    print(f"OOF eval for fold {fold}")

    # build val_df_split for that fold
    val_df_split = train_df[train_df["fold"] == fold].reset_index(drop=True)
    val_dataset = HistologyDataset(
        df=val_df_split,
        image_size=IMAGE_SIZE,
        is_train=False,   # Disable augmentations
        use_mask_crop=True
    )
    val_loader  = DataLoader(val_dataset, batch_size=1, shuffle=False,
                             num_workers=N_WORKERS, pin_memory=cuda_is_available)

    if MODEL_TO_USE == PreTrainedArchitectures.EFFICIENTNETV2_S:
        model = create_model_tf_efficientnetv2_s(pretrained=False)
    elif MODEL_TO_USE == PreTrainedArchitectures.CONVNEXT_TINY:
        model = create_model_convnext(pretrained=False)
    else:
        model = create_efficientnet_b0_model(pretrained=False)
    model.load_state_dict(torch.load(f"{prefix_filename}_fold{fold}.pth", map_location=device))

    f1 = predict_loader_with_tta(model, val_loader, device)
    fold_f1s.append(f1)
    print("Fold F1 (OOF, with TTA):", f1)

print("Mean OOF F1:", np.mean(fold_f1s))


OOF eval for fold 0
Fold F1 (OOF, with TTA): 0.37354156370728187
OOF eval for fold 1
Fold F1 (OOF, with TTA): 0.3135368297335312
OOF eval for fold 2
Fold F1 (OOF, with TTA): 0.32859790038254644
OOF eval for fold 3
Fold F1 (OOF, with TTA): 0.3284818018860572
OOF eval for fold 4
Fold F1 (OOF, with TTA): 0.3427172001828327
Mean OOF F1: 0.33737505917844984
